# 'study_prefix' should be a string at the start of each table. We'll use this
# to clean up queries, so it should be unique. Name your tables in the following
# format: [study_prefix]__[table_name]. It should probably, but not necessarily,
# be the same name as the folder the study definition is in.
study_prefix = "irae"


# The following section describes all tables that should be generated directly
# from SQL files.

[file_config]

# 'file_names' defines a list of files to execute, in order, in this folder.
# Three file types are supported:
#   - Raw SQL files
#   - Python files, which should contain a class that is based off of
#       BaseTableBuilder (or a derivative) from builders/base_table_builder.py
#   - TOML files, which provide a set of configuration params to a workflow
# These files will be executed in the order provided.

file_names = [
'athena/irae__include_study_period.sql',
'athena/irae__include_age_at_visit.sql',
'athena/irae__include_enc_class.sql',
'athena/irae__include_gender.sql',
'athena/irae__include_race.sql',
'athena/irae__cohort_study_population.sql',
'athena/irae__cohort_study_population_dx.sql',
'athena/irae__cohort_study_population_rx.sql',
'athena/irae__cohort_study_population_lab.sql',
'athena/irae__cohort_study_population_doc.sql',
'athena/irae__transplant_kidney.sql',
'athena/irae__transplant_solid_organ.sql',
'athena/irae__transplant_recipient.sql',
'athena/irae__transplant.sql',
'athena/irae__surgery_major.sql',
'athena/irae__surgery_nephrectomy_sct.sql',
'athena/irae__surgery_nephrectomy_icd10.sql',
'athena/irae__surgery.sql',
'athena/irae__dx_autoimmune_inflammatory.sql',
'athena/irae__dx_autoimmune_ibd.sql',
'athena/irae__dx_autoimmune_crohns.sql',
'athena/irae__dx_autoimmune_arthritis_ra.sql',
'athena/irae__dx_autoimmune_arthritis_disorders.sql',
'athena/irae__dx_autoimmune_lupus.sql',
'athena/irae__dx_autoimmune.sql',
'athena/irae__dx_cancer_malignant_melanoma_sct.sql',
'athena/irae__dx_cancer_malignant_melanoma_icd10.sql',
'athena/irae__dx_cancer.sql',
'athena/irae__dx_diabetes_disorder.sql',
'athena/irae__dx_diabetes_preexisting.sql',
'athena/irae__dx_diabetes_complications.sql',
'athena/irae__dx_diabetes_td2_related_dx.sql',
'athena/irae__dx_diabetes.sql',
'athena/irae__dx_heart_cardiomyopathy.sql',
'athena/irae__dx_heart_attack.sql',
'athena/irae__dx_heart_failure.sql',
'athena/irae__dx_heart_cohort.sql',
'athena/irae__dx_heart.sql',
'athena/irae__dx_htn_essential.sql',
'athena/irae__dx_htn_any.sql',
'athena/irae__dx_htn.sql',
'athena/irae__dx_compromised_immunocompromised.sql',
'athena/irae__dx_compromised_immunocompromising.sql',
'athena/irae__dx_compromised.sql',
'athena/irae__dx_infection_bacterial.sql',
'athena/irae__dx_infection_pna.sql',
'athena/irae__dx_infection_cmv_icd10.sql',
'athena/irae__dx_infection_cmv_sct.sql',
'athena/irae__dx_infection_rsv.sql',
'athena/irae__dx_infection_influenza.sql',
'athena/irae__dx_infection_shingles.sql',
'athena/irae__dx_infection_hepatitis_b.sql',
'athena/irae__dx_infection_hepatitis_c.sql',
'athena/irae__dx_infection.sql',
'athena/irae__dx_kidney_condition.sql',
'athena/irae__dx_kidney_renal_disease.sql',
'athena/irae__dx_kidney_esrd.sql',
'athena/irae__dx_kidney_ckd.sql',
'athena/irae__dx_kidney_diabetic_nephropathy.sql',
'athena/irae__dx_kidney_diabetic_ckd.sql',
'athena/irae__dx_kidney_hypertensive_ckd.sql',
'athena/irae__dx_kidney_nephrotic_syndrome.sql',
'athena/irae__dx_kidney.sql',
'athena/irae__rx_diabetes_drugs.sql',
'athena/irae__rx_diabetes.sql',
'athena/irae__rx_htn_drugs.sql',
'athena/irae__rx_htn.sql',
'athena/irae__rx_immunosuppressive_immunosuppressive.sql',
'athena/irae__rx_immunosuppressive_systemic_therapy.sql',
'athena/irae__rx_immunosuppressive_immune_modulators.sql',
'athena/irae__rx_immunosuppressive.sql',
'athena/irae__rx_compromised_therapies.sql',
'athena/irae__rx_compromised.sql',
'athena/irae__rx_diuretics_thiazide.sql',
'athena/irae__rx_diuretics_loop.sql',
'athena/irae__rx_diuretics_potassium.sql',
'athena/irae__rx_diuretics.sql',
'athena/irae__lab_gfr_eGFR.sql',
'athena/irae__lab_gfr.sql',
'athena/irae__lab_creatinine_serum_cr.sql',
'athena/irae__lab_creatinine_urine_cr.sql',
'athena/irae__lab_creatinine_urine_alb_cr_ratio.sql',
'athena/irae__lab_creatinine_urine_protein_cr_ratio.sql',
'athena/irae__lab_creatinine_blood_cr.sql',
'athena/irae__lab_creatinine.sql',
'athena/irae__lab_autoimmune_serum_rf.sql',
'athena/irae__lab_autoimmune_blood_esr.sql',
'athena/irae__lab_autoimmune_crp.sql',
'athena/irae__lab_autoimmune_tsh.sql',
'athena/irae__lab_autoimmune_t3.sql',
'athena/irae__lab_autoimmune_t4.sql',
'athena/irae__lab_autoimmune.sql',
'athena/irae__lab_lft_ggt.sql',
'athena/irae__lab_lft_pt_prothrombin_time.sql',
'athena/irae__lab_lft_inr.sql',
'athena/irae__lab_lft.sql',
'athena/irae__lab_panel_cbc_with_diff.sql',
'athena/irae__lab_panel_cbc.sql',
'athena/irae__lab_panel_cmp_comprehensive.sql',
'athena/irae__lab_panel_cmp.sql',
'athena/irae__lab_panel_lft_hepatic_function.sql',
'athena/irae__lab_panel_lft.sql',
'athena/irae__lab_azathioprine.sql',
'athena/irae__lab_cyclosporin.sql',
'athena/irae__lab_hemoglobin_a1c.sql',
'athena/irae__lab_sirolimus.sql',
'athena/irae__lab_azathioprine_tpmt_gene.sql',
'athena/irae__lab_cytomegalovirus.sql',
'athena/irae__lab_mycophenolate.sql',
'athena/irae__lab_tacrolimus.sql',
'athena/irae__rx_atg.sql',
'athena/irae__rx_azathioprine.sql',
'athena/irae__rx_belatacept.sql',
'athena/irae__rx_cyclosporin.sql',
'athena/irae__rx_sirolimus.sql',
'athena/irae__rx_tacrolimus.sql',
'athena/irae__lab_drug_levels.sql',
'athena/irae__rx_drug_levels.sql',
'athena/irae__cohort_dx_autoimmune_inflammatory.sql',
'athena/irae__cohort_dx_autoimmune_ibd.sql',
'athena/irae__cohort_dx_autoimmune_crohns.sql',
'athena/irae__cohort_dx_autoimmune_arthritis_ra.sql',
'athena/irae__cohort_dx_autoimmune_arthritis_disorders.sql',
'athena/irae__cohort_dx_autoimmune_lupus.sql',
'athena/irae__cohort_dx_cancer_malignant_melanoma_sct.sql',
'athena/irae__cohort_dx_cancer_malignant_melanoma_icd10.sql',
'athena/irae__cohort_dx_diabetes_disorder.sql',
'athena/irae__cohort_dx_diabetes_preexisting.sql',
'athena/irae__cohort_dx_diabetes_complications.sql',
'athena/irae__cohort_dx_diabetes_td2_related_dx.sql',
'athena/irae__cohort_dx_heart_cardiomyopathy.sql',
'athena/irae__cohort_dx_heart_attack.sql',
'athena/irae__cohort_dx_heart_failure.sql',
'athena/irae__cohort_dx_heart_cohort.sql',
'athena/irae__cohort_dx_htn_essential.sql',
'athena/irae__cohort_dx_htn_any.sql',
'athena/irae__cohort_dx_compromised_immunocompromised.sql',
'athena/irae__cohort_dx_compromised_immunocompromising.sql',
'athena/irae__cohort_dx_infection_bacterial.sql',
'athena/irae__cohort_dx_infection_pna.sql',
'athena/irae__cohort_dx_infection_cmv_icd10.sql',
'athena/irae__cohort_dx_infection_cmv_sct.sql',
'athena/irae__cohort_dx_infection_rsv.sql',
'athena/irae__cohort_dx_infection_influenza.sql',
'athena/irae__cohort_dx_infection_shingles.sql',
'athena/irae__cohort_dx_infection_hepatitis_b.sql',
'athena/irae__cohort_dx_infection_hepatitis_c.sql',
'athena/irae__cohort_dx_kidney_condition.sql',
'athena/irae__cohort_dx_kidney_renal_disease.sql',
'athena/irae__cohort_dx_kidney_esrd.sql',
'athena/irae__cohort_dx_kidney_ckd.sql',
'athena/irae__cohort_dx_kidney_diabetic_nephropathy.sql',
'athena/irae__cohort_dx_kidney_diabetic_ckd.sql',
'athena/irae__cohort_dx_kidney_hypertensive_ckd.sql',
'athena/irae__cohort_dx_kidney_nephrotic_syndrome.sql',
'athena/irae__cohort_rx_diabetes_drugs.sql',
'athena/irae__cohort_rx_htn_drugs.sql',
'athena/irae__cohort_rx_immunosuppressive_immunosuppressive.sql',
'athena/irae__cohort_rx_immunosuppressive_systemic_therapy.sql',
'athena/irae__cohort_rx_immunosuppressive_immune_modulators.sql',
'athena/irae__cohort_rx_compromised_therapies.sql',
'athena/irae__cohort_rx_diuretics_thiazide.sql',
'athena/irae__cohort_rx_diuretics_loop.sql',
'athena/irae__cohort_rx_diuretics_potassium.sql',
'athena/irae__cohort_lab_gfr_eGFR.sql',
'athena/irae__cohort_lab_creatinine_serum_cr.sql',
'athena/irae__cohort_lab_creatinine_urine_cr.sql',
'athena/irae__cohort_lab_creatinine_urine_alb_cr_ratio.sql',
'athena/irae__cohort_lab_creatinine_urine_protein_cr_ratio.sql',
'athena/irae__cohort_lab_creatinine_blood_cr.sql',
'athena/irae__cohort_lab_autoimmune_serum_rf.sql',
'athena/irae__cohort_lab_autoimmune_blood_esr.sql',
'athena/irae__cohort_lab_autoimmune_crp.sql',
'athena/irae__cohort_lab_autoimmune_tsh.sql',
'athena/irae__cohort_lab_autoimmune_t3.sql',
'athena/irae__cohort_lab_autoimmune_t4.sql',
'athena/irae__cohort_lab_lft_ggt.sql',
'athena/irae__cohort_lab_lft_pt_prothrombin_time.sql',
'athena/irae__cohort_lab_lft_inr.sql',
'athena/irae__cohort_lab_panel_cbc_with_diff.sql',
'athena/irae__cohort_lab_panel_cmp_comprehensive.sql',
'athena/irae__cohort_lab_panel_lft_hepatic_function.sql',
'athena/irae__cohort_rx_atg.sql',
'athena/irae__cohort_rx_azathioprine.sql',
'athena/irae__cohort_rx_belatacept.sql',
'athena/irae__cohort_rx_cyclosporin.sql',
'athena/irae__cohort_rx_sirolimus.sql',
'athena/irae__cohort_rx_tacrolimus.sql',
'athena/irae__cohort_rx_drug_levels.sql',
'athena/irae__cohort_lab_azathioprine.sql',
'athena/irae__cohort_lab_cyclosporin.sql',
'athena/irae__cohort_lab_hemoglobin_a1c.sql',
'athena/irae__cohort_lab_sirolimus.sql',
'athena/irae__cohort_lab_azathioprine_tpmt_gene.sql',
'athena/irae__cohort_lab_cytomegalovirus.sql',
'athena/irae__cohort_lab_mycophenolate.sql',
'athena/irae__cohort_lab_tacrolimus.sql',
'athena/irae__cohort_lab_drug_levels.sql',
'athena/irae__cube_study_population.sql',
'athena/irae__cube_study_population_dx.sql',
'athena/irae__cube_study_population_rx.sql',
'athena/irae__cube_dx_autoimmune_inflammatory.sql',
'athena/irae__cube_dx_autoimmune_ibd.sql',
'athena/irae__cube_dx_autoimmune_crohns.sql',
'athena/irae__cube_dx_autoimmune_arthritis_ra.sql',
'athena/irae__cube_dx_autoimmune_arthritis_disorders.sql',
'athena/irae__cube_dx_autoimmune_lupus.sql',
'athena/irae__cube_dx_cancer_malignant_melanoma_sct.sql',
'athena/irae__cube_dx_cancer_malignant_melanoma_icd10.sql',
'athena/irae__cube_dx_diabetes_disorder.sql',
'athena/irae__cube_dx_diabetes_preexisting.sql',
'athena/irae__cube_dx_diabetes_complications.sql',
'athena/irae__cube_dx_diabetes_td2_related_dx.sql',
'athena/irae__cube_dx_heart_cardiomyopathy.sql',
'athena/irae__cube_dx_heart_attack.sql',
'athena/irae__cube_dx_heart_failure.sql',
'athena/irae__cube_dx_heart_cohort.sql',
'athena/irae__cube_dx_htn_essential.sql',
'athena/irae__cube_dx_htn_any.sql',
'athena/irae__cube_dx_compromised_immunocompromised.sql',
'athena/irae__cube_dx_compromised_immunocompromising.sql',
'athena/irae__cube_dx_infection_bacterial.sql',
'athena/irae__cube_dx_infection_pna.sql',
'athena/irae__cube_dx_infection_cmv_icd10.sql',
'athena/irae__cube_dx_infection_cmv_sct.sql',
'athena/irae__cube_dx_infection_rsv.sql',
'athena/irae__cube_dx_infection_influenza.sql',
'athena/irae__cube_dx_infection_shingles.sql',
'athena/irae__cube_dx_infection_hepatitis_b.sql',
'athena/irae__cube_dx_infection_hepatitis_c.sql',
'athena/irae__cube_dx_kidney_condition.sql',
'athena/irae__cube_dx_kidney_renal_disease.sql',
'athena/irae__cube_dx_kidney_esrd.sql',
'athena/irae__cube_dx_kidney_ckd.sql',
'athena/irae__cube_dx_kidney_diabetic_nephropathy.sql',
'athena/irae__cube_dx_kidney_diabetic_ckd.sql',
'athena/irae__cube_dx_kidney_hypertensive_ckd.sql',
'athena/irae__cube_dx_kidney_nephrotic_syndrome.sql',
'athena/irae__cube_rx_diabetes_drugs.sql',
'athena/irae__cube_rx_htn_drugs.sql',
'athena/irae__cube_rx_immunosuppressive_immunosuppressive.sql',
'athena/irae__cube_rx_immunosuppressive_systemic_therapy.sql',
'athena/irae__cube_rx_immunosuppressive_immune_modulators.sql',
'athena/irae__cube_rx_compromised_therapies.sql',
'athena/irae__cube_rx_diuretics_thiazide.sql',
'athena/irae__cube_rx_diuretics_loop.sql',
'athena/irae__cube_rx_diuretics_potassium.sql',
'athena/irae__cube_rx_atg.sql',
'athena/irae__cube_rx_azathioprine.sql',
'athena/irae__cube_rx_belatacept.sql',
'athena/irae__cube_rx_cyclosporin.sql',
'athena/irae__cube_rx_sirolimus.sql',
'athena/irae__cube_rx_tacrolimus.sql',
'athena/irae__cube_rx_drug_levels.sql']

# The following section defines parameters related to exporting study data from
# your athena database

[export_config]

# The following tables will be exported and labeled as aggregate count tables.
# In most cases, tables should go in this list.

count_list = [
]

# Some specific tables (like those produced by data metrics) are a special type
# of tables, that are flat summary statistics tables. They should go in this list.

flat_list = [
]

# Tables that shouldn't go through aggregation, but instead contain data about
# the export itself, should be marked as metadata. Two types are expected as of this
# writing: a `meta_date` table, outlining the period over which the study extends,
# and a `meta_version` table, which should be incremented whenever the format of
# your export tables changes. See the core study for examples of how to structure
# these tables.

meta_list = [
]

# The following section is for advanced/unusual study use cases

# [options]

# If you want to override the default schema name to an explicit one, you can include
# the name of this schema here. 99% of the time, this is not the behavior you want -
# you want library data to be in the same schema as your data source, since this allows
# you to keep track of where your source data for a given study run came from.
#
# The intended use case for this is for static/slow moving data sets that are external
# to your EHR data - this is typically things like coding systems.
#
# These should be read only use cases - if you want to do additional iterations with
# the contents of one of these reference sets, do it in the study, not in the reference
# itself.

# use_dedicated_schema="alternate_schema_name"