study_prefix = "irae"

[file_config]
file_names = [
    "cumulus_library_kidney_transplant/athena/irae__include_study_period.sql",
    "cumulus_library_kidney_transplant/athena/irae__include_utilization.sql",
    "cumulus_library_kidney_transplant/athena/irae__include_age_at_visit.sql",
    "cumulus_library_kidney_transplant/athena/irae__include_enc_class.sql",
    "cumulus_library_kidney_transplant/athena/irae__include_gender.sql",
    "cumulus_library_kidney_transplant/athena/irae__include_race.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_population.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_population_dx.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_population_rx.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_population_lab.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_population_doc.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_population_proc.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_transplant_kidney.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_transplant_solid_organ.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_transplant_recipient.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_transplant.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_cancer_skin.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_cancer_sarcoma.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_cancer_squamous.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_cancer_melanoma.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_cancer.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_kidney_condition.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_kidney_renal_disease.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_kidney_esrd.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_kidney_ckd.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_kidney_dialysis.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_kidney_nephrotic_syndrome.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_kidney.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_autoimmune_inflammatory.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_autoimmune_ibd.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_autoimmune_crohns.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_autoimmune_arthritis_ra.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_autoimmune_arthritis_disorders.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_autoimmune_lupus.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_autoimmune.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_compromised_immunocompromised.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_compromised_immunocompromising.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_compromised.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_bacterial.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_pna.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_cmv_icd10.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_cmv_sct.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_rsv.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_influenza.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_shingles.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_hepatitis_b.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection_hepatitis_c.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_infection.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_heart_cardiomyopathy.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_heart_attack.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_heart_failure.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_heart_cohort.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_heart.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_htn_essential.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_htn_any.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_htn_hypertensive_ckd.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_htn.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_diabetes_disorder.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_diabetes_preexisting.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_diabetes_complications.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_diabetes_t2d_related_dx.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_diabetes_diabetic_nephropathy.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_diabetes_diabetic_ckd.sql",
    "cumulus_library_kidney_transplant/athena/irae__dx_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunosuppressive_everolimus.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunosuppressive_drugs.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunosuppressive_systemic_therapy.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunosuppressive_immune_modulators.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunosuppressive_coricosteroids_systemic.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunosuppressive.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_antibiotics_any.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_antibiotics_systemic.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_antibiotics.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunocompromised_therapies.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_immunocompromised.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_diabetes_drugs.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_htn_drugs.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_htn.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_diuretics_loop.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_diuretics_potassium.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_diuretics_thiazide.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_diuretics.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_cbc_with_diff.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_cbc.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_cmp_comprehensive.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_cmp.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_gfr_egfr.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_gfr.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_lft_function.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_lft_ggt.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_lft_pt.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_lft_inr.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_lft.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_creatinine_serum_cr.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_creatinine_urine_cr.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_creatinine_urine_alb_cr_ratio.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_creatinine_urine_protein_cr_ratio.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_creatinine_blood_cr.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_creatinine.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_autoimmune_serum_rf.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_autoimmune_blood_esr.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_autoimmune_crp.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_autoimmune_tsh.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_autoimmune_t3.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_autoimmune_t4.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_autoimmune.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_diabetes_screening.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_diabetes_glucose_test.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__proc_dialysis_services.sql",
    "cumulus_library_kidney_transplant/athena/irae__proc_dialysis.sql",
    "cumulus_library_kidney_transplant/athena/irae__proc_surgery_other_major.sql",
    "cumulus_library_kidney_transplant/athena/irae__proc_surgery.sql",
    "cumulus_library_kidney_transplant/athena/irae__doc_biopsy_kidney.sql",
    "cumulus_library_kidney_transplant/athena/irae__doc_biopsy_skin.sql",
    "cumulus_library_kidney_transplant/athena/irae__doc_biopsy_lung.sql",
    "cumulus_library_kidney_transplant/athena/irae__doc_biopsy_bone.sql",
    "cumulus_library_kidney_transplant/athena/irae__doc_biopsy_muscle.sql",
    "cumulus_library_kidney_transplant/athena/irae__doc_biopsy.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_azathioprine.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_azathioprine_tpmt_gene.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_cyclosporin.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_cytomegalovirus.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_hemoglobin_a1c.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_mycophenolate.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_sirolimus.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_tacrolimus.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_atg.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_azathioprine.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_belatacept.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_cyclosporin.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_mycophenolate.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_sirolimus.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_tacrolimus.sql",
    "cumulus_library_kidney_transplant/athena/irae__lab_custom.sql",
    "cumulus_library_kidney_transplant/athena/irae__rx_custom.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_doc_biopsy.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_autoimmune.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_cancer.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_compromised.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_heart.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_htn.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_infection.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_kidney.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_dx_transplant.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_autoimmune.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_cbc.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_cmp.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_creatinine.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_gfr.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_lft.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_proc_dialysis.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_proc_surgery.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_rx_antibiotics.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_rx_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_rx_diuretics.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_rx_htn.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_rx_immunocompromised.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_rx_immunosuppressive.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_lab_custom.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_rx_custom.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_variables.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_study_variables_wide.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_casedef_index.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_casedef_pre.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_casedef_post.sql",
    "cumulus_library_kidney_transplant/athena/irae__cohort_casedef_timeline.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_pat_study_population.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_study_population.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_pat_study_population_dx.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_pat_study_population_rx.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_pat_study_population_lab.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_pat_study_population_doc.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_pat_study_population_proc.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_rx_htn.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_gfr.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_proc_surgery.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_transplant.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_doc_biopsy.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_rx_immunocompromised.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_rx_antibiotics.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_kidney.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_cmp.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_creatinine.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_compromised.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_autoimmune.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_heart.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_lft.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_proc_dialysis.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_rx_diuretics.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_infection.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_cbc.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_rx_diabetes.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_cancer.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_autoimmune.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_rx_immunosuppressive.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_dx_htn.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_lab_custom.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_rx_custom.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_pat_study_variables.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_enc_study_variables.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_comorbidity_kidney.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_comorbidity_autoimmune.sql",
    "cumulus_library_kidney_transplant/athena/irae__count_comorbidity_diabetes.sql",
]

[export_config]
count_list = [
    "irae__count_pat_study_population",
    "irae__count_enc_study_population",
    "irae__count_pat_study_population_dx",
    "irae__count_pat_study_population_rx",
    "irae__count_pat_study_population_lab",
    "irae__count_pat_study_population_doc",
    "irae__count_pat_study_population_proc",
    "irae__count_enc_rx_htn",
    "irae__count_enc_lab_gfr",
    "irae__count_enc_dx_diabetes",
    "irae__count_enc_proc_surgery",
    "irae__count_enc_lab_diabetes",
    "irae__count_enc_dx_transplant",
    "irae__count_enc_doc_biopsy",
    "irae__count_enc_rx_immunocompromised",
    "irae__count_enc_rx_antibiotics",
    "irae__count_enc_dx_kidney",
    "irae__count_enc_lab_cmp",
    "irae__count_enc_lab_creatinine",
    "irae__count_enc_dx_compromised",
    "irae__count_enc_lab_autoimmune",
    "irae__count_enc_dx_heart",
    "irae__count_enc_lab_lft",
    "irae__count_enc_proc_dialysis",
    "irae__count_enc_rx_diuretics",
    "irae__count_enc_dx_infection",
    "irae__count_enc_lab_cbc",
    "irae__count_enc_rx_diabetes",
    "irae__count_enc_dx_cancer",
    "irae__count_enc_dx_autoimmune",
    "irae__count_enc_rx_immunosuppressive",
    "irae__count_enc_dx_htn",
    "irae__count_enc_lab_custom",
    "irae__count_enc_rx_custom",
    "irae__count_pat_study_variables",
    "irae__count_enc_study_variables",
    "irae__count_comorbidity_kidney",
    "irae__count_comorbidity_autoimmune",
    "irae__count_comorbidity_diabetes",
]
flat_list = []
meta_list = []
