study_prefix = "irae"

[file_config]
file_names = [
]

[export_config]
count_list = [
    "irae__count_enc_dx_autoimmune",
    "irae__count_enc_dx_cancer",
    "irae__count_enc_dx_compromised",
    "irae__count_enc_dx_diabetes",
    "irae__count_enc_dx_heart",
    "irae__count_enc_dx_htn",
    "irae__count_enc_dx_infection",
    "irae__count_enc_dx_kidney",
    "irae__count_enc_dx_transplant",
    "irae__count_enc_lab_autoimmune",
    "irae__count_enc_lab_cbc",
    "irae__count_enc_lab_cmp",
    "irae__count_enc_lab_creatinine",
    "irae__count_enc_lab_custom",
    "irae__count_enc_lab_diabetes",
    "irae__count_enc_lab_gfr",
    "irae__count_enc_lab_lft",
    "irae__count_enc_rx_custom",
    "irae__count_enc_rx_diabetes",
    "irae__count_enc_rx_diuretics",
    "irae__count_enc_rx_htn",
    "irae__count_enc_rx_immunocompromised",
    "irae__count_enc_rx_immunosuppressive",
    "irae__count_enc_study_population",
    "irae__count_enc_study_population_doc",
    "irae__count_enc_study_population_dx",
    "irae__count_enc_study_population_lab",
    "irae__count_enc_study_population_proc",
    "irae__count_enc_study_population_rx",
    "irae__count_pat_study_population",
]
flat_list = []
meta_list = []
