create or replace view irae__dx_kidney_esrd as select * from (values
('http://snomed.info/sct', '111411000119103', 'End stage renal disease due to hypertension (disorder)')
,('http://snomed.info/sct', '120261000119101', 'Benign hypertensive heart disease and chronic renal disease stage 5 (disorder)')
,('http://snomed.info/sct', '127991000119101', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '128001000119105', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '129161000119100', 'Chronic kidney disease stage 5 due to hypertension (disorder)')
,('http://snomed.info/sct', '140101000119109', 'Hypertension in chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '153851000119106', 'Malignant hypertensive chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '153891000119101', 'End stage renal disease on dialysis due to hypertension (disorder)')
,('http://snomed.info/sct', '236434000', 'End stage renal failure untreated by renal replacement therapy (disorder)')
,('http://snomed.info/sct', '236435004', 'End stage renal failure on dialysis (disorder)')
,('http://snomed.info/sct', '236436003', 'End stage renal failure with renal transplant (disorder)')
,('http://snomed.info/sct', '285011000119108', 'Chronic kidney disease stage 5 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '285841000119104', 'Malignant hypertensive end stage renal disease (disorder)')
,('http://snomed.info/sct', '286371000119107', 'Malignant hypertensive end stage renal disease on dialysis (disorder)')
,('http://www.ama-assn.org/go/cpt', '3066F', 'Documentation of treatment for nephropathy (eg, patient receiving dialysis, patient being treated for ESRD, CRF, ARF, or renal insufficiency, any visit to a nephrologist) (DM)')
,('http://snomed.info/sct', '368461000119103', 'Chronic kidney disease stage 5 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368471000119109', 'End stage renal disease on dialysis due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '428937001', 'Dependence on peritoneal dialysis due to end stage renal disease (finding)')
,('http://snomed.info/sct', '428982002', 'Dependence on hemodialysis due to end stage renal disease (finding)')
,('http://snomed.info/sct', '429075005', 'Dependence on dialysis due to end stage renal disease (finding)')
,('http://snomed.info/sct', '433146000', 'Chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '46177005', 'End-stage renal disease (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '585.5', 'Chronic kidney disease, Stage V')
,('http://hl7.org/fhir/sid/icd-9-cm', '585.6', 'End stage renal disease')
,('http://snomed.info/sct', '704667004', 'Hypertension concurrent and due to end stage renal disease on dialysis (disorder)')
,('http://snomed.info/sct', '707324008', 'Anemia co-occurrent and due to end stage renal disease (disorder)')
,('http://snomed.info/sct', '711000119100', 'Chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '712487000', 'End stage renal disease due to benign hypertension (disorder)')
,('http://snomed.info/sct', '714152005', 'Chronic kidney disease stage 5 on dialysis (disorder)')
,('http://snomed.info/sct', '714153000', 'Chronic kidney disease stage 5 with transplant (disorder)')
,('http://snomed.info/sct', '90761000119106', 'Chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90771000119100', 'End stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90791000119104', 'End stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://www.ama-assn.org/go/cpt', '90960', 'End-stage renal disease (ESRD) related services monthly, for patients 20 years of age and older. with 4 or more face-to-face visits by a physician or other qualified health care professional per month')
,('http://www.ama-assn.org/go/cpt', '90961', 'End-stage renal disease (ESRD) related services monthly, for patients 20 years of age and older. with 2-3 face-to-face visits by a physician or other qualified health care professional per month')
,('http://www.ama-assn.org/go/cpt', '90962', 'End-stage renal disease (ESRD) related services monthly, for patients 20 years of age and older. with 1 face-to-face visit by a physician or other qualified health care professional per month')
,('http://www.ama-assn.org/go/cpt', '90966', 'End-stage renal disease (ESRD) related services for home dialysis per full month, for patients 20 years of age and older')
,('http://www.ama-assn.org/go/cpt', '90970', 'End-stage renal disease (ESRD) related services for dialysis less than a full month of service, per day. for patients 20 years of age and older')
,('http://snomed.info/sct', '96701000119107', 'Hypertensive heart AND chronic kidney disease on dialysis (disorder)')
,('http://snomed.info/sct', '96711000119105', 'Hypertensive heart AND chronic kidney disease stage 5 (disorder)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G9231', 'Documentation of end stage renal disease (esrd), dialysis, renal transplant before or during the measurement period or pregnancy during the measurement period')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.0', 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.11', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.2', 'Hypertensive heart and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.5', 'Chronic kidney disease, stage 5')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.6', 'End stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V45.11', 'Renal dialysis status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.2', 'Dependence on renal dialysis')
) AS t (system, code, display) ;