create or replace view irae__dx_heart_attack as select * from (values
('http://snomed.info/sct', '10273003', 'Acute infarction of papillary muscle (disorder)')
,('http://snomed.info/sct', '15712841000119100', 'Acute ST segment elevation myocardial infarction of posterolateral wall (disorder)')
,('http://snomed.info/sct', '15712881000119105', 'Acute ST segment elevation myocardial infarction of anterolateral wall (disorder)')
,('http://snomed.info/sct', '15712921000119103', 'Acute ST segment elevation myocardial infarction of lateral wall (disorder)')
,('http://snomed.info/sct', '15712961000119108', 'Acute ST segment elevation myocardial infarction of anteroseptal wall (disorder)')
,('http://snomed.info/sct', '15713041000119103', 'Acute ST segment elevation myocardial infarction of posterior wall (disorder)')
,('http://snomed.info/sct', '15713081000119108', 'Acute ST segment elevation myocardial infarction due to left coronary artery occlusion (disorder)')
,('http://snomed.info/sct', '15713121000119105', 'Acute ST segment elevation myocardial infarction due to right coronary artery occlusion (disorder)')
,('http://snomed.info/sct', '15713161000119100', 'Acute ST segment elevation myocardial infarction of septum (disorder)')
,('http://snomed.info/sct', '15713201000119105', 'Acute ST segment elevation myocardial infarction of posterobasal wall (disorder)')
,('http://snomed.info/sct', '15990001', 'Acute myocardial infarction of posterolateral wall (disorder)')
,('http://snomed.info/sct', '17531000119105', 'Acute myocardial infarction due to left coronary artery occlusion (disorder)')
,('http://snomed.info/sct', '194809007', 'Acute atrial infarction (disorder)')
,('http://snomed.info/sct', '194856005', 'Subsequent myocardial infarction (disorder)')
,('http://snomed.info/sct', '194857001', 'Subsequent myocardial infarction of anterior wall (disorder)')
,('http://snomed.info/sct', '194858006', 'Subsequent myocardial infarction of inferior wall (disorder)')
,('http://snomed.info/sct', '23311000119105', 'Acute myocardial infarction due to right coronary artery occlusion (disorder)')
,('http://snomed.info/sct', '233825009', 'Acute Q wave infarction - anteroseptal (disorder)')
,('http://snomed.info/sct', '233826005', 'Acute non-Q wave infarction - anteroseptal (disorder)')
,('http://snomed.info/sct', '233827001', 'Acute Q wave infarction - anterolateral (disorder)')
,('http://snomed.info/sct', '233828006', 'Acute non-Q wave infarction - anterolateral (disorder)')
,('http://snomed.info/sct', '233829003', 'Acute Q wave infarction - inferior (disorder)')
,('http://snomed.info/sct', '233830008', 'Acute non-Q wave infarction - inferior (disorder)')
,('http://snomed.info/sct', '233831007', 'Acute Q wave infarction - inferolateral (disorder)')
,('http://snomed.info/sct', '233832000', 'Acute non-Q wave infarction - inferolateral (disorder)')
,('http://snomed.info/sct', '233833005', 'Acute Q wave infarction - lateral (disorder)')
,('http://snomed.info/sct', '233834004', 'Acute non-Q wave infarction - lateral (disorder)')
,('http://snomed.info/sct', '233835003', 'Acute widespread myocardial infarction (disorder)')
,('http://snomed.info/sct', '233836002', 'Acute Q wave infarction - widespread (disorder)')
,('http://snomed.info/sct', '233837006', 'Acute non-Q wave infarction - widespread (disorder)')
,('http://snomed.info/sct', '233838001', 'Acute posterior myocardial infarction (disorder)')
,('http://snomed.info/sct', '285981000119103', 'Acute ST segment elevation myocardial infarction involving left anterior descending coronary artery (disorder)')
,('http://snomed.info/sct', '30277009', 'Rupture of ventricle due to acute myocardial infarction (disorder)')
,('http://snomed.info/sct', '304914007', 'Acute Q wave myocardial infarction (disorder)')
,('http://snomed.info/sct', '307140009', 'Acute non-Q wave infarction (disorder)')
,('http://snomed.info/sct', '314207007', 'Non-Q wave myocardial infarction (disorder)')
,('http://snomed.info/sct', '401303003', 'Acute ST segment elevation myocardial infarction (disorder)')
,('http://snomed.info/sct', '401314000', 'Acute non-ST segment elevation myocardial infarction (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.00', 'Acute myocardial infarction of anterolateral wall, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.01', 'Acute myocardial infarction of anterolateral wall, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.10', 'Acute myocardial infarction of other anterior wall, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.11', 'Acute myocardial infarction of other anterior wall, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.20', 'Acute myocardial infarction of inferolateral wall, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.21', 'Acute myocardial infarction of inferolateral wall, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.30', 'Acute myocardial infarction of inferoposterior wall, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.31', 'Acute myocardial infarction of inferoposterior wall, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.40', 'Acute myocardial infarction of other inferior wall, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.41', 'Acute myocardial infarction of other inferior wall, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.50', 'Acute myocardial infarction of other lateral wall, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.51', 'Acute myocardial infarction of other lateral wall, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.60', 'True posterior wall infarction, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.61', 'True posterior wall infarction, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.70', 'Subendocardial infarction, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.71', 'Subendocardial infarction, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.80', 'Acute myocardial infarction of other specified sites, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.81', 'Acute myocardial infarction of other specified sites, initial episode of care')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.90', 'Acute myocardial infarction of unspecified site, episode of care unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '410.91', 'Acute myocardial infarction of unspecified site, initial episode of care')
,('http://snomed.info/sct', '52035003', 'Acute anteroapical myocardial infarction (disorder)')
,('http://snomed.info/sct', '54329005', 'Acute myocardial infarction of anterior wall (disorder)')
,('http://snomed.info/sct', '57054005', 'Acute myocardial infarction (disorder)')
,('http://snomed.info/sct', '58612006', 'Acute myocardial infarction of lateral wall (disorder)')
,('http://snomed.info/sct', '59063002', 'Acute myocardial infarction of apical-lateral wall (disorder)')
,('http://snomed.info/sct', '62695002', 'Acute anteroseptal myocardial infarction (disorder)')
,('http://snomed.info/sct', '64627002', 'Acute myocardial infarction of high lateral wall (disorder)')
,('http://snomed.info/sct', '65547006', 'Acute myocardial infarction of inferolateral wall (disorder)')
,('http://snomed.info/sct', '70211005', 'Acute myocardial infarction of anterolateral wall (disorder)')
,('http://snomed.info/sct', '703164000', 'Acute ST segment elevation myocardial infarction of anterior wall (disorder)')
,('http://snomed.info/sct', '703165004', 'Acute ST segment elevation myocardial infarction of anterior wall involving right ventricle (disorder)')
,('http://snomed.info/sct', '703209002', 'Subsequent ST segment elevation myocardial infarction of inferior wall (disorder)')
,('http://snomed.info/sct', '703210007', 'Subsequent ST segment elevation myocardial infarction of anterior wall (disorder)')
,('http://snomed.info/sct', '703211006', 'Subsequent ST segment elevation myocardial infarction (disorder)')
,('http://snomed.info/sct', '703213009', 'Acute ST segment elevation myocardial infarction of inferior wall (disorder)')
,('http://snomed.info/sct', '703251009', 'Acute myocardial infarction of inferior wall involving right ventricle (disorder)')
,('http://snomed.info/sct', '703252002', 'Acute myocardial infarction of anterior wall involving right ventricle (disorder)')
,('http://snomed.info/sct', '703253007', 'Acute ST segment elevation myocardial infarction of inferior wall involving right ventricle (disorder)')
,('http://snomed.info/sct', '703360004', 'Subsequent non-ST segment elevation myocardial infarction (disorder)')
,('http://snomed.info/sct', '70422006', 'Acute subendocardial infarction (disorder)')
,('http://snomed.info/sct', '70998009', 'Acute myocardial infarction of basal inferior segment of left ventricle (disorder)')
,('http://snomed.info/sct', '73795002', 'Acute myocardial infarction of inferior wall (disorder)')
,('http://snomed.info/sct', '76593002', 'Acute myocardial infarction of inferoposterior wall (disorder)')
,('http://snomed.info/sct', '79009004', 'Acute myocardial infarction of septum (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.01', 'ST elevation (STEMI) myocardial infarction involving left main coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.02', 'ST elevation (STEMI) myocardial infarction involving left anterior descending coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.09', 'ST elevation (STEMI) myocardial infarction involving other coronary artery of anterior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.11', 'ST elevation (STEMI) myocardial infarction involving right coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.19', 'ST elevation (STEMI) myocardial infarction involving other coronary artery of inferior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.21', 'ST elevation (STEMI) myocardial infarction involving left circumflex coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.29', 'ST elevation (STEMI) myocardial infarction involving other sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.3', 'ST elevation (STEMI) myocardial infarction of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.4', 'Non-ST elevation (NSTEMI) myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.9', 'Acute myocardial infarction, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.A1', 'Myocardial infarction type 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.A9', 'Other myocardial infarction type')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.B', 'Myocardial infarction with coronary microvascular dysfunction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.0', 'Subsequent ST elevation (STEMI) myocardial infarction of anterior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.1', 'Subsequent ST elevation (STEMI) myocardial infarction of inferior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.2', 'Subsequent non-ST elevation (NSTEMI) myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.8', 'Subsequent ST elevation (STEMI) myocardial infarction of other sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.9', 'Subsequent ST elevation (STEMI) myocardial infarction of unspecified site')
) AS t (system, code, display) ;