create or replace view irae__lab_autoimmune_tsh as select * from (values
('http://loinc.org', '11033-8', 'Thyrotropin [Mass/volume] in Serum or Plasma --45 minutes post dose TRH IV')
,('http://loinc.org', '11579-0', 'Thyrotropin [Units/volume] in Serum or Plasma by Detection limit <= 0.05 mIU/L')
,('http://loinc.org', '11580-8', 'Thyrotropin [Units/volume] in Serum or Plasma by Detection limit <= 0.005 mIU/L')
,('http://loinc.org', '12932-0', 'Thyrotropin [Units/volume] in Serum or Plasma --post XXX challenge')
,('http://loinc.org', '12933-8', 'Thyrotropin [Units/volume] in Serum or Plasma --10 minutes post XXX challenge')
,('http://loinc.org', '12934-6', 'Thyrotropin [Units/volume] in Serum or Plasma --15 minutes post XXX challenge')
,('http://loinc.org', '12935-3', 'Thyrotropin [Units/volume] in Serum or Plasma --20 minutes post XXX challenge')
,('http://loinc.org', '12936-1', 'Thyrotropin [Units/volume] in Serum or Plasma --40 minutes post XXX challenge')
,('http://loinc.org', '12937-9', 'Thyrotropin [Units/volume] in Serum or Plasma --45 minutes post XXX challenge')
,('http://loinc.org', '12938-7', 'Thyrotropin [Units/volume] in Serum or Plasma --1.5 hours post XXX challenge')
,('http://loinc.org', '12939-5', 'Thyrotropin [Units/volume] in Serum or Plasma --2 hours post XXX challenge')
,('http://loinc.org', '12940-3', 'Thyrotropin [Units/volume] in Serum or Plasma --30 minutes pre XXX challenge')
,('http://loinc.org', '12941-1', 'Thyrotropin [Units/volume] in Serum or Plasma --2nd specimen post XXX challenge')
,('http://loinc.org', '12942-9', 'Thyrotropin [Units/volume] in Serum or Plasma --3rd specimen post XXX challenge')
,('http://loinc.org', '12943-7', 'Thyrotropin [Units/volume] in Serum or Plasma --4th specimen post XXX challenge')
,('http://loinc.org', '12944-5', 'Thyrotropin [Units/volume] in Serum or Plasma --5th specimen post XXX challenge')
,('http://loinc.org', '12945-2', 'Thyrotropin [Units/volume] in Serum or Plasma --6th specimen post XXX challenge')
,('http://loinc.org', '12946-0', 'Thyrotropin [Units/volume] in Serum or Plasma --7th specimen post XXX challenge')
,('http://loinc.org', '12947-8', 'Thyrotropin [Units/volume] in Serum or Plasma --8th specimen post XXX challenge')
,('http://loinc.org', '12948-6', 'Thyrotropin [Units/volume] in Serum or Plasma --9th specimen post XXX challenge')
,('http://loinc.org', '13869-3', 'Thyrotropin [Mass/volume] in Serum or Plasma --1.5 hours post dose TRH IV')
,('http://loinc.org', '13870-1', 'Thyrotropin [Mass/volume] in Serum or Plasma --15 minutes post dose TRH IV')
,('http://loinc.org', '13871-9', 'Thyrotropin [Mass/volume] in Serum or Plasma --2 hours post dose TRH IV')
,('http://loinc.org', '13897-4', 'Thyrotropin.beta subunit [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '14297-6', 'Thyrotropin [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '14997-1', 'Thyrotropin [Units/volume] in Serum or Plasma --30 minutes post dose TRH IV')
,('http://loinc.org', '14998-9', 'Thyrotropin [Units/volume] in Serum or Plasma --1 hour post dose TRH IV')
,('http://loinc.org', '14999-7', 'Thyrotropin [Units/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '15000-3', 'Thyrotropin [Units/volume] in Serum or Plasma --pre dose TRH IV')
,('http://loinc.org', '1640-2', 'Thyrotropin [Mass/volume] in Serum or Plasma --30 minutes post dose TRH IV')
,('http://loinc.org', '1641-0', 'Thyrotropin [Mass/volume] in Serum or Plasma --1 hour post dose TRH IV')
,('http://loinc.org', '1642-8', 'Thyrotropin [Mass/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '1643-6', 'Thyrotropin [Mass/volume] in Serum or Plasma --pre dose TRH IV')
,('http://loinc.org', '24459-0', 'Thyrotropin [Mass/volume] in Serum or Plasma --20 minutes post dose TRH')
,('http://loinc.org', '25789-9', 'Thyrotropin [Units/volume] in Serum or Plasma --1st specimen post XXX challenge')
,('http://loinc.org', '25990-3', 'Thyrotropin [Moles/volume] in Serum or Plasma --30 minutes post dose TRH IN')
,('http://loinc.org', '25991-1', 'Thyrotropin [Moles/volume] in Serum or Plasma --pre dose TRH IN')
,('http://loinc.org', '27975-2', 'Thyrotropin [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '29316-7', 'Thyrotropin [Units/volume] in Serum or Plasma --30 minutes post XXX challenge')
,('http://loinc.org', '29317-5', 'Thyrotropin [Units/volume] in Serum or Plasma --1 hour post XXX challenge')
,('http://loinc.org', '30151-5', 'Thyrotropin.long acting [Units/volume] in Serum or Plasma')
,('http://loinc.org', '3016-3', 'Thyrotropin [Units/volume] in Serum or Plasma')
,('http://loinc.org', '3018-9', 'Thyrotropin releasing hormone [Mass/volume] in Plasma')
,('http://loinc.org', '33258-5', 'Thyrotropin [Units/volume] in Serum or Plasma --30 minutes post dose TRH')
,('http://loinc.org', '33259-3', 'Thyrotropin [Units/volume] in Serum or Plasma --1 hour post dose TRH')
,('http://loinc.org', '33260-1', 'Thyrotropin [Units/volume] in Serum or Plasma --1.5 hours post dose TRH')
,('http://loinc.org', '33261-9', 'Thyrotropin [Units/volume] in Serum or Plasma --2 hours post dose TRH')
,('http://loinc.org', '33269-2', 'Thyrotropin [Units/volume] in Serum or Plasma --pre dose TRH')
,('http://loinc.org', '34054-7', 'Thyrotropin [Units/volume] in Serum or Plasma --pre or post dose TRH')
,('http://loinc.org', '40397-2', 'Thyrotropin [Units/volume] in Serum or Plasma --15 minutes post dose triple bolus')
,('http://loinc.org', '40398-0', 'Thyrotropin [Units/volume] in Serum or Plasma --1 hour post dose triple bolus')
,('http://loinc.org', '40399-8', 'Thyrotropin [Units/volume] in Serum or Plasma --20 minutes post dose triple bolus')
,('http://loinc.org', '40400-4', 'Thyrotropin [Units/volume] in Serum or Plasma --30 minutes post dose triple bolus')
,('http://loinc.org', '40401-2', 'Thyrotropin [Units/volume] in Serum or Plasma --pre dose triple bolus')
,('http://loinc.org', '40673-6', 'Thyrotropin binding inhibitory immunoglobulins [Units/volume] in Serum')
,('http://loinc.org', '44935-5', 'Thyrotropin [Units/volume] in Serum or Plasma --15 minutes post dose TRH IV')
,('http://loinc.org', '44936-3', 'Thyrotropin [Units/volume] in Serum or Plasma --15 minutes pre dose TRH IV')
,('http://loinc.org', '45173-2', 'Thyrotropin.alpha subunit [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '47947-7', 'Thyrotropin [Units/volume] in Serum or Plasma --1.5 hours post dose luteinizing releasing hormone IV')
,('http://loinc.org', '47948-5', 'Thyrotropin [Units/volume] in Serum or Plasma --15 minutes post dose luteinizing releasing hormone IV')
,('http://loinc.org', '47949-3', 'Thyrotropin [Units/volume] in Serum or Plasma --15 minutes pre dose luteinizing releasing hormone IV')
,('http://loinc.org', '47950-1', 'Thyrotropin [Units/volume] in Serum or Plasma --1 hour post dose luteinizing releasing hormone IV')
,('http://loinc.org', '47951-9', 'Thyrotropin [Units/volume] in Serum or Plasma --2 hours post dose luteinizing releasing hormone IV')
,('http://loinc.org', '47952-7', 'Thyrotropin [Units/volume] in Serum or Plasma --30 minutes post dose luteinizing releasing hormone IV')
,('http://loinc.org', '47953-5', 'Thyrotropin [Units/volume] in Serum or Plasma --pre dose luteinizing releasing hormone IV')
,('http://loinc.org', '48077-2', 'Thyrotropin [Units/volume] in Serum or Plasma --2.5 hours post dose luteinizing releasing hormone IV')
,('http://loinc.org', '50533-9', 'Thyrotropin [Units/volume] in Serum or Plasma --1st specimen')
,('http://loinc.org', '50534-7', 'Thyrotropin [Units/volume] in Serum or Plasma --2nd specimen')
,('http://loinc.org', '50535-4', 'Thyrotropin [Units/volume] in Serum or Plasma --3rd specimen')
,('http://loinc.org', '50536-2', 'Thyrotropin [Units/volume] in Serum or Plasma --4th specimen')
,('http://loinc.org', '50537-0', 'Thyrotropin [Units/volume] in Serum or Plasma --5th specimen')
,('http://loinc.org', '50538-8', 'Thyrotropin [Units/volume] in Serum or Plasma --6th specimen')
,('http://loinc.org', '50539-6', 'Thyrotropin [Units/volume] in Serum or Plasma --7th specimen')
,('http://loinc.org', '50540-4', 'Thyrotropin [Units/volume] in Serum or Plasma --8th specimen')
,('http://loinc.org', '50541-2', 'Thyrotropin [Units/volume] in Serum or Plasma --20 minutes post dose TRH')
,('http://loinc.org', '55362-8', 'Thyrotropin [Units/volume] in Serum or Plasma --pre XXX challenge')
,('http://loinc.org', '56594-5', 'Thyrotropin [Units/volume] in Serum or Plasma --3 hours post XXX challenge')
,('http://loinc.org', '57854-2', 'Thyrotropin [Units/volume] in Serum or Plasma --5 minutes post XXX challenge')
,('http://loinc.org', '58833-5', 'Thyrotropin [Mass/volume] in Serum or Plasma --20 minutes pre XXX challenge')
,('http://loinc.org', '58834-3', 'Thyrotropin [Units/volume] in Serum or Plasma --15 minutes pre XXX challenge')
,('http://loinc.org', '65360-0', 'Thyrotropin [Units/volume] in Serum or Plasma --pre or post XXX challenge')
,('http://loinc.org', '77623-7', 'Thyrotropin [Units/volume] in Serum or Plasma --2.5 hours post XXX challenge')
,('http://loinc.org', '90801-2', 'Thyrotropin [Units/volume] in Serum or Plasma --6 hours post dose levothyroxine')
) AS t (system, code, display) ;