create or replace view irae__rx_immunosuppressive_systemic_therapy as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1001405', 'docetaxel 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '103835', 'levamisole 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105585', 'methotrexate 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105586', 'methotrexate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '107047', 'rabbit anti-human T-lymphocyte globulin 25 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093280', 'docetaxel 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1095712', '24 HR nevirapine 400 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1099048', 'peginterferon alfa-2b 0.3 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1099054', 'peginterferon alfa-2b 0.6 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1099058', 'peginterferon alfa-2b 0.2 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1101769', 'docetaxel 24 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1111071', 'docetaxel 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115257', '1.5 ML leuprolide acetate 30 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115447', '1 ML leuprolide acetate 11.25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115454', '1 ML leuprolide acetate 15 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115457', '1 ML leuprolide acetate 3.75 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115462', '1 ML leuprolide acetate 7.5 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115467', '1.5 ML leuprolide acetate 15 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115472', '1.5 ML leuprolide acetate 7.5 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1116927', 'dexamethasone phosphate 4 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1145929', '1 ML abatacept 125 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1232574', 'interferon alfa-2b 18000000 UNT Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1242231', 'lenalidomide 2.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1304995', '31 ML vincristine sulfate liposome 0.16 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1373745', '24 HR nevirapine 100 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1428947', 'lenalidomide 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431971', '24 HR tacrolimus 0.5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431980', '24 HR tacrolimus 1 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431985', '24 HR tacrolimus 5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1433768', '0.5 ML tbo-filgrastim 0.6 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1433771', '0.8 ML tbo-filgrastim 0.6 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441402', '0.4 ML methotrexate 25 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441411', '0.4 ML methotrexate 37.5 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441416', '0.4 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441422', '0.4 ML methotrexate 62.5 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153323', 'interferon beta-1a 0.03 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1656643', 'basiliximab 10 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1656648', 'basiliximab 20 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726324', '5 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726333', '15 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726492', '25 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197323', 'altretamine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197388', 'azathioprine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197422', 'busulfan 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197462', 'chlorambucil 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197549', 'cyclophosphamide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197550', 'cyclophosphamide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197553', 'cyclosporine 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197687', 'etoposide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197710', 'fluoxymesterone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197711', 'fluoxymesterone 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197712', 'fluoxymesterone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197726', 'flutamide 125 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197797', 'hydroxyurea 500 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197894', 'lomustine 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197895', 'lomustine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197896', 'lomustine 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197919', 'melphalan 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197931', 'mercaptopurine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197988', 'mitotane 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197989', 'mitoxantrone 2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198056', 'oxandrolone 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198240', 'tamoxifen 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198269', 'thioguanine 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198352', 'zidovudine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198360', 'interferon beta-1b 0.3 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198377', 'tacrolimus 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198378', 'tacrolimus 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198379', '1 ML tacrolimus 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199058', 'mycophenolate mofetil 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199123', 'bicalutamide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199147', 'lamivudine 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199159', 'tretinoin 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199224', 'anastrozole 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199258', 'oxymetholone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199310', 'azathioprine 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199315', 'etoposide 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199422', 'nevirapine 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199609', 'flutamide 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199663', 'zidovudine 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200060', 'mycophenolate mofetil 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200064', 'letrozole 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200082', 'lamivudine 150 MG / zidovudine 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200105', 'saquinavir 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200327', 'capecitabine 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200328', 'capecitabine 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200342', 'hydroxyurea 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200343', 'hydroxyurea 300 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200344', 'hydroxyurea 400 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200390', 'thalidomide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '204534', '20 ML zidovudine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205168', 'cyclosporine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', '5 ML cyclosporine 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205284', 'leflunomide 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205285', 'leflunomide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205286', 'leflunomide 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205290', 'efavirenz 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205291', 'efavirenz 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205292', 'efavirenz 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205328', 'lamivudine 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239177', 'fluorouracil 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239178', 'vinblastine sulfate 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239179', 'dactinomycin 0.5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239180', 'streptozocin 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239984', 'muromonab-CD3 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240416', 'cytarabine 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240448', '0.5 ML interferon gamma-1b 0.2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240573', 'pentostatin 10 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240754', '10 ML cladribine 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240906', '5 ML pegaspargase 750 UNT/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '241834', 'cyclosporine, modified 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '242679', 'abacavir 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249364', '20 ML cytarabine 100 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '253014', 'etanercept 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '253113', '10 ML busulfan 6 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283103', 'indinavir 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283510', 'methotrexate 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283511', 'methotrexate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283671', 'methotrexate 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284183', 'didanosine 125 MG Delayed Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284184', 'didanosine 250 MG Delayed Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284185', 'didanosine 200 MG Delayed Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284192', 'peginterferon alfa-2b 0.05 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284193', 'peginterferon alfa-2b 0.08 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284194', 'peginterferon alfa-2b 0.12 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284195', 'peginterferon alfa-2b 0.15 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284988', 'didanosine 400 MG Delayed Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '307650', 'abacavir 300 MG / lamivudine 150 MG / zidovudine 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '307816', 'aldesleukin 22000000 UNT Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308096', 'amifostine 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308725', 'bexarotene 75 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309012', 'carmustine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309013', 'carmustine 7.7 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309311', 'cisplatin 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310194', 'estramustine 140 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310248', 'etoposide 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310261', 'exemestane 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310351', 'floxuridine 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310592', 'goserelin 3.6 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310986', 'indinavir 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310987', 'indinavir 333 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310988', 'indinavir 400 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310994', 'infliximab 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311078', 'interferon alfa-2b 50000000 UNT Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311368', 'lopinavir 133 MG / ritonavir 33.3 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311487', 'melphalan 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311625', 'methotrexate 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311880', 'mycophenolate mofetil 200 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311881', 'mycophenolate mofetil 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311924', 'nelfinavir 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311925', 'nelfinavir 0.05 MG/MG Oral Powder')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311943', 'nevirapine 10 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312109', 'oprelvekin 5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313107', 'stavudine 15 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313108', 'stavudine 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313109', 'stavudine 30 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313110', 'stavudine 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313190', 'tacrolimus 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313195', 'tamoxifen 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313209', 'temozolomide 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313210', 'temozolomide 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313211', 'temozolomide 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313213', '5 ML teniposide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313428', 'toremifene 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313567', 'valrubicin 40 MG/ML Irrigation Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313759', 'zalcitabine 0.375 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313760', 'zalcitabine 0.75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314008', 'goserelin 10.8 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314167', 'procarbazine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315199', 'sargramostim 0.25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317150', 'ritonavir 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317160', 'temozolomide 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328160', 'cyclosporine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328161', 'methylprednisolone 16 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349208', 'sirolimus 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349472', 'gefitinib 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349477', 'efavirenz 600 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349491', 'lamivudine 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351270', '1 ML peginterferon alfa-2a 0.18 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351276', 'oxandrolone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359228', 'azathioprine 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359229', 'azathioprine 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360110', 'sirolimus 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360176', 'thalidomide 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360177', 'thalidomide 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402243', 'bortezomib 3.5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402245', 'atazanavir 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402246', 'atazanavir 150 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402247', 'atazanavir 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403878', 'imatinib 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403879', 'imatinib 400 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403978', 'nelfinavir 625 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '477484', '15 ML natalizumab 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485246', 'azacitidine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '545289', 'interferon alfa-2b 10000000 UNT/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '545835', 'leuprolide acetate 5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '577154', 'megestrol acetate 125 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '577212', 'tipranavir 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '583214', 'paclitaxel 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597195', 'carboplatin 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597730', 'lopinavir 200 MG / ritonavir 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597747', 'sorafenib 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '602393', 'abacavir 600 MG / lamivudine 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '602910', 'lenalidomide 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '602912', 'lenalidomide 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '603203', 'erlotinib 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '603206', 'erlotinib 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '603208', 'erlotinib 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '615136', 'interferon alfa-n3 5000000 UNT/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616015', 'abatacept 250 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616279', 'sunitinib 12.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616285', 'sunitinib 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616289', 'sunitinib 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '637549', 'topotecan 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643066', 'efavirenz 600 MG / emtricitabine 200 MG / tenofovir disoproxil fumarate 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643712', 'lenalidomide 15 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643720', 'lenalidomide 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '664741', 'atazanavir 300 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '700416', 'thalidomide 150 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '700883', 'temozolomide 140 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '700885', 'temozolomide 180 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '722289', '1.2 ML temsirolimus 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727535', '0.5 ML filgrastim 0.6 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727539', '0.6 ML pegfilgrastim 10 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727544', '0.8 ML filgrastim 0.6 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727703', '0.8 ML adalimumab 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727757', '1 ML etanercept 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727813', '0.5 ML interferon beta-1a 0.06 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '731326', '0.5 ML peginterferon alfa-2a 0.36 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '746645', 'lopinavir 100 MG / ritonavir 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '747193', 'topotecan 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '747195', 'topotecan 0.25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '752884', '0.375 ML leuprolide acetate 120 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '752889', '0.5 ML leuprolide acetate 60 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '752894', '0.375 ML leuprolide acetate 60 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '752899', '0.25 ML leuprolide acetate 30 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '758025', '0.5 ML interferon beta-1a 0.088 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '758028', '0.2 ML interferon beta-1a 0.044 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '758029', '0.5 ML interferon beta-1a 0.044 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795081', 'certolizumab pegol 200 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '797657', '3 ML samarium Sm153 50 MCI/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '806573', 'trastuzumab 22 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809158', '0.5 ML etanercept 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '828706', 'fludarabine phosphate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '829926', '10 ML arsenic trioxide 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835809', 'testosterone enanthate 200 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835894', 'cyclosporine, modified 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835925', 'cyclosporine, modified 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835945', 'temozolomide 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '846164', 'curcumin 500 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '849597', '1 ML certolizumab pegol 200 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856560', 'delavirdine mesylate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856610', 'delavirdine mesylate 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '859863', 'saquinavir mesylate 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860215', 'megestrol acetate 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860221', 'megestrol acetate 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860225', 'megestrol acetate 40 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '860231', 'megestrol acetate 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '861050', 'asparaginase 5000 UNT/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '881341', 'adefovir dipivoxil 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '900575', 'ritonavir 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905158', 'sirolimus 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979092', 'hydroxychloroquine sulfate 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '996156', 'idarubicin hydrochloride 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '996158', 'idarubicin hydrochloride 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '996160', 'idarubicin hydrochloride 5 MG Oral Capsule')
) AS t (system, code, display) ;