create or replace view irae__dx_diabetes_preexisting as select * from (values
('http://www.cms.gov/Medicare/Coding/ICD10', '02YA0Z0', 'Transplantation of Heart, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '02YA0Z1', 'Transplantation of Heart, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '02YA0Z2', 'Transplantation of Heart, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '07YM0Z0', 'Transplantation of Thymus, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '07YM0Z1', 'Transplantation of Thymus, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '07YM0Z2', 'Transplantation of Thymus, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '07YP0Z0', 'Transplantation of Spleen, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '07YP0Z1', 'Transplantation of Spleen, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '07YP0Z2', 'Transplantation of Spleen, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYC0Z0', 'Transplantation of Right Upper Lung Lobe, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYC0Z1', 'Transplantation of Right Upper Lung Lobe, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYC0Z2', 'Transplantation of Right Upper Lung Lobe, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYD0Z0', 'Transplantation of Right Middle Lung Lobe, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYD0Z1', 'Transplantation of Right Middle Lung Lobe, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYD0Z2', 'Transplantation of Right Middle Lung Lobe, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYF0Z0', 'Transplantation of Right Lower Lung Lobe, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYF0Z1', 'Transplantation of Right Lower Lung Lobe, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYF0Z2', 'Transplantation of Right Lower Lung Lobe, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYG0Z0', 'Transplantation of Left Upper Lung Lobe, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYG0Z1', 'Transplantation of Left Upper Lung Lobe, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYG0Z2', 'Transplantation of Left Upper Lung Lobe, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYH0Z0', 'Transplantation of Lung Lingula, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYH0Z1', 'Transplantation of Lung Lingula, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYH0Z2', 'Transplantation of Lung Lingula, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYJ0Z0', 'Transplantation of Left Lower Lung Lobe, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYJ0Z1', 'Transplantation of Left Lower Lung Lobe, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYJ0Z2', 'Transplantation of Left Lower Lung Lobe, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYK0Z0', 'Transplantation of Right Lung, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYK0Z1', 'Transplantation of Right Lung, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYK0Z2', 'Transplantation of Right Lung, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYL0Z0', 'Transplantation of Left Lung, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYL0Z1', 'Transplantation of Left Lung, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYL0Z2', 'Transplantation of Left Lung, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYM0Z0', 'Transplantation of Bilateral Lungs, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYM0Z1', 'Transplantation of Bilateral Lungs, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0BYM0Z2', 'Transplantation of Bilateral Lungs, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY50Z0', 'Transplantation of Esophagus, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY50Z1', 'Transplantation of Esophagus, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY50Z2', 'Transplantation of Esophagus, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY60Z0', 'Transplantation of Stomach, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY60Z1', 'Transplantation of Stomach, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY60Z2', 'Transplantation of Stomach, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY80Z0', 'Transplantation of Small Intestine, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY80Z1', 'Transplantation of Small Intestine, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DY80Z2', 'Transplantation of Small Intestine, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DYE0Z0', 'Transplantation of Large Intestine, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DYE0Z1', 'Transplantation of Large Intestine, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0DYE0Z2', 'Transplantation of Large Intestine, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0FY00Z0', 'Transplantation of Liver, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0FY00Z1', 'Transplantation of Liver, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0FY00Z2', 'Transplantation of Liver, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0FYG0Z0', 'Transplantation of Pancreas, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0FYG0Z1', 'Transplantation of Pancreas, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0FYG0Z2', 'Transplantation of Pancreas, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY00Z0', 'Transplantation of Right Ovary, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY00Z1', 'Transplantation of Right Ovary, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY00Z2', 'Transplantation of Right Ovary, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY10Z0', 'Transplantation of Left Ovary, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY10Z1', 'Transplantation of Left Ovary, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY10Z2', 'Transplantation of Left Ovary, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY90Z0', 'Transplantation of Uterus, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY90Z1', 'Transplantation of Uterus, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0UY90Z2', 'Transplantation of Uterus, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0WY20Z0', 'Transplantation of Face, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0WY20Z1', 'Transplantation of Face, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0XYJ0Z0', 'Transplantation of Right Hand, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0XYJ0Z1', 'Transplantation of Right Hand, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0XYK0Z0', 'Transplantation of Left Hand, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0XYK0Z1', 'Transplantation of Left Hand, Syngeneic, Open Approach')
,('http://snomed.info/sct', '118158008', 'Gastrointestinal tract transplantation (procedure)')
,('http://snomed.info/sct', '119661004', 'Transplantation of tissue of hand (procedure)')
,('http://snomed.info/sct', '12528003', 'Cross intrinsic transfer of hand (procedure)')
,('http://snomed.info/sct', '128531006', 'Islet cell transplant (procedure)')
,('http://snomed.info/sct', '14681002', 'Reimplantation of lung (procedure)')
,('http://snomed.info/sct', '174691005', 'Transplantation of pancreas and duodenum (procedure)')
,('http://snomed.info/sct', '174692003', 'Whole organ pancreatic transplant (procedure)')
,('http://snomed.info/sct', '174693008', 'Transplantation of tail of pancreas (procedure)')
,('http://snomed.info/sct', '174694002', 'Renewal of transplanted pancreatic tissue (procedure)')
,('http://snomed.info/sct', '174802006', 'Allotransplant of heart and lung (procedure)')
,('http://snomed.info/sct', '174808005', 'Xenotransplant of heart (procedure)')
,('http://snomed.info/sct', '174809002', 'Heterotopic allotransplant of heart (procedure)')
,('http://snomed.info/sct', '178856007', 'Reconstruction of hand using free flap with microvascular anastomosis (procedure)')
,('http://snomed.info/sct', '178858008', 'Reconstruction of first web space with local flaps (procedure)')
,('http://snomed.info/sct', '180090008', 'Release of thumb-in-palm deformity (procedure)')
,('http://snomed.info/sct', '198662005', 'Hand muscle transfer (procedure)')
,('http://snomed.info/sct', '22595005', 'Transplantation of tissue of esophagus (procedure)')
,('http://snomed.info/sct', '232657004', 'Single lung transplant (procedure)')
,('http://snomed.info/sct', '232658009', 'Double lung transplant (procedure)')
,('http://snomed.info/sct', '232659001', 'Double lung transplant as a block (procedure)')
,('http://snomed.info/sct', '232660006', 'Bilateral sequential single lung transplant (procedure)')
,('http://snomed.info/sct', '232973007', 'Allotransplant of heart (procedure)')
,('http://snomed.info/sct', '232974001', 'Orthotopic allotransplant of heart (procedure)')
,('http://snomed.info/sct', '239243008', 'Transfer of intrinsic muscle of hand (procedure)')
,('http://snomed.info/sct', '239602000', 'Metacarpal transfer (procedure)')
,('http://snomed.info/sct', '277451006', 'Part organ pancreatic transplant (procedure)')
,('http://snomed.info/sct', '287239002', 'Thymus transplantation (procedure)')
,('http://snomed.info/sct', '30998000', 'Transplantation of fascia of hand (procedure)')
,('http://snomed.info/sct', '32413006', 'Transplantation of heart (procedure)')
,('http://snomed.info/sct', '32477003', 'Heart-lung transplant with recipient cardiectomy-pneumonectomy (procedure)')
,('http://www.ama-assn.org/go/cpt', '32850', 'Donor pneumonectomy(s) (including cold preservation), from cadaver donor')
,('http://www.ama-assn.org/go/cpt', '32851', 'Lung transplant, single. without cardiopulmonary bypass')
,('http://www.ama-assn.org/go/cpt', '32852', 'Lung transplant, single. with cardiopulmonary bypass')
,('http://www.ama-assn.org/go/cpt', '32853', 'Lung transplant, double (bilateral sequential or en bloc). without cardiopulmonary bypass')
,('http://www.ama-assn.org/go/cpt', '32854', 'Lung transplant, double (bilateral sequential or en bloc). with cardiopulmonary bypass')
,('http://www.ama-assn.org/go/cpt', '32855', 'Backbench standard preparation of cadaver donor lung allograft prior to transplantation, including dissection of allograft from surrounding soft tissues to prepare pulmonary venous/atrial cuff, pulmonary artery, and bronchus. unilateral')
,('http://www.ama-assn.org/go/cpt', '32856', 'Backbench standard preparation of cadaver donor lung allograft prior to transplantation, including dissection of allograft from surrounding soft tissues to prepare pulmonary venous/atrial cuff, pulmonary artery, and bronchus. bilateral')
,('http://snomed.info/sct', '32956007', 'Transplantation of tissue of rectum (procedure)')
,('http://www.ama-assn.org/go/cpt', '33927', 'Implantation of a total replacement heart system (artificial heart) with recipient cardiectomy')
,('http://www.ama-assn.org/go/cpt', '33928', 'Removal and replacement of total replacement heart system (artificial heart)')
,('http://www.ama-assn.org/go/cpt', '33929', 'Removal of a total replacement heart system (artificial heart) for heart transplantation (List separately in addition to code for primary procedure)')
,('http://www.ama-assn.org/go/cpt', '33930', 'Donor cardiectomy-pneumonectomy (including cold preservation)')
,('http://www.ama-assn.org/go/cpt', '33933', 'Backbench standard preparation of cadaver donor heart/lung allograft prior to transplantation, including dissection of allograft from surrounding soft tissues to prepare aorta, superior vena cava, inferior vena cava, and trachea for implantation')
,('http://www.ama-assn.org/go/cpt', '33935', 'Heart-lung transplant with recipient cardiectomy-pneumonectomy')
,('http://www.ama-assn.org/go/cpt', '33940', 'Donor cardiectomy (including cold preservation)')
,('http://www.ama-assn.org/go/cpt', '33944', 'Backbench standard preparation of cadaver donor heart allograft prior to transplantation, including dissection of allograft from surrounding soft tissues to prepare aorta, superior vena cava, inferior vena cava, pulmonary artery, and left atrium for implantation')
,('http://www.ama-assn.org/go/cpt', '33945', 'Heart transplant, with or without recipient cardiectomy')
,('http://snomed.info/sct', '345797001', 'Autotransplantation of pancreatic tissue (procedure)')
,('http://snomed.info/sct', '34905004', 'Transplant of ovary (procedure)')
,('http://snomed.info/sct', '35280008', 'Transfer of digit to replace absent thumb (procedure)')
,('http://snomed.info/sct', '35896003', 'Plastic operation on hand with graft of muscle (procedure)')
,('http://www.cms.gov/Medicare/Coding/ICD10', '3E030U1', 'Introduction of Nonautologous Pancreatic Islet Cells into Peripheral Vein, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '3E033U1', 'Introduction of Nonautologous Pancreatic Islet Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '3E0J3U1', 'Introduction of Nonautologous Pancreatic Islet Cells into Biliary and Pancreatic Tract, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '3E0J7U1', 'Introduction of Nonautologous Pancreatic Islet Cells into Biliary and Pancreatic Tract, Via Natural or Artificial Opening')
,('http://www.cms.gov/Medicare/Coding/ICD10', '3E0J8U1', 'Introduction of Nonautologous Pancreatic Islet Cells into Biliary and Pancreatic Tract, Via Natural or Artificial Opening Endoscopic')
,('http://snomed.info/sct', '405768001', 'Autotransplantation of heart (procedure)')
,('http://snomed.info/sct', '422130009', 'Transplantation of hand muscle (procedure)')
,('http://snomed.info/sct', '425616008', 'Transplantation of ileum (procedure)')
,('http://snomed.info/sct', '426463009', 'Allotransplantation of ileum (procedure)')
,('http://snomed.info/sct', '426984008', 'Allotransplantation of thymus gland (procedure)')
,('http://snomed.info/sct', '429332008', 'Transplantation of single lobe of lung (procedure)')
,('http://snomed.info/sct', '439008003', 'Transfer of free jejunum with microvascular anastomosis (procedure)')
,('http://snomed.info/sct', '439925004', 'Excision of constriction ring of finger with Z plasty (procedure)')
,('http://www.ama-assn.org/go/cpt', '44132', 'Donor enterectomy (including cold preservation), open. from cadaver donor')
,('http://www.ama-assn.org/go/cpt', '44133', 'Donor enterectomy (including cold preservation), open. partial, from living donor')
,('http://www.ama-assn.org/go/cpt', '44135', 'Intestinal allotransplantation. from cadaver donor')
,('http://www.ama-assn.org/go/cpt', '44136', 'Intestinal allotransplantation. from living donor')
,('http://www.ama-assn.org/go/cpt', '44137', 'Removal of transplanted intestinal allograft, complete')
,('http://snomed.info/sct', '441751006', 'Transplantation of intestine (procedure)')
,('http://snomed.info/sct', '441754003', 'Percutaneous transhepatic transplantation of pancreatic islet cell using fluoroscopic guidance (procedure)')
,('http://www.ama-assn.org/go/cpt', '44715', 'Backbench standard preparation of cadaver or living donor intestine allograft prior to transplantation, including mobilization and fashioning of the superior mesenteric artery and vein')
,('http://www.ama-assn.org/go/cpt', '44720', 'Backbench reconstruction of cadaver or living donor intestine allograft prior to transplantation. venous anastomosis, each')
,('http://www.ama-assn.org/go/cpt', '44721', 'Backbench reconstruction of cadaver or living donor intestine allograft prior to transplantation. arterial anastomosis, each')
,('http://snomed.info/sct', '447981001', 'Allotransplantation of islets of Langerhans (procedure)')
,('http://snomed.info/sct', '452031000124100', 'Transplantation of face (procedure)')
,('http://snomed.info/sct', '47058000', 'Heart transplant with recipient cardiectomy (procedure)')
,('http://www.ama-assn.org/go/cpt', '47133', 'Donor hepatectomy (including cold preservation), from cadaver donor')
,('http://www.ama-assn.org/go/cpt', '47135', 'Liver allotransplantation, orthotopic, partial or whole, from cadaver or living donor, any age')
,('http://www.ama-assn.org/go/cpt', '47140', 'Donor hepatectomy (including cold preservation), from living donor. left lateral segment only (segments II and III)')
,('http://www.ama-assn.org/go/cpt', '47141', 'Donor hepatectomy (including cold preservation), from living donor. total left lobectomy (segments II, III and IV)')
,('http://www.ama-assn.org/go/cpt', '47142', 'Donor hepatectomy (including cold preservation), from living donor. total right lobectomy (segments V, VI, VII and VIII)')
,('http://www.ama-assn.org/go/cpt', '47143', 'Backbench standard preparation of cadaver donor whole liver graft prior to allotransplantation, including cholecystectomy, if necessary, and dissection and removal of surrounding soft tissues to prepare the vena cava, portal vein, hepatic artery, and common bile duct for implantation. without trisegment or lobe split')
,('http://www.ama-assn.org/go/cpt', '47144', 'Backbench standard preparation of cadaver donor whole liver graft prior to allotransplantation, including cholecystectomy, if necessary, and dissection and removal of surrounding soft tissues to prepare the vena cava, portal vein, hepatic artery, and common bile duct for implantation. with trisegment split of whole liver graft into 2 partial liver grafts (ie, left lateral segment [segments II and III] and right trisegment [segments I and IV through VIII])')
,('http://www.ama-assn.org/go/cpt', '47145', 'Backbench standard preparation of cadaver donor whole liver graft prior to allotransplantation, including cholecystectomy, if necessary, and dissection and removal of surrounding soft tissues to prepare the vena cava, portal vein, hepatic artery, and common bile duct for implantation. with lobe split of whole liver graft into 2 partial liver grafts (ie, left lobe [segments II, III, and IV] and right lobe [segments I and V through VIII])')
,('http://www.ama-assn.org/go/cpt', '47146', 'Backbench reconstruction of cadaver or living donor liver graft prior to allotransplantation. venous anastomosis, each')
,('http://www.ama-assn.org/go/cpt', '47147', 'Backbench reconstruction of cadaver or living donor liver graft prior to allotransplantation. arterial anastomosis, each')
,('http://www.ama-assn.org/go/cpt', '48160', 'Pancreatectomy, total or subtotal, with autologous transplantation of pancreas or pancreatic islet cells')
,('http://www.ama-assn.org/go/cpt', '48550', 'Donor pancreatectomy (including cold preservation), with or without duodenal segment for transplantation')
,('http://www.ama-assn.org/go/cpt', '48551', 'Backbench standard preparation of cadaver donor pancreas allograft prior to transplantation, including dissection of allograft from surrounding soft tissues, splenectomy, duodenotomy, ligation of bile duct, ligation of mesenteric vessels, and Y-graft arterial anastomoses from iliac artery to superior mesenteric artery and to splenic artery')
,('http://www.ama-assn.org/go/cpt', '48552', 'Backbench reconstruction of cadaver donor pancreas allograft prior to transplantation, venous anastomosis, each')
,('http://www.ama-assn.org/go/cpt', '48554', 'Transplantation of pancreatic allograft')
,('http://www.ama-assn.org/go/cpt', '48556', 'Removal of transplanted pancreatic allograft')
,('http://snomed.info/sct', '52614004', 'Transfer of digit to replace absent thumb, same hand (procedure)')
,('http://snomed.info/sct', '56278001', 'Advancement of tendon of hand (procedure)')
,('http://snomed.info/sct', '56283009', 'Transplantation of small intestine (procedure)')
,('http://snomed.info/sct', '61535006', 'Transplantation of spleen (procedure)')
,('http://snomed.info/sct', '61876009', 'Transfer of hand muscle origin (procedure)')
,('http://snomed.info/sct', '62399001', 'Autotransplantation of ovary (procedure)')
,('http://snomed.info/sct', '62438007', 'Transplantation of pancreas (procedure)')
,('http://snomed.info/sct', '62511003', 'Autotransplant of lung (procedure)')
,('http://snomed.info/sct', '6471000179103', 'Transplantation of kidney and pancreas (procedure)')
,('http://snomed.info/sct', '67075000', 'Transplantation of tissue of stomach (procedure)')
,('http://snomed.info/sct', '67562009', 'Heterotransplant of pancreas (procedure)')
,('http://snomed.info/sct', '71020001', 'Plastic operation on hand with graft of fascia (procedure)')
,('http://snomed.info/sct', '71947008', 'Homotransplant of pancreas (procedure)')
,('http://snomed.info/sct', '76077004', 'Total pancreatectomy with transplantation (procedure)')
,('http://snomed.info/sct', '8773000', 'Transplantation of large intestine (procedure)')
,('http://snomed.info/sct', '88039007', 'Transplant of lung (procedure)')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S2053', 'Transplantation of small intestine and liver allografts')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S2054', 'Transplantation of multivisceral organs')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S2055', 'Harvesting of donor multivisceral organs, with preparation and maintenance of allografts. from cadaver donor')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S2060', 'Lobar lung transplantation')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S2061', 'Donor lobectomy (lung) for transplantation, living donor')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S2152', 'Solid organ(s), complete or segmental, single organ or combination of organs. deceased or living donor(s), procurement, transplantation, and related complications. including: drugs. supplies. hospitalization with outpatient follow-up. medical/surgical, diagnostic, emergency, and rehabilitative services, and the number of days of pre- and post-transplant care in the global definition')
) AS t (system, code, display) ;