create or replace view irae__lab_diabetes_glucose_test as select * from (values
('http://loinc.org', '100746-7', 'Glucose [Moles/volume] in Mixed venous blood')
,('http://loinc.org', '14743-9', 'Glucose [Moles/volume] in Capillary blood by Glucometer')
,('http://loinc.org', '14749-6', 'Glucose [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '14768-6', 'Glucose [Moles/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '14770-2', 'Fasting glucose [Moles/volume] in Capillary blood by Glucometer')
,('http://loinc.org', '14771-0', 'Fasting glucose [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '15074-8', 'Glucose [Moles/volume] in Blood')
,('http://loinc.org', '1547-9', 'Glucose [Mass/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '1556-0', 'Fasting glucose [Mass/volume] in Capillary blood')
,('http://loinc.org', '1557-8', 'Fasting glucose [Mass/volume] in Venous blood')
,('http://loinc.org', '1558-6', 'Fasting glucose [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '2339-0', 'Glucose [Mass/volume] in Blood')
,('http://loinc.org', '2340-8', 'Glucose [Mass/volume] in Blood by Automated test strip')
,('http://loinc.org', '2341-6', 'Glucose [Mass/volume] in Blood by Test strip manual')
,('http://loinc.org', '2345-7', 'Glucose [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '32016-8', 'Glucose [Mass/volume] in Capillary blood')
,('http://loinc.org', '39480-9', 'Glucose [Moles/volume] in Venous blood')
,('http://loinc.org', '39481-7', 'Glucose [Moles/volume] in Arterial blood')
,('http://loinc.org', '40858-3', 'Glucose [Mass/volume] in Capillary blood --baseline')
,('http://loinc.org', '41604-0', 'Fasting glucose [Mass/volume] in Capillary blood by Glucometer')
,('http://loinc.org', '41651-1', 'Glucose [Mass/volume] in Arterial blood')
,('http://loinc.org', '41652-9', 'Glucose [Mass/volume] in Venous blood')
,('http://loinc.org', '41653-7', 'Glucose [Mass/volume] in Capillary blood by Glucometer')
,('http://loinc.org', '50206-2', 'Glucose [Mass/volume] in Serum or Plasma --1st specimen')
,('http://loinc.org', '50212-0', 'Glucose [Mass/volume] in Serum or Plasma --2nd specimen')
,('http://loinc.org', '51596-5', 'Glucose [Moles/volume] in Capillary blood')
,('http://loinc.org', '53049-3', 'Glucose [Mass/volume] in Serum or Plasma --pre-meal')
,('http://loinc.org', '72516-8', 'Glucose [Moles/volume] in Blood by Automated test strip')
,('http://loinc.org', '74774-1', 'Glucose [Mass/volume] in Serum, Plasma or Blood')
,('http://loinc.org', '76629-5', 'Fasting glucose [Moles/volume] in Blood')
,('http://loinc.org', '77135-2', 'Glucose [Moles/volume] in Serum, Plasma or Blood')
,('http://loinc.org', '77145-1', 'Fasting glucose [Moles/volume] in Serum, Plasma or Blood')
) AS t (system, code, display) ;