create or replace view irae__dx_autoimmune_crohns as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'K50', 'Crohns disease [regional enteritis]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.0', 'Crohns disease of small intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.00', 'Crohns disease of small intestine without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.01', 'Crohns disease of small intestine with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.011', 'Crohns disease of small intestine with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.012', 'Crohns disease of small intestine with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.013', 'Crohns disease of small intestine with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.014', 'Crohns disease of small intestine with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.018', 'Crohns disease of small intestine with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.019', 'Crohns disease of small intestine with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.1', 'Crohns disease of large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.10', 'Crohns disease of large intestine without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.11', 'Crohns disease of large intestine with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.111', 'Crohns disease of large intestine with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.112', 'Crohns disease of large intestine with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.113', 'Crohns disease of large intestine with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.114', 'Crohns disease of large intestine with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.118', 'Crohns disease of large intestine with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.119', 'Crohns disease of large intestine with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.8', 'Crohns disease of both small and large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.80', 'Crohns disease of both small and large intestine without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.81', 'Crohns disease of both small and large intestine with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.811', 'Crohns disease of both small and large intestine with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.812', 'Crohns disease of both small and large intestine with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.813', 'Crohns disease of both small and large intestine with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.814', 'Crohns disease of both small and large intestine with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.818', 'Crohns disease of both small and large intestine with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.819', 'Crohns disease of both small and large intestine with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.9', 'Crohns disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.90', 'Crohns disease, unspecified, without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.91', 'Crohns disease, unspecified, with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.911', 'Crohns disease, unspecified, with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.912', 'Crohns disease, unspecified, with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.913', 'Crohns disease, unspecified, with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.914', 'Crohns disease, unspecified, with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.918', 'Crohns disease, unspecified, with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.919', 'Crohns disease, unspecified, with unspecified complications')
) AS t (system, code, display) ;