create or replace view irae__proc_dialysis_services as select * from (values
('http://snomed.info/sct', '108241001', 'Dialysis procedure (procedure)')
,('http://snomed.info/sct', '10848006', 'Removal of peritoneal dialysis catheter (procedure)')
,('http://snomed.info/sct', '11932001', 'Stabilizing hemodialysis (procedure)')
,('http://snomed.info/sct', '14684005', 'Peritoneal dialysis excluding cannulation (procedure)')
,('http://snomed.info/sct', '180273006', 'Removal of chronic ambulatory peritoneal dialysis catheter (procedure)')
,('http://snomed.info/sct', '225230008', 'Chronic peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '225231007', 'Stab peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '233575001', 'Intermittent hemodialysis (procedure)')
,('http://snomed.info/sct', '233576000', 'Intermittent hemodialysis with sequential ultrafiltration (procedure)')
,('http://snomed.info/sct', '233577009', 'Intermittent hemodialysis with continuous ultrafiltration (procedure)')
,('http://snomed.info/sct', '233578004', 'Continuous hemodialysis (procedure)')
,('http://snomed.info/sct', '233579007', 'Continuous arteriovenous hemodialysis (procedure)')
,('http://snomed.info/sct', '233580005', 'Continuous venovenous hemodialysis (procedure)')
,('http://snomed.info/sct', '233581009', 'Hemofiltration (procedure)')
,('http://snomed.info/sct', '233582002', 'Intermittent hemofiltration (procedure)')
,('http://snomed.info/sct', '233583007', 'Continuous hemofiltration (procedure)')
,('http://snomed.info/sct', '233584001', 'Continuous arteriovenous hemofiltration (procedure)')
,('http://snomed.info/sct', '233585000', 'Continuous venovenous hemofiltration (procedure)')
,('http://snomed.info/sct', '233586004', 'Hemodiafiltration (procedure)')
,('http://snomed.info/sct', '233587008', 'Intermittent hemodiafiltration (procedure)')
,('http://snomed.info/sct', '233588003', 'Continuous hemodiafiltration (procedure)')
,('http://snomed.info/sct', '233589006', 'Continuous arteriovenous hemodiafiltration (procedure)')
,('http://snomed.info/sct', '233590002', 'Continuous venovenous hemodiafiltration (procedure)')
,('http://snomed.info/sct', '238316008', 'Aspiration of chronic ambulatory peritoneal dialysis catheter (procedure)')
,('http://snomed.info/sct', '238317004', 'Flushing of chronic ambulatory peritoneal dialysis catheter (procedure)')
,('http://snomed.info/sct', '238318009', 'Continuous ambulatory peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '238319001', 'Continuous cycling peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '238321006', 'Intermittent peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '238322004', 'Tidal peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '238323009', 'Night-time intermittent peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '265764009', 'Renal dialysis (procedure)')
,('http://snomed.info/sct', '288182009', 'Extracorporeal kidney (procedure)')
,('http://snomed.info/sct', '302497006', 'Hemodialysis (procedure)')
,('http://snomed.info/sct', '34897002', 'Hemodialysis, maintenance in hospital (procedure)')
,('http://snomed.info/sct', '427053002', 'Extracorporeal albumin hemodialysis (procedure)')
,('http://snomed.info/sct', '428648006', 'Automated peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '439278006', 'Measurement of static venous pressure in hemodialysis vascular access (procedure)')
,('http://snomed.info/sct', '439976001', 'Measurement of recirculation in hemodialysis vascular access (procedure)')
,('http://snomed.info/sct', '57274006', 'Initial hemodialysis (procedure)')
,('http://snomed.info/sct', '676002', 'Peritoneal dialysis including cannulation (procedure)')
,('http://snomed.info/sct', '67970008', 'Hemodialysis, maintenance at home (procedure)')
,('http://snomed.info/sct', '68341005', 'Hemodialysis, supervision at home (procedure)')
,('http://snomed.info/sct', '71192002', 'Peritoneal dialysis (procedure)')
,('http://snomed.info/sct', '714749008', 'Continuous renal replacement therapy (procedure)')
,('http://www.ama-assn.org/go/cpt', '90935', 'Hemodialysis procedure with single evaluation by a physician or other qualified health care professional')
,('http://www.ama-assn.org/go/cpt', '90937', 'Hemodialysis procedure requiring repeated evaluation(s) with or without substantial revision of dialysis prescription')
,('http://www.ama-assn.org/go/cpt', '90945', 'Dialysis procedure other than hemodialysis (eg, peritoneal dialysis, hemofiltration, or other continuous renal replacement therapies), with single evaluation by a physician or other qualified health care professional')
,('http://www.ama-assn.org/go/cpt', '90947', 'Dialysis procedure other than hemodialysis (eg, peritoneal dialysis, hemofiltration, or other continuous renal replacement therapies) requiring repeated evaluations by a physician or other qualified health care professional, with or without substantial revision of dialysis prescription')
,('http://www.ama-assn.org/go/cpt', '90997', 'Hemoperfusion (eg, with activated charcoal or resin)')
,('http://www.ama-assn.org/go/cpt', '90999', 'Unlisted dialysis procedure, inpatient or outpatient')
,('http://www.ama-assn.org/go/cpt', '99512', 'Home visit for hemodialysis')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'G0257', 'Unscheduled or emergency dialysis treatment for an esrd patient in a hospital outpatient department that is not certified as an esrd facility')
,('http://www.nlm.nih.gov/research/umls/hcpcs', 'S9339', 'Home therapy. peritoneal dialysis, administrative services, professional pharmacy services, care coordination and all necessary supplies and equipment (drugs and nursing visits coded separately), per diem')
) AS t (system, code, display) ;