create or replace view irae__dx_kidney_renal_disease as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'I12.0', 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.9', 'Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.0', 'Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.10', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.11', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.2', 'Hypertensive heart and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.0', 'Chronic nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.1', 'Chronic nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.2', 'Chronic nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.3', 'Chronic nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.4', 'Chronic nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.5', 'Chronic nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.6', 'Chronic nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.7', 'Chronic nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.8', 'Chronic nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.9', 'Chronic nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.A', 'Chronic nephritic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.0', 'Nephrotic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.1', 'Nephrotic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.20', 'Nephrotic syndrome with diffuse membranous glomerulonephritis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.21', 'Primary membranous nephropathy with nephrotic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.22', 'Secondary membranous nephropathy with nephrotic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.29', 'Other nephrotic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.3', 'Nephrotic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.4', 'Nephrotic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.5', 'Nephrotic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.6', 'Nephrotic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.7', 'Nephrotic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.8', 'Nephrotic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.9', 'Nephrotic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.A', 'Nephrotic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.0', 'Unspecified nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.1', 'Unspecified nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.2', 'Unspecified nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.3', 'Unspecified nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.4', 'Unspecified nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.5', 'Unspecified nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.6', 'Unspecified nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.7', 'Unspecified nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.8', 'Unspecified nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.9', 'Unspecified nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.A', 'Unspecified nephritic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.0', 'Hereditary nephropathy, not elsewhere classified with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.1', 'Hereditary nephropathy, not elsewhere classified with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.2', 'Hereditary nephropathy, not elsewhere classified with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.3', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.4', 'Hereditary nephropathy, not elsewhere classified with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.5', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.6', 'Hereditary nephropathy, not elsewhere classified with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.7', 'Hereditary nephropathy, not elsewhere classified with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.8', 'Hereditary nephropathy, not elsewhere classified with other morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.9', 'Hereditary nephropathy, not elsewhere classified with unspecified morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.A', 'Hereditary nephropathy, not elsewhere classified with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N08', 'Glomerular disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11.1', 'Chronic obstructive pyelonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11.8', 'Other chronic tubulo-interstitial nephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11.9', 'Chronic tubulo-interstitial nephritis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.1', 'Chronic kidney disease, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.2', 'Chronic kidney disease, stage 2 (mild)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.30', 'Chronic kidney disease, stage 3 unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.31', 'Chronic kidney disease, stage 3a')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.32', 'Chronic kidney disease, stage 3b')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.4', 'Chronic kidney disease, stage 4 (severe)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.5', 'Chronic kidney disease, stage 5')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.6', 'End stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.9', 'Chronic kidney disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.0', 'Renal osteodystrophy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.1', 'Nephrogenic diabetes insipidus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.81', 'Secondary hyperparathyroidism of renal origin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.89', 'Other disorders resulting from impaired renal tubular function')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.9', 'Disorder resulting from impaired renal tubular function, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26.9', 'Renal sclerosis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O26.831', 'Pregnancy related renal disease, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O26.832', 'Pregnancy related renal disease, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O26.833', 'Pregnancy related renal disease, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O26.839', 'Pregnancy related renal disease, unspecified trimester')
) AS t (system, code, display) ;