create or replace view irae__lab_autoimmune_t4 as select * from (values
('http://loinc.org', '14920-3', 'Thyroxine (T4) free [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '14921-1', 'Thyroxine (T4) [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '20451-1', 'Thyroxine (T4) [Presence] in Blood')
,('http://loinc.org', '24348-5', 'Free T4 and TSH panel - Serum or Plasma')
,('http://loinc.org', '27000-9', 'Thyroxine (T4) [Mass/volume] in Saliva (oral fluid)')
,('http://loinc.org', '27987-7', 'Thyroxine (T4) free [Units/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '3024-7', 'Thyroxine (T4) free [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '3025-4', 'Thyroxine (T4) [Mass/volume] in Blood')
,('http://loinc.org', '3026-2', 'Thyroxine (T4) [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '31144-9', 'Thyroxine (T4) [Mass/volume] in DBS')
,('http://loinc.org', '31145-6', 'Thyroxine (T4) [Moles/volume] in DBS')
,('http://loinc.org', '32215-6', 'Thyroxine (T4) free index in Serum or Plasma by calculation')
,('http://loinc.org', '35226-0', 'Thyroxine (T4) [Mass or Moles/volume] in Serum or Plasma')
,('http://loinc.org', '35228-6', 'Thyroxine (T4) free [Mass or Moles/volume] in Serum or Plasma')
,('http://loinc.org', '38506-2', 'Thyroxine (T4) [Presence] in DBS')
,('http://loinc.org', '53349-7', 'Thyroxine (T4) free [Mass/volume] in DBS')
,('http://loinc.org', '53350-5', 'Thyroxine (T4) free [Moles/volume] in DBS')
,('http://loinc.org', '58838-4', 'Thyroxine (T4) free [Mass/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '6892-4', 'Thyroxine (T4) free [Mass/volume] in Serum or Plasma by Dialysis')
,('http://loinc.org', '70217-5', 'Thyroxine (T4) free [Moles/volume] in Serum or Plasma by Dialysis')
,('http://loinc.org', '83120-6', 'Thyroxine (T4) [Moles/volume] in Serum or Plasma by Immunoassay')
,('http://loinc.org', '83121-4', 'Thyroxine (T4) free [Moles/volume] in Serum or Plasma by Immunoassay')
,('http://loinc.org', '83122-2', 'Thyroxine (T4) free [Mass/volume] in Serum or Plasma by Immunoassay')
,('http://loinc.org', 'LP386925-4', 'Free T4 and TSH panel | Serum or Plasma | Chemistry Panels')
) AS t (system, code, display) ;