create or replace view irae__dx_infection_hepatitis_c as select * from (values
('http://snomed.info/sct', '10295004', 'Chronic viral hepatitis (disorder)')
,('http://snomed.info/sct', '1092801000119102', 'Hepatic ascites co-occurrent with chronic active hepatitis due to toxic liver disease (disorder)')
,('http://snomed.info/sct', '1116000', 'Chronic aggressive type B viral hepatitis (disorder)')
,('http://snomed.info/sct', '1197150002', 'Recurrent hepatitis C virus induced liver disease following liver transplant (disorder)')
,('http://snomed.info/sct', '128302006', 'Chronic hepatitis C (disorder)')
,('http://snomed.info/sct', '16098491000119109', 'Chronic autoimmune hepatitis (disorder)')
,('http://snomed.info/sct', '16623921000119105', 'Viral hepatitis C in mother during pregnancy (disorder)')
,('http://snomed.info/sct', '16859701000119109', 'Chronic hepatitis B during pregnancy (disorder)')
,('http://snomed.info/sct', '186639003', 'Chronic viral hepatitis B without delta-agent (disorder)')
,('http://snomed.info/sct', '197284004', 'Chronic active hepatitis (disorder)')
,('http://snomed.info/sct', '235865005', 'Hepatitis D superinfection of hepatitis B carrier (disorder)')
,('http://snomed.info/sct', '235866006', 'Acute hepatitis C (disorder)')
,('http://snomed.info/sct', '235869004', 'Chronic viral hepatitis B with hepatitis D (disorder)')
,('http://snomed.info/sct', '235889003', 'Drug-induced chronic hepatitis (disorder)')
,('http://snomed.info/sct', '307757001', 'Chronic alcoholic hepatitis (disorder)')
,('http://snomed.info/sct', '347891000119103', 'Chronic hepatitis C with stage 3 fibrosis (disorder)')
,('http://snomed.info/sct', '38662009', 'Chronic persistent type B viral hepatitis (disorder)')
,('http://snomed.info/sct', '41889008', 'Chronic persistent hepatitis (disorder)')
,('http://snomed.info/sct', '435101000124104', 'Chronic viral hepatitis C with hepatic coma (disorder)')
,('http://snomed.info/sct', '442374005', 'Hepatitis B and hepatitis C (disorder)')
,('http://snomed.info/sct', '450880008', 'Chronic hepatitis E (disorder)')
,('http://snomed.info/sct', '50167007', 'Chronic active type B viral hepatitis (disorder)')
,('http://snomed.info/sct', '50711007', 'Viral hepatitis type C (disorder)')
,('http://snomed.info/sct', '551611000124101', 'Perinatal hepatitis caused by Hepatitis C virus (disorder)')
,('http://snomed.info/sct', '57339008', 'Chronic lobular hepatitis (disorder)')
,('http://snomed.info/sct', '60037002', 'Chronic persistent viral hepatitis (disorder)')
,('http://snomed.info/sct', '61977001', 'Chronic type B viral hepatitis (disorder)')
,('http://snomed.info/sct', '66870002', 'Chronic active viral hepatitis (disorder)')
,('http://snomed.info/sct', '702969000', 'Reactivation of hepatitis C viral hepatitis (disorder)')
,('http://snomed.info/sct', '703866000', 'Chronic hepatitis C with stage 2 fibrosis (disorder)')
,('http://snomed.info/sct', '708198006', 'Chronic active hepatitis C (disorder)')
,('http://snomed.info/sct', '713966008', 'Occult chronic type B viral hepatitis (disorder)')
,('http://snomed.info/sct', '735451005', 'Chronic infection caused by Hepatitis D virus (disorder)')
,('http://snomed.info/sct', '767809001', 'Chronic hepatitis C caused by hepatitis C virus genotype 6 (disorder)')
,('http://snomed.info/sct', '767810006', 'Chronic hepatitis C caused by hepatitis C virus genotype 5 (disorder)')
,('http://snomed.info/sct', '76783007', 'Chronic hepatitis (disorder)')
,('http://snomed.info/sct', '768006009', 'Chronic hepatitis C caused by Hepatitis C virus genotype 3 (disorder)')
,('http://snomed.info/sct', '768125005', 'Chronic hepatitis C caused by Hepatitis C virus genotype 2 (disorder)')
,('http://snomed.info/sct', '768126006', 'Chronic hepatitis C caused by Hepatitis C virus genotype 4 (disorder)')
,('http://snomed.info/sct', '768127002', 'Chronic hepatitis C caused by Hepatitis C virus genotype 1 (disorder)')
,('http://snomed.info/sct', '768288001', 'Chronic hepatitis C caused by Hepatitis C virus genotype 1b (disorder)')
,('http://snomed.info/sct', '768289009', 'Chronic hepatitis C caused by Hepatitis C virus genotype 1a (disorder)')
,('http://snomed.info/sct', '774204006', 'Growth retardation, mild developmental delay, chronic hepatitis syndrome (disorder)')
,('http://snomed.info/sct', '838377003', 'Chronic hepatitis C co-occurrent with human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '838380002', 'Chronic hepatitis B co-occurrent with hepatitis C and hepatitis D (disorder)')
,('http://snomed.info/sct', '89789003', 'Chronic aggressive viral hepatitis (disorder)')
,('http://snomed.info/sct', '9843006', 'Chronic lymphocytic cholangitis-cholangiohepatitis (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B17.1', 'Acute hepatitis C')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B17.10', 'Acute hepatitis C without hepatic coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B17.11', 'Acute hepatitis C with hepatic coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B18.2', 'Chronic viral hepatitis C')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B19.2', 'Unspecified viral hepatitis C')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B19.20', 'Unspecified viral hepatitis C without hepatic coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B19.21', 'Unspecified viral hepatitis C with hepatic coma')
) AS t (system, code, display) ;