create table irae__cohort_lab_hemoglobin_a1c as 
select * from 
 irae__cohort_study_population_lab , 
irae__lab_hemoglobin_a1c
WHERE
irae__cohort_study_population_lab.lab_observation_code = irae__lab_hemoglobin_a1c.code and 
irae__cohort_study_population_lab.lab_observation_system = irae__lab_hemoglobin_a1c.system