create or replace view irae__dx_heart_cohort as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'A36.81', 'Diphtheritic cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A38.1', 'Scarlet fever with myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A39.50', 'Meningococcal carditis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A39.51', 'Meningococcal endocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A39.52', 'Meningococcal myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A39.53', 'Meningococcal pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B26.82', 'Mumps myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B33.20', 'Viral carditis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B33.21', 'Viral endocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B33.22', 'Viral myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B33.23', 'Viral pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B33.24', 'Viral cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B37.6', 'Candidal endocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B58.81', 'Toxoplasma myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I01.0', 'Acute rheumatic pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I01.1', 'Acute rheumatic endocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I01.2', 'Acute rheumatic myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I01.8', 'Other acute rheumatic heart disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I01.9', 'Acute rheumatic heart disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I02.0', 'Rheumatic chorea with heart involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I05.0', 'Rheumatic mitral stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I05.1', 'Rheumatic mitral insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I05.2', 'Rheumatic mitral stenosis with insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I05.8', 'Other rheumatic mitral valve diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I05.9', 'Rheumatic mitral valve disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I06.0', 'Rheumatic aortic stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I06.1', 'Rheumatic aortic insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I06.2', 'Rheumatic aortic stenosis with insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I06.8', 'Other rheumatic aortic valve diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I06.9', 'Rheumatic aortic valve disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I07.0', 'Rheumatic tricuspid stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I07.1', 'Rheumatic tricuspid insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I07.2', 'Rheumatic tricuspid stenosis and insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I07.8', 'Other rheumatic tricuspid valve diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I07.9', 'Rheumatic tricuspid valve disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I08.0', 'Rheumatic disorders of both mitral and aortic valves')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I08.1', 'Rheumatic disorders of both mitral and tricuspid valves')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I08.2', 'Rheumatic disorders of both aortic and tricuspid valves')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I08.3', 'Combined rheumatic disorders of mitral, aortic and tricuspid valves')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I08.8', 'Other rheumatic multiple valve diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I08.9', 'Rheumatic multiple valve disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I09.0', 'Rheumatic myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I09.1', 'Rheumatic diseases of endocardium, valve unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I09.2', 'Chronic rheumatic pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I09.89', 'Other specified rheumatic heart diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I09.9', 'Rheumatic heart disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I20.0', 'Unstable angina')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I20.1', 'Angina pectoris with documented spasm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I20.8', 'Other forms of angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I20.9', 'Angina pectoris, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.01', 'ST elevation (STEMI) myocardial infarction involving left main coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.02', 'ST elevation (STEMI) myocardial infarction involving left anterior descending coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.09', 'ST elevation (STEMI) myocardial infarction involving other coronary artery of anterior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.11', 'ST elevation (STEMI) myocardial infarction involving right coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.19', 'ST elevation (STEMI) myocardial infarction involving other coronary artery of inferior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.21', 'ST elevation (STEMI) myocardial infarction involving left circumflex coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.29', 'ST elevation (STEMI) myocardial infarction involving other sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.3', 'ST elevation (STEMI) myocardial infarction of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.4', 'Non-ST elevation (NSTEMI) myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.9', 'Acute myocardial infarction, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.A1', 'Myocardial infarction type 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I21.A9', 'Other myocardial infarction type')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.0', 'Subsequent ST elevation (STEMI) myocardial infarction of anterior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.1', 'Subsequent ST elevation (STEMI) myocardial infarction of inferior wall')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.2', 'Subsequent non-ST elevation (NSTEMI) myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.8', 'Subsequent ST elevation (STEMI) myocardial infarction of other sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I22.9', 'Subsequent ST elevation (STEMI) myocardial infarction of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.0', 'Hemopericardium as current complication following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.1', 'Atrial septal defect as current complication following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.2', 'Ventricular septal defect as current complication following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.3', 'Rupture of cardiac wall without hemopericardium as current complication following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.4', 'Rupture of chordae tendineae as current complication following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.5', 'Rupture of papillary muscle as current complication following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.6', 'Thrombosis of atrium, auricular appendage, and ventricle as current complications following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.7', 'Postinfarction angina')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I23.8', 'Other current complications following acute myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I24.0', 'Acute coronary thrombosis not resulting in myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I24.1', 'Dresslers syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I24.8', 'Other forms of acute ischemic heart disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I24.9', 'Acute ischemic heart disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.10', 'Atherosclerotic heart disease of native coronary artery without angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.110', 'Atherosclerotic heart disease of native coronary artery with unstable angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.111', 'Atherosclerotic heart disease of native coronary artery with angina pectoris with documented spasm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.118', 'Atherosclerotic heart disease of native coronary artery with other forms of angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.119', 'Atherosclerotic heart disease of native coronary artery with unspecified angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.2', 'Old myocardial infarction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.3', 'Aneurysm of heart')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.41', 'Coronary artery aneurysm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.42', 'Coronary artery dissection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.5', 'Ischemic cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.6', 'Silent myocardial ischemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.750', 'Atherosclerosis of native coronary artery of transplanted heart with unstable angina')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.751', 'Atherosclerosis of native coronary artery of transplanted heart with angina pectoris with documented spasm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.758', 'Atherosclerosis of native coronary artery of transplanted heart with other forms of angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.759', 'Atherosclerosis of native coronary artery of transplanted heart with unspecified angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.811', 'Atherosclerosis of native coronary artery of transplanted heart without angina pectoris')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.82', 'Chronic total occlusion of coronary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.83', 'Coronary atherosclerosis due to lipid rich plaque')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.84', 'Coronary atherosclerosis due to calcified coronary lesion')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.89', 'Other forms of chronic ischemic heart disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I25.9', 'Chronic ischemic heart disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I30.0', 'Acute nonspecific idiopathic pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I30.1', 'Infective pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I30.8', 'Other forms of acute pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I30.9', 'Acute pericarditis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I31.0', 'Chronic adhesive pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I31.1', 'Chronic constrictive pericarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I31.2', 'Hemopericardium, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I31.3', 'Pericardial effusion (noninflammatory)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I31.4', 'Cardiac tamponade')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I31.8', 'Other specified diseases of pericardium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I31.9', 'Disease of pericardium, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I32', 'Pericarditis in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I33.0', 'Acute and subacute infective endocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I33.9', 'Acute and subacute endocarditis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I34.0', 'Nonrheumatic mitral (valve) insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I34.1', 'Nonrheumatic mitral (valve) prolapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I34.2', 'Nonrheumatic mitral (valve) stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I34.8', 'Other nonrheumatic mitral valve disorders')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I34.9', 'Nonrheumatic mitral valve disorder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I35.0', 'Nonrheumatic aortic (valve) stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I35.1', 'Nonrheumatic aortic (valve) insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I35.2', 'Nonrheumatic aortic (valve) stenosis with insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I35.8', 'Other nonrheumatic aortic valve disorders')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I35.9', 'Nonrheumatic aortic valve disorder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I36.0', 'Nonrheumatic tricuspid (valve) stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I36.1', 'Nonrheumatic tricuspid (valve) insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I36.2', 'Nonrheumatic tricuspid (valve) stenosis with insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I36.8', 'Other nonrheumatic tricuspid valve disorders')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I36.9', 'Nonrheumatic tricuspid valve disorder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I37.0', 'Nonrheumatic pulmonary valve stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I37.1', 'Nonrheumatic pulmonary valve insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I37.2', 'Nonrheumatic pulmonary valve stenosis with insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I37.8', 'Other nonrheumatic pulmonary valve disorders')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I37.9', 'Nonrheumatic pulmonary valve disorder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I38', 'Endocarditis, valve unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I39', 'Endocarditis and heart valve disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I40.0', 'Infective myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I40.1', 'Isolated myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I40.8', 'Other acute myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I40.9', 'Acute myocarditis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I41', 'Myocarditis in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.0', 'Dilated cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.1', 'Obstructive hypertrophic cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.2', 'Other hypertrophic cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.3', 'Endomyocardial (eosinophilic) disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.4', 'Endocardial fibroelastosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.5', 'Other restrictive cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.7', 'Cardiomyopathy due to drug and external agent')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.8', 'Other cardiomyopathies')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.9', 'Cardiomyopathy, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I43', 'Cardiomyopathy in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.0', 'Atrioventricular block, first degree')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.1', 'Atrioventricular block, second degree')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.2', 'Atrioventricular block, complete')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.30', 'Unspecified atrioventricular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.39', 'Other atrioventricular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.4', 'Left anterior fascicular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.5', 'Left posterior fascicular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.60', 'Unspecified fascicular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.69', 'Other fascicular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I44.7', 'Left bundle-branch block, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.0', 'Right fascicular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.10', 'Unspecified right bundle-branch block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.19', 'Other right bundle-branch block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.2', 'Bifascicular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.3', 'Trifascicular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.4', 'Nonspecific intraventricular block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.5', 'Other specified heart block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.6', 'Pre-excitation syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.81', 'Long QT syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.89', 'Other specified conduction disorders')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I45.9', 'Conduction disorder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I46.2', 'Cardiac arrest due to underlying cardiac condition')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I46.8', 'Cardiac arrest due to other underlying condition')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I46.9', 'Cardiac arrest, cause unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I47.0', 'Re-entry ventricular arrhythmia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I47.1', 'Supraventricular tachycardia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I47.2', 'Ventricular tachycardia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I47.9', 'Paroxysmal tachycardia, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I48.0', 'Paroxysmal atrial fibrillation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I48.1', 'Persistent atrial fibrillation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I48.2', 'Chronic atrial fibrillation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I48.3', 'Typical atrial flutter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I48.4', 'Atypical atrial flutter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I48.91', 'Unspecified atrial fibrillation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I48.92', 'Unspecified atrial flutter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.01', 'Ventricular fibrillation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.02', 'Ventricular flutter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.1', 'Atrial premature depolarization')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.2', 'Junctional premature depolarization')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.3', 'Ventricular premature depolarization')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.40', 'Unspecified premature depolarization')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.49', 'Other premature depolarization')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.5', 'Sick sinus syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.8', 'Other specified cardiac arrhythmias')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I49.9', 'Cardiac arrhythmia, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.0', 'Cardiac septal defect, acquired')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.1', 'Rupture of chordae tendineae, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.2', 'Rupture of papillary muscle, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.3', 'Intracardiac thrombosis, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.4', 'Myocarditis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.5', 'Myocardial degeneration')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.7', 'Cardiomegaly')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.81', 'Takotsubo syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.89', 'Other ill-defined heart diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I51.9', 'Heart disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I52', 'Other heart disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I67.0', 'Dissection of cerebral arteries, nonruptured')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.0', 'Atherosclerosis of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.1', 'Atherosclerosis of renal artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.201', 'Unspecified atherosclerosis of native arteries of extremities, right leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.202', 'Unspecified atherosclerosis of native arteries of extremities, left leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.203', 'Unspecified atherosclerosis of native arteries of extremities, bilateral legs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.208', 'Unspecified atherosclerosis of native arteries of extremities, other extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.209', 'Unspecified atherosclerosis of native arteries of extremities, unspecified extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.211', 'Atherosclerosis of native arteries of extremities with intermittent claudication, right leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.212', 'Atherosclerosis of native arteries of extremities with intermittent claudication, left leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.213', 'Atherosclerosis of native arteries of extremities with intermittent claudication, bilateral legs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.218', 'Atherosclerosis of native arteries of extremities with intermittent claudication, other extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.219', 'Atherosclerosis of native arteries of extremities with intermittent claudication, unspecified extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.221', 'Atherosclerosis of native arteries of extremities with rest pain, right leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.222', 'Atherosclerosis of native arteries of extremities with rest pain, left leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.223', 'Atherosclerosis of native arteries of extremities with rest pain, bilateral legs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.228', 'Atherosclerosis of native arteries of extremities with rest pain, other extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.229', 'Atherosclerosis of native arteries of extremities with rest pain, unspecified extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.231', 'Atherosclerosis of native arteries of right leg with ulceration of thigh')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.232', 'Atherosclerosis of native arteries of right leg with ulceration of calf')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.233', 'Atherosclerosis of native arteries of right leg with ulceration of ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.234', 'Atherosclerosis of native arteries of right leg with ulceration of heel and midfoot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.235', 'Atherosclerosis of native arteries of right leg with ulceration of other part of foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.238', 'Atherosclerosis of native arteries of right leg with ulceration of other part of lower leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.239', 'Atherosclerosis of native arteries of right leg with ulceration of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.241', 'Atherosclerosis of native arteries of left leg with ulceration of thigh')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.242', 'Atherosclerosis of native arteries of left leg with ulceration of calf')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.243', 'Atherosclerosis of native arteries of left leg with ulceration of ankle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.244', 'Atherosclerosis of native arteries of left leg with ulceration of heel and midfoot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.245', 'Atherosclerosis of native arteries of left leg with ulceration of other part of foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.248', 'Atherosclerosis of native arteries of left leg with ulceration of other part of lower leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.249', 'Atherosclerosis of native arteries of left leg with ulceration of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.25', 'Atherosclerosis of native arteries of other extremities with ulceration')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.291', 'Other atherosclerosis of native arteries of extremities, right leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.292', 'Other atherosclerosis of native arteries of extremities, left leg')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.293', 'Other atherosclerosis of native arteries of extremities, bilateral legs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.298', 'Other atherosclerosis of native arteries of extremities, other extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.299', 'Other atherosclerosis of native arteries of extremities, unspecified extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.8', 'Atherosclerosis of other arteries')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.90', 'Unspecified atherosclerosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.91', 'Generalized atherosclerosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I70.92', 'Chronic total occlusion of artery of the extremities')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.00', 'Dissection of unspecified site of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.01', 'Dissection of thoracic aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.02', 'Dissection of abdominal aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.03', 'Dissection of thoracoabdominal aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.1', 'Thoracic aortic aneurysm, ruptured')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.2', 'Thoracic aortic aneurysm, without rupture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.3', 'Abdominal aortic aneurysm, ruptured')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.4', 'Abdominal aortic aneurysm, without rupture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.5', 'Thoracoabdominal aortic aneurysm, ruptured')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.6', 'Thoracoabdominal aortic aneurysm, without rupture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.8', 'Aortic aneurysm of unspecified site, ruptured')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I71.9', 'Aortic aneurysm of unspecified site, without rupture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.0', 'Aneurysm of carotid artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.1', 'Aneurysm of artery of upper extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.2', 'Aneurysm of renal artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.3', 'Aneurysm of iliac artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.4', 'Aneurysm of artery of lower extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.5', 'Aneurysm of other precerebral arteries')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.6', 'Aneurysm of vertebral artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.8', 'Aneurysm of other specified arteries')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I72.9', 'Aneurysm of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I73.00', 'Raynauds syndrome without gangrene')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I73.1', 'Thromboangiitis obliterans [Buergers disease]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I73.81', 'Erythromelalgia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I73.89', 'Other specified peripheral vascular diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I73.9', 'Peripheral vascular disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.01', 'Saddle embolus of abdominal aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.09', 'Other arterial embolism and thrombosis of abdominal aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.10', 'Embolism and thrombosis of unspecified parts of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.11', 'Embolism and thrombosis of thoracic aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.19', 'Embolism and thrombosis of other parts of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.2', 'Embolism and thrombosis of arteries of the upper extremities')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.3', 'Embolism and thrombosis of arteries of the lower extremities')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.4', 'Embolism and thrombosis of arteries of extremities, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.5', 'Embolism and thrombosis of iliac artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.8', 'Embolism and thrombosis of other arteries')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I74.9', 'Embolism and thrombosis of unspecified artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.011', 'Atheroembolism of right upper extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.012', 'Atheroembolism of left upper extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.013', 'Atheroembolism of bilateral upper extremities')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.019', 'Atheroembolism of unspecified upper extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.021', 'Atheroembolism of right lower extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.022', 'Atheroembolism of left lower extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.023', 'Atheroembolism of bilateral lower extremities')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.029', 'Atheroembolism of unspecified lower extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.81', 'Atheroembolism of kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I75.89', 'Atheroembolism of other site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.0', 'Arteriovenous fistula, acquired')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.1', 'Stricture of artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.2', 'Rupture of artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.3', 'Arterial fibromuscular dysplasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.4', 'Celiac artery compression syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.5', 'Necrosis of artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.6', 'Arteritis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.70', 'Dissection of unspecified artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.71', 'Dissection of carotid artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.72', 'Dissection of iliac artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.73', 'Dissection of renal artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.74', 'Dissection of vertebral artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.75', 'Dissection of other precerebral arteries')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.76', 'Dissection of artery of upper extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.77', 'Dissection of artery of lower extremity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.79', 'Dissection of other specified artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.810', 'Thoracic aortic ectasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.811', 'Abdominal aortic ectasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.812', 'Thoracoabdominal aortic ectasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.819', 'Aortic ectasia, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.89', 'Other specified disorders of arteries and arterioles')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I77.9', 'Disorder of arteries and arterioles, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I78.0', 'Hereditary hemorrhagic telangiectasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I78.1', 'Nevus, non-neoplastic')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I78.8', 'Other diseases of capillaries')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I78.9', 'Disease of capillaries, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I79.0', 'Aneurysm of aorta in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I79.1', 'Aortitis in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I79.8', 'Other disorders of arteries, arterioles and capillaries in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I95.0', 'Idiopathic hypotension')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I95.1', 'Orthostatic hypotension')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I95.89', 'Other hypotension')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I95.9', 'Hypotension, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I99.8', 'Other disorder of circulatory system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I99.9', 'Unspecified disorder of circulatory system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.82', 'Influenza due to other identified influenza virus with myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.0', 'Acute vascular disorders of intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.011', 'Focal (segmental) acute (reversible) ischemia of small intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.012', 'Diffuse acute (reversible) ischemia of small intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.019', 'Acute (reversible) ischemia of small intestine, extent unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.021', 'Focal (segmental) acute infarction of small intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.022', 'Diffuse acute infarction of small intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.029', 'Acute infarction of small intestine, extent unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.031', 'Focal (segmental) acute (reversible) ischemia of large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.032', 'Diffuse acute (reversible) ischemia of large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.039', 'Acute (reversible) ischemia of large intestine, extent unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.041', 'Focal (segmental) acute infarction of large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.042', 'Diffuse acute infarction of large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.049', 'Acute infarction of large intestine, extent unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.051', 'Focal (segmental) acute (reversible) ischemia of intestine, part unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.052', 'Diffuse acute (reversible) ischemia of intestine, part unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.059', 'Acute (reversible) ischemia of intestine, part and extent unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.061', 'Focal (segmental) acute infarction of intestine, part unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.062', 'Diffuse acute infarction of intestine, part unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.069', 'Acute infarction of intestine, part and extent unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.1', 'Chronic vascular disorders of intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.8', 'Other vascular disorders of intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K55.9', 'Vascular disorder of intestine, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M31.0', 'Hypersensitivity angiitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'P29.3', 'Persistent fetal circulation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'P29.30', 'Pulmonary hypertension of newborn')
,('http://hl7.org/fhir/sid/icd-10-cm', 'P29.38', 'Other persistent fetal circulation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.0', 'Common arterial trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.1', 'Double outlet right ventricle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.2', 'Double outlet left ventricle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.3', 'Discordant ventriculoarterial connection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.4', 'Double inlet ventricle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.5', 'Discordant atrioventricular connection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.6', 'Isomerism of atrial appendages')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.8', 'Other congenital malformations of cardiac chambers and connections')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q20.9', 'Congenital malformation of cardiac chambers and connections, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q21.0', 'Ventricular septal defect')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q21.1', 'Atrial septal defect')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q21.2', 'Atrioventricular septal defect')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q21.3', 'Tetralogy of Fallot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q21.4', 'Aortopulmonary septal defect')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q21.8', 'Other congenital malformations of cardiac septa')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q21.9', 'Congenital malformation of cardiac septum, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.0', 'Pulmonary valve atresia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.1', 'Congenital pulmonary valve stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.2', 'Congenital pulmonary valve insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.3', 'Other congenital malformations of pulmonary valve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.4', 'Congenital tricuspid stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.5', 'Ebsteins anomaly')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.6', 'Hypoplastic right heart syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.8', 'Other congenital malformations of tricuspid valve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q22.9', 'Congenital malformation of tricuspid valve, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q23.0', 'Congenital stenosis of aortic valve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q23.1', 'Congenital insufficiency of aortic valve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q23.2', 'Congenital mitral stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q23.3', 'Congenital mitral insufficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q23.4', 'Hypoplastic left heart syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q23.8', 'Other congenital malformations of aortic and mitral valves')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q23.9', 'Congenital malformation of aortic and mitral valves, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.0', 'Dextrocardia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.1', 'Levocardia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.2', 'Cor triatriatum')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.3', 'Pulmonary infundibular stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.4', 'Congenital subaortic stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.5', 'Malformation of coronary vessels')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.6', 'Congenital heart block')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.8', 'Other specified congenital malformations of heart')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q24.9', 'Congenital malformation of heart, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.0', 'Patent ductus arteriosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.1', 'Coarctation of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.2', 'Atresia of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.21', 'Interruption of aortic arch')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.29', 'Other atresia of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.3', 'Supravalvular aortic stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.4', 'Other congenital malformations of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.40', 'Congenital malformation of aorta unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.41', 'Absence and aplasia of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.42', 'Hypoplasia of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.43', 'Congenital aneurysm of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.44', 'Congenital dilation of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.45', 'Double aortic arch')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.46', 'Tortuous aortic arch')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.47', 'Right aortic arch')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.48', 'Anomalous origin of subclavian artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.49', 'Other congenital malformations of aorta')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.5', 'Atresia of pulmonary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.6', 'Stenosis of pulmonary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.71', 'Coarctation of pulmonary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.72', 'Congenital pulmonary arteriovenous malformation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.79', 'Other congenital malformations of pulmonary artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.8', 'Other congenital malformations of other great arteries')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q25.9', 'Congenital malformation of great arteries, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.0', 'Congenital stenosis of vena cava')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.1', 'Persistent left superior vena cava')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.2', 'Total anomalous pulmonary venous connection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.3', 'Partial anomalous pulmonary venous connection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.4', 'Anomalous pulmonary venous connection, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.5', 'Anomalous portal venous connection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.6', 'Portal vein-hepatic artery fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.8', 'Other congenital malformations of great veins')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q26.9', 'Congenital malformation of great vein, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.0', 'Congenital absence and hypoplasia of umbilical artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.1', 'Congenital renal artery stenosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.2', 'Other congenital malformations of renal artery')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.30', 'Arteriovenous malformation, site unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.31', 'Arteriovenous malformation of vessel of upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.32', 'Arteriovenous malformation of vessel of lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.33', 'Arteriovenous malformation of digestive system vessel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.34', 'Arteriovenous malformation of renal vessel')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.39', 'Arteriovenous malformation, other site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.4', 'Congenital phlebectasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.8', 'Other specified congenital malformations of peripheral vascular system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q27.9', 'Congenital malformation of peripheral vascular system, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q28.0', 'Arteriovenous malformation of precerebral vessels')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q28.1', 'Other malformations of precerebral vessels')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q28.2', 'Arteriovenous malformation of cerebral vessels')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q28.3', 'Other malformations of cerebral vessels')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q28.8', 'Other specified congenital malformations of circulatory system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q28.9', 'Congenital malformation of circulatory system, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R00.0', 'Tachycardia, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R00.1', 'Bradycardia, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R00.2', 'Palpitations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R00.8', 'Other abnormalities of heart beat')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R00.9', 'Unspecified abnormalities of heart beat')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R01.0', 'Benign and innocent cardiac murmurs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R01.1', 'Cardiac murmur, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R01.2', 'Other cardiac sounds')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R03.0', 'Elevated blood-pressure reading, without diagnosis of hypertension')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R03.1', 'Nonspecific low blood-pressure reading')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R07.2', 'Precordial pain')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R07.82', 'Intercostal pain')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R07.89', 'Other chest pain')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R07.9', 'Chest pain, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R09.89', 'Other specified symptoms and signs involving the circulatory and respiratory systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R58', 'Hemorrhage, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z45.010', 'Encounter for checking and testing of cardiac pacemaker pulse generator [battery]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z45.018', 'Encounter for adjustment and management of other part of cardiac pacemaker')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z45.02', 'Encounter for adjustment and management of automatic implantable cardiac defibrillator')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z45.09', 'Encounter for adjustment and management of other cardiac device')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z86.73', 'Personal history of transient ischemic attack (TIA), and cerebral infarction without residual deficits')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z86.74', 'Personal history of sudden cardiac arrest')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z86.79', 'Personal history of other diseases of the circulatory system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z87.74', 'Personal history of (corrected) congenital malformations of heart and circulatory system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.1', 'Heart transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.3', 'Heart and lungs transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.0', 'Presence of cardiac pacemaker')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.1', 'Presence of aortocoronary bypass graft')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.2', 'Presence of prosthetic heart valve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.3', 'Presence of xenogenic heart valve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.4', 'Presence of other heart-valve replacement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.5', 'Presence of coronary angioplasty implant and graft')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.810', 'Presence of automatic (implantable) cardiac defibrillator')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.811', 'Presence of heart assist device')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.812', 'Presence of fully implantable artificial heart')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.818', 'Presence of other cardiac implants and grafts')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.820', 'Peripheral vascular angioplasty status with implants and grafts')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.828', 'Presence of other vascular implants and grafts')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z95.9', 'Presence of cardiac and vascular implant and graft, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z98.61', 'Coronary angioplasty status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z98.62', 'Peripheral vascular angioplasty status')
) AS t (system, code, display) ;