create or replace view irae__dx_heart_failure as select * from (values
('http://snomed.info/sct', '10091002', 'High output heart failure (disorder)')
,('http://snomed.info/sct', '101281000119107', 'Congestive heart failure due to cardiomyopathy (disorder)')
,('http://snomed.info/sct', '10335000', 'Chronic right-sided heart failure (disorder)')
,('http://snomed.info/sct', '10633002', 'Acute congestive heart failure (disorder)')
,('http://snomed.info/sct', '111283005', 'Chronic left-sided heart failure (disorder)')
,('http://snomed.info/sct', '113901000052102', 'Heart failure following administration of antineoplastic agent (disorder)')
,('http://snomed.info/sct', '1204200007', 'Left ventricular failure with normal ejection fraction due to valvular heart disease (disorder)')
,('http://snomed.info/sct', '1204203009', 'Left ventricular failure with normal ejection fraction due to coronary arteriosclerosis (disorder)')
,('http://snomed.info/sct', '1204204003', 'Left ventricular failure with normal ejection fraction due to myocarditis (disorder)')
,('http://snomed.info/sct', '1204206001', 'Left ventricular failure with normal ejection fraction due to cardiomyopathy (disorder)')
,('http://snomed.info/sct', '1204460007', 'Myocardial dysfunction with sepsis (disorder)')
,('http://snomed.info/sct', '1204462004', 'Left ventricular failure with sepsis (disorder)')
,('http://snomed.info/sct', '1204468000', 'Right ventricular failure with sepsis (disorder)')
,('http://snomed.info/sct', '120851000119104', 'Systolic heart failure stage D (disorder)')
,('http://snomed.info/sct', '120861000119102', 'Systolic heart failure stage C (disorder)')
,('http://snomed.info/sct', '120871000119108', 'Systolic heart failure stage B (disorder)')
,('http://snomed.info/sct', '120881000119106', 'Diastolic heart failure stage D (disorder)')
,('http://snomed.info/sct', '1208843003', 'Right ventricular failure due to heart valve disorder (disorder)')
,('http://snomed.info/sct', '1208846006', 'Right ventricular failure due to disorder of lung (disorder)')
,('http://snomed.info/sct', '1208848007', 'Right ventricular failure due to disorder of pulmonary circulation (disorder)')
,('http://snomed.info/sct', '1208850004', 'Right ventricular failure due to right ventricular infarction (disorder)')
,('http://snomed.info/sct', '120891000119109', 'Diastolic heart failure stage C (disorder)')
,('http://snomed.info/sct', '120901000119108', 'Diastolic heart failure stage B (disorder)')
,('http://snomed.info/sct', '1264003007', 'Acute right ventricular failure following incision of heart (disorder)')
,('http://snomed.info/sct', '1296659009', 'Acute exacerbation of chronic heart failure (disorder)')
,('http://snomed.info/sct', '13839000', 'Bernheims syndrome (disorder)')
,('http://snomed.info/sct', '153931000119109', 'Acute combined systolic and diastolic heart failure (disorder)')
,('http://snomed.info/sct', '153941000119100', 'Chronic combined systolic and diastolic heart failure (disorder)')
,('http://snomed.info/sct', '153951000119103', 'Acute on chronic combined systolic and diastolic heart failure (disorder)')
,('http://snomed.info/sct', '15629541000119106', 'Congestive heart failure stage C due to ischemic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '15629591000119103', 'Congestive heart failure stage B due to ischemic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '15629641000119107', 'Systolic heart failure stage B due to ischemic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '15629741000119102', 'Systolic heart failure stage C due to ischemic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '15781000119107', 'Hypertensive heart AND chronic kidney disease with congestive heart failure (disorder)')
,('http://snomed.info/sct', '15964661000119102', 'Acute cor pulmonale due to septic pulmonary embolism (disorder)')
,('http://snomed.info/sct', '15964701000119109', 'Acute cor pulmonale co-occurrent and due to saddle embolus of pulmonary artery (disorder)')
,('http://snomed.info/sct', '16253001', 'Dilated peripartum cardiomyopathy (disorder)')
,('http://snomed.info/sct', '16838951000119100', 'Acute on chronic right-sided congestive heart failure (disorder)')
,('http://snomed.info/sct', '194767001', 'Benign hypertensive heart disease with congestive cardiac failure (disorder)')
,('http://snomed.info/sct', '194779001', 'Hypertensive heart and renal disease with (congestive) heart failure (disorder)')
,('http://snomed.info/sct', '194781004', 'Hypertensive heart and renal disease with both (congestive) heart failure and renal failure (disorder)')
,('http://snomed.info/sct', '195111005', 'Decompensated cardiac failure (disorder)')
,('http://snomed.info/sct', '195112003', 'Compensated cardiac failure (disorder)')
,('http://snomed.info/sct', '195114002', 'Acute left ventricular failure (disorder)')
,('http://snomed.info/sct', '206586007', 'Congenital cardiac failure (disorder)')
,('http://snomed.info/sct', '23341000119109', 'Congestive heart failure with right heart failure (disorder)')
,('http://snomed.info/sct', '233924009', 'Heart failure as a complication of care (disorder)')
,('http://snomed.info/sct', '24841007', 'Cardiorespiratory failure during AND/OR resulting from a procedure (disorder)')
,('http://snomed.info/sct', '25544003', 'Low output heart failure (disorder)')
,('http://snomed.info/sct', '276514007', 'Neonatal cardiac failure (disorder)')
,('http://snomed.info/sct', '285211000119102', 'Congestive heart failure as post-operative complication of cardiac surgery (disorder)')
,('http://snomed.info/sct', '285221000119109', 'Congestive heart failure as post-operative complication of non-cardiac surgery (disorder)')
,('http://snomed.info/sct', '314206003', 'Refractory heart failure (disorder)')
,('http://snomed.info/sct', '33644002', 'Postvalvulotomy syndrome (disorder)')
,('http://snomed.info/sct', '359617009', 'Acute right-sided heart failure (disorder)')
,('http://snomed.info/sct', '364006', 'Acute left-sided heart failure (disorder)')
,('http://snomed.info/sct', '367363000', 'Right ventricular failure (disorder)')
,('http://snomed.info/sct', '410431009', 'Cardiorespiratory failure (disorder)')
,('http://snomed.info/sct', '417996009', 'Systolic heart failure (disorder)')
,('http://snomed.info/sct', '418304008', 'Diastolic heart failure (disorder)')
,('http://snomed.info/sct', '42343007', 'Congestive heart failure (disorder)')
,('http://snomed.info/sct', '424404003', 'Decompensated chronic heart failure (disorder)')
,('http://snomed.info/sct', '426263006', 'Congestive heart failure due to left ventricular systolic dysfunction (disorder)')
,('http://snomed.info/sct', '426611007', 'Congestive heart failure due to valvular disease (disorder)')
,('http://snomed.info/sct', '43736008', 'Rheumatic left ventricular failure (disorder)')
,('http://snomed.info/sct', '44088000', 'Low cardiac output syndrome (disorder)')
,('http://snomed.info/sct', '441481004', 'Chronic systolic heart failure (disorder)')
,('http://snomed.info/sct', '441530006', 'Chronic diastolic heart failure (disorder)')
,('http://snomed.info/sct', '44313006', 'Right heart failure secondary to left heart failure (disorder)')
,('http://snomed.info/sct', '443253003', 'Acute on chronic systolic heart failure (disorder)')
,('http://snomed.info/sct', '443254009', 'Acute systolic heart failure (disorder)')
,('http://snomed.info/sct', '443343001', 'Acute diastolic heart failure (disorder)')
,('http://snomed.info/sct', '443344007', 'Acute on chronic diastolic heart failure (disorder)')
,('http://snomed.info/sct', '445236007', 'Cardiorenal syndrome (disorder)')
,('http://snomed.info/sct', '446221000', 'Heart failure with normal ejection fraction (disorder)')
,('http://snomed.info/sct', '45650007', 'Kyphoscoliotic heart disease (disorder)')
,('http://snomed.info/sct', '46113002', 'Hypertensive heart failure (disorder)')
,('http://snomed.info/sct', '462172006', 'Fetal heart failure (disorder)')
,('http://snomed.info/sct', '462174007', 'Fetal heart failure with myocardial hypertrophy (disorder)')
,('http://snomed.info/sct', '462175008', 'Fetal heart failure with redistribution of cardiac output (disorder)')
,('http://snomed.info/sct', '471880001', 'Heart failure due to end stage congenital heart disease (disorder)')
,('http://snomed.info/sct', '48447003', 'Chronic heart failure (disorder)')
,('http://snomed.info/sct', '49584005', 'Acute cor pulmonale (disorder)')
,('http://snomed.info/sct', '5053004', 'Cardiac insufficiency due to prosthesis (disorder)')
,('http://snomed.info/sct', '5148006', 'Hypertensive heart disease with congestive heart failure (disorder)')
,('http://snomed.info/sct', '5375005', 'Chronic left-sided congestive heart failure (disorder)')
,('http://snomed.info/sct', '55565007', 'Cardiac failure after obstetrical surgery AND/OR other procedure including delivery (disorder)')
,('http://snomed.info/sct', '56675007', 'Acute heart failure (disorder)')
,('http://snomed.info/sct', '60856006', 'Cardiac insufficiency following cardiac surgery (disorder)')
,('http://snomed.info/sct', '609507007', 'Induced termination of pregnancy complicated by cardiac failure (disorder)')
,('http://snomed.info/sct', '62377009', 'Postpartum cardiomyopathy (disorder)')
,('http://snomed.info/sct', '66989003', 'Chronic right-sided congestive heart failure (disorder)')
,('http://snomed.info/sct', '67431000119105', 'Congestive heart failure stage D (disorder)')
,('http://snomed.info/sct', '67441000119101', 'Congestive heart failure stage C (disorder)')
,('http://snomed.info/sct', '698296002', 'Acute exacerbation of chronic congestive heart failure (disorder)')
,('http://snomed.info/sct', '698594003', 'Symptomatic congestive heart failure (disorder)')
,('http://snomed.info/sct', '703272007', 'Heart failure with reduced ejection fraction (disorder)')
,('http://snomed.info/sct', '703273002', 'Heart failure with reduced ejection fraction due to coronary artery disease (disorder)')
,('http://snomed.info/sct', '703274008', 'Heart failure with reduced ejection fraction due to myocarditis (disorder)')
,('http://snomed.info/sct', '703275009', 'Heart failure with reduced ejection fraction due to cardiomyopathy (disorder)')
,('http://snomed.info/sct', '703276005', 'Heart failure with reduced ejection fraction due to heart valve disease (disorder)')
,('http://snomed.info/sct', '704242009', 'Fetal heart failure due to extracardiac disease (disorder)')
,('http://snomed.info/sct', '717840005', 'Congestive heart failure stage B (disorder)')
,('http://snomed.info/sct', '71892000', 'Cardiac asthma (disorder)')
,('http://snomed.info/sct', '722095005', 'Acute kidney injury due to circulatory failure (disorder)')
,('http://snomed.info/sct', '722919003', 'Neonatal cardiac failure due to decreased left ventricular output (disorder)')
,('http://snomed.info/sct', '724550005', 'Neonatal cardiac failure due to pulmonary overperfusion (disorder)')
,('http://snomed.info/sct', '72481000119103', 'Congestive heart failure as early postoperative complication (disorder)')
,('http://snomed.info/sct', '7371000175103', 'Reduced ejection fraction co-occurrent and due to acute on chronic heart failure (disorder)')
,('http://snomed.info/sct', '7381000175100', 'Reduced ejection fraction co-occurrent and due to chronic heart failure (disorder)')
,('http://snomed.info/sct', '7391000175102', 'Reduced ejection fraction co-occurrent and due to acute heart failure (disorder)')
,('http://snomed.info/sct', '7401000175100', 'Acute on chronic heart failure co-occurrent with normal ejection fraction (disorder)')
,('http://snomed.info/sct', '7411000175102', 'Chronic heart failure co-occurrent with normal ejection fraction (disorder)')
,('http://snomed.info/sct', '7421000175106', 'Acute heart failure co-occurrent with normal ejection fraction (disorder)')
,('http://snomed.info/sct', '74960003', 'Acute left-sided congestive heart failure (disorder)')
,('http://snomed.info/sct', '78862003', 'Ayerzas syndrome (disorder)')
,('http://snomed.info/sct', '788950000', 'Heart failure with mid range ejection fraction (disorder)')
,('http://snomed.info/sct', '79955004', 'Chronic cor pulmonale (disorder)')
,('http://snomed.info/sct', '80479009', 'Acute right-sided congestive heart failure (disorder)')
,('http://snomed.info/sct', '82523003', 'Congestive rheumatic heart failure (disorder)')
,('http://snomed.info/sct', '83105008', 'Malignant hypertensive heart disease with congestive heart failure (disorder)')
,('http://snomed.info/sct', '83291003', 'Cor pulmonale (disorder)')
,('http://snomed.info/sct', '84114007', 'Heart failure (disorder)')
,('http://snomed.info/sct', '85232009', 'Left heart failure (disorder)')
,('http://snomed.info/sct', '871617000', 'Low output heart failure due to and following Fontan operation (disorder)')
,('http://snomed.info/sct', '88805009', 'Chronic congestive heart failure (disorder)')
,('http://snomed.info/sct', '89819002', 'Cardiac insufficiency during AND/OR resulting from a procedure (disorder)')
,('http://snomed.info/sct', '898208007', 'Heart failure due to thyrotoxicosis (disorder)')
,('http://snomed.info/sct', '92506005', 'Biventricular congestive heart failure (disorder)')
,('http://snomed.info/sct', '96311000119109', 'Exacerbation of congestive heart failure (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I11.0', 'Hypertensive heart disease with heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50', 'Heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.1', 'Left ventricular failure, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.2', 'Systolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.20', 'Unspecified systolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.21', 'Acute systolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.22', 'Chronic systolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.23', 'Acute on chronic systolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.3', 'Diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.30', 'Unspecified diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.31', 'Acute diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.32', 'Chronic diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.33', 'Acute on chronic diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.4', 'Combined systolic (congestive) and diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.40', 'Unspecified combined systolic (congestive) and diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.41', 'Acute combined systolic (congestive) and diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.42', 'Chronic combined systolic (congestive) and diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.43', 'Acute on chronic combined systolic (congestive) and diastolic (congestive) heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.8', 'Other heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.81', 'Right heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.810', 'Right heart failure, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.811', 'Acute right heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.812', 'Chronic right heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.813', 'Acute on chronic right heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.814', 'Right heart failure due to left heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.82', 'Biventricular heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.83', 'High output heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.84', 'End stage heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.89', 'Other heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I50.9', 'Heart failure, unspecified')
) AS t (system, code, display) ;