create or replace view irae__rx_diuretics_thiazide as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1000000', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1000001', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1000003', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1000005', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008801', 'amlodipine / hydrochlorothiazide / olmesartan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011710', 'aliskiren 150 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011711', 'aliskiren 150 MG / hydrochlorothiazide 12.5 MG [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011712', 'aliskiren 150 MG / hydrochlorothiazide 12.5 MG Oral Tablet [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011713', 'aliskiren 150 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011714', 'aliskiren 150 MG / hydrochlorothiazide 25 MG [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011715', 'aliskiren 150 MG / hydrochlorothiazide 25 MG Oral Tablet [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011750', 'aliskiren 300 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011751', 'aliskiren 300 MG / hydrochlorothiazide 12.5 MG [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011752', 'aliskiren 300 MG / hydrochlorothiazide 12.5 MG Oral Tablet [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011753', 'aliskiren 300 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011754', 'aliskiren 300 MG / hydrochlorothiazide 25 MG [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011755', 'aliskiren 300 MG / hydrochlorothiazide 25 MG Oral Tablet [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1151607', 'amiloride / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1151608', 'amiloride / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1152277', 'amlodipine / hydrochlorothiazide / olmesartan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1152278', 'amlodipine / hydrochlorothiazide / olmesartan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1152279', 'amlodipine / hydrochlorothiazide / valsartan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1152280', 'amlodipine / hydrochlorothiazide / valsartan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154370', 'atenolol / chlorthalidone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154371', 'atenolol / chlorthalidone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154704', 'bisoprolol / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154705', 'bisoprolol / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155750', 'captopril / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155751', 'captopril / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155783', 'chlorthalidone / clonidine Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155784', 'chlorthalidone / clonidine Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155795', 'chlorthalidone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155796', 'chlorthalidone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156302', 'indapamide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156303', 'indapamide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156609', 'candesartan / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156610', 'candesartan / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1160005', 'benazepril / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1160006', 'benazepril / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161918', 'eprosartan / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161919', 'eprosartan / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162124', 'hydrochlorothiazide / lisinopril Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162125', 'hydrochlorothiazide / lisinopril Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162126', 'hydrochlorothiazide / losartan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162127', 'hydrochlorothiazide / losartan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162130', 'hydrochlorothiazide / methyldopa Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162131', 'hydrochlorothiazide / methyldopa Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162132', 'hydrochlorothiazide / metoprolol Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162133', 'hydrochlorothiazide / metoprolol Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162138', 'hydrochlorothiazide / propranolol Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162139', 'hydrochlorothiazide / propranolol Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162146', 'hydrochlorothiazide / spironolactone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162147', 'hydrochlorothiazide / spironolactone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162152', 'hydrochlorothiazide / triamterene Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162153', 'hydrochlorothiazide / triamterene Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162156', 'hydrochlorothiazide / irbesartan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162157', 'hydrochlorothiazide / irbesartan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162649', 'enalapril / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162650', 'enalapril / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162674', 'fosinopril / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162675', 'fosinopril / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162775', 'hydrochlorothiazide / moexipril Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162776', 'hydrochlorothiazide / moexipril Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162777', 'hydrochlorothiazide / olmesartan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162778', 'hydrochlorothiazide / olmesartan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162779', 'hydrochlorothiazide / quinapril Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162780', 'hydrochlorothiazide / quinapril Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162781', 'hydrochlorothiazide / telmisartan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162782', 'hydrochlorothiazide / telmisartan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162783', 'hydrochlorothiazide / valsartan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162784', 'hydrochlorothiazide / valsartan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162786', 'hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162787', 'hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163518', 'metolazone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163519', 'metolazone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164883', 'aliskiren / hydrochlorothiazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164884', 'aliskiren / hydrochlorothiazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1166546', 'Hyzaar Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1166549', 'Hyzaar Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1168391', 'Accuretic Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1168392', 'Accuretic Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169653', 'Dutoprol Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169654', 'Dutoprol Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169664', 'Dyazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169665', 'Dyazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170817', 'Benicar HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170818', 'Benicar HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1171082', 'Diovan HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1171087', 'Diovan HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172182', 'Atacand HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172183', 'Atacand HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1173249', 'Exforge HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1173250', 'Exforge HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1173699', 'Clorpres Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1173700', 'Clorpres Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1174846', 'Aldactazide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1174847', 'Aldactazide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1175010', 'Avalide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1175011', 'Avalide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1178060', 'Micardis-HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1178061', 'Micardis-HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180272', 'Lopressor HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180275', 'Lopressor HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180897', 'Lotensin HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180902', 'Lotensin HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182013', 'Tenoretic Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182014', 'Tenoretic Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182147', 'Tribenzor Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182686', 'Tribenzor Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182741', 'Maxzide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182742', 'Maxzide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184927', 'Thalitone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184928', 'Thalitone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187277', 'Zestoretic Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187278', 'Zestoretic Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187449', 'Ziac Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187450', 'Ziac Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187581', 'Vaseretic Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187582', 'Vaseretic Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235140', 'azilsartan / chlorthalidone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235141', 'azilsartan / chlorthalidone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235142', 'azilsartan / chlorthalidone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235143', 'azilsartan / chlorthalidone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235144', 'azilsartan medoxomil 40 MG / chlorthalidone 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235146', 'azilsartan medoxomil 40 MG / chlorthalidone 12.5 MG [Edarbyclor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235147', 'azilsartan / chlorthalidone Oral Tablet [Edarbyclor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235148', 'Edarbyclor Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235149', 'Edarbyclor Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235150', 'azilsartan medoxomil 40 MG / chlorthalidone 12.5 MG Oral Tablet [Edarbyclor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235151', 'azilsartan medoxomil 40 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235153', 'azilsartan medoxomil 40 MG / chlorthalidone 25 MG [Edarbyclor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235157', 'azilsartan medoxomil 40 MG / chlorthalidone 25 MG Oral Tablet [Edarbyclor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299859', 'hydrochlorothiazide 12.5 MG / moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299871', 'hydrochlorothiazide 12.5 MG / moexipril hydrochloride 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1299890', 'hydrochlorothiazide 25 MG / moexipril hydrochloride 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1370476', 'hydrochlorothiazide 12.5 MG / metoprolol succinate 50 MG [Dutoprol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1370491', 'hydrochlorothiazide 12.5 MG / metoprolol succinate 25 MG [Dutoprol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1370496', 'hydrochlorothiazide 12.5 MG / metoprolol succinate 100 MG [Dutoprol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1372709', 'Dutoprol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1372732', 'Tribenzor')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1372733', 'Exforge HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1372759', 'Edarbyclor')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1430137', 'Tekturna HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1430140', 'Tekturna HCT Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1430141', 'Tekturna HCT Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '151195', 'atenolol / chlorthalidone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '151293', 'Accuretic')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '17276', 'Aldactazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '175128', 'Vaseretic')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197382', 'atenolol 100 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197383', 'atenolol 50 MG / chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197436', 'captopril 25 MG / hydrochlorothiazide 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197437', 'captopril 25 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197438', 'captopril 50 MG / hydrochlorothiazide 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197439', 'captopril 50 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197498', 'chlorthalidone 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197499', 'chlorthalidone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197500', 'chlorthalidone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197770', 'hydrochlorothiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197815', 'indapamide 1.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197816', 'indapamide 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197885', 'hydrochlorothiazide 12.5 MG / lisinopril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197886', 'hydrochlorothiazide 12.5 MG / lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197887', 'hydrochlorothiazide 25 MG / lisinopril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197960', 'hydrochlorothiazide 25 MG / methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197963', 'hydrochlorothiazide 15 MG / methyldopa 250 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197978', 'metolazone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197979', 'metolazone 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198224', 'hydrochlorothiazide 25 MG / spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198225', 'hydrochlorothiazide 50 MG / spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198314', 'hydrochlorothiazide 25 MG / triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198316', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199903', 'hydrochlorothiazide 12.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200284', 'hydrochlorothiazide 12.5 MG / valsartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200285', 'hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203477', 'Thalitone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208112', 'hydrochlorothiazide 25 MG / spironolactone 25 MG Oral Tablet [Aldactazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208116', 'hydrochlorothiazide 50 MG / spironolactone 50 MG Oral Tablet [Aldactazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208124', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Capsule [Dyazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214081', 'chlorthalidone 15 MG Oral Tablet [Thalitone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214083', 'chlorthalidone 25 MG Oral Tablet [Thalitone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214212', 'amiloride / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214287', 'benazepril / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214317', 'bisoprolol / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214357', 'captopril / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214418', 'chlorthalidone / clonidine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214536', 'enalapril / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214617', 'hydrochlorothiazide / irbesartan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214618', 'hydrochlorothiazide / lisinopril')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214619', 'hydrochlorothiazide / losartan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214620', 'hydrochlorothiazide / methyldopa')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214621', 'hydrochlorothiazide / metoprolol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214622', 'hydrochlorothiazide / moexipril')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214623', 'hydrochlorothiazide / propranolol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214626', 'hydrochlorothiazide / valsartan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '216099', 'Clorpres')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '216653', 'Diovan HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '217681', 'Hyzaar')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '218072', 'Lopressor HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '218089', 'Lotensin HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '23742', 'Dyazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2409', 'chlorthalidone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '258337', 'hydrochlorothiazide / triamterene')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261415', 'fosinopril / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261417', 'hydrochlorothiazide / quinapril')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261454', 'Avalide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283316', 'hydrochlorothiazide 12.5 MG / telmisartan 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283317', 'hydrochlorothiazide 12.5 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284628', 'candesartan / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284636', 'hydrochlorothiazide / telmisartan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284662', 'Atacand HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284780', 'Micardis-HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310792', 'hydrochlorothiazide 12.5 MG / irbesartan 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310793', 'hydrochlorothiazide 12.5 MG / irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310796', 'hydrochlorothiazide 12.5 MG / quinapril 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310797', 'hydrochlorothiazide 12.5 MG / quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310798', 'hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310809', 'hydrochlorothiazide 25 MG / quinapril 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310812', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310818', 'hydrochlorothiazide 50 MG / triamterene 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311671', 'metolazone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315654', 'chlorthalidone 15 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315655', 'chlorthalidone 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316047', 'hydrochlorothiazide 12.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316048', 'hydrochlorothiazide 15 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316049', 'hydrochlorothiazide 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316051', 'hydrochlorothiazide 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316052', 'hydrochlorothiazide 6.25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316079', 'indapamide 1.25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316080', 'indapamide 2.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316297', 'metolazone 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316298', 'metolazone 2.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316299', 'metolazone 5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317328', 'chlorthalidone 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '324042', 'hydrochlorothiazide / spironolactone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '331132', 'chlorthalidone 12.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349353', 'hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351292', 'eprosartan 600 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351293', 'eprosartan 600 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '352375', 'eprosartan / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366289', 'hydrochlorothiazide / triamterene Oral Capsule [Dyazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '368711', 'chlorthalidone Oral Tablet [Thalitone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369275', 'hydrochlorothiazide / triamterene Oral Tablet [Maxzide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369279', 'hydrochlorothiazide / spironolactone Oral Tablet [Aldactazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370620', 'atenolol / chlorthalidone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370635', 'hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370636', 'hydrochlorothiazide Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370638', 'amiloride / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370639', 'hydrochlorothiazide / spironolactone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370640', 'hydrochlorothiazide / triamterene Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370682', 'indapamide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370705', 'hydrochlorothiazide / irbesartan Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371000', 'benazepril / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371103', 'bisoprolol / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371253', 'captopril / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371472', 'chlorthalidone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371580', 'chlorthalidone / clonidine Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372006', 'enalapril / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372273', 'fosinopril / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372613', 'hydrochlorothiazide / lisinopril Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372650', 'hydrochlorothiazide / losartan Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372853', 'hydrochlorothiazide / methyldopa Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372888', 'metolazone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372889', 'hydrochlorothiazide / metoprolol Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372890', 'hydrochlorothiazide / metoprolol Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372946', 'hydrochlorothiazide / moexipril Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373651', 'hydrochlorothiazide / propranolol Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373732', 'hydrochlorothiazide / quinapril Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374192', 'hydrochlorothiazide / triamterene Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374280', 'hydrochlorothiazide / valsartan Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374934', 'candesartan / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '37789', 'Tenoretic')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '378735', 'eprosartan / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '378921', 'hydrochlorothiazide / telmisartan Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403853', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403854', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '403855', 'hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404880', 'Benicar HCT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '406041', 'hydrochlorothiazide / olmesartan Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '429503', 'hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '477130', 'hydrochlorothiazide 25 MG / telmisartan 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485471', 'hydrochlorothiazide 25 MG / irbesartan 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '52440', 'Maxzide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '5487', 'hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562901', 'hydrochlorothiazide 50 MG / triamterene 75 MG [Maxzide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562902', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG [Maxzide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '568840', 'hydrochlorothiazide 25 MG / spironolactone 25 MG [Aldactazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '568844', 'hydrochlorothiazide 50 MG / spironolactone 50 MG [Aldactazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '568851', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG [Dyazide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '573920', 'chlorthalidone 15 MG [Thalitone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '573922', 'chlorthalidone 25 MG [Thalitone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '5764', 'indapamide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578325', 'candesartan cilexetil 16 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578330', 'candesartan cilexetil 32 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636042', 'hydrochlorothiazide 12.5 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636045', 'hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '6916', 'metolazone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '745976', 'bisoprolol / hydrochlorothiazide Oral Tablet [Ziac]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '746021', 'atenolol 100 MG / chlorthalidone 25 MG [Tenoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '746022', 'atenolol / chlorthalidone Oral Tablet [Tenoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '746023', 'atenolol 100 MG / chlorthalidone 25 MG Oral Tablet [Tenoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '746028', 'atenolol 50 MG / chlorthalidone 25 MG [Tenoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '746030', 'atenolol 50 MG / chlorthalidone 25 MG Oral Tablet [Tenoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '749831', 'hydrochlorothiazide 12.5 MG / telmisartan 40 MG [Micardis-HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '749833', 'hydrochlorothiazide 12.5 MG / telmisartan 40 MG Oral Tablet [Micardis-HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '749835', 'hydrochlorothiazide 12.5 MG / telmisartan 80 MG [Micardis-HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '749836', 'hydrochlorothiazide / telmisartan Oral Tablet [Micardis-HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '749837', 'hydrochlorothiazide 12.5 MG / telmisartan 80 MG Oral Tablet [Micardis-HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '749839', 'hydrochlorothiazide 25 MG / telmisartan 80 MG [Micardis-HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '749841', 'hydrochlorothiazide 25 MG / telmisartan 80 MG Oral Tablet [Micardis-HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '75038', 'Ziac')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '754717', 'aliskiren / hydrochlorothiazide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '758550', 'aliskiren / hydrochlorothiazide Oral Tablet [Tekturna HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '802519', 'aliskiren / hydrochlorothiazide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '802749', 'candesartan cilexetil 32 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '805853', 'candesartan cilexetil 32 MG / hydrochlorothiazide 25 MG [Atacand HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '805854', 'candesartan / hydrochlorothiazide Oral Tablet [Atacand HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '805855', 'candesartan cilexetil 32 MG / hydrochlorothiazide 25 MG Oral Tablet [Atacand HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '805857', 'candesartan cilexetil 32 MG / hydrochlorothiazide 12.5 MG [Atacand HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '805859', 'candesartan cilexetil 32 MG / hydrochlorothiazide 12.5 MG Oral Tablet [Atacand HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '805861', 'candesartan cilexetil 16 MG / hydrochlorothiazide 12.5 MG [Atacand HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '805863', 'candesartan cilexetil 16 MG / hydrochlorothiazide 12.5 MG Oral Tablet [Atacand HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809012', 'hydrochlorothiazide 12.5 MG / valsartan 80 MG [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809014', 'hydrochlorothiazide 12.5 MG / valsartan 80 MG Oral Tablet [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809016', 'hydrochlorothiazide 12.5 MG / valsartan 160 MG [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809018', 'hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809020', 'hydrochlorothiazide 25 MG / valsartan 160 MG [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809022', 'hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809024', 'hydrochlorothiazide 12.5 MG / valsartan 320 MG [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809026', 'hydrochlorothiazide 12.5 MG / valsartan 320 MG Oral Tablet [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809028', 'hydrochlorothiazide 25 MG / valsartan 320 MG [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809029', 'hydrochlorothiazide / valsartan Oral Tablet [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809030', 'hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet [Diovan HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809852', 'hydrochlorothiazide 12.5 MG / quinapril 10 MG [Accuretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809853', 'hydrochlorothiazide / quinapril Oral Tablet [Accuretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809854', 'hydrochlorothiazide 12.5 MG / quinapril 10 MG Oral Tablet [Accuretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809856', 'hydrochlorothiazide 12.5 MG / quinapril 20 MG [Accuretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809858', 'hydrochlorothiazide 12.5 MG / quinapril 20 MG Oral Tablet [Accuretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '817496', 'hydrochlorothiazide / olmesartan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823932', 'hydrochlorothiazide 12.5 MG / irbesartan 150 MG [Avalide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823934', 'hydrochlorothiazide 12.5 MG / irbesartan 150 MG Oral Tablet [Avalide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823936', 'hydrochlorothiazide 12.5 MG / irbesartan 300 MG [Avalide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823937', 'hydrochlorothiazide / irbesartan Oral Tablet [Avalide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823938', 'hydrochlorothiazide 12.5 MG / irbesartan 300 MG Oral Tablet [Avalide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823962', 'hydrochlorothiazide / losartan Oral Tablet [Hyzaar]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823969', 'hydrochlorothiazide 25 MG / lisinopril 20 MG [Zestoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823970', 'hydrochlorothiazide / lisinopril Oral Tablet [Zestoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823971', 'hydrochlorothiazide 25 MG / lisinopril 20 MG Oral Tablet [Zestoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823980', 'hydrochlorothiazide 12.5 MG / lisinopril 20 MG [Zestoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823982', 'hydrochlorothiazide 12.5 MG / lisinopril 20 MG Oral Tablet [Zestoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823984', 'hydrochlorothiazide 12.5 MG / lisinopril 10 MG [Zestoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '823986', 'hydrochlorothiazide 12.5 MG / lisinopril 10 MG Oral Tablet [Zestoretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847040', 'hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG [Benicar HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847042', 'hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet [Benicar HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847053', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG [Benicar HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847055', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet [Benicar HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847058', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG [Benicar HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847059', 'hydrochlorothiazide / olmesartan Oral Tablet [Benicar HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847060', 'hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet [Benicar HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848130', 'amlodipine / hydrochlorothiazide / valsartan Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848131', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848132', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848134', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848135', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848137', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 320 MG [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848139', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 320 MG Oral Tablet [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848140', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848142', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848144', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / valsartan 160 MG Oral Tablet [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848145', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848147', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / valsartan 160 MG [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848148', 'amlodipine / hydrochlorothiazide / valsartan Oral Tablet [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848149', 'amlodipine 5 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848151', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848153', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 160 MG [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848155', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / valsartan 160 MG Oral Tablet [Exforge HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '852897', 'amlodipine / hydrochlorothiazide / valsartan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854908', 'bisoprolol fumarate 10 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854909', 'bisoprolol fumarate 10 MG / hydrochlorothiazide 6.25 MG [Ziac]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854910', 'bisoprolol fumarate 10 MG / hydrochlorothiazide 6.25 MG Oral Tablet [Ziac]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854916', 'bisoprolol fumarate 2.5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854917', 'bisoprolol fumarate 2.5 MG / hydrochlorothiazide 6.25 MG [Ziac]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854918', 'bisoprolol fumarate 2.5 MG / hydrochlorothiazide 6.25 MG Oral Tablet [Ziac]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854919', 'bisoprolol fumarate 5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854920', 'bisoprolol fumarate 5 MG / hydrochlorothiazide 6.25 MG [Ziac]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854921', 'bisoprolol fumarate 5 MG / hydrochlorothiazide 6.25 MG Oral Tablet [Ziac]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856422', 'hydrochlorothiazide 25 MG / propranolol hydrochloride 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856429', 'hydrochlorothiazide 25 MG / propranolol hydrochloride 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857166', 'fosinopril sodium 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '857174', 'fosinopril sodium 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '85783', 'Zestoretic')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858824', 'enalapril maleate 5 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858826', 'enalapril / hydrochlorothiazide Oral Tablet [Vaseretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858828', 'enalapril maleate 10 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858829', 'enalapril maleate 10 MG / hydrochlorothiazide 25 MG [Vaseretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858830', 'enalapril maleate 10 MG / hydrochlorothiazide 25 MG Oral Tablet [Vaseretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866452', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 100 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866455', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 100 MG Extended Release Oral Tablet [Dutoprol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866461', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 25 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866463', 'hydrochlorothiazide / metoprolol Extended Release Oral Tablet [Dutoprol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866464', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 25 MG Extended Release Oral Tablet [Dutoprol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866472', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 50 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866475', '24 HR hydrochlorothiazide 12.5 MG / metoprolol succinate 50 MG Extended Release Oral Tablet [Dutoprol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866479', 'hydrochlorothiazide 25 MG / metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866482', 'hydrochlorothiazide 25 MG / metoprolol tartrate 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866491', 'hydrochlorothiazide 50 MG / metoprolol tartrate 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866496', 'hydrochlorothiazide 25 MG / metoprolol tartrate 100 MG [Lopressor HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866497', 'hydrochlorothiazide / metoprolol Oral Tablet [Lopressor HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866498', 'hydrochlorothiazide 25 MG / metoprolol tartrate 100 MG Oral Tablet [Lopressor HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866500', 'hydrochlorothiazide 25 MG / metoprolol tartrate 50 MG [Lopressor HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866502', 'hydrochlorothiazide 25 MG / metoprolol tartrate 50 MG Oral Tablet [Lopressor HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866504', 'hydrochlorothiazide 50 MG / metoprolol tartrate 100 MG [Lopressor HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866506', 'hydrochlorothiazide 50 MG / metoprolol tartrate 100 MG Oral Tablet [Lopressor HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '882557', 'hydrochlorothiazide 25 MG / quinapril 20 MG [Accuretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '882559', 'hydrochlorothiazide 25 MG / quinapril 20 MG Oral Tablet [Accuretic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884192', 'chlorthalidone 15 MG / clonidine hydrochloride 0.1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884194', 'chlorthalidone 15 MG / clonidine hydrochloride 0.1 MG [Clorpres]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884195', 'chlorthalidone / clonidine Oral Tablet [Clorpres]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884196', 'chlorthalidone 15 MG / clonidine hydrochloride 0.1 MG Oral Tablet [Clorpres]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884198', 'chlorthalidone 15 MG / clonidine hydrochloride 0.2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884200', 'chlorthalidone 15 MG / clonidine hydrochloride 0.2 MG [Clorpres]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884202', 'chlorthalidone 15 MG / clonidine hydrochloride 0.2 MG Oral Tablet [Clorpres]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884203', 'chlorthalidone 15 MG / clonidine hydrochloride 0.3 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884205', 'chlorthalidone 15 MG / clonidine hydrochloride 0.3 MG [Clorpres]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '884207', 'chlorthalidone 15 MG / clonidine hydrochloride 0.3 MG Oral Tablet [Clorpres]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898362', 'benazepril hydrochloride 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898364', 'benazepril hydrochloride 10 MG / hydrochlorothiazide 12.5 MG [Lotensin HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898366', 'benazepril hydrochloride 10 MG / hydrochlorothiazide 12.5 MG Oral Tablet [Lotensin HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898367', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898369', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 12.5 MG [Lotensin HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898371', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 12.5 MG Oral Tablet [Lotensin HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898372', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898374', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 25 MG [Lotensin HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898376', 'benazepril hydrochloride 20 MG / hydrochlorothiazide 25 MG Oral Tablet [Lotensin HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898378', 'benazepril hydrochloride 5 MG / hydrochlorothiazide 6.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '898381', 'benazepril / hydrochlorothiazide Oral Tablet [Lotensin HCT]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '93252', 'hydrochlorothiazide 50 MG / triamterene 75 MG Oral Tablet [Maxzide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '93253', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Tablet [Maxzide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977883', 'amiloride hydrochloride 5 MG / hydrochlorothiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979464', 'hydrochlorothiazide 12.5 MG / losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979465', 'hydrochlorothiazide 12.5 MG / losartan potassium 100 MG [Hyzaar]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979466', 'hydrochlorothiazide 12.5 MG / losartan potassium 100 MG Oral Tablet [Hyzaar]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979468', 'hydrochlorothiazide 12.5 MG / losartan potassium 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979469', 'hydrochlorothiazide 12.5 MG / losartan potassium 50 MG [Hyzaar]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979470', 'hydrochlorothiazide 12.5 MG / losartan potassium 50 MG Oral Tablet [Hyzaar]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979471', 'hydrochlorothiazide 25 MG / losartan potassium 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979472', 'hydrochlorothiazide 25 MG / losartan potassium 100 MG [Hyzaar]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '979473', 'hydrochlorothiazide 25 MG / losartan potassium 100 MG Oral Tablet [Hyzaar]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999966', 'amlodipine / hydrochlorothiazide / olmesartan Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999967', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999969', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999970', 'amlodipine / hydrochlorothiazide / olmesartan Oral Tablet [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999971', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 20 MG Oral Tablet [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999986', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999988', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999990', 'amlodipine 10 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999991', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999993', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999995', 'amlodipine 10 MG / hydrochlorothiazide 25 MG / olmesartan medoxomil 40 MG Oral Tablet [Tribenzor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999996', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '999998', 'amlodipine 5 MG / hydrochlorothiazide 12.5 MG / olmesartan medoxomil 40 MG [Tribenzor]')
) AS t (system, code, display) ;