create or replace view irae__dx_htn_any as select * from (values
('http://snomed.info/sct', '1003728008', 'Fetal disorder due to maternal hypertension (disorder)')
,('http://snomed.info/sct', '1003729000', 'Fetal disorder due to maternal pre-eclampsia (disorder)')
,('http://snomed.info/sct', '104931000119100', 'Chronic kidney disease due to hypertension (disorder)')
,('http://snomed.info/sct', '10562009', 'Malignant hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '105651000119100', 'Past pregnancy history of pre-eclampsia (situation)')
,('http://snomed.info/sct', '10725009', 'Benign hypertension (disorder)')
,('http://snomed.info/sct', '10752641000119102', 'Eclampsia with pre-existing hypertension in childbirth (disorder)')
,('http://snomed.info/sct', '10757401000119104', 'Pre-existing hypertensive heart and chronic kidney disease in mother complicating childbirth (disorder)')
,('http://snomed.info/sct', '10757441000119102', 'Pre-existing hypertensive heart disease in mother complicating childbirth (disorder)')
,('http://snomed.info/sct', '10757481000119107', 'Pre-existing hypertensive heart and chronic kidney disease in mother complicating pregnancy (disorder)')
,('http://snomed.info/sct', '10759031000119106', 'Pre-existing hypertensive heart disease in mother complicating pregnancy (disorder)')
,('http://snomed.info/sct', '1078301000112109', 'Multiple drug intolerant hypertension (disorder)')
,('http://snomed.info/sct', '108701000119102', 'Cardiomyopathy due to hypertension (disorder)')
,('http://snomed.info/sct', '111411000119103', 'End stage renal disease due to hypertension (disorder)')
,('http://snomed.info/sct', '111438007', 'Hypertension secondary to renal disease in obstetric context (disorder)')
,('http://snomed.info/sct', '117681000119102', 'Chronic kidney disease stage 1 due to hypertension (disorder)')
,('http://snomed.info/sct', '118781000119108', 'Pre-existing hypertensive chronic kidney disease in mother complicating pregnancy (disorder)')
,('http://snomed.info/sct', '1201005', 'Benign essential hypertension (disorder)')
,('http://snomed.info/sct', '120261000119101', 'Benign hypertensive heart disease and chronic renal disease stage 5 (disorder)')
,('http://snomed.info/sct', '1204139007', 'Hypertension due to congenital adrenal hyperplasia (disorder)')
,('http://snomed.info/sct', '1208839002', 'Secondary hypertension due to renal tubular disorder (disorder)')
,('http://snomed.info/sct', '1208845005', 'Secondary hypertension due to congenital heart disorder (disorder)')
,('http://snomed.info/sct', '1236831007', 'Ulcer of lower leg due to arterial hypertension (disorder)')
,('http://snomed.info/sct', '1237173008', 'Ulcer of lower limb due to arterial hypertension (disorder)')
,('http://snomed.info/sct', '123799005', 'Renovascular hypertension (disorder)')
,('http://snomed.info/sct', '123800009', 'Goldblatt hypertension (disorder)')
,('http://snomed.info/sct', '1260271009', 'Hemorrhagic cerebral infarction due to hypertension (disorder)')
,('http://snomed.info/sct', '127991000119101', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '128001000119105', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '129151000119102', 'Chronic kidney disease stage 4 due to hypertension (disorder)')
,('http://snomed.info/sct', '129161000119100', 'Chronic kidney disease stage 5 due to hypertension (disorder)')
,('http://snomed.info/sct', '129171000119106', 'Chronic kidney disease stage 3 due to hypertension (disorder)')
,('http://snomed.info/sct', '129181000119109', 'Chronic kidney disease stage 2 due to hypertension (disorder)')
,('http://snomed.info/sct', '132721000119104', 'Hypertensive emergency (disorder)')
,('http://snomed.info/sct', '1332436006', 'Hypertension in chronic kidney disease stage 3B due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332441003', 'Hypertension in chronic kidney disease stage 3A due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332442005', 'Hypertension in chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332464001', 'Hypertension in chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332465000', 'Hypertension in chronic kidney disease stage 3B due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332466004', 'Hypertension in chronic kidney disease stage 3A due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332467008', 'Hypertension in chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332468003', 'Hypertension in chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140101000119109', 'Hypertension in chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140111000119107', 'Hypertension in chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140121000119100', 'Hypertension in chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140131000119102', 'Hypertension in chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1474004', 'Hypertensive heart AND renal disease complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '14973001', 'Renal sclerosis with hypertension (disorder)')
,('http://snomed.info/sct', '153851000119106', 'Malignant hypertensive chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '153891000119101', 'End stage renal disease on dialysis due to hypertension (disorder)')
,('http://snomed.info/sct', '15781000119107', 'Hypertensive heart AND chronic kidney disease with congestive heart failure (disorder)')
,('http://snomed.info/sct', '161501007', 'History of hypertension (situation)')
,('http://snomed.info/sct', '161807003', 'Past pregnancy history of severe pre-eclampsia (situation)')
,('http://snomed.info/sct', '16229371000119106', 'Labile systemic arterial hypertension (disorder)')
,('http://snomed.info/sct', '16740451000119109', 'Postpartum hemolysis-elevated liver enzymes-low platelet count syndrome (disorder)')
,('http://snomed.info/sct', '16916061000119102', 'Past pregnancy history of postpartum gestational hypertension (situation)')
,('http://snomed.info/sct', '169465000', 'Hypertension caused by oral contraceptive pill (disorder)')
,('http://snomed.info/sct', '18416000', 'Essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '193003', 'Benign hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '194767001', 'Benign hypertensive heart disease with congestive cardiac failure (disorder)')
,('http://snomed.info/sct', '194779001', 'Hypertensive heart and renal disease with (congestive) heart failure (disorder)')
,('http://snomed.info/sct', '194780003', 'Hypertensive heart and renal disease with renal failure (disorder)')
,('http://snomed.info/sct', '194781004', 'Hypertensive heart and renal disease with both (congestive) heart failure and renal failure (disorder)')
,('http://snomed.info/sct', '194783001', 'Secondary malignant renovascular hypertension (disorder)')
,('http://snomed.info/sct', '194785008', 'Secondary benign hypertension (disorder)')
,('http://snomed.info/sct', '194788005', 'Hypertension secondary to endocrine disorder (disorder)')
,('http://snomed.info/sct', '194791005', 'Hypertension caused by drug (disorder)')
,('http://snomed.info/sct', '19769006', 'High-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '198941007', 'Hypertension complicating pregnancy, childbirth and the puerperium (disorder)')
,('http://snomed.info/sct', '198942000', 'Benign essential hypertension complicating pregnancy, childbirth and the puerperium (disorder)')
,('http://snomed.info/sct', '198947006', 'Benign essential hypertension complicating pregnancy, childbirth and the puerperium with postnatal complication (disorder)')
,('http://snomed.info/sct', '198949009', 'Renal hypertension complicating pregnancy, childbirth and the puerperium (disorder)')
,('http://snomed.info/sct', '198968007', 'Transient hypertension of pregnancy with postnatal complication (disorder)')
,('http://snomed.info/sct', '198986005', 'Severe pre-eclampsia with postnatal complication (disorder)')
,('http://snomed.info/sct', '198997005', 'Pre-eclampsia or eclampsia with pre-existing hypertension (disorder)')
,('http://snomed.info/sct', '199003007', 'Pre-eclampsia or eclampsia with pre-existing hypertension with postnatal complication (disorder)')
,('http://snomed.info/sct', '199005000', 'Pre-existing hypertension complicating pregnancy, childbirth and puerperium (disorder)')
,('http://snomed.info/sct', '199006004', 'Pre-existing hypertensive heart disease complicating pregnancy, childbirth and the puerperium (disorder)')
,('http://snomed.info/sct', '199007008', 'Pre-existing hypertensive heart and renal disease complicating pregnancy, childbirth and the puerperium (disorder)')
,('http://snomed.info/sct', '199008003', 'Pre-existing secondary hypertension complicating pregnancy, childbirth and puerperium (disorder)')
,('http://snomed.info/sct', '206596003', 'Neonatal hypertension (disorder)')
,('http://snomed.info/sct', '20753005', 'Hypertensive heart disease complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '22966008', 'Hypertensive heart AND renal disease complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '23130000', 'Paroxysmal hypertension (disorder)')
,('http://snomed.info/sct', '23717007', 'Benign essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '237279007', 'Transient hypertension of pregnancy (disorder)')
,('http://snomed.info/sct', '237281009', 'Moderate proteinuric hypertension of pregnancy (disorder)')
,('http://snomed.info/sct', '237282002', 'Impending eclampsia (disorder)')
,('http://snomed.info/sct', '23786008', 'Malignant hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '24042004', 'Chronic hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '26078007', 'Hypertension secondary to renal disease complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '275516004', 'Cardiomegaly due to hypertension (disorder)')
,('http://snomed.info/sct', '28119000', 'Renal hypertension (disorder)')
,('http://snomed.info/sct', '284961000119106', 'Chronic kidney disease due to benign hypertension (disorder)')
,('http://snomed.info/sct', '284971000119100', 'Chronic kidney disease stage 1 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '284981000119102', 'Chronic kidney disease stage 2 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '284991000119104', 'Chronic kidney disease stage 3 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '285001000119105', 'Chronic kidney disease stage 4 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '285011000119108', 'Chronic kidney disease stage 5 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '285041000119107', 'Benign hypertensive heart disease and chronic renal disease stage 1 (disorder)')
,('http://snomed.info/sct', '285061000119106', 'Benign hypertensive heart disease and chronic renal disease stage 2 (disorder)')
,('http://snomed.info/sct', '285081000119102', 'Benign hypertensive heart disease and chronic renal disease stage 3 (disorder)')
,('http://snomed.info/sct', '285101000119109', 'Benign hypertensive heart disease and chronic renal disease stage 4 (disorder)')
,('http://snomed.info/sct', '285831000119108', 'Malignant hypertensive chronic kidney disease (disorder)')
,('http://snomed.info/sct', '285841000119104', 'Malignant hypertensive end stage renal disease (disorder)')
,('http://snomed.info/sct', '285851000119102', 'Malignant hypertensive chronic kidney disease stage 1 (disorder)')
,('http://snomed.info/sct', '285861000119100', 'Malignant hypertensive chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '285871000119106', 'Malignant hypertensive chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '285881000119109', 'Malignant hypertensive chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '285911000119109', 'Malignant hypertensive heart disease and chronic renal disease stage 3 (disorder)')
,('http://snomed.info/sct', '285921000119102', 'Malignant hypertensive heart disease and chronic renal disease stage 4 (disorder)')
,('http://snomed.info/sct', '286371000119107', 'Malignant hypertensive end stage renal disease on dialysis (disorder)')
,('http://snomed.info/sct', '288250001', 'Maternal hypertension (disorder)')
,('http://snomed.info/sct', '29259002', 'Malignant hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '307632004', 'Non-proteinuric hypertension of pregnancy (disorder)')
,('http://snomed.info/sct', '31407004', 'Pre-existing hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '31881008', 'Cardiovascular renal disease (disorder)')
,('http://snomed.info/sct', '31992008', 'Secondary hypertension (disorder)')
,('http://snomed.info/sct', '334831000119106', 'Disorder of right retina co-occurrent and due to hypertension (disorder)')
,('http://snomed.info/sct', '340441000119107', 'Disorder of left retina co-occurrent and due to hypertension (disorder)')
,('http://snomed.info/sct', '34273003', 'Hypertensive heart disease complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '345771000119101', 'Disorder of bilateral retinas co-occurrent and due to hypertension (disorder)')
,('http://snomed.info/sct', '34694006', 'Pre-existing hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '35303009', 'Benign essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '36221001', 'Benign hypertensive heart disease (disorder)')
,('http://snomed.info/sct', '36315003', 'Malignant hypertensive heart disease without congestive heart failure (disorder)')
,('http://snomed.info/sct', '367390009', 'Hypertension in the obstetric context (disorder)')
,('http://snomed.info/sct', '367821000119106', 'Hypertension due to compression of renal parenchyma (disorder)')
,('http://snomed.info/sct', '371125006', 'Labile essential hypertension (disorder)')
,('http://snomed.info/sct', '37618003', 'Chronic hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '38341003', 'Hypertensive disorder, systemic arterial (disorder)')
,('http://snomed.info/sct', '38481006', 'Hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '39018007', 'Renal arterial hypertension (disorder)')
,('http://snomed.info/sct', '39727004', 'Hypertension secondary to renal disease complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '397748008', 'Hypertension with albuminuria (disorder)')
,('http://snomed.info/sct', '398254007', 'Pre-eclampsia (disorder)')
,('http://snomed.info/sct', '40511000119107', 'Postpartum pre-existing essential hypertension (disorder)')
,('http://snomed.info/sct', '40521000119100', 'Postpartum pregnancy-induced hypertension (disorder)')
,('http://snomed.info/sct', '41114007', 'Mild pre-eclampsia (disorder)')
,('http://snomed.info/sct', '421731000', 'Hypertensive optic neuropathy (disorder)')
,('http://snomed.info/sct', '422001004', 'Hypertensive choroidopathy (disorder)')
,('http://snomed.info/sct', '427889009', 'Hypertension associated with transplantation (disorder)')
,('http://snomed.info/sct', '428163005', 'Hypertensive left ventricular hypertrophy (disorder)')
,('http://snomed.info/sct', '428575007', 'Hypertension secondary to kidney transplant (disorder)')
,('http://snomed.info/sct', '429198000', 'Exertional hypertension (disorder)')
,('http://snomed.info/sct', '429457004', 'Systolic essential hypertension (disorder)')
,('http://snomed.info/sct', '434711000124103', 'Perioperative hypertension (disorder)')
,('http://snomed.info/sct', '443482000', 'Hypertensive urgency (disorder)')
,('http://snomed.info/sct', '449631000124102', 'Benign hypertensive heart disease and chronic renal disease (disorder)')
,('http://snomed.info/sct', '449759005', 'Complication of systemic hypertensive disorder (disorder)')
,('http://snomed.info/sct', '46113002', 'Hypertensive heart failure (disorder)')
,('http://snomed.info/sct', '461301000124109', 'Resistant hypertensive disorder (disorder)')
,('http://snomed.info/sct', '46481004', 'Low-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '46764007', 'Severe pre-eclampsia (disorder)')
,('http://snomed.info/sct', '472749004', 'Coronary sinus hypertension as complication of procedure (disorder)')
,('http://snomed.info/sct', '473392002', 'Hypertensive nephrosclerosis (disorder)')
,('http://snomed.info/sct', '48146000', 'Diastolic hypertension (disorder)')
,('http://snomed.info/sct', '48194001', 'Pregnancy-induced hypertension (disorder)')
,('http://snomed.info/sct', '48552006', 'Hypertension secondary to renal disease complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '49102001', 'Hypertensive heart AND renal disease in obstetric context (disorder)')
,('http://snomed.info/sct', '49171007', 'Hypertensive renal disease complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '49220004', 'Hypertensive renal failure (disorder)')
,('http://snomed.info/sct', '50490005', 'Hypertensive encephalopathy (disorder)')
,('http://snomed.info/sct', '5148006', 'Hypertensive heart disease with congestive heart failure (disorder)')
,('http://snomed.info/sct', '52698002', 'Transient hypertension (disorder)')
,('http://snomed.info/sct', '541000119105', 'Hypertension complicating pregnancy, childbirth and the puerperium, antepartum (disorder)')
,('http://snomed.info/sct', '54225002', 'Malignant hypertensive heart disease (disorder)')
,('http://snomed.info/sct', '5501000119106', 'Postoperative hypertension (disorder)')
,('http://snomed.info/sct', '56218007', 'Systolic hypertension (disorder)')
,('http://snomed.info/sct', '57684003', 'Parenchymal renal hypertension (disorder)')
,('http://snomed.info/sct', '57873008', 'Hypertensive renal disease complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '59621000', 'Essential hypertension (disorder)')
,('http://snomed.info/sct', '59720008', 'Sustained diastolic hypertension (disorder)')
,('http://snomed.info/sct', '59733002', 'Hypertensive heart disease complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '60899001', 'Hypertensive heart disease without congestive heart failure (disorder)')
,('http://snomed.info/sct', '62240004', 'Benign arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '63287004', 'Benign essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '64715009', 'Hypertensive heart disease (disorder)')
,('http://snomed.info/sct', '65402008', 'Pre-existing hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '65443008', 'Malignant hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '65518004', 'Labile diastolic hypertension (disorder)')
,('http://snomed.info/sct', '66052004', 'Benign hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '66610008', 'Malignant hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '66709007', 'Hypertensive renal disease complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '67359005', 'Pre-eclampsia added to pre-existing hypertension (disorder)')
,('http://snomed.info/sct', '6962006', 'Hypertensive retinopathy (disorder)')
,('http://snomed.info/sct', '697929007', 'Intermittent hypertension (disorder)')
,('http://snomed.info/sct', '697930002', 'Labile hypertension due to being in a clinical environment (disorder)')
,('http://snomed.info/sct', '698591006', 'Benign hypertensive renal disease with renal failure (disorder)')
,('http://snomed.info/sct', '698638005', 'Pregnancy induced hypertension with pulmonary edema (disorder)')
,('http://snomed.info/sct', '698640000', 'Hypertension in the puerperium with pulmonary edema (disorder)')
,('http://snomed.info/sct', '69909000', 'Eclampsia added to pre-existing hypertension (disorder)')
,('http://snomed.info/sct', '70272006', 'Malignant hypertension (disorder)')
,('http://snomed.info/sct', '703310005', 'Autosomal dominant progressive nephropathy with hypertension (disorder)')
,('http://snomed.info/sct', '704667004', 'Hypertension concurrent and due to end stage renal disease on dialysis (disorder)')
,('http://snomed.info/sct', '706882009', 'Hypertensive crisis (disorder)')
,('http://snomed.info/sct', '709881001', 'Past pregnancy history of gestational hypertension (situation)')
,('http://snomed.info/sct', '712487000', 'End stage renal disease due to benign hypertension (disorder)')
,('http://snomed.info/sct', '712832005', 'Supine hypertension (disorder)')
,('http://snomed.info/sct', '71421000119105', 'Hypertension in chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71701000119105', 'Hypertension in chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71874008', 'Benign essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '72022006', 'Essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '720568003', 'Brachydactyly and arterial hypertension syndrome (disorder)')
,('http://snomed.info/sct', '726513006', 'Past pregnancy history of hemolysis-elevated liver enzymes-low platelet count syndrome (situation)')
,('http://snomed.info/sct', '73030000', 'Hypertensive renal disease in obstetric context (disorder)')
,('http://snomed.info/sct', '73410007', 'Benign secondary renovascular hypertension (disorder)')
,('http://snomed.info/sct', '736992003', 'Nephropathy following pre-eclampsia (disorder)')
,('http://snomed.info/sct', '74451002', 'Secondary diastolic hypertension (disorder)')
,('http://snomed.info/sct', '762463000', 'Diastolic hypertension co-occurrent with systolic hypertension (disorder)')
,('http://snomed.info/sct', '765182005', 'Pre-eclampsia in puerperium (disorder)')
,('http://snomed.info/sct', '766937004', 'Hypertension due to gain-of-function mutation in mineralocorticoid receptor (disorder)')
,('http://snomed.info/sct', '77970009', 'Benign hypertensive heart disease without congestive heart failure (disorder)')
,('http://snomed.info/sct', '78544004', 'Chronic hypertensive uremia (disorder)')
,('http://snomed.info/sct', '78808002', 'Essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '78975002', 'Malignant essential hypertension (disorder)')
,('http://snomed.info/sct', '79355007', 'Hypertensive heart disease in obstetric context (disorder)')
,('http://snomed.info/sct', '81363003', 'Malignant arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '81626002', 'Malignant hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '8218002', 'Chronic hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '82771000119102', 'Hypertension complicating pregnancy (disorder)')
,('http://snomed.info/sct', '83105008', 'Malignant hypertensive heart disease with congestive heart failure (disorder)')
,('http://snomed.info/sct', '84094009', 'Rebound hypertension (disorder)')
,('http://snomed.info/sct', '8501000119104', 'Hypertensive heart and chronic kidney disease (disorder)')
,('http://snomed.info/sct', '86041002', 'Pre-existing hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '86234004', 'Hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '871642009', 'Hypertension due to aortic arch obstruction (disorder)')
,('http://snomed.info/sct', '8762007', 'Chronic hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '89242004', 'Malignant secondary hypertension (disorder)')
,('http://snomed.info/sct', '95343001', 'Ischemic ulcer of skin due to arterial hypertension (disorder)')
,('http://snomed.info/sct', '95605009', 'Hemolysis-elevated liver enzymes-low platelet count syndrome (disorder)')
,('http://snomed.info/sct', '96701000119107', 'Hypertensive heart AND chronic kidney disease on dialysis (disorder)')
,('http://snomed.info/sct', '96711000119105', 'Hypertensive heart AND chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '96721000119103', 'Hypertensive heart AND chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '96731000119100', 'Hypertensive heart AND chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '96741000119109', 'Hypertensive heart AND chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '96751000119106', 'Hypertensive heart AND chronic kidney disease stage 1 (disorder)')
,('http://snomed.info/sct', '9901000', 'Essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
) AS t (system, code, display) ;