create or replace view irae__dx_autoimmune_lupus as select * from (values
('http://snomed.info/sct', '11013005', 'Systemic lupus erythematosus glomerulonephritis syndrome, World Health Organization class VI (disorder)')
,('http://snomed.info/sct', '196138005', 'Lung disease with systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '19682006', 'Lupus hepatitis (disorder)')
,('http://snomed.info/sct', '200936003', 'Lupus erythematosus (disorder)')
,('http://snomed.info/sct', '201436003', 'Drug-induced systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '22888007', 'Drug-induced lupus erythematosus caused by procainamide (disorder)')
,('http://snomed.info/sct', '239886003', 'Limited lupus erythematosus (disorder)')
,('http://snomed.info/sct', '239887007', 'Systemic lupus erythematosus with organ/system involvement (disorder)')
,('http://snomed.info/sct', '239888002', 'Lupus panniculitis (disorder)')
,('http://snomed.info/sct', '239889005', 'Bullous systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '239890001', 'Systemic lupus erythematosus with multisystem involvement (disorder)')
,('http://snomed.info/sct', '25380002', 'Pericarditis co-occurrent and due to systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '309762007', 'Systemic lupus erythematosus with pericarditis (disorder)')
,('http://snomed.info/sct', '36402006', 'Systemic lupus erythematosus glomerulonephritis syndrome, World Health Organization class IV (disorder)')
,('http://snomed.info/sct', '403486000', 'Acute systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '403487009', 'Fulminating systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '4676006', 'Systemic lupus erythematosus glomerulonephritis syndrome, World Health Organization class II (disorder)')
,('http://snomed.info/sct', '52042003', 'Systemic lupus erythematosus glomerulonephritis syndrome, World Health Organization class V (disorder)')
,('http://snomed.info/sct', '54072008', 'Nonbacterial verrucal endocardiosis (disorder)')
,('http://snomed.info/sct', '54912002', 'Drug-induced lupus erythematosus caused by hydralazine (disorder)')
,('http://snomed.info/sct', '55464009', 'Systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '61458006', 'Drug-induced lupus erythematosus caused by diphenylhydantoin (disorder)')
,('http://snomed.info/sct', '68815009', 'Systemic lupus erythematosus glomerulonephritis syndrome (disorder)')
,('http://snomed.info/sct', '73286009', 'Systemic lupus erythematosus glomerulonephritis syndrome, World Health Organization class I (disorder)')
,('http://snomed.info/sct', '76521009', 'Systemic lupus erythematosus glomerulonephritis syndrome, World Health Organization class III (disorder)')
,('http://snomed.info/sct', '773333003', 'Autosomal systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '77753005', 'Lupus disease of the lung (disorder)')
,('http://snomed.info/sct', '80258006', 'Drug-induced lupus erythematosus (disorder)')
,('http://snomed.info/sct', '95332009', 'Rash of systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '95644001', 'Systemic lupus erythematosus encephalitis (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.0', 'Drug-induced systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.10', 'Systemic lupus erythematosus, organ or system involvement unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.11', 'Endocarditis in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.12', 'Pericarditis in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.13', 'Lung involvement in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.14', 'Glomerular disease in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.15', 'Tubulo-interstitial nephropathy in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.19', 'Other organ or system involvement in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.8', 'Other forms of systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.9', 'Systemic lupus erythematosus, unspecified')
) AS t (system, code, display) ;