create or replace view irae__dx_kidney_dialysis as select * from (values
('http://snomed.info/sct', '114711000119105', 'Infection due to and following peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '1153581007', 'Matrix stone formation during renal dialysis (disorder)')
,('http://snomed.info/sct', '1162663008', 'Obstruction of Tenckhoff catheter (disorder)')
,('http://snomed.info/sct', '1259584009', 'Dementia due to and following dialysis (disorder)')
,('http://snomed.info/sct', '127991000119101', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '128001000119105', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '12963004', 'Dialysis-associated ascites (disorder)')
,('http://snomed.info/sct', '133031000119106', 'Thrombosis of arteriovenous graft caused by hemodialysis arteriovenous access device (disorder)')
,('http://snomed.info/sct', '19765000', 'Complication of dialysis (disorder)')
,('http://snomed.info/sct', '233766001', 'Dialysis-associated hypoxia (disorder)')
,('http://snomed.info/sct', '236435004', 'End stage renal failure on dialysis (disorder)')
,('http://snomed.info/sct', '236538004', 'Acute disorder of hemodialysis (disorder)')
,('http://snomed.info/sct', '236539007', 'First use syndrome of dialysis (disorder)')
,('http://snomed.info/sct', '236541008', 'Hyperchloremic acidosis associated with dialysis (disorder)')
,('http://snomed.info/sct', '236542001', 'Long-term disorder of dialysis (disorder)')
,('http://snomed.info/sct', '236550005', 'Polyserositis syndrome of dialysis (disorder)')
,('http://snomed.info/sct', '236552002', 'Adynamic bone disease (disorder)')
,('http://snomed.info/sct', '236554001', 'Pain during inflow of dialysate (disorder)')
,('http://snomed.info/sct', '236555000', 'Pain during outflow of dialysate (disorder)')
,('http://snomed.info/sct', '236556004', 'Bloodstained peritoneal dialysis effluent (disorder)')
,('http://snomed.info/sct', '236559006', 'Loss of ultrafiltration (disorder)')
,('http://snomed.info/sct', '236560001', 'Loss of solute clearance (disorder)')
,('http://snomed.info/sct', '236562009', 'Obstruction of peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '236563004', 'Migration of peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '236566007', 'Extrusion of peritoneal dialysis catheter cuff (disorder)')
,('http://snomed.info/sct', '236567003', 'Misplacement of acute peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '26944003', 'Acute megaloblastic anemia due to dialysis (disorder)')
,('http://snomed.info/sct', '276883000', 'Peritoneal dialysis-associated peritonitis (disorder)')
,('http://snomed.info/sct', '286371000119107', 'Malignant hypertensive end stage renal disease on dialysis (disorder)')
,('http://snomed.info/sct', '292760002', 'Dialysis fluid adverse reaction (disorder)')
,('http://snomed.info/sct', '292761003', 'Peritoneal dialysis solution adverse reaction (disorder)')
,('http://snomed.info/sct', '292762005', 'Hemodialysis fluid adverse reaction (disorder)')
,('http://snomed.info/sct', '292763000', 'Hemofiltration solution adverse reaction (disorder)')
,('http://snomed.info/sct', '32599008', 'Hemodialysis-associated amyloidosis (disorder)')
,('http://snomed.info/sct', '33461007', 'Complication of peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '33603003', 'Complication of renal dialysis (disorder)')
,('http://snomed.info/sct', '368471000119109', 'End stage renal disease on dialysis due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '402458002', 'Hemodialysis-associated secondary amyloidosis of skin (disorder)')
,('http://snomed.info/sct', '402762007', 'Skin lesion associated with hemodialysis (disorder)')
,('http://snomed.info/sct', '403732009', 'Hemodialysis-associated pseudoporphyria (disorder)')
,('http://snomed.info/sct', '404813001', 'Peritoneal dialysis leakage (disorder)')
,('http://snomed.info/sct', '408667000', 'Hemodialysis-associated hypotension (disorder)')
,('http://snomed.info/sct', '430333000', 'Hematoma of dialysis access site (disorder)')
,('http://snomed.info/sct', '431028002', 'Mechanical complication of peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '431873008', 'Peritonitis due to infected peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '433991000124108', 'Peritoneal dialysis access failure (disorder)')
,('http://snomed.info/sct', '434061000124103', 'Hemodialysis access failure (disorder)')
,('http://snomed.info/sct', '440228000', 'Leakage of peritoneal dialysate into subcutaneous tissue of abdominal wall (disorder)')
,('http://snomed.info/sct', '440310004', 'Leakage of peritoneal dialysate into pleural cavity (disorder)')
,('http://snomed.info/sct', '440551001', 'Malposition of peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '440597004', 'Obstruction of peritoneal dialysis catheter by fibrin formation (disorder)')
,('http://snomed.info/sct', '440663004', 'Encapsulating peritoneal sclerosis associated with peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '473112005', 'Leakage from Tenckhoff catheter (disorder)')
,('http://snomed.info/sct', '473147002', 'Malfunction of peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '473186003', 'Migration of Tenckhoff catheter (disorder)')
,('http://snomed.info/sct', '473190001', 'Leakage of peritoneal dialysis catheter (disorder)')
,('http://snomed.info/sct', '699235009', 'Continuous ambulatory peritoneal dialysis associated peritonitis (disorder)')
,('http://snomed.info/sct', '702634004', 'Inadequate peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '702635003', 'Inadequate hemodialysis (disorder)')
,('http://snomed.info/sct', '704667004', 'Hypertension concurrent and due to end stage renal disease on dialysis (disorder)')
,('http://snomed.info/sct', '707090004', 'Spondyloarthropathy due to hemodialysis-associated amyloidosis (disorder)')
,('http://snomed.info/sct', '713720009', 'Sclerosing peritonitis as complication of peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '713721008', 'Hydrothorax as complication of peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '713724000', 'Abdominal hernia as complication of peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '713727007', 'Hemoperitoneum as complication of peritoneal dialysis (disorder)')
,('http://snomed.info/sct', '714152005', 'Chronic kidney disease stage 5 on dialysis (disorder)')
,('http://snomed.info/sct', '719501003', 'Ultrafiltration failure (disorder)')
,('http://snomed.info/sct', '724612006', 'Avascular necrosis of bone due to and following renal dialysis (disorder)')
,('http://snomed.info/sct', '783187005', 'Aseptic peritoneal eosinophilia due to and following dialysis (disorder)')
,('http://snomed.info/sct', '85223007', 'Complication of hemodialysis (disorder)')
,('http://snomed.info/sct', '87235005', 'Dialysis disequilibrium syndrome (disorder)')
,('http://snomed.info/sct', '88351001', 'Hypercalcemia associated with chronic dialysis (disorder)')
,('http://snomed.info/sct', '90771000119100', 'End stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90791000119104', 'End stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z49.01', 'Encounter for fitting and adjustment of extracorporeal dialysis catheter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z49.02', 'Encounter for fitting and adjustment of peritoneal dialysis catheter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z49.31', 'Encounter for adequacy testing for hemodialysis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z49.32', 'Encounter for adequacy testing for peritoneal dialysis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z99.2', 'Dependence on renal dialysis')
) AS t (system, code, display) ;