create or replace view irae__rx_immunosuppressive_immune_modulators as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1001405', 'docetaxel 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1001433', '1.5 ML cabazitaxel 40 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1045456', '2 ML eribulin mesylate 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1049400', 'dexamethasone sodium phosphate 4 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105584', 'fluorouracil 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105585', 'methotrexate 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105586', 'methotrexate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105589', 'methotrexate 100 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093174', 'cyclosporine 0.002 MG/MG Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093280', 'docetaxel 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1101769', 'docetaxel 24 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1111071', 'docetaxel 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1116927', 'dexamethasone phosphate 4 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1145929', '1 ML abatacept 125 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191138', 'doxorubicin hydrochloride 2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1249712', 'dexamethasone sodium phosphate 0.4 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303125', 'prednisone 1 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303132', 'prednisone 2 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303135', 'prednisone 5 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1304995', '31 ML vincristine sulfate liposome 0.16 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1356688', 'omacetaxine mepesuccinate 3.5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1357886', 'methylprednisolone 2000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358498', 'lidocaine hydrochloride 10 MG/ML / methylprednisolone acetate 40 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358510', 'methylprednisolone acetate 20 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358610', 'methylprednisolone acetate 40 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358617', 'methylprednisolone acetate 80 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1374372', 'dexamethasone acetate 8 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431642', '4 ML golimumab 12.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431971', '24 HR tacrolimus 0.5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431980', '24 HR tacrolimus 1 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431985', '24 HR tacrolimus 5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1437968', 'cyclophosphamide 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1437969', 'cyclophosphamide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441402', '0.4 ML methotrexate 25 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441411', '0.4 ML methotrexate 37.5 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441416', '0.4 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441422', '0.4 ML methotrexate 62.5 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441527', '0.9 ML tocilizumab 180 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1482813', '1 ML golimumab 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153129', 'azathioprine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1536484', 'mercaptopurine 20 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544378', '0.2 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544385', '0.25 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544387', '0.3 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544389', '0.35 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544395', '0.45 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544397', '0.5 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544401', '0.6 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544403', '0.15 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1594357', '{3 (0.8 ML adalimumab 50 MG/ML Prefilled Syringe) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1653142', '0.5 ML golimumab 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1653165', '1 ML golimumab 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1653223', '1 ML etanercept 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1654077', '0.5 ML ustekinumab 90 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655726', '0.8 ML adalimumab 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655956', '40 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655959', '10 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655960', '2 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655967', '4 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655968', '8 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1656703', '{6 (0.8 ML adalimumab 50 MG/ML Auto-Injector) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1657862', '10 ML rituximab 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1657867', '50 ML rituximab 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1657974', '4 ML tocilizumab 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1657979', '10 ML tocilizumab 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1657981', '20 ML tocilizumab 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1660004', 'thiotepa 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1660009', 'thiotepa 15 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664434', '24 HR tacrolimus 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664456', '24 HR tacrolimus 0.75 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664461', '24 HR tacrolimus 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1670311', 'tipiracil 6.14 MG / trifluridine 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1670316', 'tipiracil 8.19 MG / trifluridine 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1718589', 'trabectedin 1 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719000', 'gemcitabine 200 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719003', 'gemcitabine 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719005', 'gemcitabine 2000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719772', '10 ML irinotecan hydrochloride liposome 4.3 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720735', 'lomustine 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720960', '26.3 ML gemcitabine 38 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720975', '52.6 ML gemcitabine 38 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720977', '5.26 ML gemcitabine 38 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726097', 'bendamustine hydrochloride 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726271', 'ixabepilone 45 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726276', 'ixabepilone 15 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726319', '2 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726324', '5 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726333', '15 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726492', '25 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726673', 'bleomycin 15 UNT Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726676', 'bleomycin 30 UNT Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726844', '0.4 ML adalimumab 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1728072', 'pemetrexed 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1728077', 'pemetrexed 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729418', '1 ML vinorelbine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729422', '5 ML vinorelbine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1731338', 'dacarbazine 200 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1731340', 'dacarbazine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1731355', '5 ML cytarabine 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732182', '25 ML epirubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732186', '100 ML epirubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734340', 'etoposide 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734917', 'cyclophosphamide 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734919', 'cyclophosphamide 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734921', 'cyclophosphamide 2000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736776', '10 ML oxaliplatin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736781', '20 ML oxaliplatin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736784', 'oxaliplatin 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736786', 'oxaliplatin 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736854', 'cisplatin 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740864', 'fludarabine phosphate 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740865', '2 ML fludarabine phosphate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740894', 'mitomycin 5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740898', 'mitomycin 40 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740900', 'mitomycin 20 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743704', 'methylprednisolone 125 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743720', 'methylprednisolone 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743726', 'methylprednisolone 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743779', '1 ML methylprednisolone acetate 40 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743855', '1 ML methylprednisolone acetate 80 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1747179', '0.4 ML methotrexate 31.3 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1747185', '0.4 ML methotrexate 43.8 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1747192', '0.4 ML methotrexate 56.3 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790095', 'doxorubicin hydrochloride 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790097', '5 ML doxorubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790099', '10 ML doxorubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790100', '25 ML doxorubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790103', 'doxorubicin hydrochloride 10 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790115', '10 ML doxorubicin hydrochloride liposome 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790127', '25 ML doxorubicin hydrochloride liposome 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790541', 'infliximab-dyyb 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791493', '20 ML idarubicin hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791498', '10 ML idarubicin hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791500', '5 ML idarubicin hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791588', 'ifosfamide 3000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791593', 'ifosfamide 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791597', '60 ML ifosfamide 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791599', '20 ML ifosfamide 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791701', '10 ML fluorouracil 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791736', '20 ML fluorouracil 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1796419', '1 ML pralatrexate 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1796424', '2 ML pralatrexate 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1797528', '40 ML oxaliplatin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1799228', '1 ML abatacept 125 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1799416', 'topotecan 4 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1799424', '4 ML topotecan 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1801277', '{4 (0.8 ML adalimumab 50 MG/ML Auto-Injector) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1805001', 'bendamustine hydrochloride 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1805007', 'bendamustine hydrochloride 25 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1811255', '26 ML ustekinumab 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812079', '1 ML dexamethasone phosphate 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812095', '1 ML dexamethasone phosphate 4 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812194', '1 ML dexamethasone phosphate 4 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1855523', '0.8 ML adalimumab 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1860480', '1 ML docetaxel 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1860485', '4 ML docetaxel 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1860619', '2 ML docetaxel 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1861411', '8 ML docetaxel 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1863343', '1 ML vincristine sulfate 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1863354', '2 ML vincristine sulfate 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869595', '{27 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1872062', 'doxorubicin hydrochloride 20 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1872979', '0.4 ML adalimumab 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1921009', '0.1 ML adalimumab 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1921016', '0.2 ML adalimumab 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1921238', '0.8 ML adalimumab 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1921592', 'methotrexate 2.5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1925254', '0.4 ML abatacept 125 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1925256', '0.7 ML abatacept 125 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1927285', 'infliximab-abda 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1927885', '11.7 ML hyaluronidase, human recombinant 2000 UNT/ML / rituximab 120 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1927893', '13.4 ML hyaluronidase, human recombinant 2000 UNT/ML / rituximab 120 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1942743', 'cytarabine liposome 100 MG / daunorubicin liposomal 44 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1943550', '{49 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1946772', 'methotrexate 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197388', 'azathioprine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197422', 'busulfan 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197462', 'chlorambucil 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197549', 'cyclophosphamide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197550', 'cyclophosphamide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197553', 'cyclosporine 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197576', 'dexamethasone 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197577', 'dexamethasone 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197579', 'dexamethasone 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197580', 'dexamethasone 1.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197581', 'dexamethasone 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197582', 'dexamethasone 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197583', 'dexamethasone 6 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197687', 'etoposide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197797', 'hydroxyurea 500 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197894', 'lomustine 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197895', 'lomustine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197896', 'lomustine 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197919', 'melphalan 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197931', 'mercaptopurine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197969', 'methylprednisolone 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197971', 'methylprednisolone 32 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197973', 'methylprednisolone 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197988', 'mitotane 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197989', 'mitoxantrone 2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198144', 'prednisone 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198145', 'prednisone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198146', 'prednisone 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198148', 'prednisone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198269', 'thioguanine 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198377', 'tacrolimus 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198378', 'tacrolimus 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198379', '1 ML tacrolimus 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199058', 'mycophenolate mofetil 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1992545', '6 ML arsenic trioxide 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199310', 'azathioprine 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199315', 'etoposide 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199316', 'fluorouracil 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199771', 'methylprednisolone 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1998783', 'gemcitabine 100 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999308', 'hydroxyurea 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200060', 'mycophenolate mofetil 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2002002', '10 ML daunorubicin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200327', 'capecitabine 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200328', 'capecitabine 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200342', 'hydroxyurea 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200343', 'hydroxyurea 300 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200344', 'hydroxyurea 400 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2045404', '0.005 ML dexamethasone 103.4 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205168', 'cyclosporine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', '5 ML cyclosporine 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052605', 'tacrolimus 0.2 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052703', 'tacrolimus 1 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205301', 'prednisone 5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055021', 'cyclosporine 0.9 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058858', '120 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058866', '140 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058880', '150 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058882', '160 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058890', '170 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058892', '180 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058894', '190 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058912', '130 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058927', '200 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2058933', '220 ML gemcitabine 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2099700', '1 ML dexamethasone phosphate 10 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2105826', '10 ML rituximab-abbs 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2105834', '50 ML rituximab-abbs 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2106073', '0.9 ML tocilizumab 180 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2108015', 'dexamethasone 0.4 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2121587', '{39 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122634', 'cladribine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122635', '{9 (cladribine 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122647', '{8 (cladribine 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122649', '{7 (cladribine 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122654', '{6 (cladribine 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122656', '{5 (cladribine 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122658', '{4 (cladribine 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2122660', '{10 (cladribine 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2182338', '1 ML etanercept 50 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2261802', 'dexamethasone 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2266525', 'infliximab-axxq 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273512', '10 ML rituximab-pvvr 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273520', '50 ML rituximab-pvvr 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2289413', '5.5 ML romidepsin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2375818', 'mitomycin 40 MG Powder for Pyelocalyceal Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377333', '0.4 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377341', '0.5 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377343', '0.6 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377345', '0.7 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377347', '0.8 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377349', '0.9 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377351', '1 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2377353', '0.3 ML methotrexate 25 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2384457', 'cedazuridine 100 MG / decitabine 35 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2386859', 'cyclophosphamide 200 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2387355', '{25 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239177', 'fluorouracil 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239178', 'vinblastine sulfate 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239179', 'dactinomycin 0.5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239180', 'streptozocin 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2392140', '0.5 ML etanercept 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2396764', 'azacitidine 200 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2396772', 'azacitidine 300 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239983', 'azathioprine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240416', 'cytarabine 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240573', 'pentostatin 10 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240754', '10 ML cladribine 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240906', '5 ML pegaspargase 750 UNT/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '241834', 'cyclosporine, modified 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '245255', 'cytarabine 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2462521', '0.5 ML etanercept-ykro 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2472327', '10 ML rituximab-arrx 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2472335', '50 ML rituximab-arrx 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249364', '20 ML cytarabine 100 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '253014', 'etanercept 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '253113', '10 ML busulfan 6 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2531374', 'melphalan flufenamide 20 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2568661', '5 ML cyclophosphamide 200 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2568663', '2.5 ML cyclophosphamide 200 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', '0.4 ML cyclosporine 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590608', 'cyclosporine 1 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590672', 'pemetrexed 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '259966', 'methylprednisolone 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2601728', 'pemetrexed 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2602136', 'pemetrexed 750 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2602363', '20 ML pemetrexed 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2602365', '40 ML pemetrexed 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2602366', '4 ML pemetrexed 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2605054', 'carmustine 300 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2605056', 'carmustine 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2605341', '34 ML pemetrexed 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2627711', '0.4 ML adalimumab-atto 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2627719', '0.8 ML adalimumab-atto 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2627724', '0.8 ML adalimumab-atto 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2634478', '0.2 ML adalimumab-atto 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2637958', '10 ML pemetrexed 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2637966', '100 ML pemetrexed 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2637968', '50 ML pemetrexed 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639651', '0.4 ML adalimumab-aaty 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639659', '0.4 ML adalimumab-aaty 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639936', 'cyclosporine 1 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640287', '0.8 ML adalimumab-bwwd 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640302', '0.8 ML adalimumab-bwwd 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640389', '0.8 ML adalimumab-aqvh 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640397', '0.8 ML adalimumab-aqvh 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640404', '0.8 ML adalimumab-fkjp 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640412', '0.4 ML adalimumab-fkjp 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640417', '0.8 ML adalimumab-fkjp 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640419', '0.8 ML adalimumab-bwwd 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640425', '0.4 ML adalimumab-bwwd 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640430', '0.4 ML adalimumab-bwwd 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640851', '0.8 ML adalimumab-aacf 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640859', '0.8 ML adalimumab-aacf 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640883', '0.8 ML adalimumab-adbm 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640891', '0.2 ML adalimumab-adbm 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640893', '0.4 ML adalimumab-adbm 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2640895', '0.8 ML adalimumab-adbm 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2641644', '0.1 ML adalimumab-adaz 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2641653', '0.2 ML adalimumab-adaz 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2641655', '0.4 ML adalimumab-adaz 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2641660', '0.4 ML adalimumab-adaz 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2641662', '0.8 ML adalimumab-adaz 100 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2641666', '0.8 ML adalimumab-adaz 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283475', 'hydroxyurea 1000 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283510', 'methotrexate 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283511', 'methotrexate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283671', 'methotrexate 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309012', 'carmustine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309013', 'carmustine 7.7 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309311', 'cisplatin 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309632', 'cyclosporine 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309650', '4 ML daunorubicin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309684', 'dexamethasone 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309686', 'dexamethasone 0.1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309696', 'dexamethasone phosphate 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310248', 'etoposide 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310351', 'floxuridine 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310994', 'infliximab 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311487', 'melphalan 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311625', 'methotrexate 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311659', 'methylprednisolone 40 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311880', 'mycophenolate mofetil 200 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311881', 'mycophenolate mofetil 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312199', 'paclitaxel 6 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312615', 'prednisone 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312617', 'prednisone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313190', 'tacrolimus 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313209', 'temozolomide 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313210', 'temozolomide 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313211', 'temozolomide 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313213', '5 ML teniposide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313567', 'valrubicin 40 MG/ML Irrigation Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314099', 'methylprednisolone 62.5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314167', 'procarbazine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315148', 'methotrexate 2.5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315187', 'prednisone 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317160', 'temozolomide 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328160', 'cyclosporine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328161', 'methylprednisolone 16 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '343033', 'dexamethasone 0.75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'cyclosporine 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359228', 'azathioprine 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359229', 'azathioprine 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '435681', 'dexamethasone 2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '477484', '15 ML natalizumab 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485246', 'azacitidine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '486419', '20 ML clofarabine 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '544940', 'cytarabine 50 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '582671', 'etanercept 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '583214', 'paclitaxel 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597195', 'carboplatin 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '603566', '50 ML nelarabine 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616015', 'abatacept 250 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636631', 'decitabine 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '637549', 'topotecan 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668579', 'vorinostat 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '700883', 'temozolomide 140 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '700885', 'temozolomide 180 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727703', '0.8 ML adalimumab 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727711', '0.67 ML anakinra 149 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727757', '1 ML etanercept 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '747193', 'topotecan 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '747195', 'topotecan 0.25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '759481', '{51 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '759696', '{12 (dexamethasone 0.75 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '759697', '{35 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '762675', '{21 (methylprednisolone 4 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763179', '{48 (prednisone 5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763181', '{21 (prednisone 5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763183', '{48 (prednisone 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '763185', '{21 (prednisone 10 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795081', 'certolizumab pegol 200 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '809158', '0.5 ML etanercept 50 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '828706', 'fludarabine phosphate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '829926', '10 ML arsenic trioxide 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835886', 'cyclosporine, modified 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835894', 'cyclosporine, modified 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835919', 'cyclosporine, modified 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835925', 'cyclosporine, modified 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835945', 'temozolomide 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '846192', '{21 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '848160', '0.5 ML golimumab 100 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '849597', '1 ML certolizumab pegol 200 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '853350', '0.5 ML ustekinumab 90 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '853355', '1 ML ustekinumab 90 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854177', 'dexamethasone 0.7 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '877513', 'romidepsin 10 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '880649', 'dexamethasone 3 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '996156', 'idarubicin hydrochloride 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '996158', 'idarubicin hydrochloride 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '996160', 'idarubicin hydrochloride 5 MG Oral Capsule')
) AS t (system, code, display) ;