create or replace view irae__lab_mycophenolate as select * from (values
('http://loinc.org', 'LOINC_NUM', 'COMPONENT')
,('http://loinc.org', '87432-1', 'Mycophenolate & mycophenolate glucuronide panel')
,('http://loinc.org', '23906-1', 'Mycophenolate glucuronide')
,('http://loinc.org', '23905-3', 'Mycophenolate')
,('http://loinc.org', '70211-8', 'Mycophenolate')
,('http://loinc.org', '55807-2', 'Mycophenolate glucuronide')
,('http://loinc.org', '72667-9', 'Mycophenolate^trough')
,('http://loinc.org', '73680-1', 'Mycophenolate^peak')
,('http://loinc.org', '55806-4', 'Mycophenolate')
,('http://loinc.org', '80697-6', 'Mycophenolate acyl-glucuronide')
,('http://loinc.org', '72986-3', 'Mycophenolate induced neutrophil Ab.IgG')
,('http://loinc.org', '72985-5', 'Mycophenolate induced neutrophil Ab.IgM')
,('http://loinc.org', '73252-9', 'Mycophenolate induced platelet Ab.IgM')
,('http://loinc.org', '73253-7', 'Mycophenolate induced platelet Ab.IgG')
) AS t (system, code, display) ;