create or replace view irae__dx_compromised_immunocompromised as select * from (values
('http://snomed.info/sct', '109964000', 'Diffuse non-Hodgkins lymphoma, undifferentiated (disorder)')
,('http://snomed.info/sct', '109966003', 'Diffuse non-Hodgkins lymphoma, immunoblastic (disorder)')
,('http://snomed.info/sct', '109967007', 'Diffuse non-Hodgkins lymphoma, small cleaved cell (disorder)')
,('http://snomed.info/sct', '109968002', 'Diffuse non-Hodgkins lymphoma, small cell (disorder)')
,('http://snomed.info/sct', '109969005', 'Diffuse large B-cell malignant lymphoma (disorder)')
,('http://snomed.info/sct', '109970006', 'Follicular non-Hodgkins lymphoma, small cleaved cell (disorder)')
,('http://snomed.info/sct', '109971005', 'Follicular non-Hodgkins lymphoma, mixed small cleaved cell and large cell (disorder)')
,('http://snomed.info/sct', '109972003', 'Follicular non-Hodgkins lymphoma, large cell (disorder)')
,('http://snomed.info/sct', '109975001', 'T-zone lymphoma (disorder)')
,('http://snomed.info/sct', '109976000', 'Lymphoepithelioid lymphoma (disorder)')
,('http://snomed.info/sct', '109977009', 'Peripheral T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '109978004', 'T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '109979007', 'B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '109989006', 'Multiple myeloma (disorder)')
,('http://snomed.info/sct', '110002002', 'Mast cell leukemia (disorder)')
,('http://snomed.info/sct', '110004001', 'Acute promyelocytic leukemia, FAB M3 (disorder)')
,('http://snomed.info/sct', '110005000', 'Acute myelomonocytic leukemia, FAB M4 (disorder)')
,('http://snomed.info/sct', '110006004', 'Prolymphocytic leukemia (disorder)')
,('http://snomed.info/sct', '110007008', 'Adult T-cell leukemia/lymphoma (disorder)')
,('http://snomed.info/sct', '111396008', 'Chédiak-Higashi syndrome (disorder)')
,('http://snomed.info/sct', '111585004', 'Neutropenia associated with autoimmune disease (disorder)')
,('http://snomed.info/sct', '111587007', 'Severe combined immunodeficiency due to absent interleukin-2 receptor (disorder)')
,('http://snomed.info/sct', '111880001', 'Acute human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '1162928000', 'Acute myeloid leukemia (morphologic abnormality)')
,('http://snomed.info/sct', '116711000119103', 'Marginal zone lymphoma of inguinal lymph node (disorder)')
,('http://snomed.info/sct', '116741000119104', 'Marginal zone lymphoma of thoracic lymph node (disorder)')
,('http://snomed.info/sct', '116811000119106', 'Non-Hodgkin lymphoma of central nervous system metastatic to lymph node of lower limb (disorder)')
,('http://snomed.info/sct', '116821000119104', 'Non-Hodgkin lymphoma of central nervous system metastatic to lymph node of upper limb (disorder)')
,('http://snomed.info/sct', '116841000119105', 'Marginal zone lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '116871000119103', 'Mantle cell lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '117061000119101', 'Peripheral T-cell lymphoma of spleen (disorder)')
,('http://snomed.info/sct', '117091000119108', 'Peripheral T-cell lymphoma of axillary lymph node (disorder)')
,('http://snomed.info/sct', '117111000119100', 'Peripheral T-cell lymphoma of thoracic lymph node (disorder)')
,('http://snomed.info/sct', '117211000119105', 'Peripheral T-cell lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '118599009', 'Hodgkins disease (disorder)')
,('http://snomed.info/sct', '118600007', 'Malignant lymphoma (disorder)')
,('http://snomed.info/sct', '118601006', 'Non-Hodgkins lymphoma (disorder)')
,('http://snomed.info/sct', '118605002', 'Hodgkin lymphoma, nodular lymphocyte predominance (disorder)')
,('http://snomed.info/sct', '118607005', 'Hodgkin lymphoma, lymphocyte-rich (disorder)')
,('http://snomed.info/sct', '118613001', 'Hairy cell leukemia (disorder)')
,('http://snomed.info/sct', '118617000', 'Burkitts lymphoma (disorder)')
,('http://snomed.info/sct', '1255796007', 'Burkitt lymphoma of lymph nodes of lower limb (disorder)')
,('http://snomed.info/sct', '1255805006', 'Malignant lymphoma of lymph nodes of head (disorder)')
,('http://snomed.info/sct', '1255806007', 'Malignant lymphoma of lymph nodes of neck (disorder)')
,('http://snomed.info/sct', '1255807003', 'Malignant lymphoma of lymph nodes of head and neck (disorder)')
,('http://snomed.info/sct', '1255895001', 'Burkitt lymphoma of lymph nodes of upper limb (disorder)')
,('http://snomed.info/sct', '1255906008', 'Malignant lymphoma of lymph nodes of upper limb (disorder)')
,('http://snomed.info/sct', '1255907004', 'Malignant lymphoma of lymph nodes of lower limb (disorder)')
,('http://snomed.info/sct', '127034005', 'Pancytopenia (disorder)')
,('http://snomed.info/sct', '127220001', 'Malignant lymphoma of lymph nodes (disorder)')
,('http://snomed.info/sct', '127225006', 'Chronic myelomonocytic leukemia (disorder)')
,('http://snomed.info/sct', '128804002', 'Primary cutaneous CD30 antigen positive T-cell lymphoproliferative disorder (morphologic abnormality)')
,('http://snomed.info/sct', '128875000', 'Primary cutaneous CD30 antigen positive large T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '129641006', 'Chronic benign neutropenia of childhood (disorder)')
,('http://snomed.info/sct', '129643009', 'Chronic hypoplastic neutropenia (disorder)')
,('http://snomed.info/sct', '13048006', 'Orbital lymphoma (disorder)')
,('http://snomed.info/sct', '133751000119102', 'Lymphoma of colon (disorder)')
,('http://snomed.info/sct', '17182001', 'Agranulocytosis (disorder)')
,('http://snomed.info/sct', '183005', 'Autoimmune pancytopenia (disorder)')
,('http://snomed.info/sct', '186706006', 'Human immunodeficiency virus infection constitutional disease (disorder)')
,('http://snomed.info/sct', '186707002', 'Human immunodeficiency virus infection with neurological disease (disorder)')
,('http://snomed.info/sct', '186708007', 'Human immunodeficiency virus infection with secondary clinical infectious disease (disorder)')
,('http://snomed.info/sct', '188511002', 'Burkitts lymphoma of intrathoracic lymph nodes (disorder)')
,('http://snomed.info/sct', '188512009', 'Burkitts lymphoma of intra-abdominal lymph nodes (disorder)')
,('http://snomed.info/sct', '188515006', 'Burkitts lymphoma of intrapelvic lymph nodes (disorder)')
,('http://snomed.info/sct', '188516007', 'Burkitts lymphoma of spleen (disorder)')
,('http://snomed.info/sct', '188517003', 'Burkitts lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '188572001', 'Hodgkins disease, nodular sclerosis of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '188609000', 'Nodular lymphoma of lymph nodes of head, face and neck (disorder)')
,('http://snomed.info/sct', '188612002', 'Nodular lymphoma of lymph nodes of axilla and upper limb (disorder)')
,('http://snomed.info/sct', '188613007', 'Nodular lymphoma of lymph nodes of inguinal region and lower limb (disorder)')
,('http://snomed.info/sct', '188672005', 'Follicular non-Hodgkins mixed small cleaved and large cell lymphoma (disorder)')
,('http://snomed.info/sct', '188674006', 'Diffuse malignant lymphoma - small non-cleaved cell (disorder)')
,('http://snomed.info/sct', '188675007', 'Malignant lymphoma - small cleaved cell (disorder)')
,('http://snomed.info/sct', '188676008', 'Malignant lymphoma - mixed small and large cell (disorder)')
,('http://snomed.info/sct', '188725004', 'Lymphoid leukemia (disorder)')
,('http://snomed.info/sct', '188726003', 'Subacute lymphoid leukemia (disorder)')
,('http://snomed.info/sct', '188728002', 'Aleukemic lymphoid leukemia (disorder)')
,('http://snomed.info/sct', '188732008', 'Myeloid leukemia (disorder)')
,('http://snomed.info/sct', '188733003', 'Chronic eosinophilic leukemia (disorder)')
,('http://snomed.info/sct', '188734009', 'Chronic neutrophilic leukemia (disorder)')
,('http://snomed.info/sct', '188744006', 'Monocytic leukemia (disorder)')
,('http://snomed.info/sct', '188754005', 'Megakaryocytic leukemia (disorder)')
,('http://snomed.info/sct', '188768003', 'Myelomonocytic leukemia (disorder)')
,('http://snomed.info/sct', '188770007', 'Subacute myelomonocytic leukemia (disorder)')
,('http://snomed.info/sct', '190030009', 'Compound leukemias (disorder)')
,('http://snomed.info/sct', '190979003', 'Selective immunoglobulin A deficiency (disorder)')
,('http://snomed.info/sct', '190996002', 'Severe combined immunodeficiency with reticular dysgenesis (disorder)')
,('http://snomed.info/sct', '190997006', 'Severe combined immunodeficiency with low T- and B-cell numbers (disorder)')
,('http://snomed.info/sct', '190998001', 'Severe combined immunodeficiency with low or normal B-cell numbers (disorder)')
,('http://snomed.info/sct', '191011000', 'Common variable immunodeficiency with predominant abnormalities of B-cell numbers and functions (disorder)')
,('http://snomed.info/sct', '191012007', 'Common variable immunodeficiency with predominant immunoregulatory T-cell disorders (disorder)')
,('http://snomed.info/sct', '191013002', 'Common variable immunodeficiency with autoantibodies to B- or T-cells (disorder)')
,('http://snomed.info/sct', '191338000', 'Primary splenic neutropenia (disorder)')
,('http://snomed.info/sct', '191347008', 'Cyclical neutropenia (disorder)')
,('http://snomed.info/sct', '209962000', 'Myeloma-associated amyloidosis (disorder)')
,('http://snomed.info/sct', '22406001', 'Severe combined immunodeficiency due to absent lymphoid stem cells (disorder)')
,('http://snomed.info/sct', '230180003', 'Human immunodeficiency virus leukoencephalopathy (disorder)')
,('http://snomed.info/sct', '232075002', 'Lymphoma of retina (disorder)')
,('http://snomed.info/sct', '23238000', 'Common variable agammaglobulinemia (disorder)')
,('http://snomed.info/sct', '234367000', 'Pancytopenia with pancreatitis (disorder)')
,('http://snomed.info/sct', '234423001', 'Chronic benign neutropenia (disorder)')
,('http://snomed.info/sct', '234424007', 'Metabolic neutropenia (disorder)')
,('http://snomed.info/sct', '234425008', 'Autoimmune neutropenia (disorder)')
,('http://snomed.info/sct', '234576008', 'Chronic familial neutropenia (disorder)')
,('http://snomed.info/sct', '234621005', 'Factor I deficiency (disorder)')
,('http://snomed.info/sct', '236513009', 'Lymphoma of kidney (disorder)')
,('http://snomed.info/sct', '240531002', 'African Burkitts lymphoma (disorder)')
,('http://snomed.info/sct', '240794006', 'Splenic schistosomal giant cell lymphoma (disorder)')
,('http://snomed.info/sct', '24743004', 'Complement deficiency disease (disorder)')
,('http://snomed.info/sct', '247860002', 'Familial neutropenia (disorder)')
,('http://snomed.info/sct', '248693006', 'Chronic idiopathic neutropenia (disorder)')
,('http://snomed.info/sct', '267540007', 'Neutropenia caused by ionizing radiation (disorder)')
,('http://snomed.info/sct', '269476000', 'Nodular lymphoma (disorder)')
,('http://snomed.info/sct', '274905008', 'Malignant lymphoma - lymphocytic, intermediate differentiation (disorder)')
,('http://snomed.info/sct', '276811008', 'Gastric lymphoma (disorder)')
,('http://snomed.info/sct', '276815004', 'Lymphoma of intestine (disorder)')
,('http://snomed.info/sct', '276836002', 'Primary cerebral lymphoma (disorder)')
,('http://snomed.info/sct', '277474005', 'B-cell chronic lymphocytic leukemia variant (disorder)')
,('http://snomed.info/sct', '277545003', 'T-cell chronic lymphocytic leukemia (disorder)')
,('http://snomed.info/sct', '277551008', 'Splenic lymphoma with villous lymphocytes (disorder)')
,('http://snomed.info/sct', '277567002', 'T-cell prolymphocytic leukemia (disorder)')
,('http://snomed.info/sct', '277568007', 'Hairy cell leukemia variant (disorder)')
,('http://snomed.info/sct', '277569004', 'Large granular lymphocytic leukemia (disorder)')
,('http://snomed.info/sct', '277570003', 'Lymphoma with spill (disorder)')
,('http://snomed.info/sct', '277571004', 'B-cell acute lymphoblastic leukemia (disorder)')
,('http://snomed.info/sct', '277572006', 'Precursor B-cell acute lymphoblastic leukemia (disorder)')
,('http://snomed.info/sct', '277573001', 'Common acute lymphoblastic leukemia (disorder)')
,('http://snomed.info/sct', '277574007', 'Null cell acute lymphoblastic leukemia (disorder)')
,('http://snomed.info/sct', '277575008', 'T-lymphoblastic leukemia (disorder)')
,('http://snomed.info/sct', '277579002', 'Light chain myeloma (disorder)')
,('http://snomed.info/sct', '277580004', 'Non-secretory myeloma (disorder)')
,('http://snomed.info/sct', '277587001', 'Juvenile chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '277589003', 'Myelodysplastic-myeloproliferative neoplasm with neutrophilia (disorder)')
,('http://snomed.info/sct', '277602003', 'Acute megakaryoblastic leukemia (disorder)')
,('http://snomed.info/sct', '277604002', 'Malignant myeloid-lymphoid neoplasm (disorder)')
,('http://snomed.info/sct', '277613000', 'Cutaneous/peripheral T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277614006', 'Prethymic and thymic T-cell lymphoma/leukemia (disorder)')
,('http://snomed.info/sct', '277615007', 'Low grade B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277616008', 'Diffuse low grade B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277617004', 'High grade B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277618009', 'Follicular low grade B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277619001', 'B-cell prolymphocytic leukemia (disorder)')
,('http://snomed.info/sct', '277622004', 'Mucosa-associated lymphoma (disorder)')
,('http://snomed.info/sct', '277623009', 'Monocytoid B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277624003', 'Follicular malignant lymphoma - mixed cell type (disorder)')
,('http://snomed.info/sct', '277625002', 'Follicular malignant lymphoma - small cleaved cell (disorder)')
,('http://snomed.info/sct', '277626001', 'Diffuse high grade B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277627005', 'Nodular high grade B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277628000', 'Diffuse malignant lymphoma - large cleaved cell (disorder)')
,('http://snomed.info/sct', '277629008', 'Diffuse malignant lymphoma - large non-cleaved cell (disorder)')
,('http://snomed.info/sct', '277632006', 'Diffuse malignant lymphoma - centroblastic polymorphic (disorder)')
,('http://snomed.info/sct', '277642008', 'Low grade T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277643003', 'High grade T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277654008', 'Enteropathy-associated T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '277664004', 'Malignant lymphoma of testis (disorder)')
,('http://snomed.info/sct', '278051002', 'Malignant lymphoma of thyroid gland (disorder)')
,('http://snomed.info/sct', '278052009', 'Malignant lymphoma of breast (disorder)')
,('http://snomed.info/sct', '278189009', 'Hypergranular promyelocytic leukemia (disorder)')
,('http://snomed.info/sct', '278453007', 'Acute biphenotypic leukemia (disorder)')
,('http://snomed.info/sct', '285420006', 'Immunoglobulin A myeloma (disorder)')
,('http://snomed.info/sct', '285421005', 'Immunoglobulin G myeloma (disorder)')
,('http://snomed.info/sct', '285422003', 'Immunoglobulin D myeloma (disorder)')
,('http://snomed.info/sct', '285769009', 'Acute promyelocytic leukemia - hypogranular variant (disorder)')
,('http://snomed.info/sct', '285776004', 'Intermediate grade B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '302841002', 'Malignant lymphoma - small lymphocytic (disorder)')
,('http://snomed.info/sct', '302842009', 'Diffuse malignant lymphoma - centroblastic (disorder)')
,('http://snomed.info/sct', '302845006', 'Nodular malignant lymphoma, lymphocytic - well differentiated (disorder)')
,('http://snomed.info/sct', '302848008', 'Nodular malignant lymphoma, lymphocytic - intermediate differentiation (disorder)')
,('http://snomed.info/sct', '302855005', 'Subacute leukemia (disorder)')
,('http://snomed.info/sct', '302856006', 'Aleukemic leukemia (disorder)')
,('http://snomed.info/sct', '303011007', 'Neutropenic disorder (disorder)')
,('http://snomed.info/sct', '303055001', 'Malignant lymphoma, follicular center cell (disorder)')
,('http://snomed.info/sct', '303056000', 'Malignant lymphoma, follicular center cell, cleaved (disorder)')
,('http://snomed.info/sct', '303057009', 'Malignant lymphoma, follicular center cell, non-cleaved (disorder)')
,('http://snomed.info/sct', '30575002', 'Fanconis anemia (disorder)')
,('http://snomed.info/sct', '307341004', 'Atypical hairy cell leukemia (disorder)')
,('http://snomed.info/sct', '307592006', 'Basophilic leukemia (disorder)')
,('http://snomed.info/sct', '307617006', 'Neutrophilic leukemia (disorder)')
,('http://snomed.info/sct', '307623001', 'Malignant lymphoma - lymphoplasmacytic (disorder)')
,('http://snomed.info/sct', '307624007', 'Diffuse malignant lymphoma - centroblastic-centrocytic (disorder)')
,('http://snomed.info/sct', '307625008', 'Malignant lymphoma - centrocytic (disorder)')
,('http://snomed.info/sct', '307636001', 'Malignant lymphoma, mixed lymphocytic-histiocytic, nodular (disorder)')
,('http://snomed.info/sct', '307637005', 'Malignant lymphoma, centroblastic-centrocytic, follicular (disorder)')
,('http://snomed.info/sct', '307646004', 'Malignant lymphoma, lymphocytic, poorly differentiated, nodular (disorder)')
,('http://snomed.info/sct', '307647008', 'Malignant lymphoma, centroblastic type, follicular (disorder)')
,('http://snomed.info/sct', '307649006', 'Microglioma (disorder)')
,('http://snomed.info/sct', '308121000', 'Follicular lymphoma (disorder)')
,('http://snomed.info/sct', '31323000', 'Severe combined immunodeficiency disease (disorder)')
,('http://snomed.info/sct', '313427003', 'Lambda light chain myeloma (disorder)')
,('http://snomed.info/sct', '32092008', 'Toxic neutropenia (disorder)')
,('http://snomed.info/sct', '32278006', 'Myeloma kidney (disorder)')
,('http://snomed.info/sct', '3439009', 'Severe combined immunodeficiency due to absent peripheral T cell maturation (disorder)')
,('http://snomed.info/sct', '350951000119101', 'B-cell lymphoma of intra-abdominal lymph nodes (disorder)')
,('http://snomed.info/sct', '351211000119104', 'B-cell lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '352251000119109', 'Small lymphocytic B-cell lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '352411000119109', 'Small lymphocytic B-cell lymphoma of intra-abdominal lymph nodes (disorder)')
,('http://snomed.info/sct', '352791000119108', 'Non-Hodgkins lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '354851000119101', 'Follicular non-Hodgkins lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '359631009', 'Acute myeloid leukemia, minimal differentiation, FAB M0 (disorder)')
,('http://snomed.info/sct', '359640008', 'Acute myeloid leukemia without maturation, FAB M1 (disorder)')
,('http://snomed.info/sct', '359648001', 'Acute myeloid leukemia with maturation, FAB M2 (disorder)')
,('http://snomed.info/sct', '36070007', 'Wiskott-Aldrich syndrome (disorder)')
,('http://snomed.info/sct', '362993009', 'Autosomal recessive severe combined immunodeficiency disease (disorder)')
,('http://snomed.info/sct', '363009005', 'Complement component deficiency (disorder)')
,('http://snomed.info/sct', '371012000', 'Acute lymphoblastic leukemia, transitional pre-B-cell (disorder)')
,('http://snomed.info/sct', '371134001', 'Malignant lymphoma, large cell, polymorphous, immunoblastic (disorder)')
,('http://snomed.info/sct', '38970002', 'Doan-Wright syndrome (disorder)')
,('http://snomed.info/sct', '400001003', 'Primary cutaneous lymphoma (disorder)')
,('http://snomed.info/sct', '400122007', 'Primary cutaneous T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '402880009', 'Primary cutaneous large T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '402881008', 'Primary cutaneous B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '403837005', 'Wiskott-Aldrich autosomal dominant variant syndrome (disorder)')
,('http://snomed.info/sct', '404111002', 'Lymphomatoid papulosis-associated mycosis fungoides (disorder)')
,('http://snomed.info/sct', '404122003', 'Leukemic infiltration of skin (chronic T-cell lymphocytic leukemia) (disorder)')
,('http://snomed.info/sct', '404123008', 'Leukemic infiltration of skin (T-cell prolymphocytic leukemia) (disorder)')
,('http://snomed.info/sct', '404124002', 'Leukemic infiltration of skin (T-cell lymphoblastic leukemia) (disorder)')
,('http://snomed.info/sct', '404126000', 'CD-30 positive pleomorphic large T-cell cutaneous lymphoma (disorder)')
,('http://snomed.info/sct', '404127009', 'CD-30 positive T-immunoblastic cutaneous lymphoma (disorder)')
,('http://snomed.info/sct', '404128004', 'CD-30 negative cutaneous T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '404129007', 'CD-30 negative anaplastic large T-cell cutaneous lymphoma (disorder)')
,('http://snomed.info/sct', '404130002', 'CD-30 negative pleomorphic large T-cell cutaneous lymphoma (disorder)')
,('http://snomed.info/sct', '404131003', 'CD-30 negative T-immunoblastic cutaneous lymphoma (disorder)')
,('http://snomed.info/sct', '404133000', 'Subcutaneous panniculitic cutaneous T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '404134006', 'Anaplastic large T-cell systemic malignant lymphoma (disorder)')
,('http://snomed.info/sct', '404135007', 'Angiocentric natural killer/T-cell malignant lymphoma involving skin (disorder)')
,('http://snomed.info/sct', '404136008', 'Aggressive natural killer-cell leukemia involving skin (disorder)')
,('http://snomed.info/sct', '404137004', 'Precursor B-cell lymphoblastic lymphoma involving skin (disorder)')
,('http://snomed.info/sct', '404138009', 'Small lymphocytic B-cell lymphoma involving skin (disorder)')
,('http://snomed.info/sct', '404139001', 'Leukemic infiltration of skin in hairy-cell leukemia (disorder)')
,('http://snomed.info/sct', '404140004', 'Primary cutaneous marginal zone B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '404143002', 'Primary cutaneous follicular center B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '404144008', 'Primary cutaneous diffuse large cell B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '404147001', 'Follicular center B-cell lymphoma (nodal/systemic with skin involvement) (disorder)')
,('http://snomed.info/sct', '404148006', 'Diffuse large B-cell lymphoma (nodal/systemic with skin involvement) (disorder)')
,('http://snomed.info/sct', '404149003', 'Lymphoplasmacytic B-cell lymphoma, nodal/systemic with skin involvement (disorder)')
,('http://snomed.info/sct', '404150003', 'Mantle cell B-cell lymphoma (nodal/systemic with skin involvement) (disorder)')
,('http://snomed.info/sct', '404151004', 'Leukemic infiltration of skin in myeloid leukemia (disorder)')
,('http://snomed.info/sct', '404152006', 'Leukemic infiltration of skin in acute myeloid leukemia (disorder)')
,('http://snomed.info/sct', '404153001', 'Leukemic infiltration of skin in chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '404154007', 'Leukemic infiltration of skin in monocytic leukemia (disorder)')
,('http://snomed.info/sct', '404172001', 'Mast cell leukemia affecting skin (disorder)')
,('http://snomed.info/sct', '409089005', 'Febrile neutropenia (disorder)')
,('http://snomed.info/sct', '413389003', 'Accelerated phase chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '413441006', 'Acute monocytic leukemia (disorder)')
,('http://snomed.info/sct', '413537009', 'Angioimmunoblastic T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '413587002', 'Smoldering myeloma (disorder)')
,('http://snomed.info/sct', '413656006', 'Blastic phase chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '413842007', 'Chronic myeloid leukemia in lymphoid blast crisis (disorder)')
,('http://snomed.info/sct', '413843002', 'Chronic myeloid leukemia in myeloid blast crisis (disorder)')
,('http://snomed.info/sct', '413847001', 'Chronic phase chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '414166008', 'Extranodal natural killer/T-cell lymphoma, nasal type (disorder)')
,('http://snomed.info/sct', '414553000', 'Kappa light chain myeloma (disorder)')
,('http://snomed.info/sct', '414780005', 'Mucosa-associated lymphoid tissue lymphoma of orbit (disorder)')
,('http://snomed.info/sct', '415287001', 'Relapsing chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '416729007', 'Neutropenia with acquired immunodeficiency syndrome (disorder)')
,('http://snomed.info/sct', '417321001', 'Human T-cell Lymphoma Virus Type -1 associated uveitis (disorder)')
,('http://snomed.info/sct', '41814009', 'Neutropenia with dysgranulopoiesis (disorder)')
,('http://snomed.info/sct', '420519005', 'Malignant lymphoma of the eye region (disorder)')
,('http://snomed.info/sct', '420788006', 'Intraocular non-Hodgkin malignant lymphoma (disorder)')
,('http://snomed.info/sct', '420890002', 'T-lymphoblastic leukemia/lymphoblastic lymphoma (disorder)')
,('http://snomed.info/sct', '421246008', 'T-lymphoblastic lymphoma (disorder)')
,('http://snomed.info/sct', '421283008', 'Primary lymphoma of brain with acquired immunodeficiency syndrome (disorder)')
,('http://snomed.info/sct', '421312009', 'Agranulocytosis with acquired immunodeficiency syndrome (disorder)')
,('http://snomed.info/sct', '422853008', 'Lymphoma of retroperitoneal space (disorder)')
,('http://snomed.info/sct', '425657001', 'Osteosclerotic myeloma (disorder)')
,('http://snomed.info/sct', '425688002', 'Philadelphia chromosome-positive acute lymphoblastic leukemia (disorder)')
,('http://snomed.info/sct', '426336007', 'Solitary osseous myeloma (disorder)')
,('http://snomed.info/sct', '427141003', 'Malignant lymphoma in remission (disorder)')
,('http://snomed.info/sct', '440422002', 'Asymptomatic multiple myeloma (disorder)')
,('http://snomed.info/sct', '441313008', 'Indolent multiple myeloma (disorder)')
,('http://snomed.info/sct', '441559006', 'Mantle cell lymphoma of spleen (disorder)')
,('http://snomed.info/sct', '441962003', 'Large cell lymphoma of intrapelvic lymph nodes (disorder)')
,('http://snomed.info/sct', '442537007', 'Non-Hodgkin lymphoma associated with Human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '443487006', 'Mantle cell lymphoma (disorder)')
,('http://snomed.info/sct', '444597005', 'Extranodal marginal zone lymphoma of mucosa-associated lymphoid tissue of stomach (disorder)')
,('http://snomed.info/sct', '444910004', 'Primary mediastinal (thymic) large B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '444911000', 'Acute myeloid leukemia with t(9:11)(p22.q23). MLLT3-MLL (disorder)')
,('http://snomed.info/sct', '445227008', 'Juvenile myelomonocytic leukemia (disorder)')
,('http://snomed.info/sct', '445269007', 'Extranodal marginal zone B-cell lymphoma of mucosa-associated lymphoid tissue (disorder)')
,('http://snomed.info/sct', '445406001', 'Hepatosplenic T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '445448008', 'Acute myeloid leukemia with myelodysplasia-related changes (disorder)')
,('http://snomed.info/sct', '447100004', 'Marginal zone lymphoma (disorder)')
,('http://snomed.info/sct', '447656001', 'Lymphoma of pylorus of stomach (disorder)')
,('http://snomed.info/sct', '447658000', 'Lymphoma of fundus of stomach (disorder)')
,('http://snomed.info/sct', '447766003', 'Lymphoma of pyloric antrum of stomach (disorder)')
,('http://snomed.info/sct', '447805007', 'Lymphoma of greater curvature of stomach (disorder)')
,('http://snomed.info/sct', '447806008', 'Lymphoma of cardia of stomach (disorder)')
,('http://snomed.info/sct', '447989004', 'Non-Hodgkins lymphoma of extranodal site (disorder)')
,('http://snomed.info/sct', '448212009', 'Anaplastic lymphoma kinase negative anaplastic large cell lymphoma (disorder)')
,('http://snomed.info/sct', '448213004', 'Diffuse non-Hodgkins lymphoma of prostate (disorder)')
,('http://snomed.info/sct', '448217003', 'Follicular non-Hodgkins lymphoma of prostate (disorder)')
,('http://snomed.info/sct', '448220006', 'Non-Hodgkins lymphoma of bone (disorder)')
,('http://snomed.info/sct', '448231003', 'Follicular non-Hodgkins lymphoma of nose (disorder)')
,('http://snomed.info/sct', '448254007', 'Non-Hodgkins lymphoma of central nervous system (disorder)')
,('http://snomed.info/sct', '448269008', 'Lymphoma of lesser curvature of stomach (disorder)')
,('http://snomed.info/sct', '448317000', 'Follicular non-Hodgkins lymphoma of soft tissue (disorder)')
,('http://snomed.info/sct', '448319002', 'Diffuse non-Hodgkins lymphoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '448354009', 'Non-Hodgkins lymphoma of intestine (disorder)')
,('http://snomed.info/sct', '448371005', 'Non-Hodgkins lymphoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '448372003', 'Non-Hodgkins lymphoma of lung (disorder)')
,('http://snomed.info/sct', '448376000', 'Non-Hodgkins lymphoma of ovary (disorder)')
,('http://snomed.info/sct', '448384001', 'Non-Hodgkins lymphoma of nose (disorder)')
,('http://snomed.info/sct', '448386004', 'Non-Hodgkins lymphoma of oral cavity (disorder)')
,('http://snomed.info/sct', '448387008', 'Non-Hodgkins lymphoma of testis (disorder)')
,('http://snomed.info/sct', '448447004', 'Non-Hodgkins lymphoma of skin (disorder)')
,('http://snomed.info/sct', '448465000', 'Diffuse non-Hodgkins lymphoma of testis (disorder)')
,('http://snomed.info/sct', '448468003', 'Diffuse non-Hodgkins lymphoma of oral cavity (disorder)')
,('http://snomed.info/sct', '448553002', 'Lymphoma of pelvis (disorder)')
,('http://snomed.info/sct', '448555009', 'Lymphoma of body of stomach (disorder)')
,('http://snomed.info/sct', '448560008', 'Diffuse non-Hodgkins lymphoma of extranodal site (disorder)')
,('http://snomed.info/sct', '448561007', 'Follicular non-Hodgkins lymphoma of extranodal site (disorder)')
,('http://snomed.info/sct', '448607004', 'Diffuse non-Hodgkins lymphoma of uterine cervix (disorder)')
,('http://snomed.info/sct', '448609001', 'Diffuse non-Hodgkins lymphoma of ovary (disorder)')
,('http://snomed.info/sct', '448663003', 'Diffuse non-Hodgkins lymphoma of stomach (disorder)')
,('http://snomed.info/sct', '448666006', 'Follicular non-Hodgkins lymphoma of bone (disorder)')
,('http://snomed.info/sct', '448672006', 'Follicular non-Hodgkins lymphoma of lung (disorder)')
,('http://snomed.info/sct', '448709005', 'Non-Hodgkins lymphoma of stomach (disorder)')
,('http://snomed.info/sct', '448738008', 'Non-Hodgkins lymphoma of soft tissue (disorder)')
,('http://snomed.info/sct', '448774004', 'Non-Hodgkins lymphoma of uterine cervix (disorder)')
,('http://snomed.info/sct', '448865007', 'Follicular non-Hodgkins lymphoma of skin (disorder)')
,('http://snomed.info/sct', '448867004', 'Diffuse non-Hodgkins lymphoma of lung (disorder)')
,('http://snomed.info/sct', '448995000', 'Follicular non-Hodgkins lymphoma of central nervous system (disorder)')
,('http://snomed.info/sct', '449053004', 'Lymphoma of lower esophagus (disorder)')
,('http://snomed.info/sct', '449058008', 'Follicular non-Hodgkins lymphoma of tonsil (disorder)')
,('http://snomed.info/sct', '449059000', 'Follicular non-Hodgkins lymphoma of uterine cervix (disorder)')
,('http://snomed.info/sct', '449063007', 'Follicular non-Hodgkins lymphoma of oral cavity (disorder)')
,('http://snomed.info/sct', '449065000', 'Diffuse non-Hodgkins lymphoma of nose (disorder)')
,('http://snomed.info/sct', '449072004', 'Lymphoma of gastrointestinal tract (disorder)')
,('http://snomed.info/sct', '449074003', 'Lymphoma of small intestine (disorder)')
,('http://snomed.info/sct', '449075002', 'Lymphoma of cardioesophageal junction (disorder)')
,('http://snomed.info/sct', '449173006', 'Diffuse non-Hodgkins lymphoma of tonsil (disorder)')
,('http://snomed.info/sct', '449176003', 'Diffuse non-Hodgkins lymphoma of intestine (disorder)')
,('http://snomed.info/sct', '449177007', 'Diffuse non-Hodgkins lymphoma of bone (disorder)')
,('http://snomed.info/sct', '449216004', 'Diffuse non-Hodgkins lymphoma of soft tissue (disorder)')
,('http://snomed.info/sct', '449217008', 'Diffuse non-Hodgkins lymphoma of skin (disorder)')
,('http://snomed.info/sct', '449218003', 'Lymphoma of sigmoid colon (disorder)')
,('http://snomed.info/sct', '449219006', 'Follicular non-Hodgkins lymphoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '449220000', 'Diffuse follicle center lymphoma (disorder)')
,('http://snomed.info/sct', '449221001', 'Diffuse non-Hodgkins lymphoma of central nervous system (disorder)')
,('http://snomed.info/sct', '449222008', 'Follicular non-Hodgkins lymphoma of stomach (disorder)')
,('http://snomed.info/sct', '449292003', 'Non-Hodgkins lymphoma of tonsil (disorder)')
,('http://snomed.info/sct', '449307001', 'Follicular non-Hodgkins lymphoma of ovary (disorder)')
,('http://snomed.info/sct', '449318001', 'Non-Hodgkins lymphoma of prostate (disorder)')
,('http://snomed.info/sct', '449418000', 'Follicular non-Hodgkins lymphoma of testis (disorder)')
,('http://snomed.info/sct', '449419008', 'Follicular non-Hodgkins lymphoma of intestine (disorder)')
,('http://snomed.info/sct', '46359005', 'Neutropenia associated with infectious disease (disorder)')
,('http://snomed.info/sct', '49555001', 'Severe combined immunodeficiency due to absent T cell receptor (disorder)')
,('http://snomed.info/sct', '55444004', 'Transient neonatal neutropenia (disorder)')
,('http://snomed.info/sct', '58639003', 'Doan-Wiseman syndrome (disorder)')
,('http://snomed.info/sct', '5876000', 'Acquired pancytopenia (disorder)')
,('http://snomed.info/sct', '65623009', 'Immune neutropenia (disorder)')
,('http://snomed.info/sct', '65880007', 'X-linked agammaglobulinemia (disorder)')
,('http://snomed.info/sct', '68261000119102', 'Diffuse non-Hodgkins lymphoma Lugano stage I (disorder)')
,('http://snomed.info/sct', '68271000119108', 'Diffuse non-Hodgkins lymphoma Lugano stage II (disorder)')
,('http://snomed.info/sct', '68291000119109', 'Diffuse non-Hodgkins lymphoma Lugano stage IV (disorder)')
,('http://snomed.info/sct', '68504005', 'Ataxia-telangiectasia syndrome (disorder)')
,('http://snomed.info/sct', '699657009', 'Hepatosplenic gamma-delta cell lymphoma (disorder)')
,('http://snomed.info/sct', '700058006', 'Ataxia-telangiectasia-like disorder (disorder)')
,('http://snomed.info/sct', '702785000', 'Large cell anaplastic lymphoma T cell and Null cell type (disorder)')
,('http://snomed.info/sct', '702786004', 'Follicular non-Hodgkins lymphoma diffuse follicle center sub-type grade 1 (disorder)')
,('http://snomed.info/sct', '702977001', 'Follicular non-Hodgkins lymphoma diffuse follicle center cell sub-type grade 2 (disorder)')
,('http://snomed.info/sct', '703626001', 'Anaplastic large cell lymphoma, T/Null cell, primary systemic type (disorder)')
,('http://snomed.info/sct', '713325002', 'Primary cerebral lymphoma co-occurrent with human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '713516007', 'Primary effusion lymphoma (disorder)')
,('http://snomed.info/sct', '713530002', 'Agranulocytosis co-occurrent with human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '713718006', 'Diffuse non-Hodgkin immunoblastic lymphoma co-occurrent with human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '713897006', 'Burkitt lymphoma co-occurrent with human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '714463003', 'Primary effusion lymphoma co-occurrent with infection caused by Human herpesvirus 8 (disorder)')
,('http://snomed.info/sct', '715950008', 'Anaplastic lymphoma kinase positive large B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '716788007', 'Epstein-Barr virus positive diffuse large B-cell lymphoma of elderly (disorder)')
,('http://snomed.info/sct', '718200007', 'Primary pulmonary lymphoma (disorder)')
,('http://snomed.info/sct', '720853005', 'Severe combined immunodeficiency, microcephaly, growth retardation, sensitivity to ionizing radiation syndrome (disorder)')
,('http://snomed.info/sct', '721555001', 'Follicular lymphoma of small intestine (disorder)')
,('http://snomed.info/sct', '721762007', 'Adult T-cell leukemia/lymphoma of skin (disorder)')
,('http://snomed.info/sct', '722067005', 'Severe combined immunodeficiency with hypereosinophilia (disorder)')
,('http://snomed.info/sct', '722954005', 'B-cell lymphoma unclassifiable with features intermediate between classical Hodgkin lymphoma and diffuse large B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '723889003', 'B lymphoblastic leukemia lymphoma with t(9:22) (q34.q11.2). BCR-ABL 1 (disorder)')
,('http://snomed.info/sct', '724645006', 'T-cell histiocyte rich large B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '724647003', 'Diffuse large B-cell lymphoma co-occurrent with chronic inflammation caused by Epstein-Barr virus (disorder)')
,('http://snomed.info/sct', '724648008', 'Plasmablastic lymphoma (disorder)')
,('http://snomed.info/sct', '726721002', 'Nodal marginal zone B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '733627006', 'Primary cutaneous gamma-delta-positive T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '734066005', 'Diffuse large B-cell lymphoma of central nervous system (disorder)')
,('http://snomed.info/sct', '735332000', 'Primary cutaneous diffuse large cell B-cell lymphoma of lower extremity (disorder)')
,('http://snomed.info/sct', '736322001', 'Pediatric follicular lymphoma (disorder)')
,('http://snomed.info/sct', '738770003', 'Anaplastic lymphoma kinase positive anaplastic large cell lymphoma (disorder)')
,('http://snomed.info/sct', '762690000', 'Classical Hodgkin lymphoma (disorder)')
,('http://snomed.info/sct', '763065008', 'Ataxia telangiectasia variant (disorder)')
,('http://snomed.info/sct', '763477007', 'Primary lymphoma of conjunctiva (disorder)')
,('http://snomed.info/sct', '763666008', 'Splenic marginal zone B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '763719001', 'Hydroa vacciniforme-like lymphoma (disorder)')
,('http://snomed.info/sct', '763884007', 'Splenic diffuse red pulp small B-cell lymphoma (disorder)')
,('http://snomed.info/sct', '765136002', 'Primary cutaneous CD8 positive aggressive epidermotropic cytotoxic T-cell lymphoma (disorder)')
,('http://snomed.info/sct', '766935007', 'Primary bone lymphoma (disorder)')
,('http://snomed.info/sct', '771443008', 'Complement component 3 deficiency (disorder)')
,('http://snomed.info/sct', '773488000', 'Combined immunodeficiency due to mucosa-associated lymphoid tissue lymphoma translocation gene 1 deficiency (disorder)')
,('http://snomed.info/sct', '773995001', 'Primary cutaneous anaplastic large cell lymphoma (disorder)')
,('http://snomed.info/sct', '782919005', 'Classical Hodgkin lymphoma type posttransplant lymphoproliferative disorder (morphologic abnormality)')
,('http://snomed.info/sct', '783541009', 'Breast implant-associated anaplastic large-cell lymphoma (disorder)')
,('http://snomed.info/sct', '78378009', 'Isoimmune neutropenia (disorder)')
,('http://snomed.info/sct', '838355002', 'Acute myeloid leukemia with CBFB::MYH11 fusion (disorder)')
,('http://snomed.info/sct', '89655007', 'Congenital neutropenia (disorder)')
,('http://snomed.info/sct', '91855006', 'Acute leukemia, disease (disorder)')
,('http://snomed.info/sct', '91857003', 'Acute lymphoid leukemia, disease (disorder)')
,('http://snomed.info/sct', '91861009', 'Acute myeloid leukemia (disorder)')
,('http://snomed.info/sct', '92812005', 'Chronic leukemia, disease (disorder)')
,('http://snomed.info/sct', '92818009', 'Chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '93143009', 'Leukemia, disease (disorder)')
,('http://snomed.info/sct', '93151007', 'Hairy cell leukemia of spleen (disorder)')
,('http://snomed.info/sct', '93191005', 'Malignant lymphoma of intra-abdominal lymph nodes (disorder)')
,('http://snomed.info/sct', '93192003', 'Malignant lymphoma of intrapelvic lymph nodes (disorder)')
,('http://snomed.info/sct', '93193008', 'Malignant lymphoma of intrathoracic lymph nodes (disorder)')
,('http://snomed.info/sct', '93197009', 'Malignant lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '93198004', 'Malignant lymphoma of spleen (disorder)')
,('http://snomed.info/sct', '93199007', 'Malignant lymphoma of extranodal AND/OR solid organ site (disorder)')
,('http://snomed.info/sct', '94392001', 'Metastatic malignant neoplasm to lymph node (disorder)')
,('http://snomed.info/sct', '94396003', 'Metastatic malignant neoplasm to lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '95186006', 'Nodular lymphoma of intra-abdominal lymph nodes (disorder)')
,('http://snomed.info/sct', '95187002', 'Nodular lymphoma of intrapelvic lymph nodes (disorder)')
,('http://snomed.info/sct', '95188007', 'Nodular lymphoma of intrathoracic lymph nodes (disorder)')
,('http://snomed.info/sct', '95192000', 'Nodular lymphoma of lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '95193005', 'Nodular lymphoma of spleen (disorder)')
,('http://snomed.info/sct', '95210003', 'Plasma cell leukemia, disease (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B20', 'Human immunodeficiency virus [HIV] disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B97.35', 'Human immunodeficiency virus, type 2 [HIV 2] as the cause of diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.00', 'Nodular lymphocyte predominant Hodgkin lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.01', 'Nodular lymphocyte predominant Hodgkin lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.02', 'Nodular lymphocyte predominant Hodgkin lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.03', 'Nodular lymphocyte predominant Hodgkin lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.04', 'Nodular lymphocyte predominant Hodgkin lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.05', 'Nodular lymphocyte predominant Hodgkin lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.06', 'Nodular lymphocyte predominant Hodgkin lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.07', 'Nodular lymphocyte predominant Hodgkin lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.08', 'Nodular lymphocyte predominant Hodgkin lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.09', 'Nodular lymphocyte predominant Hodgkin lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.10', 'Nodular sclerosis Hodgkin lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.11', 'Nodular sclerosis Hodgkin lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.12', 'Nodular sclerosis Hodgkin lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.13', 'Nodular sclerosis Hodgkin lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.14', 'Nodular sclerosis Hodgkin lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.15', 'Nodular sclerosis Hodgkin lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.16', 'Nodular sclerosis Hodgkin lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.17', 'Nodular sclerosis Hodgkin lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.18', 'Nodular sclerosis Hodgkin lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.19', 'Nodular sclerosis Hodgkin lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.20', 'Mixed cellularity Hodgkin lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.21', 'Mixed cellularity Hodgkin lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.22', 'Mixed cellularity Hodgkin lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.23', 'Mixed cellularity Hodgkin lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.24', 'Mixed cellularity Hodgkin lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.25', 'Mixed cellularity Hodgkin lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.26', 'Mixed cellularity Hodgkin lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.27', 'Mixed cellularity Hodgkin lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.28', 'Mixed cellularity Hodgkin lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.29', 'Mixed cellularity Hodgkin lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.30', 'Lymphocyte depleted Hodgkin lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.31', 'Lymphocyte depleted Hodgkin lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.32', 'Lymphocyte depleted Hodgkin lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.33', 'Lymphocyte depleted Hodgkin lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.34', 'Lymphocyte depleted Hodgkin lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.35', 'Lymphocyte depleted Hodgkin lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.36', 'Lymphocyte depleted Hodgkin lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.37', 'Lymphocyte depleted Hodgkin lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.38', 'Lymphocyte depleted Hodgkin lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.39', 'Lymphocyte depleted Hodgkin lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.40', 'Lymphocyte-rich Hodgkin lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.41', 'Lymphocyte-rich Hodgkin lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.42', 'Lymphocyte-rich Hodgkin lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.43', 'Lymphocyte-rich Hodgkin lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.44', 'Lymphocyte-rich Hodgkin lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.45', 'Lymphocyte-rich Hodgkin lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.46', 'Lymphocyte-rich Hodgkin lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.47', 'Lymphocyte-rich Hodgkin lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.48', 'Lymphocyte-rich Hodgkin lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.49', 'Lymphocyte-rich Hodgkin lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.70', 'Other Hodgkin lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.71', 'Other Hodgkin lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.72', 'Other Hodgkin lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.73', 'Other Hodgkin lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.74', 'Other Hodgkin lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.75', 'Other Hodgkin lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.76', 'Other Hodgkin lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.77', 'Other Hodgkin lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.78', 'Other Hodgkin lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.79', 'Other Hodgkin lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.90', 'Hodgkin lymphoma, unspecified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.91', 'Hodgkin lymphoma, unspecified, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.92', 'Hodgkin lymphoma, unspecified, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.93', 'Hodgkin lymphoma, unspecified, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.94', 'Hodgkin lymphoma, unspecified, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.95', 'Hodgkin lymphoma, unspecified, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.96', 'Hodgkin lymphoma, unspecified, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.97', 'Hodgkin lymphoma, unspecified, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.98', 'Hodgkin lymphoma, unspecified, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C81.99', 'Hodgkin lymphoma, unspecified, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.00', 'Follicular lymphoma grade I, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.01', 'Follicular lymphoma grade I, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.02', 'Follicular lymphoma grade I, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.03', 'Follicular lymphoma grade I, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.04', 'Follicular lymphoma grade I, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.05', 'Follicular lymphoma grade I, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.06', 'Follicular lymphoma grade I, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.07', 'Follicular lymphoma grade I, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.08', 'Follicular lymphoma grade I, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.09', 'Follicular lymphoma grade I, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.10', 'Follicular lymphoma grade II, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.11', 'Follicular lymphoma grade II, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.12', 'Follicular lymphoma grade II, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.13', 'Follicular lymphoma grade II, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.14', 'Follicular lymphoma grade II, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.15', 'Follicular lymphoma grade II, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.16', 'Follicular lymphoma grade II, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.17', 'Follicular lymphoma grade II, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.18', 'Follicular lymphoma grade II, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.19', 'Follicular lymphoma grade II, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.20', 'Follicular lymphoma grade III, unspecified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.21', 'Follicular lymphoma grade III, unspecified, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.22', 'Follicular lymphoma grade III, unspecified, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.23', 'Follicular lymphoma grade III, unspecified, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.24', 'Follicular lymphoma grade III, unspecified, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.25', 'Follicular lymphoma grade III, unspecified, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.26', 'Follicular lymphoma grade III, unspecified, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.27', 'Follicular lymphoma grade III, unspecified, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.28', 'Follicular lymphoma grade III, unspecified, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.29', 'Follicular lymphoma grade III, unspecified, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.30', 'Follicular lymphoma grade IIIa, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.31', 'Follicular lymphoma grade IIIa, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.32', 'Follicular lymphoma grade IIIa, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.33', 'Follicular lymphoma grade IIIa, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.34', 'Follicular lymphoma grade IIIa, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.35', 'Follicular lymphoma grade IIIa, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.36', 'Follicular lymphoma grade IIIa, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.37', 'Follicular lymphoma grade IIIa, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.38', 'Follicular lymphoma grade IIIa, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.39', 'Follicular lymphoma grade IIIa, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.40', 'Follicular lymphoma grade IIIb, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.41', 'Follicular lymphoma grade IIIb, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.42', 'Follicular lymphoma grade IIIb, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.43', 'Follicular lymphoma grade IIIb, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.44', 'Follicular lymphoma grade IIIb, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.45', 'Follicular lymphoma grade IIIb, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.46', 'Follicular lymphoma grade IIIb, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.47', 'Follicular lymphoma grade IIIb, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.48', 'Follicular lymphoma grade IIIb, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.49', 'Follicular lymphoma grade IIIb, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.50', 'Diffuse follicle center lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.51', 'Diffuse follicle center lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.52', 'Diffuse follicle center lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.53', 'Diffuse follicle center lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.54', 'Diffuse follicle center lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.55', 'Diffuse follicle center lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.56', 'Diffuse follicle center lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.57', 'Diffuse follicle center lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.58', 'Diffuse follicle center lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.59', 'Diffuse follicle center lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.60', 'Cutaneous follicle center lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.61', 'Cutaneous follicle center lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.62', 'Cutaneous follicle center lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.63', 'Cutaneous follicle center lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.64', 'Cutaneous follicle center lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.65', 'Cutaneous follicle center lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.66', 'Cutaneous follicle center lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.67', 'Cutaneous follicle center lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.68', 'Cutaneous follicle center lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.69', 'Cutaneous follicle center lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.80', 'Other types of follicular lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.81', 'Other types of follicular lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.82', 'Other types of follicular lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.83', 'Other types of follicular lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.84', 'Other types of follicular lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.85', 'Other types of follicular lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.86', 'Other types of follicular lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.87', 'Other types of follicular lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.88', 'Other types of follicular lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.89', 'Other types of follicular lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.90', 'Follicular lymphoma, unspecified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.91', 'Follicular lymphoma, unspecified, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.92', 'Follicular lymphoma, unspecified, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.93', 'Follicular lymphoma, unspecified, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.94', 'Follicular lymphoma, unspecified, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.95', 'Follicular lymphoma, unspecified, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.96', 'Follicular lymphoma, unspecified, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.97', 'Follicular lymphoma, unspecified, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.98', 'Follicular lymphoma, unspecified, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C82.99', 'Follicular lymphoma, unspecified, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.10', 'Mantle cell lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.11', 'Mantle cell lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.12', 'Mantle cell lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.13', 'Mantle cell lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.14', 'Mantle cell lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.15', 'Mantle cell lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.16', 'Mantle cell lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.17', 'Mantle cell lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.18', 'Mantle cell lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.19', 'Mantle cell lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.31', 'Diffuse large B-cell lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.32', 'Diffuse large B-cell lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.33', 'Diffuse large B-cell lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.34', 'Diffuse large B-cell lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.35', 'Diffuse large B-cell lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.36', 'Diffuse large B-cell lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.37', 'Diffuse large B-cell lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.38', 'Diffuse large B-cell lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.39', 'Diffuse large B-cell lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.70', 'Burkitt lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.71', 'Burkitt lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.72', 'Burkitt lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.73', 'Burkitt lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.74', 'Burkitt lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.75', 'Burkitt lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.76', 'Burkitt lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.77', 'Burkitt lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.78', 'Burkitt lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.79', 'Burkitt lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.80', 'Other non-follicular lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.81', 'Other non-follicular lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.82', 'Other non-follicular lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.83', 'Other non-follicular lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.84', 'Other non-follicular lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.85', 'Other non-follicular lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.86', 'Other non-follicular lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.87', 'Other non-follicular lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.88', 'Other non-follicular lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C83.89', 'Other non-follicular lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.40', 'Peripheral T-cell lymphoma, not elsewhere classified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.41', 'Peripheral T-cell lymphoma, not elsewhere classified, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.42', 'Peripheral T-cell lymphoma, not elsewhere classified, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.43', 'Peripheral T-cell lymphoma, not elsewhere classified, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.44', 'Peripheral T-cell lymphoma, not elsewhere classified, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.45', 'Peripheral T-cell lymphoma, not elsewhere classified, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.46', 'Peripheral T-cell lymphoma, not elsewhere classified, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.47', 'Peripheral T-cell lymphoma, not elsewhere classified, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.48', 'Peripheral T-cell lymphoma, not elsewhere classified, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.49', 'Peripheral T-cell lymphoma, not elsewhere classified, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.60', 'Anaplastic large cell lymphoma, ALK-positive, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.61', 'Anaplastic large cell lymphoma, ALK-positive, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.62', 'Anaplastic large cell lymphoma, ALK-positive, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.63', 'Anaplastic large cell lymphoma, ALK-positive, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.64', 'Anaplastic large cell lymphoma, ALK-positive, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.65', 'Anaplastic large cell lymphoma, ALK-positive, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.66', 'Anaplastic large cell lymphoma, ALK-positive, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.67', 'Anaplastic large cell lymphoma, ALK-positive, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.68', 'Anaplastic large cell lymphoma, ALK-positive, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.69', 'Anaplastic large cell lymphoma, ALK-positive, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.70', 'Anaplastic large cell lymphoma, ALK-negative, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.71', 'Anaplastic large cell lymphoma, ALK-negative, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.72', 'Anaplastic large cell lymphoma, ALK-negative, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.73', 'Anaplastic large cell lymphoma, ALK-negative, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.74', 'Anaplastic large cell lymphoma, ALK-negative, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.75', 'Anaplastic large cell lymphoma, ALK-negative, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.76', 'Anaplastic large cell lymphoma, ALK-negative, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.77', 'Anaplastic large cell lymphoma, ALK-negative, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.78', 'Anaplastic large cell lymphoma, ALK-negative, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.79', 'Anaplastic large cell lymphoma, ALK-negative, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.90', 'Mature T/NK-cell lymphomas, unspecified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.91', 'Mature T/NK-cell lymphomas, unspecified, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.92', 'Mature T/NK-cell lymphomas, unspecified, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.93', 'Mature T/NK-cell lymphomas, unspecified, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.94', 'Mature T/NK-cell lymphomas, unspecified, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.95', 'Mature T/NK-cell lymphomas, unspecified, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.96', 'Mature T/NK-cell lymphomas, unspecified, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.97', 'Mature T/NK-cell lymphomas, unspecified, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.98', 'Mature T/NK-cell lymphomas, unspecified, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.99', 'Mature T/NK-cell lymphomas, unspecified, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A0', 'Cutaneous T-cell lymphoma, unspecified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A1', 'Cutaneous T-cell lymphoma, unspecified lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A2', 'Cutaneous T-cell lymphoma, unspecified, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A3', 'Cutaneous T-cell lymphoma, unspecified, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A4', 'Cutaneous T-cell lymphoma, unspecified, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A5', 'Cutaneous T-cell lymphoma, unspecified, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A6', 'Cutaneous T-cell lymphoma, unspecified, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A7', 'Cutaneous T-cell lymphoma, unspecified, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A8', 'Cutaneous T-cell lymphoma, unspecified, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.A9', 'Cutaneous T-cell lymphoma, unspecified, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z0', 'Other mature T/NK-cell lymphomas, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z1', 'Other mature T/NK-cell lymphomas, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z2', 'Other mature T/NK-cell lymphomas, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z3', 'Other mature T/NK-cell lymphomas, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z4', 'Other mature T/NK-cell lymphomas, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z5', 'Other mature T/NK-cell lymphomas, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z6', 'Other mature T/NK-cell lymphomas, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z7', 'Other mature T/NK-cell lymphomas, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z8', 'Other mature T/NK-cell lymphomas, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C84.Z9', 'Other mature T/NK-cell lymphomas, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.10', 'Unspecified B-cell lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.11', 'Unspecified B-cell lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.12', 'Unspecified B-cell lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.13', 'Unspecified B-cell lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.14', 'Unspecified B-cell lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.15', 'Unspecified B-cell lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.16', 'Unspecified B-cell lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.17', 'Unspecified B-cell lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.18', 'Unspecified B-cell lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.19', 'Unspecified B-cell lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.20', 'Mediastinal (thymic) large B-cell lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.21', 'Mediastinal (thymic) large B-cell lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.22', 'Mediastinal (thymic) large B-cell lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.23', 'Mediastinal (thymic) large B-cell lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.24', 'Mediastinal (thymic) large B-cell lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.25', 'Mediastinal (thymic) large B-cell lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.26', 'Mediastinal (thymic) large B-cell lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.27', 'Mediastinal (thymic) large B-cell lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.28', 'Mediastinal (thymic) large B-cell lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.29', 'Mediastinal (thymic) large B-cell lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.80', 'Other specified types of non-Hodgkin lymphoma, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.81', 'Other specified types of non-Hodgkin lymphoma, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.82', 'Other specified types of non-Hodgkin lymphoma, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.83', 'Other specified types of non-Hodgkin lymphoma, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.84', 'Other specified types of non-Hodgkin lymphoma, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.85', 'Other specified types of non-Hodgkin lymphoma, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.86', 'Other specified types of non-Hodgkin lymphoma, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.87', 'Other specified types of non-Hodgkin lymphoma, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.88', 'Other specified types of non-Hodgkin lymphoma, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.89', 'Other specified types of non-Hodgkin lymphoma, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.90', 'Non-Hodgkin lymphoma, unspecified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.91', 'Non-Hodgkin lymphoma, unspecified, lymph nodes of head, face, and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.92', 'Non-Hodgkin lymphoma, unspecified, intrathoracic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.93', 'Non-Hodgkin lymphoma, unspecified, intra-abdominal lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.94', 'Non-Hodgkin lymphoma, unspecified, lymph nodes of axilla and upper limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.95', 'Non-Hodgkin lymphoma, unspecified, lymph nodes of inguinal region and lower limb')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.96', 'Non-Hodgkin lymphoma, unspecified, intrapelvic lymph nodes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.97', 'Non-Hodgkin lymphoma, unspecified, spleen')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.98', 'Non-Hodgkin lymphoma, unspecified, lymph nodes of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C85.99', 'Non-Hodgkin lymphoma, unspecified, extranodal and solid organ sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C86.0', 'Extranodal NK/T-cell lymphoma, nasal type')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C86.1', 'Hepatosplenic T-cell lymphoma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C86.2', 'Enteropathy-type (intestinal) T-cell lymphoma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C86.3', 'Subcutaneous panniculitis-like T-cell lymphoma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C86.4', 'Blastic NK-cell lymphoma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C86.6', 'Primary cutaneous CD30-positive T-cell proliferations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C88.4', 'Extranodal marginal zone B-cell lymphoma of mucosa-associated lymphoid tissue [MALT-lymphoma]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C90.00', 'Multiple myeloma not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C90.02', 'Multiple myeloma in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C90.10', 'Plasma cell leukemia not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C90.12', 'Plasma cell leukemia in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.00', 'Acute lymphoblastic leukemia not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.02', 'Acute lymphoblastic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.30', 'Prolymphocytic leukemia of B-cell type not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.32', 'Prolymphocytic leukemia of B-cell type, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.50', 'Adult T-cell lymphoma/leukemia (HTLV-1-associated) not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.52', 'Adult T-cell lymphoma/leukemia (HTLV-1-associated), in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.60', 'Prolymphocytic leukemia of T-cell type not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.62', 'Prolymphocytic leukemia of T-cell type, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.90', 'Lymphoid leukemia, unspecified not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.92', 'Lymphoid leukemia, unspecified, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.A0', 'Mature B-cell leukemia Burkitt-type not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.A2', 'Mature B-cell leukemia Burkitt-type, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.Z0', 'Other lymphoid leukemia not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C91.Z2', 'Other lymphoid leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.00', 'Acute myeloblastic leukemia, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.02', 'Acute myeloblastic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.10', 'Chronic myeloid leukemia, BCR/ABL-positive, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.12', 'Chronic myeloid leukemia, BCR/ABL-positive, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.20', 'Atypical chronic myeloid leukemia, BCR/ABL-negative, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.22', 'Atypical chronic myeloid leukemia, BCR/ABL-negative, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.40', 'Acute promyelocytic leukemia, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.42', 'Acute promyelocytic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.50', 'Acute myelomonocytic leukemia, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.52', 'Acute myelomonocytic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.60', 'Acute myeloid leukemia with 11q23-abnormality not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.62', 'Acute myeloid leukemia with 11q23-abnormality in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.90', 'Myeloid leukemia, unspecified, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.92', 'Myeloid leukemia, unspecified in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.A0', 'Acute myeloid leukemia with multilineage dysplasia, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.A2', 'Acute myeloid leukemia with multilineage dysplasia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.Z0', 'Other myeloid leukemia not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C92.Z2', 'Other myeloid leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.00', 'Acute monoblastic/monocytic leukemia, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.02', 'Acute monoblastic/monocytic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.10', 'Chronic myelomonocytic leukemia not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.12', 'Chronic myelomonocytic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.30', 'Juvenile myelomonocytic leukemia, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.32', 'Juvenile myelomonocytic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.90', 'Monocytic leukemia, unspecified, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.92', 'Monocytic leukemia, unspecified in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.Z0', 'Other monocytic leukemia, not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C93.Z2', 'Other monocytic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C94.20', 'Acute megakaryoblastic leukemia not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C94.22', 'Acute megakaryoblastic leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C94.30', 'Mast cell leukemia not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C94.32', 'Mast cell leukemia, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C94.80', 'Other specified leukemias not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C94.82', 'Other specified leukemias, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C95.00', 'Acute leukemia of unspecified cell type not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C95.02', 'Acute leukemia of unspecified cell type, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C95.10', 'Chronic leukemia of unspecified cell type not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C95.12', 'Chronic leukemia of unspecified cell type, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C95.90', 'Leukemia, unspecified not having achieved remission')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C95.92', 'Leukemia, unspecified, in relapse')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C96.4', 'Sarcoma of dendritic cells (accessory cells)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C96.9', 'Malignant neoplasm of lymphoid, hematopoietic and related tissue, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C96.Z', 'Other specified malignant neoplasms of lymphoid, hematopoietic and related tissue')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D46.9', 'Myelodysplastic syndrome, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D46.Z', 'Other myelodysplastic syndromes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D61.818', 'Other pancytopenia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D70.0', 'Congenital agranulocytosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D70.3', 'Neutropenia due to infection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D70.4', 'Cyclic neutropenia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D70.8', 'Other neutropenia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D70.9', 'Neutropenia, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D73.81', 'Neutropenic splenomegaly')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D80.0', 'Hereditary hypogammaglobulinemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D80.1', 'Nonfamilial hypogammaglobulinemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D80.2', 'Selective deficiency of immunoglobulin A [IgA]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D80.7', 'Transient hypogammaglobulinemia of infancy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D80.8', 'Other immunodeficiencies with predominantly antibody defects')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D80.9', 'Immunodeficiency with predominantly antibody defects, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D81.0', 'Severe combined immunodeficiency [SCID] with reticular dysgenesis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D81.1', 'Severe combined immunodeficiency [SCID] with low T- and B-cell numbers')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D81.2', 'Severe combined immunodeficiency [SCID] with low or normal B-cell numbers')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D81.31', 'Severe combined immunodeficiency due to adenosine deaminase deficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D81.89', 'Other combined immunodeficiencies')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D81.9', 'Combined immunodeficiency, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D82.0', 'Wiskott-Aldrich syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D82.3', 'Immunodeficiency following hereditary defective response to Epstein-Barr virus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D82.8', 'Immunodeficiency associated with other specified major defects')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D82.9', 'Immunodeficiency associated with major defect, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D83.0', 'Common variable immunodeficiency with predominant abnormalities of B-cell numbers and function')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D83.1', 'Common variable immunodeficiency with predominant immunoregulatory T-cell disorders')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D83.2', 'Common variable immunodeficiency with autoantibodies to B- or T-cells')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D83.8', 'Other common variable immunodeficiencies')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D83.9', 'Common variable immunodeficiency, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D84.1', 'Defects in the complement system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D84.81', 'Immunodeficiency due to conditions classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D84.821', 'Immunodeficiency due to drugs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D84.822', 'Immunodeficiency due to external causes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D84.9', 'Immunodeficiency, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E70.330', 'Chediak-Higashi syndrome')
) AS t (system, code, display) ;