create or replace view irae__lab_diabetes_screening as select * from (values
('http://loinc.org', '10449-7', 'Glucose [Mass/volume] in Serum or Plasma --1 hour post meal')
,('http://loinc.org', '10450-5', 'Glucose [Mass/volume] in Serum or Plasma --10 hours fasting')
,('http://loinc.org', '1521-4', 'Glucose [Mass/volume] in Serum or Plasma --2 hours post meal')
,('http://loinc.org', '1547-9', 'Glucose [Mass/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '1550-3', 'Glucose [Mass/volume] in Serum or Plasma --pre 12 hour fast')
,('http://loinc.org', '1554-5', 'Glucose [Mass/volume] in Serum or Plasma --12 hours fasting')
,('http://loinc.org', '1556-0', 'Fasting glucose [Mass/volume] in Capillary blood')
,('http://loinc.org', '1557-8', 'Fasting glucose [Mass/volume] in Venous blood')
,('http://loinc.org', '1558-6', 'Fasting glucose [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '16915-1', 'Glucose [Mass/volume] in Serum or Plasma --post meal')
,('http://loinc.org', '17856-6', 'Hemoglobin A1c/Hemoglobin.total in Blood by HPLC')
,('http://loinc.org', '17865-7', 'Glucose [Mass/volume] in Serum or Plasma --8 hours fasting')
,('http://loinc.org', '21004-7', 'Glucose tolerance [Interpretation] in Serum or Plasma')
,('http://loinc.org', '2339-0', 'Glucose [Mass/volume] in Blood')
,('http://loinc.org', '2340-8', 'Glucose [Mass/volume] in Blood by Automated test strip')
,('http://loinc.org', '2341-6', 'Glucose [Mass/volume] in Blood by Test strip manual')
,('http://loinc.org', '2345-7', 'Glucose [Mass/volume] in Serum or Plasma')
,('http://www.ama-assn.org/go/cpt', '3044F', 'Most recent hemoglobin A1c (HbA1c) level less than 7.0% (DM)')
,('http://www.ama-assn.org/go/cpt', '3046F', 'Most recent hemoglobin A1c level greater than 9.0% (DM)')
,('http://loinc.org', '32016-8', 'Glucose [Mass/volume] in Capillary blood')
,('http://loinc.org', '40858-3', 'Glucose [Mass/volume] in Capillary blood --baseline')
,('http://loinc.org', '41604-0', 'Fasting glucose [Mass/volume] in Capillary blood by Glucometer')
,('http://loinc.org', '41651-1', 'Glucose [Mass/volume] in Arterial blood')
,('http://loinc.org', '41652-9', 'Glucose [Mass/volume] in Venous blood')
,('http://loinc.org', '41653-7', 'Glucose [Mass/volume] in Capillary blood by Glucometer')
,('http://loinc.org', '4548-4', 'Hemoglobin A1c/Hemoglobin.total in Blood')
,('http://loinc.org', '4549-2', 'Hemoglobin A1c/Hemoglobin.total in Blood by Electrophoresis')
,('http://loinc.org', '49688-5', 'Glucose tolerance [Interpretation] in Serum or Plasma Narrative--post 75 g glucose PO')
,('http://loinc.org', '49689-3', 'Glucose tolerance [Interpretation] in Serum or Plasma Narrative--post 100 g glucose PO')
,('http://loinc.org', '50667-5', 'Glucose tolerance [Interpretation] in Serum or Plasma Narrative')
,('http://loinc.org', '53049-3', 'Glucose [Mass/volume] in Serum or Plasma --pre-meal')
,('http://loinc.org', '6689-4', 'Glucose [Mass/volume] in Blood --2 hours post meal')
,('http://loinc.org', '74774-1', 'Glucose [Mass/volume] in Serum, Plasma or Blood')
,('http://loinc.org', '80959-0', 'Glucose [Mass/volume] in Serum or Plasma --1.5 hours post meal')
,('http://www.ama-assn.org/go/cpt', '83036', 'Hemoglobin. glycosylated (A1C)')
,('http://www.ama-assn.org/go/cpt', '83037', 'Hemoglobin. glycosylated (A1C) by device cleared by FDA for home use')
,('http://loinc.org', '87422-2', 'Glucose [Mass/volume] in Blood --post meal')
,('http://loinc.org', '88365-2', 'Glucose [Mass/volume] in Blood --pre-meal')
,('http://loinc.org', '93791-2', 'Glucose [Mass/volume] mean in Serum or Plasma')
,('http://loinc.org', '99504-3', 'Glucose [Mass/volume] in Interstitial fluid')
,('http://loinc.org', 'LP19482-6', 'Glucose tolerance')
,('http://loinc.org', 'LP387198-7', 'Glucose tolerance | Serum or Plasma | Chemistry - challenge')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z13.1', 'Encounter for screening for diabetes mellitus')
) AS t (system, code, display) ;