create or replace view irae__dx_kidney_ckd as select * from (values
('http://snomed.info/sct', '104931000119100', 'Chronic kidney disease due to hypertension (disorder)')
,('http://snomed.info/sct', '10757401000119104', 'Pre-existing hypertensive heart and chronic kidney disease in mother complicating childbirth (disorder)')
,('http://snomed.info/sct', '10757481000119107', 'Pre-existing hypertensive heart and chronic kidney disease in mother complicating pregnancy (disorder)')
,('http://snomed.info/sct', '117681000119102', 'Chronic kidney disease stage 1 due to hypertension (disorder)')
,('http://snomed.info/sct', '118781000119108', 'Pre-existing hypertensive chronic kidney disease in mother complicating pregnancy (disorder)')
,('http://snomed.info/sct', '120261000119101', 'Benign hypertensive heart disease and chronic renal disease stage 5 (disorder)')
,('http://snomed.info/sct', '129151000119102', 'Chronic kidney disease stage 4 due to hypertension (disorder)')
,('http://snomed.info/sct', '129161000119100', 'Chronic kidney disease stage 5 due to hypertension (disorder)')
,('http://snomed.info/sct', '129171000119106', 'Chronic kidney disease stage 3 due to hypertension (disorder)')
,('http://snomed.info/sct', '129181000119109', 'Chronic kidney disease stage 2 due to hypertension (disorder)')
,('http://snomed.info/sct', '140101000119109', 'Hypertension in chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140111000119107', 'Hypertension in chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140121000119100', 'Hypertension in chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140131000119102', 'Hypertension in chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '153851000119106', 'Malignant hypertensive chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '1801000119106', 'Anemia, pre-end stage renal disease on erythropoietin protocol (disorder)')
,('http://snomed.info/sct', '20917003', 'Chronic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236433006', 'Acute-on-chronic renal failure (disorder)')
,('http://snomed.info/sct', '284961000119106', 'Chronic kidney disease due to benign hypertension (disorder)')
,('http://snomed.info/sct', '284971000119100', 'Chronic kidney disease stage 1 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '284981000119102', 'Chronic kidney disease stage 2 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '284991000119104', 'Chronic kidney disease stage 3 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '285001000119105', 'Chronic kidney disease stage 4 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '285011000119108', 'Chronic kidney disease stage 5 due to benign hypertension (disorder)')
,('http://snomed.info/sct', '285041000119107', 'Benign hypertensive heart disease and chronic renal disease stage 1 (disorder)')
,('http://snomed.info/sct', '285061000119106', 'Benign hypertensive heart disease and chronic renal disease stage 2 (disorder)')
,('http://snomed.info/sct', '285081000119102', 'Benign hypertensive heart disease and chronic renal disease stage 3 (disorder)')
,('http://snomed.info/sct', '285101000119109', 'Benign hypertensive heart disease and chronic renal disease stage 4 (disorder)')
,('http://snomed.info/sct', '285831000119108', 'Malignant hypertensive chronic kidney disease (disorder)')
,('http://snomed.info/sct', '285851000119102', 'Malignant hypertensive chronic kidney disease stage 1 (disorder)')
,('http://snomed.info/sct', '285861000119100', 'Malignant hypertensive chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '285871000119106', 'Malignant hypertensive chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '285881000119109', 'Malignant hypertensive chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '285911000119109', 'Malignant hypertensive heart disease and chronic renal disease stage 3 (disorder)')
,('http://snomed.info/sct', '285921000119102', 'Malignant hypertensive heart disease and chronic renal disease stage 4 (disorder)')
,('http://snomed.info/sct', '368421000119108', 'Chronic kidney disease stage 1 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368431000119106', 'Chronic kidney disease stage 2 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368441000119102', 'Chronic kidney disease stage 3 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368451000119100', 'Chronic kidney disease stage 4 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368461000119103', 'Chronic kidney disease stage 5 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '425369003', 'Chronic progressive renal failure (disorder)')
,('http://snomed.info/sct', '431855005', 'Chronic kidney disease stage 1 (disorder)')
,('http://snomed.info/sct', '431856006', 'Chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '431857002', 'Chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '433144002', 'Chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '433146000', 'Chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '449631000124102', 'Benign hypertensive heart disease and chronic renal disease (disorder)')
,('http://snomed.info/sct', '49708008', 'Anemia of chronic renal failure (disorder)')
,('http://snomed.info/sct', '57557005', 'Chronic milk alkali syndrome (disorder)')
,('http://snomed.info/sct', '691421000119108', 'Anemia co-occurrent and due to chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '700378005', 'Chronic kidney disease stage 3A (disorder)')
,('http://snomed.info/sct', '700379002', 'Chronic kidney disease stage 3B (disorder)')
,('http://snomed.info/sct', '709044004', 'Chronic kidney disease (disorder)')
,('http://snomed.info/sct', '711000119100', 'Chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713313000', 'Chronic kidney disease mineral and bone disorder (disorder)')
,('http://snomed.info/sct', '714152005', 'Chronic kidney disease stage 5 on dialysis (disorder)')
,('http://snomed.info/sct', '714153000', 'Chronic kidney disease stage 5 with transplant (disorder)')
,('http://snomed.info/sct', '71421000119105', 'Hypertension in chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71701000119105', 'Hypertension in chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '721000119107', 'Chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '722098007', 'Chronic kidney disease following donor nephrectomy (disorder)')
,('http://snomed.info/sct', '722149000', 'Chronic kidney disease due to and following excision of neoplasm of kidney (disorder)')
,('http://snomed.info/sct', '722150000', 'Chronic kidney disease due to systemic infection (disorder)')
,('http://snomed.info/sct', '722467000', 'Chronic kidney disease due to traumatic loss of kidney (disorder)')
,('http://snomed.info/sct', '723190009', 'Chronic renal insufficiency (disorder)')
,('http://snomed.info/sct', '731000119105', 'Chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '741000119101', 'Chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '751000119104', 'Chronic kidney disease stage 1 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '771000119108', 'Chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '776416004', 'Hyperuricemia, pulmonary hypertension, renal failure, alkalosis syndrome (disorder)')
,('http://snomed.info/sct', '8501000119104', 'Hypertensive heart and chronic kidney disease (disorder)')
,('http://snomed.info/sct', '90688005', 'Chronic renal failure syndrome (disorder)')
,('http://snomed.info/sct', '90721000119101', 'Chronic kidney disease stage 1 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90731000119103', 'Chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90741000119107', 'Chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90751000119109', 'Chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90761000119106', 'Chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90771000119100', 'End stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90791000119104', 'End stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '96701000119107', 'Hypertensive heart AND chronic kidney disease on dialysis (disorder)')
,('http://snomed.info/sct', '96711000119105', 'Hypertensive heart AND chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '96721000119103', 'Hypertensive heart AND chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '96731000119100', 'Hypertensive heart AND chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '96741000119109', 'Hypertensive heart AND chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '96751000119106', 'Hypertensive heart AND chronic kidney disease stage 1 (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A02.25', 'Salmonella pyelonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A36.84', 'Diphtheritic tubulo-interstitial nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'B58.83', 'Toxoplasma tubulo-interstitial nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D63.1', 'Anemia in chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D86.84', 'Sarcoid pyelonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.21', 'Diabetes mellitus due to underlying condition with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.22', 'Diabetes mellitus due to underlying condition with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.29', 'Diabetes mellitus due to underlying condition with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.2', 'Drug or chemical induced diabetes mellitus with kidney complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.21', 'Drug or chemical induced diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.22', 'Drug or chemical induced diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.29', 'Drug or chemical induced diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.21', 'Type 1 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.22', 'Type 1 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.29', 'Type 1 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.21', 'Type 2 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.22', 'Type 2 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.29', 'Type 2 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.21', 'Other specified diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.22', 'Other specified diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12', 'Hypertensive chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.0', 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.9', 'Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13', 'Hypertensive heart and chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.0', 'Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.1', 'Hypertensive heart and chronic kidney disease without heart failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.10', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.11', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.2', 'Hypertensive heart and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.15', 'Tubulo-interstitial nephropathy in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.04', 'Sjögren syndrome with tubulo-interstitial nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.9', 'Chronic nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04', 'Nephrotic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.0', 'Nephrotic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.1', 'Nephrotic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.2', 'Nephrotic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.20', 'Nephrotic syndrome with diffuse membranous glomerulonephritis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.21', 'Primary membranous nephropathy with nephrotic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.22', 'Secondary membranous nephropathy with nephrotic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.29', 'Other nephrotic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.3', 'Nephrotic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.4', 'Nephrotic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.5', 'Nephrotic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.6', 'Nephrotic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.7', 'Nephrotic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.8', 'Nephrotic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.9', 'Nephrotic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.A', 'Nephrotic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05', 'Unspecified nephritic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.2', 'Unspecified nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.6', 'Unspecified nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.8', 'Unspecified nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07', 'Hereditary nephropathy, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.0', 'Hereditary nephropathy, not elsewhere classified with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.1', 'Hereditary nephropathy, not elsewhere classified with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.2', 'Hereditary nephropathy, not elsewhere classified with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.3', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.4', 'Hereditary nephropathy, not elsewhere classified with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.5', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.6', 'Hereditary nephropathy, not elsewhere classified with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.7', 'Hereditary nephropathy, not elsewhere classified with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.8', 'Hereditary nephropathy, not elsewhere classified with other morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.9', 'Hereditary nephropathy, not elsewhere classified with unspecified morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.A', 'Hereditary nephropathy, not elsewhere classified with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.71', 'Vesicoureteral-reflux without reflux nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.72', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.721', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter, unilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.722', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.729', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.73', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.731', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter, unilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.732', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.739', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.0', 'Analgesic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.1', 'Nephropathy induced by other drugs, medicaments and biological substances')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.2', 'Nephropathy induced by unspecified drug, medicament or biological substance')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.3', 'Nephropathy induced by heavy metals')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.4', 'Toxic nephropathy, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N15.0', 'Balkan nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18', 'Chronic kidney disease (CKD)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.1', 'Chronic kidney disease, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.2', 'Chronic kidney disease, stage 2 (mild)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.3', 'Chronic kidney disease, stage 3 (moderate)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.30', 'Chronic kidney disease, stage 3 unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.31', 'Chronic kidney disease, stage 3a')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.32', 'Chronic kidney disease, stage 3b')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.4', 'Chronic kidney disease, stage 4 (severe)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.5', 'Chronic kidney disease, stage 5')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.6', 'End stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.9', 'Chronic kidney disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.89', 'Other disorders resulting from impaired renal tubular function')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.21', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.211', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, first trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.212', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, second trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.213', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, third trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.219', 'Pre-existing hypertensive chronic kidney disease complicating pregnancy, unspecified trimester')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.22', 'Pre-existing hypertensive chronic kidney disease complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.23', 'Pre-existing hypertensive chronic kidney disease complicating the puerperium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.31', 'Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.32', 'Pre-existing hypertensive heart and chronic kidney disease complicating childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O10.33', 'Pre-existing hypertensive heart and chronic kidney disease complicating the puerperium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z87.441', 'Personal history of nephrotic syndrome')
) AS t (system, code, display) ;