create or replace view irae__rx_immunosuppressive_drugs as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '105585', 'methotrexate 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105586', 'methotrexate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105611', 'azathioprine 50 MG Oral Tablet [Imuran]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '107047', 'rabbit anti-human T-lymphocyte globulin 25 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '107050', 'rabbit anti-human T-lymphocyte globulin 25 MG Injection [Thymoglobulin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108513', 'tacrolimus 1 MG Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108514', 'tacrolimus 5 MG Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108515', '1 ML tacrolimus 5 MG/ML Injection [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1112976', 'belatacept 250 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1112980', 'belatacept 250 MG Injection [Nulojix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119400', 'everolimus 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119402', 'everolimus 7.5 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1308428', 'everolimus 2 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1308430', 'everolimus 3 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1308432', 'everolimus 5 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310138', 'everolimus 2 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310144', 'everolimus 3 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310147', 'everolimus 5 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431971', '24 HR tacrolimus 0.5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431977', '24 HR tacrolimus 0.5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431980', '24 HR tacrolimus 1 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431982', '24 HR tacrolimus 1 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431985', '24 HR tacrolimus 5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431987', '24 HR tacrolimus 5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664434', '24 HR tacrolimus 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664440', '24 HR tacrolimus 4 MG Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664456', '24 HR tacrolimus 0.75 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664458', '24 HR tacrolimus 0.75 MG Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664461', '24 HR tacrolimus 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664463', '24 HR tacrolimus 1 MG Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197388', 'azathioprine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197906', '5 ML lymphocyte immune globulin, anti-thymocyte globulin, equine 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198377', 'tacrolimus 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198378', 'tacrolimus 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198379', '1 ML tacrolimus 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199058', 'mycophenolate mofetil 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199310', 'azathioprine 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200060', 'mycophenolate mofetil 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056895', 'everolimus 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056897', 'everolimus 1 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '206289', '5 ML lymphocyte immune globulin, anti-thymocyte globulin, equine 50 MG/ML Injection [ATGAM]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239983', 'azathioprine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261134', 'tacrolimus 0.5 MG Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283510', 'methotrexate 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283511', 'methotrexate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283671', 'methotrexate 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284592', 'methotrexate 5 MG Oral Tablet [Trexall]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284593', 'methotrexate 10 MG Oral Tablet [Trexall]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284594', 'methotrexate 7.5 MG Oral Tablet [Trexall]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284595', 'methotrexate 15 MG Oral Tablet [Trexall]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311880', 'mycophenolate mofetil 200 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313190', 'tacrolimus 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314230', 'sirolimus 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349208', 'sirolimus 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351901', 'sirolimus 1 MG/ML Oral Solution [Rapamune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351989', 'sirolimus 1 MG Oral Tablet [Rapamune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359228', 'azathioprine 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359229', 'azathioprine 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360110', 'sirolimus 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404432', 'sirolimus 2 MG Oral Tablet [Rapamune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404475', 'azathioprine 75 MG Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404476', 'azathioprine 100 MG Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485020', 'mycophenolic acid 180 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485023', 'mycophenolic acid 360 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616435', 'mycophenolate mofetil 500 MG Oral Tablet [Cellcept]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616444', 'mycophenolate mofetil 200 MG/ML Oral Suspension [Cellcept]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616447', 'mycophenolate mofetil 250 MG Oral Capsule [Cellcept]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616449', 'mycophenolic acid 360 MG Delayed Release Oral Tablet [Myfortic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '616450', 'mycophenolic acid 180 MG Delayed Release Oral Tablet [Myfortic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845507', 'everolimus 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845512', 'everolimus 10 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845515', 'everolimus 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845518', 'everolimus 5 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905158', 'sirolimus 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '905160', 'sirolimus 0.5 MG Oral Tablet [Rapamune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977427', 'everolimus 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977431', 'everolimus 0.25 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977434', 'everolimus 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977436', 'everolimus 0.5 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977438', 'everolimus 0.75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977440', 'everolimus 0.75 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998189', 'everolimus 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998191', 'everolimus 2.5 MG Oral Tablet [Afinitor]')
) AS t (system, code, display) ;