create or replace view irae__lab_tacrolimus as select * from (values
('http://loinc.org', 'LOINC_NUM', 'COMPONENT')
,('http://loinc.org', '32594-4', 'Tacrolimus')
,('http://loinc.org', '92727-7', 'Tacrolimus')
,('http://loinc.org', '11253-2', 'Tacrolimus')
,('http://loinc.org', '80550-7', 'Tacrolimus')
,('http://loinc.org', '32721-3', 'Tacrolimus')
,('http://loinc.org', '77348-1', 'Tacrolimus^trough')
,('http://loinc.org', '74096-9', 'Tacrolimus')
,('http://loinc.org', '74097-7', 'Tacrolimus')
,('http://loinc.org', '76494-4', 'Tacrolimus')
,('http://loinc.org', '92728-5', 'Tacrolimus^4H post dose')
,('http://loinc.org', '33929-1', 'Tacrolimus^trough')
,('http://loinc.org', '92729-3', 'Tacrolimus^2H post dose')
,('http://loinc.org', '59822-7', 'Tacrolimus^4H post dose')
,('http://loinc.org', '92730-1', 'Tacrolimus^1H post dose')
,('http://loinc.org', '59823-5', 'Tacrolimus^2H post dose')
,('http://loinc.org', '72946-7', 'Tacrolimus induced neutrophil Ab.IgG')
,('http://loinc.org', '72945-9', 'Tacrolimus induced neutrophil Ab.IgM')
,('http://loinc.org', '73133-1', 'Tacrolimus induced platelet Ab.IgG')
,('http://loinc.org', '73132-3', 'Tacrolimus induced platelet Ab.IgM')
) AS t (system, code, display) ;