create or replace view irae__dx_diabetes_complications as select * from (values
('http://snomed.info/sct', '1003605004', 'Glaucoma suspect due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '102621000119101', 'Ulcer of skin due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '102781000119107', 'Sensory neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '103981000119101', 'Proliferative retinopathy following surgery due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '104941000119109', 'Ischemia of retina due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '104951000119106', 'Vitreous hemorrhage due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '104961000119108', 'Ischemia of retina due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '10656231000119100', 'Ulcer of skin of toe due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '10656271000119102', 'Ulcer of skin of toe due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '10660471000119109', 'Ulcer of left foot due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '10661671000119102', 'Ulcer of right foot due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '109171000119104', 'Retinal edema due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '110141000119100', 'Ulcer of lower limb due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '110171000119107', 'Ulcer of lower limb due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '110181000119105', 'Peripheral sensory neuropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '111231000119109', 'Dyslipidemia with high density lipoprotein below reference range and triglyceride above reference range due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '111556005', 'Ketoacidosis without coma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1144894004', 'Peripheral autonomic neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1172389004', 'Disorder due to malnutrition related diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1196922005', 'Neovascular glaucoma due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '1196923000', 'Neovascular glaucoma due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '119831000119106', 'Hypoglycemia unawareness due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '120711000119108', 'Hypoglycemic unawareness due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '120731000119103', 'Hypoglycemia due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1217674007', 'Neurotrophic keratitis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1251386008', 'Disorder of skin due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1259048007', 'Lesion of brachial plexus due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '126531000119109', 'Peripheral vascular disease due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '126534007', 'Mixed sensorimotor polyneuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '126535008', 'Motor polyneuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '126551000119103', 'Nephropathy due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '126571000119107', 'Polyneuropathy due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '126591000119108', 'Retinopathy due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '127011001', 'Sensory neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '127013003', 'Disorder of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '127014009', 'Peripheral angiopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '127991000119101', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '128001000119105', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '129599004', 'Large baby of diabetic mother (disorder)')
,('http://snomed.info/sct', '1306699009', 'Stable treated proliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1306700005', 'Stable treated proliferative retinopathy of bilateral eyes due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332436006', 'Hypertension in chronic kidney disease stage 3B due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332441003', 'Hypertension in chronic kidney disease stage 3A due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332442005', 'Hypertension in chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332464001', 'Hypertension in chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332465000', 'Hypertension in chronic kidney disease stage 3B due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332466004', 'Hypertension in chronic kidney disease stage 3A due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332467008', 'Hypertension in chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332468003', 'Hypertension in chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332469006', 'Chronic kidney disease stage 3B due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332470007', 'Chronic kidney disease stage 3A due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332471006', 'Chronic kidney disease stage 3B due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332472004', 'Chronic kidney disease stage 3A due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '137931000119102', 'Hyperlipidemia due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '137941000119106', 'Hyperlipidemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138591000119106', 'Disorder of vision due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138611000119101', 'Hyperosmolarity due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138621000119108', 'Ketoacidosis due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138811000119100', 'Complication due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138881000119106', 'Mild nonproliferative retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138891000119109', 'Moderate nonproliferative retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138901000119108', 'Severe nonproliferative retinopathy due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '138911000119106', 'Mild nonproliferative retinopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138921000119104', 'Moderate nonproliferative retinopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138941000119105', 'Severe nonproliferative retinopathy due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '140101000119109', 'Hypertension in chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140111000119107', 'Hypertension in chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140121000119100', 'Hypertension in chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140131000119102', 'Hypertension in chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140381000119104', 'Neuropathic ulcer of toe due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140391000119101', 'Ulcer of toe due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140411000119101', 'Ischemic ankle ulcer due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '140421000119108', 'Neuropathic ankle ulcer due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '140521000119107', 'Ischemic ulcer of foot due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140531000119105', 'Neuropathic ulcer of foot due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1491000119102', 'Vitreous hemorrhage due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1501000119109', 'Proliferative retinopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1511000119107', 'Peripheral neuropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1521000119100', 'Ulcer of foot due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1531000119102', 'Dermopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1551000119108', 'Nonproliferative retinopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1571000119104', 'Mixed hyperlipidemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '157141000119108', 'Proteinuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '15936501000119100', 'Inflammatory dermatosis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '164881000119109', 'Ulcer of foot due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '16697421000119103', 'Moderate nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16697471000119102', 'Moderate nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16697521000119104', 'Moderate nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745051000119107', 'Nonproliferative retinopathy of right eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16745131000119100', 'Nonproliferative retinopathy of left eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16745211000119100', 'Nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745411000119104', 'Mild nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745531000119108', 'Mild nonproliferative retinopathy of left eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16745611000119102', 'Mild nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745651000119101', 'Mild nonproliferative retinopathy of right eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16745891000119105', 'Mild nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745931000119102', 'Mild nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16746131000119105', 'Moderate nonproliferative retinopathy of left eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16746261000119108', 'Moderate nonproliferative retinopathy of right eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16746341000119103', 'Moderate nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16746661000119106', 'Nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16746741000119102', 'Nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16746901000119101', 'Severe nonproliferative retinopathy of left eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16746941000119104', 'Severe nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16747021000119109', 'Severe nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16747101000119101', 'Severe nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16747141000119104', 'Severe nonproliferative retinopathy of right eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16747341000119101', 'Severe nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16747661000119109', 'Nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16747741000119100', 'Proliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16747901000119104', 'Proliferative retinopathy of left eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16748141000119100', 'Proliferative retinopathy of bilateral eyes due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16748741000119101', 'Proliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16749661000119102', 'Proliferative retinopathy of right eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '16749781000119101', 'Proliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16891151000119103', 'Coronary artery disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '16891191000119108', 'Coronary artery disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '170766006', 'Loss of hypoglycemic warning due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '18521000119106', 'Microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '190330002', 'Hyperosmolar coma due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '190331003', 'Hyperosmolar coma due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '190406000', 'Ketoacidosis due to malnutrition related diabetes mellitus (disorder)')
,('http://snomed.info/sct', '193141005', 'Mononeuritis multiplex due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '193183000', 'Acute painful neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '193184006', 'Chronic painful neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '193185007', 'Asymptomatic neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '193349004', 'Preproliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '193350004', 'Advanced maculopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '193489006', 'Iritis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '19378003', 'Pseudotabes due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '197605007', 'Nephrotic syndrome due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '200687002', 'Cellulitis of foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '201000119106', 'Disorder due to well controlled type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '201250006', 'Ischemic ulcer of foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '201251005', 'Neuropathic ulcer of foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '201252003', 'Mixed diabetic ulcer - foot (disorder)')
,('http://snomed.info/sct', '201723002', 'Cheiroarthropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '201724008', 'Neuropathic arthropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '21584002', 'Syndrome of infant of diabetic mother (disorder)')
,('http://snomed.info/sct', '217341008', 'Xanthoma diabeticorum (disorder)')
,('http://snomed.info/sct', '230572002', 'Neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '230574001', 'Acute painful polyneuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '230575000', 'Chronic painful polyneuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '230576004', 'Asymmetric polyneuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '230577008', 'Mononeuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '230579006', 'Thoracic radiculopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '232020009', 'Disorder of macula due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '232021008', 'Proliferative retinopathy with optic disc neovascularization due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '232022001', 'Proliferative retinopathy with neovascularization elsewhere than the optic disc due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '232023006', 'Traction detachment of retina due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '236499007', 'Microalbuminuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '236500003', 'Proteinuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '237620003', 'Abnormal metabolic state due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '237621004', 'Severe hyperglycemia due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '237632004', 'Hypoglycemic event due to diabetes (disorder)')
,('http://snomed.info/sct', '237633009', 'Hypoglycemia due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '237635002', 'Nocturnal hypoglycemia due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '238981002', 'Disorder of soft tissue due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '238982009', 'Dermopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '238983004', 'Thick skin syndrome due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '238984005', 'Rubeosis faciei due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '243421000119104', 'Proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '25093002', 'Disorder of eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '25412000', 'Microaneurysm of retinal artery due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '26298008', 'Ketoacidotic coma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '267604001', 'Myasthenic syndrome due to diabetic mellitus (disorder)')
,('http://snomed.info/sct', '280137006', 'Diabetic foot (disorder)')
,('http://snomed.info/sct', '28331000119107', 'Retinal edema due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '309426007', 'Glomerulopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '310387003', 'Intracapillary glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '310505005', 'Hyperosmolar non-ketotic state due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '311366001', 'Kimmelstiel-Wilson syndrome (disorder)')
,('http://snomed.info/sct', '311782002', 'Advanced retinal disease due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '31211000119101', 'Peripheral angiopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312903003', 'Mild nonproliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312904009', 'Moderate nonproliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312905005', 'Severe nonproliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312906006', 'Non-high-risk proliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312907002', 'High risk proliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312908007', 'Quiescent proliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312909004', 'Proliferative retinopathy with iris neovascularization due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312910009', 'Vitreous hemorrhage due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '312912001', 'Macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314010006', 'Diffuse exudative maculopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314011005', 'Focal exudative maculopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314014002', 'Ischemic maculopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314015001', 'Mixed maculopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314537004', 'Optic papillopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314893005', 'Arthropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314902007', 'Peripheral angiopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '314903002', 'Arthropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '35777006', 'Mononeuropathy multiplex due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '359611005', 'Neuropathy with neurologic complication due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '361216007', 'Femoral mononeuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '367211000119103', 'Inflammatory dermatosis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '367241000119104', 'Hyperosmolar coma due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '367261000119100', 'Hyperosmolarity due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '367991000119101', 'Hyperglycemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368051000119109', 'Hyperglycemia due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368101000119109', 'Periodontal disease co-occurrent and due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '368141000119106', 'Autonomic neuropathy due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368151000119108', 'Cataract due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368171000119104', 'Dermatitis due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368181000119101', 'Ulcer of foot due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368201000119100', 'Disorder of kidney due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368251000119101', 'Polyneuropathy due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368421000119108', 'Chronic kidney disease stage 1 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368431000119106', 'Chronic kidney disease stage 2 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368441000119102', 'Chronic kidney disease stage 3 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368451000119100', 'Chronic kidney disease stage 4 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368461000119103', 'Chronic kidney disease stage 5 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368471000119109', 'End stage renal disease on dialysis due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368521000119107', 'Disorder of nerve co-occurrent and due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368541000119101', 'Cheiroarthropathy due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '368551000119104', 'Dyslipidemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368561000119102', 'Hyperosmolarity due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368581000119106', 'Neuropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368591000119109', 'Cheiroarthropathy due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '368601000119102', 'Hyperosmolar coma due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368711000119106', 'Mild nonproliferative retinopathy due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368721000119104', 'Non-proliferative retinopathy due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368741000119105', 'Moderate non-proliferative retinopathy due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '371087003', 'Ulcer of foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '38046004', 'Diffuse glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '38205001', 'Diarrhea due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '39058009', 'Lumbosacral radiculoplexus neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '390834004', 'Nonproliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '39127005', 'Symmetric proximal motor neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '39181008', 'Radiculoplexus neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '395204000', 'Hyperosmolar non-ketotic state due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '398140007', 'Post hypoglycemic hyperglycemia due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399862001', 'High risk proliferative retinopathy without macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399863006', 'Very severe nonproliferative retinopathy without macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399864000', 'Macular edema not clinically significant due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399865004', 'Very severe proliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399866003', 'Venous beading of retina due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399868002', 'Intraretinal microvascular anomaly due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399869005', 'High risk proliferative retinopathy not amenable to photocoagulation due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399870006', 'Non-high-risk proliferative retinopathy with no macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399871005', 'Visually threatening retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399872003', 'Severe nonproliferative retinopathy with clinically significant macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399873008', 'Severe nonproliferative retinopathy without macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399874002', 'High risk proliferative retinopathy with clinically significant macula edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399875001', 'Non-high-risk proliferative retinopathy with clinically significant macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399876000', 'Very severe nonproliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '399877009', 'Very severe nonproliferative retinopathy with clinically significant macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '402864004', 'Wet gangrene of foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '419100001', 'Infection of foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '41911000119107', 'Glaucoma due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420270002', 'Ketoacidosis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420279001', 'Renal disorder due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420422005', 'Ketoacidosis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420436000', 'Mononeuropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420486006', 'Exudative maculopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420514000', 'Persistent proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420662003', 'Coma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420683009', 'Disorder of nervous system due to malnutrition related diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420715001', 'Persistent microalbuminuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420756003', 'Cataract of eye due to diabetes mellitus type 2 (disorder)')
,('http://snomed.info/sct', '420789003', 'Retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420825003', 'Gangrene due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420868002', 'Disorder due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420918009', 'Mononeuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420996007', 'Coma due to malnutrition-related diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421075007', 'Ketoacidotic coma due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421256007', 'Disorder of eye due to malnutrition related diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421305000', 'Persistent microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421326000', 'Disorder of nervous system due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421365002', 'Peripheral circulatory disorder due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421437000', 'Hypoglycemic coma due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421468001', 'Disorder of nervous system due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421631007', 'Gangrene due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421725003', 'Hypoglycemic coma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421750000', 'Ketoacidosis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421779007', 'Exudative maculopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421847006', 'Ketoacidotic coma due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421893009', 'Renal disorder due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421895002', 'Peripheral vascular disorder due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421920002', 'Cataract of eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '421966007', 'Non-ketotic non-hyperosmolar coma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421986006', 'Persistent proteinuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422014003', 'Disorder due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422034002', 'Retinopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422088007', 'Disorder of nervous system due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422099009', 'Disorder of eye due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422126006', 'Hyperosmolar coma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422166005', 'Peripheral circulatory disorder due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422183001', 'Skin ulcer due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '422275004', 'Gangrene due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '424736006', 'Peripheral neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '425455002', 'Glomerulonephritis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '426907004', 'Small vessel disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '427027005', 'Lumbosacral radiculoplexus neuropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '427134009', 'Small vessel disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '427571000', 'Lumbosacral radiculoplexus neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '427943001', 'Ophthalmoplegia due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '428007007', 'Erectile dysfunction due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '428896009', 'Hyperosmolality due to uncontrolled type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '43959009', 'Cataract of eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '441656006', 'Hyperglycemic crisis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '445170001', 'Macroalbuminuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '4855003', 'Retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '48951005', 'Bullous disease due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '49455004', 'Polyneuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '50620007', 'Autonomic neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '56391002', 'Necrobiosis lipoidica diabeticorum (disorder)')
,('http://snomed.info/sct', '59276001', 'Proliferative retinopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '60951000119105', 'Blindness due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '60961000119107', 'Nonproliferative diabetic retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '60971000119101', 'Proliferative retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '60981000119103', 'Glaucoma due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '60991000119100', 'Blindness due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '62260007', 'Pretibial pigmental patches due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '63510008', 'Nodular glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '691000119103', 'Erectile dysfunction due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '701000119103', 'Mixed hyperlipidemia due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '704241002', 'Fetal hypertrophic cardiomyopathy due to maternal diabetes mellitus (disorder)')
,('http://snomed.info/sct', '706891008', 'Neuropathy due to unstable diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '706894000', 'Retinopathy due to unstable diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '707221002', 'Glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '711000119100', 'Chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '712882000', 'Autonomic neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '712883005', 'Autonomic neuropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713457002', 'Neovascular glaucoma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713702000', 'Gastroparesis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713703005', 'Gastroparesis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713704004', 'Gastroparesis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713705003', 'Polyneuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713706002', 'Polyneuropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71421000119105', 'Hypertension in chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71441000119104', 'Nephrotic syndrome due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '716020005', 'Diabetic embryopathy (disorder)')
,('http://snomed.info/sct', '71701000119105', 'Hypertension in chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71721000119101', 'Nephrotic syndrome due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71771000119100', 'Neuropathic arthropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71791000119104', 'Peripheral neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '719216001', 'Hypoglycemic coma due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72021000119109', 'Dermopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72031000119107', 'Severe malnutrition due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72041000119103', 'Osteomyelitis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72051000119101', 'Severe malnutrition due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72061000119104', 'Osteomyelitis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '721000119107', 'Chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '721283000', 'Acidosis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '721284006', 'Acidosis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72141000119104', 'Chronic ulcer of skin due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '723074006', 'Renal papillary necrosis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '724136006', 'Mastopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '724876003', 'Lesion of skin due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '731000119105', 'Chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '735200002', 'Absence of lower limb due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '735537007', 'Hyperosmolar hyperglycemic coma due to diabetes mellitus without ketoacidosis (disorder)')
,('http://snomed.info/sct', '735538002', 'Lactic acidosis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '735539005', 'Metabolic acidosis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '739681000', 'Disorder of eye due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '741000119101', 'Chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '74627003', 'Complication due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '751000119104', 'Chronic kidney disease stage 1 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '75682002', 'Diabetes mellitus caused by insulin receptor antibodies (disorder)')
,('http://snomed.info/sct', '761000119102', 'Dyslipidemia due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '762291006', 'Syndrome of infant of mother with gestational diabetes (disorder)')
,('http://snomed.info/sct', '762489000', 'Acute complication due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '768792007', 'Cataract of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '768793002', 'Cataract of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '768794008', 'Cataract of bilateral eyes due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '768797001', 'Iritis of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '768798006', 'Iritis of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '768799003', 'Iritis of bilateral eyes due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769181007', 'Preproliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769182000', 'Preproliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769183005', 'Mild nonproliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769184004', 'Mild nonproliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769185003', 'Moderate nonproliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769186002', 'Moderate nonproliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769187006', 'Severe nonproliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769188001', 'Severe nonproliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769190000', 'Very severe nonproliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769191001', 'Very severe nonproliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769217008', 'Macular edema of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769218003', 'Macular edema of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769219006', 'Macular edema due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769220000', 'Macular edema due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769221001', 'Clinically significant macular edema of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769222008', 'Clinically significant macular edema of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769244003', 'Disorder of right macula due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769245002', 'Disorder of left macula due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770094004', 'Cervical radiculoplexus neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770095003', 'Cranial nerve palsy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770096002', 'Erectile dysfunction due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770097006', 'Clinically significant macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770098001', 'Cranial nerve palsy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770323005', 'Retinal edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770324004', 'Ischemia of retina due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770361008', 'Vitreous hemorrhage of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770362001', 'Vitreous hemorrhage of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770581008', 'Microaneurysm of right retinal artery due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770582001', 'Microaneurysm of left retinal artery due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770599000', 'Venous beading of right retina due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770600002', 'Venous beading of left retina due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770765001', 'Proliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770766000', 'Proliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '771000119108', 'Chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '781000119106', 'Neuropathic arthropathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '788878000', 'Cardiomyopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789542009', 'Neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789562001', 'Ulcer of heel due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789567007', 'Ulcer of heel due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789568002', 'Ulcer of midfoot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789569005', 'Neuropathic ulcer of heel due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789570006', 'Neuropathic ulcer of midfoot due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789571005', 'Ulcer of heel due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789572003', 'Ulcer of midfoot due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789585000', 'Sensory polyneuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '791000119109', 'Angina due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '792926007', 'Armanni-Ebstein kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '79554005', 'Asymmetric proximal motor neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '816177009', 'Nonproliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '816178004', 'Nonproliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '816961009', 'Stable treated proliferative retinopathy of right eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '816962002', 'Stable treated proliferative retinopathy of left eye due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '81830002', 'Mononeuropathy simplex due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '822995009', 'Hyperglycemia due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '82541000119100', 'Traction detachment of retina due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '82551000119103', 'Rubeosis iridis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '82571000119107', 'Traction detachment of retina due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '82581000119105', 'Rubeosis iridis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '82980005', 'Anemia due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '84361000119102', 'Insulin reactive hypoglycemia due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '84371000119108', 'Hypoglycemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '860721006', 'Disorder of macula of bilateral eyes due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '860798008', 'Glaucoma due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '860883001', 'Generalized autonomic neuropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '860977000', 'Ulcer of right foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '860978005', 'Ulcer of left foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '860979002', 'Chronic ulcer of right foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '860980004', 'Chronic ulcer of left foot due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '870420005', 'Severe nonproliferative retinopathy with venous beading of retina due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '870421009', 'Cystoid macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '870529009', 'Persistent macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '871778008', 'Centrally involved macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '871781003', 'Non centrally involved macular edema due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '87441000119104', 'Ulcer of ankle due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '87461000119100', 'Ulcer of forefoot due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '87471000119106', 'Ulcer of ankle due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '87491000119107', 'Ulcer of forefoot due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '87921000119104', 'Cranial nerve palsy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90721000119101', 'Chronic kidney disease stage 1 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90731000119103', 'Chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90741000119107', 'Chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90751000119109', 'Chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90761000119106', 'Chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90771000119100', 'End stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90781000119102', 'Microalbuminuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90791000119104', 'End stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '96441000119101', 'Chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '97331000119101', 'Macular edema and retinopathy due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '97341000119105', 'Proliferative retinopathy with retinal edema due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '97621000119107', 'Stasis ulcer due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '9859006', 'Acanthosis nigricans due to type 2 diabetes mellitus (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.1', 'Type 1 diabetes mellitus with ketoacidosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.10', 'Type 1 diabetes mellitus with ketoacidosis without coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.11', 'Type 1 diabetes mellitus with ketoacidosis with coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.2', 'Type 1 diabetes mellitus with kidney complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.21', 'Type 1 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.22', 'Type 1 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.29', 'Type 1 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3', 'Type 1 diabetes mellitus with ophthalmic complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.31', 'Type 1 diabetes mellitus with unspecified diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.311', 'Type 1 diabetes mellitus with unspecified diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.319', 'Type 1 diabetes mellitus with unspecified diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.32', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.321', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3211', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3212', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3213', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3219', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.329', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3291', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3292', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3293', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3299', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.33', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.331', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3311', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3312', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3313', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3319', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.339', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3391', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3392', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3393', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3399', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.34', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.341', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3411', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3412', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3413', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3419', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.349', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3491', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3492', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3493', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3499', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.35', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.351', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3511', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3512', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3513', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3519', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.352', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3521', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3522', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3523', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3529', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.353', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3531', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3532', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3533', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3539', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.354', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3541', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3542', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3543', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3549', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.355', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3551', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3552', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3553', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3559', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.359', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3591', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3592', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3593', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3599', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.36', 'Type 1 diabetes mellitus with diabetic cataract')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X1', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X2', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X3', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X9', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.39', 'Type 1 diabetes mellitus with other diabetic ophthalmic complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.4', 'Type 1 diabetes mellitus with neurological complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.40', 'Type 1 diabetes mellitus with diabetic neuropathy, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.41', 'Type 1 diabetes mellitus with diabetic mononeuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.42', 'Type 1 diabetes mellitus with diabetic polyneuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.43', 'Type 1 diabetes mellitus with diabetic autonomic (poly)neuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.44', 'Type 1 diabetes mellitus with diabetic amyotrophy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.49', 'Type 1 diabetes mellitus with other diabetic neurological complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.5', 'Type 1 diabetes mellitus with circulatory complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.51', 'Type 1 diabetes mellitus with diabetic peripheral angiopathy without gangrene')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.52', 'Type 1 diabetes mellitus with diabetic peripheral angiopathy with gangrene')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.59', 'Type 1 diabetes mellitus with other circulatory complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.6', 'Type 1 diabetes mellitus with other specified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.61', 'Type 1 diabetes mellitus with diabetic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.610', 'Type 1 diabetes mellitus with diabetic neuropathic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.618', 'Type 1 diabetes mellitus with other diabetic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.62', 'Type 1 diabetes mellitus with skin complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.620', 'Type 1 diabetes mellitus with diabetic dermatitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.621', 'Type 1 diabetes mellitus with foot ulcer')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.622', 'Type 1 diabetes mellitus with other skin ulcer')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.628', 'Type 1 diabetes mellitus with other skin complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.63', 'Type 1 diabetes mellitus with oral complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.630', 'Type 1 diabetes mellitus with periodontal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.638', 'Type 1 diabetes mellitus with other oral complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.64', 'Type 1 diabetes mellitus with hypoglycemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.641', 'Type 1 diabetes mellitus with hypoglycemia with coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.649', 'Type 1 diabetes mellitus with hypoglycemia without coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.65', 'Type 1 diabetes mellitus with hyperglycemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.69', 'Type 1 diabetes mellitus with other specified complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.8', 'Type 1 diabetes mellitus with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.A', 'Type 1 diabetes mellitus, presymptomatic')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.A0', 'Type 1 diabetes mellitus, presymptomatic, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.A1', 'Type 1 diabetes mellitus, presymptomatic, Stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.A2', 'Type 1 diabetes mellitus, presymptomatic, Stage 2')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.0', 'Type 2 diabetes mellitus with hyperosmolarity')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.00', 'Type 2 diabetes mellitus with hyperosmolarity without nonketotic hyperglycemic-hyperosmolar coma (NKHHC)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.01', 'Type 2 diabetes mellitus with hyperosmolarity with coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.1', 'Type 2 diabetes mellitus with ketoacidosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.10', 'Type 2 diabetes mellitus with ketoacidosis without coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.11', 'Type 2 diabetes mellitus with ketoacidosis with coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.2', 'Type 2 diabetes mellitus with kidney complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.21', 'Type 2 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.22', 'Type 2 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.29', 'Type 2 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3', 'Type 2 diabetes mellitus with ophthalmic complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.31', 'Type 2 diabetes mellitus with unspecified diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.311', 'Type 2 diabetes mellitus with unspecified diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.319', 'Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.32', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.321', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3211', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3212', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3213', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3219', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.329', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3291', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3292', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3293', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3299', 'Type 2 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.33', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.331', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3311', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3312', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3313', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3319', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.339', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3391', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3392', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3393', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3399', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.34', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.341', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3411', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3412', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3413', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3419', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.349', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3491', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3492', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3493', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3499', 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.35', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.351', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3511', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3512', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3513', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3519', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.352', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3521', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3522', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3523', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3529', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.353', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3531', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3532', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3533', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3539', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.354', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3541', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3542', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3543', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3549', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.355', 'Type 2 diabetes mellitus with stable proliferative diabetic retinopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3551', 'Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3552', 'Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3553', 'Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3559', 'Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.359', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3591', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3592', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3593', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.3599', 'Type 2 diabetes mellitus with proliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.36', 'Type 2 diabetes mellitus with diabetic cataract')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.37', 'Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.37X1', 'Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.37X2', 'Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.37X3', 'Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.37X9', 'Type 2 diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.39', 'Type 2 diabetes mellitus with other diabetic ophthalmic complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.4', 'Type 2 diabetes mellitus with neurological complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.40', 'Type 2 diabetes mellitus with diabetic neuropathy, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.41', 'Type 2 diabetes mellitus with diabetic mononeuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.42', 'Type 2 diabetes mellitus with diabetic polyneuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.43', 'Type 2 diabetes mellitus with diabetic autonomic (poly)neuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.44', 'Type 2 diabetes mellitus with diabetic amyotrophy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.49', 'Type 2 diabetes mellitus with other diabetic neurological complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.5', 'Type 2 diabetes mellitus with circulatory complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.51', 'Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.52', 'Type 2 diabetes mellitus with diabetic peripheral angiopathy with gangrene')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.59', 'Type 2 diabetes mellitus with other circulatory complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.6', 'Type 2 diabetes mellitus with other specified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.61', 'Type 2 diabetes mellitus with diabetic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.610', 'Type 2 diabetes mellitus with diabetic neuropathic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.618', 'Type 2 diabetes mellitus with other diabetic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.62', 'Type 2 diabetes mellitus with skin complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.620', 'Type 2 diabetes mellitus with diabetic dermatitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.621', 'Type 2 diabetes mellitus with foot ulcer')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.622', 'Type 2 diabetes mellitus with other skin ulcer')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.628', 'Type 2 diabetes mellitus with other skin complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.63', 'Type 2 diabetes mellitus with oral complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.630', 'Type 2 diabetes mellitus with periodontal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.638', 'Type 2 diabetes mellitus with other oral complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.64', 'Type 2 diabetes mellitus with hypoglycemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.641', 'Type 2 diabetes mellitus with hypoglycemia with coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.649', 'Type 2 diabetes mellitus with hypoglycemia without coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.65', 'Type 2 diabetes mellitus with hyperglycemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.69', 'Type 2 diabetes mellitus with other specified complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.8', 'Type 2 diabetes mellitus with unspecified complications')
) AS t (system, code, display) ;