create or replace view irae__dx_cancer_malignant_melanoma_icd10 as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'C43.0', 'Malignant melanoma of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.10', 'Malignant melanoma of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.11', 'Malignant melanoma of right eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.12', 'Malignant melanoma of left eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.20', 'Malignant melanoma of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.21', 'Malignant melanoma of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.22', 'Malignant melanoma of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.30', 'Malignant melanoma of unspecified part of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.31', 'Malignant melanoma of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.39', 'Malignant melanoma of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.4', 'Malignant melanoma of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.51', 'Malignant melanoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.52', 'Malignant melanoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.59', 'Malignant melanoma of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.60', 'Malignant melanoma of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.61', 'Malignant melanoma of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.62', 'Malignant melanoma of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.70', 'Malignant melanoma of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.71', 'Malignant melanoma of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.72', 'Malignant melanoma of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.8', 'Malignant melanoma of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.9', 'Malignant melanoma of skin, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.0', 'Melanoma in situ of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.10', 'Melanoma in situ of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.11', 'Melanoma in situ of right eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.12', 'Melanoma in situ of left eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.20', 'Melanoma in situ of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.21', 'Melanoma in situ of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.22', 'Melanoma in situ of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.30', 'Melanoma in situ of unspecified part of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.39', 'Melanoma in situ of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.4', 'Melanoma in situ of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.51', 'Melanoma in situ of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.52', 'Melanoma in situ of breast (skin) (soft tissue)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.59', 'Melanoma in situ of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.60', 'Melanoma in situ of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.61', 'Melanoma in situ of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.62', 'Melanoma in situ of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.70', 'Melanoma in situ of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.71', 'Melanoma in situ of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.72', 'Melanoma in situ of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.8', 'Melanoma in situ of other sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.9', 'Melanoma in situ, unspecified')
) AS t (system, code, display) ;