create or replace view irae__dx_transplant_recipient as select * from (values
('http://hl7.org/fhir/sid/icd-9-cm', 'V42.0', 'Kidney replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.1', 'Heart replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.2', 'Heart valve replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.3', 'Skin replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.4', 'Bone replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.5', 'Cornea replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.6', 'Lung replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.7', 'Liver replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.81', 'Bone marrow replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.82', 'Peripheral stem cells replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.83', 'Pancreas replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.84', 'Organ or tissue replaced by transplant, intestines')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.89', 'Other specified organ or tissue replaced by transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', 'V42.9', 'Unspecified organ or tissue replaced by transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.0', 'Kidney transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.1', 'Heart transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.2', 'Lung transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.3', 'Heart and lungs transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.4', 'Liver transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.5', 'Skin transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.6', 'Bone transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.7', 'Corneal transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.81', 'Bone marrow transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.82', 'Intestine transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.83', 'Pancreas transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.84', 'Stem cells transplant status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.89', 'Other transplanted organ and tissue status')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.9', 'Transplanted organ and tissue status, unspecified')
) AS t (system, code, display) ;