create or replace view irae__rx_azathioprine as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', 'code', 'display')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105611', 'IMURAN 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105611', 'Imuran 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105611', 'azaTHIOprine 50 MG Oral Tablet [Imuran]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105611', 'azathioprine 50 MG Oral Tablet [Imuran]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155000', 'azaTHIOprine Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155000', 'azathioprine Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155001', 'azaTHIOprine Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155001', 'azathioprine Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155002', 'azaTHIOprine Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155002', 'azathioprine Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172006', 'Imuran Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172007', 'Imuran Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1176318', 'Azasan Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1176319', 'Azasan Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1256', 'azaTHIOprine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1256', 'azathioprine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153129', 'azaTHIOprine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153129', 'azathioprine 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1789839', 'azaTHIOprine Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1789839', 'azathioprine Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197388', 'azaTHIOprine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197388', 'azathioprine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199310', 'azaTHIOprine 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199310', 'azathioprine 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202559', 'Imuran')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239983', 'azaTHIOprine (as azaTHIOprine sodium) 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239983', 'azaTHIOprine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239983', 'azathioprine (as azathioprine sodium) 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239983', 'azathioprine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '267476', 'azaTHIOprine sodium')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '267476', 'azathioprine sodium')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315447', 'azaTHIOprine 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315447', 'azathioprine 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '329313', 'azaTHIOprine 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '329313', 'azathioprine 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359228', 'azaTHIOprine 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359228', 'azathioprine 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359229', 'azaTHIOprine 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '359229', 'azathioprine 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360265', 'azaTHIOprine 75 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360265', 'azathioprine 75 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360266', 'azaTHIOprine 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '360266', 'azathioprine 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '368214', 'azaTHIOprine Oral Tablet [Imuran]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '368214', 'azathioprine Oral Tablet [Imuran]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370973', 'azaTHIOprine Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370973', 'azathioprine Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '385562', 'azaTHIOprine 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '385562', 'azathioprine 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404475', 'AZASAN 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404475', 'Azasan 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404475', 'azaTHIOprine 75 MG Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404475', 'azathioprine 75 MG Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404476', 'AZASAN 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404476', 'Azasan 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404476', 'azaTHIOprine 100 MG Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404476', 'azathioprine 100 MG Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '404872', 'Azasan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '405819', 'azaTHIOprine Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '405819', 'azathioprine Oral Tablet [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564120', 'azaTHIOprine 50 MG [Imuran]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564120', 'azathioprine 50 MG [Imuran]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '576426', 'azaTHIOprine 75 MG [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '576426', 'azathioprine 75 MG [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '576427', 'azaTHIOprine 100 MG [Azasan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '576427', 'azathioprine 100 MG [Azasan]')
) AS t (system, code, display) ;