create or replace view irae__dx_htn_hypertensive_ckd as select * from (values
('http://snomed.info/sct', '111438007', 'Hypertension secondary to renal disease in obstetric context (disorder)')
,('http://snomed.info/sct', '123799005', 'Renovascular hypertension (disorder)')
,('http://snomed.info/sct', '123800009', 'Goldblatt hypertension (disorder)')
,('http://snomed.info/sct', '14973001', 'Renal sclerosis with hypertension (disorder)')
,('http://snomed.info/sct', '193003', 'Benign hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '194783001', 'Secondary malignant renovascular hypertension (disorder)')
,('http://snomed.info/sct', '19769006', 'High-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '23130000', 'Paroxysmal hypertension (disorder)')
,('http://snomed.info/sct', '28119000', 'Renal hypertension (disorder)')
,('http://snomed.info/sct', '285831000119108', 'Malignant hypertensive chronic kidney disease (disorder)')
,('http://snomed.info/sct', '285841000119104', 'Malignant hypertensive end stage renal disease (disorder)')
,('http://snomed.info/sct', '286371000119107', 'Malignant hypertensive end stage renal disease on dialysis (disorder)')
,('http://snomed.info/sct', '302910002', 'Atherosclerotic renal artery stenosis (disorder)')
,('http://snomed.info/sct', '32916005', 'Nephrosclerosis (disorder)')
,('http://snomed.info/sct', '38481006', 'Hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '39018007', 'Renal arterial hypertension (disorder)')
,('http://snomed.info/sct', '397748008', 'Hypertension with albuminuria (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '403.01', 'Hypertensive chronic kidney disease, malignant, with chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '403.10', 'Hypertensive chronic kidney disease, benign, with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '403.11', 'Hypertensive chronic kidney disease, benign, with chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '403.90', 'Hypertensive chronic kidney disease, unspecified, with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '403.91', 'Hypertensive chronic kidney disease, unspecified, with chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.00', 'Hypertensive heart and chronic kidney disease, malignant, without heart failure and with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.01', 'Hypertensive heart and chronic kidney disease, malignant, with heart failure and with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.02', 'Hypertensive heart and chronic kidney disease, malignant, without heart failure and with chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.03', 'Hypertensive heart and chronic kidney disease, malignant, with heart failure and with chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.10', 'Hypertensive heart and chronic kidney disease, benign, without heart failure and with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.11', 'Hypertensive heart and chronic kidney disease, benign, with heart failure and with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.12', 'Hypertensive heart and chronic kidney disease, benign, without heart failure and with chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.13', 'Hypertensive heart and chronic kidney disease, benign, with heart failure and chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.90', 'Hypertensive heart and chronic kidney disease, unspecified, without heart failure and with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.91', 'Hypertensive heart and chronic kidney disease, unspecified, with heart failure and with chronic kidney disease stage I through stage IV, or unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.92', 'Hypertensive heart and chronic kidney disease, unspecified, without heart failure and with chronic kidney disease stage V or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-9-cm', '404.93', 'Hypertensive heart and chronic kidney disease, unspecified, with heart failure and chronic kidney disease stage V or end stage renal disease')
,('http://snomed.info/sct', '427889009', 'Hypertension associated with transplantation (disorder)')
,('http://snomed.info/sct', '428575007', 'Hypertension secondary to kidney transplant (disorder)')
,('http://snomed.info/sct', '431431000124100', 'Arteriosclerosis of renal artery (disorder)')
,('http://snomed.info/sct', '45281005', 'Atherosclerosis of renal artery (disorder)')
,('http://snomed.info/sct', '473392002', 'Hypertensive nephrosclerosis (disorder)')
,('http://snomed.info/sct', '49220004', 'Hypertensive renal failure (disorder)')
,('http://snomed.info/sct', '57684003', 'Parenchymal renal hypertension (disorder)')
,('http://snomed.info/sct', '62240004', 'Benign arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '65443008', 'Malignant hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '66052004', 'Benign hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '66610008', 'Malignant hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '73410007', 'Benign secondary renovascular hypertension (disorder)')
,('http://snomed.info/sct', '78544004', 'Chronic hypertensive uremia (disorder)')
,('http://snomed.info/sct', '81363003', 'Malignant arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '86234004', 'Hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '90493000', 'Arteriolar nephrosclerosis (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.0', 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.9', 'Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.0', 'Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.10', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.11', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.2', 'Hypertensive heart and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I15.0', 'Renovascular hypertension')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I15.1', 'Hypertension secondary to other renal disorders')
) AS t (system, code, display) ;