create or replace view irae__dx_kidney_condition as select * from (values
('http://snomed.info/sct', '104931000119100', 'Chronic kidney disease due to hypertension (disorder)')
,('http://snomed.info/sct', '111438007', 'Hypertension secondary to renal disease in obstetric context (disorder)')
,('http://snomed.info/sct', '117681000119102', 'Chronic kidney disease stage 1 due to hypertension (disorder)')
,('http://snomed.info/sct', '118781000119108', 'Pre-existing hypertensive chronic kidney disease in mother complicating pregnancy (disorder)')
,('http://snomed.info/sct', '123799005', 'Renovascular hypertension (disorder)')
,('http://snomed.info/sct', '123800009', 'Goldblatt hypertension (disorder)')
,('http://snomed.info/sct', '129151000119102', 'Chronic kidney disease stage 4 due to hypertension (disorder)')
,('http://snomed.info/sct', '129161000119100', 'Chronic kidney disease stage 5 due to hypertension (disorder)')
,('http://snomed.info/sct', '129171000119106', 'Chronic kidney disease stage 3 due to hypertension (disorder)')
,('http://snomed.info/sct', '129181000119109', 'Chronic kidney disease stage 2 due to hypertension (disorder)')
,('http://snomed.info/sct', '14669001', 'Acute kidney injury (disorder)')
,('http://snomed.info/sct', '14973001', 'Renal sclerosis with hypertension (disorder)')
,('http://snomed.info/sct', '153851000119106', 'Malignant hypertensive chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '15781000119107', 'Hypertensive heart AND chronic kidney disease with congestive heart failure (disorder)')
,('http://snomed.info/sct', '193003', 'Benign hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '194783001', 'Secondary malignant renovascular hypertension (disorder)')
,('http://snomed.info/sct', '19769006', 'High-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '23130000', 'Paroxysmal hypertension (disorder)')
,('http://snomed.info/sct', '253878003', 'Adult type polycystic kidney disease type 1 (disorder)')
,('http://snomed.info/sct', '253879006', 'Adult type polycystic kidney disease type 2 (disorder)')
,('http://snomed.info/sct', '28119000', 'Renal hypertension (disorder)')
,('http://snomed.info/sct', '285831000119108', 'Malignant hypertensive chronic kidney disease (disorder)')
,('http://snomed.info/sct', '285841000119104', 'Malignant hypertensive end stage renal disease (disorder)')
,('http://snomed.info/sct', '285851000119102', 'Malignant hypertensive chronic kidney disease stage 1 (disorder)')
,('http://snomed.info/sct', '285861000119100', 'Malignant hypertensive chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '285871000119106', 'Malignant hypertensive chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '285881000119109', 'Malignant hypertensive chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '286371000119107', 'Malignant hypertensive end stage renal disease on dialysis (disorder)')
,('http://snomed.info/sct', '32916005', 'Nephrosclerosis (disorder)')
,('http://snomed.info/sct', '35455006', 'Acute tubular necrosis (disorder)')
,('http://snomed.info/sct', '38481006', 'Hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '39018007', 'Renal arterial hypertension (disorder)')
,('http://snomed.info/sct', '397748008', 'Hypertension with albuminuria (disorder)')
,('http://snomed.info/sct', '42399005', 'Renal failure syndrome (disorder)')
,('http://snomed.info/sct', '427889009', 'Hypertension associated with transplantation (disorder)')
,('http://snomed.info/sct', '428575007', 'Hypertension secondary to kidney transplant (disorder)')
,('http://snomed.info/sct', '431855005', 'Chronic kidney disease stage 1 (disorder)')
,('http://snomed.info/sct', '431856006', 'Chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '431857002', 'Chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '433144002', 'Chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '433146000', 'Chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '444271000', 'Erythropoietin resistance in anemia of chronic kidney disease (disorder)')
,('http://snomed.info/sct', '473392002', 'Hypertensive nephrosclerosis (disorder)')
,('http://snomed.info/sct', '49220004', 'Hypertensive renal failure (disorder)')
,('http://snomed.info/sct', '57684003', 'Parenchymal renal hypertension (disorder)')
,('http://snomed.info/sct', '62240004', 'Benign arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '65443008', 'Malignant hypertensive renal disease (disorder)')
,('http://snomed.info/sct', '66052004', 'Benign hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '66610008', 'Malignant hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '700378005', 'Chronic kidney disease stage 3A (disorder)')
,('http://snomed.info/sct', '700379002', 'Chronic kidney disease stage 3B (disorder)')
,('http://snomed.info/sct', '707323002', 'Anemia co-occurrent and due to chronic kidney disease (disorder)')
,('http://snomed.info/sct', '71064009', 'Acquired polycystic kidney disease (disorder)')
,('http://snomed.info/sct', '711000119100', 'Chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71421000119105', 'Hypertension in chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71701000119105', 'Hypertension in chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '721000119107', 'Chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '731000119105', 'Chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '73410007', 'Benign secondary renovascular hypertension (disorder)')
,('http://snomed.info/sct', '741000119101', 'Chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '751000119104', 'Chronic kidney disease stage 1 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '765330003', 'Autosomal dominant polycystic kidney disease (disorder)')
,('http://snomed.info/sct', '771000119108', 'Chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '78544004', 'Chronic hypertensive uremia (disorder)')
,('http://snomed.info/sct', '81363003', 'Malignant arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '8501000119104', 'Hypertensive heart and chronic kidney disease (disorder)')
,('http://snomed.info/sct', '86234004', 'Hypertensive heart AND renal disease (disorder)')
,('http://snomed.info/sct', '90493000', 'Arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '90721000119101', 'Chronic kidney disease stage 1 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90731000119103', 'Chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90741000119107', 'Chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90751000119109', 'Chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90761000119106', 'Chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '96441000119101', 'Chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '96701000119107', 'Hypertensive heart AND chronic kidney disease on dialysis (disorder)')
,('http://snomed.info/sct', '96711000119105', 'Hypertensive heart AND chronic kidney disease stage 5 (disorder)')
,('http://snomed.info/sct', '96721000119103', 'Hypertensive heart AND chronic kidney disease stage 4 (disorder)')
,('http://snomed.info/sct', '96731000119100', 'Hypertensive heart AND chronic kidney disease stage 3 (disorder)')
,('http://snomed.info/sct', '96741000119109', 'Hypertensive heart AND chronic kidney disease stage 2 (disorder)')
,('http://snomed.info/sct', '96751000119106', 'Hypertensive heart AND chronic kidney disease stage 1 (disorder)')
,('http://www.nlm.nih.gov/research/umls', 'C0001126', 'Renal tubular acidosis')
,('http://www.nlm.nih.gov/research/umls', 'C0011881', 'Diabetic Nephropathy')
,('http://www.nlm.nih.gov/research/umls', 'C0017658', 'Glomerulonephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0017661', 'IGA Glomerulonephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0017662', 'Glomerulonephritis, Membranoproliferative')
,('http://www.nlm.nih.gov/research/umls', 'C0017665', 'Membranous glomerulonephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0020295', 'Hydronephrosis')
,('http://www.nlm.nih.gov/research/umls', 'C0020544', 'Renal hypertension')
,('http://www.nlm.nih.gov/research/umls', 'C0021313', 'Infection of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0022658', 'Kidney Diseases')
,('http://www.nlm.nih.gov/research/umls', 'C0022660', 'Kidney Failure, Acute')
,('http://www.nlm.nih.gov/research/umls', 'C0022661', 'Kidney Failure, Chronic')
,('http://www.nlm.nih.gov/research/umls', 'C0022665', 'Kidney Neoplasm')
,('http://www.nlm.nih.gov/research/umls', 'C0022671', 'Kidney Transplantation')
,('http://www.nlm.nih.gov/research/umls', 'C0022681', 'Medullary sponge kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0024143', 'Lupus Nephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0027695', 'Nephrectomy')
,('http://www.nlm.nih.gov/research/umls', 'C0027697', 'Nephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0027707', 'Nephritis, Interstitial')
,('http://www.nlm.nih.gov/research/umls', 'C0027708', 'Nephroblastoma')
,('http://www.nlm.nih.gov/research/umls', 'C0027719', 'Nephrosclerosis')
,('http://www.nlm.nih.gov/research/umls', 'C0027726', 'Nephrotic Syndrome')
,('http://www.nlm.nih.gov/research/umls', 'C0034186', 'Pyelonephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0034216', 'Pyonephrosis')
,('http://www.nlm.nih.gov/research/umls', 'C0035067', 'Renal Artery Stenosis')
,('http://www.nlm.nih.gov/research/umls', 'C0035078', 'Kidney Failure')
,('http://www.nlm.nih.gov/research/umls', 'C0035086', 'Renal Osteodystrophy')
,('http://www.nlm.nih.gov/research/umls', 'C0041349', 'Nephritis, Tubulointerstitial')
,('http://www.nlm.nih.gov/research/umls', 'C0085413', 'Polycystic Kidney, Autosomal Dominant')
,('http://www.nlm.nih.gov/research/umls', 'C0151746', 'Abnormal renal function')
,('http://www.nlm.nih.gov/research/umls', 'C0152451', 'Chronic glomerulonephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0153618', 'Malignant tumor of renal pelvis')
,('http://www.nlm.nih.gov/research/umls', 'C0153685', 'Metastatic malignant neoplasm to kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0155601', 'Hypertensive heart and renal disease')
,('http://www.nlm.nih.gov/research/umls', 'C0155734', 'Atherosclerosis of renal artery')
,('http://www.nlm.nih.gov/research/umls', 'C0155742', 'Aneurysm of renal artery')
,('http://www.nlm.nih.gov/research/umls', 'C0191126', 'Venous catheterization for renal dialysis')
,('http://www.nlm.nih.gov/research/umls', 'C0203851', 'Kidney transplant evaluation')
,('http://www.nlm.nih.gov/research/umls', 'C0238217', 'Renal transplant rejection')
,('http://www.nlm.nih.gov/research/umls', 'C0241961', 'Angiomyolipoma of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0262613', 'Renal mass')
,('http://www.nlm.nih.gov/research/umls', 'C0264653', 'Hypertensive renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0266294', 'Unilateral agenesis of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0268769', 'Chronic gouty nephropathy')
,('http://www.nlm.nih.gov/research/umls', 'C0268781', 'Idiopathic granulomatous interstitial nephropathy')
,('http://www.nlm.nih.gov/research/umls', 'C0268800', 'Simple renal cyst')
,('http://www.nlm.nih.gov/research/umls', 'C0268804', 'Hydroureteronephrosis')
,('http://www.nlm.nih.gov/research/umls', 'C0269673', 'Renal disease in pregnancy AND/OR puerperium without hypertension')
,('http://www.nlm.nih.gov/research/umls', 'C0271847', 'Hyperparathyroidism due to renal insufficiency')
,('http://www.nlm.nih.gov/research/umls', 'C0271932', 'Anemia of chronic renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0274419', 'Complication of renal dialysis')
,('http://www.nlm.nih.gov/research/umls', 'C0279702', 'Conventional (Clear Cell) Renal Cell Carcinoma')
,('http://www.nlm.nih.gov/research/umls', 'C0311245', 'Congenital cystic kidney disease')
,('http://www.nlm.nih.gov/research/umls', 'C0341677', 'renal impairment. disorder resulting from')
,('http://www.nlm.nih.gov/research/umls', 'C0341687', 'Nephrotic syndrome in amyloidosis')
,('http://www.nlm.nih.gov/research/umls', 'C0341698', 'Atrophy of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0348860', 'Hypertensive renal disease with renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0348879', 'Hypertensive heart and renal disease with renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0403419', 'Chronic focal glomerulonephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0403447', 'Chronic Kidney Insufficiency')
,('http://www.nlm.nih.gov/research/umls', 'C0403462', 'Acute-on-chronic renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0403464', 'End stage renal failure on dialysis')
,('http://www.nlm.nih.gov/research/umls', 'C0451718', 'Non-obstructive reflux-associated chronic pyelonephritis (disorder)')
,('http://www.nlm.nih.gov/research/umls', 'C0455641', 'History of renal transplant')
,('http://www.nlm.nih.gov/research/umls', 'C0455667', 'History of renal dialysis')
,('http://www.nlm.nih.gov/research/umls', 'C0472713', 'Anemia of renal disease')
,('http://www.nlm.nih.gov/research/umls', 'C0494575', 'Hypertensive heart and renal disease with (congestive) heart failure')
,('http://www.nlm.nih.gov/research/umls', 'C0494576', 'Hypertensive heart and renal disease with both (congestive) heart failure and renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0496927', 'Neoplasm of uncertain or unknown behavior of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0520575', 'Acute pyelonephritis')
,('http://www.nlm.nih.gov/research/umls', 'C0521622', 'Bilateral hydronephrosis')
,('http://www.nlm.nih.gov/research/umls', 'C0553718', 'Renal artery occlusion')
,('http://www.nlm.nih.gov/research/umls', 'C0554309', 'Prerenal azotemia')
,('http://www.nlm.nih.gov/research/umls', 'C0588179', 'Anemia secondary to renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0740457', 'Malignant neoplasm of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C0741151', 'Aneurysm of infrarenal abdominal aorta')
,('http://www.nlm.nih.gov/research/umls', 'C0748315', 'Chronic progressive renal failure')
,('http://www.nlm.nih.gov/research/umls', 'C0848548', 'hypertensive nephropathy')
,('http://www.nlm.nih.gov/research/umls', 'C1261281', 'Disorder of transplanted kidney')
,('http://www.nlm.nih.gov/research/umls', 'C1319314', 'Transitional cell carcinoma of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C1387408', 'History of malignant neoplasm of kidney')
,('http://www.nlm.nih.gov/research/umls', 'C1561643', 'Chronic Kidney Diseases')
,('http://www.nlm.nih.gov/research/umls', 'C1565489', 'Renal Insufficiency')
,('http://www.nlm.nih.gov/research/umls', 'C1691228', 'Cystic Kidney Diseases')
,('http://www.nlm.nih.gov/research/umls', 'C1719759', 'Renal disorder due to type 1 diabetes mellitus')
,('http://www.nlm.nih.gov/research/umls', 'C1720457', 'Renal disorder due to type 2 diabetes mellitus')
,('http://www.nlm.nih.gov/research/umls', 'C1971734', 'Disorder of kidney and/or ureter')
,('http://www.nlm.nih.gov/research/umls', 'C2316401', 'Chronic kidney disease stage 1')
,('http://www.nlm.nih.gov/research/umls', 'C2316786', 'Chronic kidney disease stage 2')
,('http://www.nlm.nih.gov/research/umls', 'C2316787', 'Chronic kidney disease stage 3')
,('http://www.nlm.nih.gov/research/umls', 'C2316810', 'Chronic kidney disease stage 5')
,('http://www.nlm.nih.gov/research/umls', 'C2317473', 'Chronic kidney disease stage 4')
,('http://www.nlm.nih.gov/research/umls', 'C3887499', 'Renal cyst')
,('http://www.nlm.nih.gov/research/umls', 'C4546414', 'Left renal agenesis')
,('http://www.nlm.nih.gov/research/umls', 'C4546415', 'Right renal agenesis')
,('http://www.nlm.nih.gov/research/umls', 'C4551529', 'Renal Dialysis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.0', 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I12.9', 'Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.0', 'Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.10', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.11', 'Hypertensive heart and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I13.2', 'Hypertensive heart and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00', 'Acute nephritic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.0', 'Acute nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.1', 'Acute nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.2', 'Acute nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.3', 'Acute nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.4', 'Acute nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.5', 'Acute nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.6', 'Acute nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.7', 'Acute nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.8', 'Acute nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.9', 'Acute nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01', 'Rapidly progressive nephritic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.0', 'Rapidly progressive nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.1', 'Rapidly progressive nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.2', 'Rapidly progressive nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.3', 'Rapidly progressive nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.4', 'Rapidly progressive nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.5', 'Rapidly progressive nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.6', 'Rapidly progressive nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.7', 'Rapidly progressive nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.8', 'Rapidly progressive nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.9', 'Rapidly progressive nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02', 'Recurrent and persistent hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.0', 'Recurrent and persistent hematuria with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.1', 'Recurrent and persistent hematuria with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.2', 'Recurrent and persistent hematuria with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.3', 'Recurrent and persistent hematuria with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.4', 'Recurrent and persistent hematuria with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.5', 'Recurrent and persistent hematuria with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.6', 'Recurrent and persistent hematuria with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.7', 'Recurrent and persistent hematuria with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.8', 'Recurrent and persistent hematuria with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.9', 'Recurrent and persistent hematuria with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03', 'Chronic nephritic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.0', 'Chronic nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.1', 'Chronic nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.2', 'Chronic nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.3', 'Chronic nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.4', 'Chronic nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.5', 'Chronic nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.6', 'Chronic nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.7', 'Chronic nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.8', 'Chronic nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.9', 'Chronic nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04', 'Nephrotic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.0', 'Nephrotic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.1', 'Nephrotic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.2', 'Nephrotic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.3', 'Nephrotic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.4', 'Nephrotic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.5', 'Nephrotic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.6', 'Nephrotic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.7', 'Nephrotic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.8', 'Nephrotic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.9', 'Nephrotic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05', 'Unspecified nephritic syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.0', 'Unspecified nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.1', 'Unspecified nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.2', 'Unspecified nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.3', 'Unspecified nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.4', 'Unspecified nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.5', 'Unspecified nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.6', 'Unspecified nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.7', 'Unspecified nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.8', 'Unspecified nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.9', 'Unspecified nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06', 'Isolated proteinuria with specified morphological lesion')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.0', 'Isolated proteinuria with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.1', 'Isolated proteinuria with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.2', 'Isolated proteinuria with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.3', 'Isolated proteinuria with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.4', 'Isolated proteinuria with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.5', 'Isolated proteinuria with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.6', 'Isolated proteinuria with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.7', 'Isolated proteinuria with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.8', 'Isolated proteinuria with other morphologic lesion')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.9', 'Isolated proteinuria with unspecified morphologic lesion')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07', 'Hereditary nephropathy, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.0', 'Hereditary nephropathy, not elsewhere classified with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.1', 'Hereditary nephropathy, not elsewhere classified with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.2', 'Hereditary nephropathy, not elsewhere classified with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.3', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.4', 'Hereditary nephropathy, not elsewhere classified with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.5', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.6', 'Hereditary nephropathy, not elsewhere classified with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.7', 'Hereditary nephropathy, not elsewhere classified with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.8', 'Hereditary nephropathy, not elsewhere classified with other morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.9', 'Hereditary nephropathy, not elsewhere classified with unspecified morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N08', 'Glomerular disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N10', 'Acute pyelonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11', 'Chronic tubulo-interstitial nephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11.0', 'Nonobstructive reflux-associated chronic pyelonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11.1', 'Chronic obstructive pyelonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11.8', 'Other chronic tubulo-interstitial nephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N11.9', 'Chronic tubulo-interstitial nephritis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N12', 'Tubulo-interstitial nephritis, not specified as acute or chronic')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13', 'Obstructive and reflux uropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.0', 'Hydronephrosis with ureteropelvic junction obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.1', 'Hydronephrosis with ureteral stricture, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.2', 'Hydronephrosis with renal and ureteral calculous obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.3', 'Other and unspecified hydronephrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.30', 'Unspecified hydronephrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.39', 'Other hydronephrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.4', 'Hydroureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.5', 'Crossing vessel and stricture of ureter without hydronephrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.6', 'Pyonephrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.7', 'Vesicoureteral-reflux')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.70', 'Vesicoureteral-reflux, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.71', 'Vesicoureteral-reflux without reflux nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.72', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.721', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter, unilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.722', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.729', 'Vesicoureteral-reflux with reflux nephropathy without hydroureter, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.73', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.731', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter, unilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.732', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.739', 'Vesicoureteral-reflux with reflux nephropathy with hydroureter, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.8', 'Other obstructive and reflux uropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N13.9', 'Obstructive and reflux uropathy, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14', 'Drug- and heavy-metal-induced tubulo-interstitial and tubular conditions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.0', 'Analgesic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.1', 'Nephropathy induced by other drugs, medicaments and biological substances')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.2', 'Nephropathy induced by unspecified drug, medicament or biological substance')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.3', 'Nephropathy induced by heavy metals')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.4', 'Toxic nephropathy, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N15', 'Other renal tubulo-interstitial diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N15.0', 'Balkan nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N15.1', 'Renal and perinephric abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N15.8', 'Other specified renal tubulo-interstitial diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N15.9', 'Renal tubulo-interstitial disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N16', 'Renal tubulo-interstitial disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17', 'Acute kidney failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.0', 'Acute kidney failure with tubular necrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.1', 'Acute kidney failure with acute cortical necrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.2', 'Acute kidney failure with medullary necrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.8', 'Other acute kidney failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.9', 'Acute kidney failure, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18', 'Chronic kidney disease (CKD)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.1', 'Chronic kidney disease, stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.2', 'Chronic kidney disease, stage 2 (mild)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.3', 'Chronic kidney disease, stage 3 (moderate)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.4', 'Chronic kidney disease, stage 4 (severe)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.5', 'Chronic kidney disease, stage 5')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.6', 'End stage renal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N18.9', 'Chronic kidney disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N19', 'Unspecified kidney failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25', 'Disorders resulting from impaired renal tubular function')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.0', 'Renal osteodystrophy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.1', 'Nephrogenic diabetes insipidus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.8', 'Other disorders resulting from impaired renal tubular function')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.81', 'Secondary hyperparathyroidism of renal origin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.89', 'Other disorders resulting from impaired renal tubular function')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.9', 'Disorder resulting from impaired renal tubular function, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26', 'Unspecified contracted kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26.1', 'Atrophy of kidney (terminal)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26.2', 'Page kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26.9', 'Renal sclerosis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N27', 'Small kidney of unknown cause')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N27.0', 'Small kidney, unilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N27.1', 'Small kidney, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N27.9', 'Small kidney, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28', 'Other disorders of kidney and ureter, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.0', 'Ischemia and infarction of kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.1', 'Cyst of kidney, acquired')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.8', 'Other specified disorders of kidney and ureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.81', 'Hypertrophy of kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.82', 'Megaloureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.83', 'Nephroptosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.84', 'Pyelitis cystica')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.85', 'Pyeloureteritis cystica')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.86', 'Ureteritis cystica')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.89', 'Other specified disorders of kidney and ureter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N28.9', 'Disorder of kidney and ureter, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N29', 'Other disorders of kidney and ureter in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30', 'Cystitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.0', 'Acute cystitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.00', 'Acute cystitis without hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.01', 'Acute cystitis with hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.1', 'Interstitial cystitis (chronic)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.10', 'Interstitial cystitis (chronic) without hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.11', 'Interstitial cystitis (chronic) with hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.2', 'Other chronic cystitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.20', 'Other chronic cystitis without hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.21', 'Other chronic cystitis with hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.3', 'Trigonitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.30', 'Trigonitis without hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.31', 'Trigonitis with hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.4', 'Irradiation cystitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.40', 'Irradiation cystitis without hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.41', 'Irradiation cystitis with hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.8', 'Other cystitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.80', 'Other cystitis without hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.81', 'Other cystitis with hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.9', 'Cystitis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.90', 'Cystitis, unspecified without hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N30.91', 'Cystitis, unspecified with hematuria')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N31', 'Neuromuscular dysfunction of bladder, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N31.0', 'Uninhibited neuropathic bladder, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N31.1', 'Reflex neuropathic bladder, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N31.2', 'Flaccid neuropathic bladder, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N31.8', 'Other neuromuscular dysfunction of bladder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N31.9', 'Neuromuscular dysfunction of bladder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32', 'Other disorders of bladder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.0', 'Bladder-neck obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.1', 'Vesicointestinal fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.2', 'Vesical fistula, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.3', 'Diverticulum of bladder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.8', 'Other specified disorders of bladder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.81', 'Overactive bladder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.89', 'Other specified disorders of bladder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N32.9', 'Bladder disorder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N33', 'Bladder disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N34', 'Urethritis and urethral syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N34.0', 'Urethral abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N34.1', 'Nonspecific urethritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N34.2', 'Other urethritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N34.3', 'Urethral syndrome, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35', 'Urethral stricture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.0', 'Post-traumatic urethral stricture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.01', 'Post-traumatic urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.010', 'Post-traumatic urethral stricture, male, meatal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.011', 'Post-traumatic bulbous urethral stricture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.012', 'Post-traumatic membranous urethral stricture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.013', 'Post-traumatic anterior urethral stricture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.014', 'Post-traumatic urethral stricture, male, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.016', 'Post-traumatic urethral stricture, male, overlapping sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.02', 'Post-traumatic urethral stricture, female')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.021', 'Urethral stricture due to childbirth')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.028', 'Other post-traumatic urethral stricture, female')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.1', 'Postinfective urethral stricture, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.11', 'Postinfective urethral stricture, not elsewhere classified, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.111', 'Postinfective urethral stricture, not elsewhere classified, male, meatal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.112', 'Postinfective bulbous urethral stricture, not elsewhere classified, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.113', 'Postinfective membranous urethral stricture, not elsewhere classified, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.114', 'Postinfective anterior urethral stricture, not elsewhere classified, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.116', 'Postinfective urethral stricture, not elsewhere classified, male, overlapping sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.119', 'Postinfective urethral stricture, not elsewhere classified, male, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.12', 'Postinfective urethral stricture, not elsewhere classified, female')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.8', 'Other urethral stricture')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.81', 'Other urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.811', 'Other urethral stricture, male, meatal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.812', 'Other bulbous urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.813', 'Other membranous urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.814', 'Other anterior urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.816', 'Other urethral stricture, male, overlapping sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.819', 'Other urethral stricture, male, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.82', 'Other urethral stricture, female')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.9', 'Urethral stricture, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.91', 'Urethral stricture, unspecified, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.911', 'Unspecified urethral stricture, male, meatal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.912', 'Unspecified bulbous urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.913', 'Unspecified membranous urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.914', 'Unspecified anterior urethral stricture, male')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.916', 'Unspecified urethral stricture, male, overlapping sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.919', 'Unspecified urethral stricture, male, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N35.92', 'Unspecified urethral stricture, female')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36', 'Other disorders of urethra')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.0', 'Urethral fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.1', 'Urethral diverticulum')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.2', 'Urethral caruncle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.4', 'Urethral functional and muscular disorders')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.41', 'Hypermobility of urethra')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.42', 'Intrinsic sphincter deficiency (ISD)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.43', 'Combined hypermobility of urethra and intrinsic sphincter deficiency')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.44', 'Muscular disorders of urethra')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.5', 'Urethral false passage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.8', 'Other specified disorders of urethra')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N36.9', 'Urethral disorder, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N37', 'Urethral disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39', 'Other disorders of urinary system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.0', 'Urinary tract infection, site not specified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.3', 'Stress incontinence (female) (male)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.4', 'Other specified urinary incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.41', 'Urge incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.42', 'Incontinence without sensory awareness')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.43', 'Post-void dribbling')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.44', 'Nocturnal enuresis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.45', 'Continuous leakage')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.46', 'Mixed incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.49', 'Other specified urinary incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.490', 'Overflow incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.491', 'Coital incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.492', 'Postural (urinary) incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.498', 'Other specified urinary incontinence')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.8', 'Other specified disorders of urinary system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N39.9', 'Disorder of urinary system, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.00', 'Congenital renal cyst, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.01', 'Congenital single renal cyst')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.02', 'Congenital multiple renal cysts')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.11', 'Cystic dilatation of collecting ducts')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.2', 'Polycystic kidney, adult type')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.3', 'Polycystic kidney, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.4', 'Renal dysplasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.5', 'Medullary cystic kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.8', 'Other cystic kidney diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.9', 'Cystic kidney disease, unspecified')
) AS t (system, code, display) ;