create or replace view irae__dx_autoimmune_ibd as select * from (values
('http://snomed.info/sct', '10743231000119101', 'Stenosis of small intestine co-occurrent and due to Crohns disease (disorder)')
,('http://snomed.info/sct', '1085131000119105', 'Abscess of intestine co-occurrent and due to chronic ulcerative pancolitis (disorder)')
,('http://snomed.info/sct', '1085231000119100', 'Abscess of intestine co-occurrent and due to chronic ulcerative rectosigmoiditis (disorder)')
,('http://snomed.info/sct', '1085751000119100', 'Abscess of intestine co-occurrent and due to Crohns disease of large intestine (disorder)')
,('http://snomed.info/sct', '1085801000119106', 'Abscess of intestine co-occurrent and due to Crohns disease of small and large intestine (disorder)')
,('http://snomed.info/sct', '1085851000119105', 'Abscess of intestine co-occurrent and due to Crohns disease of small intestine (disorder)')
,('http://snomed.info/sct', '1085901000119101', 'Abscess of intestine co-occurrent and due to Crohns disease (disorder)')
,('http://snomed.info/sct', '1092841000119100', 'Abscess of intestine co-occurrent and due to ulcerative colitis (disorder)')
,('http://snomed.info/sct', '1173999006', 'Interleukin 21 related infantile inflammatory bowel disease (disorder)')
,('http://snomed.info/sct', '1186721005', 'Infantile inflammatory bowel disease with neurological involvement (disorder)')
,('http://snomed.info/sct', '1197428008', 'Combined immunodeficiency, enteropathy spectrum (disorder)')
,('http://snomed.info/sct', '1197727002', 'Crohns disease of parastomal skin (disorder)')
,('http://snomed.info/sct', '1197732001', 'Crohn disease of colon and rectum (disorder)')
,('http://snomed.info/sct', '1197733006', 'Crohn disease of jejunum and ileum (disorder)')
,('http://snomed.info/sct', '128600008', 'Acute ulcerative colitis (disorder)')
,('http://snomed.info/sct', '1300120005', 'Alkaline phosphatase intestinal gene related inflammatory bowel disease (disorder)')
,('http://snomed.info/sct', '1300124001', 'Tripartite motif-containing protein 22-related inflammatory bowel disease (disorder)')
,('http://snomed.info/sct', '13470001', 'Chronic ulcerative ileocolitis (disorder)')
,('http://snomed.info/sct', '14311001', 'Severe chronic ulcerative colitis (disorder)')
,('http://snomed.info/sct', '15342002', 'Chronic ulcerative enterocolitis (disorder)')
,('http://snomed.info/sct', '196578009', 'Crohns disease of oral soft tissues (disorder)')
,('http://snomed.info/sct', '196977009', 'Crohns disease of terminal ileum (disorder)')
,('http://snomed.info/sct', '196987008', 'Ulcerative ileocolitis (disorder)')
,('http://snomed.info/sct', '201805000', 'Juvenile arthritis in Crohns disease (disorder)')
,('http://snomed.info/sct', '201807008', 'Juvenile arthritis in ulcerative colitis (disorder)')
,('http://snomed.info/sct', '206138281000119100', 'Crohn disease of rectum in remission (disorder)')
,('http://snomed.info/sct', '214036171000119109', 'Left sided ulcerative colitis in remission (disorder)')
,('http://snomed.info/sct', '234999001', 'Crohns disease of gingivae (disorder)')
,('http://snomed.info/sct', '235607002', 'Crohns disease of esophagus (disorder)')
,('http://snomed.info/sct', '235664007', 'Crohns disease of stomach (disorder)')
,('http://snomed.info/sct', '235714007', 'Ulcerative enterocolitis (disorder)')
,('http://snomed.info/sct', '235796008', 'Perianal Crohns disease (disorder)')
,('http://snomed.info/sct', '239809007', 'Juvenile arthritis of inflammatory bowel disease (disorder)')
,('http://snomed.info/sct', '24526004', 'Inflammatory bowel disease (disorder)')
,('http://snomed.info/sct', '24829000', 'Eosinophilic ulcerative colitis (disorder)')
,('http://snomed.info/sct', '253855721000119107', 'Crohn disease of small intestine in remission (disorder)')
,('http://snomed.info/sct', '295046003', 'Ulcerative proctocolitis (disorder)')
,('http://snomed.info/sct', '34000006', 'Crohns disease (disorder)')
,('http://snomed.info/sct', '38106008', 'Crohns disease of ileum (disorder)')
,('http://snomed.info/sct', '3815005', 'Crohns disease of rectum (disorder)')
,('http://snomed.info/sct', '397172008', 'Gastrointestinal Crohns disease (disorder)')
,('http://snomed.info/sct', '397173003', 'Crohns disease of intestine (disorder)')
,('http://snomed.info/sct', '399946006', 'Crohns disease of skin (disorder)')
,('http://snomed.info/sct', '402375009', 'Crohns disease of vulva (disorder)')
,('http://snomed.info/sct', '402376005', 'Crohns disease of penis (disorder)')
,('http://snomed.info/sct', '402377001', 'Crohns disease of scrotum (disorder)')
,('http://snomed.info/sct', '402378006', 'Metastatic Crohns disease of skin (disorder)')
,('http://snomed.info/sct', '404908004', 'Toxic megacolon due to ulcerative colitis (disorder)')
,('http://snomed.info/sct', '410484008', 'Iritis with ulcerative colitis (disorder)')
,('http://snomed.info/sct', '410485009', 'Iritis with Crohns disease (disorder)')
,('http://snomed.info/sct', '414153008', 'Exacerbation of Crohns disease of large intestine (disorder)')
,('http://snomed.info/sct', '414154002', 'Exacerbation of Crohns disease of small intestine (disorder)')
,('http://snomed.info/sct', '414156000', 'Exacerbation of ulcerative colitis (disorder)')
,('http://snomed.info/sct', '426549001', 'Crohns disease in remission (disorder)')
,('http://snomed.info/sct', '441971007', 'Chronic left-sided ulcerative colitis (disorder)')
,('http://snomed.info/sct', '442159003', 'Chronic ulcerative pancolitis (disorder)')
,('http://snomed.info/sct', '444546002', 'Chronic ulcerative colitis (disorder)')
,('http://snomed.info/sct', '444548001', 'Ulcerative pancolitis (disorder)')
,('http://snomed.info/sct', '445243001', 'Left sided ulcerative colitis (disorder)')
,('http://snomed.info/sct', '453720571000119100', 'Acute ulcerative rectosigmoiditis (disorder)')
,('http://snomed.info/sct', '501913511000119109', 'Chronic ulcerative rectosigmoiditis in remission (disorder)')
,('http://snomed.info/sct', '50440006', 'Crohns disease of colon (disorder)')
,('http://snomed.info/sct', '515623061000119105', 'Crohn disease of colon in remission (disorder)')
,('http://snomed.info/sct', '52506002', 'Chronic ulcerative rectosigmoiditis (disorder)')
,('http://snomed.info/sct', '527788091000119106', 'Crohn disease of small intestine and large intestine in remission (disorder)')
,('http://snomed.info/sct', '542440891000119103', 'Ulcerative pancolitis in remission (disorder)')
,('http://snomed.info/sct', '56287005', 'Crohns disease of duodenum (disorder)')
,('http://snomed.info/sct', '56689002', 'Crohns disease of small intestine (disorder)')
,('http://snomed.info/sct', '61424003', 'Crohns disease of pylorus (disorder)')
,('http://snomed.info/sct', '64766004', 'Ulcerative colitis (disorder)')
,('http://snomed.info/sct', '671131000124105', 'Crohn-like disease of ileal pouch (disorder)')
,('http://snomed.info/sct', '697969008', 'Ulcerative colitis in remission (disorder)')
,('http://snomed.info/sct', '70622003', 'Crohns disease of pyloric antrum (disorder)')
,('http://snomed.info/sct', '71833008', 'Crohns disease of small and large intestines (disorder)')
,('http://snomed.info/sct', '721686000', 'Inflammatory polyps co-occurrent and due to inflammatory bowel disease (disorder)')
,('http://snomed.info/sct', '721702009', 'Crohn disease of anal canal (disorder)')
,('http://snomed.info/sct', '722850002', 'Crohns disease of gastrointestinal anastomosis (disorder)')
,('http://snomed.info/sct', '726101009', 'Extraintestinal Crohns (disorder)')
,('http://snomed.info/sct', '733157003', 'Crohn disease of appendix (disorder)')
,('http://snomed.info/sct', '737195007', 'Crohn disease of upper gastrointestinal tract (disorder)')
,('http://snomed.info/sct', '7620006', 'Crohns disease of large bowel (disorder)')
,('http://snomed.info/sct', '78324009', 'Mild chronic ulcerative colitis (disorder)')
,('http://snomed.info/sct', '78712000', 'Moderate chronic ulcerative colitis (disorder)')
,('http://snomed.info/sct', '788718000', 'Iritis co-occurrent with inflammatory bowel disease (disorder)')
,('http://snomed.info/sct', '8161000119106', 'Arthritis co-occurrent and due to Crohns disease (disorder)')
,('http://snomed.info/sct', '91390005', 'Crohns disease of jejunum (disorder)')
,('http://snomed.info/sct', '966011731000119103', 'Acute ulcerative pancolitis (disorder)')
,('http://snomed.info/sct', '969688801000119108', 'Acute left-sided ulcerative colitis (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50', 'Crohns disease [regional enteritis]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.0', 'Crohns disease of small intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.00', 'Crohns disease of small intestine without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.01', 'Crohns disease of small intestine with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.011', 'Crohns disease of small intestine with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.012', 'Crohns disease of small intestine with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.013', 'Crohns disease of small intestine with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.014', 'Crohns disease of small intestine with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.018', 'Crohns disease of small intestine with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.019', 'Crohns disease of small intestine with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.1', 'Crohns disease of large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.10', 'Crohns disease of large intestine without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.11', 'Crohns disease of large intestine with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.111', 'Crohns disease of large intestine with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.112', 'Crohns disease of large intestine with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.113', 'Crohns disease of large intestine with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.114', 'Crohns disease of large intestine with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.118', 'Crohns disease of large intestine with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.119', 'Crohns disease of large intestine with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.8', 'Crohns disease of both small and large intestine')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.80', 'Crohns disease of both small and large intestine without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.81', 'Crohns disease of both small and large intestine with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.811', 'Crohns disease of both small and large intestine with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.812', 'Crohns disease of both small and large intestine with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.813', 'Crohns disease of both small and large intestine with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.814', 'Crohns disease of both small and large intestine with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.818', 'Crohns disease of both small and large intestine with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.819', 'Crohns disease of both small and large intestine with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.9', 'Crohns disease, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.90', 'Crohns disease, unspecified, without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.91', 'Crohns disease, unspecified, with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.911', 'Crohns disease, unspecified, with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.912', 'Crohns disease, unspecified, with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.913', 'Crohns disease, unspecified, with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.914', 'Crohns disease, unspecified, with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.918', 'Crohns disease, unspecified, with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K50.919', 'Crohns disease, unspecified, with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51', 'Ulcerative colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.0', 'Ulcerative (chronic) pancolitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.00', 'Ulcerative (chronic) pancolitis without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.01', 'Ulcerative (chronic) pancolitis with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.011', 'Ulcerative (chronic) pancolitis with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.012', 'Ulcerative (chronic) pancolitis with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.013', 'Ulcerative (chronic) pancolitis with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.014', 'Ulcerative (chronic) pancolitis with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.018', 'Ulcerative (chronic) pancolitis with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.019', 'Ulcerative (chronic) pancolitis with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.2', 'Ulcerative (chronic) proctitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.20', 'Ulcerative (chronic) proctitis without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.21', 'Ulcerative (chronic) proctitis with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.211', 'Ulcerative (chronic) proctitis with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.212', 'Ulcerative (chronic) proctitis with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.213', 'Ulcerative (chronic) proctitis with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.214', 'Ulcerative (chronic) proctitis with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.218', 'Ulcerative (chronic) proctitis with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.219', 'Ulcerative (chronic) proctitis with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.3', 'Ulcerative (chronic) rectosigmoiditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.30', 'Ulcerative (chronic) rectosigmoiditis without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.31', 'Ulcerative (chronic) rectosigmoiditis with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.311', 'Ulcerative (chronic) rectosigmoiditis with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.312', 'Ulcerative (chronic) rectosigmoiditis with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.313', 'Ulcerative (chronic) rectosigmoiditis with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.314', 'Ulcerative (chronic) rectosigmoiditis with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.318', 'Ulcerative (chronic) rectosigmoiditis with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.319', 'Ulcerative (chronic) rectosigmoiditis with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.4', 'Inflammatory polyps of colon')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.40', 'Inflammatory polyps of colon without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.41', 'Inflammatory polyps of colon with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.411', 'Inflammatory polyps of colon with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.412', 'Inflammatory polyps of colon with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.413', 'Inflammatory polyps of colon with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.414', 'Inflammatory polyps of colon with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.418', 'Inflammatory polyps of colon with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.419', 'Inflammatory polyps of colon with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.5', 'Left sided colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.50', 'Left sided colitis without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.51', 'Left sided colitis with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.511', 'Left sided colitis with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.512', 'Left sided colitis with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.513', 'Left sided colitis with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.514', 'Left sided colitis with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.518', 'Left sided colitis with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.519', 'Left sided colitis with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.8', 'Other ulcerative colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.80', 'Other ulcerative colitis without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.81', 'Other ulcerative colitis with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.811', 'Other ulcerative colitis with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.812', 'Other ulcerative colitis with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.813', 'Other ulcerative colitis with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.814', 'Other ulcerative colitis with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.818', 'Other ulcerative colitis with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.819', 'Other ulcerative colitis with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.9', 'Ulcerative colitis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.90', 'Ulcerative colitis, unspecified, without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.91', 'Ulcerative colitis, unspecified, with complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.911', 'Ulcerative colitis, unspecified with rectal bleeding')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.912', 'Ulcerative colitis, unspecified with intestinal obstruction')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.913', 'Ulcerative colitis, unspecified with fistula')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.914', 'Ulcerative colitis, unspecified with abscess')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.918', 'Ulcerative colitis, unspecified with other complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K51.919', 'Ulcerative colitis, unspecified with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.0', 'Gastroenteritis and colitis due to radiation')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.1', 'Toxic gastroenteritis and colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.2', 'Allergic and dietetic gastroenteritis and colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.21', 'Food protein-induced enterocolitis syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.22', 'Food protein-induced enteropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.29', 'Other allergic and dietetic gastroenteritis and colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.3', 'Indeterminate colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.8', 'Other specified noninfective gastroenteritis and colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.81', 'Eosinophilic gastritis or gastroenteritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.82', 'Eosinophilic colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.83', 'Microscopic colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.831', 'Collagenous colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.832', 'Lymphocytic colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.838', 'Other microscopic colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.839', 'Microscopic colitis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.89', 'Other specified noninfective gastroenteritis and colitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'K52.9', 'Noninfective gastroenteritis and colitis, unspecified')
) AS t (system, code, display) ;