create or replace view irae__proc_nephrectomy_sct as select * from (values
('http://snomed.info/sct', '1017216005', 'Laparoscopic total excision of right kidney (procedure)')
,('http://snomed.info/sct', '1017217001', 'Laparoscopic total excision of left kidney (procedure)')
,('http://snomed.info/sct', '108022006', 'Kidney excision (procedure)')
,('http://snomed.info/sct', '116033007', 'Radical nephrectomy (procedure)')
,('http://snomed.info/sct', '116166009', 'Radical nephrectomy AND ipsilateral adrenalectomy (procedure)')
,('http://snomed.info/sct', '12976005', 'Donor nephrectomy (procedure)')
,('http://snomed.info/sct', '175905003', 'Total nephrectomy (procedure)')
,('http://snomed.info/sct', '175911000', 'Live donor nephrectomy (procedure)')
,('http://snomed.info/sct', '1866009', 'Total excision of bilateral kidneys (procedure)')
,('http://snomed.info/sct', '265550007', 'Transplant nephrectomy (procedure)')
,('http://snomed.info/sct', '361249003', 'Nephrectomy with excision of perirenal tissue (procedure)')
,('http://snomed.info/sct', '439235001', 'Laparoscopic radical nephrectomy (procedure)')
,('http://snomed.info/sct', '439964001', 'Laparoscopic excision of kidney and total excision of ureter (procedure)')
,('http://snomed.info/sct', '440446009', 'Laparoscopic excision of kidney and partial excision of ureter (procedure)')
,('http://snomed.info/sct', '442919002', 'Adrenal sparing radical nephrectomy (procedure)')
,('http://snomed.info/sct', '444083005', 'Total excision of left kidney (procedure)')
,('http://snomed.info/sct', '446296004', 'Laparoscopic total excision of kidney (procedure)')
,('http://snomed.info/sct', '6561000179108', 'Open nephrectomy from live donor (procedure)')
,('http://snomed.info/sct', '698869007', 'Laparoscopic bilateral total nephrectomy (procedure)')
,('http://snomed.info/sct', '708908003', 'Laparoscopic live donor nephrectomy (procedure)')
,('http://snomed.info/sct', '712998006', 'Laparoscopic radical nephrectomy using robotic assistance (procedure)')
,('http://snomed.info/sct', '714031000', 'Single port laparoscopic nephrectomy (procedure)')
,('http://snomed.info/sct', '765472003', 'Excision of left kidney (procedure)')
,('http://snomed.info/sct', '765473008', 'Excision of right kidney (procedure)')
,('http://snomed.info/sct', '88930008', 'Total nephrectomy in recipient (procedure)')
) AS t (system, code, display) ;