create or replace view irae__lab_autoimmune_t3 as select * from (values
('http://loinc.org', '14928-6', 'Triiodothyronine (T3) Free [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '14930-2', 'Triiodothyronine (T3) [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '26879-7', 'Triiodothyronine (T3) [Mass/volume] in Saliva (oral fluid)')
,('http://loinc.org', '29239-1', 'Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma by Dialysis')
,('http://loinc.org', '3051-0', 'Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '3053-6', 'Triiodothyronine (T3) [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '3054-4', 'Triiodothyronine (T3).true [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '35230-2', 'Triiodothyronine (T3) Free [Mass or Moles/volume] in Serum or Plasma')
,('http://loinc.org', '35231-0', 'Triiodothyronine (T3) [Mass or Moles/volume] in Serum or Plasma')
,('http://loinc.org', '40327-9', 'Triiodothyronine (T3) Free [Moles/volume] in Serum or Plasma --pre dose triple bolus')
,('http://loinc.org', '58840-0', 'Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '70152-4', 'Triiodothyronine (T3)/Thyroxine (T4) [Mass Ratio] in Serum or Plasma')
,('http://loinc.org', '83124-8', 'Triiodothyronine (T3) [Mass/volume] in Serum or Plasma by Immunoassay')
,('http://loinc.org', '83125-5', 'Triiodothyronine (T3) [Moles/volume] in Serum or Plasma by Immunoassay')
,('http://loinc.org', '83126-3', 'Triiodothyronine (T3) Free [Moles/volume] in Serum or Plasma by Immunoassay')
,('http://loinc.org', '83127-1', 'Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma by Immunoassay')
,('http://loinc.org', '97164-8', 'Triiodothyronine (T3) [Mass/time] in 24 hour Urine')
,('http://loinc.org', '97165-5', 'Triiodothyronine (T3) [Moles/time] in 24 hour Urine')
,('http://loinc.org', 'LP15921-7', 'Triiodothyronine resin uptake (T3RU)')
,('http://loinc.org', 'LP15922-5', 'Triiodothyronine')
,('http://loinc.org', 'LP307573-8', 'Triiodothyronine/Thyroxine')
) AS t (system, code, display) ;