create or replace view irae__rx_diuretics_potassium as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '104230', 'spironolactone 1 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104231', 'spironolactone 2 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104232', 'spironolactone 5 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104233', 'spironolactone 10 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104245', 'benzthiazide 25 MG / triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104248', 'chlorthalidone 50 MG / triamterene 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198222', 'spironolactone 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198223', 'spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198224', 'hydrochlorothiazide 25 MG / spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198225', 'hydrochlorothiazide 50 MG / spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198312', 'triamterene 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198313', 'triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198314', 'hydrochlorothiazide 25 MG / triamterene 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198316', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '246399', 'furosemide 20 MG / spironolactone 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250376', 'hydroflumethiazide 25 MG / spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250377', 'hydroflumethiazide 50 MG / spironolactone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250708', 'furosemide 40 MG / triamterene 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310812', 'hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310818', 'hydrochlorothiazide 50 MG / triamterene 75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313096', 'spironolactone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314029', 'hydrochlorothiazide 25 MG / triamterene 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351256', 'eplerenone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351257', 'eplerenone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351258', 'eplerenone 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977880', 'amiloride hydrochloride 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977883', 'amiloride hydrochloride 5 MG / hydrochlorothiazide 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977887', 'amiloride hydrochloride 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977890', 'amiloride hydrochloride 10 MG / furosemide 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977907', 'amiloride hydrochloride 2.5 MG / cyclopenthiazide 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977920', 'amiloride hydrochloride 2.5 MG / atenolol 50 MG / hydrochlorothiazide 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977945', 'amiloride hydrochloride 2.5 MG / furosemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977949', 'amiloride hydrochloride 2.5 MG / hydrochlorothiazide 25 MG / timolol maleate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977950', 'amiloride hydrochloride 2.5 MG / hydrochlorothiazide 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977951', 'amiloride hydrochloride 5 MG / bumetanide 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977959', 'amiloride hydrochloride 5 MG / furosemide 40 MG Oral Tablet')
) AS t (system, code, display) ;