create or replace view irae__dx_autoimmune_arthritis_ra as select * from (values
('http://snomed.info/sct', '1073601000119101', 'Seropositive rheumatoid arthritis of joint of right foot (disorder)')
,('http://snomed.info/sct', '1073611000119103', 'Seropositive rheumatoid arthritis of joint of left foot (disorder)')
,('http://snomed.info/sct', '1073681000119109', 'Rheumatoid arthritis of left ankle (disorder)')
,('http://snomed.info/sct', '1073691000119107', 'Rheumatoid arthritis of left elbow (disorder)')
,('http://snomed.info/sct', '1073701000119107', 'Rheumatoid arthritis of left foot (disorder)')
,('http://snomed.info/sct', '1073711000119105', 'Rheumatoid arthritis of left hand (disorder)')
,('http://snomed.info/sct', '1073721000119103', 'Rheumatoid arthritis of left hip (disorder)')
,('http://snomed.info/sct', '1073731000119100', 'Rheumatoid arthritis of left knee (disorder)')
,('http://snomed.info/sct', '1073741000119109', 'Rheumatoid arthritis of left shoulder (disorder)')
,('http://snomed.info/sct', '1073751000119106', 'Rheumatoid arthritis of left wrist (disorder)')
,('http://snomed.info/sct', '1073761000119108', 'Rheumatoid arthritis of right ankle (disorder)')
,('http://snomed.info/sct', '1073771000119102', 'Rheumatoid arthritis of right elbow (disorder)')
,('http://snomed.info/sct', '1073781000119104', 'Rheumatoid arthritis of right foot (disorder)')
,('http://snomed.info/sct', '1073791000119101', 'Rheumatoid arthritis of right hand (disorder)')
,('http://snomed.info/sct', '1073801000119100', 'Rheumatoid arthritis of right hip (disorder)')
,('http://snomed.info/sct', '1073811000119102', 'Rheumatoid arthritis of right knee (disorder)')
,('http://snomed.info/sct', '1073821000119109', 'Rheumatoid arthritis of right shoulder (disorder)')
,('http://snomed.info/sct', '1073831000119107', 'Rheumatoid arthritis of right wrist (disorder)')
,('http://snomed.info/sct', '11055151000119108', 'Seropositive rheumatoid arthritis of multiple joints (disorder)')
,('http://snomed.info/sct', '1149218009', 'Rheumatoid arthritis with isolated nailfold vasculitis (disorder)')
,('http://snomed.info/sct', '1149219001', 'Rheumatoid arthritis with systemic vasculitis (disorder)')
,('http://snomed.info/sct', '1162303002', 'Seronegative rheumatoid arthritis with erosion of joint (disorder)')
,('http://snomed.info/sct', '1162313005', 'Rheumatoid factor and cyclic citrullinated peptide antibody positive rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '1162319009', 'Rheumatoid factor and cyclic citrullinated peptide antibody positive erosive rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '1162336001', 'Cyclic citrullinated peptide antibody positive erosive rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '1162362005', 'Felty syndrome with seronegative erosive rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '1162364006', 'Felty syndrome with seronegative rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '1162677006', 'Rheumatoid arthritis with rheumatoid lung disease (disorder)')
,('http://snomed.info/sct', '1222679006', 'Autoimmune interstitial lung disease, arthritis syndrome (disorder)')
,('http://snomed.info/sct', '1290768009', 'Seronegative rheumatoid arthritis of joint of shoulder region (disorder)')
,('http://snomed.info/sct', '129563009', 'Rheumatoid arthritis with osteoperiostitis (disorder)')
,('http://snomed.info/sct', '143441000119108', 'Rheumatoid arthritis in remission (disorder)')
,('http://snomed.info/sct', '15685921000119102', 'Rheumatoid arthritis of bilateral temporomandibular joints (disorder)')
,('http://snomed.info/sct', '15685961000119107', 'Rheumatoid arthritis of right temporomandibular joint (disorder)')
,('http://snomed.info/sct', '15686001000119104', 'Rheumatoid arthritis of left temporomandibular joint (disorder)')
,('http://snomed.info/sct', '15686241000119106', 'Rheumatoid arthritis of bilateral glenohumeral joints (disorder)')
,('http://snomed.info/sct', '15686281000119101', 'Rheumatoid arthritis of bilateral feet (disorder)')
,('http://snomed.info/sct', '15686321000119106', 'Rheumatoid arthritis of bilateral elbows (disorder)')
,('http://snomed.info/sct', '15687201000119107', 'Rheumatoid arthritis of bilateral knees (disorder)')
,('http://snomed.info/sct', '15687321000119109', 'Rheumatoid arthritis of bilateral hands (disorder)')
,('http://snomed.info/sct', '15687841000119108', 'Rheumatoid arthritis of bilateral hips (disorder)')
,('http://snomed.info/sct', '15691081000119100', 'Seronegative rheumatoid arthritis of joint of bilateral feet (disorder)')
,('http://snomed.info/sct', '15691121000119103', 'Seronegative rheumatoid arthritis of joint of bilateral elbows (disorder)')
,('http://snomed.info/sct', '15691161000119108', 'Seronegative rheumatoid arthritis of bilateral hands (disorder)')
,('http://snomed.info/sct', '15691241000119101', 'Seronegative rheumatoid arthritis of bilateral knees (disorder)')
,('http://snomed.info/sct', '15691281000119106', 'Seronegative rheumatoid arthritis of joint of bilateral shoulder regions (disorder)')
,('http://snomed.info/sct', '15691321000119101', 'Seronegative rheumatoid arthritis of bilateral wrists (disorder)')
,('http://snomed.info/sct', '15691361000119106', 'Seronegative rheumatoid arthritis of bilateral hip joints (disorder)')
,('http://snomed.info/sct', '15691721000119102', 'Rheumatoid arthritis of bilateral ankles (disorder)')
,('http://snomed.info/sct', '15691761000119107', 'Rheumatoid arthritis of bilateral wrists (disorder)')
,('http://snomed.info/sct', '15691801000119104', 'Seropositive rheumatoid arthritis of bilateral hands (disorder)')
,('http://snomed.info/sct', '15691841000119102', 'Seropositive rheumatoid arthritis of joint of bilateral shoulder regions (disorder)')
,('http://snomed.info/sct', '15691881000119107', 'Seropositive rheumatoid arthritis of bilateral knees (disorder)')
,('http://snomed.info/sct', '15691921000119100', 'Seropositive rheumatoid arthritis of bilateral hip joints (disorder)')
,('http://snomed.info/sct', '15691961000119105', 'Seropositive rheumatoid arthritis of joint of bilateral ankles (disorder)')
,('http://snomed.info/sct', '15692001000119101', 'Seropositive rheumatoid arthritis of joint of bilateral elbows (disorder)')
,('http://snomed.info/sct', '15692041000119104', 'Seropositive rheumatoid arthritis of joint of bilateral wrist regions (disorder)')
,('http://snomed.info/sct', '16050071000119108', 'Seropositive rheumatoid arthritis of bilateral feet (disorder)')
,('http://snomed.info/sct', '16606681000119101', 'Seronegative rheumatoid arthritis in remission (disorder)')
,('http://snomed.info/sct', '16606721000119107', 'Seropositive rheumatoid arthritis in remission (disorder)')
,('http://snomed.info/sct', '201764007', 'Rheumatoid arthritis of cervical spine (disorder)')
,('http://snomed.info/sct', '201766009', 'Rheumatoid arthritis of shoulder (disorder)')
,('http://snomed.info/sct', '201767000', 'Rheumatoid arthritis of sternoclavicular joint (disorder)')
,('http://snomed.info/sct', '201768005', 'Rheumatoid arthritis of acromioclavicular joint (disorder)')
,('http://snomed.info/sct', '201769002', 'Rheumatoid arthritis of elbow (disorder)')
,('http://snomed.info/sct', '201770001', 'Rheumatoid arthritis of distal radioulnar joint (disorder)')
,('http://snomed.info/sct', '201771002', 'Rheumatoid arthritis of wrist (disorder)')
,('http://snomed.info/sct', '201772009', 'Rheumatoid arthritis of metacarpophalangeal joint (disorder)')
,('http://snomed.info/sct', '201773004', 'Rheumatoid arthritis of proximal interphalangeal joint of finger (disorder)')
,('http://snomed.info/sct', '201774005', 'Rheumatoid arthritis of distal interphalangeal joint of finger (disorder)')
,('http://snomed.info/sct', '201775006', 'Rheumatoid arthritis of hip (disorder)')
,('http://snomed.info/sct', '201776007', 'Rheumatoid arthritis of sacroiliac joint (disorder)')
,('http://snomed.info/sct', '201777003', 'Rheumatoid arthritis of knee (disorder)')
,('http://snomed.info/sct', '201778008', 'Rheumatoid arthritis of tibiofibular joint (disorder)')
,('http://snomed.info/sct', '201779000', 'Rheumatoid arthritis of ankle (disorder)')
,('http://snomed.info/sct', '201780002', 'Rheumatoid arthritis of subtalar joint (disorder)')
,('http://snomed.info/sct', '201781003', 'Rheumatoid arthritis of talonavicular joint (disorder)')
,('http://snomed.info/sct', '201783000', 'Rheumatoid arthritis of first metatarsophalangeal joint (disorder)')
,('http://snomed.info/sct', '201784006', 'Rheumatoid arthritis of lesser metatarsophalangeal joint (disorder)')
,('http://snomed.info/sct', '201785007', 'Rheumatoid arthritis of interphalangeal joint of toe (disorder)')
,('http://snomed.info/sct', '201791009', 'Flare of rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '239791005', 'Seropositive rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '239792003', 'Seronegative rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '239943002', 'Rheumatoid arthritis with necrotizing vasculitis (disorder)')
,('http://snomed.info/sct', '287006005', 'Rheumatoid arthritis of multiple joints (disorder)')
,('http://snomed.info/sct', '287007001', 'Rheumatoid arthritis of hand joint (disorder)')
,('http://snomed.info/sct', '287008006', 'Rheumatoid arthritis of ankle and/or foot (disorder)')
,('http://snomed.info/sct', '28880005', 'Rheumatoid arthritis with carditis (disorder)')
,('http://snomed.info/sct', '299271000119109', 'Seronegative rheumatoid arthritis of joint of elbow (disorder)')
,('http://snomed.info/sct', '308143008', 'Seropositive erosive rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '318841000119100', 'Seropositive rheumatoid arthritis of joint of left ankle (disorder)')
,('http://snomed.info/sct', '318851000119103', 'Seropositive rheumatoid arthritis of joint of left elbow (disorder)')
,('http://snomed.info/sct', '318861000119101', 'Seropositive rheumatoid arthritis of left hand (disorder)')
,('http://snomed.info/sct', '318871000119107', 'Seropositive rheumatoid arthritis of left hip (disorder)')
,('http://snomed.info/sct', '318881000119105', 'Seropositive rheumatoid arthritis of left knee (disorder)')
,('http://snomed.info/sct', '318891000119108', 'Seropositive rheumatoid arthritis of joint of left shoulder region (disorder)')
,('http://snomed.info/sct', '318901000119107', 'Seropositive rheumatoid arthritis of joint of left wrist region (disorder)')
,('http://snomed.info/sct', '318911000119105', 'Seropositive rheumatoid arthritis of joint of right ankle (disorder)')
,('http://snomed.info/sct', '318921000119103', 'Seropositive rheumatoid arthritis of joint of right elbow (disorder)')
,('http://snomed.info/sct', '318931000119100', 'Seropositive rheumatoid arthritis of right hand (disorder)')
,('http://snomed.info/sct', '318941000119109', 'Seropositive rheumatoid arthritis of right hip (disorder)')
,('http://snomed.info/sct', '318951000119106', 'Seropositive rheumatoid arthritis of right knee (disorder)')
,('http://snomed.info/sct', '318961000119108', 'Seropositive rheumatoid arthritis of joint of right shoulder region (disorder)')
,('http://snomed.info/sct', '318971000119102', 'Seropositive rheumatoid arthritis of joint of right wrist region (disorder)')
,('http://snomed.info/sct', '319011000119103', 'Seronegative rheumatoid arthritis of joint of left ankle (disorder)')
,('http://snomed.info/sct', '319021000119105', 'Seronegative rheumatoid arthritis of joint of left elbow (disorder)')
,('http://snomed.info/sct', '319031000119108', 'Seronegative rheumatoid arthritis of left hand (disorder)')
,('http://snomed.info/sct', '319041000119104', 'Seronegative rheumatoid arthritis of joint of left hip (disorder)')
,('http://snomed.info/sct', '319051000119102', 'Seronegative rheumatoid arthritis of left knee joint (disorder)')
,('http://snomed.info/sct', '319061000119100', 'Seronegative rheumatoid arthritis of joint of left shoulder region (disorder)')
,('http://snomed.info/sct', '319071000119106', 'Seronegative rheumatoid arthritis of joint of left wrist region (disorder)')
,('http://snomed.info/sct', '319081000119109', 'Seronegative rheumatoid arthritis of multiple joints (disorder)')
,('http://snomed.info/sct', '319091000119107', 'Seronegative rheumatoid arthritis of joint of right ankle (disorder)')
,('http://snomed.info/sct', '319101000119102', 'Seronegative rheumatoid arthritis of joint of right elbow (disorder)')
,('http://snomed.info/sct', '319111000119104', 'Seronegative rheumatoid arthritis of right hand (disorder)')
,('http://snomed.info/sct', '319121000119106', 'Seronegative rheumatoid arthritis of joint of right hip (disorder)')
,('http://snomed.info/sct', '319131000119109', 'Seronegative rheumatoid arthritis of right knee joint (disorder)')
,('http://snomed.info/sct', '319141000119100', 'Seronegative rheumatoid arthritis of joint of right shoulder region (disorder)')
,('http://snomed.info/sct', '319151000119103', 'Seronegative rheumatoid arthritis of joint of right wrist region (disorder)')
,('http://snomed.info/sct', '38877003', 'Rheumatoid arthritis with aortitis (disorder)')
,('http://snomed.info/sct', '398640008', 'Rheumatoid arthritis with pneumoconiosis (disorder)')
,('http://snomed.info/sct', '399923009', 'Rheumatoid arthritis with arteritis (disorder)')
,('http://snomed.info/sct', '400054000', 'Rheumatoid arthritis with vasculitis (disorder)')
,('http://snomed.info/sct', '402432002', 'Rheumatoid arthritis with neutrophilic dermatitis (disorder)')
,('http://snomed.info/sct', '402433007', 'Rheumatoid arthritis with nailfold and finger-pulp infarcts (disorder)')
,('http://snomed.info/sct', '427770001', 'Rheumatoid arthritis of temporomandibular joint (disorder)')
,('http://snomed.info/sct', '429192004', 'Rheumatoid arthritis of foot (disorder)')
,('http://snomed.info/sct', '459921000124108', 'Seropositive rheumatoid arthritis of shoulder joint (disorder)')
,('http://snomed.info/sct', '59165007', 'Rheumatoid arthritis with scleritis (disorder)')
,('http://snomed.info/sct', '69896004', 'Rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '735599007', 'Rheumatoid arthritis with erosion of joint (disorder)')
,('http://snomed.info/sct', '7607008', 'Rheumatoid arthritis with pericarditis (disorder)')
,('http://snomed.info/sct', '77522006', 'Rheumatoid arthritis with episcleritis (disorder)')
,('http://snomed.info/sct', '781206002', 'Rheumatoid arthritis of joint of spine (disorder)')
,('http://snomed.info/sct', '86219005', 'Uveitis-rheumatoid arthritis syndrome (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05', 'Rheumatoid arthritis with rheumatoid factor')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.0', 'Feltys syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.00', 'Feltys syndrome, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.01', 'Feltys syndrome, shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.011', 'Feltys syndrome, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.012', 'Feltys syndrome, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.019', 'Feltys syndrome, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.02', 'Feltys syndrome, elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.021', 'Feltys syndrome, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.022', 'Feltys syndrome, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.029', 'Feltys syndrome, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.03', 'Feltys syndrome, wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.031', 'Feltys syndrome, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.032', 'Feltys syndrome, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.039', 'Feltys syndrome, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.04', 'Feltys syndrome, hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.041', 'Feltys syndrome, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.042', 'Feltys syndrome, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.049', 'Feltys syndrome, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.05', 'Feltys syndrome, hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.051', 'Feltys syndrome, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.052', 'Feltys syndrome, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.059', 'Feltys syndrome, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.06', 'Feltys syndrome, knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.061', 'Feltys syndrome, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.062', 'Feltys syndrome, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.069', 'Feltys syndrome, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.07', 'Feltys syndrome, ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.071', 'Feltys syndrome, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.072', 'Feltys syndrome, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.079', 'Feltys syndrome, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.09', 'Feltys syndrome, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.1', 'Rheumatoid lung disease with rheumatoid arthritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.10', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.11', 'Rheumatoid lung disease with rheumatoid arthritis of shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.111', 'Rheumatoid lung disease with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.112', 'Rheumatoid lung disease with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.119', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.12', 'Rheumatoid lung disease with rheumatoid arthritis of elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.121', 'Rheumatoid lung disease with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.122', 'Rheumatoid lung disease with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.129', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.13', 'Rheumatoid lung disease with rheumatoid arthritis of wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.131', 'Rheumatoid lung disease with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.132', 'Rheumatoid lung disease with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.139', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.14', 'Rheumatoid lung disease with rheumatoid arthritis of hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.141', 'Rheumatoid lung disease with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.142', 'Rheumatoid lung disease with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.149', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.15', 'Rheumatoid lung disease with rheumatoid arthritis of hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.151', 'Rheumatoid lung disease with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.152', 'Rheumatoid lung disease with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.159', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.16', 'Rheumatoid lung disease with rheumatoid arthritis of knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.161', 'Rheumatoid lung disease with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.162', 'Rheumatoid lung disease with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.169', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.17', 'Rheumatoid lung disease with rheumatoid arthritis of ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.171', 'Rheumatoid lung disease with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.172', 'Rheumatoid lung disease with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.179', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.19', 'Rheumatoid lung disease with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.2', 'Rheumatoid vasculitis with rheumatoid arthritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.20', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.21', 'Rheumatoid vasculitis with rheumatoid arthritis of shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.211', 'Rheumatoid vasculitis with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.212', 'Rheumatoid vasculitis with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.219', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.22', 'Rheumatoid vasculitis with rheumatoid arthritis of elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.221', 'Rheumatoid vasculitis with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.222', 'Rheumatoid vasculitis with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.229', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.23', 'Rheumatoid vasculitis with rheumatoid arthritis of wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.231', 'Rheumatoid vasculitis with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.232', 'Rheumatoid vasculitis with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.239', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.24', 'Rheumatoid vasculitis with rheumatoid arthritis of hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.241', 'Rheumatoid vasculitis with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.242', 'Rheumatoid vasculitis with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.249', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.25', 'Rheumatoid vasculitis with rheumatoid arthritis of hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.251', 'Rheumatoid vasculitis with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.252', 'Rheumatoid vasculitis with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.259', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.26', 'Rheumatoid vasculitis with rheumatoid arthritis of knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.261', 'Rheumatoid vasculitis with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.262', 'Rheumatoid vasculitis with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.269', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.27', 'Rheumatoid vasculitis with rheumatoid arthritis of ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.271', 'Rheumatoid vasculitis with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.272', 'Rheumatoid vasculitis with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.279', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.29', 'Rheumatoid vasculitis with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.3', 'Rheumatoid heart disease with rheumatoid arthritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.30', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.31', 'Rheumatoid heart disease with rheumatoid arthritis of shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.311', 'Rheumatoid heart disease with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.312', 'Rheumatoid heart disease with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.319', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.32', 'Rheumatoid heart disease with rheumatoid arthritis of elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.321', 'Rheumatoid heart disease with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.322', 'Rheumatoid heart disease with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.329', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.33', 'Rheumatoid heart disease with rheumatoid arthritis of wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.331', 'Rheumatoid heart disease with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.332', 'Rheumatoid heart disease with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.339', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.34', 'Rheumatoid heart disease with rheumatoid arthritis of hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.341', 'Rheumatoid heart disease with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.342', 'Rheumatoid heart disease with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.349', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.35', 'Rheumatoid heart disease with rheumatoid arthritis of hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.351', 'Rheumatoid heart disease with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.352', 'Rheumatoid heart disease with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.359', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.36', 'Rheumatoid heart disease with rheumatoid arthritis of knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.361', 'Rheumatoid heart disease with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.362', 'Rheumatoid heart disease with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.369', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.37', 'Rheumatoid heart disease with rheumatoid arthritis of ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.371', 'Rheumatoid heart disease with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.372', 'Rheumatoid heart disease with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.379', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.39', 'Rheumatoid heart disease with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.4', 'Rheumatoid myopathy with rheumatoid arthritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.40', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.41', 'Rheumatoid myopathy with rheumatoid arthritis of shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.411', 'Rheumatoid myopathy with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.412', 'Rheumatoid myopathy with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.419', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.42', 'Rheumatoid myopathy with rheumatoid arthritis of elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.421', 'Rheumatoid myopathy with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.422', 'Rheumatoid myopathy with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.429', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.43', 'Rheumatoid myopathy with rheumatoid arthritis of wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.431', 'Rheumatoid myopathy with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.432', 'Rheumatoid myopathy with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.439', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.44', 'Rheumatoid myopathy with rheumatoid arthritis of hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.441', 'Rheumatoid myopathy with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.442', 'Rheumatoid myopathy with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.449', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.45', 'Rheumatoid myopathy with rheumatoid arthritis of hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.451', 'Rheumatoid myopathy with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.452', 'Rheumatoid myopathy with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.459', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.46', 'Rheumatoid myopathy with rheumatoid arthritis of knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.461', 'Rheumatoid myopathy with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.462', 'Rheumatoid myopathy with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.469', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.47', 'Rheumatoid myopathy with rheumatoid arthritis of ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.471', 'Rheumatoid myopathy with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.472', 'Rheumatoid myopathy with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.479', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.49', 'Rheumatoid myopathy with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.5', 'Rheumatoid polyneuropathy with rheumatoid arthritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.50', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.51', 'Rheumatoid polyneuropathy with rheumatoid arthritis of shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.511', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.512', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.519', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.52', 'Rheumatoid polyneuropathy with rheumatoid arthritis of elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.521', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.522', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.529', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.53', 'Rheumatoid polyneuropathy with rheumatoid arthritis of wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.531', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.532', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.539', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.54', 'Rheumatoid polyneuropathy with rheumatoid arthritis of hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.541', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.542', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.549', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.55', 'Rheumatoid polyneuropathy with rheumatoid arthritis of hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.551', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.552', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.559', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.56', 'Rheumatoid polyneuropathy with rheumatoid arthritis of knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.561', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.562', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.569', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.57', 'Rheumatoid polyneuropathy with rheumatoid arthritis of ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.571', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.572', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.579', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.59', 'Rheumatoid polyneuropathy with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.6', 'Rheumatoid arthritis with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.60', 'Rheumatoid arthritis of unspecified site with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.61', 'Rheumatoid arthritis of shoulder with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.611', 'Rheumatoid arthritis of right shoulder with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.612', 'Rheumatoid arthritis of left shoulder with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.619', 'Rheumatoid arthritis of unspecified shoulder with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.62', 'Rheumatoid arthritis of elbow with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.621', 'Rheumatoid arthritis of right elbow with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.622', 'Rheumatoid arthritis of left elbow with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.629', 'Rheumatoid arthritis of unspecified elbow with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.63', 'Rheumatoid arthritis of wrist with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.631', 'Rheumatoid arthritis of right wrist with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.632', 'Rheumatoid arthritis of left wrist with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.639', 'Rheumatoid arthritis of unspecified wrist with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.64', 'Rheumatoid arthritis of hand with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.641', 'Rheumatoid arthritis of right hand with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.642', 'Rheumatoid arthritis of left hand with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.649', 'Rheumatoid arthritis of unspecified hand with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.65', 'Rheumatoid arthritis of hip with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.651', 'Rheumatoid arthritis of right hip with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.652', 'Rheumatoid arthritis of left hip with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.659', 'Rheumatoid arthritis of unspecified hip with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.66', 'Rheumatoid arthritis of knee with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.661', 'Rheumatoid arthritis of right knee with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.662', 'Rheumatoid arthritis of left knee with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.669', 'Rheumatoid arthritis of unspecified knee with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.67', 'Rheumatoid arthritis of ankle and foot with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.671', 'Rheumatoid arthritis of right ankle and foot with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.672', 'Rheumatoid arthritis of left ankle and foot with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.679', 'Rheumatoid arthritis of unspecified ankle and foot with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.69', 'Rheumatoid arthritis of multiple sites with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.7', 'Rheumatoid arthritis with rheumatoid factor without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.70', 'Rheumatoid arthritis with rheumatoid factor of unspecified site without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.71', 'Rheumatoid arthritis with rheumatoid factor of shoulder without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.711', 'Rheumatoid arthritis with rheumatoid factor of right shoulder without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.712', 'Rheumatoid arthritis with rheumatoid factor of left shoulder without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.719', 'Rheumatoid arthritis with rheumatoid factor of unspecified shoulder without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.72', 'Rheumatoid arthritis with rheumatoid factor of elbow without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.721', 'Rheumatoid arthritis with rheumatoid factor of right elbow without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.722', 'Rheumatoid arthritis with rheumatoid factor of left elbow without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.729', 'Rheumatoid arthritis with rheumatoid factor of unspecified elbow without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.73', 'Rheumatoid arthritis with rheumatoid factor of wrist without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.731', 'Rheumatoid arthritis with rheumatoid factor of right wrist without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.732', 'Rheumatoid arthritis with rheumatoid factor of left wrist without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.739', 'Rheumatoid arthritis with rheumatoid factor of unspecified wrist without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.74', 'Rheumatoid arthritis with rheumatoid factor of hand without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.741', 'Rheumatoid arthritis with rheumatoid factor of right hand without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.742', 'Rheumatoid arthritis with rheumatoid factor of left hand without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.749', 'Rheumatoid arthritis with rheumatoid factor of unspecified hand without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.75', 'Rheumatoid arthritis with rheumatoid factor of hip without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.751', 'Rheumatoid arthritis with rheumatoid factor of right hip without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.752', 'Rheumatoid arthritis with rheumatoid factor of left hip without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.759', 'Rheumatoid arthritis with rheumatoid factor of unspecified hip without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.76', 'Rheumatoid arthritis with rheumatoid factor of knee without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.761', 'Rheumatoid arthritis with rheumatoid factor of right knee without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.762', 'Rheumatoid arthritis with rheumatoid factor of left knee without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.769', 'Rheumatoid arthritis with rheumatoid factor of unspecified knee without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.77', 'Rheumatoid arthritis with rheumatoid factor of ankle and foot without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.771', 'Rheumatoid arthritis with rheumatoid factor of right ankle and foot without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.772', 'Rheumatoid arthritis with rheumatoid factor of left ankle and foot without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.779', 'Rheumatoid arthritis with rheumatoid factor of unspecified ankle and foot without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.79', 'Rheumatoid arthritis with rheumatoid factor of multiple sites without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.7A', 'Rheumatoid arthritis with rheumatoid factor of other specified site without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.8', 'Other rheumatoid arthritis with rheumatoid factor')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.80', 'Other rheumatoid arthritis with rheumatoid factor of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.81', 'Other rheumatoid arthritis with rheumatoid factor of shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.811', 'Other rheumatoid arthritis with rheumatoid factor of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.812', 'Other rheumatoid arthritis with rheumatoid factor of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.819', 'Other rheumatoid arthritis with rheumatoid factor of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.82', 'Other rheumatoid arthritis with rheumatoid factor of elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.821', 'Other rheumatoid arthritis with rheumatoid factor of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.822', 'Other rheumatoid arthritis with rheumatoid factor of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.829', 'Other rheumatoid arthritis with rheumatoid factor of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.83', 'Other rheumatoid arthritis with rheumatoid factor of wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.831', 'Other rheumatoid arthritis with rheumatoid factor of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.832', 'Other rheumatoid arthritis with rheumatoid factor of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.839', 'Other rheumatoid arthritis with rheumatoid factor of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.84', 'Other rheumatoid arthritis with rheumatoid factor of hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.841', 'Other rheumatoid arthritis with rheumatoid factor of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.842', 'Other rheumatoid arthritis with rheumatoid factor of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.849', 'Other rheumatoid arthritis with rheumatoid factor of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.85', 'Other rheumatoid arthritis with rheumatoid factor of hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.851', 'Other rheumatoid arthritis with rheumatoid factor of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.852', 'Other rheumatoid arthritis with rheumatoid factor of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.859', 'Other rheumatoid arthritis with rheumatoid factor of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.86', 'Other rheumatoid arthritis with rheumatoid factor of knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.861', 'Other rheumatoid arthritis with rheumatoid factor of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.862', 'Other rheumatoid arthritis with rheumatoid factor of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.869', 'Other rheumatoid arthritis with rheumatoid factor of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.87', 'Other rheumatoid arthritis with rheumatoid factor of ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.871', 'Other rheumatoid arthritis with rheumatoid factor of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.872', 'Other rheumatoid arthritis with rheumatoid factor of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.879', 'Other rheumatoid arthritis with rheumatoid factor of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.89', 'Other rheumatoid arthritis with rheumatoid factor of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.8A', 'Other rheumatoid arthritis with rheumatoid factor of other specified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.9', 'Rheumatoid arthritis with rheumatoid factor, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06', 'Other rheumatoid arthritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.0', 'Rheumatoid arthritis without rheumatoid factor')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.00', 'Rheumatoid arthritis without rheumatoid factor, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.01', 'Rheumatoid arthritis without rheumatoid factor, shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.011', 'Rheumatoid arthritis without rheumatoid factor, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.012', 'Rheumatoid arthritis without rheumatoid factor, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.019', 'Rheumatoid arthritis without rheumatoid factor, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.02', 'Rheumatoid arthritis without rheumatoid factor, elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.021', 'Rheumatoid arthritis without rheumatoid factor, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.022', 'Rheumatoid arthritis without rheumatoid factor, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.029', 'Rheumatoid arthritis without rheumatoid factor, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.03', 'Rheumatoid arthritis without rheumatoid factor, wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.031', 'Rheumatoid arthritis without rheumatoid factor, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.032', 'Rheumatoid arthritis without rheumatoid factor, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.039', 'Rheumatoid arthritis without rheumatoid factor, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.04', 'Rheumatoid arthritis without rheumatoid factor, hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.041', 'Rheumatoid arthritis without rheumatoid factor, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.042', 'Rheumatoid arthritis without rheumatoid factor, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.049', 'Rheumatoid arthritis without rheumatoid factor, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.05', 'Rheumatoid arthritis without rheumatoid factor, hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.051', 'Rheumatoid arthritis without rheumatoid factor, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.052', 'Rheumatoid arthritis without rheumatoid factor, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.059', 'Rheumatoid arthritis without rheumatoid factor, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.06', 'Rheumatoid arthritis without rheumatoid factor, knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.061', 'Rheumatoid arthritis without rheumatoid factor, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.062', 'Rheumatoid arthritis without rheumatoid factor, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.069', 'Rheumatoid arthritis without rheumatoid factor, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.07', 'Rheumatoid arthritis without rheumatoid factor, ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.071', 'Rheumatoid arthritis without rheumatoid factor, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.072', 'Rheumatoid arthritis without rheumatoid factor, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.079', 'Rheumatoid arthritis without rheumatoid factor, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.08', 'Rheumatoid arthritis without rheumatoid factor, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.09', 'Rheumatoid arthritis without rheumatoid factor, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.0A', 'Rheumatoid arthritis without rheumatoid factor, other specified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.1', 'Adult-onset Stills disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.2', 'Rheumatoid bursitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.20', 'Rheumatoid bursitis, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.21', 'Rheumatoid bursitis, shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.211', 'Rheumatoid bursitis, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.212', 'Rheumatoid bursitis, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.219', 'Rheumatoid bursitis, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.22', 'Rheumatoid bursitis, elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.221', 'Rheumatoid bursitis, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.222', 'Rheumatoid bursitis, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.229', 'Rheumatoid bursitis, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.23', 'Rheumatoid bursitis, wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.231', 'Rheumatoid bursitis, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.232', 'Rheumatoid bursitis, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.239', 'Rheumatoid bursitis, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.24', 'Rheumatoid bursitis, hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.241', 'Rheumatoid bursitis, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.242', 'Rheumatoid bursitis, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.249', 'Rheumatoid bursitis, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.25', 'Rheumatoid bursitis, hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.251', 'Rheumatoid bursitis, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.252', 'Rheumatoid bursitis, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.259', 'Rheumatoid bursitis, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.26', 'Rheumatoid bursitis, knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.261', 'Rheumatoid bursitis, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.262', 'Rheumatoid bursitis, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.269', 'Rheumatoid bursitis, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.27', 'Rheumatoid bursitis, ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.271', 'Rheumatoid bursitis, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.272', 'Rheumatoid bursitis, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.279', 'Rheumatoid bursitis, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.28', 'Rheumatoid bursitis, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.29', 'Rheumatoid bursitis, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.3', 'Rheumatoid nodule')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.30', 'Rheumatoid nodule, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.31', 'Rheumatoid nodule, shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.311', 'Rheumatoid nodule, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.312', 'Rheumatoid nodule, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.319', 'Rheumatoid nodule, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.32', 'Rheumatoid nodule, elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.321', 'Rheumatoid nodule, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.322', 'Rheumatoid nodule, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.329', 'Rheumatoid nodule, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.33', 'Rheumatoid nodule, wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.331', 'Rheumatoid nodule, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.332', 'Rheumatoid nodule, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.339', 'Rheumatoid nodule, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.34', 'Rheumatoid nodule, hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.341', 'Rheumatoid nodule, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.342', 'Rheumatoid nodule, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.349', 'Rheumatoid nodule, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.35', 'Rheumatoid nodule, hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.351', 'Rheumatoid nodule, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.352', 'Rheumatoid nodule, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.359', 'Rheumatoid nodule, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.36', 'Rheumatoid nodule, knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.361', 'Rheumatoid nodule, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.362', 'Rheumatoid nodule, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.369', 'Rheumatoid nodule, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.37', 'Rheumatoid nodule, ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.371', 'Rheumatoid nodule, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.372', 'Rheumatoid nodule, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.379', 'Rheumatoid nodule, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.38', 'Rheumatoid nodule, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.39', 'Rheumatoid nodule, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.4', 'Inflammatory polyarthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.8', 'Other specified rheumatoid arthritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.80', 'Other specified rheumatoid arthritis, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.81', 'Other specified rheumatoid arthritis, shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.811', 'Other specified rheumatoid arthritis, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.812', 'Other specified rheumatoid arthritis, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.819', 'Other specified rheumatoid arthritis, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.82', 'Other specified rheumatoid arthritis, elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.821', 'Other specified rheumatoid arthritis, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.822', 'Other specified rheumatoid arthritis, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.829', 'Other specified rheumatoid arthritis, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.83', 'Other specified rheumatoid arthritis, wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.831', 'Other specified rheumatoid arthritis, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.832', 'Other specified rheumatoid arthritis, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.839', 'Other specified rheumatoid arthritis, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.84', 'Other specified rheumatoid arthritis, hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.841', 'Other specified rheumatoid arthritis, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.842', 'Other specified rheumatoid arthritis, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.849', 'Other specified rheumatoid arthritis, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.85', 'Other specified rheumatoid arthritis, hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.851', 'Other specified rheumatoid arthritis, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.852', 'Other specified rheumatoid arthritis, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.859', 'Other specified rheumatoid arthritis, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.86', 'Other specified rheumatoid arthritis, knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.861', 'Other specified rheumatoid arthritis, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.862', 'Other specified rheumatoid arthritis, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.869', 'Other specified rheumatoid arthritis, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.87', 'Other specified rheumatoid arthritis, ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.871', 'Other specified rheumatoid arthritis, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.872', 'Other specified rheumatoid arthritis, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.879', 'Other specified rheumatoid arthritis, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.88', 'Other specified rheumatoid arthritis, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.89', 'Other specified rheumatoid arthritis, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.8A', 'Other specified rheumatoid arthritis, other specified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.9', 'Rheumatoid arthritis, unspecified')
) AS t (system, code, display) ;