create or replace view irae__rx_diuretics_loop as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1151349', 'bumetanide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1151350', 'bumetanide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156816', 'ethacrynate Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156817', 'ethacrynate Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162713', 'furosemide Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162714', 'furosemide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162715', 'furosemide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162752', 'torsemide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162753', 'torsemide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1168680', 'Bumex Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1168681', 'Bumex Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172416', 'Demadex Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172417', 'Demadex Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1173193', 'Edecrin Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1173194', 'Edecrin Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1175647', 'Lasix Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1175648', 'Lasix Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251902', 'ethacrynic acid 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251903', 'ethacrynic acid 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251904', 'ethacrynic acid 25 MG [Edecrin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251905', 'ethacrynic acid 25 MG Oral Tablet [Edecrin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251906', 'ethacrynic acid 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1251907', 'ethacrynic acid 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '151689', 'Edecrin')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1808', 'bumetanide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197417', 'bumetanide 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197418', 'bumetanide 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197419', 'bumetanide 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197730', 'furosemide 10 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197731', 'furosemide 8 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197732', 'furosemide 80 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198369', 'torsemide 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198370', 'torsemide 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198371', 'torsemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198372', 'torsemide 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200801', 'furosemide 20 MG Oral Tablet [Lasix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200809', 'furosemide 40 MG Oral Tablet [Lasix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202991', 'Lasix')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203538', 'Bumex')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205488', 'bumetanide 0.5 MG Oral Tablet [Bumex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205489', 'bumetanide 1 MG Oral Tablet [Bumex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205490', 'bumetanide 2 MG Oral Tablet [Bumex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205732', 'furosemide 80 MG Oral Tablet [Lasix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208076', 'torsemide 10 MG Oral Tablet [Demadex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208081', 'torsemide 20 MG Oral Tablet [Demadex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589872', 'Soaanz')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589873', 'torsemide 20 MG [Soaanz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589874', 'Soaanz Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589875', 'Soaanz Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589876', 'torsemide Oral Tablet [Soaanz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589877', 'torsemide 20 MG Oral Tablet [Soaanz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589880', 'torsemide 40 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589881', 'torsemide 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589882', 'torsemide 40 MG [Soaanz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589883', 'torsemide 40 MG Oral Tablet [Soaanz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589884', 'torsemide 60 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589885', 'torsemide 60 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589886', 'torsemide 60 MG [Soaanz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589887', 'torsemide 60 MG Oral Tablet [Soaanz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2647723', 'ethacrynic acid Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658998', 'ethacrynic acid Oral Tablet [Edecrin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2659396', 'ethacrynic acid Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2659623', 'ethacrynic acid Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310429', 'furosemide 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313988', 'furosemide 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315499', 'bumetanide 0.25 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315500', 'bumetanide 0.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315501', 'bumetanide 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315502', 'bumetanide 2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315970', 'furosemide 20 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315971', 'furosemide 40 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315972', 'furosemide 8 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316842', 'torsemide 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316844', 'torsemide 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316845', 'torsemide 5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317376', 'furosemide 10 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317377', 'furosemide 80 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317521', 'torsemide 20 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '368487', 'furosemide Oral Tablet [Lasix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369285', 'torsemide Oral Tablet [Demadex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369375', 'bumetanide Oral Tablet [Bumex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371158', 'bumetanide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372280', 'furosemide Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372281', 'furosemide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374168', 'torsemide Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '38413', 'torsemide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '4109', 'ethacrynic acid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '4603', 'furosemide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '565450', 'furosemide 20 MG [Lasix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '565458', 'furosemide 40 MG [Lasix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '566394', 'bumetanide 0.5 MG [Bumex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '566395', 'bumetanide 1 MG [Bumex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '566396', 'bumetanide 2 MG [Bumex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '566621', 'furosemide 80 MG [Lasix]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '568804', 'torsemide 10 MG [Demadex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '568809', 'torsemide 20 MG [Demadex]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '617327', 'ethacrynate Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '619260', 'ethacrynate Oral Tablet [Edecrin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '62349', 'ethacrynate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '71974', 'Demadex')
) AS t (system, code, display) ;