config_type="file_upload"

[tables.valueset_casedef]
# https://github.com/smart-on-fhir/cumulus-library/issues/569
col_types = [
    "STRING",  # system
    "STRING",  # code
    "STRING",  # display
    "BOOLEAN", # include
    "STRING",  # likely
    "STRING",  # preop
    "STRING",  # transplant
    "STRING",  # rejection
    "STRING",  # failure
    "STRING",  # outcome
    "STRING",  # lab
    "STRING"]  # imaging
file = "casedef.csv"