config_type="file_upload"

[tables.valueset_casedef]
# https://github.com/smart-on-fhir/cumulus-library/issues/569
col_types = [
    "STRING",   # system
    "STRING",   # code
    "STRING",   # display
    "BOOLEAN",  # include
    "STRING",  # likely
    "STRING",  # preop
    "STRING",  # transplant
    "STRING",  # rejection
    "STRING",  # failure
    "STRING",  # outcome
    "STRING",  # lab
    "STRING"]  # imaging
file = "casedef.csv"

[tables.valueset_lab_albumin_urine]
file = "lab_albumin_urine.csv"

[tables.valueset_lab_azathioprine]
file = "lab_azathioprine.csv"

[tables.valueset_lab_azathioprine_tpmt_gene]
file = "lab_azathioprine_tpmt_gene.csv"

[tables.valueset_lab_c_peptide]
file = "lab_c_peptide.csv"

[tables.valueset_lab_cyclosporin]
file = "lab_cyclosporin.csv"

[tables.valueset_lab_cytomegalovirus]
file = "lab_cytomegalovirus.csv"

[tables.valueset_lab_gad]
file = "lab_gad.csv"

[tables.valueset_lab_gfr_custom]
file = "lab_gfr_custom.csv"

[tables.valueset_lab_glucose]
file = "lab_glucose.csv"

[tables.valueset_lab_hdl]
file = "lab_hdl.csv"

[tables.valueset_lab_hemoglobin_a1c]
file = "lab_hemoglobin_a1c.csv"

[tables.valueset_lab_hla]
file = "lab_hla.csv"

[tables.valueset_lab_insulin]
file = "lab_insulin.csv"

[tables.valueset_lab_ketone_urine]
file = "lab_ketone_urine.csv"

[tables.valueset_lab_ldl]
file = "lab_ldl.csv"

[tables.valueset_lab_mycophenolate]
file = "lab_mycophenolate.csv"

[tables.valueset_lab_sirolimus]
file = "lab_sirolimus.csv"

[tables.valueset_lab_tacrolimus]
file = "lab_tacrolimus.csv"

[tables.valueset_lab_triglyceride]
file = "lab_triglyceride.csv"

[tables.valueset_rx_alemtuzumab]
file = "rx_alemtuzumab.csv"

[tables.valueset_rx_atg]
file = "rx_atg.csv"

[tables.valueset_rx_azathioprine]
file = "rx_azathioprine.csv"

[tables.valueset_rx_basiliximab]
file = "rx_basiliximab.csv"

[tables.valueset_rx_belatacept]
file = "rx_belatacept.csv"

[tables.valueset_rx_cyclosporin]
file = "rx_cyclosporin.csv"

[tables.valueset_rx_cytogam]
file = "rx_cytogam.csv"

[tables.valueset_rx_everolimus]
file = "rx_everolimus.csv"

[tables.valueset_rx_ig]
file = "rx_ig.csv"

[tables.valueset_rx_ivig]
file = "rx_ivig.csv"

[tables.valueset_rx_methylprednisolone]
file = "rx_methylprednisolone.csv"

[tables.valueset_rx_mycophenolate]
file = "rx_mycophenolate.csv"

[tables.valueset_rx_prednisolone]
file = "rx_prednisolone.csv"

[tables.valueset_rx_prednisone]
file = "rx_prednisone.csv"

[tables.valueset_rx_rituximab]
file = "rx_rituximab.csv"

[tables.valueset_rx_sirolimus]
file = "rx_sirolimus.csv"

[tables.valueset_rx_tacrolimus]
file = "rx_tacrolimus.csv"

