config_type="file_upload"

[tables.valueset_diag_kidney_biopsy]
file = "diag_kidney_biopsy.csv"

[tables.valueset_doc_type_relevant]
file = "doc_type_relevant.csv"

[tables.valueset_dx_cancer_general]
file = "dx_cancer_general.csv"

[tables.valueset_dx_cancer_specific]
file = "dx_cancer_specific.csv"

[tables.valueset_dx_graft_failure]
file = "dx_graft_failure.csv"

[tables.valueset_dx_graft_rejection]
file = "dx_graft_rejection.csv"

[tables.valueset_dx_infection_bacterial]
file = "dx_infection_bacterial.csv"

[tables.valueset_dx_infection_cmv]
file = "dx_infection_cmv.csv"

[tables.valueset_dx_infection_ebv]
file = "dx_infection_ebv.csv"

[tables.valueset_dx_infection_fungal]
file = "dx_infection_fungal.csv"

[tables.valueset_dx_infection_hepatitis_b]
file = "dx_infection_hepatitis_b.csv"

[tables.valueset_dx_infection_hepatitis_c]
file = "dx_infection_hepatitis_c.csv"

[tables.valueset_dx_infection_hsv]
file = "dx_infection_hsv.csv"

[tables.valueset_dx_infection_influenza]
file = "dx_infection_influenza.csv"

[tables.valueset_dx_infection_pna]
file = "dx_infection_pna.csv"

[tables.valueset_dx_infection_rsv]
file = "dx_infection_rsv.csv"

[tables.valueset_dx_kidney_biopsy]
file = "dx_kidney_biopsy.csv"

[tables.valueset_dx_ptld]
file = "dx_ptld.csv"

[tables.valueset_dx_transplant]
file = "dx_transplant.csv"

[tables.valueset_fhir_diagnostic_service]
file = "fhir_diagnostic_service.csv"

[tables.include_age_at_visit]
file = "include_age_at_visit.csv"

[tables.include_diag_category]
file = "include_diag_category.csv"

[tables.include_gender]
file = "include_gender.csv"

[tables.include_study_period]
file = "include_study_period.csv"

[tables.include_utilization]
file = "include_utilization.csv"

[tables.valueset_lab_albumin]
file = "lab_albumin.csv"

[tables.valueset_lab_crp]
file = "lab_crp.csv"

[tables.valueset_lab_drug_level]
file = "lab_drug_level.csv"

[tables.valueset_lab_dsa]
file = "lab_dsa.csv"

[tables.valueset_lab_esr]
file = "lab_esr.csv"

[tables.valueset_lab_gfr_custom]
file = "lab_gfr_custom.csv"

[tables.valueset_lab_graft_failure]
file = "lab_graft_failure.csv"

[tables.valueset_lab_graft_rejection]
file = "lab_graft_rejection.csv"

[tables.valueset_lab_hla]
file = "lab_hla.csv"

[tables.valueset_lab_infection_bacterial]
file = "lab_infection_bacterial.csv"

[tables.valueset_lab_infection_cmv]
file = "lab_infection_cmv.csv"

[tables.valueset_lab_infection_ebv]
file = "lab_infection_ebv.csv"

[tables.valueset_lab_infection_fungal]
file = "lab_infection_fungal.csv"

[tables.valueset_lab_infection_hsv]
file = "lab_infection_hsv.csv"

[tables.valueset_lab_infection_viral_other]
file = "lab_infection_viral_other.csv"

[tables.valueset_lab_iron_ferritin]
file = "lab_iron_ferritin.csv"

[tables.valueset_lab_kidney_biopsy]
file = "lab_kidney_biopsy.csv"

[tables.valueset_lab_ptld]
file = "lab_ptld.csv"

[tables.valueset_lab_tpmt_gene]
file = "lab_tpmt_gene.csv"

[tables.valueset_proc_dsa]
file = "proc_dsa.csv"

[tables.valueset_proc_graft_failure]
file = "proc_graft_failure.csv"

[tables.valueset_proc_graft_rejection]
file = "proc_graft_rejection.csv"

[tables.valueset_proc_kidney_biopsy]
file = "proc_kidney_biopsy.csv"

[tables.valueset_proc_nephrectomy]
file = "proc_nephrectomy.csv"

[tables.valueset_proc_transplant]
file = "proc_transplant.csv"

[tables.valueset_rx_antimetabolite_azathioprine]
file = "rx_antimetabolite_azathioprine.csv"

[tables.valueset_rx_antimetabolite_mycophenolate]
file = "rx_antimetabolite_mycophenolate.csv"

[tables.valueset_rx_atg]
file = "rx_atg.csv"

[tables.valueset_rx_belatacept]
file = "rx_belatacept.csv"

[tables.valueset_rx_cni_cyclosporin]
file = "rx_cni_cyclosporin.csv"

[tables.valueset_rx_cni_tacrolimus]
file = "rx_cni_tacrolimus.csv"

[tables.valueset_rx_corticosteroid_methylprednisolone]
file = "rx_corticosteroid_methylprednisolone.csv"

[tables.valueset_rx_corticosteroid_prednisolone]
file = "rx_corticosteroid_prednisolone.csv"

[tables.valueset_rx_corticosteroid_prednisone]
file = "rx_corticosteroid_prednisone.csv"

[tables.valueset_rx_cytogam]
file = "rx_cytogam.csv"

[tables.valueset_rx_ig]
file = "rx_ig.csv"

[tables.valueset_rx_ivig]
file = "rx_ivig.csv"

[tables.valueset_rx_mab_alemtuzumab]
file = "rx_mab_alemtuzumab.csv"

[tables.valueset_rx_mab_basiliximab]
file = "rx_mab_basiliximab.csv"

[tables.valueset_rx_mab_rituximab]
file = "rx_mab_rituximab.csv"

[tables.valueset_rx_mtor_everolimus]
file = "rx_mtor_everolimus.csv"

[tables.valueset_rx_mtor_sirolimus]
file = "rx_mtor_sirolimus.csv"

[tables.valueset_service_kidney_biopsy]
file = "service_kidney_biopsy.csv"