study_prefix = "irae"

[[stages.file_upload]]
type = "submanifest"
files = ['file_upload.toml']

[[stages.study_population]]
type = "submanifest"
files = ['study_population.toml']

[[stages.study_variable]]
type = "submanifest"
files = ['study_variable.toml']

[[stages.study_variable_wide]]
type = "submanifest"
files = ['study_variable_wide.toml']

[[stages.casedef]]
type = "submanifest"
files = ['casedef.toml']

[[stages.sample]]
type = "submanifest"
files = ['sample.toml']

[[stages.nlp]]
type = "submanifest"
files = ['nlp_tasks.toml']

[[stages.nlp_10]]
type = "submanifest"
files = ['nlp_tasks_10.toml']

[[stages.nlp_post_processing]]
type = "submanifest"
files = ['nlp_post_processing.toml']

[[stages.cube]]
type = "submanifest"
files = ['cube.toml']