[[actions]]
description = 'Flattened NLP results for IRAE Clinical Tasks'
type = "build:parallel"
files = [
    "llm/builder/irae_donor_wide.py",
    "llm/builder/irae_immunosuppressive_medications_wide.py",
    "llm/builder/irae_longitudinal_wide.py",
    "llm/builder/irae_multiple_transplant_history_wide.py",
]

[[actions]]
description = 'Span Highlights for IRAE Clinical Tasks'
type = "build:parallel"
files = [
    "llm/builder/irae_donor_highlights.py",
    "llm/builder/irae_immunosuppressive_medications_highlights.py",
    "llm/builder/irae_longitudinal_highlights.py",
    "llm/builder/irae_multiple_transplant_history_highlights.py",
]

# Add back in when @Andy has an equivalent version of timeline
# [[actions]]
# description = 'LLM timeline in WIDE format'
# type = "build:parallel"
# files = [
#     "llm/athena/irae__llm_timeline.sql",
# ]