[[actions]]
description="samples for casedef temporality (pre, per, peri_post, post)"
type="build:parallel"
files= [
	"athena/irae__sample_casedef.sql",
	"athena/irae__sample_casedef_pre.sql",
	"athena/irae__sample_casedef_peri.sql",
	"athena/irae__sample_casedef_peri_post.sql",
	"athena/irae__sample_casedef_post.sql",
]

[[actions]]
description = 'samples for casedef temporality (limit 10 patients or 50 notes)'
type="build:parallel"
files= [
	"athena/irae__sample_casedef_pre_limit_patient_10.sql",
	"athena/irae__sample_casedef_pre_limit_note_50.sql",
	"athena/irae__sample_casedef_peri_limit_patient_10.sql",
	"athena/irae__sample_casedef_peri_limit_note_50.sql",
	"athena/irae__sample_casedef_peri_post_limit_patient_10.sql",
	"athena/irae__sample_casedef_peri_post_limit_note_50.sql",
	"athena/irae__sample_casedef_post_limit_patient_10.sql",
	"athena/irae__sample_casedef_post_limit_note_50.sql"
]