[[actions]]
description = "variable cohorts"
type = "build:parallel"
files = [
    "athena/irae__cohort_diag_kidney_biopsy.sql",
    "athena/irae__cohort_doc_type_relevant.sql",
    "athena/irae__cohort_dx_cancer_general.sql",
    "athena/irae__cohort_dx_cancer_specific.sql",
    "athena/irae__cohort_dx_graft_failure.sql",
    "athena/irae__cohort_dx_graft_rejection.sql",
    "athena/irae__cohort_dx_infection_bacterial.sql",
    "athena/irae__cohort_dx_infection_cmv.sql",
    "athena/irae__cohort_dx_infection_ebv.sql",
    "athena/irae__cohort_dx_infection_fungal.sql",
    "athena/irae__cohort_dx_infection_hepatitis_b.sql",
    "athena/irae__cohort_dx_infection_hepatitis_c.sql",
    "athena/irae__cohort_dx_infection_hsv.sql",
    "athena/irae__cohort_dx_infection_influenza.sql",
    "athena/irae__cohort_dx_infection_pna.sql",
    "athena/irae__cohort_dx_infection_rsv.sql",
    "athena/irae__cohort_dx_kidney_biopsy.sql",
    "athena/irae__cohort_dx_ptld.sql",
    "athena/irae__cohort_dx_transplant.sql",
    "athena/irae__cohort_lab_albumin.sql",
    "athena/irae__cohort_lab_crp.sql",
    "athena/irae__cohort_lab_drug_level.sql",
    "athena/irae__cohort_lab_dsa.sql",
    "athena/irae__cohort_lab_esr.sql",
    "athena/irae__cohort_lab_gfr_custom.sql",
    "athena/irae__cohort_lab_graft_failure.sql",
    "athena/irae__cohort_lab_graft_rejection.sql",
    "athena/irae__cohort_lab_hla.sql",
    "athena/irae__cohort_lab_infection_bacterial.sql",
    "athena/irae__cohort_lab_infection_cmv.sql",
    "athena/irae__cohort_lab_infection_ebv.sql",
    "athena/irae__cohort_lab_infection_fungal.sql",
    "athena/irae__cohort_lab_infection_hsv.sql",
    "athena/irae__cohort_lab_infection_viral_other.sql",
    "athena/irae__cohort_lab_iron_ferritin.sql",
    "athena/irae__cohort_lab_kidney_biopsy.sql",
    "athena/irae__cohort_lab_ptld.sql",
    "athena/irae__cohort_lab_tpmt_gene.sql",
    "athena/irae__cohort_proc_dsa.sql",
    "athena/irae__cohort_proc_graft_failure.sql",
    "athena/irae__cohort_proc_graft_rejection.sql",
    "athena/irae__cohort_proc_kidney_biopsy.sql",
    "athena/irae__cohort_proc_nephrectomy.sql",
    "athena/irae__cohort_proc_transplant.sql",
    "athena/irae__cohort_rx_antimetabolite_azathioprine.sql",
    "athena/irae__cohort_rx_antimetabolite_mycophenolate.sql",
    "athena/irae__cohort_rx_atg.sql",
    "athena/irae__cohort_rx_belatacept.sql",
    "athena/irae__cohort_rx_cni_cyclosporin.sql",
    "athena/irae__cohort_rx_cni_tacrolimus.sql",
    "athena/irae__cohort_rx_corticosteroid_methylprednisolone.sql",
    "athena/irae__cohort_rx_corticosteroid_prednisolone.sql",
    "athena/irae__cohort_rx_corticosteroid_prednisone.sql",
    "athena/irae__cohort_rx_cytogam.sql",
    "athena/irae__cohort_rx_ig.sql",
    "athena/irae__cohort_rx_ivig.sql",
    "athena/irae__cohort_rx_mab_alemtuzumab.sql",
    "athena/irae__cohort_rx_mab_basiliximab.sql",
    "athena/irae__cohort_rx_mab_rituximab.sql",
    "athena/irae__cohort_rx_mtor_everolimus.sql",
    "athena/irae__cohort_rx_mtor_sirolimus.sql",
]
