
[[actions]]
description="variable union (bool)"
type="build:parallel"
files= [
	"athena/irae__cohort_variable_union.sql"
]

[[actions]]
description="variable union ('diag', 'proc', 'lab', 'rx', 'dx', 'doc')"
type="build:parallel"
files= [
	"athena/irae__cohort_variable_union_diag.sql",
	"athena/irae__cohort_variable_union_proc.sql",
	"athena/irae__cohort_variable_union_lab.sql",
	"athena/irae__cohort_variable_union_rx.sql",
	"athena/irae__cohort_variable_union_dx.sql",
	"athena/irae__cohort_variable_union_doc.sql"
]

[[actions]]
description="variable wide (bool)"
type="build:parallel"
files= [
	"athena/irae__cohort_variable_wide.sql"
]

[[actions]]
description="variable wide ('diag', 'proc', 'lab', 'rx', 'dx', 'doc')"
type="build:parallel"
files= [
	"athena/irae__cohort_variable_wide_diag.sql",
	"athena/irae__cohort_variable_wide_proc.sql",
	"athena/irae__cohort_variable_wide_lab.sql",
	"athena/irae__cohort_variable_wide_rx.sql",
	"athena/irae__cohort_variable_wide_dx.sql",
	"athena/irae__cohort_variable_wide_doc.sql"
]