create or replace view irae__doc_biopsy_lung as select * from (values
('http://snomed.info/sct', '116030005', 'Wedge biopsy of lung (procedure)')
,('http://snomed.info/sct', '173190004', 'Needle biopsy of lesion of lung (procedure)')
,('http://snomed.info/sct', '173191000', 'Aspiration biopsy of lesion of lung (procedure)')
,('http://snomed.info/sct', '232628003', 'Open biopsy of lung (procedure)')
,('http://snomed.info/sct', '243411004', 'Fiberoptic bronchoscopy with biopsy of lung (procedure)')
,('http://snomed.info/sct', '243685008', 'Bronchoscopy with transbronchial lung biopsy (procedure)')
,('http://snomed.info/sct', '274319000', 'Needle biopsy of lung (procedure)')
,('http://snomed.info/sct', '287465001', 'Percutaneous needle biopsy lung (procedure)')
,('http://snomed.info/sct', '35295005', 'Percutaneous fine needle biopsy of lung (procedure)')
,('http://snomed.info/sct', '429932001', 'Biopsy of lung using computed tomography guidance (procedure)')
,('http://snomed.info/sct', '431721002', 'Biopsy of lung using fluoroscopic guidance (procedure)')
,('http://snomed.info/sct', '432231006', 'Fine needle aspiration biopsy of lung (procedure)')
,('http://snomed.info/sct', '432652008', 'Biopsy of lung using ultrasound guidance (procedure)')
,('http://snomed.info/sct', '43831007', 'Percutaneous core needle biopsy of lung (procedure)')
,('http://snomed.info/sct', '442877005', 'Percutaneous needle biopsy of lung using ultrasound guidance (procedure)')
,('http://snomed.info/sct', '443810005', 'Minithoracotomy and biopsy of lung (procedure)')
,('http://snomed.info/sct', '450348001', 'Biopsy of lesion of lung (procedure)')
,('http://snomed.info/sct', '66258007', 'Thoracoscopic biopsy of lung (procedure)')
,('http://snomed.info/sct', '708813000', 'Percutaneous fine needle aspiration biopsy of lung using imaging guidance (procedure)')
,('http://snomed.info/sct', '78603008', 'Biopsy of lung (procedure)')
,('http://snomed.info/sct', '81070005', 'Bronchoscopy through tracheostomy with biopsy of lung (procedure)')
) AS t (system, code, display) ;