create or replace view irae__dx_htn_essential as select * from (values
('http://snomed.info/sct', '1201005', 'Benign essential hypertension (disorder)')
,('http://snomed.info/sct', '18416000', 'Essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '19769006', 'High-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '23717007', 'Benign essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '35303009', 'Benign essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://snomed.info/sct', '371125006', 'Labile essential hypertension (disorder)')
,('http://snomed.info/sct', '40511000119107', 'Postpartum pre-existing essential hypertension (disorder)')
,('http://snomed.info/sct', '429457004', 'Systolic essential hypertension (disorder)')
,('http://snomed.info/sct', '46481004', 'Low-renin essential hypertension (disorder)')
,('http://snomed.info/sct', '59621000', 'Essential hypertension (disorder)')
,('http://snomed.info/sct', '63287004', 'Benign essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '71874008', 'Benign essential hypertension complicating AND/OR reason for care during childbirth (disorder)')
,('http://snomed.info/sct', '72022006', 'Essential hypertension in obstetric context (disorder)')
,('http://snomed.info/sct', '78808002', 'Essential hypertension complicating AND/OR reason for care during pregnancy (disorder)')
,('http://snomed.info/sct', '78975002', 'Malignant essential hypertension (disorder)')
,('http://snomed.info/sct', '9901000', 'Essential hypertension complicating AND/OR reason for care during puerperium (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I10', 'Essential (primary) hypertension')
) AS t (system, code, display) ;