create or replace view irae__rx_evorolimus as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1119401', 'everolimus 7.5 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119402', 'AFINITOR 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119402', 'Afinitor 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119402', 'everolimus 7.5 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172066', 'Afinitor Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172067', 'Afinitor Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1186316', 'Zortress Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1186317', 'Zortress Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310137', 'Afinitor Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310138', 'AFINITOR DISPERZ 2 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310138', 'Afinitor Disperz 2 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310138', 'everolimus 2 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310144', 'AFINITOR DISPERZ 3 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310144', 'Afinitor Disperz 3 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310144', 'everolimus 3 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310147', 'AFINITOR DISPERZ 5 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310147', 'Afinitor Disperz 5 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310147', 'everolimus 5 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869515', 'everolimus 2 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869516', 'everolimus Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869520', 'everolimus 3 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056896', 'everolimus 1 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056897', 'ZORTRESS 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056897', 'Zortress 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056897', 'everolimus 1 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845509', 'Afinitor')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845510', 'everolimus 10 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845511', 'everolimus Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845512', 'AFINITOR 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845512', 'Afinitor 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845512', 'everolimus 10 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845517', 'everolimus 5 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845518', 'AFINITOR 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845518', 'Afinitor 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845518', 'everolimus 5 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977428', 'Zortress')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977429', 'everolimus 0.25 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977430', 'everolimus Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977431', 'Zortress 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977431', 'everolimus 0.25 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977435', 'everolimus 0.5 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977436', 'Zortress 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977436', 'everolimus 0.5 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977439', 'everolimus 0.75 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977440', 'Zortress 0.75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977440', 'everolimus 0.75 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998190', 'everolimus 2.5 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998191', 'AFINITOR 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998191', 'Afinitor 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998191', 'everolimus 2.5 MG Oral Tablet [Afinitor]')
) AS t (system, code, display) ;