create or replace view irae__dx_transplant_stem_cell as select * from (values
('http://snomed.info/sct', '121121000119106', 'Acute graft-versus-host reaction following bone marrow transplant (disorder)')
,('http://snomed.info/sct', '122491000119108', 'Lymphoproliferative disorder after transplantation of bone marrow (disorder)')
,('http://snomed.info/sct', '234519006', 'Bone marrow transplant rejection (disorder)')
,('http://snomed.info/sct', '234520000', 'Bone marrow transplant failure (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.0', 'Bone marrow or hematopoietic stem cell transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.00', 'Bone marrow transplant, not otherwise specified')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.01', 'Autologous bone marrow transplant without purging')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.02', 'Allogeneic bone marrow transplant with purging')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.03', 'Allogeneic bone marrow transplant without purging')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.04', 'Autologous hematopoietic stem cell transplant without purging')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.05', 'Allogeneic hematopoietic stem cell transpant without purging')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.06', 'Cord blood stem cell transplant')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.07', 'Autologous hematopoietic stem cell transplant with purging')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.08', 'Allogeneic hematopoietic stem cell transplant with purging')
,('http://hl7.org/fhir/sid/icd-9-cm', '41.09', 'Autologous bone marrow transplant with purging')
,('http://snomed.info/sct', '428103008', 'Disorder of transplanted bone marrow (disorder)')
,('http://snomed.info/sct', '429362002', 'Short stature associated with bone marrow transplant (disorder)')
,('http://snomed.info/sct', '429450002', 'Disorder related to bone marrow transplantation (disorder)')
,('http://snomed.info/sct', '429514007', 'Growth hormone deficiency after bone marrow transplant (disorder)')
,('http://snomed.info/sct', '431456004', 'Accelerated rejection of bone marrow transplant (disorder)')
,('http://snomed.info/sct', '431862001', 'Acute rejection of bone marrow transplant (disorder)')
,('http://snomed.info/sct', '431953002', 'Chronic rejection of bone marrow transplant (disorder)')
,('http://snomed.info/sct', '432782005', 'Hyperacute rejection of bone marrow transplant (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '996.85', 'Complications of transplanted bone marrow')
,('http://hl7.org/fhir/sid/icd-9-cm', '996.88', 'Complications of transplanted organ, stem cell')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.0', 'Complications of bone marrow transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.00', 'Unspecified complication of bone marrow transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.01', 'Bone marrow transplant rejection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.02', 'Bone marrow transplant failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.03', 'Bone marrow transplant infection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.09', 'Other complications of bone marrow transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.5', 'Complications of stem cell transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.00', 'Unspecified complication of bone marrow transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.01', 'Bone marrow transplant rejection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.02', 'Bone marrow transplant failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.03', 'Bone marrow transplant infection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.09', 'Other complications of bone marrow transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.10', 'Unspecified complication of kidney transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.11', 'Kidney transplant rejection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.12', 'Kidney transplant failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.13', 'Kidney transplant infection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.19', 'Other complication of kidney transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.20', 'Unspecified complication of heart transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.21', 'Heart transplant rejection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.22', 'Heart transplant failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.23', 'Heart transplant infection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.290', 'Cardiac allograft vasculopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.298', 'Other complications of heart transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.30', 'Unspecified complication of heart-lung transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.31', 'Heart-lung transplant rejection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.32', 'Heart-lung transplant failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.33', 'Heart-lung transplant infection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.39', 'Other complications of heart-lung transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.40', 'Unspecified complication of liver transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.41', 'Liver transplant rejection')
) AS t (system, code, display) ;