create or replace view irae__rx_immunosuppressive_coricosteroids_systemic as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1005831', '{48 (prednisolone 5 MG Oral Tablet [MILLIPRED]) } Pack [Millipred DP 12 Day]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007039', 'betamethasone / betamethasone acetate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007088', 'betamethasone dipropionate / betamethasone sodium phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1037338', 'hydrocortisone sodium phosphate 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1049383', 'Dexium')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1049384', 'dexamethasone 2 MG/ML [Dexium]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1049385', 'dexamethasone Injectable Solution [Dexium]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1049386', 'dexamethasone 2 MG/ML Injectable Solution [Dexium]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105389', 'betamethasone 0.5 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105392', 'dexamethasone 0.5 MG Oral Tablet [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105398', 'hydrocortisone 100 MG Injection [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105408', 'prednisolone 2.5 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105409', 'prednisolone 5 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105410', 'prednisolone 5 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085666', 'triamcinolone diacetate 25 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085680', 'triamcinolone diacetate 40 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085737', 'triamcinolone acetonide 0.147 MG/ML [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085750', 'triamcinolone acetonide 10 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085751', 'triamcinolone acetonide 10 MG/ML [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085752', 'triamcinolone acetonide 10 MG/ML Injectable Suspension [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085754', 'triamcinolone acetonide 40 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085755', 'triamcinolone acetonide 40 MG/ML [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085756', 'triamcinolone acetonide 40 MG/ML Injectable Suspension [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085985', 'triamcinolone acetonide 3 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085992', 'triamcinolone hexacetonide 5 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085993', 'triamcinolone hexacetonide 5 MG/ML [Aristospan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085994', 'triamcinolone hexacetonide 5 MG/ML Injectable Suspension [Aristospan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085996', 'triamcinolone hexacetonide 20 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085997', 'triamcinolone hexacetonide 20 MG/ML [Aristospan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1085998', 'triamcinolone hexacetonide 20 MG/ML Injectable Suspension [Aristospan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1086258', 'triamcinolone acetonide 40 MG/ML [Triesence]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1086259', '1 ML triamcinolone acetonide 40 MG/ML Injection [Triesence]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1086275', '1 ML triamcinolone acetonide 40 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1087756', 'dexamethasone 2 MG/ML [Dexasone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1087757', 'dexamethasone 2 MG/ML Injectable Solution [Dexasone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1087918', 'dexamethasone 3 MG/ML [Dexium]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1087919', 'dexamethasone 3 MG/ML Injectable Solution [Dexium]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1116926', 'dexamethasone phosphate 4 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1116927', 'dexamethasone phosphate 4 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1151338', 'budesonide Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1151339', 'budesonide Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153796', 'betamethasone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153799', 'betamethasone Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153800', 'betamethasone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153802', 'betamethasone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154531', 'dexamethasone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154534', 'dexamethasone Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154535', 'dexamethasone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154537', 'dexamethasone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155527', 'cortisone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155528', 'cortisone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155815', 'cortisone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1157200', 'deflazacort Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1157201', 'deflazacort Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163486', 'methylprednisolone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163488', 'methylprednisolone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163489', 'methylprednisolone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165880', 'A-Hydrocort Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165881', 'A-MethaPred Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1166205', 'Celestone Soluspan Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1167031', 'Entocort Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1167032', 'Entocort Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170041', 'Kenalog Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170297', 'Decadron Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170298', 'Decadron Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170762', 'Aristospan Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170955', 'Cortef Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1170956', 'Cortef Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172410', 'Deltasone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172411', 'Deltasone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1173110', 'Depo-Medrol Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1175250', 'Dexasone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1175843', 'Dexium Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1183227', 'Triesence Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184839', 'Solu-Cortef Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184840', 'Solu-Medrol Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184933', 'MILLIPRED Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184934', 'MILLIPRED Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184935', 'MILLIPRED Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187894', 'Veripred Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1187895', 'Veripred Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191678', 'Prednistab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191679', 'prednisolone 20 MG [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191680', 'prednisolone Oral Tablet [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191681', 'Prednistab Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191682', 'Prednistab Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191683', 'prednisolone 20 MG Oral Tablet [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191685', 'prednisolone 5 MG [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191686', 'prednisolone 5 MG Oral Tablet [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235042', '{21 (prednisolone 5 MG Oral Tablet [MILLIPRED]) } Pack [Millipred DP 6 Day]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1244214', 'budesonide 3 MG Delayed Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1244215', 'budesonide 3 MG Delayed Release Oral Capsule [Entocort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1295250', 'betamethasone Disintegrating Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303124', 'prednisone Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303125', 'prednisone 1 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303126', 'Rayos')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303127', 'prednisone 1 MG [Rayos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303128', 'prednisone Delayed Release Oral Tablet [Rayos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303129', 'Rayos Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303130', 'Rayos Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303131', 'prednisone 1 MG Delayed Release Oral Tablet [Rayos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303132', 'prednisone 2 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303133', 'prednisone 2 MG [Rayos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303134', 'prednisone 2 MG Delayed Release Oral Tablet [Rayos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303135', 'prednisone 5 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303136', 'prednisone 5 MG [Rayos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1303137', 'prednisone 5 MG Delayed Release Oral Tablet [Rayos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1357886', 'methylprednisolone 2000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1357888', 'methylprednisolone 2000 MG Injection [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358496', 'methylprednisolone acetate 40 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358509', 'methylprednisolone acetate 20 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358510', 'methylprednisolone acetate 20 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358511', 'methylprednisolone acetate 20 MG/ML [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358512', 'methylprednisolone acetate 20 MG/ML Injectable Suspension [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358610', 'methylprednisolone acetate 40 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358611', 'methylprednisolone acetate 40 MG/ML [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358612', 'methylprednisolone acetate 40 MG/ML Injectable Suspension [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358616', 'methylprednisolone acetate 80 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358617', 'methylprednisolone acetate 80 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358618', 'methylprednisolone acetate 80 MG/ML [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1358619', 'methylprednisolone acetate 80 MG/ML Injectable Suspension [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366548', 'budesonide 9 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366549', 'budesonide Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366550', '24 HR budesonide 9 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366551', 'Uceris')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366552', 'budesonide 9 MG [Uceris]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366553', 'budesonide Extended Release Oral Tablet [Uceris]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366554', 'Uceris Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366555', 'Uceris Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1366556', '24 HR budesonide 9 MG Extended Release Oral Tablet [Uceris]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1367172', 'budesonide (11.beta.,16.alpha.(S))')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1374371', 'dexamethasone acetate 8 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1374372', 'dexamethasone acetate 8 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1489770', 'budesonide Delayed Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1489772', 'budesonide Delayed Release Oral Capsule [Entocort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1514', 'betamethasone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1516', 'betamethasone acetate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153098', 'deflazacort 6 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153171', 'Entocort')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153880', 'deflazacort 30 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '155323', 'methylprednisolone acetate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716092', 'betamethasone dipropionate 0.643 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738585', 'hydrocortisone Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738586', 'hydrocortisone 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738587', 'hydrocortisone 1000 MG [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738588', 'hydrocortisone Injection [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738589', 'hydrocortisone 1000 MG Injection [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738590', 'hydrocortisone 250 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738591', 'hydrocortisone 250 MG [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738592', 'hydrocortisone 250 MG Injection [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738594', 'hydrocortisone 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738595', 'hydrocortisone 500 MG [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738596', 'hydrocortisone 500 MG Injection [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738600', 'hydrocortisone 100 MG [Solu-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738602', 'hydrocortisone 100 MG [A-Hydrocort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738603', 'hydrocortisone Injection [A-Hydrocort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743702', 'methylprednisolone 125 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743703', 'methylprednisolone Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743704', 'methylprednisolone 125 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743705', 'methylprednisolone 125 MG [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743706', 'methylprednisolone Injection [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743707', 'methylprednisolone 125 MG Injection [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743719', 'methylprednisolone 500 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743720', 'methylprednisolone 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743721', 'methylprednisolone 500 MG [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743722', 'methylprednisolone 500 MG Injection [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743725', 'methylprednisolone 1000 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743726', 'methylprednisolone 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743727', 'methylprednisolone 1000 MG [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743729', 'methylprednisolone 1000 MG Injection [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743779', '1 ML methylprednisolone acetate 40 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743780', 'methylprednisolone Injection [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743781', '1 ML methylprednisolone acetate 40 MG/ML Injection [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743855', '1 ML methylprednisolone acetate 80 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1743856', '1 ML methylprednisolone acetate 80 MG/ML Injection [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744013', 'methylprednisolone 2000 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744015', 'methylprednisolone 2000 MG [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744018', 'methylprednisolone 40 MG [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744020', 'methylprednisolone 40 MG [A-MethaPred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744021', 'methylprednisolone Injection [A-MethaPred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1744024', 'methylprednisolone 125 MG [A-MethaPred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1792143', 'triamcinolone Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1792144', '1 ML triamcinolone acetonide 40 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1792145', 'triamcinolone Injection [Triesence]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812073', 'dexamethasone Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812078', 'dexamethasone phosphate 10 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1812094', 'dexamethasone Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869595', '{27 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870945', 'Emflaza')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870946', 'deflazacort 6 MG [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870947', 'deflazacort Oral Tablet [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870948', 'Emflaza Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870949', 'Emflaza Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870950', 'deflazacort 6 MG Oral Tablet [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870951', 'deflazacort 30 MG [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870952', 'deflazacort 30 MG Oral Tablet [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870953', 'deflazacort 18 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870954', 'deflazacort 18 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870955', 'deflazacort 18 MG [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870956', 'deflazacort 18 MG Oral Tablet [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870957', 'deflazacort 36 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870958', 'deflazacort 36 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870959', 'deflazacort 36 MG [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870960', 'deflazacort 36 MG Oral Tablet [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870961', 'deflazacort 22.75 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870962', 'deflazacort Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870963', 'deflazacort Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870964', 'deflazacort 22.75 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870965', 'deflazacort 22.75 MG/ML [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870966', 'deflazacort Oral Suspension [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870967', 'Emflaza Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870968', 'deflazacort 22.75 MG/ML Oral Suspension [Emflaza]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '19254', 'betamethasone dipropionate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1943550', '{49 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1947125', 'Zilretta')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1947127', 'triamcinolone Injection [Zilretta]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1947128', 'Zilretta Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1947131', 'triamcinolone acetonide 32 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1947132', 'triamcinolone acetonide 32 MG [Zilretta]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1947133', 'triamcinolone acetonide 32 MG Injection [Zilretta]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197545', 'cortisone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197576', 'dexamethasone 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197577', 'dexamethasone 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197579', 'dexamethasone 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197580', 'dexamethasone 1.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197581', 'dexamethasone 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197582', 'dexamethasone 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197583', 'dexamethasone 6 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197782', 'hydrocortisone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197783', 'hydrocortisone 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197787', 'hydrocortisone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197969', 'methylprednisolone 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197971', 'methylprednisolone 32 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197973', 'methylprednisolone 8 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198142', 'prednisolone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198144', 'prednisone 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198145', 'prednisone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198146', 'prednisone 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198148', 'prednisone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198301', 'triamcinolone 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198303', 'triamcinolone 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '19831', 'budesonide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199343', 'prednisolone 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199771', 'methylprednisolone 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1998481', '{49 (dexamethasone 1.5 MG Oral Tablet) } Pack [TaperDex 12 Day Taper]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1998482', '{21 (dexamethasone 1.5 MG Oral Tablet) } Pack [TaperDex 6 Day Taper]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199967', 'prednisolone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202645', 'Cortef')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202877', 'Kenalog')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203189', 'methylprednisolone sodium succinate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203220', 'betamethasone sodium phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203592', 'Solu-Cortef')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203594', 'A-Hydrocort')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203704', 'Dexasone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203789', 'Aristospan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203856', 'Solu-Medrol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203857', 'A-MethaPred')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205301', 'prednisone 5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205712', 'dexamethasone 4 MG Oral Tablet [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205717', 'dexamethasone 6 MG Oral Tablet [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '206997', 'prednisone 20 MG Oral Tablet [Deltasone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207136', 'methylprednisolone 2 MG Oral Tablet [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207137', 'methylprednisolone 8 MG Oral Tablet [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207138', 'methylprednisolone 16 MG Oral Tablet [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207141', 'methylprednisolone 32 MG Oral Tablet [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207190', 'methylprednisolone 40 MG Injection [A-MethaPred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207191', 'methylprednisolone 40 MG Injection [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207192', 'methylprednisolone 125 MG Injection [A-MethaPred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207193', 'methylprednisolone 62.5 MG/ML Injectable Solution [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208680', 'hydrocortisone 5 MG Oral Tablet [Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208712', 'hydrocortisone 10 MG Oral Tablet [Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208816', 'hydrocortisone 20 MG Oral Tablet [Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208947', 'hydrocortisone 100 MG Injection [A-Hydrocort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2118829', '{21 (dexamethasone 1.5 MG Oral Tablet) } Pack [HiDex 6-Day Taper]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2118835', '{27 (dexamethasone 1.5 MG Oral Tablet) } Pack [TaperDex 7-Day Taper]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2121587', '{39 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2121735', '{39 (dexamethasone 1.5 MG Oral Tablet) } Pack [Dxevo 11 Day Taper]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '215664', 'betamethasone dipropionate, augmented')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '21655', 'cortisone acetate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2168081', 'triamcinolone acetonide 80 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2168082', 'triamcinolone acetonide 80 MG/ML [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2168083', 'triamcinolone acetonide 80 MG/ML Injectable Suspension [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2168095', '1 ML triamcinolone acetonide 80 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2168096', 'triamcinolone Injection [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2168097', '1 ML triamcinolone acetonide 80 MG/ML Injection [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '22396', 'deflazacort')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '22584', 'Depo-Medrol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2261801', 'dexamethasone 20 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2261802', 'dexamethasone 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '226432', 'deflazacort 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '22690', 'dexamethasone acetate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2269303', 'budesonide 6 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2269304', 'budesonide Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2269305', '24 HR budesonide 6 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2269307', '24 HR budesonide 9 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '22694', 'dexamethasone trimethyl acetate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273102', 'Ortikos')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273103', 'budesonide 6 MG [Ortikos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273104', 'budesonide Extended Release Oral Capsule [Ortikos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273105', 'Ortikos Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273106', 'Ortikos Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273107', '24 HR budesonide 6 MG Extended Release Oral Capsule [Ortikos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273109', 'budesonide 9 MG [Ortikos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2273110', '24 HR budesonide 9 MG Extended Release Oral Capsule [Ortikos]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '227682', 'Decadron')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '227730', 'Deltasone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2286256', 'Hemady')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2286257', 'dexamethasone 20 MG [Hemady]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2286258', 'dexamethasone Oral Tablet [Hemady]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2286259', 'Hemady Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2286260', 'Hemady Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2286261', 'dexamethasone 20 MG Oral Tablet [Hemady]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '235486', 'dexamethasone phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2387355', '{25 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2387356', '{25 (dexamethasone 1.5 MG Oral Tablet) } Pack [Zcort 7 Day Taper]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '238754', 'hydrocortisone 25 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '238755', 'hydrocortisone 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399645', 'Alkindi')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399646', 'hydrocortisone 0.5 MG [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399647', 'hydrocortisone Oral Granules [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399648', 'Alkindi Granule Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399649', 'Alkindi Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399650', 'hydrocortisone 0.5 MG Oral Granules [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399653', 'hydrocortisone 1 MG [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399654', 'hydrocortisone 1 MG Oral Granules [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399657', 'hydrocortisone 2 MG [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399658', 'hydrocortisone 2 MG Oral Granules [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399660', 'hydrocortisone 5 MG [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2399661', 'hydrocortisone 5 MG Oral Granules [Alkindi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '245258', 'betamethasone 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2480108', '1 ML triamcinolone acetonide 40 MG/ML Injection [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249066', 'prednisolone 5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250788', 'hydrocortisone 100 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2539176', '2 ML triamcinolone hexacetonide 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2585221', '0.9 ML triamcinolone acetonide 40 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587882', 'budesonide 4 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587883', 'budesonide 4 MG Delayed Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587884', 'Tarpeyo')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587885', 'budesonide 4 MG [Tarpeyo]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587886', 'Tarpeyo Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587887', 'Tarpeyo Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587888', 'budesonide Delayed Release Oral Capsule [Tarpeyo]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2587889', 'budesonide 4 MG Delayed Release Oral Capsule [Tarpeyo]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '259966', 'methylprednisolone 4 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260125', 'prednisolone 25 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260330', 'methylprednisolone 4 MG Oral Tablet [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260409', 'prednisolone 1 MG/ML Oral Solution [Pediapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283077', 'prednisolone 3 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2878', 'cortisone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '29917', 'methylprednisolone sodium phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308709', 'betamethasone 0.6 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308718', 'betamethasone 4 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309696', 'dexamethasone phosphate 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310899', 'hydrocortisone 2 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311659', 'methylprednisolone 40 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312614', 'prednisolone 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312615', 'prednisone 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312617', 'prednisone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314099', 'methylprednisolone 62.5 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315187', 'prednisone 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315476', 'betamethasone 0.12 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315477', 'betamethasone 0.6 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315774', 'dexamethasone 0.25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315775', 'dexamethasone 0.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315776', 'dexamethasone 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315777', 'dexamethasone 1.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315778', 'dexamethasone 4 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315779', 'dexamethasone 6 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316285', 'methylprednisolone 2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316287', 'methylprednisolone 32 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316288', 'methylprednisolone 8 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317346', 'dexamethasone 2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317426', 'methylprednisolone 16 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317427', 'methylprednisolone 4 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317524', 'triamcinolone 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '3264', 'dexamethasone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '3265', 'dexamethasone isonicotinate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328161', 'methylprednisolone 16 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '329229', 'cortisone 5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '329583', 'betamethasone 3 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '330037', 'methylprednisolone 40 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '331514', 'betamethasone 4 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '332216', 'methylprednisolone 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '332617', 'betamethasone 0.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '332685', 'budesonide 3 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '332963', 'deflazacort 30 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '332964', 'deflazacort 6 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '332981', 'dexamethasone 3 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '332984', 'dexamethasone 0.4 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '340091', 'betamethasone 1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '340130', 'betamethasone 0.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '343033', 'dexamethasone 0.75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '343040', 'dexamethasone 0.75 MG Oral Tablet [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345816', 'dexamethasone 0.75 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '346173', 'methylprednisolone 62.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '348428', 'prednisolone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '358827', 'betamethasone acetate 3 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '362772', 'methylprednisolone Injectable Solution [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363482', 'dexamethasone Injectable Solution [Dexasone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365570', 'methylprednisolone Injectable Suspension [Depo-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365600', 'betamethasone Injectable Suspension [Celestone Soluspan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365675', 'triamcinolone Injectable Suspension [Kenalog]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '368772', 'methylprednisolone Oral Tablet [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369183', 'hydrocortisone Oral Tablet [Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369461', 'dexamethasone Oral Tablet [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370647', 'hydrocortisone Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370648', 'hydrocortisone Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370649', 'hydrocortisone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371049', 'betamethasone Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371053', 'betamethasone Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371056', 'betamethasone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371635', 'cortisone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371693', 'deflazacort Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371721', 'dexamethasone Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371725', 'dexamethasone Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371728', 'dexamethasone Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371729', 'dexamethasone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372866', 'methylprednisolone Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372868', 'methylprednisolone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373568', 'prednisolone Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373572', 'prednisolone Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373575', 'prednisolone Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373578', 'prednisolone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373583', 'prednisone Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373585', 'prednisone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '376656', 'methylprednisolone Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '378340', 'betamethasone Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '378635', 'hydrocortisone Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '379264', 'prednisolone Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '379265', 'betamethasone Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '380844', 'triamcinolone Injectable Suspension [Aristospan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '38546', 'triamcinolone hexacetonide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '385598', 'deflazacort 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '429199', 'prednisolone 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '435681', 'dexamethasone 2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '438889', 'dexamethasone 0.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451789', 'dexamethasone 2 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '47847', 'Celestone Soluspan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564044', 'dexamethasone 0.5 MG [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '566603', 'dexamethasone 4 MG [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '566608', 'dexamethasone 6 MG [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '567793', 'prednisone 20 MG [Deltasone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '567927', 'methylprednisolone 2 MG [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '567928', 'methylprednisolone 8 MG [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '567929', 'methylprednisolone 16 MG [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '567932', 'methylprednisolone 32 MG [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '567984', 'methylprednisolone 62.5 MG/ML [Solu-Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '569343', 'hydrocortisone 5 MG [Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '569375', 'hydrocortisone 10 MG [Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '569465', 'hydrocortisone 20 MG [Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574125', 'methylprednisolone 4 MG [Medrol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '575233', 'dexamethasone 0.75 MG [Decadron]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578803', 'betamethasone 3 MG/ML / betamethasone acetate 3 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578804', 'betamethasone 3 MG/ML / betamethasone acetate 3 MG/ML [Celestone Soluspan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '578806', 'betamethasone 3 MG/ML / betamethasone acetate 3 MG/ML Injectable Suspension [Celestone Soluspan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643123', 'prednisolone 10 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643125', 'prednisolone 15 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643127', 'prednisolone 30 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '647126', 'prednisolone Disintegrating Oral Tablet [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '647127', 'prednisolone 15 MG Disintegrating Oral Tablet [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668658', 'prednisolone 10 MG Disintegrating Oral Tablet [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668660', 'prednisolone 30 MG Disintegrating Oral Tablet [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '670084', 'betamethasone 0.12 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '6902', 'methylprednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '702306', 'prednisolone 4 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727885', 'triamcinolone Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '753380', 'Triesence')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '759481', '{51 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '759696', '{12 (dexamethasone 0.75 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '759697', '{35 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '762675', '{21 (methylprednisolone 4 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '792956', 'prednisolone Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '792957', 'prednisolone 1 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '793099', 'prednisolone 3 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '794979', 'prednisolone 2 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795094', 'MILLIPRED')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795095', 'prednisolone 2 MG/ML [MILLIPRED]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795096', 'prednisolone Oral Solution [MILLIPRED]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795097', 'prednisolone 2 MG/ML Oral Solution [MILLIPRED]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795716', '{12 (dexamethasone 0.75 MG Oral Tablet [Decadron]) } Pack [Decadron 5-12]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '797022', '{35 (dexamethasone 1.5 MG Oral Tablet) } Pack [DexPak TaperPak Junior 10 Day]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '797023', '{51 (dexamethasone 1.5 MG Oral Tablet) } Pack [DexPak TaperPak 13 Day]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '808116', 'prednisolone 5 MG [MILLIPRED]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '808117', 'prednisolone Oral Tablet [MILLIPRED]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '808118', 'prednisolone 5 MG Oral Tablet [MILLIPRED]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '814394', 'betamethasone acetate / betamethasone sodium phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '824886', 'Veripred')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '824887', 'prednisolone 4 MG/ML [Veripred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '824888', 'prednisolone Oral Solution [Veripred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '824889', 'prednisolone 4 MG/ML Oral Solution [Veripred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '828247', 'cortisone acetate 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '828248', 'cortisone acetate 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '834023', '{21 (methylprednisolone 4 MG Oral Tablet [Medrol]) } Pack [Medrol Dosepak]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '846192', '{21 (dexamethasone 1.5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '847225', '{21 (dexamethasone 1.5 MG Oral Tablet) } Pack [DexPak TaperPak 6 Day]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '854175', 'dexamethasone 0.7 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '8640', 'prednisone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '880649', 'dexamethasone 3 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '92354', 'prednisone Oral Tablet [Deltasone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '93720', 'prednisolone Oral Solution [Pediapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '96818', 'triamcinolone Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '96819', 'triamcinolone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '991399', 'budesonide 3 MG [Entocort]')
) AS t (system, code, display) ;