create or replace view irae__lab_interpretation_any as select * from (values
('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', '<', 'Off scale low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', '>', 'Off scale high')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'A', 'Abnormal')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'AA', 'Critical abnormal')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'AC', 'Anti-complementary substances present')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'B', 'Better')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'CAR', 'Carrier')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'Carrier', 'Carrier')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'D', 'Significant change down')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'DET', 'Detected')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'E', 'Equivocal')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'EX', 'outside threshold')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'EXP', 'Expected')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'H', 'High')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'H>', 'Significantly high')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'HH', 'Critical high')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'HM', 'Hold for Medical Review')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'HU', 'Significantly high')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'HX', 'above high threshold')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'I', 'Intermediate')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'IE', 'Insufficient evidence')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'IND', 'Indeterminate')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'L', 'Low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'L<', 'Significantly low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'LL', 'Critical low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'LU', 'Significantly low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'LX', 'below low threshold')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'MS', 'moderately susceptible')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'N', 'Normal')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'NCL', 'No CLSI defined breakpoint')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'ND', 'Not detected')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'NEG', 'Negative')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'NR', 'Non-reactive')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'NS', 'Non-susceptible')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'OBX', 'Interpretation qualifiers in separate OBX segments')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'ObservationInterpretationDetection', 'ObservationInterpretationDetection')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'ObservationInterpretationExpectation', 'ObservationInterpretationExpectation')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'POS', 'Positive')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'QCF', 'Quality control failure')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'R', 'Resistant')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'RR', 'Reactive')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'ReactivityObservationInterpretation', 'ReactivityObservationInterpretation')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'S', 'Susceptible')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'SDD', 'Susceptible-dose dependent')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'SYN-R', 'Synergy - resistant')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'SYN-S', 'Synergy - susceptible')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'TOX', 'Cytotoxic substance present')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'U', 'Significant change up')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'UNE', 'Unexpected')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'VS', 'very susceptible')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'W', 'Worse')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'WR', 'Weakly reactive')
) AS t (system, code, display) ;