create or replace view irae__lab_hdl as select * from (values
('http://loinc.org', 'LOINC_NUM', 'COMPONENT')
,('http://loinc.org', '92711-1', 'Lipoprotein.alpha.subparticle.small')
,('http://loinc.org', '48090-5', 'Cholesterol.in HDL/Cholesterol.in HDL+Cholesterol.in VLDL')
,('http://loinc.org', '86222-7', 'Lipoprotein.alpha 3')
,('http://loinc.org', '3044-5', 'Triglyceride+ester.in HDL')
,('http://loinc.org', '54467-6', 'Cholesterol.in HDL 2a/Cholesterol.in HDL.total')
,('http://loinc.org', '54468-4', 'Cholesterol.in HDL 2b/Cholesterol.in HDL.total')
,('http://loinc.org', '54469-2', 'Cholesterol.in HDL 3a/Cholesterol.in HDL.total')
,('http://loinc.org', '54470-0', 'Cholesterol.in HDL 3b/Cholesterol.in HDL.total')
,('http://loinc.org', '54471-8', 'Cholesterol.in HDL 3c/Cholesterol.in HDL.total')
,('http://loinc.org', '105517-7', 'HDL from lipid profile')
,('http://loinc.org', '49748-7', 'Lipoprotein.alpha')
,('http://loinc.org', '27340-9', 'Cholesterol.in HDL')
,('http://loinc.org', '53135-0', 'Cholesterol.in HDL')
,('http://loinc.org', '9322-9', 'Cholesterol.total/Cholesterol.in HDL')
,('http://loinc.org', '96596-2', 'Cholesterol.in HDL')
,('http://loinc.org', '54372-8', 'Cholesterol.in HDL')
,('http://loinc.org', '2085-9', 'Cholesterol.in HDL')
,('http://loinc.org', '2086-7', 'Cholesterol.in HDL')
,('http://loinc.org', '14646-4', 'Cholesterol.in HDL')
,('http://loinc.org', '14813-0', 'Lipoprotein.alpha')
,('http://loinc.org', '35197-3', 'Cholesterol.in HDL')
,('http://loinc.org', '50840-8', 'Cholesterol.in HDL')
,('http://loinc.org', '9832-7', 'Cholesterol.in HDL 2')
,('http://loinc.org', '26015-8', 'Cholesterol.in HDL 2')
,('http://loinc.org', '57936-7', 'Cholesterol.in HDL 2a')
,('http://loinc.org', '56132-4', 'Cholesterol.in HDL 2a')
,('http://loinc.org', '56133-2', 'Cholesterol.in HDL 2b')
,('http://loinc.org', '9833-5', 'Cholesterol.in HDL 3')
,('http://loinc.org', '35243-5', 'Cholesterol.in HDL 3')
,('http://loinc.org', '26017-4', 'Cholesterol.in HDL 3')
,('http://loinc.org', '57937-5', 'Cholesterol.in HDL 3a')
,('http://loinc.org', '47220-9', 'Cholesterol.in HDL 4+5')
,('http://loinc.org', '96589-7', 'Cholesterol.total/Cholesterol.in HDL')
,('http://loinc.org', '12772-0', 'Cholesterol.in HDL')
,('http://loinc.org', '49130-8', 'Cholesterol.in HDL')
,('http://loinc.org', '18263-4', 'Cholesterol.in HDL')
,('http://loinc.org', '12771-2', 'Cholesterol.in HDL')
,('http://loinc.org', '47221-7', 'Cholesterol.in HDL 1+2')
,('http://loinc.org', '26016-6', 'Cholesterol.in HDL 2')
,('http://loinc.org', '50409-2', 'Cholesterol.in HDL 2+3')
,('http://loinc.org', '2095-8', 'Cholesterol.in HDL/Cholesterol.total')
,('http://loinc.org', '70200-1', 'Cholesterol.in HDL/Cholesterol.total')
,('http://loinc.org', '13460-1', 'Cholesterol.in LDL/Cholesterol.in HDL')
,('http://loinc.org', '9830-1', 'Cholesterol.total/Cholesterol.in HDL')
,('http://loinc.org', '32309-7', 'Cholesterol.total/Cholesterol.in HDL')
,('http://loinc.org', '44733-4', 'Triglyceride/Cholesterol.in HDL')
,('http://loinc.org', '55607-6', 'Triglyceride/Cholesterol.in HDL')
,('http://loinc.org', '16616-5', 'Cholesterol.in HDL/Cholesterol.in LDL')
,('http://loinc.org', '11054-4', 'Cholesterol.in LDL/Cholesterol.in HDL')
,('http://loinc.org', '44915-7', 'Cholesterol.in LDL/Cholesterol.in HDL')
,('http://loinc.org', '43729-3', 'Lipoprotein.alpha.subparticle.large')
,('http://loinc.org', '43396-1', 'Cholesterol.non HDL')
,('http://loinc.org', '70204-3', 'Cholesterol.non HDL')
,('http://loinc.org', '56035-9', 'Apolipoprotein A-I/Cholesterol.in HDL')
,('http://loinc.org', '53528-6', 'Triglyceride.in HDL 3')
,('http://loinc.org', '53527-8', 'Triglyceride.in HDL 2')
,('http://loinc.org', '47228-2', 'Cholesterol.non HDL/Cholesterol.total')
,('http://loinc.org', '19250-0', 'Lipoprotein.alpha')
,('http://loinc.org', '62253-0', 'Lipoprotein.alpha')
,('http://loinc.org', '17845-9', 'Lipoprotein.alpha')
,('http://loinc.org', '2573-4', 'Lipoprotein.alpha')
,('http://loinc.org', '26822-7', 'Lipoprotein.alpha')
,('http://loinc.org', '17082-9', 'Lipoprotein.alpha')
,('http://loinc.org', '15121-7', 'Lipoprotein.alpha/Lipoprotein.total')
,('http://loinc.org', '44717-7', 'Lipoprotein.beta/Lipoprotein.alpha')
) AS t (system, code, display) ;