create or replace view irae__dx_cancer_skin as select * from (values
('http://snomed.info/sct', '1079121000119101', 'Primary basal cell carcinoma of skin of left hip (disorder)')
,('http://snomed.info/sct', '1079141000119107', 'Primary basal cell carcinoma of skin of left shoulder (disorder)')
,('http://snomed.info/sct', '1079181000119102', 'Primary basal cell carcinoma of skin of right hip (disorder)')
,('http://snomed.info/sct', '1079201000119101', 'Primary basal cell carcinoma of skin of right shoulder (disorder)')
,('http://snomed.info/sct', '1081021000119109', 'Malignant melanoma of skin of left lower limb (disorder)')
,('http://snomed.info/sct', '1082051000119106', 'Primary squamous cell carcinoma of skin of left upper limb (disorder)')
,('http://snomed.info/sct', '1082091000119101', 'Primary squamous cell carcinoma of skin of left hip (disorder)')
,('http://snomed.info/sct', '1082101000119106', 'Primary squamous cell carcinoma of skin of left lower limb (disorder)')
,('http://snomed.info/sct', '1082131000119104', 'Primary squamous cell carcinoma of skin of left shoulder (disorder)')
,('http://snomed.info/sct', '1082171000119101', 'Primary squamous cell carcinoma of skin of right upper limb (disorder)')
,('http://snomed.info/sct', '1082211000119104', 'Primary squamous cell carcinoma of skin of right hip (disorder)')
,('http://snomed.info/sct', '1082221000119106', 'Primary squamous cell carcinoma of skin of right lower limb (disorder)')
,('http://snomed.info/sct', '1082261000119101', 'Primary squamous cell carcinoma of skin of right shoulder (disorder)')
,('http://snomed.info/sct', '109264009', 'Overlapping malignant neoplasm of skin (disorder)')
,('http://snomed.info/sct', '109267002', 'Overlapping malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '109386008', 'Kaposis sarcoma of skin (disorder)')
,('http://snomed.info/sct', '10976631000119101', 'Leiomyosarcoma of skin of chest (disorder)')
,('http://snomed.info/sct', '1186616001', 'Primary Kaposi sarcoma of skin (disorder)')
,('http://snomed.info/sct', '1197324006', 'Metastatic malignant melanoma to skin (disorder)')
,('http://snomed.info/sct', '1236953005', 'Metastatic carcinoma to bone, connective tissue, skin and breast (disorder)')
,('http://snomed.info/sct', '1237424008', 'Metastatic carcinoma to foreskin (disorder)')
,('http://snomed.info/sct', '1237477003', 'Metastatic carcinoma to skin of head (disorder)')
,('http://snomed.info/sct', '1237478008', 'Metastatic carcinoma to skin of neck (disorder)')
,('http://snomed.info/sct', '1237519007', 'Metastatic carcinoma to skin of lower limb (disorder)')
,('http://snomed.info/sct', '1237520001', 'Metastatic carcinoma to skin of trunk (disorder)')
,('http://snomed.info/sct', '1237521002', 'Metastatic carcinoma to skin of upper limb (disorder)')
,('http://snomed.info/sct', '1254748001', 'Metastatic clear cell squamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '1254750009', 'Metastatic acantholytic squamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '1254753006', 'Metastatic verrucous carcinoma to skin of sole of foot (disorder)')
,('http://snomed.info/sct', '1254755004', 'Metastatic basosquamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '1259251005', 'Primary mucoepidermoid carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259260002', 'Primary mucinous eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259319007', 'Primary amelanotic malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259372006', 'Primary clear cell squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259373001', 'Primary spindle cell squamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259374007', 'Primary acantholytic squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259376009', 'Primary basosquamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259378005', 'Primary superficial spreading malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259379002', 'Primary nodular malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259380004', 'Primary acral lentiginous malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259382007', 'Primary epithelioid cell sarcoma of skin (disorder)')
,('http://snomed.info/sct', '1259390007', 'Primary carcinoma of foreskin (disorder)')
,('http://snomed.info/sct', '1259459009', 'Primary nodular basal cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259530006', 'Primary carcinoma of skin of lower limb (disorder)')
,('http://snomed.info/sct', '1259532003', 'Primary carcinoma of skin of trunk (disorder)')
,('http://snomed.info/sct', '1259533008', 'Primary carcinoma of skin of upper limb (disorder)')
,('http://snomed.info/sct', '1259567003', 'Primary eccrine ductal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259569000', 'Primary clear cell eccrine hidradenocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259571000', 'Primary small cell eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259573002', 'Primary apocrine adenocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259575009', 'Primary ceruminous gland adenocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259577001', 'Primary mixed eccrine/pilar adnexal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259578006', 'Primary undifferentiated adnexal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259587002', 'Primary carcinosarcoma of skin (disorder)')
,('http://snomed.info/sct', '1259592000', 'Primary eccrine porocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259593005', 'Primary digital papillary eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259594004', 'Primary adenoid cystic eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259596002', 'Primary microcystic adnexal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259599009', 'Primary eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259601006', 'Primary myxofibrosarcoma of skin (disorder)')
,('http://snomed.info/sct', '1259736002', 'Primary malignant blue nevus of skin (disorder)')
,('http://snomed.info/sct', '1259777003', 'Primary malignant eccrine spiradenoma of skin (disorder)')
,('http://snomed.info/sct', '1259778008', 'Primary malignant chondroid syringoma of skin (disorder)')
,('http://snomed.info/sct', '1259779000', 'Primary malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '1259780002', 'Primary superficial malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '1259781003', 'Primary giant cell malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '1259782005', 'Primary inflammatory malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '1259789001', 'Primary pleomorphic malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '1259797008', 'Primary Paget disease of skin of scrotum (disorder)')
,('http://snomed.info/sct', '1263651005', 'Metastatic mucoepidermoid carcinoma to skin (disorder)')
,('http://snomed.info/sct', '1264364008', 'Metastatic ceruminous adenocarcinoma to skin (disorder)')
,('http://snomed.info/sct', '1268699008', 'Primary pilomatrix carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1268881002', 'Primary malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1268906006', 'Primary Klatskin tumor (disorder)')
,('http://snomed.info/sct', '1268956001', 'Primary extramammary Paget disease of skin (disorder)')
,('http://snomed.info/sct', '15950061000119105', 'Primary malignant neoplasm of skin of right breast (disorder)')
,('http://snomed.info/sct', '15950221000119108', 'Primary malignant neoplasm of skin of left breast (disorder)')
,('http://snomed.info/sct', '15951021000119107', 'Malignant melanoma of skin of bilateral lower limbs (disorder)')
,('http://snomed.info/sct', '15951061000119102', 'Malignant melanoma of skin of bilateral upper limbs (disorder)')
,('http://snomed.info/sct', '16091131000119108', 'Primary angiosarcoma of skin of forehead (disorder)')
,('http://snomed.info/sct', '16091171000119106', 'Angiosarcoma of skin of cheek (disorder)')
,('http://snomed.info/sct', '16091251000119109', 'Primary angiosarcoma of skin of nose (disorder)')
,('http://snomed.info/sct', '16091371000119108', 'Primary angiosarcoma of skin of temporal region (disorder)')
,('http://snomed.info/sct', '16091411000119109', 'Primary angiosarcoma of skin of lip (disorder)')
,('http://snomed.info/sct', '16905141000119107', 'Primary malignant neoplasm of skin of right upper eyelid (disorder)')
,('http://snomed.info/sct', '16905341000119105', 'Primary malignant neoplasm of skin of right lower eyelid (disorder)')
,('http://snomed.info/sct', '16905541000119102', 'Primary malignant neoplasm of skin of left lower eyelid (disorder)')
,('http://snomed.info/sct', '16905581000119107', 'Primary malignant neoplasm of skin of left upper eyelid (disorder)')
,('http://snomed.info/sct', '188089003', 'Malignant neoplasm of skin of ear and external auditory canal (disorder)')
,('http://snomed.info/sct', '188090007', 'Malignant neoplasm of skin of auricle (ear) (disorder)')
,('http://snomed.info/sct', '188091006', 'Malignant neoplasm of skin of external auditory meatus (disorder)')
,('http://snomed.info/sct', '188095002', 'Malignant neoplasm of skin of cheek, external (disorder)')
,('http://snomed.info/sct', '188099008', 'Malignant neoplasm of skin of nose (external) (disorder)')
,('http://snomed.info/sct', '188100000', 'Malignant neoplasm of skin of temple (disorder)')
,('http://snomed.info/sct', '188102008', 'Malignant neoplasm of scalp and/or skin of neck (disorder)')
,('http://snomed.info/sct', '188103003', 'Malignant neoplasm of skin of scalp (disorder)')
,('http://snomed.info/sct', '188107002', 'Malignant neoplasm of skin of axillary fold (disorder)')
,('http://snomed.info/sct', '188110009', 'Malignant neoplasm of skin of abdominal wall (disorder)')
,('http://snomed.info/sct', '188121000', 'Malignant neoplasm of skin of upper arm (disorder)')
,('http://snomed.info/sct', '188122007', 'Malignant neoplasm of skin of forearm (disorder)')
,('http://snomed.info/sct', '188125009', 'Malignant neoplasm of skin of thumb (disorder)')
,('http://snomed.info/sct', '188132000', 'Malignant neoplasm of skin of popliteal fossa area (disorder)')
,('http://snomed.info/sct', '188133005', 'Malignant neoplasm of skin of lower leg (disorder)')
,('http://snomed.info/sct', '188135003', 'Malignant neoplasm of skin of heel (disorder)')
,('http://snomed.info/sct', '188138001', 'Malignant neoplasm of skin of great toe (disorder)')
,('http://snomed.info/sct', '188454009', 'Metastatic malignant neoplasm to skin of head (disorder)')
,('http://snomed.info/sct', '188458007', 'Metastatic malignant neoplasm to skin of shoulder and arm (disorder)')
,('http://snomed.info/sct', '233719000', 'Lymphangioleiomyomatosis of skin (disorder)')
,('http://snomed.info/sct', '238863004', 'Giant cell fibroblastoma of skin (disorder)')
,('http://snomed.info/sct', '243971001000119103', 'Malignant melanoma of skin of right ankle (disorder)')
,('http://snomed.info/sct', '249389151000119103', 'Malignant melanoma of skin of right wrist (disorder)')
,('http://snomed.info/sct', '253017000', 'Klatskins tumor (disorder)')
,('http://snomed.info/sct', '254650008', 'Malignant epithelial neoplasm of skin (disorder)')
,('http://snomed.info/sct', '254651007', 'Squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254652000', 'Clear cell squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254653005', 'Spindle cell squamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254654004', 'Acantholytic squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254701007', 'Basal cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254702000', 'Basosquamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254707006', 'Malignant skin tumor with eccrine differentiation (disorder)')
,('http://snomed.info/sct', '254708001', 'Eccrine porocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '254709009', 'Digital papillary eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254711000', 'Adenoid cystic eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254712007', 'Microcystic adnexal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254713002', 'Mucoepidermoid carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254714008', 'Mucinous eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254726003', 'Malignant skin tumor with apocrine differentiation (disorder)')
,('http://snomed.info/sct', '254727007', 'Extramammary Pagets disease of skin (disorder)')
,('http://snomed.info/sct', '254729005', 'Apudoma of skin (disorder)')
,('http://snomed.info/sct', '254730000', 'Superficial spreading malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254731001', 'Nodular malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254732008', 'Acral lentiginous malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254754005', 'Atypical fibroxanthoma of skin (disorder)')
,('http://snomed.info/sct', '254794007', 'Angiosarcoma of skin (disorder)')
,('http://snomed.info/sct', '254796009', 'Solitary fibrous tumor of skin (disorder)')
,('http://snomed.info/sct', '254797000', 'Malignant hemangiopericytoma of skin (disorder)')
,('http://snomed.info/sct', '254798005', 'Hemangioendothelioma of skin (disorder)')
,('http://snomed.info/sct', '254800003', 'Epithelioid cell sarcoma of skin (disorder)')
,('http://snomed.info/sct', '254908006', 'Malignant tumor of skin of penis (disorder)')
,('http://snomed.info/sct', '254909003', 'Carcinoma of foreskin (disorder)')
,('http://snomed.info/sct', '255068000', 'Carcinoma of bone, connective tissue, skin and breast (disorder)')
,('http://snomed.info/sct', '255093003', 'Malignant skin tumor with adnexal differentiation (disorder)')
,('http://snomed.info/sct', '271467005', 'Malignant neoplasm of bone, connective tissue, skin and breast (disorder)')
,('http://snomed.info/sct', '276738009', 'Primary signet ring cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '276750003', 'Malignant tumor of skin with pilar differentiation (disorder)')
,('http://snomed.info/sct', '276751004', 'Amelanotic malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '285307007', 'Squamous cell carcinoma of skin of upper lip (disorder)')
,('http://snomed.info/sct', '285308002', 'Squamous cell carcinoma of skin of lower lip (disorder)')
,('http://snomed.info/sct', '285309005', 'Squamous cell carcinoma of skin of cheek (disorder)')
,('http://snomed.info/sct', '286891000', 'Carcinoma of skin of head/neck (disorder)')
,('http://snomed.info/sct', '307603002', 'Malignant blue nevus of skin (disorder)')
,('http://snomed.info/sct', '307610008', 'Pilomatrix carcinoma of skin (disorder)')
,('http://snomed.info/sct', '311779007', 'Malignant neoplasm of skin of scapular region (disorder)')
,('http://snomed.info/sct', '314975005', 'Local recurrence of malignant tumor of skin (disorder)')
,('http://snomed.info/sct', '314976006', 'Local recurrence of malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '351961000119109', 'Malignant melanoma of skin of right upper limb (disorder)')
,('http://snomed.info/sct', '352001000119100', 'Malignant melanoma of skin of right lower limb (disorder)')
,('http://snomed.info/sct', '352201000119105', 'Malignant melanoma of skin of left upper limb (disorder)')
,('http://snomed.info/sct', '352381000119106', 'Primary malignant neoplasm of skin of left upper limb (disorder)')
,('http://snomed.info/sct', '352391000119109', 'Primary malignant neoplasm of skin of left ear (disorder)')
,('http://snomed.info/sct', '352421000119102', 'Primary malignant neoplasm of skin of left shoulder (disorder)')
,('http://snomed.info/sct', '352431000119104', 'Primary malignant neoplasm of skin of right ear (disorder)')
,('http://snomed.info/sct', '352461000119107', 'Primary malignant neoplasm of skin of right lower limb (disorder)')
,('http://snomed.info/sct', '352471000119101', 'Primary malignant neoplasm of skin of right shoulder (disorder)')
,('http://snomed.info/sct', '352481000119103', 'Primary malignant neoplasm of skin of left lower limb (disorder)')
,('http://snomed.info/sct', '355141000119106', 'Primary malignant neoplasm of skin of right upper limb (disorder)')
,('http://snomed.info/sct', '363450006', 'Malignant tumor of foreskin (disorder)')
,('http://snomed.info/sct', '372122006', 'Malignant neoplasm of skin head and neck (disorder)')
,('http://snomed.info/sct', '372123001', 'Primary malignant neoplasm of skin head and neck (disorder)')
,('http://snomed.info/sct', '372124007', 'Malignant neoplasm of skin of lower limb (disorder)')
,('http://snomed.info/sct', '372125008', 'Carcinoma of skin of lower limb (disorder)')
,('http://snomed.info/sct', '372126009', 'Malignant neoplasm of skin of trunk (disorder)')
,('http://snomed.info/sct', '372127000', 'Carcinoma of skin of trunk (disorder)')
,('http://snomed.info/sct', '372128005', 'Malignant neoplasm of skin of upper limb (disorder)')
,('http://snomed.info/sct', '372129002', 'Carcinoma of skin of upper limb (disorder)')
,('http://snomed.info/sct', '372130007', 'Malignant neoplasm of skin (disorder)')
,('http://snomed.info/sct', '398670003', 'Pigmented dermatofibrosarcoma protuberans of skin (disorder)')
,('http://snomed.info/sct', '398903003', 'Pleomorphic malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '399897004', 'Basal cell carcinoma of postauricular skin (disorder)')
,('http://snomed.info/sct', '399934007', 'Basal cell carcinoma of preauricular skin (disorder)')
,('http://snomed.info/sct', '400173004', 'Eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '400175006', 'Myxofibrosarcoma of skin (disorder)')
,('http://snomed.info/sct', '400375351000119102', 'Malignant melanoma of skin of left ankle (disorder)')
,('http://snomed.info/sct', '402523001', 'Basal cell carcinoma of truncal skin (disorder)')
,('http://snomed.info/sct', '402652009', 'Malignant vascular tumor of skin (disorder)')
,('http://snomed.info/sct', '402819001', 'Basal cell carcinoma of skin of lip (disorder)')
,('http://snomed.info/sct', '402873007', 'Malignant fibrohistiocytic tumor of skin (disorder)')
,('http://snomed.info/sct', '402879006', 'T-cell leukemic infiltration of skin (disorder)')
,('http://snomed.info/sct', '402882001', 'Hodgkins disease affecting skin (disorder)')
,('http://snomed.info/sct', '403458008', 'Localized skin involvement by breast carcinoma (disorder)')
,('http://snomed.info/sct', '403711001', 'Primary malignant neoplasm of skin due to psoralen and longwave ultraviolet radiation therapy (disorder)')
,('http://snomed.info/sct', '403729006', 'Malignant neoplasm of skin caused by radiation (disorder)')
,('http://snomed.info/sct', '403742006', 'Malignant neoplasm of skin caused by arsenic (disorder)')
,('http://snomed.info/sct', '403892001', 'Squamous cell carcinoma of skin of face (disorder)')
,('http://snomed.info/sct', '403894000', 'Squamous cell carcinoma of skin of ear (disorder)')
,('http://snomed.info/sct', '403898002', 'Squamous cell carcinoma of skin of lower extremity (disorder)')
,('http://snomed.info/sct', '403899005', 'Squamous cell carcinoma of skin of trunk (disorder)')
,('http://snomed.info/sct', '403939009', 'Eccrine ductal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '403940006', 'Clear cell eccrine hidradenocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '403941005', 'Malignant cylindroma of skin (disorder)')
,('http://snomed.info/sct', '403942003', 'Malignant eccrine spiradenoma of skin (disorder)')
,('http://snomed.info/sct', '403943008', 'Malignant chondroid syringoma of skin (disorder)')
,('http://snomed.info/sct', '403944002', 'Small cell eccrine carcinoma of skin (disorder)')
,('http://snomed.info/sct', '403949007', 'Apocrine adenocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '403951006', 'Ceruminous gland adenocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '403954003', 'Mixed eccrine/pilar adnexal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '403955002', 'Undifferentiated adnexal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '404011000', 'Plexiform fibrohistiocytic tumor of skin (disorder)')
,('http://snomed.info/sct', '404013002', 'Angiomatoid fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '404014008', 'Malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '404015009', 'Superficial malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '404016005', 'Giant cell malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '404017001', 'Inflammatory malignant fibrous histiocytoma of skin (disorder)')
,('http://snomed.info/sct', '404045007', 'Epithelioid leiomyosarcoma of skin (disorder)')
,('http://snomed.info/sct', '404046008', 'Myxoid leiomyosarcoma of skin (disorder)')
,('http://snomed.info/sct', '404087009', 'Carcinosarcoma of skin (disorder)')
,('http://snomed.info/sct', '404091004', 'Malignant infiltration of skin by underlying tumor (disorder)')
,('http://snomed.info/sct', '404092006', 'Metastatic carcinoma to skin (disorder)')
,('http://snomed.info/sct', '404093001', 'Sarcomatous metastasis in skin (disorder)')
,('http://snomed.info/sct', '404122003', 'Leukemic infiltration of skin (chronic T-cell lymphocytic leukemia) (disorder)')
,('http://snomed.info/sct', '404123008', 'Leukemic infiltration of skin (T-cell prolymphocytic leukemia) (disorder)')
,('http://snomed.info/sct', '404124002', 'Leukemic infiltration of skin (T-cell lymphoblastic leukemia) (disorder)')
,('http://snomed.info/sct', '404135007', 'Angiocentric natural killer/T-cell malignant lymphoma involving skin (disorder)')
,('http://snomed.info/sct', '404136008', 'Aggressive natural killer-cell leukemia involving skin (disorder)')
,('http://snomed.info/sct', '404137004', 'Precursor B-cell lymphoblastic lymphoma involving skin (disorder)')
,('http://snomed.info/sct', '404138009', 'Small lymphocytic B-cell lymphoma involving skin (disorder)')
,('http://snomed.info/sct', '404139001', 'Leukemic infiltration of skin in hairy-cell leukemia (disorder)')
,('http://snomed.info/sct', '404147001', 'Follicular center B-cell lymphoma (nodal/systemic with skin involvement) (disorder)')
,('http://snomed.info/sct', '404148006', 'Diffuse large B-cell lymphoma (nodal/systemic with skin involvement) (disorder)')
,('http://snomed.info/sct', '404149003', 'Lymphoplasmacytic B-cell lymphoma, nodal/systemic with skin involvement (disorder)')
,('http://snomed.info/sct', '404150003', 'Mantle cell B-cell lymphoma (nodal/systemic with skin involvement) (disorder)')
,('http://snomed.info/sct', '404151004', 'Leukemic infiltration of skin in myeloid leukemia (disorder)')
,('http://snomed.info/sct', '404152006', 'Leukemic infiltration of skin in acute myeloid leukemia (disorder)')
,('http://snomed.info/sct', '404153001', 'Leukemic infiltration of skin in chronic myeloid leukemia (disorder)')
,('http://snomed.info/sct', '404154007', 'Leukemic infiltration of skin in monocytic leukemia (disorder)')
,('http://snomed.info/sct', '404155008', 'Granulocytic sarcoma affecting skin (disorder)')
,('http://snomed.info/sct', '404156009', 'Leukemic infiltration of skin (disorder)')
,('http://snomed.info/sct', '404157000', 'Specific skin infiltration in Hodgkins disease (disorder)')
,('http://snomed.info/sct', '404169008', 'Malignant histiocytosis involving skin (disorder)')
,('http://snomed.info/sct', '404172001', 'Mast cell leukemia affecting skin (disorder)')
,('http://snomed.info/sct', '423280002', 'Malignant melanoma of skin of canthus of eye (disorder)')
,('http://snomed.info/sct', '423284006', 'Squamous cell carcinoma of skin of neck (disorder)')
,('http://snomed.info/sct', '423425006', 'Malignant neoplasm of skin of eyelid (disorder)')
,('http://snomed.info/sct', '423447006', 'Malignant melanoma of skin of lower eyelid (disorder)')
,('http://snomed.info/sct', '423494003', 'Malignant melanoma of skin of upper eyelid (disorder)')
,('http://snomed.info/sct', '424302003', 'Malignant melanoma of skin of lower lip (disorder)')
,('http://snomed.info/sct', '424487008', 'Malignant melanoma of skin of upper lip (disorder)')
,('http://snomed.info/sct', '429114002', 'Malignant basal cell neoplasm of skin (disorder)')
,('http://snomed.info/sct', '443136000', 'Malignant neoplasm of skin of face (disorder)')
,('http://snomed.info/sct', '447712006', 'Malignant melanoma of skin of anus (disorder)')
,('http://snomed.info/sct', '447738006', 'Pagets disease of skin of scrotum (disorder)')
,('http://snomed.info/sct', '448273006', 'Malignant melanoma of skin of scrotum (disorder)')
,('http://snomed.info/sct', '448298007', 'Malignant melanoma of skin of penis (disorder)')
,('http://snomed.info/sct', '448300007', 'Malignant melanoma of skin of vulva (disorder)')
,('http://snomed.info/sct', '448447004', 'Non-Hodgkins lymphoma of skin (disorder)')
,('http://snomed.info/sct', '448865007', 'Follicular non-Hodgkins lymphoma of skin (disorder)')
,('http://snomed.info/sct', '449217008', 'Diffuse non-Hodgkins lymphoma of skin (disorder)')
,('http://snomed.info/sct', '449309003', 'Malignant neoplasm of skin of scrotum (disorder)')
,('http://snomed.info/sct', '449416001', 'Malignant epithelial neoplasm of skin of anus (disorder)')
,('http://snomed.info/sct', '449630001', 'Metastatic malignant neoplasm to skin of lower leg (disorder)')
,('http://snomed.info/sct', '449631002', 'Metastatic malignant neoplasm to skin of upper arm (disorder)')
,('http://snomed.info/sct', '449634005', 'Primary malignant neoplasm of skin of lower leg (disorder)')
,('http://snomed.info/sct', '449636007', 'Malignant melanoma of skin of lower leg (disorder)')
,('http://snomed.info/sct', '449637003', 'Malignant melanoma of skin of upper arm (disorder)')
,('http://snomed.info/sct', '455733521000119103', 'Primary squamous cell carcinoma of skin of head and/or neck (disorder)')
,('http://snomed.info/sct', '688321000119107', 'Primary malignant neoplasm of skin of bridge of nose (disorder)')
,('http://snomed.info/sct', '688381000119106', 'Primary malignant neoplasm of skin of ala nasi (disorder)')
,('http://snomed.info/sct', '688411000119109', 'Primary malignant neoplasm of skin of tip of nose (disorder)')
,('http://snomed.info/sct', '689211000119102', 'Primary squamous cell carcinoma of perianal skin (disorder)')
,('http://snomed.info/sct', '721540005', 'Primary adnexal carcinoma of skin (disorder)')
,('http://snomed.info/sct', '721541009', 'Primary malignant sarcoma of skin (disorder)')
,('http://snomed.info/sct', '721762007', 'Adult T-cell leukemia/lymphoma of skin (disorder)')
,('http://snomed.info/sct', '722712000', 'Occupational cancer of skin (disorder)')
,('http://snomed.info/sct', '724866001', 'Primary malignant neoplasm of skin due to and following radiotherapy (disorder)')
,('http://snomed.info/sct', '726019003', 'Familial malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '78461000119105', 'Metastatic squamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '79281000119106', 'Primary adenocarcinoma of skin (disorder)')
,('http://snomed.info/sct', '808558991000119105', 'Malignant melanoma of skin of left forearm (disorder)')
,('http://snomed.info/sct', '827186009', 'Metastatic malignant neoplasm to skin of hip and skin of lower leg (disorder)')
,('http://snomed.info/sct', '91231000119104', 'Metastatic adenocarcinoma to skin (disorder)')
,('http://snomed.info/sct', '91251000119105', 'Small cell carcinoma metastatic to skin (disorder)')
,('http://snomed.info/sct', '93209006', 'Malignant melanoma of perianal skin (disorder)')
,('http://snomed.info/sct', '93210001', 'Malignant melanoma of skin of abdomen (disorder)')
,('http://snomed.info/sct', '93211002', 'Malignant melanoma of skin of ankle (disorder)')
,('http://snomed.info/sct', '93213004', 'Malignant melanoma of skin of axilla (disorder)')
,('http://snomed.info/sct', '93214005', 'Malignant melanoma of skin of back (disorder)')
,('http://snomed.info/sct', '93215006', 'Malignant melanoma of skin of breast (disorder)')
,('http://snomed.info/sct', '93216007', 'Malignant melanoma of skin of buttock (disorder)')
,('http://snomed.info/sct', '93217003', 'Malignant melanoma of skin of cheek (disorder)')
,('http://snomed.info/sct', '93218008', 'Malignant melanoma of skin of chest (disorder)')
,('http://snomed.info/sct', '93219000', 'Malignant melanoma of skin of chin (disorder)')
,('http://snomed.info/sct', '93220006', 'Malignant melanoma of skin of ear (disorder)')
,('http://snomed.info/sct', '93221005', 'Malignant melanoma of skin of elbow (disorder)')
,('http://snomed.info/sct', '93222003', 'Malignant melanoma of skin of external auditory canal (disorder)')
,('http://snomed.info/sct', '93223008', 'Malignant melanoma of skin of eyebrow (disorder)')
,('http://snomed.info/sct', '93224002', 'Malignant melanoma of skin of eyelid (disorder)')
,('http://snomed.info/sct', '93225001', 'Malignant melanoma of skin of face (disorder)')
,('http://snomed.info/sct', '93226000', 'Malignant melanoma of skin of finger (disorder)')
,('http://snomed.info/sct', '93227009', 'Malignant melanoma of skin of foot (disorder)')
,('http://snomed.info/sct', '93228004', 'Malignant melanoma of skin of forearm (disorder)')
,('http://snomed.info/sct', '93229007', 'Malignant melanoma of skin of forehead (disorder)')
,('http://snomed.info/sct', '93230002', 'Malignant melanoma of skin of groin (disorder)')
,('http://snomed.info/sct', '93636004', 'Malignant melanoma of skin of hand (disorder)')
,('http://snomed.info/sct', '93637008', 'Malignant melanoma of skin of hip (disorder)')
,('http://snomed.info/sct', '93638003', 'Malignant melanoma of skin of knee (disorder)')
,('http://snomed.info/sct', '93640008', 'Malignant melanoma of skin of lip (disorder)')
,('http://snomed.info/sct', '93641007', 'Malignant melanoma of skin of lower limb (disorder)')
,('http://snomed.info/sct', '93642000', 'Malignant melanoma of skin of neck (disorder)')
,('http://snomed.info/sct', '93643005', 'Malignant melanoma of skin of nose (disorder)')
,('http://snomed.info/sct', '93644004', 'Malignant melanoma of skin of perineum (disorder)')
,('http://snomed.info/sct', '93645003', 'Malignant melanoma of skin of popliteal area (disorder)')
,('http://snomed.info/sct', '93646002', 'Malignant melanoma of skin of scalp (disorder)')
,('http://snomed.info/sct', '93647006', 'Malignant melanoma of skin of shoulder (disorder)')
,('http://snomed.info/sct', '93648001', 'Malignant melanoma of skin of temporal region (disorder)')
,('http://snomed.info/sct', '93649009', 'Malignant melanoma of skin of thigh (disorder)')
,('http://snomed.info/sct', '93650009', 'Malignant melanoma of skin of toe (disorder)')
,('http://snomed.info/sct', '93651008', 'Malignant melanoma of skin of trunk (disorder)')
,('http://snomed.info/sct', '93652001', 'Malignant melanoma of skin of umbilicus (disorder)')
,('http://snomed.info/sct', '93653006', 'Malignant melanoma of skin of upper limb (disorder)')
,('http://snomed.info/sct', '93654000', 'Malignant melanoma of skin of wrist (disorder)')
,('http://snomed.info/sct', '93655004', 'Malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '93663003', 'Primary malignant neoplasm of skin with adnexal differentiation (disorder)')
,('http://snomed.info/sct', '93956001', 'Primary malignant neoplasm of perianal skin (disorder)')
,('http://snomed.info/sct', '939595491000119108', 'Malignant melanoma of skin of right forearm (disorder)')
,('http://snomed.info/sct', '94007006', 'Primary malignant neoplasm of skin of abdomen (disorder)')
,('http://snomed.info/sct', '94008001', 'Primary malignant neoplasm of skin of ankle (disorder)')
,('http://snomed.info/sct', '94010004', 'Primary malignant neoplasm of skin of axilla (disorder)')
,('http://snomed.info/sct', '94011000', 'Primary malignant neoplasm of skin of back (disorder)')
,('http://snomed.info/sct', '94012007', 'Primary malignant neoplasm of skin of breast (disorder)')
,('http://snomed.info/sct', '94013002', 'Primary malignant neoplasm of skin of buttock (disorder)')
,('http://snomed.info/sct', '94014008', 'Primary malignant neoplasm of skin of cheek (disorder)')
,('http://snomed.info/sct', '94015009', 'Primary malignant neoplasm of skin of chest (disorder)')
,('http://snomed.info/sct', '94016005', 'Primary malignant neoplasm of skin of chin (disorder)')
,('http://snomed.info/sct', '94017001', 'Primary malignant neoplasm of skin of ear (disorder)')
,('http://snomed.info/sct', '94018006', 'Primary malignant neoplasm of skin of elbow (disorder)')
,('http://snomed.info/sct', '94019003', 'Primary malignant neoplasm of skin of external auditory canal (disorder)')
,('http://snomed.info/sct', '94020009', 'Primary malignant neoplasm of skin of eyebrow (disorder)')
,('http://snomed.info/sct', '94021008', 'Primary malignant neoplasm of skin of eyelid (disorder)')
,('http://snomed.info/sct', '94022001', 'Primary malignant neoplasm of skin of face (disorder)')
,('http://snomed.info/sct', '94023006', 'Primary malignant neoplasm of skin of finger (disorder)')
,('http://snomed.info/sct', '94024000', 'Primary malignant neoplasm of skin of foot (disorder)')
,('http://snomed.info/sct', '94025004', 'Primary malignant neoplasm of skin of forearm (disorder)')
,('http://snomed.info/sct', '94026003', 'Primary malignant neoplasm of skin of forehead (disorder)')
,('http://snomed.info/sct', '94027007', 'Primary malignant neoplasm of skin of groin (disorder)')
,('http://snomed.info/sct', '94028002', 'Primary malignant neoplasm of skin of hand (disorder)')
,('http://snomed.info/sct', '94029005', 'Primary malignant neoplasm of skin of hip (disorder)')
,('http://snomed.info/sct', '94030000', 'Primary malignant neoplasm of skin of knee (disorder)')
,('http://snomed.info/sct', '94032008', 'Primary malignant neoplasm of skin of lip (disorder)')
,('http://snomed.info/sct', '94033003', 'Primary malignant neoplasm of skin of lower limb (disorder)')
,('http://snomed.info/sct', '94034009', 'Primary malignant neoplasm of skin of neck (disorder)')
,('http://snomed.info/sct', '94035005', 'Primary malignant neoplasm of skin of nose (disorder)')
,('http://snomed.info/sct', '94036006', 'Primary malignant neoplasm of skin of perineum (disorder)')
,('http://snomed.info/sct', '94037002', 'Primary malignant neoplasm of skin of popliteal area (disorder)')
,('http://snomed.info/sct', '94038007', 'Primary malignant neoplasm of skin of scalp (disorder)')
,('http://snomed.info/sct', '94039004', 'Primary malignant neoplasm of skin of shoulder (disorder)')
,('http://snomed.info/sct', '94040002', 'Primary malignant neoplasm of skin of temporal region (disorder)')
,('http://snomed.info/sct', '94041003', 'Primary malignant neoplasm of skin of thigh (disorder)')
,('http://snomed.info/sct', '94042005', 'Primary malignant neoplasm of skin of toe (disorder)')
,('http://snomed.info/sct', '94043000', 'Primary malignant neoplasm of skin of trunk (disorder)')
,('http://snomed.info/sct', '94044006', 'Primary malignant neoplasm of skin of umbilicus (disorder)')
,('http://snomed.info/sct', '94045007', 'Primary malignant neoplasm of skin of upper limb (disorder)')
,('http://snomed.info/sct', '94046008', 'Primary malignant neoplasm of skin of wrist (disorder)')
,('http://snomed.info/sct', '94047004', 'Primary malignant neoplasm of skin (disorder)')
,('http://snomed.info/sct', '94159002', 'Metastatic malignant neoplasm to adnexa of skin (disorder)')
,('http://snomed.info/sct', '94483003', 'Metastatic malignant neoplasm to perianal skin (disorder)')
,('http://snomed.info/sct', '94539009', 'Metastatic malignant neoplasm to skin of abdomen (disorder)')
,('http://snomed.info/sct', '94540006', 'Metastatic malignant neoplasm to skin of ankle (disorder)')
,('http://snomed.info/sct', '94542003', 'Metastatic malignant neoplasm to skin of axilla (disorder)')
,('http://snomed.info/sct', '94543008', 'Metastatic malignant neoplasm to skin of back (disorder)')
,('http://snomed.info/sct', '94544002', 'Metastatic malignant neoplasm to skin of breast (disorder)')
,('http://snomed.info/sct', '94545001', 'Metastatic malignant neoplasm to skin of buttock (disorder)')
,('http://snomed.info/sct', '94546000', 'Metastatic malignant neoplasm to skin of cheek (disorder)')
,('http://snomed.info/sct', '94547009', 'Metastatic malignant neoplasm to skin of chest (disorder)')
,('http://snomed.info/sct', '94548004', 'Metastatic malignant neoplasm to skin of chin (disorder)')
,('http://snomed.info/sct', '94549007', 'Metastatic malignant neoplasm to skin of ear (disorder)')
,('http://snomed.info/sct', '94550007', 'Metastatic malignant neoplasm to skin of elbow (disorder)')
,('http://snomed.info/sct', '94551006', 'Metastatic malignant neoplasm to skin of external auditory canal (disorder)')
,('http://snomed.info/sct', '94552004', 'Metastatic malignant neoplasm to skin of eyebrow (disorder)')
,('http://snomed.info/sct', '94553009', 'Metastatic malignant neoplasm to skin of eyelid (disorder)')
,('http://snomed.info/sct', '94554003', 'Metastatic malignant neoplasm to skin of face (disorder)')
,('http://snomed.info/sct', '94555002', 'Metastatic malignant neoplasm to skin of finger (disorder)')
,('http://snomed.info/sct', '94556001', 'Metastatic malignant neoplasm to skin of foot (disorder)')
,('http://snomed.info/sct', '94557005', 'Metastatic malignant neoplasm to skin of forearm (disorder)')
,('http://snomed.info/sct', '94558000', 'Metastatic malignant neoplasm to skin of forehead (disorder)')
,('http://snomed.info/sct', '94559008', 'Metastatic malignant neoplasm to skin of groin (disorder)')
,('http://snomed.info/sct', '94560003', 'Metastatic malignant neoplasm to skin of hand (disorder)')
,('http://snomed.info/sct', '94561004', 'Metastatic malignant neoplasm to skin of hip (disorder)')
,('http://snomed.info/sct', '94562006', 'Metastatic malignant neoplasm to skin of knee (disorder)')
,('http://snomed.info/sct', '94564007', 'Metastatic malignant neoplasm to skin of lip (disorder)')
,('http://snomed.info/sct', '94565008', 'Metastatic malignant neoplasm to skin of lower limb (disorder)')
,('http://snomed.info/sct', '94566009', 'Metastatic malignant neoplasm to skin of neck (disorder)')
,('http://snomed.info/sct', '94567000', 'Metastatic malignant neoplasm to skin of nose (disorder)')
,('http://snomed.info/sct', '94568005', 'Metastatic malignant neoplasm to skin of perineum (disorder)')
,('http://snomed.info/sct', '94569002', 'Metastatic malignant neoplasm to skin of popliteal area (disorder)')
,('http://snomed.info/sct', '94570001', 'Metastatic malignant neoplasm to skin of scalp (disorder)')
,('http://snomed.info/sct', '94571002', 'Metastatic malignant neoplasm to skin of shoulder (disorder)')
,('http://snomed.info/sct', '94572009', 'Metastatic malignant neoplasm to skin of temporal region (disorder)')
,('http://snomed.info/sct', '94573004', 'Metastatic malignant neoplasm to skin of thigh (disorder)')
,('http://snomed.info/sct', '94574005', 'Metastatic malignant neoplasm to skin of toe (disorder)')
,('http://snomed.info/sct', '94575006', 'Metastatic malignant neoplasm to skin of trunk (disorder)')
,('http://snomed.info/sct', '94576007', 'Metastatic malignant neoplasm to skin of umbilicus (disorder)')
,('http://snomed.info/sct', '94577003', 'Metastatic malignant neoplasm to skin of upper limb (disorder)')
,('http://snomed.info/sct', '94578008', 'Metastatic malignant neoplasm to skin of wrist (disorder)')
,('http://snomed.info/sct', '94579000', 'Metastatic malignant neoplasm to skin (disorder)')
,('http://snomed.info/sct', '94728008', 'Neoplasm of uncertain behavior of adnexa of skin (disorder)')
,('http://snomed.info/sct', '94996007', 'Neoplasm of uncertain behavior of perianal skin (disorder)')
,('http://snomed.info/sct', '95047009', 'Neoplasm of uncertain behavior of skin of abdomen (disorder)')
,('http://snomed.info/sct', '95048004', 'Neoplasm of uncertain behavior of skin of ankle (disorder)')
,('http://snomed.info/sct', '95049007', 'Neoplasm of uncertain behavior of skin of upper arm (disorder)')
,('http://snomed.info/sct', '95050007', 'Neoplasm of uncertain behavior of skin of axilla (disorder)')
,('http://snomed.info/sct', '95051006', 'Neoplasm of uncertain behavior of skin of back (disorder)')
,('http://snomed.info/sct', '95052004', 'Neoplasm of uncertain behavior of skin of breast (disorder)')
,('http://snomed.info/sct', '95053009', 'Neoplasm of uncertain behavior of skin of buttock (disorder)')
,('http://snomed.info/sct', '95054003', 'Neoplasm of uncertain behavior of skin of cheek (disorder)')
,('http://snomed.info/sct', '95055002', 'Neoplasm of uncertain behavior of skin of chest (disorder)')
,('http://snomed.info/sct', '95056001', 'Neoplasm of uncertain behavior of skin of chin (disorder)')
,('http://snomed.info/sct', '95057005', 'Neoplasm of uncertain behavior of skin of ear (disorder)')
,('http://snomed.info/sct', '95058000', 'Neoplasm of uncertain behavior of skin of elbow (disorder)')
,('http://snomed.info/sct', '95059008', 'Neoplasm of uncertain behavior of skin of external auditory canal (disorder)')
,('http://snomed.info/sct', '95060003', 'Neoplasm of uncertain behavior of skin of eyebrow (disorder)')
,('http://snomed.info/sct', '95061004', 'Neoplasm of uncertain behavior of skin of eyelid (disorder)')
,('http://snomed.info/sct', '95062006', 'Neoplasm of uncertain behavior of skin of face (disorder)')
,('http://snomed.info/sct', '95063001', 'Neoplasm of uncertain behavior of skin of finger (disorder)')
,('http://snomed.info/sct', '95064007', 'Neoplasm of uncertain behavior of skin of foot (disorder)')
,('http://snomed.info/sct', '95065008', 'Neoplasm of uncertain behavior of skin of forearm (disorder)')
,('http://snomed.info/sct', '95066009', 'Neoplasm of uncertain behavior of skin of forehead (disorder)')
,('http://snomed.info/sct', '95067000', 'Neoplasm of uncertain behavior of skin of groin (disorder)')
,('http://snomed.info/sct', '95068005', 'Neoplasm of uncertain behavior of skin of hand (disorder)')
,('http://snomed.info/sct', '95069002', 'Neoplasm of uncertain behavior of skin of hip (disorder)')
,('http://snomed.info/sct', '95070001', 'Neoplasm of uncertain behavior of skin of knee (disorder)')
,('http://snomed.info/sct', '95071002', 'Neoplasm of uncertain behavior of skin of lower leg (disorder)')
,('http://snomed.info/sct', '95072009', 'Neoplasm of uncertain behavior of skin of lip (disorder)')
,('http://snomed.info/sct', '95073004', 'Neoplasm of uncertain behavior of skin of lower limb (disorder)')
,('http://snomed.info/sct', '95074005', 'Neoplasm of uncertain behavior of skin of neck (disorder)')
,('http://snomed.info/sct', '95075006', 'Neoplasm of uncertain behavior of skin of nose (disorder)')
,('http://snomed.info/sct', '95076007', 'Neoplasm of uncertain behavior of skin of perineum (disorder)')
,('http://snomed.info/sct', '95077003', 'Neoplasm of uncertain behavior of skin of popliteal area (disorder)')
,('http://snomed.info/sct', '95078008', 'Neoplasm of uncertain behavior of skin of scalp (disorder)')
,('http://snomed.info/sct', '95079000', 'Neoplasm of uncertain behavior of skin of shoulder (disorder)')
,('http://snomed.info/sct', '95080002', 'Neoplasm of uncertain behavior of skin of temporal region (disorder)')
,('http://snomed.info/sct', '95081003', 'Neoplasm of uncertain behavior of skin of thigh (disorder)')
,('http://snomed.info/sct', '95082005', 'Neoplasm of uncertain behavior of skin of toe (disorder)')
,('http://snomed.info/sct', '95083000', 'Neoplasm of uncertain behavior of skin of trunk (disorder)')
,('http://snomed.info/sct', '95084006', 'Neoplasm of uncertain behavior of skin of umbilicus (disorder)')
,('http://snomed.info/sct', '95085007', 'Neoplasm of uncertain behavior of skin of upper limb (disorder)')
,('http://snomed.info/sct', '95086008', 'Neoplasm of uncertain behavior of skin of wrist (disorder)')
,('http://snomed.info/sct', '95087004', 'Neoplasm of uncertain behavior of skin (disorder)')
,('http://snomed.info/sct', '985355341000119101', 'Malignant melanoma of skin of left wrist (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.51', 'Malignant melanoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.52', 'Malignant melanoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.8', 'Malignant melanoma of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.9', 'Malignant melanoma of skin, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.00', 'Unspecified malignant neoplasm of skin of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.01', 'Basal cell carcinoma of skin of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.02', 'Squamous cell carcinoma of skin of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.09', 'Other specified malignant neoplasm of skin of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.101', 'Unspecified malignant neoplasm of skin of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1021', 'Unspecified malignant neoplasm of skin of right upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1022', 'Unspecified malignant neoplasm of skin of right lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1091', 'Unspecified malignant neoplasm of skin of left upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1092', 'Unspecified malignant neoplasm of skin of left lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.111', 'Basal cell carcinoma of skin of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1121', 'Basal cell carcinoma of skin of right upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1122', 'Basal cell carcinoma of skin of right lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1191', 'Basal cell carcinoma of skin of left upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1192', 'Basal cell carcinoma of skin of left lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.121', 'Squamous cell carcinoma of skin of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1221', 'Squamous cell carcinoma of skin of right upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1222', 'Squamous cell carcinoma of skin of right lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1291', 'Squamous cell carcinoma of skin of left upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1292', 'Squamous cell carcinoma of skin of left lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.131', 'Sebaceous cell carcinoma of skin of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1321', 'Sebaceous cell carcinoma of skin of right upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1322', 'Sebaceous cell carcinoma of skin of right lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1391', 'Sebaceous cell carcinoma of skin of left upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1392', 'Sebaceous cell carcinoma of skin of left lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.191', 'Other specified malignant neoplasm of skin of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1921', 'Other specified malignant neoplasm of skin of right upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1922', 'Other specified malignant neoplasm of skin of right lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1991', 'Other specified malignant neoplasm of skin of left upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1992', 'Other specified malignant neoplasm of skin of left lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.201', 'Unspecified malignant neoplasm of skin of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.202', 'Unspecified malignant neoplasm of skin of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.209', 'Unspecified malignant neoplasm of skin of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.211', 'Basal cell carcinoma of skin of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.212', 'Basal cell carcinoma of skin of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.219', 'Basal cell carcinoma of skin of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.221', 'Squamous cell carcinoma of skin of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.222', 'Squamous cell carcinoma of skin of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.229', 'Squamous cell carcinoma of skin of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.291', 'Other specified malignant neoplasm of skin of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.292', 'Other specified malignant neoplasm of skin of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.299', 'Other specified malignant neoplasm of skin of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.300', 'Unspecified malignant neoplasm of skin of unspecified part of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.301', 'Unspecified malignant neoplasm of skin of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.309', 'Unspecified malignant neoplasm of skin of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.310', 'Basal cell carcinoma of skin of unspecified parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.311', 'Basal cell carcinoma of skin of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.319', 'Basal cell carcinoma of skin of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.320', 'Squamous cell carcinoma of skin of unspecified parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.321', 'Squamous cell carcinoma of skin of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.329', 'Squamous cell carcinoma of skin of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.390', 'Other specified malignant neoplasm of skin of unspecified parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.391', 'Other specified malignant neoplasm of skin of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.399', 'Other specified malignant neoplasm of skin of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.40', 'Unspecified malignant neoplasm of skin of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.41', 'Basal cell carcinoma of skin of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.42', 'Squamous cell carcinoma of skin of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.49', 'Other specified malignant neoplasm of skin of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.500', 'Unspecified malignant neoplasm of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.501', 'Unspecified malignant neoplasm of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.509', 'Unspecified malignant neoplasm of skin of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.510', 'Basal cell carcinoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.511', 'Basal cell carcinoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.519', 'Basal cell carcinoma of skin of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.520', 'Squamous cell carcinoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.521', 'Squamous cell carcinoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.529', 'Squamous cell carcinoma of skin of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.590', 'Other specified malignant neoplasm of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.591', 'Other specified malignant neoplasm of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.599', 'Other specified malignant neoplasm of skin of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.601', 'Unspecified malignant neoplasm of skin of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.602', 'Unspecified malignant neoplasm of skin of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.609', 'Unspecified malignant neoplasm of skin of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.611', 'Basal cell carcinoma of skin of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.612', 'Basal cell carcinoma of skin of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.619', 'Basal cell carcinoma of skin of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.621', 'Squamous cell carcinoma of skin of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.622', 'Squamous cell carcinoma of skin of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.629', 'Squamous cell carcinoma of skin of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.691', 'Other specified malignant neoplasm of skin of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.692', 'Other specified malignant neoplasm of skin of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.699', 'Other specified malignant neoplasm of skin of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.701', 'Unspecified malignant neoplasm of skin of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.702', 'Unspecified malignant neoplasm of skin of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.709', 'Unspecified malignant neoplasm of skin of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.711', 'Basal cell carcinoma of skin of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.712', 'Basal cell carcinoma of skin of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.719', 'Basal cell carcinoma of skin of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.721', 'Squamous cell carcinoma of skin of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.722', 'Squamous cell carcinoma of skin of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.729', 'Squamous cell carcinoma of skin of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.791', 'Other specified malignant neoplasm of skin of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.792', 'Other specified malignant neoplasm of skin of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.799', 'Other specified malignant neoplasm of skin of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.80', 'Unspecified malignant neoplasm of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.81', 'Basal cell carcinoma of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.82', 'Squamous cell carcinoma of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.89', 'Other specified malignant neoplasm of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.90', 'Unspecified malignant neoplasm of skin, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.91', 'Basal cell carcinoma of skin, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.92', 'Squamous cell carcinoma of skin, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.99', 'Other specified malignant neoplasm of skin, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C46.0', 'Kaposis sarcoma of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C4A.51', 'Merkel cell carcinoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C4A.52', 'Merkel cell carcinoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C79.2', 'Secondary malignant neoplasm of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D48.5', 'Neoplasm of uncertain behavior of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D49.2', 'Neoplasm of unspecified behavior of bone, soft tissue, and skin')
) AS t (system, code, display) ;