create or replace view irae__rx_prednisolone as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '102857', 'Prednisolone 16 MG/ML Injectable Solution [Codelsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548713', 'Prednisolone acetate 10 MG/ML [Omnipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548738', 'Prednisolone acetate 10 MG/ML [Ocu-Pred-A]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1549316', 'Prednisolone acetate 1.25 MG/ML [Econopred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162276', 'oxytetracycline / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162561', 'polidocanol / Prednisolone / promethazine Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451088', 'bismuth chloride oxide / Prednisolone / zinc oxide Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451089', 'Prednisolone 1.1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451094', 'Prednisolone Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451099', 'Prednisolone / propylene glycol salicylate Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451124', 'idoxuridine / Prednisolone Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451130', 'oxyquinoline / Prednisolone Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451160', 'Prednisolone Paste')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '452820', 'Prednisolone 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689752', 'phenylephrine / Prednisolone / sulfacetamide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '323977', 'Prednisolone 40 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205826', 'gentamicin 3 MG/ML / Prednisolone acetate 10 MG/ML Ophthalmic Suspension [Pred-G]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '808117', 'Prednisolone Oral Tablet [Millipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '392181', 'Prednisolone 2.5 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328813', 'Prednisolone 2.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '330164', 'Prednisolone 100 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '333915', 'Prednisolone 0.0025 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '335528', 'Prednisolone 0.2 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '335533', 'Prednisolone 0.0019 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317474', 'Prednisolone 3 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345099', 'Prednisolone 0.1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870659', 'gentamicin 0.003 MG/MG / Prednisolone acetate 0.006 MG/MG [Pred-G]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '377392', 'Prednisolone Otic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '542620', 'Prednisolone Ophthalmic Solution [Pred-Phosphate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '545252', 'Prednisolone / sulfacetamide Ophthalmic Ointment [Predsulfair]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '547221', 'Prednisolone Injectable Suspension [Pricortin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '542621', 'Prednisolone 10 MG/ML Ophthalmic Solution [Pred-Phosphate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012023', 'Sulster (Prednisolone sodium phosphate 0.25 % / sulfacetamide sodium 10 % ) Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363278', 'Prednisolone Injectable Solution [Key-Pred SP]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363815', 'Prednisolone Ophthalmic Solution [Ocu-Pred Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363903', 'Prednisolone Ophthalmic Solution [Minims Prednisolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '416363', 'bisdequalinium 4.8 MG/ML / Prednisolone 2.5 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '417397', 'neomycin 3 MG/ML / Prednisolone 4 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '417896', 'Prednisolone 4 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '418925', 'polidocanol 0.03 MG/MG / Prednisolone 0.004 MG/MG / promethazine 0.02 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '418976', 'Prednisolone 0.002 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '418978', 'Prednisolone 0.0025 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '421326', 'dibucaine 1 MG / Prednisolone 1.1 MG Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '429198', 'Prednisolone 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '8638', 'Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1158144', 'phenylephrine / Prednisolone Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1179764', 'Minims Prednisolone Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1183439', 'Orapred Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184005', 'Pediapred Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184934', 'Millipred Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185831', 'Prelone Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '34372', 'Prednisolone acetate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250862', 'Prednisolone 0.2 MG/ML Enema')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689615', 'atropine / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260394', 'Prednisolone 50 MG/ML Injectable Suspension [Key-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260402', 'Prednisolone 50 MG/ML Injectable Suspension [Predicort-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260404', 'Prednisolone 80 MG/ML Injectable Suspension [Depo-Predate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260405', 'Prednisolone 20 MG/ML Injectable Solution [Hydeltrasol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260407', 'Prednisolone 20 MG/ML Injectable Solution [Predicort RP]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012214', 'Vasocidin (Prednisolone sodium phosphate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1376336', 'Prednisolone acetate 1 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '803309', 'Prednisolone 1 MG/ML [Flo-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2645363', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2646912', 'Prednisolone acetate Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2646929', 'Prednisolone acetate Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2648304', 'Prednisolone / trimeprazine tartrate Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2654891', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Solution [Optimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011978', 'Prednisolone acetate 0.0025 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011980', 'Prednisolone acetate 0.0025 MG/MG / sulfacetamide sodium 0.1 MG/MG [Cetapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011986', 'Prednisolone acetate 0.002 MG/MG / sulfacetamide sodium 0.1 MG/MG [Blephamide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012001', 'Prednisolone acetate 0.005 MG/MG / sulfacetamide sodium 0.1 MG/MG [AK-Cide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012007', 'Prednisolone acetate 0.005 MG/MG / sulfacetamide sodium 0.1 MG/MG [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012024', 'Prednisolone sodium phosphate 2.5 MG/ML / sulfacetamide sodium 100 MG/ML [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012079', 'Prednisolone acetate 2.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012176', 'Prednisolone sodium phosphate 5 MG/ML / sulfacetamide sodium 100 MG/ML [AK-Cide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012208', 'Prednisolone 3 MG/ML Oral Solution [AsmalPred Plus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012213', 'Prednisolone sodium phosphate 5 MG/ML / sulfacetamide sodium 100 MG/ML [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1493170', 'Prednisolone 10 MG/ML Injectable Solution [Solu-Delta-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1493171', 'Prednisolone 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312601', 'Prednisolone 2 MG/ML / sulfacetamide 100 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312603', 'Prednisolone 2 MG/ML / sulfacetamide 200 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345878', 'Prednisolone acetate 3 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345879', 'Prednisolone acetate 5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351704', 'Prednisolone 10 MG/ML Ophthalmic Solution [Ocu-Pred Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156760', 'Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105408', 'Prednisolone 2.5 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105411', 'Prednisolone 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '106025', 'Minims Prednisolone 5 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '106992', 'Prednisolone 0.001 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '106993', 'Prednisolone 0.003 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '106996', 'Prednisolone 0.1 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '106997', 'Prednisolone 0.3 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374690', 'neomycin / polymyxin B / Prednisolone Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '438433', 'chloramphenicol / Prednisolone Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249191', 'dibucaine 0.005 MG/MG / Prednisolone 0.0019 MG/MG Rectal Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249447', 'Prednisolone 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '246727', 'chloramphenicol 1 MG/ML / Prednisolone 5 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2655490', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment [Predsulfair]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2655713', 'Prednisolone acetate Ophthalmic Suspension [Omnipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2655885', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Solution [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2656295', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Suspension [Sulster]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2656572', 'Prednisolone acetate Ophthalmic Suspension [Pred Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657142', 'Prednisolone / trimeprazine tartrate Oral Tablet [Temaril-P]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657971', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment [AK-Cide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658073', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment [Blephamide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658953', 'Prednisolone acetate Ophthalmic Suspension [Econopred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2659298', 'Prednisolone / trimeprazine tartrate Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2661173', 'atropine sulfate / Prednisolone acetate Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2661578', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2661636', 'Prednisolone sodium phosphate Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '755702', 'Prelone 3 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012017', 'Blephamide (Prednisolone acetate 0.2 % / sulfacetamide sodium 10 % ) Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012118', 'Supred (Prednisolone sodium phosphate 0.25 % / sulfacetamide sodium 10 % ) Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548705', 'Prednisolone acetate 10 MG/ML Ophthalmic Suspension [Econopred Plus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '824889', 'Veripred 20 Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007260', 'oxytetracycline / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008245', 'menthol / Prednisolone / thymol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008294', 'miconazole / polymyxin B / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008890', 'dibucaine / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1009010', 'Prednisolone / salicylic acid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '619280', 'Prednisolone / sulfacetamide Ophthalmic Suspension [Metimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2645920', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574182', 'Prednisolone 50 MG/ML [Key-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574184', 'Prednisolone 50 MG/ML [Pred-Ject-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574188', 'Prednisolone 50 MG/ML [Predate-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574191', 'Prednisolone 50 MG/ML [Pri-Cortin 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574626', 'Prednisolone 25 MG/ML [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '575438', 'Prednisolone 5 MG [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563156', 'Prednisolone 16 MG/ML [Codelsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563157', 'Prednisolone 5 MG [Stintisone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '568390', 'neomycin 3.5 MG/ML / polymyxin B 10000 UNT/ML / Prednisolone 5 MG/ML [Poly Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '539944', 'Prednisolone 5 MG/ML [Prelone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '541703', 'Prednisolone 5 MG [Prednoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '569628', 'Prednisolone 3 MG/ML [Prelone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104171', 'Prednisolone 0.2 MG/ML Enema [Predenema]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572088', 'Prednisolone 1.25 MG/ML [AK-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572089', 'Prednisolone 1.25 MG/ML [Inflamase Mild]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572090', 'Prednisolone 10 MG/ML [AK-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572091', 'Prednisolone 10 MG/ML [Inflamase Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365618', 'Prednisolone Injectable Suspension [Predate-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365619', 'Prednisolone Injectable Suspension [Predalone 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365620', 'Prednisolone Injectable Suspension [Predaject-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365624', 'Prednisolone Injectable Suspension [Key-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365840', 'Prednisolone / sulfacetamide Ophthalmic Suspension [AK-Cide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '367242', 'Prednisolone / sulfacetamide Ophthalmic Ointment [Cetapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371387', 'chloramphenicol / Prednisolone Otic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373570', 'Prednisolone Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373972', 'Prednisolone / sulfacetamide Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '580010', 'Prednisolone 1.25 MG/ML [Ocu-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153916', 'clotrimazole / hexamidine / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155323', 'bismuth chloride oxide / Prednisolone / zinc oxide Rectal Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155885', 'dibucaine / Prednisolone Rectal Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '794979', 'Prednisolone 2 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165752', 'Prednisolone / sulfacetamide Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165757', 'Prednisolone Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165758', 'Prednisolone Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169771', 'Flo-Pred Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '211751', 'Prednisolone 1.25 MG/ML Ophthalmic Solution [AK-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '211755', 'Prednisolone 10 MG/ML Ophthalmic Solution [Prednisol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1190936', 'atropine sulfate 1 % / Prednisolone acetate 0.25 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '647126', 'Prednisolone Disintegrating Oral Tablet [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '891148', 'miconazole / polymyxin B / Prednisolone Otic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '891152', 'miconazole / polymyxin B / Prednisolone Otic Suspension [Surolan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312193', 'phenylephrine 1.2 MG/ML / Prednisolone 5 MG/ML / sulfacetamide 100 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897058', 'Prednisolone / trimeprazine Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897061', 'Prednisolone 2 MG / trimeprazine tartrate 5 MG [Temaril-P]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870655', 'gentamicin / Prednisolone Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '102858', 'Prednisolone 5 MG Oral Tablet [Stintisone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '103166', 'Prednisolone 16 MG/ML Injectable Solution [Codelson]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '103264', 'Prednisolone 5 MG/ML Otic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312611', 'Prednisolone 5 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1159812', 'menthol / Prednisolone / thymol Rectal Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161205', 'bisdequalinium / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451086', 'Prednisolone 2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451096', 'Prednisolone Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451110', 'Prednisolone 8 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451115', 'bisdequalinium / Prednisolone Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451162', 'Prednisolone Topical Gel')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451305', 'Prednisolone / rifamycins Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451836', 'fluPrednisolone 1.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '604202', 'Prednisolone 1 MG/ML [Bubbli-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '604203', 'Prednisolone Oral Solution [Bubbli-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '323918', 'Prednisolone 80 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2661773', 'Prednisolone acetate Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2663537', 'Prednisolone acetate Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012152', 'Optimyd (Prednisolone sodium phosphate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328816', 'Prednisolone 1.25 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '333210', 'Prednisolone 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '333913', 'Prednisolone 0.005 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '333914', 'Prednisolone 0.002 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '335262', 'Prednisolone 0.3 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310468', 'gentamicin sulfate 0.3 % / Prednisolone acetate 0.6 % Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310469', 'gentamicin 3 MG/ML / Prednisolone acetate 10 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345097', 'Prednisolone 0.01 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345098', 'Prednisolone 0.03 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345131', 'Prednisolone 1.25 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870654', 'Prednisolone acetate 0.006 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870666', 'gentamicin / Prednisolone Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '542616', 'Prednisolone Ophthalmic Solution [Isolone Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '542634', 'Prednisolone / sulfacetamide Ophthalmic Solution [Sulster]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '542617', 'Prednisolone 10 MG/ML Ophthalmic Solution [Isolone Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012006', 'Predsulfair (Prednisolone acetate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363559', 'Prednisolone Injectable Solution [Codelsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363610', 'Prednisolone Enema [Predfoam]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363611', 'Prednisolone Enema [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363767', 'Prednisolone Ophthalmic Solution [Inflamase Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '415884', 'Prednisolone 0.01 MG/MG Topical Gel')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '416576', 'clotrimazole 10 MG/ML / hexamidine 2.5 MG/ML / Prednisolone 5 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '417022', 'Prednisolone 0.01 MG/MG / rifamycins 0.0025 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '417779', 'idoxuridine 0.002 MG/MG / Prednisolone 0.002 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '418972', 'Prednisolone 0.005 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '418977', 'Prednisolone 0.001 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '418987', 'Prednisolone 0.004 MG/MG / ZNO 0.03 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '420747', 'Prednisolone 2 MG/ML / salicylic acid 4 MG/ML Topical Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '421255', 'menthol 10 MG / Prednisolone 1 MG / thymol 0.5 MG Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1158143', 'phenylephrine / Prednisolone / sulfacetamide Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1158306', 'dexpanthenol / Prednisolone / salicylic acid Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156284', 'idoxuridine / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156757', 'Prednisolone Paste Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1157546', 'neomycin / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '436507', 'Prednisolone 100 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184933', 'Millipred Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '792956', 'Prednisolone Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260285', 'Pred-G (gentamicin sulfate 0.3 % / Prednisolone acetate 0.6 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260391', 'Prednisolone 25 MG/ML Injectable Suspension [Key-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260397', 'Prednisolone 50 MG/ML Injectable Suspension [Predacort 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260398', 'Prednisolone 50 MG/ML Injectable Suspension [Predaject-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260403', 'Prednisolone 50 MG/ML Injectable Suspension [Pri-Cortin 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '803308', 'Flo-Pred 3 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2645619', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2649492', 'Prednisolone acetate Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2654779', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Solution [Sulster]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012005', 'Prednisolone acetate 0.005 MG/MG / sulfacetamide sodium 0.1 MG/MG [Predsulfair]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012085', 'Prednisolone sodium phosphate 2.5 MG/ML / sulfacetamide sodium 100 MG/ML [Cetapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012149', 'Prednisolone sodium phosphate 5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012151', 'Prednisolone sodium phosphate 5 MG/ML / sulfacetamide sodium 100 MG/ML [Optimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012907', 'Prednisolone acetate 0.005 MG/MG / sulfacetamide sodium 0.1 MG/MG [Medasulf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '219136', 'Pediapred')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1493172', 'Prednisolone 50 MG/ML [Solu-Delta-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1493168', 'Prednisolone Injectable Solution [Solu-Delta-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '647127', 'Orapred 15 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012015', 'Prednisolone acetate 0.2 % / sulfacetamide sodium 10 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012080', 'Prednisolone acetate 0.25 % / sulfacetamide sodium 10 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1547974', 'Prednisolone sodium phosphate 0.5 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668660', 'Orapred 30 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548739', 'Prednisolone acetate 10 MG/ML Ophthalmic Suspension [Ocu-Pred-A]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012025', 'Vasocidin (Prednisolone sodium phosphate 0.25 % / sulfacetamide sodium 10 % ) Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105409', 'Prednisolone 5 MG Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '106994', 'Prednisolone 0.01 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '580011', 'Prednisolone 1.25 MG/ML Ophthalmic Solution [Ocu-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '379264', 'Prednisolone Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '438796', 'clotrimazole / hexamidine / Prednisolone Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164102', 'miconazole / polymyxin B / Prednisolone Otic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249066', 'Prednisolone 5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2655258', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment [Cetapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2656294', 'gentamicin / Prednisolone acetate Ophthalmic Ointment [Pred-G]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657175', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Suspension [Blephamide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657694', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Suspension [AK-Cide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658111', 'Prednisolone acetate Ophthalmic Suspension [Ocu-Pred-A]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2659133', 'Prednisolone acetate Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2659927', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '207638', 'Poly Pred (Prednisolone 5 MG/ neomycin 3.5 MG/ polymyxin b 10000 UNT) per ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '208988', 'Prednisolone acetate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012004', 'Metimyd (Prednisolone acetate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012008', 'Vasocidin (Prednisolone acetate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012087', 'Cetapred (Prednisolone sodium phosphate 0.25 % / sulfacetamide sodium 10 % ) Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012177', 'AK-Cide (Prednisolone sodium phosphate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '209002', 'Prednisolone 1.2 MG/ML Ophthalmic Suspension [Pred Mild]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007264', 'oxyquinoline / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007726', 'bisdequalinium / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008055', 'Prednisolone / trimeprazine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008241', 'Prednisolone / zinc oxide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008707', 'bismuth chloride oxide / Prednisolone / zinc oxide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '619281', 'Prednisolone / sulfacetamide Ophthalmic Suspension [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349801', 'Prednisolone 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562661', 'Prednisolone 40 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562781', 'Prednisolone 1.2 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574180', 'Prednisolone 25 MG/ML [Predcor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574186', 'Prednisolone 50 MG/ML [Predaject-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574190', 'Prednisolone 50 MG/ML [Predicort-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574193', 'Prednisolone 20 MG/ML [Hydeltrasol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574196', 'Prednisolone 1 MG/ML [Pediapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373973', 'Prednisolone / sulfacetamide Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563538', 'Prednisolone 5 MG [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563539', 'Prednisolone 20 MG [Predfoam]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564291', 'Prednisolone 5 MG/ML [Minims Prednisolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104172', 'Prednisolone 0.2 MG/ML Enema [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572092', 'Prednisolone 10 MG/ML [Prednisol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365617', 'Prednisolone Injectable Suspension [Predcor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365621', 'Prednisolone Injectable Suspension [Predacort 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365623', 'Prednisolone Injectable Suspension [Medicort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365625', 'Prednisolone Injectable Suspension [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365809', 'Prednisolone Ophthalmic Suspension [Ocu-Pred-A]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365822', 'Prednisolone Ophthalmic Suspension [Pred Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '367224', 'Prednisolone / sulfacetamide Ophthalmic Ointment [AK-Cide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369438', 'Prednisolone Oral Tablet [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371385', 'chloramphenicol / Prednisolone Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373394', 'phenylephrine / Prednisolone Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373573', 'niacinamide / Prednisolone Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373578', 'Prednisolone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373581', 'dibucaine / Prednisolone Rectal Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373974', 'Prednisolone / sulfacetamide Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '580007', 'Prednisolone 2 MG/ML / sulfacetamide 100 MG/ML Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '107666', 'Prednisolone 20 MG Rectal Foam')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153053', 'chloramphenicol / Prednisolone Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153054', 'chloramphenicol / Prednisolone Otic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '385800', 'Prednisolone Rectal Foam [Predfoam]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165760', 'Prednisolone Otic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169772', 'Flo-Pred Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191686', 'Prednisolone 5 MG Oral Tablet [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '251979', 'phenylephrine 0.8 MG/ML / Prednisolone 1 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '252948', 'Prednisolone 0.002 MG/MG Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795097', 'Millipred 2 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199343', 'Prednisolone 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199968', 'Prednisolone 5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '211753', 'Prednisolone 10 MG/ML Ophthalmic Solution [AK-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '211754', 'Prednisolone 10 MG/ML Ophthalmic Solution [Inflamase Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643123', 'Prednisolone 10 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643127', 'Prednisolone 30 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '891147', 'Prednisolone acetate 5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897062', 'Prednisolone / trimeprazine Oral Tablet [Temaril-P]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012021', 'Prednisolone sodium phosphate 0.25 % / sulfacetamide sodium 10 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '102859', 'Prednisolone 16 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '103223', 'Prednisolone 5 MG/ML Ophthalmic Solution [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548704', 'Prednisolone acetate 10 MG/ML [Econopred Plus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283077', 'Prednisolone 3 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284275', 'Prelone 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284516', 'Orapred 3 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '285077', 'Orapred')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161446', 'fluPrednisolone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '446684', 'neomycin / Prednisolone Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451093', 'Prednisolone 0.001 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451127', 'estradiol / Prednisolone Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '690161', 'Prednisolone / sulfacetamide')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '808116', 'Prednisolone 5 MG [Millipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328310', 'Prednisolone 10 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328809', 'Prednisolone 1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328812', 'Prednisolone 2 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '333209', 'Prednisolone 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1296584', 'Orapred Disintegrating Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870660', 'gentamicin / Prednisolone Ophthalmic Ointment [Pred-G]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870656', 'gentamicin / Prednisolone Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '547220', 'Prednisolone 25 MG/ML [Pricortin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363691', 'Prednisolone Ophthalmic Solution [Inflamase Mild]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363768', 'Prednisolone Ophthalmic Solution [AK-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363816', 'Prednisolone Ophthalmic Solution [Ocu-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '364478', 'Prednisolone Oral Solution [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '415640', 'Prednisolone 5 MG/ML / propylene glycol salicylate 1 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '416566', 'estradiol 0.05 MG/ML / Prednisolone 4 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '416681', 'Prednisolone 0.005 MG/MG Paste')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '417893', 'Prednisolone 2.5 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '418460', 'oxytetracycline 0.005 MG/MG / Prednisolone 0.0025 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '420775', 'Prednisolone 100 MG Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '421480', 'BISMUTH CHLORIDE OXIDE 44 MG / Prednisolone 2 MG / ZNO 66 MG Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '422650', 'Prednisolone 20 MG Enema')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '428443', 'dexpanthenol 3 MG/ML / Prednisolone 2 MG/ML / salicylic acid 10 MG/ML Topical Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1158660', 'niacinamide / Prednisolone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '436279', 'Prednisolone 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '436508', 'fluPrednisolone 1.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1183437', 'Orapred Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184006', 'Pediapred Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185832', 'Prelone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '34376', 'Prednisolone tebutate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250864', 'Prednisolone 5 MG Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250869', 'Prednisolone 20 MG/ACTUAT Rectal Foam')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689325', 'gentamicin / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '693010', 'neomycin / polymyxin B / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '693011', 'neomycin / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '259052', 'Prednisolone 0.2 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260392', 'Prednisolone 25 MG/ML Injectable Suspension [Predcor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260400', 'Prednisolone 50 MG/ML Injectable Suspension [Predate-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260406', 'Prednisolone 20 MG/ML Injectable Solution [Key-Pred SP]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260409', 'Pediapred 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261992', 'Prednisolone 25 MG/ML Injectable Suspension [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261993', 'Prednisolone 50 MG/ML Injectable Suspension [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '389031', 'Prednisolone 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '803306', 'Prednisolone 3 MG/ML [Flo-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2646280', 'atropine sulfate / Prednisolone acetate Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011984', 'Prednisolone acetate 0.002 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011999', 'Prednisolone acetate 0.005 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012014', 'Prednisolone acetate 2 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012016', 'Prednisolone acetate 2 MG/ML / sulfacetamide sodium 100 MG/ML [Blephamide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012022', 'Prednisolone sodium phosphate 2.5 MG/ML / sulfacetamide sodium 100 MG/ML [Sulster]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012086', 'Prednisolone / sulfacetamide Ophthalmic Suspension [Cetapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012117', 'Prednisolone sodium phosphate 2.5 MG/ML / sulfacetamide sodium 100 MG/ML [Supred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012187', 'Prednisolone sodium phosphate 5 MG/ML / sulfacetamide sodium 100 MG/ML [Metimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012207', 'Prednisolone Oral Solution [AsmalPred Plus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '225925', 'Minims Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1493167', 'Prednisolone 10 MG/ML [Solu-Delta-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '647125', 'Prednisolone 15 MG [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011985', 'Prednisolone acetate 0.2 % / sulfacetamide sodium 10 % Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012224', 'Prednisolone acetate 0.5 % / sulfacetamide sodium 10 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312609', 'Prednisolone 100 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012150', 'Prednisolone sodium phosphate 0.5 % / sulfacetamide sodium 10 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668657', 'Prednisolone 10 MG [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668658', 'Orapred 10 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '347155', 'Prednisolone 1.1 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '348428', 'Prednisolone 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351519', 'Prednisolone 5 MG Oral Tablet [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351703', 'Prednisolone 1.2 MG/ML Ophthalmic Solution [Ocu-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '409432', 'Prednisolone 2.5 MG/ML Topical Spray')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105410', 'Prednisolone 5 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165759', 'Prednisolone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '106995', 'Prednisolone 0.03 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '376404', 'neomycin / Prednisolone Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165180', 'estradiol / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '248804', 'chloramphenicol 2 MG/ML / Prednisolone 5 MG/ML Otic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2656219', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Suspension [Cetapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658288', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Suspension [Metimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658657', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2659308', 'Prednisolone acetate Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2661078', 'Prednisolone acetate Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2661299', 'gentamicin / Prednisolone acetate Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '755936', 'Prednisolone acetate 3 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011981', 'Cetapred (Prednisolone acetate 0.25 % / sulfacetamide sodium 10 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012002', 'AK-Cide (Prednisolone acetate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012908', 'Medasulf (Prednisolone acetate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1005830', '{48 (Prednisolone 5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007035', 'dequalinium / polidocanol / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007257', 'phenylephrine / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008236', 'chloramphenicol / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008244', 'Prednisolone / propylene glycol salicylate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008474', 'clotrimazole / hexamidine / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008863', 'dexpanthenol / Prednisolone / salicylic acid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '619279', 'Prednisolone / sulfacetamide Ophthalmic Ointment [Metimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '619303', 'Prednisolone / sulfacetamide Ophthalmic Solution [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897063', 'Temaril-P (Prednisolone 2 MG / trimeprazine tartrate 5 MG) Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311888', 'neomycin 0.35 % / polymyxin B 10,000 UNT/ML / Prednisolone 0.5 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2646710', 'Prednisolone sodium phosphate Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '92892', 'Prednisolone Injectable Solution [Hydeltrasol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562662', 'Prednisolone 80 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574179', 'Prednisolone 25 MG/ML [Key-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574181', 'Prednisolone 40 MG/ML [Depo-Predate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574183', 'Prednisolone 50 MG/ML [Medicort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574185', 'Prednisolone 50 MG/ML [Predacort 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574187', 'Prednisolone 50 MG/ML [Predalone 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574194', 'Prednisolone 20 MG/ML [Key-Pred SP]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574627', 'Prednisolone 50 MG/ML [Cotolone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574754', 'Prednisolone 1 MG/ML [Prelone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574944', 'Prednisolone 3 MG/ML [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '575551', 'Prednisolone 1.2 MG/ML [Ocu-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563270', 'Prednisolone 5 MG/ML [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563536', 'Prednisolone 0.2 MG/ML [Predenema]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563537', 'Prednisolone 0.2 MG/ML [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '541543', 'Prednisolone 1.1 MG/ML [AK-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '569642', 'Prednisolone 1.2 MG/ML [Pred Mild]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365356', 'Prednisolone Otic Solution [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365598', 'Prednisolone Injectable Suspension [Hydeltra-T.B.A.]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365614', 'Prednisolone Injectable Suspension [Depo-Predate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365821', 'Prednisolone Ophthalmic Suspension [Econopred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365835', 'Prednisolone / sulfacetamide Ophthalmic Suspension [Supred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365841', 'Prednisolone / sulfacetamide Ophthalmic Suspension [Blephamide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '367257', 'Prednisolone / sulfacetamide Ophthalmic Ointment [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370965', 'atropine / Prednisolone Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373568', 'Prednisolone Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373576', 'Prednisolone Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373579', 'Prednisolone Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108304', 'Prednisolone 20 MG Rectal Foam [Predfoam]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153945', 'dequalinium / polidocanol / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '385141', 'Prednisolone Oral Tablet [Prednesol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '385326', 'Prednisolone Injectable Solution [Codelson]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '440699', 'dequalinium / polidocanol / Prednisolone Topical Gel')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '440700', 'Prednisolone 0.004 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165749', 'Prednisolone / propylene glycol salicylate Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165751', 'Prednisolone / salicylic acid Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165754', 'Prednisolone / trimeprazine Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165755', 'Prednisolone / zinc oxide Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165756', 'Prednisolone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191679', 'Prednisolone 20 MG [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191683', 'Prednisolone 20 MG Oral Tablet [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191685', 'Prednisolone 5 MG [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199967', 'Prednisolone 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '211752', 'Prednisolone 1.25 MG/ML Ophthalmic Solution [Inflamase Mild]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '856820', 'Prednisolone / sulfacetamide Ophthalmic Ointment [Blephamide]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '337411', 'Prednisolone 25 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '891149', 'miconazole nitrate 23 MG / polymyxin B sulfate 0.5293 MG / Prednisolone acetate 5 MG per 1 ML Otic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '891151', 'miconazole nitrate 23 MG/ML / polymyxin B sulfate 0.5293 MG/ML / Prednisolone acetate 5 MG/ML [Surolan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '891153', 'Surolan (miconazole nitrate 23 MG / polymyxin B sulfate 0.5293 MG / Prednisolone acetate 5 MG) per ML Otic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '897059', 'Prednisolone 2 MG / trimeprazine tartrate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316579', 'Prednisolone 5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '755703', 'Prelone 5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '103263', 'Prednisolone 5 MG/ML Otic Solution [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548723', 'Prednisolone acetate 10 MG/ML [Pred Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1549314', 'Prednisolone acetate 1.25 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161445', 'fluPrednisolone Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1162267', 'oxyquinoline / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '446683', 'Prednisolone 4 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '447124', 'oxytetracycline / Prednisolone Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451092', 'dexpanthenol / Prednisolone / salicylic acid Topical Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451107', 'Prednisolone / zinc oxide Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451108', 'Prednisolone Topical Spray')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451137', 'Prednisolone / salicylic acid Topical Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451161', 'Prednisolone 0.01 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451837', 'fluPrednisolone Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '452077', 'menthol / Prednisolone / thymol Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '604204', 'Prednisolone 1 MG/ML Oral Solution [Bubbli-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '702306', 'Prednisolone 4 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198142', 'Prednisolone 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2662662', 'miconazole nitrate / polymyxin B sulfate / Prednisolone acetate Otic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '806539', 'Prednisolone / sulfacetamide Ophthalmic Solution [Optimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '808118', 'Millipred 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328808', 'Prednisolone 20 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328814', 'Prednisolone 5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328815', 'Prednisolone 1.2 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '335529', 'Prednisolone 2.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '335531', 'Prednisolone 20 MG/ACTUAT')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '335532', 'Prednisolone 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '335535', 'Prednisolone 1.3 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1295508', 'Prednisolone Disintegrating Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870668', 'gentamicin 3 MG/ML / Prednisolone acetate 10 MG/ML [Pred-G]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870669', 'gentamicin / Prednisolone Ophthalmic Suspension [Pred-G]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2649474', 'gentamicin / Prednisolone acetate Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2648388', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '353628', 'Prednisolone 16 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '547222', 'Prednisolone 25 MG/ML Injectable Suspension [Pricortin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '542615', 'Prednisolone 10 MG/ML [Isolone Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '542619', 'Prednisolone 10 MG/ML [Pred-Phosphate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '541544', 'Prednisolone 1.1 MG/ML Ophthalmic Solution [AK-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '541705', 'Prednisolone 5 MG Oral Tablet [Prednoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363277', 'Prednisolone Injectable Solution [Predicort RP]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363620', 'Prednisolone Enema [Predenema]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363667', 'Prednisolone Ophthalmic Solution [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363766', 'Prednisolone Ophthalmic Solution [Prednisol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '364214', 'Prednisolone Oral Solution [Prelone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '412642', 'Prednisolone 8 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '416545', 'dequalinium 0.003 MG/MG / polidocanol 0.003 MG/MG / Prednisolone 0.005 MG/MG Topical Gel')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '416577', 'oxyquinoline 2.5 MG/ML / Prednisolone 2.5 MG/ML Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '419051', 'chloramphenicol 0.002 MG/MG / Prednisolone 0.005 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '429199', 'Prednisolone 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156758', 'Prednisolone Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1157539', 'neomycin / polymyxin B / Prednisolone Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '436615', 'Prednisolone 0.5 % Topical Cream')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '242887', 'niacinamide 25 MG/ML / Prednisolone 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '792957', 'Prednisolone 1 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '793099', 'Prednisolone 3 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1183438', 'Orapred Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1184935', 'Millipred Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '34374', 'Prednisolone phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249573', 'chloramphenicol 2 MG/ML / Prednisolone 5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250343', 'dibucaine 1 MG / Prednisolone 1.3 MG Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '792207', 'Flo-Pred')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260125', 'Prednisolone 25 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260127', 'Prednisolone 50 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260393', 'Prednisolone 40 MG/ML Injectable Suspension [Depo-Predate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260395', 'Prednisolone 50 MG/ML Injectable Suspension [Medicort]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260396', 'Prednisolone 50 MG/ML Injectable Suspension [Pred-Ject-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260399', 'Prednisolone 50 MG/ML Injectable Suspension [Predalone 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260401', 'Prednisolone 50 MG/ML Injectable Suspension [Predcor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '260408', 'Prednisolone acetate 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1376335', 'Prednisolone acetate 10 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '803307', 'Prednisolone Oral Suspension [Flo-Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '803310', 'Flo-Pred 1 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2646780', 'miconazole nitrate / polymyxin B sulfate / Prednisolone acetate Otic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2654990', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment [Metimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '55062', 'Prednisolone sodium phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '55063', 'Prednisolone sodium succinate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012000', 'Prednisolone acetate 0.5 % / sulfacetamide sodium 10 % Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012003', 'Prednisolone acetate 0.005 MG/MG / sulfacetamide sodium 0.1 MG/MG [Metimyd]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012020', 'Prednisolone sodium phosphate 2.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012084', 'Prednisolone sodium phosphate 0.25 % / sulfacetamide sodium 10 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012175', 'Prednisolone sodium phosphate 0.5 % / sulfacetamide sodium 10 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012206', 'Prednisolone 3 MG/ML [AsmalPred Plus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1013114', '{21 (Prednisolone 5 MG Oral Tablet) } Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '219356', 'Prelone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548714', 'Prednisolone acetate 10 MG/ML Ophthalmic Suspension [Omnipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '731219', 'Prednisolone Ophthalmic Suspension [Omnipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1493173', 'Prednisolone 50 MG/ML Injectable Solution [Solu-Delta-Cortef]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312604', 'Prednisolone 2.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011979', 'Prednisolone acetate 0.25 % / sulfacetamide sodium 10 % Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1549315', 'Prednisolone acetate 0.125 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312614', 'Prednisolone 1 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668659', 'Prednisolone 30 MG [Orapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '343660', 'Prednisolone 50 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '345880', 'Prednisolone acetate 20 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351159', 'Prednisolone 25 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '4497', 'fluPrednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105407', 'Prednisolone 5 MG Oral Tablet [Prednesol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '376134', 'phenylephrine / Prednisolone / sulfacetamide Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249424', 'phenylephrine 1.2 MG/ML / Prednisolone 10 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235042', 'Millipred DP 6 Day Dose Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '268872', 'Prednisolone sodium metasulphobenzoate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2655335', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Suspension [Supred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657145', 'Prednisolone acetate Ophthalmic Suspension [Econopred Plus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657449', 'gentamicin / Prednisolone acetate Ophthalmic Suspension [Pred-G]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658423', 'Prednisolone acetate / sulfacetamide sodium Ophthalmic Ointment [Medasulf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658709', 'miconazole nitrate / polymyxin B sulfate / Prednisolone acetate Otic Suspension [Surolan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658713', 'Prednisolone sodium phosphate / sulfacetamide sodium Ophthalmic Suspension [Vasocidin]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2660054', 'Prednisolone / trimeprazine tartrate Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1011987', 'Blephamide (Prednisolone acetate 0.2 % / sulfacetamide sodium 10 % ) Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012188', 'Metimyd (Prednisolone sodium phosphate 0.5 % / sulfacetamide sodium 10 % ) Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1012098', 'Sulster (Prednisolone sodium phosphate 0.25 % / sulfacetamide sodium 10 % ) Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1549317', 'Prednisolone acetate 1.25 MG/ML Ophthalmic Suspension [Econopred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1548724', 'Prednisolone acetate 10 MG/ML Ophthalmic Suspension [Pred Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '824887', 'Prednisolone 4 MG/ML [Veripred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '824888', 'Prednisolone Oral Solution [Veripred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1005831', 'Millipred DP 12 Day Pack')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007261', 'Prednisolone / rifamycins')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007263', 'estradiol / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007725', 'idoxuridine / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008247', 'niacinamide / Prednisolone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008864', 'polidocanol / Prednisolone / promethazine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '619278', 'Prednisolone / sulfacetamide Ophthalmic Ointment [Medasulf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214105', 'Prednisolone 20 MG/ML Injectable Suspension [Hydeltra-T.B.A.]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311931', 'neomycin 5 MG / Prednisolone 5 MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '349970', 'Prednisolone 1.1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2645921', 'Prednisolone acetate Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2647419', 'gentamicin / Prednisolone acetate Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '93720', 'Prednisolone Oral Solution [Pediapred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562379', 'Prednisolone 0.12 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '562654', 'Prednisolone 20 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574189', 'Prednisolone 50 MG/ML [Predcor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574192', 'Prednisolone 80 MG/ML [Depo-Predate]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574195', 'Prednisolone 20 MG/ML [Predicort RP]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '575552', 'Prednisolone 10 MG/ML [Ocu-Pred Forte]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '563254', 'Prednisolone 16 MG/ML [Codelson]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564053', 'Prednisolone 5 MG [Prednesol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '541704', 'Prednisolone Oral Tablet [Prednoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104173', 'Prednisolone 5 MG Rectal Suppository [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '104174', 'Prednisolone 20 MG Enema [Predfoam]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '573944', 'Prednisolone 20 MG/ML [Hydeltra-T.B.A.]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365615', 'Prednisolone Injectable Suspension [Pri-Cortin 50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365616', 'Prednisolone Injectable Suspension [Predicort-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365622', 'Prednisolone Injectable Suspension [Pred-Ject-50]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365813', 'neomycin / polymyxin B / Prednisolone Ophthalmic Suspension [Poly Pred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365831', 'Prednisolone Ophthalmic Suspension [Econopred Plus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365832', 'Prednisolone Ophthalmic Suspension [Pred Mild]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '365836', 'Prednisolone / sulfacetamide Ophthalmic Suspension [Sulster]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '367523', 'Prednisolone Rectal Suppository [Predsol]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '369537', 'Prednisolone Oral Tablet [Stintisone]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371386', 'chloramphenicol / Prednisolone Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373569', 'Prednisolone Enema')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373571', 'Prednisolone Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373572', 'Prednisolone Delayed Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373574', 'Prednisolone Rectal Foam')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373575', 'Prednisolone Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373577', 'Prednisolone Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373582', 'dibucaine / Prednisolone Rectal Suppository')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156759', 'Prednisolone Rectal Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1153055', 'chloramphenicol / Prednisolone Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1154986', 'atropine / Prednisolone Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '440702', 'polidocanol / Prednisolone / promethazine Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165750', 'Prednisolone / rifamycins Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1165753', 'Prednisolone / trimeprazine Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191680', 'Prednisolone Oral Tablet [Prednistab]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795095', 'Prednisolone 2 MG/ML [Millipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795096', 'Prednisolone Oral Solution [Millipred]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '795094', 'Millipred')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '336584', 'Prednisolone 20 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643124', 'Prednisolone 15 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643125', 'Prednisolone 15 MG Disintegrating Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643126', 'Prednisolone 30 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314165', 'Prednisolone 10 MG/ML Ophthalmic Solution')
) AS t (system, code, display) ;