create or replace view irae__rx_cytogam as select * from (values

('http://www.nlm.nih.gov/research/umls/rxnorm','1156645','cytomegalovirus immune globulin Injectable Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1174483','Cytogam Injectable Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1806659','cytomegalovirus immune globulin Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1806661','cytomegalovirus immune globulin Injection [Cytogam]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1806663','cytomegalovirus immune globulin 50 MG/ML Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1806664','Cytogam 50 MG/ML Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1997443','cytomegalovirus immune globulin, human'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1999436','cytomegalovirus immune globulin, human 50 MG/ML'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1999438','cytomegalovirus immune globulin, human 50 MG/ML [Cytogam]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1999440','cytomegalovirus immune globulin, human 50 MG/ML Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1999441','cytomegalovirus immune globulin, human 50 MG/ML Injection [Cytogam]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','204528','50 ML cytomegalovirus immune globulin, human 50 MG/ML Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','209029','50 ML Cytogam 50 MG/ML Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','216315','Cytogam'),
('http://www.nlm.nih.gov/research/umls/rxnorm','22178','cytomegalovirus immune globulin'),
('http://www.nlm.nih.gov/research/umls/rxnorm','2648654','cytomegalovirus immune globulin, human Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','2654836','cytomegalovirus immune globulin, human Injection [Cytogam]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','2662844','cytomegalovirus immune globulin, human Injectable Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','342915','cytomegalovirus immune globulin 50 MG/ML'),
('http://www.nlm.nih.gov/research/umls/rxnorm','376867','cytomegalovirus immune globulin Injectable Solution'),
('http://www.nlm.nih.gov/research/umls/rxnorm','413186','cytomegalovirus immune globulin 100 MG/ML Injectable Solution'),
('http://www.nlm.nih.gov/research/umls/rxnorm','413187','cytomegalovirus immune globulin 95 MG/ML Injectable Solution'),
('http://www.nlm.nih.gov/research/umls/rxnorm','415182','cytomegalovirus immune globulin 60 MG/ML Injectable Solution'),
('http://www.nlm.nih.gov/research/umls/rxnorm','438887','cytomegalovirus immune globulin 100 MG/ML'),
('http://www.nlm.nih.gov/research/umls/rxnorm','438888','cytomegalovirus immune globulin 95 MG/ML'),
('http://www.nlm.nih.gov/research/umls/rxnorm','451377','cytomegalovirus immune globulin 60 MG/ML'),
('http://www.nlm.nih.gov/research/umls/rxnorm','569664','cytomegalovirus immune globulin 50 MG/ML [Cytogam]')
) AS t (system,code,display) ;