create or replace view irae__lab_creatinine_serum_cr as select * from (values
('http://loinc.org', '103616-9', 'Creatinine [Moles/volume] in Serum or Plasma by LC/MS/MS')
,('http://loinc.org', '11041-1', 'Creatinine [Mass/volume] in Serum or Plasma --post dialysis')
,('http://loinc.org', '11042-9', 'Creatinine [Mass/volume] in Serum or Plasma --pre dialysis')
,('http://loinc.org', '14682-9', 'Creatinine [Moles/volume] in Serum or Plasma')
,('http://loinc.org', '16188-5', 'Creatinine [Mass/volume] in Serum or Plasma --2 hour specimen')
,('http://loinc.org', '16189-3', 'Creatinine [Mass/volume] in Serum or Plasma --4 hour specimen')
,('http://loinc.org', '2160-0', 'Creatinine [Mass/volume] in Serum or Plasma')
,('http://loinc.org', '35203-9', 'Creatinine [Mass or Moles/volume] in Serum or Plasma')
,('http://loinc.org', '39955-0', 'Creatinine [Mass/volume] in Serum or Plasma --pre XXX challenge')
,('http://loinc.org', '39956-8', 'Creatinine [Mass/volume] in Serum or Plasma --1.5 hours pre XXX challenge')
,('http://loinc.org', '39957-6', 'Creatinine [Mass/volume] in Serum or Plasma --1 hour pre XXX challenge')
,('http://loinc.org', '39958-4', 'Creatinine [Mass/volume] in Serum or Plasma --45 minutes pre XXX challenge')
,('http://loinc.org', '39959-2', 'Creatinine [Mass/volume] in Serum or Plasma --30 minutes pre XXX challenge')
,('http://loinc.org', '39960-0', 'Creatinine [Mass/volume] in Serum or Plasma --45 minutes post XXX challenge')
,('http://loinc.org', '39961-8', 'Creatinine [Mass/volume] in Serum or Plasma --3.5 hours post XXX challenge')
,('http://loinc.org', '39962-6', 'Creatinine [Mass/volume] in Serum or Plasma --3.75 hours post XXX challenge')
,('http://loinc.org', '39963-4', 'Creatinine [Mass/volume] in Serum or Plasma --4 hours post XXX challenge')
,('http://loinc.org', '39964-2', 'Creatinine [Mass/volume] in Serum or Plasma --4.5 hours post XXX challenge')
,('http://loinc.org', '39965-9', 'Creatinine [Mass/volume] in Serum or Plasma --5.25 hours post XXX challenge')
,('http://loinc.org', '39966-7', 'Creatinine [Mass/volume] in Serum or Plasma --5.5 hours post XXX challenge')
,('http://loinc.org', '39967-5', 'Creatinine [Mass/volume] in Serum or Plasma --6.5 hours post XXX challenge')
,('http://loinc.org', '39968-3', 'Creatinine [Mass/volume] in Serum or Plasma --8 hours post XXX challenge')
,('http://loinc.org', '39969-1', 'Creatinine [Mass/volume] in Serum or Plasma --9 hours post XXX challenge')
,('http://loinc.org', '39970-9', 'Creatinine [Mass/volume] in Serum or Plasma --10 hours post XXX challenge')
,('http://loinc.org', '39971-7', 'Creatinine [Mass/volume] in Serum or Plasma --12 hours post XXX challenge')
,('http://loinc.org', '39972-5', 'Creatinine [Mass/volume] in Serum or Plasma --16 hours post XXX challenge')
,('http://loinc.org', '39973-3', 'Creatinine [Mass/volume] in Serum or Plasma --18 hours post XXX challenge')
,('http://loinc.org', '39974-1', 'Creatinine [Mass/volume] in Serum or Plasma --2 days post XXX challenge')
,('http://loinc.org', '39975-8', 'Creatinine [Mass/volume] in Serum or Plasma --4 days post XXX challenge')
,('http://loinc.org', '39976-6', 'Creatinine [Mass/volume] in Serum or Plasma --7 days post XXX challenge')
,('http://loinc.org', '40112-5', 'Creatinine [Moles/volume] in Serum or Plasma --pre XXX challenge')
,('http://loinc.org', '40113-3', 'Creatinine [Moles/volume] in Serum or Plasma --1.5 hours pre XXX challenge')
,('http://loinc.org', '40114-1', 'Creatinine [Moles/volume] in Serum or Plasma --1 hour pre XXX challenge')
,('http://loinc.org', '40115-8', 'Creatinine [Moles/volume] in Serum or Plasma --45 minutes pre XXX challenge')
,('http://loinc.org', '40116-6', 'Creatinine [Moles/volume] in Serum or Plasma --30 minutes pre XXX challenge')
,('http://loinc.org', '40117-4', 'Creatinine [Moles/volume] in Serum or Plasma --45 minutes post XXX challenge')
,('http://loinc.org', '40118-2', 'Creatinine [Moles/volume] in Serum or Plasma --3.5 hours post XXX challenge')
,('http://loinc.org', '40119-0', 'Creatinine [Moles/volume] in Serum or Plasma --4 hours post XXX challenge')
,('http://loinc.org', '40120-8', 'Creatinine [Moles/volume] in Serum or Plasma --8 hours post XXX challenge')
,('http://loinc.org', '40121-6', 'Creatinine [Moles/volume] in Serum or Plasma --9 hours post XXX challenge')
,('http://loinc.org', '40122-4', 'Creatinine [Moles/volume] in Serum or Plasma --10 hours post XXX challenge')
,('http://loinc.org', '40123-2', 'Creatinine [Moles/volume] in Serum or Plasma --12 hours post XXX challenge')
,('http://loinc.org', '40124-0', 'Creatinine [Moles/volume] in Serum or Plasma --16 hours post XXX challenge')
,('http://loinc.org', '40125-7', 'Creatinine [Moles/volume] in Serum or Plasma --18 hours post XXX challenge')
,('http://loinc.org', '40126-5', 'Creatinine [Moles/volume] in Serum or Plasma --2 days post XXX challenge')
,('http://loinc.org', '40127-3', 'Creatinine [Moles/volume] in Serum or Plasma --4 days post XXX challenge')
,('http://loinc.org', '40128-1', 'Creatinine [Moles/volume] in Serum or Plasma --7 days post XXX challenge')
,('http://loinc.org', '40248-7', 'Creatinine [Mass/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '40249-5', 'Creatinine [Mass/volume] in Serum or Plasma --30 minutes post XXX challenge')
,('http://loinc.org', '40250-3', 'Creatinine [Mass/volume] in Serum or Plasma --1 hour post XXX challenge')
,('http://loinc.org', '40251-1', 'Creatinine [Mass/volume] in Serum or Plasma --1.5 hours post XXX challenge')
,('http://loinc.org', '40252-9', 'Creatinine [Mass/volume] in Serum or Plasma --2 hours post XXX challenge')
,('http://loinc.org', '40253-7', 'Creatinine [Mass/volume] in Serum or Plasma --2.25 hours post XXX challenge')
,('http://loinc.org', '40254-5', 'Creatinine [Mass/volume] in Serum or Plasma --2.5 hours post XXX challenge')
,('http://loinc.org', '40255-2', 'Creatinine [Mass/volume] in Serum or Plasma --3 hours post XXX challenge')
,('http://loinc.org', '40256-0', 'Creatinine [Mass/volume] in Serum or Plasma --5 hours post XXX challenge')
,('http://loinc.org', '40257-8', 'Creatinine [Mass/volume] in Serum or Plasma --6 hours post XXX challenge')
,('http://loinc.org', '40258-6', 'Creatinine [Mass/volume] in Serum or Plasma --1 day post XXX challenge')
,('http://loinc.org', '40264-4', 'Creatinine [Moles/volume] in Serum or Plasma --baseline')
,('http://loinc.org', '40265-1', 'Creatinine [Moles/volume] in Serum or Plasma --30 minutes post XXX challenge')
,('http://loinc.org', '40266-9', 'Creatinine [Moles/volume] in Serum or Plasma --1 hour post XXX challenge')
,('http://loinc.org', '40267-7', 'Creatinine [Moles/volume] in Serum or Plasma --1.5 hours post XXX challenge')
,('http://loinc.org', '40268-5', 'Creatinine [Moles/volume] in Serum or Plasma --2 hours post XXX challenge')
,('http://loinc.org', '40269-3', 'Creatinine [Moles/volume] in Serum or Plasma --2.5 hours post XXX challenge')
,('http://loinc.org', '40270-1', 'Creatinine [Moles/volume] in Serum or Plasma --3 hours post XXX challenge')
,('http://loinc.org', '40271-9', 'Creatinine [Moles/volume] in Serum or Plasma --5 hours post XXX challenge')
,('http://loinc.org', '40272-7', 'Creatinine [Moles/volume] in Serum or Plasma --6 hours post XXX challenge')
,('http://loinc.org', '40273-5', 'Creatinine [Moles/volume] in Serum or Plasma --1 day post XXX challenge')
,('http://loinc.org', '44784-7', 'Creatinine [Mass/volume] (Maximum value during study) in Serum or Plasma')
,('http://loinc.org', '51619-5', 'Creatinine [Moles/volume] in Serum or Plasma --pre dialysis')
,('http://loinc.org', '51620-3', 'Creatinine [Moles/volume] in Serum or Plasma --post dialysis')
,('http://loinc.org', '62425-4', 'Creatinine [Moles/volume] in Serum or Plasma --post XXX challenge')
,('http://loinc.org', '72271-0', 'Creatinine [Mass/volume] in Serum or Plasma --pre contrast')
,('http://loinc.org', '77140-2', 'Creatinine [Moles/volume] in Serum, Plasma or Blood')
,('http://loinc.org', '93999-1', 'Creatinine [Mass/volume] in Serum or Plasma --1 hour post dose vasopressin')
,('http://loinc.org', '94008-0', 'Creatinine [Mass/volume] in Serum or Plasma --2 hours post dose vasopressin')
) AS t (system, code, display) ;