create or replace view irae__dx_diabetes_ckd as select * from (values
('http://snomed.info/sct', '126551000119103', 'Nephropathy due to secondary diabetes mellitus (disorder)')
,('http://snomed.info/sct', '127013003', 'Disorder of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '127991000119101', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '128001000119105', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332436006', 'Hypertension in chronic kidney disease stage 3B due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332441003', 'Hypertension in chronic kidney disease stage 3A due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332442005', 'Hypertension in chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332464001', 'Hypertension in chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332465000', 'Hypertension in chronic kidney disease stage 3B due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332466004', 'Hypertension in chronic kidney disease stage 3A due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332467008', 'Hypertension in chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332468003', 'Hypertension in chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332469006', 'Chronic kidney disease stage 3B due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332470007', 'Chronic kidney disease stage 3A due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332471006', 'Chronic kidney disease stage 3B due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332472004', 'Chronic kidney disease stage 3A due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140101000119109', 'Hypertension in chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140111000119107', 'Hypertension in chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140121000119100', 'Hypertension in chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '140131000119102', 'Hypertension in chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '157141000119108', 'Proteinuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '18521000119106', 'Microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '197605007', 'Nephrotic syndrome due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '236499007', 'Microalbuminuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '236500003', 'Proteinuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '243421000119104', 'Proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '309426007', 'Glomerulopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '310387003', 'Intracapillary glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '311366001', 'Kimmelstiel-Wilson syndrome (disorder)')
,('http://snomed.info/sct', '368201000119100', 'Disorder of kidney due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368421000119108', 'Chronic kidney disease stage 1 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368431000119106', 'Chronic kidney disease stage 2 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368441000119102', 'Chronic kidney disease stage 3 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368451000119100', 'Chronic kidney disease stage 4 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368461000119103', 'Chronic kidney disease stage 5 due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368471000119109', 'End stage renal disease on dialysis due to drug induced diabetes mellitus (disorder)')
,('http://snomed.info/sct', '38046004', 'Diffuse glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420279001', 'Renal disorder due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420514000', 'Persistent proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420715001', 'Persistent microalbuminuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421305000', 'Persistent microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421893009', 'Renal disorder due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421986006', 'Persistent proteinuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '425455002', 'Glomerulonephritis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '445170001', 'Macroalbuminuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '63510008', 'Nodular glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '707221002', 'Glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '711000119100', 'Chronic kidney disease stage 5 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71421000119105', 'Hypertension in chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71441000119104', 'Nephrotic syndrome due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71701000119105', 'Hypertension in chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71721000119101', 'Nephrotic syndrome due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '721000119107', 'Chronic kidney disease stage 4 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '723074006', 'Renal papillary necrosis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '731000119105', 'Chronic kidney disease stage 3 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '741000119101', 'Chronic kidney disease stage 2 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '751000119104', 'Chronic kidney disease stage 1 due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '771000119108', 'Chronic kidney disease due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '792926007', 'Armanni-Ebstein kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90721000119101', 'Chronic kidney disease stage 1 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90731000119103', 'Chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90741000119107', 'Chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90751000119109', 'Chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90761000119106', 'Chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90771000119100', 'End stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90781000119102', 'Microalbuminuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90791000119104', 'End stage renal disease on dialysis due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '96441000119101', 'Chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.21', 'Diabetes mellitus due to underlying condition with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.22', 'Diabetes mellitus due to underlying condition with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.29', 'Diabetes mellitus due to underlying condition with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.21', 'Drug or chemical induced diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.22', 'Drug or chemical induced diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.29', 'Drug or chemical induced diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.21', 'Type 1 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.22', 'Type 1 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.29', 'Type 1 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.21', 'Type 2 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.22', 'Type 2 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.29', 'Type 2 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.21', 'Other specified diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.22', 'Other specified diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.29', 'Other specified diabetes mellitus with other diabetic kidney complication')
) AS t (system, code, display) ;