create or replace view irae__rx_cyclosporin as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', 'code', 'display')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093172', 'cycloSPORINE 0.002 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093172', 'cyclosporine 0.002 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093173', 'cycloSPORINE Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093173', 'cyclosporine Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093174', 'cycloSPORINE 0.002 MG/MG Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093174', 'cycloSPORINE 0.2 % Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093174', 'cyclosporine 0.002 MG/MG Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093174', 'cyclosporine 0.2 % Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093176', 'cycloSPORINE 0.002 MG/MG [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093176', 'cyclosporine 0.002 MG/MG [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093177', 'cycloSPORINE Ophthalmic Ointment [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093177', 'cyclosporine Ophthalmic Ointment [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093178', 'cycloSPORINE 0.002 MG/MG Ophthalmic Ointment [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093178', 'cyclosporine 0.002 MG/MG Ophthalmic Ointment [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156186', 'cycloSPORINE Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156186', 'cyclosporine Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156187', 'cycloSPORINE Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156187', 'cyclosporine Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156188', 'cycloSPORINE Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156188', 'cyclosporine Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156189', 'cycloSPORINE Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156189', 'cyclosporine Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156190', 'cycloSPORINE Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156190', 'cyclosporine Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169824', 'Gengraf Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169825', 'Gengraf Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169826', 'Gengraf Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1181672', 'Neoral Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1181673', 'Neoral Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1181674', 'Neoral Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182527', 'Restasis Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185408', 'SandIMMUNE Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185408', 'Sandimmune Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185409', 'SandIMMUNE Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185409', 'Sandimmune Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185410', 'SandIMMUNE Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185410', 'Sandimmune Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185411', 'SandIMMUNE Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185411', 'Sandimmune Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233905', 'cycloSPORINE, modified 100 MG/ML [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233905', 'cyclosporine, modified 100 MG/ML [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233906', 'cycloSPORINE Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233906', 'cyclosporine Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233908', 'cycloSPORINE, modified 100 MG/ML Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233908', 'cyclosporine, modified 100 MG/ML Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732364', 'cycloSPORINE Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732364', 'cyclosporine Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732366', 'cycloSPORINE Injection [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732366', 'cyclosporine Injection [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197552', 'SandIMMUNE 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197552', 'Sandimmune 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197552', 'cycloSPORINE 100 MG Oral Capsule [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197552', 'cyclosporine 100 MG Oral Capsule [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197553', 'cycloSPORINE 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197553', 'cyclosporine 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202816', 'SandIMMUNE')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202816', 'Sandimmune')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202817', 'Neoral')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205168', 'cycloSPORINE 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205168', 'cyclosporine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', '5 ML cycloSPORINE 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', '5 ML cyclosporine 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', 'cycloSPORINE 250 MG in 5 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', 'cycloSPORINE 250 MG per 5 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', 'cyclosporine 250 MG per 5 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055019', 'cycloSPORINE 0.9 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055019', 'cyclosporine 0.9 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055020', 'cycloSPORINE Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055020', 'cyclosporine Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055021', 'cycloSPORINE 0.09 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055021', 'cycloSPORINE 0.9 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055021', 'cyclosporine 0.09 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055021', 'cyclosporine 0.9 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055022', 'Cequa')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055023', 'cycloSPORINE 0.9 MG/ML [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055023', 'cyclosporine 0.9 MG/ML [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055024', 'cycloSPORINE Ophthalmic Solution [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055024', 'cyclosporine Ophthalmic Solution [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055025', 'Cequa Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055026', 'Cequa 0.09 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055026', 'Cequa 0.9 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055026', 'cycloSPORINE 0.9 MG/ML Ophthalmic Solution [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055026', 'cyclosporine 0.9 MG/ML Ophthalmic Solution [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212810', 'SandIMMUNE 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212810', 'Sandimmune 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212810', 'cycloSPORINE 25 MG Oral Capsule [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212810', 'cyclosporine 25 MG Oral Capsule [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', '5 ML SandIMMUNE 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', '5 ML Sandimmune 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', '5 ML cycloSPORINE 50 MG/ML Injection [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', '5 ML cyclosporine 50 MG/ML Injection [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', 'SandIMMUNE 250 MG in 5 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', 'SandIMMUNE 250 MG per 5 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', 'Sandimmune 250 MG per 5 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'SandIMMUNE 100 MG in 1 mL Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'SandIMMUNE 100 MG per 1 ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'SandIMMUNE 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'Sandimmune 100 MG per 1 ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'Sandimmune 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'cycloSPORINE 100 MG/ML Oral Solution [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'cyclosporine 100 MG/ML Oral Solution [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '236077', 'cycloSPORINE, modified')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '236077', 'cyclosporine, modified')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '241834', 'cycloSPORINE, modified 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '241834', 'cyclosporine, modified 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470533', 'cycloSPORINE, modified 100 MG/ML [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470533', 'cyclosporine, modified 100 MG/ML [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470534', 'cycloSPORINE Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470534', 'cyclosporine Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470537', 'cycloSPORINE, modified 100 MG/ML Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470537', 'cyclosporine, modified 100 MG/ML Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', '0.4 ML cycloSPORINE 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', '0.4 ML cyclosporine 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', 'cycloSPORINE 0.05 % in 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', 'cycloSPORINE 0.05 % per 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', 'cycloSPORINE 0.5 MG/ML per 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', 'cyclosporine 0.05 % per 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', 'cyclosporine 0.5 MG/ML per 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572293', '0.4 ML Restasis 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572293', '0.4 ML cycloSPORINE 0.5 MG/ML Ophthalmic Suspension [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572293', '0.4 ML cyclosporine 0.5 MG/ML Ophthalmic Suspension [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572293', 'Restasis 0.05 % in 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572293', 'Restasis 0.05 % per 0.4 ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590607', 'cycloSPORINE 1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590607', 'cyclosporine 1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590608', 'cycloSPORINE 0.1 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590608', 'cycloSPORINE 1 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590608', 'cyclosporine 0.1 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590608', 'cyclosporine 1 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590610', 'cycloSPORINE 1 MG/ML [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590610', 'cyclosporine 1 MG/ML [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590612', 'cycloSPORINE Ophthalmic Suspension [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590612', 'cyclosporine Ophthalmic Suspension [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590613', 'cycloSPORINE 1 MG/ML Ophthalmic Suspension [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590613', 'cyclosporine 1 MG/ML Ophthalmic Suspension [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261530', 'Gengraf')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639936', 'cycloSPORINE 0.1 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639936', 'cycloSPORINE 1 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639936', 'cyclosporine 0.1 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639936', 'cyclosporine 1 MG/ML Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639938', 'cycloSPORINE 1 MG/ML [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639938', 'cyclosporine 1 MG/ML [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639940', 'cycloSPORINE Ophthalmic Solution [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639940', 'cyclosporine Ophthalmic Solution [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639941', 'cycloSPORINE 1 MG/ML Ophthalmic Solution [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639941', 'cyclosporine 1 MG/ML Ophthalmic Solution [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2645340', 'cycloSPORINE, modified Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2645340', 'cyclosporine, modified Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2647505', 'cycloSPORINE, modified Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2647505', 'cyclosporine, modified Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2654174', 'cycloSPORINE, modified Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2654174', 'cyclosporine, modified Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2656813', 'cycloSPORINE, modified Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2656813', 'cyclosporine, modified Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657003', 'cycloSPORINE, modified Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657003', 'cyclosporine, modified Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657141', 'cycloSPORINE, modified Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657141', 'cyclosporine, modified Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657509', 'cycloSPORINE, modified Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657509', 'cyclosporine, modified Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657747', 'cycloSPORINE, modified Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657747', 'cyclosporine, modified Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658601', 'cycloSPORINE, modified Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658601', 'cyclosporine, modified Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2660112', 'cycloSPORINE, modified Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2660112', 'cyclosporine, modified Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2662711', 'cycloSPORINE, modified Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2662711', 'cyclosporine, modified Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2663521', 'cycloSPORINE, modified Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2663521', 'cyclosporine, modified Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665976', 'cycloSPORINE, modified 100 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665976', 'cyclosporine, modified 100 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665979', 'cycloSPORINE Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665979', 'cyclosporine Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665980', 'cycloSPORINE, modified Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665980', 'cyclosporine, modified Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665981', 'cycloSPORINE, modified 100 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665981', 'cyclosporine, modified 100 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665982', 'cycloSPORINE, modified 25 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665982', 'cyclosporine, modified 25 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665983', 'cycloSPORINE, modified 25 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665983', 'cyclosporine, modified 25 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665984', 'cycloSPORINE, modified 50 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665984', 'cyclosporine, modified 50 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665985', 'cycloSPORINE, modified 50 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665985', 'cyclosporine, modified 50 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '3008', 'cycloSPORINE')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '3008', 'cyclosporine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309632', 'cycloSPORINE 100 MG in 1 mL Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309632', 'cycloSPORINE 100 MG per 1 ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309632', 'cycloSPORINE 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309632', 'cyclosporine 100 MG per 1 ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309632', 'cyclosporine 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315749', 'cycloSPORINE 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315749', 'cyclosporine 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315750', 'cycloSPORINE 100 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315750', 'cyclosporine 100 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315751', 'cycloSPORINE 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315751', 'cyclosporine 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315752', 'cycloSPORINE 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315752', 'cyclosporine 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315753', 'cycloSPORINE 50 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315753', 'cyclosporine 50 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328160', 'cycloSPORINE 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328160', 'cyclosporine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '334294', 'cycloSPORINE, modified 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '334294', 'cyclosporine, modified 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'cycloSPORINE 0.05 % Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'cycloSPORINE 0.05 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'cycloSPORINE 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'cyclosporine 0.05 % Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'cyclosporine 0.05 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'cyclosporine 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '352951', 'Restasis')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '353400', 'cycloSPORINE 0.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '353400', 'cyclosporine 0.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363914', 'cycloSPORINE Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363914', 'cyclosporine Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363942', 'cycloSPORINE Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363942', 'cyclosporine Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366173', 'cycloSPORINE Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366173', 'cyclosporine Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366479', 'cycloSPORINE Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366479', 'cyclosporine Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366488', 'cycloSPORINE Oral Capsule [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366488', 'cyclosporine Oral Capsule [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371666', 'cycloSPORINE Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371666', 'cyclosporine Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371667', 'cycloSPORINE Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371667', 'cyclosporine Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '378766', 'cycloSPORINE Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '378766', 'cyclosporine Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402092', 'Restasis 0.05 % Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402092', 'Restasis 0.05 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402092', 'Restasis 0.5 MG/ML Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402092', 'cycloSPORINE 0.5 MG/ML Ophthalmic Suspension [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402092', 'cyclosporine 0.5 MG/ML Ophthalmic Suspension [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402330', 'cycloSPORINE Ophthalmic Suspension [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402330', 'cyclosporine Ophthalmic Suspension [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484788', 'cycloSPORINE microemulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484788', 'cyclosporine microemulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '486331', 'cycloSPORINE 100 MG/ML [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '486331', 'cyclosporine 100 MG/ML [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '539499', 'cycloSPORINE Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '539499', 'cyclosporine Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '565430', 'cycloSPORINE 100 MG [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '565430', 'cyclosporine 100 MG [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572889', 'cycloSPORINE 25 MG [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572889', 'cyclosporine 25 MG [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572915', 'cycloSPORINE 50 MG/ML [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572915', 'cyclosporine 50 MG/ML [Sandimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '576100', 'cycloSPORINE 0.5 MG/ML [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '576100', 'cyclosporine 0.5 MG/ML [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835787', 'cycloSPORINE, modified 100 MG [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835787', 'cyclosporine, modified 100 MG [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835835', 'GENGRAF 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835835', 'Gengraf 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835835', 'cycloSPORINE, modified 100 MG Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835835', 'cyclosporine, modified 100 MG Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835885', 'cycloSPORINE, modified 100 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835885', 'cyclosporine, modified 100 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835886', 'cycloSPORINE, modified 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835886', 'cycloSPORINE, modified 100 MG/mL Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835886', 'cyclosporine, modified 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835887', 'cycloSPORINE, modified 100 MG/ML [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835887', 'cyclosporine, modified 100 MG/ML [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835892', 'GENGRAF 100 MG in 1 mL Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835892', 'Gengraf 100 MG per 1 ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835892', 'cycloSPORINE, modified 100 MG/ML Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835892', 'cyclosporine, modified 100 MG/ML Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835893', 'cycloSPORINE, modified 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835893', 'cyclosporine, modified 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835894', 'cycloSPORINE, modified 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835894', 'cyclosporine, modified 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835895', 'cycloSPORINE, modified 25 MG [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835895', 'cyclosporine, modified 25 MG [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835896', 'GENGRAF 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835896', 'Gengraf 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835896', 'cycloSPORINE, modified 25 MG Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835896', 'cyclosporine, modified 25 MG Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835897', 'cycloSPORINE, modified 100 MG/ML [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835897', 'cyclosporine, modified 100 MG/ML [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835899', 'NEORAL 100 MG in 1 mL Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835899', 'Neoral 100 MG per 1 ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835899', 'cycloSPORINE, modified 100 MG/ML Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835899', 'cyclosporine, modified 100 MG/ML Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835900', 'cycloSPORINE, modified 100 MG [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835900', 'cyclosporine, modified 100 MG [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835901', 'cycloSPORINE, modified 25 MG [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835901', 'cyclosporine, modified 25 MG [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835909', 'Neoral 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835909', 'cycloSPORINE, modified 25 MG Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835909', 'cyclosporine, modified 25 MG Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835911', 'Neoral 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835911', 'cycloSPORINE, modified 100 MG Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835911', 'cyclosporine, modified 100 MG Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835916', 'cycloSPORINE, modified 100 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835916', 'cyclosporine, modified 100 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835917', 'cycloSPORINE, modified 100 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835917', 'cyclosporine, modified 100 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835918', 'cycloSPORINE, modified 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835918', 'cyclosporine, modified 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835919', 'cycloSPORINE, modified 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835919', 'cyclosporine, modified 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835920', 'cycloSPORINE, modified 10 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835920', 'cyclosporine, modified 10 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835921', 'cycloSPORINE, modified 10 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835921', 'cyclosporine, modified 10 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835922', 'cycloSPORINE, modified 25 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835922', 'cyclosporine, modified 25 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835923', 'cycloSPORINE, modified 25 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835923', 'cyclosporine, modified 25 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835924', 'cycloSPORINE, modified 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835924', 'cyclosporine, modified 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835925', 'cycloSPORINE, modified 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835925', 'cyclosporine, modified 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835926', 'cycloSPORINE, modified 50 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835926', 'cyclosporine, modified 50 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835927', 'cycloSPORINE, modified 50 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835927', 'cyclosporine, modified 50 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '94035', 'cycloSPORINE Oral Solution [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '94035', 'cyclosporine Oral Solution [Sandimmune]')
) AS t (system, code, display) ;