create or replace view irae__dx_transplant_kidney as select * from (values
('http://www.cms.gov/Medicare/Coding/ICD10', '0TY00Z0', 'Transplantation of Right Kidney, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0TY00Z1', 'Transplantation of Right Kidney, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0TY00Z2', 'Transplantation of Right Kidney, Zooplastic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0TY10Z0', 'Transplantation of Left Kidney, Allogeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0TY10Z1', 'Transplantation of Left Kidney, Syngeneic, Open Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '0TY10Z2', 'Transplantation of Left Kidney, Zooplastic, Open Approach')
,('http://snomed.info/sct', '113127005', 'Kidney transplant evaluation (procedure)')
,('http://snomed.info/sct', '122531000119108', 'Lymphoproliferative disorder following kidney transplant (disorder)')
,('http://snomed.info/sct', '128631000119109', 'Chronic graft-versus-host disease following kidney transplant (disorder)')
,('http://snomed.info/sct', '175948009', 'Exploration of renal transplant (procedure)')
,('http://snomed.info/sct', '213150003', 'Kidney transplant failure and rejection (disorder)')
,('http://snomed.info/sct', '241484009', 'Ultrasound scan of transplant kidney (procedure)')
,('http://snomed.info/sct', '428575007', 'Hypertension secondary to kidney transplant (disorder)')
,('http://snomed.info/sct', '428645009', 'Examination of recipient after kidney transplant (procedure)')
,('http://snomed.info/sct', '431988002', 'Doppler ultrasonography of transplanted kidney (procedure)')
,('http://snomed.info/sct', '440449002', 'Magnetic resonance angiography of transplanted kidney (procedure)')
,('http://snomed.info/sct', '440512006', 'Biopsy of transplanted kidney using ultrasound guidance (procedure)')
,('http://snomed.info/sct', '443578000', 'Radionuclide imaging of transplanted kidney (procedure)')
,('http://snomed.info/sct', '473195006', 'Renal function of transplanted kidney within reference range (finding)')
,('http://snomed.info/sct', '58797008', 'Disorder due to and following transplant of kidney (disorder)')
,('http://snomed.info/sct', '6471000179103', 'Transplantation of kidney and pancreas (procedure)')
,('http://snomed.info/sct', '6501000179109', 'Laparoscopic biopsy of transplanted kidney (procedure)')
,('http://snomed.info/sct', '70536003', 'Transplant of kidney (procedure)')
,('http://snomed.info/sct', '713825007', 'Renal artery stenosis of transplanted kidney (disorder)')
,('http://snomed.info/sct', '714153000', 'Chronic kidney disease stage 5 with transplant (disorder)')
,('http://snomed.info/sct', '718030008', 'Antegrade insertion of stent into transplanted ureter using fluoroscopic guidance (procedure)')
,('http://snomed.info/sct', '718031007', 'Retrograde insertion of stent into transplanted ureter using fluoroscopic guidance (procedure)')
,('http://snomed.info/sct', '737295003', 'Transplanted kidney present (finding)')
,('http://snomed.info/sct', '764643003', 'Removal of nephrostomy tube from transplanted kidney using fluoroscopic guidance (procedure)')
,('http://snomed.info/sct', '782655004', 'Laparoscopic transplant of kidney using robotic assistance (procedure)')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT2900Z', 'Computerized Tomography (CT Scan) of Kidney Transplant using High Osmolar Contrast, Unenhanced and Enhanced')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT290ZZ', 'Computerized Tomography (CT Scan) of Kidney Transplant using High Osmolar Contrast')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT2910Z', 'Computerized Tomography (CT Scan) of Kidney Transplant using Low Osmolar Contrast, Unenhanced and Enhanced')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT291ZZ', 'Computerized Tomography (CT Scan) of Kidney Transplant using Low Osmolar Contrast')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT29Y0Z', 'Computerized Tomography (CT Scan) of Kidney Transplant using Other Contrast, Unenhanced and Enhanced')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT29YZZ', 'Computerized Tomography (CT Scan) of Kidney Transplant using Other Contrast')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT29ZZZ', 'Computerized Tomography (CT Scan) of Kidney Transplant')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT39Y0Z', 'Magnetic Resonance Imaging (MRI) of Kidney Transplant using Other Contrast, Unenhanced and Enhanced')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT39YZZ', 'Magnetic Resonance Imaging (MRI) of Kidney Transplant using Other Contrast')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT39ZZZ', 'Magnetic Resonance Imaging (MRI) of Kidney Transplant')
,('http://www.cms.gov/Medicare/Coding/ICD10', 'BT49ZZZ', 'Ultrasonography of Kidney Transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.1', 'Complications of kidney transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.10', 'Unspecified complication of kidney transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.11', 'Kidney transplant rejection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.12', 'Kidney transplant failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.13', 'Kidney transplant infection')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T86.19', 'Other complication of kidney transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z48.22', 'Encounter for aftercare following kidney transplant')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Z94.0', 'Kidney transplant status')
) AS t (system, code, display) ;