create or replace view irae__dx_kidney_nephrotic_syndrome as select * from (values
('http://snomed.info/sct', '101711000119105', 'Glomerulonephritis co-occurrent and due to antineutrophil cytoplasmic antibody positive vasculitis (disorder)')
,('http://snomed.info/sct', '111395007', 'Arginine vasopressin resistance (disorder)')
,('http://snomed.info/sct', '11480007', 'Idiopathic granulomatous interstitial nephropathy (disorder)')
,('http://snomed.info/sct', '123609007', 'Subacute glomerulonephritis (disorder)')
,('http://snomed.info/sct', '123610002', 'Healed glomerulonephritis (disorder)')
,('http://snomed.info/sct', '123752003', 'Immune-complex glomerulonephritis (disorder)')
,('http://snomed.info/sct', '12491000132101', 'Isolated proteinuria (finding)')
,('http://snomed.info/sct', '12511000132108', 'Persistent proteinuria (finding)')
,('http://snomed.info/sct', '13335004', 'Sclerosing glomerulonephritis (disorder)')
,('http://snomed.info/sct', '1426004', 'Necrotizing glomerulonephritis (disorder)')
,('http://snomed.info/sct', '157141000119108', 'Proteinuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '15911000119103', 'Primary tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '1776003', 'Renal tubular acidosis (disorder)')
,('http://snomed.info/sct', '18521000119106', 'Microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '19351000', 'Acute glomerulonephritis (disorder)')
,('http://snomed.info/sct', '194909006', 'Acute pericarditis co-occurrent and due to uremia (disorder)')
,('http://snomed.info/sct', '197579006', 'Acute proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197580009', 'Acute nephritis with lesions of necrotizing glomerulitis (disorder)')
,('http://snomed.info/sct', '197582001', 'Acute glomerulonephritis associated with another disorder (disorder)')
,('http://snomed.info/sct', '197584000', 'Acute focal nephritis (disorder)')
,('http://snomed.info/sct', '197585004', 'Acute diffuse nephritis (disorder)')
,('http://snomed.info/sct', '197589005', 'Nephrotic syndrome with proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197590001', 'Nephrotic syndrome with membranous glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197591002', 'Nephrotic syndrome with membranoproliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197593004', 'Nephrotic syndrome, minor glomerular abnormality (disorder)')
,('http://snomed.info/sct', '197594005', 'Nephrotic syndrome, focal and segmental glomerular lesions (disorder)')
,('http://snomed.info/sct', '197595006', 'Nephrotic syndrome, diffuse membranous glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197596007', 'Nephrotic syndrome, diffuse mesangial proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197597003', 'Nephrotic syndrome, diffuse endocapillary proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197598008', 'Nephrotic syndrome, diffuse mesangiocapillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197599000', 'Nephrotic syndrome, dense deposit disease (disorder)')
,('http://snomed.info/sct', '197600002', 'Nephrotic syndrome, diffuse crescentic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197601003', 'Finnish congenital nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '197603000', 'Nephrotic syndrome associated with another disorder (disorder)')
,('http://snomed.info/sct', '197605007', 'Nephrotic syndrome due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '197607004', 'Nephrotic syndrome in polyarteritis nodosa (disorder)')
,('http://snomed.info/sct', '197613008', 'Chronic mesangial proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197617009', 'Chronic exudative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197618004', 'Chronic focal glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197619007', 'Chronic diffuse glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197626007', 'Focal membranoproliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197629000', 'Anaphylactoid glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197661001', 'Glomerulosclerosis (disorder)')
,('http://snomed.info/sct', '197664009', 'Phosphate-losing tubular disorders (disorder)')
,('http://snomed.info/sct', '197671004', 'Renal function impairment with growth failure (disorder)')
,('http://snomed.info/sct', '197679002', 'Glomerular disease (disorder)')
,('http://snomed.info/sct', '197681000', 'Acute nephritic syndrome, minor glomerular abnormality (disorder)')
,('http://snomed.info/sct', '197682007', 'Acute nephritic syndrome, focal and segmental glomerular lesions (disorder)')
,('http://snomed.info/sct', '197683002', 'Acute nephritic syndrome, diffuse membranous glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197684008', 'Acute nephritic syndrome, diffuse mesangial proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197685009', 'Acute nephritic syndrome, diffuse endocapillary proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197686005', 'Acute nephritic syndrome, diffuse mesangiocapillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197687001', 'Acute nephritic syndrome, dense deposit disease (disorder)')
,('http://snomed.info/sct', '197688006', 'Acute nephritic syndrome, diffuse crescentic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197689003', 'Rapidly progressive nephritic syndrome (disorder)')
,('http://snomed.info/sct', '197690007', 'Rapidly progressive nephritic syndrome, minor glomerular abnormality (disorder)')
,('http://snomed.info/sct', '197691006', 'Rapidly progressive nephritic syndrome, focal and segmental glomerular lesions (disorder)')
,('http://snomed.info/sct', '197692004', 'Rapidly progressive nephritic syndrome, diffuse membranous glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197693009', 'Rapidly progressive nephritic syndrome, diffuse mesangial proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197694003', 'Rapidly progressive nephritic syndrome, diffuse endocapillary proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197695002', 'Rapidly progressive nephritic syndrome, diffuse mesangiocapillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197696001', 'Rapidly progressive nephritic syndrome, dense deposit disease (disorder)')
,('http://snomed.info/sct', '197697005', 'Rapidly progressive nephritic syndrome, diffuse crescentic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197707007', 'Chronic nephritic syndrome (disorder)')
,('http://snomed.info/sct', '197708002', 'Chronic nephritic syndrome, minor glomerular abnormality (disorder)')
,('http://snomed.info/sct', '197709005', 'Chronic nephritic syndrome, focal and segmental glomerular lesions (disorder)')
,('http://snomed.info/sct', '197712008', 'Chronic nephritic syndrome, diffuse endocapillary proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197713003', 'Chronic nephritic syndrome, diffuse mesangiocapillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197714009', 'Chronic nephritic syndrome, dense deposit disease (disorder)')
,('http://snomed.info/sct', '197715005', 'Chronic nephritic syndrome, diffuse crescentic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '197739000', 'Glomerular disorders in blood diseases and disorders involving the immune mechanism (disorder)')
,('http://snomed.info/sct', '197769007', 'Acute pyelonephritis with medullary necrosis (disorder)')
,('http://snomed.info/sct', '20917003', 'Chronic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '22702000', 'Glomerulitis (disorder)')
,('http://snomed.info/sct', '236374007', 'Chronic infective interstitial nephritis (disorder)')
,('http://snomed.info/sct', '236380004', 'Steroid-sensitive nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '236381000', 'Steroid-resistant nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '236382007', 'Steroid-dependent nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '236383002', 'Familial mesangial sclerosis (disorder)')
,('http://snomed.info/sct', '236384008', 'Congenital nephrotic syndrome with focal glomerulosclerosis (disorder)')
,('http://snomed.info/sct', '236385009', 'Drash syndrome (disorder)')
,('http://snomed.info/sct', '236392004', 'Rapidly progressive glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236393009', 'Endocapillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236394003', 'Idiopathic endocapillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236395002', 'Post-infectious glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236397005', 'Post-infectious glomerulonephritis - Garland variety (disorder)')
,('http://snomed.info/sct', '236398000', 'Crescentic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236399008', 'Steroid-sensitive minimal change glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236400001', 'Steroid-resistant minimal change glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236401002', 'Steroid-dependent minimal change glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236402009', 'Glomerulopathy due to ischemia (disorder)')
,('http://snomed.info/sct', '236403004', 'Focal segmental glomerulosclerosis (disorder)')
,('http://snomed.info/sct', '236404005', 'Classical focal segmental glomerulosclerosis (disorder)')
,('http://snomed.info/sct', '236405006', 'Hyperfiltration focal segmental glomerulosclerosis (disorder)')
,('http://snomed.info/sct', '236407003', 'Immunoglobulin A nephropathy (disorder)')
,('http://snomed.info/sct', '236409000', 'Mesangiocapillary glomerulonephritis type III (disorder)')
,('http://snomed.info/sct', '236410005', 'Mesangiocapillary glomerulonephritis type IV (disorder)')
,('http://snomed.info/sct', '236411009', 'Immunoglobulin M nephropathy (disorder)')
,('http://snomed.info/sct', '236412002', 'C1q nephropathy (disorder)')
,('http://snomed.info/sct', '236413007', 'Membranous glomerulonephritis - stage I (disorder)')
,('http://snomed.info/sct', '236414001', 'Membranous glomerulonephritis - stage II (disorder)')
,('http://snomed.info/sct', '236415000', 'Membranous glomerulonephritis - stage III (disorder)')
,('http://snomed.info/sct', '236416004', 'Membranous glomerulonephritis - stage IV (disorder)')
,('http://snomed.info/sct', '236417008', 'Membranous glomerulonephritis stage V (disorder)')
,('http://snomed.info/sct', '236418003', 'Thin basement membrane disease (disorder)')
,('http://snomed.info/sct', '236419006', 'Progressive hereditary glomerulonephritis without deafness (disorder)')
,('http://snomed.info/sct', '236452000', 'Chronic drug-induced tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '236453005', 'Chronic tubulointerstitial nephritis caused by heavy metal (disorder)')
,('http://snomed.info/sct', '236454004', 'Chronic lead nephropathy (disorder)')
,('http://snomed.info/sct', '236455003', 'Saturnine nephropathy (disorder)')
,('http://snomed.info/sct', '236456002', 'Chronic cadmium nephropathy (disorder)')
,('http://snomed.info/sct', '236457006', 'Chronic mercury nephropathy (disorder)')
,('http://snomed.info/sct', '236458001', 'Granulomatous tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '236460004', 'Familial proximal renal tubular acidosis (disorder)')
,('http://snomed.info/sct', '236461000', 'Distal renal tubular acidosis (disorder)')
,('http://snomed.info/sct', '236463002', 'Hyperkalemic renal tubular acidosis (disorder)')
,('http://snomed.info/sct', '236466005', 'Congenital Fanconi syndrome (disorder)')
,('http://snomed.info/sct', '236479001', 'Magnesium-losing nephropathy (disorder)')
,('http://snomed.info/sct', '236480003', 'Inherited magnesium-losing nephropathy (disorder)')
,('http://snomed.info/sct', '236499007', 'Microalbuminuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '236500003', 'Proteinuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '236503001', 'Acute scleroderma renal crisis (disorder)')
,('http://snomed.info/sct', '236508005', 'Malignancy-associated glomerulonephritis (disorder)')
,('http://snomed.info/sct', '236524006', 'Acute radiation nephritis (disorder)')
,('http://snomed.info/sct', '236530006', 'Pulmonic stenosis and congenital nephrosis (disorder)')
,('http://snomed.info/sct', '236532003', 'Renal tubular acidosis with progressive nerve deafness (disorder)')
,('http://snomed.info/sct', '236535001', 'Glomerulopathy with giant fibrillar deposits (disorder)')
,('http://snomed.info/sct', '236587002', 'Transplant glomerulopathy (disorder)')
,('http://snomed.info/sct', '236588007', 'Transplant glomerulopathy - early form (disorder)')
,('http://snomed.info/sct', '236589004', 'Transplant glomerulopathy - late form (disorder)')
,('http://snomed.info/sct', '236590008', 'Cytomegalovirus-induced glomerulonephritis (disorder)')
,('http://snomed.info/sct', '239932005', 'Primary pauci-immune necrotizing and crescentic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '243421000119104', 'Proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '24790002', 'Proximal renal tubular acidosis (disorder)')
,('http://snomed.info/sct', '253864004', 'Familial hypoplastic, glomerulocystic kidney (disorder)')
,('http://snomed.info/sct', '25821008', 'Focal glomerular sclerosis (disorder)')
,('http://snomed.info/sct', '26121002', 'Balkan nephropathy (disorder)')
,('http://snomed.info/sct', '266549004', 'Nephrotic syndrome with minimal change glomerulonephritis (disorder)')
,('http://snomed.info/sct', '270494003', 'Acute papillary necrosis (disorder)')
,('http://snomed.info/sct', '276585000', 'Congenital nephritis (disorder)')
,('http://snomed.info/sct', '28191000119109', 'Chronic nephritic syndrome with membranous glomerulonephritis (disorder)')
,('http://snomed.info/sct', '282364005', 'Immunoglobulin A nephropathy associated with liver disease (disorder)')
,('http://snomed.info/sct', '307755009', 'Renal tubulo-interstitial disorder due to systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '309426007', 'Glomerulopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '311366001', 'Kimmelstiel-Wilson syndrome (disorder)')
,('http://snomed.info/sct', '320681000119102', 'Tubulointerstitial nephropathy due to Sjogren syndrome (disorder)')
,('http://snomed.info/sct', '33763006', 'Hypercalcemic nephropathy (disorder)')
,('http://snomed.info/sct', '35546006', 'Mesangial proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '359694003', 'Idiopathic crescentic glomerulonephritis, type II (disorder)')
,('http://snomed.info/sct', '36171008', 'Glomerulonephritis (disorder)')
,('http://snomed.info/sct', '363234001', 'Nephrotic syndrome secondary to systemic disease (disorder)')
,('http://snomed.info/sct', '368901000119106', 'Chronic nephritic syndrome co-occurrent and due to membranoproliferative glomerulonephritis type III (disorder)')
,('http://snomed.info/sct', '368921000119102', 'Nephritic syndrome co-occurrent and due to membranoproliferative glomerulonephritis type III (disorder)')
,('http://snomed.info/sct', '3704008', 'Diffuse endocapillary proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '370494002', 'Protein-losing nephropathy (disorder)')
,('http://snomed.info/sct', '37061001', 'Granulomatous sarcoid nephropathy (disorder)')
,('http://snomed.info/sct', '37085009', 'Shunt nephritis (disorder)')
,('http://snomed.info/sct', '399094007', 'Familial hematuria (disorder)')
,('http://snomed.info/sct', '399190000', 'Non-progressive hereditary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '399340005', 'Hereditary nephritis (disorder)')
,('http://snomed.info/sct', '40233000', 'Nephrotic-nephritic syndrome (disorder)')
,('http://snomed.info/sct', '418839003', 'Tubulointerstitial nephritis with uveitis syndrome (disorder)')
,('http://snomed.info/sct', '420514000', 'Persistent proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420715001', 'Persistent microalbuminuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421305000', 'Persistent microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421986006', 'Persistent proteinuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '42231000009109', 'Bacterial nephritis (disorder)')
,('http://snomed.info/sct', '424188009', 'Idiopathic interstitial tubulonephritis (disorder)')
,('http://snomed.info/sct', '425384007', 'Sarcoidosis with glomerulonephritis (disorder)')
,('http://snomed.info/sct', '428255004', 'Tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '439990003', 'Drug-induced tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '440018001', 'Heavy-metal-induced tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '441815006', 'Proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '444977005', 'Autosomal dominant focal segmental glomerulosclerosis (disorder)')
,('http://snomed.info/sct', '445170001', 'Macroalbuminuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '445258009', 'Idiopathic rapidly progressive glomerulonephritis (disorder)')
,('http://snomed.info/sct', '445388002', 'Autosomal recessive focal segmental glomerulosclerosis (disorder)')
,('http://snomed.info/sct', '445404003', 'Familial immunoglobulin A nephropathy (disorder)')
,('http://snomed.info/sct', '446923008', 'Lipoprotein glomerulopathy (disorder)')
,('http://snomed.info/sct', '44785005', 'Minimal change disease (disorder)')
,('http://snomed.info/sct', '45927004', 'Immunologic mediated tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '48796009', 'Congenital nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '50411000119108', 'Secondary tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '52254009', 'Nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '52845002', 'Nephritis (disorder)')
,('http://snomed.info/sct', '53556002', 'Cis-platinum nephropathy (disorder)')
,('http://snomed.info/sct', '54879000', 'Hypokalemic nephropathy (disorder)')
,('http://snomed.info/sct', '55652009', 'Idiopathic crescentic glomerulonephritis, type III (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '580.4', 'Acute glomerulonephritis with lesion of rapidly progressive glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '580.81', 'Acute glomerulonephritis in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-9-cm', '580.89', 'Acute glomerulonephritis with other specified pathological lesion in kidney')
,('http://hl7.org/fhir/sid/icd-9-cm', '580.9', 'Acute glomerulonephritis with unspecified pathological lesion in kidney')
,('http://hl7.org/fhir/sid/icd-9-cm', '581.0', 'Nephrotic syndrome with lesion of proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '581.1', 'Nephrotic syndrome with lesion of membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '581.2', 'Nephrotic syndrome with lesion of membranoproliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '581.3', 'Nephrotic syndrome with lesion of minimal change glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '581.81', 'Nephrotic syndrome in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-9-cm', '581.89', 'Nephrotic syndrome with other specified pathological lesion in kidney')
,('http://hl7.org/fhir/sid/icd-9-cm', '581.9', 'Nephrotic syndrome with unspecified pathological lesion in kidney')
,('http://hl7.org/fhir/sid/icd-9-cm', '582.0', 'Chronic glomerulonephritis with lesion of proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '582.1', 'Chronic glomerulonephritis with lesion of membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '582.2', 'Chronic glomerulonephritis with lesion of membranoproliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '582.4', 'Chronic glomerulonephritis with lesion of rapidly progressive glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '582.81', 'Chronic glomerulonephritis in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-9-cm', '582.89', 'Chronic glomerulonephritis with other specified pathological lesion in kidney')
,('http://hl7.org/fhir/sid/icd-9-cm', '582.9', 'Chronic glomerulonephritis with unspecified pathological lesion in kidney')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.0', 'Nephritis and nephropathy, not specified as acute or chronic, with lesion of proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.1', 'Nephritis and nephropathy, not specified as acute or chronic, with lesion of membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.2', 'Nephritis and nephropathy, not specified as acute or chronic, with lesion of membranoproliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.4', 'Nephritis and nephropathy, not specified as acute or chronic, with lesion of rapidly progressive glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.6', 'Nephritis and nephropathy, not specified as acute or chronic, with lesion of renal cortical necrosis')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.7', 'Nephritis and nephropathy, not specified as acute or chronic, with lesion of renal medullary necrosis')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.81', 'Nephritis and nephropathy, not specified as acute or chronic, in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.89', 'Nephritis and nephropathy, not specified as acute or chronic, with other specified pathological lesion in kidney')
,('http://hl7.org/fhir/sid/icd-9-cm', '583.9', 'Nephritis and nephropathy, not specified as acute or chronic, with unspecified pathological lesion in kidney')
,('http://snomed.info/sct', '58574008', 'Acute nephropathy (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '588.0', 'Renal osteodystrophy')
,('http://hl7.org/fhir/sid/icd-9-cm', '588.1', 'Nephrogenic diabetes insipidus')
,('http://hl7.org/fhir/sid/icd-9-cm', '588.81', 'Secondary hyperparathyroidism (of renal origin)')
,('http://hl7.org/fhir/sid/icd-9-cm', '588.89', 'Other specified disorders resulting from impaired renal function')
,('http://hl7.org/fhir/sid/icd-9-cm', '588.9', 'Unspecified disorder resulting from impaired renal function')
,('http://snomed.info/sct', '59400006', 'Analgesic nephropathy (disorder)')
,('http://snomed.info/sct', '60926001', 'Chronic tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '61503006', 'Acute nephritis (disorder)')
,('http://snomed.info/sct', '62240004', 'Benign arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '62332007', 'Infantile nephropathic cystinosis (disorder)')
,('http://snomed.info/sct', '62853008', 'Anti-glomerular basement membrane tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '64168005', 'Idiopathic crescentic glomerulonephritis, type I (disorder)')
,('http://snomed.info/sct', '64212008', 'Diffuse crescentic glomerulonephritis (disorder)')
,('http://snomed.info/sct', '68544003', 'Acute glomerulonephritis due to and following streptococcal infection (disorder)')
,('http://snomed.info/sct', '68779003', 'Primary immunoglobulin A nephropathy (disorder)')
,('http://snomed.info/sct', '700107006', 'Bartter syndrome antenatal type 1 (disorder)')
,('http://snomed.info/sct', '700111000', 'Bartter syndrome type 3 (disorder)')
,('http://snomed.info/sct', '700112007', 'Bartter syndrome type 4 (disorder)')
,('http://snomed.info/sct', '702718005', 'Acute on chronic tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '707742001', 'Bartter syndrome (disorder)')
,('http://snomed.info/sct', '707756004', 'Gitelman syndrome (disorder)')
,('http://snomed.info/sct', '71441000119104', 'Nephrotic syndrome due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71721000119101', 'Nephrotic syndrome due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '717760006', 'Multi-drug resistant nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '717766000', 'Alport syndrome autosomal dominant (disorder)')
,('http://snomed.info/sct', '717767009', 'Alport syndrome autosomal recessive (disorder)')
,('http://snomed.info/sct', '717768004', 'Alport syndrome X-linked (disorder)')
,('http://snomed.info/sct', '717791000', 'Bartter syndrome type 4a (disorder)')
,('http://snomed.info/sct', '719839000', 'Tubular renal disease with cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '720982007', 'Alport syndrome, intellectual disability, midface hypoplasia, elliptocytosis syndrome (disorder)')
,('http://snomed.info/sct', '721175003', 'Idiopathic glomerular disease (disorder)')
,('http://snomed.info/sct', '721207002', 'Seizure, sensorineural deafness, ataxia, intellectual disability, electrolyte imbalance syndrome (disorder)')
,('http://snomed.info/sct', '721297008', 'Galloway Mowat syndrome (disorder)')
,('http://snomed.info/sct', '721840000', 'Hyperuricemia, anemia, renal failure syndrome (disorder)')
,('http://snomed.info/sct', '722086002', 'Membranous glomerulonephritis due to malignant neoplastic disease (disorder)')
,('http://snomed.info/sct', '722118005', 'Congenital nephrotic syndrome due to congenital infection (disorder)')
,('http://snomed.info/sct', '722119002', 'Idiopathic membranous glomerulonephritis (disorder)')
,('http://snomed.info/sct', '722120008', 'Membranous glomerulonephritis caused by drug (disorder)')
,('http://snomed.info/sct', '722139003', 'Focal segmental glomerulosclerosis caused by lithium (disorder)')
,('http://snomed.info/sct', '722147003', 'Focal segmental glomerulosclerosis due to sickle cell disease (disorder)')
,('http://snomed.info/sct', '722168002', 'Membranous glomerulonephritis co-occurrent with infectious disease (disorder)')
,('http://snomed.info/sct', '722294004', 'Autosomal dominant intermediate Charcot-Marie-Tooth disease type E (disorder)')
,('http://snomed.info/sct', '722369003', 'Congenital nephrotic syndrome due to diffuse mesangial sclerosis (disorder)')
,('http://snomed.info/sct', '722381004', 'Congenital cataract, nephropathy, encephalopathy syndrome (disorder)')
,('http://snomed.info/sct', '722468005', 'Distal renal tubular acidosis co-occurrent with sensorineural deafness (disorder)')
,('http://snomed.info/sct', '722758004', 'Complement component 3 glomerulopathy (disorder)')
,('http://snomed.info/sct', '722759007', 'Glomerulopathy with fibronectin deposits 2 (disorder)')
,('http://snomed.info/sct', '722760002', 'Dense deposit disease (disorder)')
,('http://snomed.info/sct', '722761003', 'Complement component 3 glomerulonephritis (disorder)')
,('http://snomed.info/sct', '722948009', 'Glomerular disorder due to non-neuropathic heredofamilial amyloidosis (disorder)')
,('http://snomed.info/sct', '723074006', 'Renal papillary necrosis due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '724099000', 'Acquired monoclonal immunoglobulin light chain-associated Fanconi syndrome (disorder)')
,('http://snomed.info/sct', '725592009', 'Congenital membranous nephropathy due to maternal anti-neutral endopeptidase alloimmunization (disorder)')
,('http://snomed.info/sct', '726082003', 'Immunotactoid glomerulonephritis (disorder)')
,('http://snomed.info/sct', '726541005', 'Acute kidney injury due to trauma (disorder)')
,('http://snomed.info/sct', '73305009', 'Fibrillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '733453005', 'Congenital nephrotic syndrome, interstitial lung disease, epidermolysis bullosa syndrome (disorder)')
,('http://snomed.info/sct', '75888001', 'Mesangiocapillary glomerulonephritis, type I (disorder)')
,('http://snomed.info/sct', '766249007', 'Deafness, nephritis, anorectal malformation syndrome (disorder)')
,('http://snomed.info/sct', '7703001', 'Renal tubular defect (disorder)')
,('http://snomed.info/sct', '770414008', 'Alport syndrome (disorder)')
,('http://snomed.info/sct', '771447009', 'Laminin subunit beta 2 related infantile-onset nephrotic syndrome (disorder)')
,('http://snomed.info/sct', '77182004', 'Membranous glomerulonephritis (disorder)')
,('http://snomed.info/sct', '7724006', 'Nephritic syndrome (disorder)')
,('http://snomed.info/sct', '773647007', 'Nephrotic syndrome, deafness, pretibial epidermolysis bullosa syndrome (disorder)')
,('http://snomed.info/sct', '776416004', 'Hyperuricemia, pulmonary hypertension, renal failure, alkalosis syndrome (disorder)')
,('http://snomed.info/sct', '782738008', 'Karyomegalic interstitial nephritis (disorder)')
,('http://snomed.info/sct', '782771007', 'Mitochondrial deoxyribonucleic acid depletion syndrome hepatocerebrorenal form (disorder)')
,('http://snomed.info/sct', '783614008', 'Familial steroid-resistant nephrotic syndrome with sensorineural deafness (disorder)')
,('http://snomed.info/sct', '783620009', 'Dominant hypophosphatemia with nephrolithiasis and/or osteoporosis (disorder)')
,('http://snomed.info/sct', '783787000', 'Retinal vasculopathy with cerebral leukoencephalopathy and systemic manifestations (disorder)')
,('http://snomed.info/sct', '78815005', 'Hereditary tubulointerstitial disorder (disorder)')
,('http://snomed.info/sct', '788613004', 'Anti-glomerular basement membrane disease (disorder)')
,('http://snomed.info/sct', '792926007', 'Armanni-Ebstein kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '79385002', 'Lowe syndrome (disorder)')
,('http://snomed.info/sct', '80321008', 'Mesangiocapillary glomerulonephritis (disorder)')
,('http://snomed.info/sct', '81363003', 'Malignant arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '81475007', 'Acquired vasopressin resistance (disorder)')
,('http://snomed.info/sct', '818952002', 'Fibronectin glomerulopathy (disorder)')
,('http://snomed.info/sct', '8199003', 'Focal embolic nephritis syndrome (disorder)')
,('http://snomed.info/sct', '82112005', 'Idiopathic chronic tubulointerstitial nephritis (disorder)')
,('http://snomed.info/sct', '829971006', 'Non-amyloid monoclonal immunoglobulin deposition disease (disorder)')
,('http://snomed.info/sct', '838353009', 'Acute pyelonephritis caused by bacterium (disorder)')
,('http://snomed.info/sct', '83866005', 'Focal AND segmental proliferative glomerulonephritis (disorder)')
,('http://snomed.info/sct', '83923004', 'Familial interstitial nephritis (disorder)')
,('http://snomed.info/sct', '860892003', 'Glomerular disease due to infectious disease (disorder)')
,('http://snomed.info/sct', '860893008', 'Glomerular disease due to parasitic disease (disorder)')
,('http://snomed.info/sct', '90493000', 'Arteriolar nephrosclerosis (disorder)')
,('http://snomed.info/sct', '90781000119102', 'Microalbuminuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90971000119103', 'Glomerulonephritis co-occurrent and due to vasculitis (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.0', 'Acute nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.1', 'Acute nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.2', 'Acute nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.3', 'Acute nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.4', 'Acute nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.5', 'Acute nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.6', 'Acute nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.7', 'Acute nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.8', 'Acute nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.9', 'Acute nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N00.A', 'Acute nephritic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.0', 'Rapidly progressive nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.1', 'Rapidly progressive nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.2', 'Rapidly progressive nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.3', 'Rapidly progressive nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.4', 'Rapidly progressive nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.5', 'Rapidly progressive nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.6', 'Rapidly progressive nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.7', 'Rapidly progressive nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.8', 'Rapidly progressive nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.9', 'Rapidly progressive nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N01.A', 'Rapidly progressive nephritic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.0', 'Recurrent and persistent hematuria with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.1', 'Recurrent and persistent hematuria with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.2', 'Recurrent and persistent hematuria with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.3', 'Recurrent and persistent hematuria with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.4', 'Recurrent and persistent hematuria with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.5', 'Recurrent and persistent hematuria with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.6', 'Recurrent and persistent hematuria with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.7', 'Recurrent and persistent hematuria with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.8', 'Recurrent and persistent hematuria with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.9', 'Recurrent and persistent hematuria with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N02.A', 'Recurrent and persistent hematuria with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.0', 'Chronic nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.1', 'Chronic nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.2', 'Chronic nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.3', 'Chronic nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.4', 'Chronic nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.5', 'Chronic nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.6', 'Chronic nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.7', 'Chronic nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.8', 'Chronic nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.9', 'Chronic nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N03.A', 'Chronic nephritic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.0', 'Nephrotic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.1', 'Nephrotic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.2', 'Nephrotic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.3', 'Nephrotic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.4', 'Nephrotic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.5', 'Nephrotic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.6', 'Nephrotic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.7', 'Nephrotic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.8', 'Nephrotic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.9', 'Nephrotic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N04.A', 'Nephrotic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.0', 'Unspecified nephritic syndrome with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.1', 'Unspecified nephritic syndrome with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.2', 'Unspecified nephritic syndrome with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.3', 'Unspecified nephritic syndrome with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.4', 'Unspecified nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.5', 'Unspecified nephritic syndrome with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.6', 'Unspecified nephritic syndrome with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.7', 'Unspecified nephritic syndrome with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.8', 'Unspecified nephritic syndrome with other morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.9', 'Unspecified nephritic syndrome with unspecified morphologic changes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N05.A', 'Unspecified nephritic syndrome with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.0', 'Isolated proteinuria with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.1', 'Isolated proteinuria with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.2', 'Isolated proteinuria with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.3', 'Isolated proteinuria with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.4', 'Isolated proteinuria with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.5', 'Isolated proteinuria with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.6', 'Isolated proteinuria with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.7', 'Isolated proteinuria with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.8', 'Isolated proteinuria with other morphologic lesion')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.9', 'Isolated proteinuria with unspecified morphologic lesion')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N06.A', 'Isolated proteinuria with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.0', 'Hereditary nephropathy, not elsewhere classified with minor glomerular abnormality')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.1', 'Hereditary nephropathy, not elsewhere classified with focal and segmental glomerular lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.2', 'Hereditary nephropathy, not elsewhere classified with diffuse membranous glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.3', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangial proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.4', 'Hereditary nephropathy, not elsewhere classified with diffuse endocapillary proliferative glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.5', 'Hereditary nephropathy, not elsewhere classified with diffuse mesangiocapillary glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.6', 'Hereditary nephropathy, not elsewhere classified with dense deposit disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.7', 'Hereditary nephropathy, not elsewhere classified with diffuse crescentic glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.8', 'Hereditary nephropathy, not elsewhere classified with other morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.9', 'Hereditary nephropathy, not elsewhere classified with unspecified morphologic lesions')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N07.A', 'Hereditary nephropathy, not elsewhere classified with C3 glomerulonephritis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N08', 'Glomerular disorders in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.0', 'Analgesic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.1', 'Nephropathy induced by other drugs, medicaments and biological substances')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.2', 'Nephropathy induced by unspecified drug, medicament or biological substance')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.3', 'Nephropathy induced by heavy metals')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N14.4', 'Toxic nephropathy, not elsewhere classified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.0', 'Renal osteodystrophy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.1', 'Nephrogenic diabetes insipidus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.81', 'Secondary hyperparathyroidism of renal origin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.89', 'Other disorders resulting from impaired renal tubular function')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N25.9', 'Disorder resulting from impaired renal tubular function, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26.1', 'Atrophy of kidney (terminal)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26.2', 'Page kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N26.9', 'Renal sclerosis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q60.0', 'Renal agenesis, unilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q60.1', 'Renal agenesis, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q60.2', 'Renal agenesis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q60.3', 'Renal hypoplasia, unilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q60.4', 'Renal hypoplasia, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q60.5', 'Renal hypoplasia, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q60.6', 'Potters syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.00', 'Congenital renal cyst, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.01', 'Congenital single renal cyst')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.02', 'Congenital multiple renal cysts')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.11', 'Cystic dilatation of collecting ducts')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.19', 'Other polycystic kidney, infantile type')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.2', 'Polycystic kidney, adult type')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.3', 'Polycystic kidney, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.4', 'Renal dysplasia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.5', 'Medullary cystic kidney')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.8', 'Other cystic kidney diseases')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q61.9', 'Cystic kidney disease, unspecified')
) AS t (system, code, display) ;