create or replace view irae__rx_tacrolimus as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '284521', 'Protopic 0.03 % Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431978', 'Tacrolimus 0.5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431988', 'Tacrolimus 5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431981', 'Tacrolimus 1 MG [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431985', 'Tacrolimus 5 MG 24HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431971', 'Tacrolimus 0.5 MG 24HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '331550', 'Tacrolimus 0.0003 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664459', 'Tacrolimus 0.75 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664464', 'Tacrolimus 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664465', 'Envarsus 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235241', 'Tacrolimus 0.5 MG Oral Capsule [Hecoria]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484288', 'Tacrolimus monohydrate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164202', 'Tacrolimus Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313189', 'Tacrolimus 0.03 % Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052605', 'Tacrolimus 0.2 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052608', 'Prograf Granule Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574378', 'Tacrolimus 0.5 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '235991', 'anhydrous Tacrolimus')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431982', '24 HR Tacrolimus 1 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431977', '24 HR Tacrolimus 0.5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431973', 'Tacrolimus 0.5 MG [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431980', 'Tacrolimus 1 MG 24HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665161', 'BX Rating Tacrolimus 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '330404', 'Tacrolimus 0.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '331549', 'Tacrolimus 0.001 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664433', 'Tacrolimus Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664436', 'Tacrolimus 4 MG [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664442', 'Envarsus 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163655', 'Tacrolimus Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235243', 'Tacrolimus 1 MG Oral Capsule [Hecoria]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235244', 'Tacrolimus 5 MG [Hecoria]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '427807', 'Tacrolimus 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '427808', 'Tacrolimus 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180663', 'Prograf Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052503', 'Tacrolimus 0.2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052604', 'Tacrolimus Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052606', 'Tacrolimus 0.2 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052609', 'Prograf 0.2 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052703', 'Tacrolimus 1 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564559', 'Tacrolimus 5 MG/ML [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198378', 'Tacrolimus 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '42316', 'Tacrolimus')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664456', 'Tacrolimus 0.75 MG 24HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664461', 'Tacrolimus 1 MG 24HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284520', 'Protopic 0.1 % Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284848', 'Protopic')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '451875', 'Tacrolimus Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431989', 'Tacrolimus 5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431979', 'Tacrolimus 0.5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431987', '24 HR Tacrolimus 5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431984', 'Tacrolimus 1 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431986', 'Tacrolimus 5 MG [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431970', 'Tacrolimus Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738334', 'Tacrolimus Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664435', 'Envarsus')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664439', 'Envarsus Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664441', 'Tacrolimus 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664455', 'Tacrolimus 0.75 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664457', 'Tacrolimus 0.75 MG [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664463', '24 HR Envarsus 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180664', 'Prograf Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052603', 'Tacrolimus Granule Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052607', 'Tacrolimus Granules for Oral Suspension [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564557', 'Tacrolimus 1 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564558', 'Tacrolimus 5 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366273', 'Tacrolimus Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198377', 'Tacrolimus 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664434', 'Tacrolimus 4 MG 24HR Extended Release Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738339', 'Prograf 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314266', 'Tacrolimus 0.1 % Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164204', 'Tacrolimus Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431974', 'Tacrolimus Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431983', 'Tacrolimus 1 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665162', 'BX Rating Tacrolimus 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665163', 'BX Rating Tacrolimus 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664432', 'Tacrolimus 4 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664437', 'Tacrolimus Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664438', 'Envarsus Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664440', '24 HR Envarsus 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664460', 'Envarsus 0.75 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664462', 'Tacrolimus 1 MG [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317510', 'Tacrolimus 5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '379082', 'Tacrolimus Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '196463', 'Prograf')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164203', 'Tacrolimus Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235237', 'Tacrolimus 0.5 MG [Hecoria]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235238', 'Tacrolimus Oral Capsule [Hecoria]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235242', 'Tacrolimus 1 MG [Hecoria]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1235245', 'Tacrolimus 5 MG Oral Capsule [Hecoria]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108513', 'Prograf 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108514', 'Prograf 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108515', 'Prograf 5 MG in 1 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180662', 'Prograf Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182458', 'Protopic Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261134', 'Prograf 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313190', 'Tacrolimus 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052704', 'Prograf 1 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574948', 'Tacrolimus 0.001 MG/MG [Protopic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574949', 'Tacrolimus 0.0003 MG/MG [Protopic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '367339', 'Tacrolimus Topical Ointment [Protopic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374015', 'Tacrolimus Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198379', '1 ML Tacrolimus 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664458', '24 HR Envarsus 0.75 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738336', 'Tacrolimus Injection [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738338', 'Tacrolimus 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316758', 'Tacrolimus 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316759', 'Tacrolimus 5 MG')
) AS t (system, code, display) ;