create or replace view irae__lab_cytomegalovirus as select * from (values

('http://loinc.org','100675-8','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','100676-6','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','101815-9','Cytomegalovirus (CMV), Spinal fluid'),
('http://loinc.org','101816-7','Cytomegalovirus (CMV), Urine'),
('http://loinc.org','101947-0','Cytomegalovirus (CMV), Respiratory system specimen'),
('http://loinc.org','101948-8','Cytomegalovirus (CMV), Stool'),
('http://loinc.org','102088-2','Torch Ab.IgG panel, Blood'),
('http://loinc.org','10391-1','Volume of Cytomegalovirus (CMV) Immune Globulin given'),
('http://loinc.org','104760-4','Cytomegalovirus (CMV), Specimen'),
('http://loinc.org','105739-7','Cytomegalovirus (CMV), Pericardial fluid'),
('http://loinc.org','105879-1','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','105880-9','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','106028-4','Cytomegalovirus (CMV), Genital specimen'),
('http://loinc.org','10660-9','Cytomegalovirus (CMV) antigen, Tissue'),
('http://loinc.org','11008-0','Cytomegalovirus (CMV) IgG antibody, Spinal fluid'),
('http://loinc.org','13225-8','Cytomegalovirus (CMV) IgG antibody specimen 1, Blood'),
('http://loinc.org','13226-6','Cytomegalovirus (CMV) IgM antibody, Spinal fluid'),
('http://loinc.org','13949-3','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','15377-5','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','16712-2','Cytomegalovirus (CMV) antibody, Body fluid'),
('http://loinc.org','16713-0','Cytomegalovirus (CMV) antibody, Spinal fluid'),
('http://loinc.org','16714-8','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','16715-5','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','16716-3','Cytomegalovirus (CMV) IgG antibody specimen 2, Blood'),
('http://loinc.org','16717-1','Cytomegalovirus (CMV) antigen, Urine'),
('http://loinc.org','16718-9','Cytomegalovirus (CMV) antigen, Blood'),
('http://loinc.org','16719-7','Cytomegalovirus (CMV) Inclusion Bodies, Urine'),
('http://loinc.org','20475-0','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','21237-3','Cytomegalovirus (CMV) IgM antibody, Spinal fluid'),
('http://loinc.org','22239-8','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','22240-6','Cytomegalovirus (CMV) antibody, Spinal fluid'),
('http://loinc.org','22241-4','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','22242-2','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','22243-0','Cytomegalovirus (CMV) IgG antibody, Spinal fluid'),
('http://loinc.org','22244-8','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','22245-5','Cytomegalovirus (CMV) IgG antibody, Spinal fluid'),
('http://loinc.org','22246-3','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','22247-1','Cytomegalovirus (CMV) IgG antibody specimen 2, Blood'),
('http://loinc.org','22248-9','Cytomegalovirus (CMV) IgM antibody, Spinal fluid'),
('http://loinc.org','22249-7','Cytomegalovirus (CMV) IgM antibody, Blood'),
('http://loinc.org','24041-6','Cytomegalovirus (CMV), Specimen'),
('http://loinc.org','24119-0','Cytomegalovirus (CMV) IgM antibody, Blood'),
('http://loinc.org','24314-7','TORCH 1996 panel, Blood'),
('http://loinc.org','24315-4','Cytomegalovirus (CMV) IgG and IgM Panel, Blood'),
('http://loinc.org','28008-1','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','29590-7','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','29604-6','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','30246-3','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','30247-1','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','30325-5','Cytomegalovirus (CMV) IgM antibody, Blood'),
('http://loinc.org','30326-3','Cytomegalovirus (CMV), Spinal fluid'),
('http://loinc.org','31795-8','Cytomegalovirus (CMV) antigen, Blood'),
('http://loinc.org','31796-6','Cytomegalovirus (CMV) antigen, Urine'),
('http://loinc.org','31797-4','Cytomegalovirus (CMV) antigen, Specimen'),
('http://loinc.org','32170-3','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','32675-1','Cytomegalovirus (CMV) culture, Bronchial specimen'),
('http://loinc.org','32791-6','Cytomegalovirus (CMV) IgG antibody 1st specimen/2nd specimen, Blood'),
('http://loinc.org','32835-1','Cytomegalovirus (CMV) IgG antibody 1st specimen/2nd specimen, Blood'),
('http://loinc.org','33006-8','Cytomegalovirus (CMV), Specimen'),
('http://loinc.org','33285-8','Cytomegalovirus (CMV) IgM antibody, Body fluid'),
('http://loinc.org','33616-4','Cytomegalovirus (CMV) Early antigen, Urine'),
('http://loinc.org','33631-3','Cytomegalovirus (CMV) UL54 gene variant analysis'),
('http://loinc.org','33632-1','Cytomegalovirus (CMV) UL54+UL97 gene variant analysis'),
('http://loinc.org','34201-4','Cytomegalovirus (CMV) culture, Amniotic fluid'),
('http://loinc.org','34403-6','Cytomegalovirus (CMV) Ab avidity, Blood'),
('http://loinc.org','34665-0','TORCH panel, Spinal fluid'),
('http://loinc.org','34719-5','Cytomegalovirus (CMV), Amniotic fluid'),
('http://loinc.org','34720-3','Cytomegalovirus (CMV), Specimen'),
('http://loinc.org','34944-9','Cytomegalovirus (CMV) IgG and IgM Panel, Spinal fluid'),
('http://loinc.org','35401-9','Cytomegalovirus (CMV), Bronchial specimen'),
('http://loinc.org','39003-9','Cytomegalovirus (CMV), Spinal fluid'),
('http://loinc.org','40444-2','Cytomegalovirus (CMV) Gene variant analysis'),
('http://loinc.org','41155-3','Cytomegalovirus (CMV) IgM antibody, Body fluid'),
('http://loinc.org','42336-8','Cytomegalovirus (CMV) antigen, Specimen'),
('http://loinc.org','42495-2','Cytomegalovirus (CMV) IgG antibody, Spinal fluid'),
('http://loinc.org','42899-5','Cytomegalovirus (CMV) IgM antibody, Spinal fluid'),
('http://loinc.org','43045-4','Cytomegalovirus (CMV) IgM antibody, Spinal fluid'),
('http://loinc.org','43700-4','Cytomegalovirus (CMV) culture, Urine'),
('http://loinc.org','43701-2','Cytomegalovirus (CMV) culture, Specimen'),
('http://loinc.org','43702-0','Cytomegalovirus (CMV) culture, Spinal fluid'),
('http://loinc.org','43703-8','Cytomegalovirus (CMV) culture, Blood'),
('http://loinc.org','43704-6','Cytomegalovirus (CMV) culture, Body fluid'),
('http://loinc.org','43705-3','Cytomegalovirus (CMV) culture, Bone marrow'),
('http://loinc.org','43706-1','Cytomegalovirus (CMV) culture, Anal'),
('http://loinc.org','43707-9','Cytomegalovirus (CMV) culture, Tissue'),
('http://loinc.org','44817-5','Cytomegalovirus (CMV) IgM antibody, Spinal fluid'),
('http://loinc.org','45286-2','Cytomegalovirus (CMV) IgA antibody, Body fluid'),
('http://loinc.org','45326-6','Cytomegalovirus (CMV) IgG avidity, Blood'),
('http://loinc.org','47307-4','Cytomegalovirus (CMV) IgG index, Serum+Cerebrospinal fluid'),
('http://loinc.org','47363-7','Cytomegalovirus (CMV) antibody, Donor Blood'),
('http://loinc.org','47430-4','Cytomegalovirus (CMV) antibody, Donor Blood'),
('http://loinc.org','49347-8','Cytomegalovirus (CMV), Urine'),
('http://loinc.org','49348-6','Cytomegalovirus (CMV), Amniotic fluid'),
('http://loinc.org','49349-4','Cytomegalovirus (CMV), Bronchoalveolar lavage specimen'),
('http://loinc.org','49350-2','Cytomegalovirus (CMV), Bone marrow'),
('http://loinc.org','49351-0','Cytomegalovirus (CMV), Tissue'),
('http://loinc.org','49539-0','Cytomegalovirus (CMV) IgM antibody, Blood'),
('http://loinc.org','4996-5','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','4997-3','Cytomegalovirus (CMV), Tissue'),
('http://loinc.org','4998-1','Cytomegalovirus (CMV), Tissue'),
('http://loinc.org','4999-9','Cytomegalovirus (CMV), Urine'),
('http://loinc.org','5000-5','Cytomegalovirus (CMV), Specimen'),
('http://loinc.org','50018-1','Cytomegalovirus (CMV) IgG antibody, Body fluid'),
('http://loinc.org','50549-5','CMV+Epstein Barr virus, Specimen'),
('http://loinc.org','5121-9','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','5122-7','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','5123-5','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','5124-3','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','5125-0','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','5126-8','Cytomegalovirus (CMV) IgM antibody, Blood'),
('http://loinc.org','5127-6','Cytomegalovirus (CMV) IgM antibody, Blood'),
('http://loinc.org','52976-8','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','52984-2','Cytomegalovirus (CMV) IgG avidity, Blood'),
('http://loinc.org','53763-9','Cytomegalovirus (CMV), Specimen'),
('http://loinc.org','54061-7','HEDIS 2009-2011 Tests Used in Early Prenatal Care - Cytomegalovirus (PPC-C)'),
('http://loinc.org','54163-1','Cytomegalovirus (CMV), Urine'),
('http://loinc.org','54164-9','Cytomegalovirus (CMV) Immediate-early antigen, Blood'),
('http://loinc.org','54206-8','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','5835-4','Cytomegalovirus (CMV) culture, Blood'),
('http://loinc.org','5836-2','Cytomegalovirus (CMV) culture, Tissue'),
('http://loinc.org','5837-0','Cytomegalovirus (CMV) culture, Urine'),
('http://loinc.org','5838-8','Cytomegalovirus (CMV) culture, Specimen'),
('http://loinc.org','59838-3','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','60541-0','Cytomegalovirus (CMV) Early antigen, Specimen'),
('http://loinc.org','6375-0','Cytomegalovirus (CMV) antigen, Blood'),
('http://loinc.org','6376-8','Cytomegalovirus (CMV) antigen, Blood'),
('http://loinc.org','6377-6','Cytomegalovirus (CMV) antigen, Blood'),
('http://loinc.org','6378-4','Cytomegalovirus (CMV) antigen, Urine'),
('http://loinc.org','6379-2','Cytomegalovirus (CMV) antigen, Specimen'),
('http://loinc.org','6380-0','Cytomegalovirus (CMV) antigen, Specimen'),
('http://loinc.org','6381-8','Cytomegalovirus (CMV) antigen, Specimen'),
('http://loinc.org','67769-0','HEDIS 2012, 2013 Tests Used in Early Prenatal Care - Cytomegalovirus (PPC-C)'),
('http://loinc.org','67805-2','Cytomegalovirus (CMV) antigen'),
('http://loinc.org','6921-1','Cytomegalovirus (CMV) IgG antibody, Spinal fluid'),
('http://loinc.org','72493-0','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','72494-8','Cytomegalovirus (CMV), Blood'),
('http://loinc.org','72605-9','Cytomegalovirus (CMV) Glycoprotein genotype, Specimen'),
('http://loinc.org','72833-7','Cytomegalovirus (CMV) UL97 gene variant analysis'),
('http://loinc.org','72852-7','Cytomegalovirus (CMV) Resistance Panel'),
('http://loinc.org','74242-9','HEDIS 2014-2016 Value Set - Cytomegalovirus Antibody'),
('http://loinc.org','77388-7','Cytomegalovirus (CMV) antigen, Bronchoalveolar lavage specimen'),
('http://loinc.org','78001-5','Cytomegalovirus (CMV) pp65 per 100000 PMN Cells, Blood'),
('http://loinc.org','78445-4','Cytomegalovirus (CMV) IgG avidity, Blood'),
('http://loinc.org','7851-9','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','7852-7','Cytomegalovirus (CMV) IgG antibody, Blood'),
('http://loinc.org','7853-5','Cytomegalovirus (CMV) IgM antibody, Blood'),
('http://loinc.org','81328-7','Cytomegalovirus (CMV) culture, Lower respiratory'),
('http://loinc.org','82189-2','Cytomegalovirus (CMV), Spinal fluid'),
('http://loinc.org','82958-0','HEDIS 2017, 2018 Value Set - Cytomegalovirus Antibody'),
('http://loinc.org','83065-3','Cytomegalovirus (CMV), Saliva'),
('http://loinc.org','86517-0','Cytomegalovirus (CMV) antigen, Tissue'),
('http://loinc.org','87382-8','Porcine cytomegalovirus, Specimen'),
('http://loinc.org','87424-8','Cytomegalovirus (CMV) IgG and IgM Panel, Blood'),
('http://loinc.org','87725-8','Cytomegalovirus (CMV) IgM antibody, Donor Blood'),
('http://loinc.org','87726-6','Cytomegalovirus (CMV) IgG antibody, Donor Blood'),
('http://loinc.org','88130-0','Cytomegalovirus (CMV), Eye fluid'),
('http://loinc.org','88131-8','Cytomegalovirus (CMV), Eye fluid'),
('http://loinc.org','88535-0','Cytomegalovirus (CMV), Dried blood spot'),
('http://loinc.org','88545-9','Cytomegalovirus (CMV), Dried blood spot'),
('http://loinc.org','88558-2','Cytomegalovirus (CMV), Lower respiratory'),
('http://loinc.org','88564-0','Cytomegalovirus (CMV) culture, Bone marrow'),
('http://loinc.org','88566-5','Cytomegalovirus (CMV) antigen, Bone marrow'),
('http://loinc.org','88567-3','Cytomegalovirus (CMV), Bone marrow'),
('http://loinc.org','88622-6','Cytomegalovirus (CMV) culture, Eye fluid'),
('http://loinc.org','88623-4','Cytomegalovirus (CMV) culture, Spinal fluid'),
('http://loinc.org','88624-2','Cytomegalovirus (CMV) culture, Amniotic fluid'),
('http://loinc.org','88625-9','Cytomegalovirus (CMV) culture, Eye fluid'),
('http://loinc.org','89583-9','Cytomegalovirus (CMV) antigen, Spinal fluid'),
('http://loinc.org','90777-4','HEDIS 2019 Value Set - Cytomegalovirus Antibody'),
('http://loinc.org','91783-1','Cytomegalovirus (CMV) culture, Lower respiratory'),
('http://loinc.org','93753-2','Porcine cytomegalovirus, Specimen'),
('http://loinc.org','94823-2','Cytomegalovirus (CMV), Amniotic fluid'),
('http://loinc.org','9513-3','Cytomegalovirus (CMV) antibody, Blood'),
('http://loinc.org','95136-8','Cytomegalovirus DNA Panel, Amniotic fluid'),
('http://loinc.org','9514-1','Cytomegalovirus (CMV) antibody, Spinal fluid'),
('http://loinc.org','95184-8','Cytomegalovirus t-cell immunodeficiency panel, Blood'),
('http://loinc.org','95527-8','Cytomegalovirus (CMV) IgG antibody, Saliva'),
('http://loinc.org','96396-7','Cytomegalovirus (CMV), Specimen'),
('http://loinc.org','98081-3','Cytomegalovirus (CMV), Saliva')
) AS t (system,code,display) ;