create or replace view irae__dx_diabetes_pre as select * from (values
('http://snomed.info/sct', '128264007', 'Impaired glucose tolerance with hyperinsulism (disorder)')
,('http://snomed.info/sct', '1310004', 'Impaired glucose tolerance associated with genetic syndrome (disorder)')
,('http://snomed.info/sct', '14052004', 'Impaired glucose tolerance in and individual with a heritable form of maturity onset diabetes in the young (disorder)')
,('http://snomed.info/sct', '1822007', 'Impaired glucose tolerance associated with pancreatic disease (disorder)')
,('http://snomed.info/sct', '22910008', 'Impaired glucose tolerance in obese (disorder)')
,('http://snomed.info/sct', '237628005', 'Impaired glucose tolerance in pregnancy (disorder)')
,('http://snomed.info/sct', '26254008', 'Potential abnormality of glucose tolerance (disorder)')
,('http://snomed.info/sct', '2725003', 'Previous abnormality of glucose tolerance (disorder)')
,('http://snomed.info/sct', '32284009', 'Impaired glucose tolerance in nonobese (disorder)')
,('http://snomed.info/sct', '33669002', 'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class D (disorder)')
,('http://snomed.info/sct', '34818008', 'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class B (disorder)')
,('http://snomed.info/sct', '38063000', 'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class C (disorder)')
,('http://snomed.info/sct', '4307007', 'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class F (disorder)')
,('http://snomed.info/sct', '60634005', 'Impaired glucose tolerance associated with drugs (disorder)')
,('http://snomed.info/sct', '721121000124104', 'Diabetes mellitus type 1 stage 2 (disorder)')
,('http://snomed.info/sct', '721201000124104', 'Diabetes mellitus type 1 stage 3 (disorder)')
,('http://snomed.info/sct', '73480000', 'Impaired glucose tolerance associated with hormonal etiology (disorder)')
,('http://snomed.info/sct', '82141001', 'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class A (disorder)')
,('http://snomed.info/sct', '82260000', 'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class R (disorder)')
,('http://snomed.info/sct', '82701004', 'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class FR (disorder)')
,('http://snomed.info/sct', '88512005', 'Impaired glucose tolerance associated with insulin receptor abnormality (disorder)')
,('http://snomed.info/sct', '9414007', 'Impaired glucose tolerance (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R73.01', 'Impaired fasting glucose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R73.02', 'Impaired glucose tolerance (oral)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R73.03', 'Prediabetes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R73.09', 'Other abnormal glucose')
) AS t (system, code, display) ;