create or replace view irae__rx_cyclosporin as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '835927', 'Cyclosporine, modified 50 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2662711', 'Cyclosporine, modified Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665979', 'Cyclosporine Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665983', 'Cyclosporine, modified 25 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665984', 'Cyclosporine, modified 50 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055021', 'Cyclosporine 0.09 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470534', 'Cyclosporine Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '486331', 'Cyclosporine 100 MG/ML [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185408', 'SandIMMUNE Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185409', 'SandIMMUNE Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590608', 'Cyclosporine 0.1 % Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835787', 'Cyclosporine, modified 100 MG [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835885', 'Cyclosporine, modified 100 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835895', 'Cyclosporine, modified 25 MG [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202816', 'SandIMMUNE')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '670177', 'Cyclosporine 50 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093176', 'Cyclosporine 0.002 MG/MG [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093177', 'Cyclosporine Ophthalmic Ointment [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197552', 'SandIMMUNE 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590612', 'Cyclosporine Ophthalmic Suspension [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657141', 'Cyclosporine, modified Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212957', 'SandIMMUNE 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732369', 'SandIMMUNE 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732364', 'Cyclosporine Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835926', 'Cyclosporine, modified 50 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '539499', 'Cyclosporine Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835916', 'Cyclosporine, modified 100 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572889', 'Cyclosporine 25 MG [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572895', 'Cyclosporine 50 MG [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572915', 'Cyclosporine 50 MG/ML [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371666', 'Cyclosporine Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '583288', 'Cyclosporine 100 MG [Cyslosporine]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169824', 'Gengraf Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639936', 'Cyclosporine 0.1 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639941', 'Cyclosporine 1 MG/ML Ophthalmic Solution [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835835', 'GENGRAF 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309632', 'Cyclosporine 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315751', 'Cyclosporine 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665976', 'Cyclosporine, modified 100 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665985', 'Cyclosporine, modified 50 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '334294', 'Cyclosporine, modified 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055020', 'Cyclosporine Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055022', 'Cequa')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055026', 'Cequa 0.09 % Ophthalmic Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363942', 'Cyclosporine Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '364418', 'Cyclosporine Oral Solution [Sangcya]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156188', 'Cyclosporine Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185410', 'SandIMMUNE Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835887', 'Cyclosporine, modified 100 MG/ML [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835897', 'Cyclosporine, modified 100 MG/ML [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835918', 'Cyclosporine, modified 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835925', 'Cyclosporine, modified 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2645340', 'Cyclosporine, modified Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '3008', 'Cyclosporine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '353400', 'Cyclosporine 0.5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '583290', 'Cyclosporine 100 MG Oral Capsule [Cyslosporine]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '378766', 'Cyclosporine Ophthalmic Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '241834', 'Cyclosporine, modified 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657509', 'Cyclosporine, modified Oral Solution [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657747', 'Cyclosporine, modified Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212810', 'SandIMMUNE 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212958', 'Cyclosporine 100 MG/ML Oral Solution [Sangcya]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732368', 'Cyclosporine 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '565430', 'Cyclosporine 100 MG [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835920', 'Cyclosporine, modified 10 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366173', 'Cyclosporine Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371667', 'Cyclosporine Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169826', 'Gengraf Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639938', 'Cyclosporine 1 MG/ML [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315749', 'Cyclosporine 100 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315752', 'Cyclosporine 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402330', 'Cyclosporine Ophthalmic Suspension [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835923', 'Cyclosporine, modified 25 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572293', 'Restasis 0.05 % in 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205168', 'Cyclosporine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '205175', '5 ML Cyclosporine 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665980', 'Cyclosporine, modified Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '328160', 'Cyclosporine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055023', 'Cyclosporine 0.9 MG/ML [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055024', 'Cyclosporine Ophthalmic Solution [Cequa]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055025', 'Cequa Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470537', 'Cyclosporine, modified 100 MG/ML Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484788', 'Cyclosporine microemulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835911', 'Neoral 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835909', 'Neoral 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156189', 'Cyclosporine Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156190', 'Cyclosporine Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1181673', 'Neoral Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835886', 'Cyclosporine, modified 100 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835893', 'Cyclosporine, modified 25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835894', 'Cyclosporine, modified 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835900', 'Cyclosporine, modified 100 MG [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835901', 'Cyclosporine, modified 25 MG [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261530', 'Gengraf')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '202817', 'Neoral')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093172', 'Cyclosporine 0.002 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '348431', 'Cyclosporine 1000 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '402092', 'Restasis 0.05 % Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233905', 'Cyclosporine, modified 100 MG/ML [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233908', 'Cyclosporine, modified 100 MG/ML Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197553', 'Cyclosporine 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590610', 'Cyclosporine 1 MG/ML [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2656813', 'Cyclosporine, modified Oral Capsule [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2657003', 'Cyclosporine, modified Oral Solution [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2660112', 'Cyclosporine, modified Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212821', 'SandIMMUNE 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '212844', '5 ML SandIMMUNE 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732366', 'Cyclosporine Injection [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2689928', 'Cyclosporine, modified 100 MG/ML Oral Solution [Modulis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2689927', 'Cyclosporine, modified Oral Solution [Modulis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '94035', 'Cyclosporine Oral Solution [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835922', 'Cyclosporine, modified 25 MG [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '572919', 'Cyclosporine 100 MG/ML [Sangcya]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1169825', 'Gengraf Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835896', 'GENGRAF 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315753', 'Cyclosporine 50 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '358763', 'Cyclosporine 1000 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835892', 'GENGRAF 100 MG in 1 mL Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835921', 'Cyclosporine, modified 10 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835917', 'Cyclosporine, modified 100 MG Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2572292', 'Cyclosporine 0.05 % in 0.4 ML Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590607', 'Cyclosporine 1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2663521', 'Cyclosporine, modified Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665981', 'Cyclosporine, modified 100 MG Oral Capsule [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665982', 'Cyclosporine, modified 25 MG [Sporimune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2055019', 'Cyclosporine 0.9 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2470533', 'Cyclosporine, modified 100 MG/ML [Cyclavance]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '363914', 'Cyclosporine Oral Solution [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156186', 'Cyclosporine Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156187', 'Cyclosporine Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1181672', 'Neoral Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1181674', 'Neoral Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1182527', 'Restasis Ophthalmic Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1185411', 'SandIMMUNE Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835924', 'Cyclosporine, modified 50 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2647505', 'Cyclosporine, modified Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2654174', 'Cyclosporine, modified Oral Capsule [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093173', 'Cyclosporine Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093174', 'Cyclosporine 0.2 % Ophthalmic Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093178', 'Cyclosporine 0.002 MG/MG Ophthalmic Ointment [Optimmune]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351291', 'Cyclosporine 0.05 % Ophthalmic Emulsion')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '352951', 'Restasis')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '583289', 'Cyclosporine Oral Capsule [Cyslosporine]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1233906', 'Cyclosporine Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2590613', 'Cyclosporine 1 MG/ML Ophthalmic Suspension [Verkazia]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2658601', 'Cyclosporine, modified Oral Solution [Atopica]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835899', 'NEORAL 100 MG in 1 mL Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2689923', 'Cyclosporine, modified 100 MG/ML [Modulis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2689926', 'Cyclosporine Oral Solution [Modulis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '576100', 'Cyclosporine 0.5 MG/ML [Restasis]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366479', 'Cyclosporine Oral Capsule [Neoral]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366488', 'Cyclosporine Oral Capsule [SandIMMUNE]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2639940', 'Cyclosporine Ophthalmic Solution [Vevye]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1797521', 'GENGRAF 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1797520', 'Cyclosporine, modified 50 MG [Gengraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '835919', 'Cyclosporine, modified 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '236077', 'Cyclosporine, modified')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '315750', 'Cyclosporine 100 MG/ML')
) AS t (system, code, display) ;