create or replace view irae__rx_immunosuppressive_everolimus as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1119399', 'everolimus 7.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119400', 'everolimus 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119401', 'everolimus 7.5 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1119402', 'everolimus 7.5 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163786', 'everolimus Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163787', 'everolimus Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172066', 'Afinitor Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1172067', 'Afinitor Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1186316', 'Zortress Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1186317', 'Zortress Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1308426', 'everolimus Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1308428', 'everolimus 2 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1308430', 'everolimus 3 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1308432', 'everolimus 5 MG Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310137', 'Afinitor Oral Liquid Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310138', 'everolimus 2 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310144', 'everolimus 3 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1310147', 'everolimus 5 MG Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '141704', 'everolimus')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869512', 'everolimus 2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869513', 'everolimus Tablet for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869515', 'everolimus 2 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869516', 'everolimus Tablet for Oral Suspension [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869518', 'everolimus 3 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1869520', 'everolimus 3 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056894', 'everolimus 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056895', 'everolimus 1 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056896', 'everolimus 1 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2056897', 'everolimus 1 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685197', 'Torpenz')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685198', 'everolimus 2.5 MG [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685199', 'Torpenz Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685200', 'Torpenz Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685201', 'everolimus Oral Tablet [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685202', 'everolimus 2.5 MG Oral Tablet [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685203', 'everolimus 10 MG [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685204', 'everolimus 10 MG Oral Tablet [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685205', 'everolimus 5 MG [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685206', 'everolimus 5 MG Oral Tablet [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685207', 'everolimus 7.5 MG [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2685208', 'everolimus 7.5 MG Oral Tablet [Torpenz]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845505', 'everolimus 10 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845506', 'everolimus Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845507', 'everolimus 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845509', 'Afinitor')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845510', 'everolimus 10 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845511', 'everolimus Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845512', 'everolimus 10 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845514', 'everolimus 5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845515', 'everolimus 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845517', 'everolimus 5 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '845518', 'everolimus 5 MG Oral Tablet [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977426', 'everolimus 0.25 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977427', 'everolimus 0.25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977428', 'Zortress')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977429', 'everolimus 0.25 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977430', 'everolimus Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977431', 'everolimus 0.25 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977433', 'everolimus 0.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977434', 'everolimus 0.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977435', 'everolimus 0.5 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977436', 'everolimus 0.5 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977437', 'everolimus 0.75 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977438', 'everolimus 0.75 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977439', 'everolimus 0.75 MG [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '977440', 'everolimus 0.75 MG Oral Tablet [Zortress]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998188', 'everolimus 2.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998189', 'everolimus 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998190', 'everolimus 2.5 MG [Afinitor]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '998191', 'everolimus 2.5 MG Oral Tablet [Afinitor]')
) AS t (system, code, display) ;