create or replace view irae__dx_heart_cardiomyopathy as select * from (values
('http://snomed.info/sct', '103331000119103', 'Toxic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '1086051000119107', 'Cardiomyopathy due to diphtheria (disorder)')
,('http://snomed.info/sct', '108701000119102', 'Cardiomyopathy due to hypertension (disorder)')
,('http://snomed.info/sct', '111000119104', 'Nonischemic congestive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '11104006', 'Dilated cardiomyopathy due to phytanic acid storage disease (disorder)')
,('http://snomed.info/sct', '111285003', 'Dilated cardiomyopathy due to metabolic disorder (disorder)')
,('http://snomed.info/sct', '1137377003', 'Cardiomyopathy due to thyrotoxicosis (disorder)')
,('http://snomed.info/sct', '1149109001', 'Dilated cardiomyopathy due to electrolyte imbalance (disorder)')
,('http://snomed.info/sct', '1153452008', 'Dilated cardiomyopathy due to parasitic myocarditis (disorder)')
,('http://snomed.info/sct', '1172839002', 'Lethal left ventricular non-compaction, seizures, hypotonia, cataract, developmental delay syndrome (disorder)')
,('http://snomed.info/sct', '1173036000', 'Combined oxidative phosphorylation defect type 23 (disorder)')
,('http://snomed.info/sct', '1177176009', 'Intermediate epidermolysis bullosa simplex with cardiomyopathy (disorder)')
,('http://snomed.info/sct', '1179293006', 'Erythrokeratodermia cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '1186718008', 'Neonatal encephalomyopathy, cardiomyopathy, respiratory distress syndrome (disorder)')
,('http://snomed.info/sct', '1186866009', 'Cardiomyopathy due to acromegaly (disorder)')
,('http://snomed.info/sct', '1187635008', 'Maternally inherited mitochondrial cardiomyopathy (disorder)')
,('http://snomed.info/sct', '1187642008', 'Macrocephaly, intellectual disability, left ventricular non compaction syndrome (disorder)')
,('http://snomed.info/sct', '119731000146105', 'Cardiomyopathy due to disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)')
,('http://snomed.info/sct', '1197430005', 'Glutaminyl-transfer ribonucleic acid amidotransferase subunit-related combined oxidative phosphorylation defect (disorder)')
,('http://snomed.info/sct', '1204194004', 'Hypertrophic cardiomyopathy of apex of heart (disorder)')
,('http://snomed.info/sct', '1230303001', 'Fatal congenital hypertrophic cardiomyopathy due to glycogen storage disease (disorder)')
,('http://snomed.info/sct', '1234750000', 'Dilated cardiomyopathy caused by ethanol (disorder)')
,('http://snomed.info/sct', '12563008', 'Dilated cardiomyopathy caused by radiation (disorder)')
,('http://snomed.info/sct', '1264404009', 'Dilated cardiomyopathy due to scleroderma (disorder)')
,('http://snomed.info/sct', '15544002', 'Restrictive cardiomyopathy secondary to infiltrations (disorder)')
,('http://snomed.info/sct', '16228931000119102', 'Cardiomyopathy caused by drug (disorder)')
,('http://snomed.info/sct', '16253001', 'Dilated peripartum cardiomyopathy (disorder)')
,('http://snomed.info/sct', '165468981000119105', 'Toxic dilated cardiomyopathy (disorder)')
,('http://snomed.info/sct', '195020003', 'Hypertrophic cardiomyopathy without obstruction (disorder)')
,('http://snomed.info/sct', '195021004', 'Primary dilated cardiomyopathy (disorder)')
,('http://snomed.info/sct', '195025008', 'Cardiac glycogenosis (disorder)')
,('http://snomed.info/sct', '195027000', 'Cardiomyopathy due to mucopolysaccharidosis (disorder)')
,('http://snomed.info/sct', '195029002', 'Cardiomyopathy associated with another disorder (disorder)')
,('http://snomed.info/sct', '195030007', 'Cardiomyopathy in Friedreichs ataxia (disorder)')
,('http://snomed.info/sct', '195031006', 'Cardiomyopathy in myotonic dystrophy (disorder)')
,('http://snomed.info/sct', '195032004', 'Dystrophic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '204981000119101', 'Cardiomyopathy due to viral infection (disorder)')
,('http://snomed.info/sct', '20529002', 'Secondary dilated cardiomyopathy (disorder)')
,('http://snomed.info/sct', '21430002', 'Dilated cardiomyopathy due to rheumatoid arthritis (disorder)')
,('http://snomed.info/sct', '233871002', 'Congestive obstructive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '233873004', 'Hypertrophic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '233875006', 'Post-myocarditic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '233877003', 'Restrictive cardiomyopathy without endomyocardial fibrosis (disorder)')
,('http://snomed.info/sct', '233878008', 'Familial restrictive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '240077004', 'Severe scapuloperoneal muscular dystrophy with cardiomyopathy (disorder)')
,('http://snomed.info/sct', '24584003', 'Restrictive cardiomyopathy secondary to malignancy (disorder)')
,('http://snomed.info/sct', '253528005', 'Arrhythmogenic right ventricular dysplasia (disorder)')
,('http://snomed.info/sct', '27097002', 'Danish type familial amyloid cardiomyopathy (disorder)')
,('http://snomed.info/sct', '2816000', 'Dilated cardiomyopathy due to myotonic dystrophy (disorder)')
,('http://snomed.info/sct', '28869005', 'Dilated cardiomyopathy due to muscular dystrophy (disorder)')
,('http://snomed.info/sct', '30496006', 'Dilated cardiomyopathy due to viral myocarditis (disorder)')
,('http://snomed.info/sct', '30884007', 'Restrictive cardiomyopathy secondary to familial storage disease (disorder)')
,('http://snomed.info/sct', '315608004', 'Cardiomyopathy in Duchenne muscular dystrophy (disorder)')
,('http://snomed.info/sct', '33006007', 'Restrictive cardiomyopathy secondary to endocardial fibroelastosis (disorder)')
,('http://snomed.info/sct', '33258008', 'Primary eosinophilic endomyocardial restrictive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '35719004', 'Dilated cardiomyopathy due to systemic sclerosis (disorder)')
,('http://snomed.info/sct', '35728003', 'Familial cardiomyopathy (disorder)')
,('http://snomed.info/sct', '36471000', 'Dilated cardiomyopathy due to systemic lupus erythematosus (disorder)')
,('http://snomed.info/sct', '39041004', 'Restrictive cardiomyopathy secondary to sarcoidosis (disorder)')
,('http://snomed.info/sct', '39693003', 'Dilated cardiomyopathy due to granuloma (disorder)')
,('http://snomed.info/sct', '398754006', 'Restrictive cardiomyopathy with endomyocardial fibrosis (disorder)')
,('http://snomed.info/sct', '399020009', 'Congestive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '40532006', 'Dilated cardiomyopathy due to protozoan myocarditis (disorder)')
,('http://snomed.info/sct', '406428006', 'Hypertrophy of septomarginal trabeculation (disorder)')
,('http://snomed.info/sct', '413994008', 'Dilated cardiomyopathy with connective tissue disorder (disorder)')
,('http://snomed.info/sct', '413995009', 'Dilated cardiomyopathy due to taurine deficiency (disorder)')
,('http://snomed.info/sct', '415295002', 'Restrictive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '415509000', 'Secondary restrictive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '419097006', 'Glycogen storage disease due to lysosomal associated membrane protein 2 deficiency (disorder)')
,('http://snomed.info/sct', '42099002', 'Primary endomyocardial fibrosis restrictive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '426300009', 'Tachycardia-induced cardiomyopathy (disorder)')
,('http://snomed.info/sct', '426856002', 'Ischemic congestive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '441541008', 'Takotsubo cardiomyopathy (disorder)')
,('http://snomed.info/sct', '44630002', 'Dilated cardiomyopathy due to fungal myocarditis (disorder)')
,('http://snomed.info/sct', '447934002', 'Right ventricular myocardial noncompaction cardiomyopathy (disorder)')
,('http://snomed.info/sct', '447935001', 'Left ventricular myocardial noncompaction cardiomyopathy (disorder)')
,('http://snomed.info/sct', '45227007', 'Hypertrophic obstructive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '460500001', 'Histiocytoid mitochondrial cardiomyopathy due to cytochrome aa3 deficiency (disorder)')
,('http://snomed.info/sct', '46696008', 'Dilated cardiomyopathy due to dermatomyositis (disorder)')
,('http://snomed.info/sct', '46939000', 'Keshan disease (disorder)')
,('http://snomed.info/sct', '471841009', 'Inflammatory cardiomyopathy (disorder)')
,('http://snomed.info/sct', '471846004', 'Cardiomyopathy due to neuromuscular disorder (disorder)')
,('http://snomed.info/sct', '471858004', 'Valvular cardiomyopathy (disorder)')
,('http://snomed.info/sct', '471870000', 'Pacing-induced cardiomyopathy (disorder)')
,('http://snomed.info/sct', '471875005', 'Ventricular myocardial noncompaction cardiomyopathy (disorder)')
,('http://snomed.info/sct', '471885006', 'Hypertrophic cardiomyopathy with genetic marker (disorder)')
,('http://snomed.info/sct', '471890009', 'Dilated cardiomyopathy with genetic marker (disorder)')
,('http://snomed.info/sct', '472100003', 'Ischemic dilated cardiomyopathy due to coronary artery disease (disorder)')
,('http://snomed.info/sct', '472315005', 'Mitochondrial cardiomyopathy (disorder)')
,('http://snomed.info/sct', '472316006', 'Hypertrophic mitochondrial cardiomyopathy (disorder)')
,('http://snomed.info/sct', '472317002', 'Histiocytoid mitochondrial cardiomyopathy (disorder)')
,('http://snomed.info/sct', '472318007', 'Hypertrophic mitochondrial cardiomyopathy associated with cataracts and lactic acidosis (disorder)')
,('http://snomed.info/sct', '472319004', 'Fatal infantile mitochondrial cardiomyopathy (disorder)')
,('http://snomed.info/sct', '472320005', 'Maternally inherited mitochondrial cardiomyopathy and myopathy (disorder)')
,('http://snomed.info/sct', '472323007', 'Fetal cardiomyopathy (disorder)')
,('http://snomed.info/sct', '472324001', 'Fetal hypertrophic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '472325000', 'Fetal hypertrophic cardiomyopathy due to twin to twin transfusion syndrome (disorder)')
,('http://snomed.info/sct', '472326004', 'Fetal hypertrophic cardiomyopathy associated with renal disease (disorder)')
,('http://snomed.info/sct', '472327008', 'Fetal dilated cardiomyopathy (disorder)')
,('http://snomed.info/sct', '50270004', 'Dilated cardiomyopathy due to Friedreichs ataxia (disorder)')
,('http://snomed.info/sct', '50275009', 'Cobalt cardiomyopathy (disorder)')
,('http://snomed.info/sct', '52029003', 'Primary familial dilated cardiomyopathy (disorder)')
,('http://snomed.info/sct', '53043001', 'Primary idiopathic dilated cardiomyopathy (disorder)')
,('http://snomed.info/sct', '53703001', 'Primary eosinophilic endomyocardial cardiomyopathy (disorder)')
,('http://snomed.info/sct', '54830008', 'Dilated cardiomyopathy due to bacterial myocarditis (disorder)')
,('http://snomed.info/sct', '56941009', 'Restrictive cardiomyopathy secondary to hemochromatosis (disorder)')
,('http://snomed.info/sct', '58629009', 'Dilated cardiomyopathy due to amyloidosis (disorder)')
,('http://snomed.info/sct', '58911001', 'Dilated cardiomyopathy due to glycogen storage disease (disorder)')
,('http://snomed.info/sct', '6022005', 'Dilated cardiomyopathy due to sarcoidosis (disorder)')
,('http://snomed.info/sct', '60514000', 'Dilated cardiomyopathy due to familial storage disease (disorder)')
,('http://snomed.info/sct', '62377009', 'Postpartum cardiomyopathy (disorder)')
,('http://snomed.info/sct', '63183009', 'Primary idiopathic hypertrophic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '64041007', 'Primary idiopathic restrictive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '64077000', 'Myocardial degeneration (disorder)')
,('http://snomed.info/sct', '64615000', 'Restrictive cardiomyopathy secondary to glycogen storage disease (disorder)')
,('http://snomed.info/sct', '64749001', 'Dilated cardiomyopathy due to infiltration (disorder)')
,('http://snomed.info/sct', '68602002', 'Primary endomyocardial fibrosis cardiomyopathy (disorder)')
,('http://snomed.info/sct', '69609002', 'Nonobstructive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '699668009', 'Secondary nonischemic congestive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '700065003', 'Primary hypertrophic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '702424003', 'Dilated cardiomyopathy 3B (disorder)')
,('http://snomed.info/sct', '704241002', 'Fetal hypertrophic cardiomyopathy due to maternal diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713523008', 'Cardiomyopathy co-occurrent with human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '715535009', 'Keratosis palmoplantaris and arrhythmogenic cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '715626008', 'Tropical endomyocardial fibrosis (disorder)')
,('http://snomed.info/sct', '715655000', 'Transthyretin related familial amyloid cardiomyopathy (disorder)')
,('http://snomed.info/sct', '715865008', 'Familial isolated arrhythmogenic right ventricular dysplasia (disorder)')
,('http://snomed.info/sct', '717812000', 'Congenital cataract, hypertrophic cardiomyopathy, mitochondrial myopathy syndrome (disorder)')
,('http://snomed.info/sct', '718713000', 'Hypertrophic cardiomyopathy with hypotonia and lactic acidosis syndrome (disorder)')
,('http://snomed.info/sct', '719272007', 'Progressive sensorineural hearing loss and hypertrophic cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '719380003', 'Microcephalus cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '719451006', 'Dilated cardiomyopathy with hypergonadotropic hypogonadism syndrome (disorder)')
,('http://snomed.info/sct', '719824001', 'Vici syndrome (disorder)')
,('http://snomed.info/sct', '719835006', 'Wooly hair and palmoplantar keratoderma with dilated cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '719839000', 'Tubular renal disease with cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '720609003', 'Cardiomyopathy with cataract and hip spine disease syndrome (disorder)')
,('http://snomed.info/sct', '720610008', 'Cardiomyopathy and renal anomaly syndrome (disorder)')
,('http://snomed.info/sct', '721014007', 'Heart-hand syndrome Slovenian type (disorder)')
,('http://snomed.info/sct', '723993005', 'Sensorineural deafness with dilated cardiomyopathy syndrome (disorder)')
,('http://snomed.info/sct', '724173009', 'Maternally inherited cardiomyopathy and hearing loss syndrome (disorder)')
,('http://snomed.info/sct', '725027004', 'Muscle and heart glycogen synthase deficiency (disorder)')
,('http://snomed.info/sct', '725416005', 'Cardiomyopathy due to cirrhosis of liver (disorder)')
,('http://snomed.info/sct', '72972005', 'Dilated cardiomyopathy caused by drug (disorder)')
,('http://snomed.info/sct', '74249003', 'Dilated cardiomyopathy due to malignancy (disorder)')
,('http://snomed.info/sct', '763280005', 'Encephalopathy, hypertrophic cardiomyopathy, renal tubular disease syndrome (disorder)')
,('http://snomed.info/sct', '766883006', 'Familial dilated cardiomyopathy with conduction defect due to lamin A/C mutation (disorder)')
,('http://snomed.info/sct', '76931005', 'Restrictive cardiomyopathy secondary to granulomas (disorder)')
,('http://snomed.info/sct', '771478008', 'Mitochondrial hypertrophic cardiomyopathy with lactic acidosis due to mitochondrial transfer ribonucleic acid translation optimization 1 deficiency (disorder)')
,('http://snomed.info/sct', '771509001', 'Hypertrophic cardiomyopathy and renal tubular disease due to mitochondrial deoxyribonucleic acid mutation (disorder)')
,('http://snomed.info/sct', '771513008', 'Infantile hypertrophic cardiomyopathy due to mitochondrial ribosomal protein L44 deficiency (disorder)')
,('http://snomed.info/sct', '774148007', 'Polyglucosan body myopathy type 1 (disorder)')
,('http://snomed.info/sct', '775908005', 'Combined oxidative phosphorylation defect type 17 (disorder)')
,('http://snomed.info/sct', '788878000', 'Cardiomyopathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789037005', 'Rheumatic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '79152002', 'Dilated cardiomyopathy due to neuromuscular disorder (disorder)')
,('http://snomed.info/sct', '79754008', 'Restrictive cardiomyopathy secondary to amyloidosis (disorder)')
,('http://snomed.info/sct', '8209004', 'Dilated cardiomyopathy due to hemochromatosis (disorder)')
,('http://snomed.info/sct', '83978005', 'Primary familial hypertrophic cardiomyopathy (disorder)')
,('http://snomed.info/sct', '84725008', 'Restrictive cardiomyopathy due to mucopolysaccharidosis (disorder)')
,('http://snomed.info/sct', '84733009', 'Dilated cardiomyopathy due to nutritional deficiency (disorder)')
,('http://snomed.info/sct', '85898001', 'Cardiomyopathy (disorder)')
,('http://snomed.info/sct', '860837007', 'Cardiomyopathy due to connective tissue disease (disorder)')
,('http://snomed.info/sct', '860839005', 'Cardiomyopathy due to storage disease (disorder)')
,('http://snomed.info/sct', '86194008', 'Dilated cardiomyopathy due to infectious disease (disorder)')
,('http://snomed.info/sct', '86995005', 'Dilated cardiomyopathy due to mucopolysaccharidosis (disorder)')
,('http://snomed.info/sct', '871638006', 'Hypertrophic cardiomyopathy due to glycogen storage disease (disorder)')
,('http://snomed.info/sct', '871639003', 'Dilated cardiomyopathy due to mitochondrial disease (disorder)')
,('http://snomed.info/sct', '871646007', 'Infiltrative cardiomyopathy (disorder)')
,('http://snomed.info/sct', '871649000', 'Hypertrophic cardiomyopathy due to lysosomal disease (disorder)')
,('http://snomed.info/sct', '880014009', 'Dilated cardiomyopathy due to carnitine deficiency (disorder)')
,('http://snomed.info/sct', '880038008', 'Dilated cardiomyopathy due to lysosomal storage disease (disorder)')
,('http://snomed.info/sct', '880040003', 'Arrhythmogenic left ventricular cardiomyopathy (disorder)')
,('http://snomed.info/sct', '880042006', 'Dilated cardiomyopathy caused by anthracycline (disorder)')
,('http://snomed.info/sct', '890119003', 'Hypertrophic cardiomyopathy due to Friedreich ataxia (disorder)')
,('http://snomed.info/sct', '890120009', 'Hypertrophic cardiomyopathy due to neuromuscular disorder (disorder)')
,('http://snomed.info/sct', '890121008', 'Hypertrophic cardiomyopathy due to hyperthyroidism (disorder)')
,('http://snomed.info/sct', '890122001', 'Hypertrophic cardiomyopathy due to disorder (disorder)')
,('http://snomed.info/sct', '89461002', 'Primary cardiomyopathy (disorder)')
,('http://snomed.info/sct', '90828009', 'Primary restrictive cardiomyopathy (disorder)')
,('http://snomed.info/sct', '91604001', 'Dilated cardiomyopathy due to polyarteritis nodosa (disorder)')
,('http://snomed.info/sct', '9909003', 'Fatty degeneration of heart (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.0', 'Dilated cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.1', 'Obstructive hypertrophic cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.2', 'Other hypertrophic cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.3', 'Endomyocardial (eosinophilic) disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.4', 'Endocardial fibroelastosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.5', 'Other restrictive cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.6', 'Alcoholic cardiomyopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.7', 'Cardiomyopathy due to drug and external agent')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.8', 'Other cardiomyopathies')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I42.9', 'Cardiomyopathy, unspecified')
) AS t (system, code, display) ;