create or replace view irae__dx_cancer_melanoma_malignant as select * from (values
('http://snomed.info/sct', '109267002', 'Overlapping malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '188033007', 'Malignant melanoma of auricle (ear) (disorder)')
,('http://snomed.info/sct', '254730000', 'Superficial spreading malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254731001', 'Nodular malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254732008', 'Acral lentiginous malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254733003', 'Malignant melanoma arising in intradermal nevus (disorder)')
,('http://snomed.info/sct', '254734009', 'Malignant melanoma arising in congenital nevus (disorder)')
,('http://snomed.info/sct', '276751004', 'Amelanotic malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '302837001', 'Lentigo maligna melanoma (disorder)')
,('http://snomed.info/sct', '307603002', 'Malignant blue nevus of skin (disorder)')
,('http://snomed.info/sct', '314976006', 'Local recurrence of malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '403714009', 'Psoralen and long-wave ultraviolet radiation therapy-associated malignant melanoma (disorder)')
,('http://snomed.info/sct', '424302003', 'Malignant melanoma of skin of lower lip (disorder)')
,('http://snomed.info/sct', '424487008', 'Malignant melanoma of skin of upper lip (disorder)')
,('http://snomed.info/sct', '449636007', 'Malignant melanoma of skin of lower leg (disorder)')
,('http://snomed.info/sct', '449637003', 'Malignant melanoma of skin of upper arm (disorder)')
,('http://snomed.info/sct', '93209006', 'Malignant melanoma of perianal skin (disorder)')
,('http://snomed.info/sct', '93210001', 'Malignant melanoma of skin of abdomen (disorder)')
,('http://snomed.info/sct', '93211002', 'Malignant melanoma of skin of ankle (disorder)')
,('http://snomed.info/sct', '93213004', 'Malignant melanoma of skin of axilla (disorder)')
,('http://snomed.info/sct', '93214005', 'Malignant melanoma of skin of back (disorder)')
,('http://snomed.info/sct', '93215006', 'Malignant melanoma of skin of breast (disorder)')
,('http://snomed.info/sct', '93216007', 'Malignant melanoma of skin of buttock (disorder)')
,('http://snomed.info/sct', '93217003', 'Malignant melanoma of skin of cheek (disorder)')
,('http://snomed.info/sct', '93218008', 'Malignant melanoma of skin of chest (disorder)')
,('http://snomed.info/sct', '93219000', 'Malignant melanoma of skin of chin (disorder)')
,('http://snomed.info/sct', '93220006', 'Malignant melanoma of skin of ear (disorder)')
,('http://snomed.info/sct', '93221005', 'Malignant melanoma of skin of elbow (disorder)')
,('http://snomed.info/sct', '93222003', 'Malignant melanoma of skin of external auditory canal (disorder)')
,('http://snomed.info/sct', '93223008', 'Malignant melanoma of skin of eyebrow (disorder)')
,('http://snomed.info/sct', '93225001', 'Malignant melanoma of skin of face (disorder)')
,('http://snomed.info/sct', '93226000', 'Malignant melanoma of skin of finger (disorder)')
,('http://snomed.info/sct', '93227009', 'Malignant melanoma of skin of foot (disorder)')
,('http://snomed.info/sct', '93228004', 'Malignant melanoma of skin of forearm (disorder)')
,('http://snomed.info/sct', '93229007', 'Malignant melanoma of skin of forehead (disorder)')
,('http://snomed.info/sct', '93230002', 'Malignant melanoma of skin of groin (disorder)')
,('http://snomed.info/sct', '93636004', 'Malignant melanoma of skin of hand (disorder)')
,('http://snomed.info/sct', '93637008', 'Malignant melanoma of skin of hip (disorder)')
,('http://snomed.info/sct', '93638003', 'Malignant melanoma of skin of knee (disorder)')
,('http://snomed.info/sct', '93640008', 'Malignant melanoma of skin of lip (disorder)')
,('http://snomed.info/sct', '93641007', 'Malignant melanoma of skin of lower limb (disorder)')
,('http://snomed.info/sct', '93642000', 'Malignant melanoma of skin of neck (disorder)')
,('http://snomed.info/sct', '93643005', 'Malignant melanoma of skin of nose (disorder)')
,('http://snomed.info/sct', '93644004', 'Malignant melanoma of skin of perineum (disorder)')
,('http://snomed.info/sct', '93645003', 'Malignant melanoma of skin of popliteal area (disorder)')
,('http://snomed.info/sct', '93646002', 'Malignant melanoma of skin of scalp (disorder)')
,('http://snomed.info/sct', '93647006', 'Malignant melanoma of skin of shoulder (disorder)')
,('http://snomed.info/sct', '93648001', 'Malignant melanoma of skin of temporal region (disorder)')
,('http://snomed.info/sct', '93649009', 'Malignant melanoma of skin of thigh (disorder)')
,('http://snomed.info/sct', '93650009', 'Malignant melanoma of skin of toe (disorder)')
,('http://snomed.info/sct', '93651008', 'Malignant melanoma of skin of trunk (disorder)')
,('http://snomed.info/sct', '93652001', 'Malignant melanoma of skin of umbilicus (disorder)')
,('http://snomed.info/sct', '93653006', 'Malignant melanoma of skin of upper limb (disorder)')
,('http://snomed.info/sct', '93654000', 'Malignant melanoma of skin of wrist (disorder)')
,('http://snomed.info/sct', '93655004', 'Malignant melanoma of skin (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.0', 'Malignant melanoma of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.10', 'Malignant melanoma of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.11', 'Malignant melanoma of right eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.12', 'Malignant melanoma of left eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.20', 'Malignant melanoma of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.21', 'Malignant melanoma of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.22', 'Malignant melanoma of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.30', 'Malignant melanoma of unspecified part of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.31', 'Malignant melanoma of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.39', 'Malignant melanoma of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.4', 'Malignant melanoma of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.51', 'Malignant melanoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.52', 'Malignant melanoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.59', 'Malignant melanoma of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.60', 'Malignant melanoma of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.61', 'Malignant melanoma of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.62', 'Malignant melanoma of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.70', 'Malignant melanoma of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.71', 'Malignant melanoma of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.72', 'Malignant melanoma of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.8', 'Malignant melanoma of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.9', 'Malignant melanoma of skin, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.0', 'Melanoma in situ of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.10', 'Melanoma in situ of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.11', 'Melanoma in situ of right eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.12', 'Melanoma in situ of left eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.20', 'Melanoma in situ of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.21', 'Melanoma in situ of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.22', 'Melanoma in situ of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.30', 'Melanoma in situ of unspecified part of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.39', 'Melanoma in situ of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.4', 'Melanoma in situ of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.51', 'Melanoma in situ of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.52', 'Melanoma in situ of breast (skin) (soft tissue)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.59', 'Melanoma in situ of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.60', 'Melanoma in situ of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.61', 'Melanoma in situ of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.62', 'Melanoma in situ of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.70', 'Melanoma in situ of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.71', 'Melanoma in situ of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.72', 'Melanoma in situ of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.8', 'Melanoma in situ of other sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D03.9', 'Melanoma in situ, unspecified')
) AS t (system, code, display) ;