create or replace view irae__dx_cancer_squamous as select * from (values
('http://snomed.info/sct', '1010656004', 'Adenoid squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '1010669000', 'Primary squamous cell carcinoma of superior wall of nasopharynx (disorder)')
,('http://snomed.info/sct', '1010674008', 'Basaloid squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '1010675009', 'Squamous cell carcinoma of posterior wall of nasopharynx (disorder)')
,('http://snomed.info/sct', '1010677001', 'Primary squamous cell carcinomas of anterior wall of nasopharynx (disorder)')
,('http://snomed.info/sct', '1010679003', 'Primary squamous cell carcinoma of lateral wall of nasopharynx (disorder)')
,('http://snomed.info/sct', '1010681001', 'Primary squamous cell carcinoma of overlapping sites of nasopharynx (disorder)')
,('http://snomed.info/sct', '105041000119109', 'Metastatic squamous cell carcinoma to lung (disorder)')
,('http://snomed.info/sct', '105111000119109', 'Primary squamous cell carcinoma of thymus (disorder)')
,('http://snomed.info/sct', '105121000119102', 'Squamous cell carcinoma of vagina (disorder)')
,('http://snomed.info/sct', '107591000119100', 'Primary squamous cell carcinoma of urethra (disorder)')
,('http://snomed.info/sct', '107791000119107', 'Primary adenosquamous carcinoma of endometrium (disorder)')
,('http://snomed.info/sct', '107831000119101', 'Metastatic squamous cell carcinoma to liver (disorder)')
,('http://snomed.info/sct', '1082051000119106', 'Primary squamous cell carcinoma of skin of left upper limb (disorder)')
,('http://snomed.info/sct', '1082061000119108', 'Primary squamous cell carcinoma of conjunctiva of left eye (disorder)')
,('http://snomed.info/sct', '1082071000119102', 'Primary squamous cell carcinoma of left ear (disorder)')
,('http://snomed.info/sct', '1082091000119101', 'Primary squamous cell carcinoma of skin of left hip (disorder)')
,('http://snomed.info/sct', '1082101000119106', 'Primary squamous cell carcinoma of skin of left lower limb (disorder)')
,('http://snomed.info/sct', '1082111000119109', 'Primary squamous cell carcinoma of lower lobe of left lung (disorder)')
,('http://snomed.info/sct', '1082121000119102', 'Primary squamous cell carcinoma of left main bronchus (disorder)')
,('http://snomed.info/sct', '1082131000119104', 'Primary squamous cell carcinoma of skin of left shoulder (disorder)')
,('http://snomed.info/sct', '1082141000119108', 'Primary squamous cell carcinoma of upper lobe of left lung (disorder)')
,('http://snomed.info/sct', '1082171000119101', 'Primary squamous cell carcinoma of skin of right upper limb (disorder)')
,('http://snomed.info/sct', '1082181000119103', 'Primary squamous cell carcinoma of conjunctiva of right eye (disorder)')
,('http://snomed.info/sct', '1082191000119100', 'Primary squamous cell carcinoma of right ear (disorder)')
,('http://snomed.info/sct', '1082211000119104', 'Primary squamous cell carcinoma of skin of right hip (disorder)')
,('http://snomed.info/sct', '1082221000119106', 'Primary squamous cell carcinoma of skin of right lower limb (disorder)')
,('http://snomed.info/sct', '1082231000119109', 'Primary squamous cell carcinoma of lower lobe of right lung (disorder)')
,('http://snomed.info/sct', '1082241000119100', 'Primary squamous cell carcinoma of right main bronchus (disorder)')
,('http://snomed.info/sct', '1082251000119103', 'Primary squamous cell carcinoma of middle lobe of right lung (disorder)')
,('http://snomed.info/sct', '1082261000119101', 'Primary squamous cell carcinoma of skin of right shoulder (disorder)')
,('http://snomed.info/sct', '1082271000119107', 'Primary squamous cell carcinoma of upper lobe of right lung (disorder)')
,('http://snomed.info/sct', '1148901006', 'Squamous cell carcinoma of male genital (disorder)')
,('http://snomed.info/sct', '1197275006', 'Primary squamous cell carcinoma of fallopian tube (disorder)')
,('http://snomed.info/sct', '1197276007', 'Primary squamous cell carcinoma of pharyngeal lymphoid ring (disorder)')
,('http://snomed.info/sct', '1197285007', 'Metastatic squamous cell carcinoma to thoracic lymph node (disorder)')
,('http://snomed.info/sct', '1197292002', 'Metastatic squamous cell carcinoma of pelvic lymph node (disorder)')
,('http://snomed.info/sct', '1197293007', 'Metastatic squamous cell carcinoma to lymph nodes of head and neck (disorder)')
,('http://snomed.info/sct', '1197295000', 'Metastatic squamous cell carcinoma to lymph nodes of multiple sites (disorder)')
,('http://snomed.info/sct', '1197297008', 'Metastatic squamous cell carcinoma to lymph node of lower limb (disorder)')
,('http://snomed.info/sct', '1197299006', 'Metastatic squamous cell carcinoma to lymph node of upper limb (disorder)')
,('http://snomed.info/sct', '1197322005', 'Metastatic squamous cell carcinoma to abdominal lymph node (disorder)')
,('http://snomed.info/sct', '12240951000119107', 'Squamous cell carcinoma of left lung (disorder)')
,('http://snomed.info/sct', '12240991000119102', 'Squamous cell carcinoma of right lung (disorder)')
,('http://snomed.info/sct', '1229871006', 'Primary squamous cell carcinoma of nasal cavity and paranasal sinus (disorder)')
,('http://snomed.info/sct', '1237048006', 'Metastatic squamous cell carcinoma to bronchus (disorder)')
,('http://snomed.info/sct', '1237466009', 'Metastatic squamous cell carcinoma to bronchus of left upper lobe (disorder)')
,('http://snomed.info/sct', '1237467000', 'Metastatic squamous cell carcinoma to bronchus of right upper lobe (disorder)')
,('http://snomed.info/sct', '1237469002', 'Metastatic squamous cell carcinoma to bronchus of left lower lobe (disorder)')
,('http://snomed.info/sct', '1237471002', 'Metastatic squamous cell carcinoma to bronchus of right lower lobe (disorder)')
,('http://snomed.info/sct', '1237472009', 'Metastatic squamous cell carcinoma to bronchus of middle lobe of right lung (disorder)')
,('http://snomed.info/sct', '1240353009', 'Metastatic squamous cell carcinoma to prostate (disorder)')
,('http://snomed.info/sct', '1240355002', 'Metastatic squamous cell carcinoma to epididymis and spermatic cord (disorder)')
,('http://snomed.info/sct', '1240370001', 'Metastatic squamous cell carcinoma to liver and intrahepatic biliary tract (disorder)')
,('http://snomed.info/sct', '1254748001', 'Metastatic clear cell squamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '1254749009', 'Metastatic acantholytic squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '1254750009', 'Metastatic acantholytic squamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '1254755004', 'Metastatic basosquamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '1254785009', 'Squamous cell adenoid carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '1254787001', 'Papillary squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '1254789003', 'Clear cell squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '1254790007', 'Basaloid squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '1254800007', 'Squamous cell carcinoma of lateral wall of oropharynx (disorder)')
,('http://snomed.info/sct', '1254801006', 'Basaloid squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '1254803009', 'Papillary squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '1254805002', 'Squamous cell carcinoma of posterior wall of oropharynx (disorder)')
,('http://snomed.info/sct', '1254806001', 'Spindle cell squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '1254852008', 'Squamous cell carcinoma of laryngeal cartilage (disorder)')
,('http://snomed.info/sct', '1255631006', 'Spindle cell squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '1255632004', 'Spindle cell squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '1255646004', 'Basaloid squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '1255647008', 'Basaloid squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '1255651005', 'Basaloid squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '1255660002', 'Squamous cell carcinoma of sphenoidal sinus (disorder)')
,('http://snomed.info/sct', '1259367002', 'Primary squamous cell carcinoma of bronchus (disorder)')
,('http://snomed.info/sct', '1259371004', 'Primary squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '1259372006', 'Primary clear cell squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259373001', 'Primary spindle cell squamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259374007', 'Primary acantholytic squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259376009', 'Primary basosquamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '1259387001', 'Primary adenosquamous carcinoma of cervix (disorder)')
,('http://snomed.info/sct', '1259409000', 'Primary squamous cell carcinoma of bronchus in left lower lobe (disorder)')
,('http://snomed.info/sct', '1259410005', 'Primary squamous cell carcinoma of bronchus in left upper lobe (disorder)')
,('http://snomed.info/sct', '1259411009', 'Primary squamous cell carcinoma of bronchus in right lower lobe (disorder)')
,('http://snomed.info/sct', '1259412002', 'Primary squamous cell carcinoma of bronchus of middle lobe of right lung (disorder)')
,('http://snomed.info/sct', '1259413007', 'Primary squamous cell carcinoma of bronchus in right upper lobe (disorder)')
,('http://snomed.info/sct', '1259445002', 'Primary keratinizing squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '1259446001', 'Primary undifferentiated nonkeratinizing squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '1259454004', 'Primary adenosquamous carcinoma (disorder)')
,('http://snomed.info/sct', '1259461000', 'Primary squamous cell carcinoma of right lung (disorder)')
,('http://snomed.info/sct', '1259463002', 'Primary squamous cell carcinoma of left lung (disorder)')
,('http://snomed.info/sct', '1259551009', 'Primary spindle cell squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '1259553007', 'Primary acantholytic squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '1259555000', 'Primary verrucous squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '1259620008', 'Primary papillary squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '1259702008', 'Primary adenoid squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '1259704009', 'Primary basaloid squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '1259754003', 'Primary squamous non-small cell lung cancer (disorder)')
,('http://snomed.info/sct', '1259757005', 'Primary nonsquamous nonsmall cell neoplasm of lung (disorder)')
,('http://snomed.info/sct', '1260021004', 'Adenoid squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '1260024007', 'Adenoid squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '1260037005', 'Adenosquamous carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '1260038000', 'Adenosquamous carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '1260039008', 'Adenosquamous carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '1260040005', 'Adenosquamous carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '1260042002', 'Adenosquamous carcinoma of lung (disorder)')
,('http://snomed.info/sct', '1260046004', 'Squamous cell carcinoma of ethmoidal sinus (disorder)')
,('http://snomed.info/sct', '1260048003', 'Squamous cell carcinoma of frontal sinus (disorder)')
,('http://snomed.info/sct', '1260056000', 'Clear cell squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '1260071001', 'Papillary squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '1260073003', 'Papillary squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '1260074009', 'Papillary squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '1260076006', 'Small cell non-keratinizing squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '1260079004', 'Squamous cell carcinoma of hypopharyngeal aspect of aryepiglottic fold (disorder)')
,('http://snomed.info/sct', '1260080001', 'Squamous cell carcinoma of maxillary sinus (disorder)')
,('http://snomed.info/sct', '1260081002', 'Squamous cell carcinoma of postcricoid region (disorder)')
,('http://snomed.info/sct', '1260082009', 'Squamous cell carcinoma of posterior wall of hypopharynx (disorder)')
,('http://snomed.info/sct', '1260083004', 'Squamous cell carcinoma of piriform sinus (disorder)')
,('http://snomed.info/sct', '1260084005', 'Squamous cell carcinoma of vallecula (disorder)')
,('http://snomed.info/sct', '1263786003', 'Metastatic basaloid squamous cell carcinoma to nasopharynx (disorder)')
,('http://snomed.info/sct', '1264066001', 'Metastatic keratinizing squamous cell carcinoma to nasopharynx (disorder)')
,('http://snomed.info/sct', '1264116009', 'Metastatic adenosquamous carcinoma (disorder)')
,('http://snomed.info/sct', '1264117000', 'Metastatic adenosquamous carcinoma to cervix (disorder)')
,('http://snomed.info/sct', '1264258003', 'Metastatic papillary squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '1268541001', 'Primary squamous cell carcinoma of liver and intrahepatic biliary tract (disorder)')
,('http://snomed.info/sct', '1268632002', 'Primary squamous cell carcinoma of gallbladder and extrahepatic biliary tract (disorder)')
,('http://snomed.info/sct', '1268633007', 'Primary squamous cell carcinoma of rectum (disorder)')
,('http://snomed.info/sct', '1268634001', 'Primary squamous cell carcinoma of stomach (disorder)')
,('http://snomed.info/sct', '1268635000', 'Primary squamous cell carcinoma of colon (disorder)')
,('http://snomed.info/sct', '1268636004', 'Primary squamous cell carcinoma of small intestine (disorder)')
,('http://snomed.info/sct', '1269123008', 'Metastatic squamous cell carcinoma to rectum (disorder)')
,('http://snomed.info/sct', '1269125001', 'Metastatic squamous cell carcinoma to small intestine (disorder)')
,('http://snomed.info/sct', '1269126000', 'Metastatic squamous cell carcinoma to stomach (disorder)')
,('http://snomed.info/sct', '15957141000119109', 'Metastatic squamous cell carcinoma to bilateral lungs (disorder)')
,('http://snomed.info/sct', '15957181000119104', 'Metastatic squamous cell carcinoma to right lung (disorder)')
,('http://snomed.info/sct', '15957221000119107', 'Metastatic squamous cell carcinoma to left lung (disorder)')
,('http://snomed.info/sct', '15958301000119109', 'Metastatic squamous cell carcinoma to right kidney (disorder)')
,('http://snomed.info/sct', '15958381000119101', 'Metastatic squamous cell carcinoma to left kidney (disorder)')
,('http://snomed.info/sct', '1671000119100', 'Metastatic squamous cell carcinoma to lymph node (disorder)')
,('http://snomed.info/sct', '18121000119104', 'Primary squamous cell carcinoma of palatine tonsil (disorder)')
,('http://snomed.info/sct', '231831002', 'Squamous cell carcinoma of eyelid (disorder)')
,('http://snomed.info/sct', '254437001', 'Squamous cell carcinoma of buccal mucosa (disorder)')
,('http://snomed.info/sct', '254620000', 'Squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '254622008', 'Squamous cell carcinoma of bronchus (disorder)')
,('http://snomed.info/sct', '254634000', 'Squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '254651007', 'Squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254652000', 'Clear cell squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254653005', 'Spindle cell squamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254654004', 'Acantholytic squamous cell carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254702000', 'Basosquamous carcinoma of skin (disorder)')
,('http://snomed.info/sct', '254886006', 'Squamous cell carcinoma of cervix (disorder)')
,('http://snomed.info/sct', '254888007', 'Adenosquamous carcinoma of cervix (disorder)')
,('http://snomed.info/sct', '254895003', 'Squamous cell carcinoma of vulva (disorder)')
,('http://snomed.info/sct', '255003007', 'Squamous cell carcinoma of conjunctiva (disorder)')
,('http://snomed.info/sct', '255008003', 'Squamous cell carcinoma of cornea (disorder)')
,('http://snomed.info/sct', '255071008', 'Squamous cell carcinoma of lip (disorder)')
,('http://snomed.info/sct', '255084004', 'Squamous cell carcinoma of anal margin (disorder)')
,('http://snomed.info/sct', '255111004', 'Squamous cell carcinoma of urinary bladder (disorder)')
,('http://snomed.info/sct', '276804009', 'Squamous cell carcinoma of esophagus (disorder)')
,('http://snomed.info/sct', '276860003', 'Squamous cell carcinoma of scrotum (disorder)')
,('http://snomed.info/sct', '276952000', 'Squamous cell carcinoma of tongue (disorder)')
,('http://snomed.info/sct', '276953005', 'Squamous cell carcinoma of gum (disorder)')
,('http://snomed.info/sct', '276954004', 'Squamous cell carcinoma of floor of mouth (disorder)')
,('http://snomed.info/sct', '276962007', 'Squamous cell carcinoma of palate (disorder)')
,('http://snomed.info/sct', '285307007', 'Squamous cell carcinoma of skin of upper lip (disorder)')
,('http://snomed.info/sct', '285308002', 'Squamous cell carcinoma of skin of lower lip (disorder)')
,('http://snomed.info/sct', '285309005', 'Squamous cell carcinoma of skin of cheek (disorder)')
,('http://snomed.info/sct', '307502000', 'Squamous cell carcinoma of mouth (disorder)')
,('http://snomed.info/sct', '313353007', 'Squamous cell carcinoma of bronchus in left lower lobe (disorder)')
,('http://snomed.info/sct', '313354001', 'Squamous cell carcinoma of bronchus in left upper lobe (disorder)')
,('http://snomed.info/sct', '313355000', 'Squamous cell carcinoma of bronchus in right lower lobe (disorder)')
,('http://snomed.info/sct', '313356004', 'Squamous cell carcinoma of bronchus of middle lobe of right lung (disorder)')
,('http://snomed.info/sct', '313357008', 'Squamous cell carcinoma of bronchus in right upper lobe (disorder)')
,('http://snomed.info/sct', '399590005', 'Squamous cell carcinoma of prostate (disorder)')
,('http://snomed.info/sct', '402815007', 'Squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '402816008', 'Squamous cell carcinoma of anogenital area (disorder)')
,('http://snomed.info/sct', '402817004', 'Squamous cell carcinoma of nail apparatus (disorder)')
,('http://snomed.info/sct', '403468003', 'Squamous cell carcinoma of penis (disorder)')
,('http://snomed.info/sct', '403713003', 'Psoralen and long-wave ultraviolet radiation therapy-associated squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '403890009', 'Squamous cell carcinoma of vulva due to lichen sclerosus (disorder)')
,('http://snomed.info/sct', '403891008', 'Squamous cell carcinoma of scalp (disorder)')
,('http://snomed.info/sct', '403892001', 'Squamous cell carcinoma of skin of face (disorder)')
,('http://snomed.info/sct', '403893006', 'Squamous cell carcinoma of forehead (disorder)')
,('http://snomed.info/sct', '403894000', 'Squamous cell carcinoma of skin of ear (disorder)')
,('http://snomed.info/sct', '403895004', 'Squamous cell carcinoma of foot (disorder)')
,('http://snomed.info/sct', '403896003', 'Squamous cell carcinoma of hand (disorder)')
,('http://snomed.info/sct', '403897007', 'Squamous cell carcinoma of upper extremity (disorder)')
,('http://snomed.info/sct', '403898002', 'Squamous cell carcinoma of skin of lower extremity (disorder)')
,('http://snomed.info/sct', '403899005', 'Squamous cell carcinoma of skin of trunk (disorder)')
,('http://snomed.info/sct', '403900000', 'Spindle cell squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '403901001', 'Acantholytic squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '403902008', 'Adenosquamous carcinoma (disorder)')
,('http://snomed.info/sct', '403903003', 'Signet ring squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '403904009', 'Verrucous squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '403905005', 'Multiple squamous cell carcinomata (disorder)')
,('http://snomed.info/sct', '403906006', 'Metastatic squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '405822008', 'Squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '408648004', 'Squamous cell carcinoma of epiglottis (disorder)')
,('http://snomed.info/sct', '408649007', 'Squamous cell carcinoma of pharynx (disorder)')
,('http://snomed.info/sct', '418372008', 'Squamous cell carcinoma of mucous membrane of lower lip (disorder)')
,('http://snomed.info/sct', '419240004', 'Squamous cell carcinoma of mucous membrane of upper lip (disorder)')
,('http://snomed.info/sct', '419842002', 'Squamous cell carcinoma of oral mucous membrane (disorder)')
,('http://snomed.info/sct', '422378004', 'Squamous cell carcinoma of bridge of nose (disorder)')
,('http://snomed.info/sct', '422572002', 'Squamous cell carcinoma of chin (disorder)')
,('http://snomed.info/sct', '422599000', 'Squamous cell carcinoma of back (disorder)')
,('http://snomed.info/sct', '422676009', 'Squamous cell carcinoma of ala nasi (disorder)')
,('http://snomed.info/sct', '422691006', 'Squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '423284006', 'Squamous cell carcinoma of skin of neck (disorder)')
,('http://snomed.info/sct', '423295000', 'Squamous cell carcinoma of lung, TNM stage 1 (disorder)')
,('http://snomed.info/sct', '423464009', 'Squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '423468007', 'Squamous cell carcinoma of lung, TNM stage 2 (disorder)')
,('http://snomed.info/sct', '423506005', 'Squamous cell carcinoma of external auditory canal (disorder)')
,('http://snomed.info/sct', '423700001', 'Squamous cell carcinoma of auricle of ear (disorder)')
,('http://snomed.info/sct', '423896007', 'Squamous cell carcinoma of tip of nose (disorder)')
,('http://snomed.info/sct', '424260006', 'Squamous cell carcinoma of nasolabial fold (disorder)')
,('http://snomed.info/sct', '425148008', 'Squamous cell carcinoma of temple (disorder)')
,('http://snomed.info/sct', '425230006', 'Squamous cell carcinoma of lung, TNM stage 3 (disorder)')
,('http://snomed.info/sct', '425303004', 'Squamous cell carcinomatosis (disorder)')
,('http://snomed.info/sct', '425376008', 'Squamous cell carcinoma of lung, TNM stage 4 (disorder)')
,('http://snomed.info/sct', '440173001', 'Nonsquamous nonsmall cell neoplasm of lung (disorder)')
,('http://snomed.info/sct', '440527006', 'Primary squamous cell carcinoma of naris (disorder)')
,('http://snomed.info/sct', '448165009', 'Squamous cell carcinoma arising in chronic ulcer (disorder)')
,('http://snomed.info/sct', '448930008', 'Squamous cell carcinoma of nose (disorder)')
,('http://snomed.info/sct', '448931007', 'Squamous cell carcinoma of shoulder (disorder)')
,('http://snomed.info/sct', '455733521000119103', 'Primary squamous cell carcinoma of skin of head and/or neck (disorder)')
,('http://snomed.info/sct', '688671000119103', 'Primary squamous cell carcinoma of anterior floor of mouth (disorder)')
,('http://snomed.info/sct', '688681000119100', 'Primary squamous cell carcinoma of body of tongue (disorder)')
,('http://snomed.info/sct', '688691000119102', 'Primary squamous cell carcinoma of anterior wall of urinary bladder (disorder)')
,('http://snomed.info/sct', '688711000119104', 'Primary squamous cell carcinoma of aryepiglottic fold (disorder)')
,('http://snomed.info/sct', '688731000119109', 'Primary squamous cell carcinoma of neck of urinary bladder (disorder)')
,('http://snomed.info/sct', '688751000119103', 'Primary squamous cell carcinoma of border of tongue (disorder)')
,('http://snomed.info/sct', '688781000119105', 'Primary squamous cell carcinoma of commissure of lip (disorder)')
,('http://snomed.info/sct', '688801000119109', 'Primary squamous cell carcinoma of dome of urinary bladder (disorder)')
,('http://snomed.info/sct', '688811000119107', 'Primary squamous cell carcinoma of dorsal surface of tongue (disorder)')
,('http://snomed.info/sct', '688861000119105', 'Primary squamous cell carcinoma of hard palate (disorder)')
,('http://snomed.info/sct', '688891000119103', 'Primary squamous cell carcinoma of mucous membrane of lip (disorder)')
,('http://snomed.info/sct', '688901000119104', 'Primary squamous cell carcinoma of mucous membrane of lower lip (disorder)')
,('http://snomed.info/sct', '688911000119101', 'Primary squamous cell carcinoma of mucous membrane of upper lip (disorder)')
,('http://snomed.info/sct', '688931000119106', 'Primary squamous cell carcinoma of lateral floor of mouth (disorder)')
,('http://snomed.info/sct', '688941000119102', 'Primary squamous cell carcinoma of lateral wall of urinary bladder (disorder)')
,('http://snomed.info/sct', '688981000119107', 'Primary squamous cell carcinoma of lower gum (disorder)')
,('http://snomed.info/sct', '689211000119102', 'Primary squamous cell carcinoma of perianal skin (disorder)')
,('http://snomed.info/sct', '689231000119107', 'Primary squamous cell carcinoma of posterior wall of urinary bladder (disorder)')
,('http://snomed.info/sct', '689251000119101', 'Primary squamous cell carcinoma of posterior wall of nasopharynx (disorder)')
,('http://snomed.info/sct', '689281000119108', 'Primary squamous cell carcinoma of retromolar area (disorder)')
,('http://snomed.info/sct', '689311000119105', 'Primary squamous cell carcinoma of soft palate (disorder)')
,('http://snomed.info/sct', '689361000119108', 'Primary squamous cell carcinoma of tonsillar fossa (disorder)')
,('http://snomed.info/sct', '689371000119102', 'Primary squamous cell carcinoma of tonsillar pillar (disorder)')
,('http://snomed.info/sct', '689401000119104', 'Primary squamous cell carcinoma of upper gum (disorder)')
,('http://snomed.info/sct', '689441000119102', 'Primary squamous cell carcinoma of ureteral orifice (disorder)')
,('http://snomed.info/sct', '689451000119100', 'Primary squamous cell carcinoma of uvula (disorder)')
,('http://snomed.info/sct', '689471000119109', 'Primary squamous cell carcinoma of inferior surface of tongue (disorder)')
,('http://snomed.info/sct', '689481000119107', 'Primary squamous cell carcinoma of vermilion border of lower lip (disorder)')
,('http://snomed.info/sct', '689491000119105', 'Primary squamous cell carcinoma of vermilion border of upper lip (disorder)')
,('http://snomed.info/sct', '689501000119103', 'Primary squamous cell carcinoma of vestibule of mouth (disorder)')
,('http://snomed.info/sct', '698011002', 'Keratinizing squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '698048006', 'Undifferentiated nonkeratinizing squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '707353009', 'Primary squamous cell carcinoma of accessory sinus (disorder)')
,('http://snomed.info/sct', '707354003', 'Primary squamous cell carcinoma of maxillary sinus (disorder)')
,('http://snomed.info/sct', '707355002', 'Primary squamous cell carcinoma of sphenoidal sinus (disorder)')
,('http://snomed.info/sct', '707356001', 'Primary squamous cell carcinoma of frontal sinus (disorder)')
,('http://snomed.info/sct', '707357005', 'Primary squamous cell carcinoma of laryngeal cartilage (disorder)')
,('http://snomed.info/sct', '707358000', 'Primary squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '707359008', 'Primary squamous cell carcinoma of ethmoidal sinus (disorder)')
,('http://snomed.info/sct', '707388009', 'Primary squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '707389001', 'Primary clear cell squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '707390005', 'Primary basaloid squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '707391009', 'Primary papillary squamous cell carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '707393007', 'Primary adenosquamous carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '707405009', 'Primary adenosquamous carcinoma of lung (disorder)')
,('http://snomed.info/sct', '707408006', 'Primary small cell non-keratinizing squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '707422006', 'Primary spindle cell squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '707424007', 'Primary adenosquamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '707425008', 'Primary adenoid squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '707426009', 'Primary papillary squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '707429002', 'Overlapping squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '707430007', 'Overlapping squamous cell carcinoma of laryngeal cartilage (disorder)')
,('http://snomed.info/sct', '707453008', 'Primary clear cell squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '707454002', 'Primary basaloid squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '707455001', 'Primary papillary squamous cell carcinoma of lung (disorder)')
,('http://snomed.info/sct', '707481002', 'Primary basaloid squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '707482009', 'Primary papillary squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '707484005', 'Primary adenoid squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '707485006', 'Primary adenosquamous carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '707489000', 'Primary spindle cell squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '707492001', 'Primary squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '707495004', 'Primary squamous cell adenoid carcinoma of trachea (disorder)')
,('http://snomed.info/sct', '707528007', 'Primary squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '707529004', 'Overlapping squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '707531008', 'Primary squamous cell carcinoma of branchial cleft (disorder)')
,('http://snomed.info/sct', '707532001', 'Primary squamous cell carcinoma of posterior wall of oropharynx (disorder)')
,('http://snomed.info/sct', '707535004', 'Primary squamous cell carcinoma of lateral wall of oropharynx (disorder)')
,('http://snomed.info/sct', '707537007', 'Primary squamous cell carcinoma of anterior surface of epiglottis (disorder)')
,('http://snomed.info/sct', '707538002', 'Primary squamous cell carcinoma of vallecula (disorder)')
,('http://snomed.info/sct', '707575007', 'Primary squamous cell carcinoma of supraglottis (disorder)')
,('http://snomed.info/sct', '707576008', 'Primary squamous cell carcinoma of subglottis (disorder)')
,('http://snomed.info/sct', '707579001', 'Primary basaloid squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '707581004', 'Primary papillary squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '707582006', 'Primary spindle cell squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '707583001', 'Primary adenosquamous carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '707585008', 'Primary squamous cell carcinoma of oropharynx (disorder)')
,('http://snomed.info/sct', '707628004', 'Overlapping squamous cell carcinoma of hypopharynx (disorder)')
,('http://snomed.info/sct', '707662004', 'Primary basaloid squamous cell carcinoma of larynx (disorder)')
,('http://snomed.info/sct', '707664003', 'Primary squamous cell carcinoma of glottis (disorder)')
,('http://snomed.info/sct', '707686002', 'Primary squamous cell carcinoma of posterior wall of hypopharynx (disorder)')
,('http://snomed.info/sct', '707697002', 'Primary squamous cell carcinoma of hypopharyngeal aspect of aryepiglottic fold (disorder)')
,('http://snomed.info/sct', '707703001', 'Primary squamous cell carcinoma of postcricoid region (disorder)')
,('http://snomed.info/sct', '707704007', 'Primary squamous cell carcinoma of pyriform sinus (disorder)')
,('http://snomed.info/sct', '716659002', 'Squamous cell carcinoma of head and neck (disorder)')
,('http://snomed.info/sct', '719052006', 'Recurrent squamous cell carcinoma (disorder)')
,('http://snomed.info/sct', '721604004', 'Primary squamous cell carcinoma of overlapping sites of male genital organ (disorder)')
,('http://snomed.info/sct', '721605003', 'Primary squamous cell carcinoma of overlapping sites of accessory sinuses (disorder)')
,('http://snomed.info/sct', '721618006', 'Primary squamous cell carcinoma of upper third of esophagus (disorder)')
,('http://snomed.info/sct', '721619003', 'Primary squamous cell carcinoma of middle third of esophagus (disorder)')
,('http://snomed.info/sct', '721620009', 'Primary squamous cell carcinoma of lower third of esophagus (disorder)')
,('http://snomed.info/sct', '721621008', 'Primary squamous cell carcinoma of overlapping sites of esophagus (disorder)')
,('http://snomed.info/sct', '722112006', 'Primary squamous cell carcinoma of ear (disorder)')
,('http://snomed.info/sct', '722530005', 'Primary squamous cell carcinoma of pharyngeal tonsil (disorder)')
,('http://snomed.info/sct', '722542000', 'Primary squamous cell carcinoma of anal canal (disorder)')
,('http://snomed.info/sct', '722666002', 'Primary squamous cell carcinoma of lacrimal apparatus (disorder)')
,('http://snomed.info/sct', '722672002', 'Primary squamous cell carcinoma of base of tongue (disorder)')
,('http://snomed.info/sct', '722673007', 'Primary squamous cell carcinoma of lingual tonsil (disorder)')
,('http://snomed.info/sct', '722674001', 'Primary squamous cell carcinoma of parotid gland (disorder)')
,('http://snomed.info/sct', '722676004', 'Primary squamous cell carcinoma of middle ear (disorder)')
,('http://snomed.info/sct', '722678003', 'Primary squamous cell carcinoma of vagina (disorder)')
,('http://snomed.info/sct', '723182009', 'Primary squamous cell carcinoma of nasal cavity (disorder)')
,('http://snomed.info/sct', '723265000', 'Primary squamous cell carcinoma of anus (disorder)')
,('http://snomed.info/sct', '723301009', 'Squamous non-small cell lung cancer (disorder)')
,('http://snomed.info/sct', '724467001', 'Primary squamous cell carcinoma of overlapping sites of urinary organs (disorder)')
,('http://snomed.info/sct', '733134009', 'Primary squamous cell carcinoma of paraurethral gland (disorder)')
,('http://snomed.info/sct', '733343005', 'Primary squamous cell carcinoma of oral cavity (disorder)')
,('http://snomed.info/sct', '733344004', 'Primary squamous cell carcinoma of lip (disorder)')
,('http://snomed.info/sct', '733345003', 'Primary squamous cell carcinoma of pharynx (disorder)')
,('http://snomed.info/sct', '733357007', 'Primary squamous cell carcinoma of intrathoracic organ (disorder)')
,('http://snomed.info/sct', '733358002', 'Primary squamous cell carcinoma of respiratory system (disorder)')
,('http://snomed.info/sct', '733359005', 'Primary squamous cell carcinoma of endometrium (disorder)')
,('http://snomed.info/sct', '737310005', 'Primary squamous cell carcinoma of submandibular gland (disorder)')
,('http://snomed.info/sct', '737311009', 'Primary squamous cell carcinoma of sublingual gland (disorder)')
,('http://snomed.info/sct', '764735002', 'Squamous cell carcinoma of small intestine (disorder)')
,('http://snomed.info/sct', '764737005', 'Squamous cell carcinoma of corpus uteri (disorder)')
,('http://snomed.info/sct', '766978002', 'Squamous cell carcinoma of gallbladder and extrahepatic biliary tract (disorder)')
,('http://snomed.info/sct', '766979005', 'Squamous cell carcinoma of rectum (disorder)')
,('http://snomed.info/sct', '766980008', 'Squamous cell carcinoma of stomach (disorder)')
,('http://snomed.info/sct', '766981007', 'Squamous cell carcinoma of colon (disorder)')
,('http://snomed.info/sct', '770602005', 'Squamous cell carcinoma of exocrine pancreas (disorder)')
,('http://snomed.info/sct', '770684008', 'Squamous cell carcinoma of liver and intrahepatic biliary tract (disorder)')
,('http://snomed.info/sct', '78461000119105', 'Metastatic squamous cell carcinoma to skin (disorder)')
,('http://snomed.info/sct', '870327007', 'Papillary squamous cell carcinoma of nasopharynx (disorder)')
,('http://snomed.info/sct', '91151000119103', 'Primary squamous cell carcinoma of chest wall (disorder)')
,('http://snomed.info/sct', '91181000119105', 'Squamous cell carcinoma metastatic to pleura (disorder)')
,('http://snomed.info/sct', '91271000119101', 'Metastatic squamous cell carcinoma to bone (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.02', 'Squamous cell carcinoma of skin of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.121', 'Squamous cell carcinoma of skin of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1221', 'Squamous cell carcinoma of skin of right upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1222', 'Squamous cell carcinoma of skin of right lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1291', 'Squamous cell carcinoma of skin of left upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.1292', 'Squamous cell carcinoma of skin of left lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.221', 'Squamous cell carcinoma of skin of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.222', 'Squamous cell carcinoma of skin of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.229', 'Squamous cell carcinoma of skin of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.320', 'Squamous cell carcinoma of skin of unspecified parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.321', 'Squamous cell carcinoma of skin of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.329', 'Squamous cell carcinoma of skin of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.42', 'Squamous cell carcinoma of skin of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.520', 'Squamous cell carcinoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.521', 'Squamous cell carcinoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.529', 'Squamous cell carcinoma of skin of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.621', 'Squamous cell carcinoma of skin of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.622', 'Squamous cell carcinoma of skin of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.629', 'Squamous cell carcinoma of skin of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.721', 'Squamous cell carcinoma of skin of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.722', 'Squamous cell carcinoma of skin of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.729', 'Squamous cell carcinoma of skin of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.82', 'Squamous cell carcinoma of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C44.92', 'Squamous cell carcinoma of skin, unspecified')
) AS t (system, code, display) ;