create or replace view irae__dx_diabetes_nephropathy as select * from (values
('http://snomed.info/sct', '127013003', 'Disorder of kidney due to diabetes mellitus (disorder)')
,('http://hl7.org/fhir/sid/icd-9-cm', '250.41', 'Diabetes with renal manifestations, type I [juvenile type], not stated as uncontrolled')
,('http://hl7.org/fhir/sid/icd-9-cm', '250.42', 'Diabetes with renal manifestations, type II or unspecified type, uncontrolled')
,('http://hl7.org/fhir/sid/icd-9-cm', '250.43', 'Diabetes with renal manifestations, type I [juvenile type], uncontrolled')
,('http://snomed.info/sct', '38046004', 'Diffuse glomerulosclerosis of kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420715001', 'Persistent microalbuminuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421986006', 'Persistent proteinuria due to type 2 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '445170001', 'Macroalbuminuric nephropathy due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71701000119105', 'Hypertension in chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '792926007', 'Armanni-Ebstein kidney due to diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90721000119101', 'Chronic kidney disease stage 1 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90731000119103', 'Chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90741000119107', 'Chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90751000119109', 'Chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90761000119106', 'Chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90771000119100', 'End stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '96441000119101', 'Chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.21', 'Diabetes mellitus due to underlying condition with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.22', 'Diabetes mellitus due to underlying condition with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E08.29', 'Diabetes mellitus due to underlying condition with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.21', 'Drug or chemical induced diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.22', 'Drug or chemical induced diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E09.29', 'Drug or chemical induced diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.21', 'Type 1 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.22', 'Type 1 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.29', 'Type 1 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.21', 'Type 2 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.22', 'Type 2 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E11.29', 'Type 2 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.21', 'Other specified diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.22', 'Other specified diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E13.29', 'Other specified diabetes mellitus with other diabetic kidney complication')
) AS t (system, code, display) ;