create or replace view irae__lab_ketone_urine as select * from (values
('http://loinc.org', 'LOINC_NUM', 'COMPONENT')
,('http://loinc.org', '31184-5', 'Methyl amyl ketone')
,('http://loinc.org', '31165-4', 'Methyl butyl ketone')
,('http://loinc.org', '31166-2', 'Methyl isoamyl ketone')
,('http://loinc.org', '31167-0', 'Methyl propyl ketone')
,('http://loinc.org', '17269-2', 'Methyl isobutyl ketone')
,('http://loinc.org', '13009-6', 'Methyl ethyl ketone')
,('http://loinc.org', '49779-2', 'Ketones')
,('http://loinc.org', '5797-6', 'Ketones')
,('http://loinc.org', '21236-5', 'Cyclohexanone')
,('http://loinc.org', '50557-8', 'Ketones')
,('http://loinc.org', '12448-7', 'Ketones^post CFst')
,('http://loinc.org', '12451-1', 'Ketones^3H post XXX challenge')
,('http://loinc.org', '12450-3', 'Ketones^2H post XXX challenge')
,('http://loinc.org', '21245-6', 'Diisobutylketone')
,('http://loinc.org', '12449-5', 'Ketones^1H post XXX challenge')
,('http://loinc.org', '25706-3', 'Ketones^2H post dose glucose')
,('http://loinc.org', '25707-1', 'Ketones^4H post dose glucose')
,('http://loinc.org', '5570-7', 'Acetone')
,('http://loinc.org', '35665-9', 'Acetone')
) AS t (system, code, display) ;