create table irae__cohort_lab_tacrolimus as 
select distinct * from 
 irae__cohort_study_population_lab , 
irae__valueset_lab_tacrolimus
WHERE
irae__cohort_study_population_lab.lab_observation_code = irae__valueset_lab_tacrolimus.code and 
irae__cohort_study_population_lab.lab_observation_system = irae__valueset_lab_tacrolimus.system