create or replace view irae__dx_infection_hsv as select * from (values
('http://loinc.org', '103180-6', 'Herpes simplex virus 1 DNA [Presence] in Urine by NAA with probe detection')
,('http://loinc.org', '103181-4', 'Herpes simplex virus 2 DNA [Presence] in Urine by NAA with probe detection')
,('http://loinc.org', '16130-7', 'Herpes simplex virus 1 DNA [Presence] in Specimen by NAA with probe detection')
,('http://loinc.org', '16131-5', 'Herpes simplex virus 2 DNA [Presence] in Specimen by NAA with probe detection')
,('http://loinc.org', '16952-4', 'Herpes simplex virus 1 DNA [Presence] in Cerebral spinal fluid by NAA with probe detection')
,('http://loinc.org', '16953-2', 'Herpes simplex virus 1 DNA [Presence] in Serum or Plasma by NAA with probe detection')
,('http://loinc.org', '16959-9', 'Herpes simplex virus 2 DNA [Presence] in Serum or Plasma by NAA with probe detection')
,('http://loinc.org', '16960-7', 'Herpes simplex virus 2 DNA [Presence] in Cerebral spinal fluid by NAA with probe detection')
,('http://loinc.org', '20444-6', 'Herpes simplex virus 1+2 DNA [Presence] in Specimen by NAA with probe detection')
,('http://loinc.org', '32141-4', 'Herpes simplex virus 1+2 DNA [Presence] in Cerebral spinal fluid by NAA with probe detection')
,('http://loinc.org', '34451-5', 'Herpes simplex virus DNA [Presence] in Blood by NAA with probe detection')
,('http://loinc.org', '34655-1', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Cerebral spinal fluid by NAA with probe detection')
,('http://loinc.org', '44478-6', 'Herpes simplex virus 1 DNA [Presence] in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '44503-1', 'Herpes simplex virus 2 DNA [Presence] in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '44517-1', 'Herpes simplex virus DNA [Presence] in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '44518-9', 'Herpes simplex virus DNA [Presence] in Serum or Plasma by NAA with probe detection')
,('http://loinc.org', '44868-8', 'Herpes simplex virus 1+2 DNA [Presence] in Vaginal fluid by NAA with probe detection')
,('http://loinc.org', '47409-8', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Serum or Plasma by NAA with probe detection')
,('http://loinc.org', '49381-7', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Specimen by NAA with probe detection')
,('http://loinc.org', '49382-5', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Tissue by NAA with probe detection')
,('http://loinc.org', '49383-3', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Urine by NAA with probe detection')
,('http://loinc.org', '49384-1', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Bone marrow by NAA with probe detection')
,('http://loinc.org', '49385-8', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '49386-6', 'Herpes simplex virus 1+2 DNA [#/volume] (viral load) in Bronchoalveolar lavage by NAA with probe detection')
,('http://loinc.org', '49985-5', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Blood by NAA with probe detection')
,('http://loinc.org', '49986-3', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Body fluid by NAA with probe detection')
,('http://loinc.org', '49987-1', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Cerebral spinal fluid by NAA with probe detection')
,('http://loinc.org', '49988-9', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Blood by NAA with probe detection')
,('http://loinc.org', '49989-7', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Body fluid by NAA with probe detection')
,('http://loinc.org', '49990-5', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Cerebral spinal fluid by NAA with probe detection')
,('http://loinc.org', '5013-8', 'Herpes simplex virus DNA [Presence] in Cerebral spinal fluid by NAA with probe detection')
,('http://loinc.org', '5014-6', 'Herpes simplex virus DNA [Presence] in Specimen by NAA with probe detection')
,('http://loinc.org', '50660-0', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Serum or Plasma by NAA with probe detection')
,('http://loinc.org', '50661-8', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Urine by NAA with probe detection')
,('http://loinc.org', '50662-6', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Serum or Plasma by NAA with probe detection')
,('http://loinc.org', '50663-4', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Urine by NAA with probe detection')
,('http://loinc.org', '58414-4', 'Herpes simplex virus 1+2 DNA [Presence] in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '60461-1', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Specimen by NAA with probe detection')
,('http://loinc.org', '60462-9', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Specimen by NAA with probe detection')
,('http://loinc.org', '62470-0', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Bone marrow by NAA with probe detection')
,('http://loinc.org', '62471-8', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Tissue by NAA with probe detection')
,('http://loinc.org', '62472-6', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '62473-4', 'Herpes simplex virus 1 DNA [#/volume] (viral load) in Bronchoalveolar lavage by NAA with probe detection')
,('http://loinc.org', '62474-2', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Bone marrow by NAA with probe detection')
,('http://loinc.org', '62475-9', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Tissue by NAA with probe detection')
,('http://loinc.org', '62476-7', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '62477-5', 'Herpes simplex virus 2 DNA [#/volume] (viral load) in Bronchoalveolar lavage by NAA with probe detection')
,('http://loinc.org', '72838-6', 'Herpes simplex virus DNA [Identifier] in Specimen by NAA with probe detection')
,('http://loinc.org', '80353-6', 'Herpes simplex virus 1 genome DNA polymerase region B+thymidine kinase region C [Presence] in Anogenital specimen by NAA with probe detection')
,('http://loinc.org', '80355-1', 'Herpes simplex virus 2 genome glycoprotein B 3 end region+thymidine kinase region C [Presence] in Anogenital specimen by NAA with probe detection')
,('http://loinc.org', '82190-0', 'Herpes simplex virus 1 DNA [Presence] in Cerebral spinal fluid by NAA with non-probe detection')
,('http://loinc.org', '82191-8', 'Herpes simplex virus 2 DNA [Presence] in Cerebral spinal fluid by NAA with non-probe detection')
,('http://loinc.org', '86539-4', 'Herpes simplex virus 1 DNA [Presence] in Tissue by NAA with probe detection')
,('http://loinc.org', '86541-0', 'Herpes simplex virus 2 DNA [Presence] in Tissue by NAA with probe detection')
,('http://loinc.org', '86542-8', 'Herpes simplex virus DNA [Presence] in Tissue by NAA with probe detection')
,('http://loinc.org', '88128-4', 'Herpes simplex virus 1 DNA [Presence] in Cornea or Conjunctiva by NAA with probe detection')
,('http://loinc.org', '88133-4', 'Herpes simplex virus 2 DNA [Presence] in Cornea or Conjunctiva by NAA with probe detection')
,('http://loinc.org', '88138-3', 'Herpes simplex virus DNA [Presence] in Cornea or Conjunctiva by NAA with probe detection')
,('http://loinc.org', '89584-7', 'Herpes simplex virus DNA [Presence] in Lower respiratory specimen by NAA with probe detection')
,('http://loinc.org', '89585-4', 'Herpes simplex virus 1 DNA [Presence] in Lower respiratory specimen by NAA with probe detection')
,('http://loinc.org', '89587-0', 'Herpes simplex virus 2 DNA [Presence] in Lower respiratory specimen by NAA with probe detection')
,('http://loinc.org', '90450-8', 'Herpes simplex virus DNA [Presence] in Aspirate by NAA with probe detection')
,('http://loinc.org', '90451-6', 'Herpes simplex virus 1 DNA [Presence] in Aspirate by NAA with probe detection')
,('http://loinc.org', '90452-4', 'Herpes simplex virus 1 DNA [Presence] in Upper respiratory specimen by NAA with probe detection')
,('http://loinc.org', '90453-2', 'Herpes simplex virus 2 DNA [Presence] in Aspirate by NAA with probe detection')
,('http://loinc.org', '90454-0', 'Herpes simplex virus 2 DNA [Presence] in Upper respiratory specimen by NAA with probe detection')
,('http://loinc.org', '91857-3', 'Herpes simplex virus DNA [Presence] in Genital specimen by NAA with probe detection')
,('http://loinc.org', '91858-1', 'Herpes simplex virus 2 DNA [Presence] in Genital specimen by NAA with probe detection')
,('http://loinc.org', '91859-9', 'Herpes simplex virus 1 DNA [Presence] in Genital specimen by NAA with probe detection')
,('http://loinc.org', '92870-5', 'Herpes simplex virus 1 DNA [Presence] in Blood by NAA with probe detection')
,('http://loinc.org', '92871-3', 'Herpes simplex virus 1 DNA [Presence] in Skin by NAA with probe detection')
,('http://loinc.org', '92872-1', 'Herpes simplex virus 1 DNA [Presence] in Anogenital by NAA with probe detection')
,('http://loinc.org', '92873-9', 'Herpes simplex virus 2 DNA [Presence] in Blood by NAA with probe detection')
,('http://loinc.org', '92874-7', 'Herpes simplex virus 2 DNA [Presence] in Skin by NAA with probe detection')
,('http://loinc.org', '92875-4', 'Herpes simplex virus 2 DNA [Presence] in Anogenital by NAA with probe detection')
,('http://loinc.org', '93438-0', 'Herpes simplex virus 2 DNA [Presence] in Blood by NAA with non-probe detection')
,('http://loinc.org', '93439-8', 'Herpes simplex virus 1 DNA [Presence] in Blood by NAA with non-probe detection')
,('http://loinc.org', '94581-6', 'Herpes simplex virus 1 DNA [Presence] in Specimen by NAA with non-probe detection')
,('http://loinc.org', '94582-4', 'Herpes simplex virus 2 DNA [Presence] in Specimen by NAA with non-probe detection')
,('http://loinc.org', '94834-9', 'Herpes simplex virus 1+2 DNA [Log #/volume] (viral load) in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '94835-6', 'Herpes simplex virus 1 DNA [Log #/volume] (viral load) in Amniotic fluid by NAA with probe detection')
,('http://loinc.org', '94836-4', 'Herpes simplex virus 2 DNA [Log #/volume] (viral load) in Amniotic fluid by NAA with probe detection')
) AS t (system, code, display) ;