create or replace view irae__rx_tacrolimus as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', 'code', 'display')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108513', 'Prograf 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108513', 'tacrolimus 1 MG Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108514', 'Prograf 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108514', 'tacrolimus 5 MG Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108515', '1 ML tacrolimus 5 MG/ML Injection [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108515', 'Prograf 5 MG in 1 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '108515', 'Prograf 5 MG per 1 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163655', 'tacrolimus Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164202', 'tacrolimus Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164203', 'tacrolimus Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164204', 'tacrolimus Topical Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180662', 'Prograf Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180663', 'Prograf Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1180664', 'Prograf Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431970', 'tacrolimus Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431971', '24 HR tacrolimus 0.5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431971', 'tacrolimus 0.5 MG (as anhydrous tacrolimus) 24 HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431971', 'tacrolimus 0.5 MG 24HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431973', 'tacrolimus 0.5 MG [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431974', 'tacrolimus Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431977', '24 HR tacrolimus 0.5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431980', '24 HR tacrolimus 1 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431980', 'tacrolimus 1 MG (as anhydrous tacrolimus) 24 HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431980', 'tacrolimus 1 MG 24HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431981', 'tacrolimus 1 MG [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431982', '24 HR tacrolimus 1 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431982', 'Astagraf XL 1 MG (as anhydrous tacrolimus) 24 HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431985', '24 HR tacrolimus 5 MG Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431985', 'tacrolimus 5 MG (as anhydrous tacrolimus) 24 HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431985', 'tacrolimus 5 MG 24HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431986', 'tacrolimus 5 MG [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431987', '24 HR tacrolimus 5 MG Extended Release Oral Capsule [Astagraf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431987', 'Astagraf XL 5 MG (as anhydrous tacrolimus) 24 HR Extended Release Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664432', 'tacrolimus 4 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664433', 'tacrolimus Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664434', '24 HR tacrolimus 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664434', 'tacrolimus 4 MG (as anhydrous tacrolimus) 24HR Extended Release Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664434', 'tacrolimus 4 MG 24HR Extended Release Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664435', 'Envarsus')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664436', 'tacrolimus 4 MG [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664437', 'tacrolimus Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664438', 'Envarsus Oral Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664439', 'Envarsus Pill')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664440', '24 HR Envarsus 4 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664440', '24 HR tacrolimus 4 MG Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664440', 'Envarsus XR 4 MG 24HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664455', 'tacrolimus 0.75 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664456', '24 HR tacrolimus 0.75 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664456', 'tacrolimus 0.75 MG (as anhydrous tacrolimus) 24 HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664456', 'tacrolimus 0.75 MG 24HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664457', 'tacrolimus 0.75 MG [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664458', '24 HR Envarsus 0.75 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664458', '24 HR tacrolimus 0.75 MG Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664458', 'Envarsus XR 0.75 MG 24HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664461', '24 HR tacrolimus 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664461', 'tacrolimus 1 MG (as anhydrous tacrolimus) 24 HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664461', 'tacrolimus 1 MG 24HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664462', 'tacrolimus 1 MG [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664463', '24 HR Envarsus 1 MG Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664463', '24 HR tacrolimus 1 MG Extended Release Oral Tablet [Envarsus]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1664463', 'Envarsus XR 1 MG 24HR Extended Release Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738334', 'tacrolimus Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1738336', 'tacrolimus Injection [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '196463', 'Prograf')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198377', 'tacrolimus 1 MG (as anhydrous tacrolimus) Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198377', 'tacrolimus 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198378', 'tacrolimus 5 MG (as anhydrous tacrolimus) Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198378', 'tacrolimus 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198379', '1 ML tacrolimus 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198379', 'tacrolimus 5 MG in 1 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198379', 'tacrolimus 5 MG per 1 ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052503', 'tacrolimus 0.2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052603', 'tacrolimus Granule Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052604', 'tacrolimus Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052605', 'tacrolimus 0.2 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052606', 'tacrolimus 0.2 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052607', 'tacrolimus Granules for Oral Suspension [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052608', 'Prograf Granule Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052609', 'Prograf 0.2 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052609', 'tacrolimus 0.2 MG Granules for Oral Suspension [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052703', 'tacrolimus 1 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052704', 'Prograf 1 MG Granules for Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2052704', 'tacrolimus 1 MG Granules for Oral Suspension [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '235991', 'anhydrous tacrolimus')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261134', 'Prograf 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '261134', 'tacrolimus 0.5 MG Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665161', 'BX Rating tacrolimus 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665161', 'tacrolimus 0.5 MG Oral Capsule, BX Rating')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665162', 'BX Rating tacrolimus 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665162', 'tacrolimus 1 MG Oral Capsule, BX Rating')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665163', 'BX Rating tacrolimus 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2665163', 'tacrolimus 5 MG Oral Capsule, BX Rating')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284520', 'tacrolimus 0.001 MG/MG Topical Ointment [Protopic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '284521', 'tacrolimus 0.0003 MG/MG Topical Ointment [Protopic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313189', 'tacrolimus (as tacrolimus monohydrate) 0.0003 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313189', 'tacrolimus 0.0003 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313189', 'tacrolimus 0.03 % Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313190', 'tacrolimus 0.5 MG (as anhydrous tacrolimus) Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313190', 'tacrolimus 0.5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314266', 'tacrolimus (as tacrolimus monohydrate) 0.001 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314266', 'tacrolimus 0.001 MG/MG Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314266', 'tacrolimus 0.1 % Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316758', 'tacrolimus 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '316759', 'tacrolimus 5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317510', 'tacrolimus 5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '330404', 'tacrolimus 0.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '331549', 'tacrolimus 0.001 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '331550', 'tacrolimus 0.0003 MG/MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '366273', 'tacrolimus Oral Capsule [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '367339', 'tacrolimus Topical Ointment [Protopic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374015', 'tacrolimus Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '379082', 'tacrolimus Topical Ointment')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '42316', 'tacrolimus')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484288', 'tacrolimus monohydrate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564557', 'tacrolimus 1 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564558', 'tacrolimus 5 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '564559', 'tacrolimus 5 MG/ML [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574378', 'tacrolimus 0.5 MG [Prograf]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574948', 'tacrolimus 0.001 MG/MG [Protopic]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '574949', 'tacrolimus 0.0003 MG/MG [Protopic]')
) AS t (system, code, display) ;