create or replace view irae__dx_diabetes_t1d as select * from (values
('http://snomed.info/sct', '102781000119107', 'Sensory neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '104941000119109', 'Ischemia of retina due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '104951000119106', 'Vitreous hemorrhage due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '10656231000119100', 'Ulcer of skin of toe due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '109171000119104', 'Retinal edema due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '110141000119100', 'Ulcer of lower limb due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1196923000', 'Neovascular glaucoma due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '120711000119108', 'Hypoglycemic unawareness due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1217068008', 'Fulminant type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1255271005', 'Juvenile-onset diabetes mellitus, central and peripheral neurodegeneration syndrome (disorder)')
,('http://snomed.info/sct', '128001000119105', 'Hypertension concurrent and due to end stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1285518004', 'Wolfram syndrome type 1 (disorder)')
,('http://snomed.info/sct', '1285519007', 'Wolfram syndrome type 2 (disorder)')
,('http://snomed.info/sct', '1290118005', 'Presymptomatic diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '1332436006', 'Hypertension in chronic kidney disease stage 3B due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332441003', 'Hypertension in chronic kidney disease stage 3A due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332442005', 'Hypertension in chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332464001', 'Hypertension in chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332467008', 'Hypertension in chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332468003', 'Hypertension in chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332471006', 'Chronic kidney disease stage 3B due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '1332472004', 'Chronic kidney disease stage 3A due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '137941000119106', 'Hyperlipidemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138881000119106', 'Mild nonproliferative retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138891000119109', 'Moderate nonproliferative retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '138901000119108', 'Severe nonproliferative retinopathy due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '1571000119104', 'Mixed hyperlipidemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '164881000119109', 'Ulcer of foot due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '16697421000119103', 'Moderate nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16697471000119102', 'Moderate nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16697521000119104', 'Moderate nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745211000119100', 'Nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745411000119104', 'Mild nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745611000119102', 'Mild nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16745891000119105', 'Mild nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16746661000119106', 'Nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16746741000119102', 'Nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16746941000119104', 'Severe nonproliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16747101000119101', 'Severe nonproliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16747341000119101', 'Severe nonproliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16747741000119100', 'Proliferative retinopathy of left eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16748741000119101', 'Proliferative retinopathy of right eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16749781000119101', 'Proliferative retinopathy of bilateral eyes due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '16891191000119108', 'Coronary artery disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '18521000119106', 'Microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '190330002', 'Hyperosmolar coma due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '190368000', 'Type I diabetes mellitus with ulcer (disorder)')
,('http://snomed.info/sct', '190372001', 'Type I diabetes mellitus maturity onset (disorder)')
,('http://snomed.info/sct', '199229001', 'Pre-existing type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '23045005', 'Insulin dependent diabetes mellitus type IA (disorder)')
,('http://snomed.info/sct', '243421000119104', 'Proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '28032008', 'Insulin dependent diabetes mellitus type IB (disorder)')
,('http://snomed.info/sct', '290002008', 'Brittle type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '31211000119101', 'Peripheral angiopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '31321000119102', 'Diabetes mellitus type 1 without retinopathy (disorder)')
,('http://snomed.info/sct', '314893005', 'Arthropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '367211000119103', 'Inflammatory dermatosis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '367991000119101', 'Hyperglycemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368521000119107', 'Disorder of nerve co-occurrent and due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368541000119101', 'Cheiroarthropathy due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '368551000119104', 'Dyslipidemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '368561000119102', 'Hyperosmolarity due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420270002', 'Ketoacidosis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420486006', 'Exudative maculopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420514000', 'Persistent proteinuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420789003', 'Retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420825003', 'Gangrene due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420868002', 'Disorder due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '420918009', 'Mononeuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421075007', 'Ketoacidotic coma due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421305000', 'Persistent microalbuminuria due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421365002', 'Peripheral circulatory disorder due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421437000', 'Hypoglycemic coma due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421468001', 'Disorder of nervous system due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421893009', 'Renal disorder due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '421920002', 'Cataract of eye due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '426875007', 'Latent autoimmune diabetes mellitus in adult (disorder)')
,('http://snomed.info/sct', '426907004', 'Small vessel disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '427571000', 'Lumbosacral radiculoplexus neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '428896009', 'Hyperosmolality due to uncontrolled type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '444073006', 'Uncontrolled type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '444074000', 'Well controlled type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '46635009', 'Diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '609564002', 'Pre-existing type 1 diabetes mellitus in pregnancy (disorder)')
,('http://snomed.info/sct', '609566000', 'Pregnancy and type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '60961000119107', 'Nonproliferative diabetic retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '60971000119101', 'Proliferative retinopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '60981000119103', 'Glaucoma due to diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '60991000119100', 'Blindness due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '691000119103', 'Erectile dysfunction due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '703137001', 'Type I diabetes mellitus in remission (disorder)')
,('http://snomed.info/sct', '706891008', 'Neuropathy due to unstable diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '706894000', 'Retinopathy due to unstable diabetes mellitus type 1 (disorder)')
,('http://snomed.info/sct', '70694009', 'Wolfram syndrome (disorder)')
,('http://snomed.info/sct', '712882000', 'Autonomic neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713702000', 'Gastroparesis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '713705003', 'Polyneuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '716020005', 'Diabetic embryopathy (disorder)')
,('http://snomed.info/sct', '71701000119105', 'Hypertension in chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71721000119101', 'Nephrotic syndrome due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71771000119100', 'Neuropathic arthropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '71791000119104', 'Peripheral neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72021000119109', 'Dermopathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72031000119107', 'Severe malnutrition due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72041000119103', 'Osteomyelitis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '721111000124107', 'Diabetes mellitus type 1 stage 1 (disorder)')
,('http://snomed.info/sct', '721121000124104', 'Diabetes mellitus type 1 stage 2 (disorder)')
,('http://snomed.info/sct', '721201000124104', 'Diabetes mellitus type 1 stage 3 (disorder)')
,('http://snomed.info/sct', '721283000', 'Acidosis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '72141000119104', 'Chronic ulcer of skin due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '722454003', 'Intellectual disability, craniofacial dysmorphism, hypogonadism, diabetes mellitus syndrome (disorder)')
,('http://snomed.info/sct', '739681000', 'Disorder of eye due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '769219006', 'Macular edema due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '770098001', 'Cranial nerve palsy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789542009', 'Neuropathy due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789571005', 'Ulcer of heel due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '789572003', 'Ulcer of midfoot due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '82571000119107', 'Traction detachment of retina due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '82581000119105', 'Rubeosis iridis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '84371000119108', 'Hypoglycemia due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '870528001', 'Newly diagnosed type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '87471000119106', 'Ulcer of ankle due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '87491000119107', 'Ulcer of forefoot due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90721000119101', 'Chronic kidney disease stage 1 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90731000119103', 'Chronic kidney disease stage 2 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90741000119107', 'Chronic kidney disease stage 3 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90751000119109', 'Chronic kidney disease stage 4 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90761000119106', 'Chronic kidney disease stage 5 due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '90771000119100', 'End stage renal disease on dialysis due to type 1 diabetes mellitus (disorder)')
,('http://snomed.info/sct', '96441000119101', 'Chronic kidney disease due to type 1 diabetes mellitus (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.10', 'Type 1 diabetes mellitus with ketoacidosis without coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.11', 'Type 1 diabetes mellitus with ketoacidosis with coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.21', 'Type 1 diabetes mellitus with diabetic nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.22', 'Type 1 diabetes mellitus with diabetic chronic kidney disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.29', 'Type 1 diabetes mellitus with other diabetic kidney complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.311', 'Type 1 diabetes mellitus with unspecified diabetic retinopathy with macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.319', 'Type 1 diabetes mellitus with unspecified diabetic retinopathy without macular edema')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3211', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3212', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3213', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3219', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3291', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3292', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3293', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3299', 'Type 1 diabetes mellitus with mild nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3311', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3312', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3313', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3319', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3391', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3392', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3393', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3399', 'Type 1 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3411', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3412', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3413', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3419', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3491', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3492', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3493', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3499', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3511', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3512', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3513', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3519', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3521', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3522', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3523', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3529', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment involving the macula, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3531', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3532', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3533', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3539', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with traction retinal detachment not involving the macula, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3541', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3542', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3543', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3549', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy with combined traction retinal detachment and rhegmatogenous retinal detachment, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3551', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3552', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3553', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3559', 'Type 1 diabetes mellitus with stable proliferative diabetic retinopathy, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3591', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3592', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3593', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.3599', 'Type 1 diabetes mellitus with proliferative diabetic retinopathy without macular edema, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.36', 'Type 1 diabetes mellitus with diabetic cataract')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X1', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, right eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X2', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, left eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X3', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, bilateral')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.37X9', 'Type 1 diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.39', 'Type 1 diabetes mellitus with other diabetic ophthalmic complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.40', 'Type 1 diabetes mellitus with diabetic neuropathy, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.41', 'Type 1 diabetes mellitus with diabetic mononeuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.42', 'Type 1 diabetes mellitus with diabetic polyneuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.43', 'Type 1 diabetes mellitus with diabetic autonomic (poly)neuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.44', 'Type 1 diabetes mellitus with diabetic amyotrophy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.49', 'Type 1 diabetes mellitus with other diabetic neurological complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.51', 'Type 1 diabetes mellitus with diabetic peripheral angiopathy without gangrene')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.52', 'Type 1 diabetes mellitus with diabetic peripheral angiopathy with gangrene')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.59', 'Type 1 diabetes mellitus with other circulatory complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.610', 'Type 1 diabetes mellitus with diabetic neuropathic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.618', 'Type 1 diabetes mellitus with other diabetic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.620', 'Type 1 diabetes mellitus with diabetic dermatitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.621', 'Type 1 diabetes mellitus with foot ulcer')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.622', 'Type 1 diabetes mellitus with other skin ulcer')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.628', 'Type 1 diabetes mellitus with other skin complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.630', 'Type 1 diabetes mellitus with periodontal disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.638', 'Type 1 diabetes mellitus with other oral complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.641', 'Type 1 diabetes mellitus with hypoglycemia with coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.649', 'Type 1 diabetes mellitus with hypoglycemia without coma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.65', 'Type 1 diabetes mellitus with hyperglycemia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.69', 'Type 1 diabetes mellitus with other specified complication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.8', 'Type 1 diabetes mellitus with unspecified complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.9', 'Type 1 diabetes mellitus without complications')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.A0', 'Type 1 diabetes mellitus, presymptomatic, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.A1', 'Type 1 diabetes mellitus, presymptomatic, Stage 1')
,('http://hl7.org/fhir/sid/icd-10-cm', 'E10.A2', 'Type 1 diabetes mellitus, presymptomatic, Stage 2')
) AS t (system, code, display) ;