create or replace view irae__dx_autoimmune_inflammatory as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'G04.00', 'Acute disseminated encephalitis and encephalomyelitis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.01', 'Postinfectious acute disseminated encephalitis and encephalomyelitis (postinfectious ADEM)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.02', 'Postimmunization acute disseminated encephalitis, myelitis and encephalomyelitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.30', 'Acute necrotizing hemorrhagic encephalopathy, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.31', 'Postinfectious acute necrotizing hemorrhagic encephalopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.39', 'Other acute necrotizing hemorrhagic encephalopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.81', 'Other encephalitis and encephalomyelitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.89', 'Other myelitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.90', 'Encephalitis and encephalomyelitis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G04.91', 'Myelitis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G05.4', 'Myelitis in diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G35', 'Multiple sclerosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G36.0', 'Neuromyelitis optica [Devic]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G36.1', 'Acute and subacute hemorrhagic leukoencephalitis [Hurst]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G36.8', 'Other specified acute disseminated demyelination')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G36.9', 'Acute disseminated demyelination, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.0', 'Diffuse sclerosis of central nervous system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.1', 'Central demyelination of corpus callosum')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.2', 'Central pontine myelinolysis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.3', 'Acute transverse myelitis in demyelinating disease of central nervous system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.4', 'Subacute necrotizing myelitis of central nervous system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.5', 'Concentric sclerosis [Balo] of central nervous system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.8', 'Other specified demyelinating diseases of central nervous system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G37.9', 'Demyelinating disease of central nervous system, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'G61.0', 'Guillain-Barre syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L40.50', 'Arthropathic psoriasis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L40.51', 'Distal interphalangeal psoriatic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L40.52', 'Psoriatic arthritis mutilans')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L40.53', 'Psoriatic spondylitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L40.54', 'Psoriatic juvenile arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L40.59', 'Other psoriatic arthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L90.0', 'Lichen sclerosus et atrophicus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L94.0', 'Localized scleroderma [morphea]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L94.1', 'Linear scleroderma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'L94.3', 'Sclerodactyly')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.00', 'Feltys syndrome, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.011', 'Feltys syndrome, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.012', 'Feltys syndrome, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.019', 'Feltys syndrome, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.021', 'Feltys syndrome, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.022', 'Feltys syndrome, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.029', 'Feltys syndrome, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.031', 'Feltys syndrome, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.032', 'Feltys syndrome, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.039', 'Feltys syndrome, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.041', 'Feltys syndrome, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.042', 'Feltys syndrome, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.049', 'Feltys syndrome, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.051', 'Feltys syndrome, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.052', 'Feltys syndrome, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.059', 'Feltys syndrome, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.061', 'Feltys syndrome, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.062', 'Feltys syndrome, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.069', 'Feltys syndrome, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.071', 'Feltys syndrome, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.072', 'Feltys syndrome, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.079', 'Feltys syndrome, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.09', 'Feltys syndrome, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.10', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.111', 'Rheumatoid lung disease with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.112', 'Rheumatoid lung disease with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.119', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.121', 'Rheumatoid lung disease with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.122', 'Rheumatoid lung disease with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.129', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.131', 'Rheumatoid lung disease with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.132', 'Rheumatoid lung disease with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.139', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.141', 'Rheumatoid lung disease with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.142', 'Rheumatoid lung disease with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.149', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.151', 'Rheumatoid lung disease with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.152', 'Rheumatoid lung disease with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.159', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.161', 'Rheumatoid lung disease with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.162', 'Rheumatoid lung disease with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.169', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.171', 'Rheumatoid lung disease with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.172', 'Rheumatoid lung disease with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.179', 'Rheumatoid lung disease with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.19', 'Rheumatoid lung disease with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.20', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.211', 'Rheumatoid vasculitis with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.212', 'Rheumatoid vasculitis with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.219', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.221', 'Rheumatoid vasculitis with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.222', 'Rheumatoid vasculitis with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.229', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.231', 'Rheumatoid vasculitis with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.232', 'Rheumatoid vasculitis with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.239', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.241', 'Rheumatoid vasculitis with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.242', 'Rheumatoid vasculitis with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.249', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.251', 'Rheumatoid vasculitis with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.252', 'Rheumatoid vasculitis with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.259', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.261', 'Rheumatoid vasculitis with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.262', 'Rheumatoid vasculitis with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.269', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.271', 'Rheumatoid vasculitis with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.272', 'Rheumatoid vasculitis with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.279', 'Rheumatoid vasculitis with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.29', 'Rheumatoid vasculitis with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.30', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.311', 'Rheumatoid heart disease with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.312', 'Rheumatoid heart disease with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.319', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.321', 'Rheumatoid heart disease with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.322', 'Rheumatoid heart disease with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.329', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.331', 'Rheumatoid heart disease with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.332', 'Rheumatoid heart disease with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.339', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.341', 'Rheumatoid heart disease with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.342', 'Rheumatoid heart disease with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.349', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.351', 'Rheumatoid heart disease with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.352', 'Rheumatoid heart disease with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.359', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.361', 'Rheumatoid heart disease with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.362', 'Rheumatoid heart disease with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.369', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.371', 'Rheumatoid heart disease with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.372', 'Rheumatoid heart disease with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.379', 'Rheumatoid heart disease with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.39', 'Rheumatoid heart disease with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.40', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.411', 'Rheumatoid myopathy with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.412', 'Rheumatoid myopathy with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.419', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.421', 'Rheumatoid myopathy with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.422', 'Rheumatoid myopathy with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.429', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.431', 'Rheumatoid myopathy with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.432', 'Rheumatoid myopathy with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.439', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.441', 'Rheumatoid myopathy with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.442', 'Rheumatoid myopathy with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.449', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.451', 'Rheumatoid myopathy with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.452', 'Rheumatoid myopathy with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.459', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.461', 'Rheumatoid myopathy with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.462', 'Rheumatoid myopathy with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.469', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.471', 'Rheumatoid myopathy with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.472', 'Rheumatoid myopathy with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.479', 'Rheumatoid myopathy with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.49', 'Rheumatoid myopathy with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.50', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.511', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.512', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.519', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.521', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.522', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.529', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.531', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.532', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.539', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.541', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.542', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.549', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.551', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.552', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.559', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.561', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.562', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.569', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.571', 'Rheumatoid polyneuropathy with rheumatoid arthritis of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.572', 'Rheumatoid polyneuropathy with rheumatoid arthritis of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.579', 'Rheumatoid polyneuropathy with rheumatoid arthritis of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.59', 'Rheumatoid polyneuropathy with rheumatoid arthritis of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.60', 'Rheumatoid arthritis of unspecified site with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.611', 'Rheumatoid arthritis of right shoulder with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.612', 'Rheumatoid arthritis of left shoulder with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.619', 'Rheumatoid arthritis of unspecified shoulder with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.621', 'Rheumatoid arthritis of right elbow with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.622', 'Rheumatoid arthritis of left elbow with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.629', 'Rheumatoid arthritis of unspecified elbow with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.631', 'Rheumatoid arthritis of right wrist with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.632', 'Rheumatoid arthritis of left wrist with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.639', 'Rheumatoid arthritis of unspecified wrist with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.641', 'Rheumatoid arthritis of right hand with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.642', 'Rheumatoid arthritis of left hand with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.649', 'Rheumatoid arthritis of unspecified hand with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.651', 'Rheumatoid arthritis of right hip with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.652', 'Rheumatoid arthritis of left hip with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.659', 'Rheumatoid arthritis of unspecified hip with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.661', 'Rheumatoid arthritis of right knee with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.662', 'Rheumatoid arthritis of left knee with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.669', 'Rheumatoid arthritis of unspecified knee with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.671', 'Rheumatoid arthritis of right ankle and foot with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.672', 'Rheumatoid arthritis of left ankle and foot with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.679', 'Rheumatoid arthritis of unspecified ankle and foot with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.69', 'Rheumatoid arthritis of multiple sites with involvement of other organs and systems')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.70', 'Rheumatoid arthritis with rheumatoid factor of unspecified site without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.711', 'Rheumatoid arthritis with rheumatoid factor of right shoulder without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.712', 'Rheumatoid arthritis with rheumatoid factor of left shoulder without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.719', 'Rheumatoid arthritis with rheumatoid factor of unspecified shoulder without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.721', 'Rheumatoid arthritis with rheumatoid factor of right elbow without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.722', 'Rheumatoid arthritis with rheumatoid factor of left elbow without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.729', 'Rheumatoid arthritis with rheumatoid factor of unspecified elbow without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.731', 'Rheumatoid arthritis with rheumatoid factor of right wrist without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.732', 'Rheumatoid arthritis with rheumatoid factor of left wrist without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.739', 'Rheumatoid arthritis with rheumatoid factor of unspecified wrist without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.741', 'Rheumatoid arthritis with rheumatoid factor of right hand without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.742', 'Rheumatoid arthritis with rheumatoid factor of left hand without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.749', 'Rheumatoid arthritis with rheumatoid factor of unspecified hand without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.751', 'Rheumatoid arthritis with rheumatoid factor of right hip without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.752', 'Rheumatoid arthritis with rheumatoid factor of left hip without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.759', 'Rheumatoid arthritis with rheumatoid factor of unspecified hip without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.761', 'Rheumatoid arthritis with rheumatoid factor of right knee without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.762', 'Rheumatoid arthritis with rheumatoid factor of left knee without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.769', 'Rheumatoid arthritis with rheumatoid factor of unspecified knee without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.771', 'Rheumatoid arthritis with rheumatoid factor of right ankle and foot without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.772', 'Rheumatoid arthritis with rheumatoid factor of left ankle and foot without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.779', 'Rheumatoid arthritis with rheumatoid factor of unspecified ankle and foot without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.79', 'Rheumatoid arthritis with rheumatoid factor of multiple sites without organ or systems involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.80', 'Other rheumatoid arthritis with rheumatoid factor of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.821', 'Other rheumatoid arthritis with rheumatoid factor of right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.822', 'Other rheumatoid arthritis with rheumatoid factor of left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.829', 'Other rheumatoid arthritis with rheumatoid factor of unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.831', 'Other rheumatoid arthritis with rheumatoid factor of right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.832', 'Other rheumatoid arthritis with rheumatoid factor of left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.839', 'Other rheumatoid arthritis with rheumatoid factor of unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.841', 'Other rheumatoid arthritis with rheumatoid factor of right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.842', 'Other rheumatoid arthritis with rheumatoid factor of left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.849', 'Other rheumatoid arthritis with rheumatoid factor of unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.851', 'Other rheumatoid arthritis with rheumatoid factor of right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.852', 'Other rheumatoid arthritis with rheumatoid factor of left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.859', 'Other rheumatoid arthritis with rheumatoid factor of unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.861', 'Other rheumatoid arthritis with rheumatoid factor of right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.862', 'Other rheumatoid arthritis with rheumatoid factor of left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.869', 'Other rheumatoid arthritis with rheumatoid factor of unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.871', 'Other rheumatoid arthritis with rheumatoid factor of right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.872', 'Other rheumatoid arthritis with rheumatoid factor of left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.879', 'Other rheumatoid arthritis with rheumatoid factor of unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.89', 'Other rheumatoid arthritis with rheumatoid factor of multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M05.9', 'Rheumatoid arthritis with rheumatoid factor, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.00', 'Rheumatoid arthritis without rheumatoid factor, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.011', 'Rheumatoid arthritis without rheumatoid factor, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.012', 'Rheumatoid arthritis without rheumatoid factor, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.019', 'Rheumatoid arthritis without rheumatoid factor, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.021', 'Rheumatoid arthritis without rheumatoid factor, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.022', 'Rheumatoid arthritis without rheumatoid factor, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.029', 'Rheumatoid arthritis without rheumatoid factor, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.031', 'Rheumatoid arthritis without rheumatoid factor, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.032', 'Rheumatoid arthritis without rheumatoid factor, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.039', 'Rheumatoid arthritis without rheumatoid factor, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.041', 'Rheumatoid arthritis without rheumatoid factor, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.042', 'Rheumatoid arthritis without rheumatoid factor, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.049', 'Rheumatoid arthritis without rheumatoid factor, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.051', 'Rheumatoid arthritis without rheumatoid factor, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.052', 'Rheumatoid arthritis without rheumatoid factor, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.059', 'Rheumatoid arthritis without rheumatoid factor, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.061', 'Rheumatoid arthritis without rheumatoid factor, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.062', 'Rheumatoid arthritis without rheumatoid factor, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.069', 'Rheumatoid arthritis without rheumatoid factor, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.071', 'Rheumatoid arthritis without rheumatoid factor, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.072', 'Rheumatoid arthritis without rheumatoid factor, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.079', 'Rheumatoid arthritis without rheumatoid factor, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.08', 'Rheumatoid arthritis without rheumatoid factor, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.09', 'Rheumatoid arthritis without rheumatoid factor, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.1', 'Adult-onset Stills disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.20', 'Rheumatoid bursitis, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.211', 'Rheumatoid bursitis, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.212', 'Rheumatoid bursitis, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.219', 'Rheumatoid bursitis, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.221', 'Rheumatoid bursitis, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.222', 'Rheumatoid bursitis, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.229', 'Rheumatoid bursitis, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.231', 'Rheumatoid bursitis, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.232', 'Rheumatoid bursitis, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.239', 'Rheumatoid bursitis, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.241', 'Rheumatoid bursitis, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.242', 'Rheumatoid bursitis, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.249', 'Rheumatoid bursitis, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.251', 'Rheumatoid bursitis, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.252', 'Rheumatoid bursitis, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.259', 'Rheumatoid bursitis, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.261', 'Rheumatoid bursitis, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.262', 'Rheumatoid bursitis, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.269', 'Rheumatoid bursitis, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.271', 'Rheumatoid bursitis, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.272', 'Rheumatoid bursitis, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.279', 'Rheumatoid bursitis, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.28', 'Rheumatoid bursitis, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.29', 'Rheumatoid bursitis, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.30', 'Rheumatoid nodule, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.311', 'Rheumatoid nodule, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.312', 'Rheumatoid nodule, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.319', 'Rheumatoid nodule, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.321', 'Rheumatoid nodule, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.322', 'Rheumatoid nodule, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.329', 'Rheumatoid nodule, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.331', 'Rheumatoid nodule, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.332', 'Rheumatoid nodule, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.339', 'Rheumatoid nodule, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.341', 'Rheumatoid nodule, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.342', 'Rheumatoid nodule, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.349', 'Rheumatoid nodule, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.351', 'Rheumatoid nodule, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.352', 'Rheumatoid nodule, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.359', 'Rheumatoid nodule, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.361', 'Rheumatoid nodule, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.362', 'Rheumatoid nodule, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.369', 'Rheumatoid nodule, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.371', 'Rheumatoid nodule, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.372', 'Rheumatoid nodule, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.379', 'Rheumatoid nodule, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.38', 'Rheumatoid nodule, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.39', 'Rheumatoid nodule, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.4', 'Inflammatory polyarthropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.811', 'Other specified rheumatoid arthritis, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.812', 'Other specified rheumatoid arthritis, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.819', 'Other specified rheumatoid arthritis, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.821', 'Other specified rheumatoid arthritis, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.822', 'Other specified rheumatoid arthritis, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.829', 'Other specified rheumatoid arthritis, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.831', 'Other specified rheumatoid arthritis, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.832', 'Other specified rheumatoid arthritis, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.839', 'Other specified rheumatoid arthritis, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.841', 'Other specified rheumatoid arthritis, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.842', 'Other specified rheumatoid arthritis, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.849', 'Other specified rheumatoid arthritis, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.851', 'Other specified rheumatoid arthritis, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.852', 'Other specified rheumatoid arthritis, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.859', 'Other specified rheumatoid arthritis, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.861', 'Other specified rheumatoid arthritis, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.862', 'Other specified rheumatoid arthritis, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.869', 'Other specified rheumatoid arthritis, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.871', 'Other specified rheumatoid arthritis, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.872', 'Other specified rheumatoid arthritis, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.879', 'Other specified rheumatoid arthritis, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.88', 'Other specified rheumatoid arthritis, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.89', 'Other specified rheumatoid arthritis, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M06.9', 'Rheumatoid arthritis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.611', 'Enteropathic arthropathies, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.612', 'Enteropathic arthropathies, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.619', 'Enteropathic arthropathies, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.621', 'Enteropathic arthropathies, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.622', 'Enteropathic arthropathies, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.629', 'Enteropathic arthropathies, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.631', 'Enteropathic arthropathies, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.632', 'Enteropathic arthropathies, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.639', 'Enteropathic arthropathies, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.641', 'Enteropathic arthropathies, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.642', 'Enteropathic arthropathies, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.649', 'Enteropathic arthropathies, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.651', 'Enteropathic arthropathies, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.652', 'Enteropathic arthropathies, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.659', 'Enteropathic arthropathies, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.661', 'Enteropathic arthropathies, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.662', 'Enteropathic arthropathies, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.669', 'Enteropathic arthropathies, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.671', 'Enteropathic arthropathies, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.672', 'Enteropathic arthropathies, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.679', 'Enteropathic arthropathies, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.68', 'Enteropathic arthropathies, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M07.69', 'Enteropathic arthropathies, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.00', 'Unspecified juvenile rheumatoid arthritis of unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.011', 'Unspecified juvenile rheumatoid arthritis, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.012', 'Unspecified juvenile rheumatoid arthritis, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.019', 'Unspecified juvenile rheumatoid arthritis, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.021', 'Unspecified juvenile rheumatoid arthritis, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.022', 'Unspecified juvenile rheumatoid arthritis, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.029', 'Unspecified juvenile rheumatoid arthritis, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.031', 'Unspecified juvenile rheumatoid arthritis, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.032', 'Unspecified juvenile rheumatoid arthritis, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.039', 'Unspecified juvenile rheumatoid arthritis, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.041', 'Unspecified juvenile rheumatoid arthritis, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.042', 'Unspecified juvenile rheumatoid arthritis, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.049', 'Unspecified juvenile rheumatoid arthritis, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.051', 'Unspecified juvenile rheumatoid arthritis, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.052', 'Unspecified juvenile rheumatoid arthritis, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.059', 'Unspecified juvenile rheumatoid arthritis, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.061', 'Unspecified juvenile rheumatoid arthritis, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.062', 'Unspecified juvenile rheumatoid arthritis, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.069', 'Unspecified juvenile rheumatoid arthritis, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.071', 'Unspecified juvenile rheumatoid arthritis, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.072', 'Unspecified juvenile rheumatoid arthritis, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.079', 'Unspecified juvenile rheumatoid arthritis, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.08', 'Unspecified juvenile rheumatoid arthritis, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.09', 'Unspecified juvenile rheumatoid arthritis, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.1', 'Juvenile ankylosing spondylitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.20', 'Juvenile rheumatoid arthritis with systemic onset, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.211', 'Juvenile rheumatoid arthritis with systemic onset, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.212', 'Juvenile rheumatoid arthritis with systemic onset, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.219', 'Juvenile rheumatoid arthritis with systemic onset, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.221', 'Juvenile rheumatoid arthritis with systemic onset, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.222', 'Juvenile rheumatoid arthritis with systemic onset, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.229', 'Juvenile rheumatoid arthritis with systemic onset, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.231', 'Juvenile rheumatoid arthritis with systemic onset, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.232', 'Juvenile rheumatoid arthritis with systemic onset, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.239', 'Juvenile rheumatoid arthritis with systemic onset, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.241', 'Juvenile rheumatoid arthritis with systemic onset, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.242', 'Juvenile rheumatoid arthritis with systemic onset, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.249', 'Juvenile rheumatoid arthritis with systemic onset, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.251', 'Juvenile rheumatoid arthritis with systemic onset, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.252', 'Juvenile rheumatoid arthritis with systemic onset, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.259', 'Juvenile rheumatoid arthritis with systemic onset, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.261', 'Juvenile rheumatoid arthritis with systemic onset, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.262', 'Juvenile rheumatoid arthritis with systemic onset, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.269', 'Juvenile rheumatoid arthritis with systemic onset, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.271', 'Juvenile rheumatoid arthritis with systemic onset, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.272', 'Juvenile rheumatoid arthritis with systemic onset, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.279', 'Juvenile rheumatoid arthritis with systemic onset, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.28', 'Juvenile rheumatoid arthritis with systemic onset, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.29', 'Juvenile rheumatoid arthritis with systemic onset, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.3', 'Juvenile rheumatoid polyarthritis (seronegative)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.40', 'Pauciarticular juvenile rheumatoid arthritis, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.411', 'Pauciarticular juvenile rheumatoid arthritis, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.412', 'Pauciarticular juvenile rheumatoid arthritis, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.419', 'Pauciarticular juvenile rheumatoid arthritis, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.421', 'Pauciarticular juvenile rheumatoid arthritis, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.422', 'Pauciarticular juvenile rheumatoid arthritis, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.429', 'Pauciarticular juvenile rheumatoid arthritis, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.431', 'Pauciarticular juvenile rheumatoid arthritis, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.432', 'Pauciarticular juvenile rheumatoid arthritis, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.439', 'Pauciarticular juvenile rheumatoid arthritis, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.441', 'Pauciarticular juvenile rheumatoid arthritis, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.442', 'Pauciarticular juvenile rheumatoid arthritis, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.449', 'Pauciarticular juvenile rheumatoid arthritis, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.451', 'Pauciarticular juvenile rheumatoid arthritis, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.452', 'Pauciarticular juvenile rheumatoid arthritis, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.459', 'Pauciarticular juvenile rheumatoid arthritis, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.461', 'Pauciarticular juvenile rheumatoid arthritis, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.462', 'Pauciarticular juvenile rheumatoid arthritis, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.469', 'Pauciarticular juvenile rheumatoid arthritis, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.471', 'Pauciarticular juvenile rheumatoid arthritis, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.472', 'Pauciarticular juvenile rheumatoid arthritis, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.479', 'Pauciarticular juvenile rheumatoid arthritis, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.48', 'Pauciarticular juvenile rheumatoid arthritis, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.80', 'Other juvenile arthritis, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.811', 'Other juvenile arthritis, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.812', 'Other juvenile arthritis, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.819', 'Other juvenile arthritis, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.821', 'Other juvenile arthritis, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.822', 'Other juvenile arthritis, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.829', 'Other juvenile arthritis, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.831', 'Other juvenile arthritis, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.832', 'Other juvenile arthritis, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.839', 'Other juvenile arthritis, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.841', 'Other juvenile arthritis, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.842', 'Other juvenile arthritis, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.849', 'Other juvenile arthritis, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.851', 'Other juvenile arthritis, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.852', 'Other juvenile arthritis, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.859', 'Other juvenile arthritis, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.861', 'Other juvenile arthritis, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.862', 'Other juvenile arthritis, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.869', 'Other juvenile arthritis, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.871', 'Other juvenile arthritis, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.872', 'Other juvenile arthritis, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.879', 'Other juvenile arthritis, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.88', 'Other juvenile arthritis, other specified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.89', 'Other juvenile arthritis, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.90', 'Juvenile arthritis, unspecified, unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.911', 'Juvenile arthritis, unspecified, right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.912', 'Juvenile arthritis, unspecified, left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.919', 'Juvenile arthritis, unspecified, unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.921', 'Juvenile arthritis, unspecified, right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.922', 'Juvenile arthritis, unspecified, left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.929', 'Juvenile arthritis, unspecified, unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.931', 'Juvenile arthritis, unspecified, right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.932', 'Juvenile arthritis, unspecified, left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.939', 'Juvenile arthritis, unspecified, unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.941', 'Juvenile arthritis, unspecified, right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.942', 'Juvenile arthritis, unspecified, left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.949', 'Juvenile arthritis, unspecified, unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.951', 'Juvenile arthritis, unspecified, right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.952', 'Juvenile arthritis, unspecified, left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.959', 'Juvenile arthritis, unspecified, unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.961', 'Juvenile arthritis, unspecified, right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.962', 'Juvenile arthritis, unspecified, left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.969', 'Juvenile arthritis, unspecified, unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.971', 'Juvenile arthritis, unspecified, right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.972', 'Juvenile arthritis, unspecified, left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.979', 'Juvenile arthritis, unspecified, unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.98', 'Juvenile arthritis, unspecified, vertebrae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M08.99', 'Juvenile arthritis, unspecified, multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.00', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.011', 'Chronic postrheumatic arthropathy [Jaccoud], right shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.012', 'Chronic postrheumatic arthropathy [Jaccoud], left shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.019', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.021', 'Chronic postrheumatic arthropathy [Jaccoud], right elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.022', 'Chronic postrheumatic arthropathy [Jaccoud], left elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.029', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified elbow')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.031', 'Chronic postrheumatic arthropathy [Jaccoud], right wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.032', 'Chronic postrheumatic arthropathy [Jaccoud], left wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.039', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified wrist')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.041', 'Chronic postrheumatic arthropathy [Jaccoud], right hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.042', 'Chronic postrheumatic arthropathy [Jaccoud], left hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.049', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified hand')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.051', 'Chronic postrheumatic arthropathy [Jaccoud], right hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.052', 'Chronic postrheumatic arthropathy [Jaccoud], left hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.059', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.061', 'Chronic postrheumatic arthropathy [Jaccoud], right knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.062', 'Chronic postrheumatic arthropathy [Jaccoud], left knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.069', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified knee')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.071', 'Chronic postrheumatic arthropathy [Jaccoud], right ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.072', 'Chronic postrheumatic arthropathy [Jaccoud], left ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.079', 'Chronic postrheumatic arthropathy [Jaccoud], unspecified ankle and foot')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.08', 'Chronic postrheumatic arthropathy [Jaccoud], other specified site')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M12.09', 'Chronic postrheumatic arthropathy [Jaccoud], multiple sites')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.0', 'Drug-induced systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.10', 'Systemic lupus erythematosus, organ or system involvement unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.11', 'Endocarditis in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.12', 'Pericarditis in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.13', 'Lung involvement in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.14', 'Glomerular disease in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.15', 'Tubulo-interstitial nephropathy in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.19', 'Other organ or system involvement in systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.8', 'Other forms of systemic lupus erythematosus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M32.9', 'Systemic lupus erythematosus, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.00', 'Juvenile dermatomyositis, organ involvement unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.01', 'Juvenile dermatomyositis with respiratory involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.02', 'Juvenile dermatomyositis with myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.03', 'Juvenile dermatomyositis without myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.09', 'Juvenile dermatomyositis with other organ involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.10', 'Other dermatomyositis, organ involvement unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.11', 'Other dermatomyositis with respiratory involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.12', 'Other dermatomyositis with myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.13', 'Other dermatomyositis without myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.19', 'Other dermatomyositis with other organ involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.20', 'Polymyositis, organ involvement unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.21', 'Polymyositis with respiratory involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.22', 'Polymyositis with myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.29', 'Polymyositis with other organ involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.90', 'Dermatopolymyositis, unspecified, organ involvement unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.91', 'Dermatopolymyositis, unspecified with respiratory involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.92', 'Dermatopolymyositis, unspecified with myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.93', 'Dermatopolymyositis, unspecified without myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M33.99', 'Dermatopolymyositis, unspecified with other organ involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.0', 'Progressive systemic sclerosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.1', 'CR(E)ST syndrome')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.2', 'Systemic sclerosis induced by drug and chemical')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.81', 'Systemic sclerosis with lung involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.82', 'Systemic sclerosis with myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.83', 'Systemic sclerosis with polyneuropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.89', 'Other systemic sclerosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M34.9', 'Systemic sclerosis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.00', 'Sjögren syndrome, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.01', 'Sjögren syndrome with keratoconjunctivitis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.02', 'Sjögren syndrome with lung involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.03', 'Sjögren syndrome with myopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.04', 'Sjögren syndrome with tubulo-interstitial nephropathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.09', 'Sjögren syndrome with other organ involvement')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.1', 'Other overlap syndromes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.5', 'Multifocal fibrosclerosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.8', 'Other specified systemic involvement of connective tissue')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M35.9', 'Systemic involvement of connective tissue, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M36.0', 'Dermato(poly)myositis in neoplastic disease')
,('http://hl7.org/fhir/sid/icd-10-cm', 'M36.8', 'Systemic disorders of connective tissue in other diseases classified elsewhere')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q79.6', 'Ehlers-Danlos syndromes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'Q87.40', 'Marfan syndrome, unspecified')
) AS t (system, code, display) ;