create or replace view irae__dx_cancer_melanoma as select * from (values
('http://snomed.info/sct', '1010631005', 'Primary malignant melanoma of overlapping sites of accessory sinuses (disorder)')
,('http://snomed.info/sct', '103511000119103', 'Melanoma carcinomatosis (disorder)')
,('http://snomed.info/sct', '1080941000119109', 'Malignant melanoma of left choroid (disorder)')
,('http://snomed.info/sct', '1080981000119104', 'Malignant melanoma of right choroid (disorder)')
,('http://snomed.info/sct', '108101000119101', 'Malignant melanoma metastatic to kidney (disorder)')
,('http://snomed.info/sct', '1081021000119109', 'Malignant melanoma of skin of left lower limb (disorder)')
,('http://snomed.info/sct', '109267002', 'Overlapping malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1197294001', 'Malignant melanoma arising in melanocytic nevus (disorder)')
,('http://snomed.info/sct', '1197324006', 'Metastatic malignant melanoma to skin (disorder)')
,('http://snomed.info/sct', '1197332003', 'Primary malignant melanoma of central nervous system (disorder)')
,('http://snomed.info/sct', '1197334002', 'Malignant melanoma of uveal tract (disorder)')
,('http://snomed.info/sct', '1259319007', 'Primary amelanotic malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259378005', 'Primary superficial spreading malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259379002', 'Primary nodular malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259380004', 'Primary acral lentiginous malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1259424009', 'Primary lentigo maligna melanoma (disorder)')
,('http://snomed.info/sct', '1259561002', 'Primary balloon cell malignant melanoma (disorder)')
,('http://snomed.info/sct', '1259563004', 'Primary spindle cell malignant melanoma (disorder)')
,('http://snomed.info/sct', '1259564005', 'Primary desmoplastic malignant melanoma (disorder)')
,('http://snomed.info/sct', '1259676000', 'Primary nodular melanoma of mucous membrane (disorder)')
,('http://snomed.info/sct', '1268881002', 'Primary malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '1285321001', 'Nevoid melanoma (disorder)')
,('http://snomed.info/sct', '15951021000119107', 'Malignant melanoma of skin of bilateral lower limbs (disorder)')
,('http://snomed.info/sct', '15951061000119102', 'Malignant melanoma of skin of bilateral upper limbs (disorder)')
,('http://snomed.info/sct', '15958661000119103', 'Metastatic malignant melanoma to left kidney (disorder)')
,('http://snomed.info/sct', '15958701000119105', 'Metastatic malignant melanoma to bilateral kidneys (disorder)')
,('http://snomed.info/sct', '15958741000119107', 'Metastatic malignant melanoma to right kidney (disorder)')
,('http://snomed.info/sct', '188030005', 'Malignant melanoma of lip (disorder)')
,('http://snomed.info/sct', '188033007', 'Malignant melanoma of auricle (ear) (disorder)')
,('http://snomed.info/sct', '188034001', 'Malignant melanoma of external auditory meatus (disorder)')
,('http://snomed.info/sct', '188038003', 'Malignant melanoma of chin (disorder)')
,('http://snomed.info/sct', '188040008', 'Malignant melanoma of forehead (disorder)')
,('http://snomed.info/sct', '188045003', 'Malignant melanoma of scalp (disorder)')
,('http://snomed.info/sct', '188046002', 'Malignant melanoma of neck (disorder)')
,('http://snomed.info/sct', '188049009', 'Malignant melanoma of axilla (disorder)')
,('http://snomed.info/sct', '188050009', 'Malignant melanoma of breast (disorder)')
,('http://snomed.info/sct', '188051008', 'Malignant melanoma of buttock (disorder)')
,('http://snomed.info/sct', '188052001', 'Malignant melanoma of groin (disorder)')
,('http://snomed.info/sct', '188054000', 'Malignant melanoma of perineum (disorder)')
,('http://snomed.info/sct', '188055004', 'Malignant melanoma of umbilicus (disorder)')
,('http://snomed.info/sct', '188060000', 'Malignant melanoma of shoulder (disorder)')
,('http://snomed.info/sct', '188061001', 'Malignant melanoma of upper arm (disorder)')
,('http://snomed.info/sct', '188062008', 'Malignant melanoma of forearm (disorder)')
,('http://snomed.info/sct', '188063003', 'Malignant melanoma of hand (disorder)')
,('http://snomed.info/sct', '188064009', 'Malignant melanoma of finger (disorder)')
,('http://snomed.info/sct', '188065005', 'Malignant melanoma of thumb (disorder)')
,('http://snomed.info/sct', '188068007', 'Malignant melanoma of hip (disorder)')
,('http://snomed.info/sct', '188069004', 'Malignant melanoma of thigh (disorder)')
,('http://snomed.info/sct', '188070003', 'Malignant melanoma of knee (disorder)')
,('http://snomed.info/sct', '188071004', 'Malignant melanoma of popliteal fossa area (disorder)')
,('http://snomed.info/sct', '188072006', 'Malignant melanoma of lower leg (disorder)')
,('http://snomed.info/sct', '188073001', 'Malignant melanoma of ankle (disorder)')
,('http://snomed.info/sct', '188074007', 'Malignant melanoma of heel (disorder)')
,('http://snomed.info/sct', '188075008', 'Malignant melanoma of foot (disorder)')
,('http://snomed.info/sct', '188076009', 'Malignant melanoma of toe (disorder)')
,('http://snomed.info/sct', '188077000', 'Malignant melanoma of great toe (disorder)')
,('http://snomed.info/sct', '231834005', 'Malignant melanoma of eyelid (disorder)')
,('http://snomed.info/sct', '243971001000119103', 'Malignant melanoma of skin of right ankle (disorder)')
,('http://snomed.info/sct', '249389151000119103', 'Malignant melanoma of skin of right wrist (disorder)')
,('http://snomed.info/sct', '254730000', 'Superficial spreading malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254731001', 'Nodular malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254732008', 'Acral lentiginous malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '254733003', 'Malignant melanoma arising in intradermal nevus (disorder)')
,('http://snomed.info/sct', '254734009', 'Malignant melanoma arising in congenital nevus (disorder)')
,('http://snomed.info/sct', '254896002', 'Malignant melanoma of vulva (disorder)')
,('http://snomed.info/sct', '255004001', 'Malignant melanoma of conjunctiva (disorder)')
,('http://snomed.info/sct', '255012009', 'Malignant melanoma of iris (disorder)')
,('http://snomed.info/sct', '255015006', 'Malignant melanoma of ciliary body (disorder)')
,('http://snomed.info/sct', '255021005', 'Malignant melanoma of choroid (disorder)')
,('http://snomed.info/sct', '269578002', 'Malignant melanoma of head and neck (disorder)')
,('http://snomed.info/sct', '269579005', 'Malignant melanoma of trunk (disorder)')
,('http://snomed.info/sct', '269580008', 'Malignant melanoma of upper limb (disorder)')
,('http://snomed.info/sct', '269581007', 'Malignant melanoma of lower limb (disorder)')
,('http://snomed.info/sct', '274087000', 'Malignant melanoma of eye (disorder)')
,('http://snomed.info/sct', '276751004', 'Amelanotic malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '276821000', 'Malignant melanoma of anus (disorder)')
,('http://snomed.info/sct', '276822007', 'Malignant melanoma of rectum (disorder)')
,('http://snomed.info/sct', '277530005', 'Malignant melanoma of meninges (disorder)')
,('http://snomed.info/sct', '302837001', 'Lentigo maligna melanoma (disorder)')
,('http://snomed.info/sct', '310498001', 'Malignant melanoma of back (disorder)')
,('http://snomed.info/sct', '313248004', 'Malignant melanoma of chest wall (disorder)')
,('http://snomed.info/sct', '314976006', 'Local recurrence of malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '351961000119109', 'Malignant melanoma of skin of right upper limb (disorder)')
,('http://snomed.info/sct', '352001000119100', 'Malignant melanoma of skin of right lower limb (disorder)')
,('http://snomed.info/sct', '352201000119105', 'Malignant melanoma of skin of left upper limb (disorder)')
,('http://snomed.info/sct', '372244006', 'Malignant melanoma (disorder)')
,('http://snomed.info/sct', '399660006', 'Ring melanoma of ciliary body (disorder)')
,('http://snomed.info/sct', '400375351000119102', 'Malignant melanoma of skin of left ankle (disorder)')
,('http://snomed.info/sct', '402558004', 'Malignant melanoma (vertical growth phase) (disorder)')
,('http://snomed.info/sct', '402559007', 'Congenital malignant melanoma (disorder)')
,('http://snomed.info/sct', '402560002', 'Materno-fetal metastatic malignant melanoma (disorder)')
,('http://snomed.info/sct', '402561003', 'Malignant melanoma of soft tissues (disorder)')
,('http://snomed.info/sct', '402562005', 'Malignant melanoma animal-type (disorder)')
,('http://snomed.info/sct', '402563000', 'Metastatic malignant melanoma with diffuse hypermelanosis (disorder)')
,('http://snomed.info/sct', '402564006', 'Multiple primary malignant melanomata (disorder)')
,('http://snomed.info/sct', '403714009', 'Psoralen and long-wave ultraviolet radiation therapy-associated malignant melanoma (disorder)')
,('http://snomed.info/sct', '403921000', 'Borderline malignant melanoma (disorder)')
,('http://snomed.info/sct', '403922007', 'Balloon cell malignant melanoma (disorder)')
,('http://snomed.info/sct', '403923002', 'Spindle cell malignant melanoma (disorder)')
,('http://snomed.info/sct', '403924008', 'Desmoplastic malignant melanoma (disorder)')
,('http://snomed.info/sct', '403925009', 'Neurotropic malignant melanoma (disorder)')
,('http://snomed.info/sct', '403926005', 'Malignant melanoma of oral cavity (disorder)')
,('http://snomed.info/sct', '403927001', 'Malignant melanoma of nail apparatus (disorder)')
,('http://snomed.info/sct', '423280002', 'Malignant melanoma of skin of canthus of eye (disorder)')
,('http://snomed.info/sct', '423447006', 'Malignant melanoma of skin of lower eyelid (disorder)')
,('http://snomed.info/sct', '423494003', 'Malignant melanoma of skin of upper eyelid (disorder)')
,('http://snomed.info/sct', '423673009', 'Malignant melanoma of retina (disorder)')
,('http://snomed.info/sct', '424190005', 'Malignant melanoma of unknown origin (disorder)')
,('http://snomed.info/sct', '424302003', 'Malignant melanoma of skin of lower lip (disorder)')
,('http://snomed.info/sct', '424487008', 'Malignant melanoma of skin of upper lip (disorder)')
,('http://snomed.info/sct', '443493003', 'Metastatic malignant melanoma (disorder)')
,('http://snomed.info/sct', '447712006', 'Malignant melanoma of skin of anus (disorder)')
,('http://snomed.info/sct', '448273006', 'Malignant melanoma of skin of scrotum (disorder)')
,('http://snomed.info/sct', '448298007', 'Malignant melanoma of skin of penis (disorder)')
,('http://snomed.info/sct', '448300007', 'Malignant melanoma of skin of vulva (disorder)')
,('http://snomed.info/sct', '449636007', 'Malignant melanoma of skin of lower leg (disorder)')
,('http://snomed.info/sct', '449637003', 'Malignant melanoma of skin of upper arm (disorder)')
,('http://snomed.info/sct', '698040004', 'Malignant melanoma of nasal cavity (disorder)')
,('http://snomed.info/sct', '698041000', 'Malignant melanoma of vestibule of mouth (disorder)')
,('http://snomed.info/sct', '698042007', 'Malignant melanoma of tongue (disorder)')
,('http://snomed.info/sct', '698043002', 'Malignant melanoma of floor of mouth (disorder)')
,('http://snomed.info/sct', '698044008', 'Malignant melanoma of palatine arch (disorder)')
,('http://snomed.info/sct', '698045009', 'Malignant melanoma of buccal mucosa (disorder)')
,('http://snomed.info/sct', '698285005', 'Malignant melanoma of ethmoid sinus (disorder)')
,('http://snomed.info/sct', '698286006', 'Malignant melanoma of palate (disorder)')
,('http://snomed.info/sct', '698287002', 'Malignant melanoma of gum (disorder)')
,('http://snomed.info/sct', '698288007', 'Malignant melanoma of maxillary sinus (disorder)')
,('http://snomed.info/sct', '707350007', 'Malignant melanoma of accessory sinus (disorder)')
,('http://snomed.info/sct', '707361004', 'Malignant melanoma of frontal sinus (disorder)')
,('http://snomed.info/sct', '707362006', 'Malignant melanoma of sphenoidal sinus (disorder)')
,('http://snomed.info/sct', '717968005', 'Melanoma and neural system tumor syndrome (disorder)')
,('http://snomed.info/sct', '720587009', 'Donor derived melanoma (disorder)')
,('http://snomed.info/sct', '721563000', 'Primary malignant melanoma of vagina (disorder)')
,('http://snomed.info/sct', '721627007', 'Malignant melanoma of esophagus (disorder)')
,('http://snomed.info/sct', '722543005', 'Primary malignant melanoma of anal canal (disorder)')
,('http://snomed.info/sct', '722665003', 'Primary malignant melanoma of cornea (disorder)')
,('http://snomed.info/sct', '723281005', 'Primary malignant melanoma of anus (disorder)')
,('http://snomed.info/sct', '726019003', 'Familial malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '783736003', 'Malignant melanoma of mucous membrane (disorder)')
,('http://snomed.info/sct', '808558991000119105', 'Malignant melanoma of skin of left forearm (disorder)')
,('http://snomed.info/sct', '816204007', 'Nodular melanoma of mucous membrane (disorder)')
,('http://snomed.info/sct', '830150003', 'Malignant melanoma with B-Raf proto-oncogene, serine/threonine kinase V600E mutation (disorder)')
,('http://snomed.info/sct', '866072004', 'Malignant melanoma of orbit (disorder)')
,('http://snomed.info/sct', '866073009', 'Malignant melanoma of overlapping sites of eye and adnexa (disorder)')
,('http://snomed.info/sct', '866079008', 'Malignant melanoma of lacrimal gland (disorder)')
,('http://snomed.info/sct', '866082003', 'Malignant melanoma of lacrimal drainage system (disorder)')
,('http://snomed.info/sct', '91221000119102', 'Metastatic malignant melanoma to pleura (disorder)')
,('http://snomed.info/sct', '93209006', 'Malignant melanoma of perianal skin (disorder)')
,('http://snomed.info/sct', '93210001', 'Malignant melanoma of skin of abdomen (disorder)')
,('http://snomed.info/sct', '93211002', 'Malignant melanoma of skin of ankle (disorder)')
,('http://snomed.info/sct', '93213004', 'Malignant melanoma of skin of axilla (disorder)')
,('http://snomed.info/sct', '93214005', 'Malignant melanoma of skin of back (disorder)')
,('http://snomed.info/sct', '93215006', 'Malignant melanoma of skin of breast (disorder)')
,('http://snomed.info/sct', '93216007', 'Malignant melanoma of skin of buttock (disorder)')
,('http://snomed.info/sct', '93217003', 'Malignant melanoma of skin of cheek (disorder)')
,('http://snomed.info/sct', '93218008', 'Malignant melanoma of skin of chest (disorder)')
,('http://snomed.info/sct', '93219000', 'Malignant melanoma of skin of chin (disorder)')
,('http://snomed.info/sct', '93220006', 'Malignant melanoma of skin of ear (disorder)')
,('http://snomed.info/sct', '93221005', 'Malignant melanoma of skin of elbow (disorder)')
,('http://snomed.info/sct', '93222003', 'Malignant melanoma of skin of external auditory canal (disorder)')
,('http://snomed.info/sct', '93223008', 'Malignant melanoma of skin of eyebrow (disorder)')
,('http://snomed.info/sct', '93224002', 'Malignant melanoma of skin of eyelid (disorder)')
,('http://snomed.info/sct', '93225001', 'Malignant melanoma of skin of face (disorder)')
,('http://snomed.info/sct', '93226000', 'Malignant melanoma of skin of finger (disorder)')
,('http://snomed.info/sct', '93227009', 'Malignant melanoma of skin of foot (disorder)')
,('http://snomed.info/sct', '93228004', 'Malignant melanoma of skin of forearm (disorder)')
,('http://snomed.info/sct', '93229007', 'Malignant melanoma of skin of forehead (disorder)')
,('http://snomed.info/sct', '93230002', 'Malignant melanoma of skin of groin (disorder)')
,('http://snomed.info/sct', '93636004', 'Malignant melanoma of skin of hand (disorder)')
,('http://snomed.info/sct', '93637008', 'Malignant melanoma of skin of hip (disorder)')
,('http://snomed.info/sct', '93638003', 'Malignant melanoma of skin of knee (disorder)')
,('http://snomed.info/sct', '93640008', 'Malignant melanoma of skin of lip (disorder)')
,('http://snomed.info/sct', '93641007', 'Malignant melanoma of skin of lower limb (disorder)')
,('http://snomed.info/sct', '93642000', 'Malignant melanoma of skin of neck (disorder)')
,('http://snomed.info/sct', '93643005', 'Malignant melanoma of skin of nose (disorder)')
,('http://snomed.info/sct', '93644004', 'Malignant melanoma of skin of perineum (disorder)')
,('http://snomed.info/sct', '93645003', 'Malignant melanoma of skin of popliteal area (disorder)')
,('http://snomed.info/sct', '93646002', 'Malignant melanoma of skin of scalp (disorder)')
,('http://snomed.info/sct', '93647006', 'Malignant melanoma of skin of shoulder (disorder)')
,('http://snomed.info/sct', '93648001', 'Malignant melanoma of skin of temporal region (disorder)')
,('http://snomed.info/sct', '93649009', 'Malignant melanoma of skin of thigh (disorder)')
,('http://snomed.info/sct', '93650009', 'Malignant melanoma of skin of toe (disorder)')
,('http://snomed.info/sct', '93651008', 'Malignant melanoma of skin of trunk (disorder)')
,('http://snomed.info/sct', '93652001', 'Malignant melanoma of skin of umbilicus (disorder)')
,('http://snomed.info/sct', '93653006', 'Malignant melanoma of skin of upper limb (disorder)')
,('http://snomed.info/sct', '93654000', 'Malignant melanoma of skin of wrist (disorder)')
,('http://snomed.info/sct', '93655004', 'Malignant melanoma of skin (disorder)')
,('http://snomed.info/sct', '939595491000119108', 'Malignant melanoma of skin of right forearm (disorder)')
,('http://snomed.info/sct', '97051000119105', 'Malignant melanoma metastatic to pancreas (disorder)')
,('http://snomed.info/sct', '985355341000119101', 'Malignant melanoma of skin of left wrist (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.0', 'Malignant melanoma of lip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.10', 'Malignant melanoma of unspecified eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.111', 'Malignant melanoma of right upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.112', 'Malignant melanoma of right lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.121', 'Malignant melanoma of left upper eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.122', 'Malignant melanoma of left lower eyelid, including canthus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.20', 'Malignant melanoma of unspecified ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.21', 'Malignant melanoma of right ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.22', 'Malignant melanoma of left ear and external auricular canal')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.30', 'Malignant melanoma of unspecified part of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.31', 'Malignant melanoma of nose')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.39', 'Malignant melanoma of other parts of face')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.4', 'Malignant melanoma of scalp and neck')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.51', 'Malignant melanoma of anal skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.52', 'Malignant melanoma of skin of breast')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.59', 'Malignant melanoma of other part of trunk')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.60', 'Malignant melanoma of unspecified upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.61', 'Malignant melanoma of right upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.62', 'Malignant melanoma of left upper limb, including shoulder')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.70', 'Malignant melanoma of unspecified lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.71', 'Malignant melanoma of right lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.72', 'Malignant melanoma of left lower limb, including hip')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.8', 'Malignant melanoma of overlapping sites of skin')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C43.9', 'Malignant melanoma of skin, unspecified')
) AS t (system, code, display) ;