create or replace view irae__lab_interpretation_abnormal as select * from (values
('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'A', 'Abnormal')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'AA', 'Critical abnormal')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'DET', 'Detected')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'H', 'High')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'H>', 'Significantly high')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'HH', 'Critical high')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'I', 'Intermediate')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'L', 'Low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'L<', 'Significantly low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'LL', 'Critical low')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'POS', 'Positive')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'R', 'Resistant')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'RR', 'Reactive')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'SYN-R', 'Synergy - resistant')
,('http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation', 'WR', 'Weakly reactive')
,('http://snomed.info/sct', '17621005', 'Normal (qualifier value)')
,('http://snomed.info/sct', '260360000', 'Very high (qualifier value)')
,('http://snomed.info/sct', '260362008', 'Very low (qualifier value)')
,('http://snomed.info/sct', '263654008', 'Abnormal (qualifier value)')
,('http://snomed.info/sct', '371879000', 'Abnormally high (qualifier value)')
,('http://snomed.info/sct', '371880002', 'Abnormally low (qualifier value)')
) AS t (system, code, display) ;