create table irae__cohort_lab_albumin as 
select distinct * from 
 irae__cohort_study_population_lab , 
irae__valueset_lab_albumin
WHERE
irae__cohort_study_population_lab.lab_observation_code = irae__valueset_lab_albumin.code and 
irae__cohort_study_population_lab.lab_observation_system = irae__valueset_lab_albumin.system