create or replace view irae__dx_transplant_solid_organ as select * from (values
('http://snomed.info/sct', '122501000119101', 'Lymphoproliferative disorder following lung transplant (disorder)')
,('http://snomed.info/sct', '122511000119103', 'Lymphoproliferative disorder following heart transplantation (disorder)')
,('http://snomed.info/sct', '122531000119108', 'Lymphoproliferative disorder following kidney transplant (disorder)')
,('http://snomed.info/sct', '128631000119109', 'Chronic graft-versus-host disease following kidney transplant (disorder)')
,('http://snomed.info/sct', '129781000119105', 'Neoplasia following lung transplant (disorder)')
,('http://snomed.info/sct', '15960341000119104', 'Unstable angina due to arteriosclerosis of coronary artery bypass graft of transplanted heart (disorder)')
,('http://snomed.info/sct', '213150003', 'Kidney transplant failure and rejection (disorder)')
,('http://snomed.info/sct', '213151004', 'Heart transplant failure and rejection (disorder)')
,('http://snomed.info/sct', '213152006', 'Heart-lung transplant failure and rejection (disorder)')
,('http://snomed.info/sct', '233844002', 'Accelerated coronary artery disease in transplanted heart (disorder)')
,('http://snomed.info/sct', '233933006', 'Cardiac transplant rejection (disorder)')
,('http://snomed.info/sct', '233934000', 'Cardiac transplant failure (disorder)')
,('http://snomed.info/sct', '234046009', 'Transplant renal vein thrombosis (disorder)')
,('http://snomed.info/sct', '236436003', 'End stage renal failure with renal transplant (disorder)')
,('http://snomed.info/sct', '236569000', 'Primary non-function of renal transplant (disorder)')
,('http://snomed.info/sct', '236570004', 'Renal transplant rejection (disorder)')
,('http://snomed.info/sct', '236571000', 'Hyperacute rejection of renal transplant (disorder)')
,('http://snomed.info/sct', '236572007', 'Accelerated rejection of renal transplant (disorder)')
,('http://snomed.info/sct', '236573002', 'Very mild acute rejection of renal transplant (disorder)')
,('http://snomed.info/sct', '236574008', 'Acute rejection of renal transplant (disorder)')
,('http://snomed.info/sct', '236575009', 'Acute rejection of renal transplant - grade I (disorder)')
,('http://snomed.info/sct', '236576005', 'Acute rejection of renal transplant - grade II (disorder)')
,('http://snomed.info/sct', '236577001', 'Acute rejection of renal transplant - grade III (disorder)')
,('http://snomed.info/sct', '236578006', 'Chronic rejection of renal transplant (disorder)')
,('http://snomed.info/sct', '236579003', 'Chronic rejection of renal transplant - grade I (disorder)')
,('http://snomed.info/sct', '236580000', 'Chronic rejection of renal transplant - grade II (disorder)')
,('http://snomed.info/sct', '236581001', 'Chronic rejection of renal transplant - grade III (disorder)')
,('http://snomed.info/sct', '236582008', 'Acute-on-chronic rejection of renal transplant (disorder)')
,('http://snomed.info/sct', '236583003', 'Failed renal transplant (disorder)')
,('http://snomed.info/sct', '236584009', 'Perfusion injury of renal transplant (disorder)')
,('http://snomed.info/sct', '277010001', 'Unexplained episode of renal transplant dysfunction (disorder)')
,('http://snomed.info/sct', '277011002', 'Pre-existing disease in renal transplant (disorder)')
,('http://snomed.info/sct', '312603000', 'Lung transplant rejection (disorder)')
,('http://snomed.info/sct', '427928003', 'Disorder related to lung transplantation (disorder)')
,('http://snomed.info/sct', '428575007', 'Hypertension secondary to kidney transplant (disorder)')
,('http://snomed.info/sct', '429257001', 'Disorder of transplanted heart (disorder)')
,('http://snomed.info/sct', '429451003', 'Disorder related to renal transplantation (disorder)')
,('http://snomed.info/sct', '431186002', 'Accelerated rejection of cardiac transplant (disorder)')
,('http://snomed.info/sct', '431223003', 'Acute rejection of lung transplant (disorder)')
,('http://snomed.info/sct', '431507002', 'Accelerated rejection of lung transplant (disorder)')
,('http://snomed.info/sct', '431896008', 'Chronic rejection of cardiac transplant (disorder)')
,('http://snomed.info/sct', '432773004', 'Hyperacute rejection of cardiac transplant (disorder)')
,('http://snomed.info/sct', '432774005', 'Hyperacute rejection of lung transplant (disorder)')
,('http://snomed.info/sct', '432843002', 'Acute rejection of cardiac transplant (disorder)')
,('http://snomed.info/sct', '432958009', 'Chronic rejection of lung transplant (disorder)')
,('http://snomed.info/sct', '433592008', 'Acute rejection of pancreas transplant (disorder)')
,('http://snomed.info/sct', '433809002', 'Accelerated rejection of pancreas transplant (disorder)')
,('http://snomed.info/sct', '434202008', 'Hyperacute rejection of pancreas transplant (disorder)')
,('http://snomed.info/sct', '434271002', 'Chronic rejection of pancreas transplant (disorder)')
,('http://snomed.info/sct', '44165003', 'Complication of transplanted lung (disorder)')
,('http://snomed.info/sct', '444855007', 'Arteriosclerosis of coronary artery bypass graft of transplanted heart (disorder)')
,('http://snomed.info/sct', '471851005', 'Disorder of myocardium associated with rejection of cardiac transplant (disorder)')
,('http://snomed.info/sct', '58797008', 'Disorder due to and following transplant of kidney (disorder)')
,('http://snomed.info/sct', '703048006', 'Vesicoureteric reflux after renal transplant (disorder)')
,('http://snomed.info/sct', '707148007', 'Recurrent renal disease following transplantation of kidney (disorder)')
,('http://snomed.info/sct', '713825007', 'Renal artery stenosis of transplanted kidney (disorder)')
,('http://snomed.info/sct', '714153000', 'Chronic kidney disease stage 5 with transplant (disorder)')
,('http://snomed.info/sct', '762618008', 'Bronchiolitis obliterans syndrome due to and after lung transplantation (disorder)')
,('http://snomed.info/sct', '792842004', 'Coronary arteriosclerosis in artery of transplanted heart (disorder)')
,('http://snomed.info/sct', '79369007', 'Complication of transplanted pancreas (disorder)')
) AS t (system, code, display) ;