create or replace view irae__dx_kidney_akf as select * from (values
('http://snomed.info/sct', '1177174007', 'Acute kidney injury following administration of contrast media (disorder)')
,('http://snomed.info/sct', '12245621000119102', 'Acute renal failure following procedure (disorder)')
,('http://snomed.info/sct', '1263955004', 'Acute renal failure following ectopic pregnancy (disorder)')
,('http://snomed.info/sct', '1263956003', 'Acute renal failure following molar pregnancy (disorder)')
,('http://snomed.info/sct', '1285574007', 'Hepatorenal syndrome with acute kidney injury (disorder)')
,('http://snomed.info/sct', '1293198008', 'Post-renal acute kidney injury (disorder)')
,('http://snomed.info/sct', '1293200002', 'Intra-renal acute kidney injury (disorder)')
,('http://snomed.info/sct', '129561000119108', 'Pre-renal acute kidney injury (disorder)')
,('http://snomed.info/sct', '129721000119106', 'Acute renal failure on dialysis (disorder)')
,('http://snomed.info/sct', '145681000119101', 'Acute renal failure due to tubular necrosis (disorder)')
,('http://snomed.info/sct', '14669001', 'Acute kidney injury (disorder)')
,('http://snomed.info/sct', '17380002', 'Failed attempted abortion with acute renal failure (disorder)')
,('http://snomed.info/sct', '200118004', 'Post-delivery acute renal failure with postnatal problem (disorder)')
,('http://snomed.info/sct', '236424009', 'Acute renal impairment (disorder)')
,('http://snomed.info/sct', '236428007', 'Acute kidney injury due to nephrotoxicity (disorder)')
,('http://snomed.info/sct', '236431008', 'Traumatic anuria - crush syndrome (disorder)')
,('http://snomed.info/sct', '236432001', 'Pulmonary renal syndrome (disorder)')
,('http://snomed.info/sct', '236433006', 'Acute-on-chronic renal failure (disorder)')
,('http://snomed.info/sct', '23697004', 'Crush syndrome (disorder)')
,('http://snomed.info/sct', '269257004', 'Acute renal failure due to crush syndrome (disorder)')
,('http://snomed.info/sct', '298015003', 'Acute renal papillary necrosis with renal failure (disorder)')
,('http://snomed.info/sct', '301814009', 'Post-renal renal failure (disorder)')
,('http://snomed.info/sct', '307309005', 'Transient acute renal failure (disorder)')
,('http://snomed.info/sct', '36225005', 'Acute renal failure due to procedure (disorder)')
,('http://snomed.info/sct', '368951000119105', 'Acute kidney injury caused by contrast agent (disorder)')
,('http://snomed.info/sct', '422593004', 'Acute renal failure caused by angiotensin-converting-enzyme inhibitor (disorder)')
,('http://snomed.info/sct', '423533009', 'Acute renal failure due to ischemia (disorder)')
,('http://snomed.info/sct', '429224003', 'Acute renal failure due to acute cortical necrosis (disorder)')
,('http://snomed.info/sct', '430535006', 'Acute renal failure with oliguria (disorder)')
,('http://snomed.info/sct', '438783006', 'Acute postoperative renal failure (disorder)')
,('http://snomed.info/sct', '609455009', 'Induced termination of pregnancy complicated by acute renal failure (disorder)')
,('http://snomed.info/sct', '609472002', 'Induced termination of pregnancy complicated by acute renal failure with oliguria (disorder)')
,('http://snomed.info/sct', '722095005', 'Acute kidney injury due to circulatory failure (disorder)')
,('http://snomed.info/sct', '722096006', 'Acute kidney injury due to hypovolemia (disorder)')
,('http://snomed.info/sct', '722278006', 'Acute kidney injury due to sepsis (disorder)')
,('http://snomed.info/sct', '733137002', 'Acute kidney failure stage 1 (disorder)')
,('http://snomed.info/sct', '733138007', 'Acute kidney failure stage 2 (disorder)')
,('http://snomed.info/sct', '733139004', 'Acute kidney failure stage 3 (disorder)')
,('http://snomed.info/sct', '733839001', 'Postpartum acute renal failure (disorder)')
,('http://snomed.info/sct', '870589006', 'Acute kidney injury due to disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)')
,('http://snomed.info/sct', '88380005', 'Acute milk alkali syndrome (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17', 'Acute kidney failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.0', 'Acute kidney failure with tubular necrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.1', 'Acute kidney failure with acute cortical necrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.2', 'Acute kidney failure with medullary necrosis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.8', 'Other acute kidney failure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'N17.9', 'Acute kidney failure, unspecified')
) AS t (system, code, display) ;