create or replace view irae__lab_triglyceride as select * from (values
('http://loinc.org', 'LOINC_NUM', 'COMPONENT')
,('http://loinc.org', '78361-3', 'Fatty acid & triglyceride panel')
,('http://loinc.org', '70259-7', 'Triglyceride.pericard fld/Triglyceride.serum')
,('http://loinc.org', '70269-6', 'Triglyceride.plr fld/Triglyceride.serum')
,('http://loinc.org', '70260-5', 'Triglyceride.periton fld/Triglyceride.serum')
,('http://loinc.org', '35361-5', 'Triglyceride.in lipoprotein (little a)')
,('http://loinc.org', '35360-7', 'Triglyceride.in lipoprotein (little a)')
,('http://loinc.org', '59572-8', 'Triglyceride')
,('http://loinc.org', '30570-6', 'Triglyceride')
,('http://loinc.org', '95808-2', 'Cholesterol & triglyceride & chylomicrons panel')
,('http://loinc.org', '14450-1', 'Triglyceride')
,('http://loinc.org', '59571-0', 'Triglyceride')
,('http://loinc.org', '3043-7', 'Triglyceride')
,('http://loinc.org', '3049-4', 'Triglyceride')
,('http://loinc.org', '70218-3', 'Triglyceride')
,('http://loinc.org', '14445-1', 'Triglyceride')
,('http://loinc.org', '69947-0', 'Triglyceride')
,('http://loinc.org', '39801-6', 'Triglyceride')
,('http://loinc.org', '22731-4', 'Triglyceride')
,('http://loinc.org', '14447-7', 'Triglyceride')
,('http://loinc.org', '9619-8', 'Triglyceride')
,('http://loinc.org', '14448-5', 'Triglyceride')
,('http://loinc.org', '77360-6', 'Triglyceride')
,('http://loinc.org', '96598-8', 'Triglyceride')
,('http://loinc.org', '14446-9', 'Triglyceride')
,('http://loinc.org', '28554-4', 'Triglyceride')
,('http://loinc.org', '66769-1', 'Triglyceride')
,('http://loinc.org', '12228-3', 'Triglyceride')
,('http://loinc.org', '59036-4', 'Triglyceride')
,('http://loinc.org', '77361-4', 'Triglyceride')
,('http://loinc.org', '35217-9', 'Triglyceride')
,('http://loinc.org', '29766-3', 'Triglyceride')
,('http://loinc.org', '14927-8', 'Triglyceride')
,('http://loinc.org', '12950-2', 'Triglyceride')
,('http://loinc.org', '13899-0', 'Triglyceride')
,('http://loinc.org', '51605-4', 'Triglyceride')
,('http://loinc.org', '2571-8', 'Triglyceride')
,('http://loinc.org', '14449-3', 'Triglyceride')
,('http://loinc.org', '12951-0', 'Triglyceride')
,('http://loinc.org', '94865-3', 'Triglyceride^^corrected for glycerol')
,('http://loinc.org', '17081-1', 'Triglyceride^post CFst')
,('http://loinc.org', '94859-6', 'Glycerol & Glycerol-corrected triglyceride panel')
,('http://loinc.org', '3044-5', 'Triglyceride+ester.in HDL')
,('http://loinc.org', '3045-2', 'Triglyceride+ester.in IDL')
,('http://loinc.org', '3046-0', 'Triglyceride+ester.in LDL')
,('http://loinc.org', '3047-8', 'Triglyceride+ester.in VLDL')
,('http://loinc.org', '2096-6', 'Cholesterol/Triglyceride')
,('http://loinc.org', '47210-0', 'Triglyceride^post CFst')
,('http://loinc.org', '44718-5', 'Lipoprotein.pre-beta/Triglyceride')
,('http://loinc.org', '94872-9', 'Cholesterol & triglyceride panel')
,('http://loinc.org', '34695-7', 'Cholesterol.in VLDL/Triglyceride')
,('http://loinc.org', '3048-6', 'Triglyceride^post CFst')
,('http://loinc.org', '30524-3', 'Triglyceride^post 12H CFst')
,('http://loinc.org', '44733-4', 'Triglyceride/Cholesterol.in HDL')
,('http://loinc.org', '55607-6', 'Triglyceride/Cholesterol.in HDL')
,('http://loinc.org', '1644-4', 'Triglyceride^post 12H CFst')
,('http://loinc.org', '53526-0', 'Triglyceride.in VLDL')
,('http://loinc.org', '81903-7', 'Medium chain triglyceride intake')
,('http://loinc.org', '35363-1', 'Triglyceride.in chylomicrons')
,('http://loinc.org', '53528-6', 'Triglyceride.in HDL 3')
,('http://loinc.org', '35362-3', 'Triglyceride.in chylomicrons')
,('http://loinc.org', '53527-8', 'Triglyceride.in HDL 2')
,('http://loinc.org', '81902-9', 'Medium chain triglyceride intake')
,('http://loinc.org', '101952-0', 'MTTP gene targeted mutation analysis')
) AS t (system, code, display) ;