create or replace view irae__rx_cancer_chemo_advanced as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1001405', 'docetaxel 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1001433', '1.5 ML cabazitaxel 40 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1045456', '2 ML eribulin mesylate 0.5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105585', 'methotrexate 2.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '105586', 'methotrexate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1093280', 'docetaxel 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191138', 'doxorubicin hydrochloride 2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1193331', 'ruxolitinib 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1193339', 'ruxolitinib 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1193343', 'ruxolitinib 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1193347', 'ruxolitinib 20 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1193351', 'ruxolitinib 25 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1437968', 'cyclophosphamide 25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1437969', 'cyclophosphamide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441402', '0.4 ML methotrexate 25 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441411', '0.4 ML methotrexate 37.5 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441416', '0.4 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1441422', '0.4 ML methotrexate 62.5 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1536484', 'mercaptopurine 20 MG/ML Oral Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1543547', 'belinostat 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544378', '0.2 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544385', '0.25 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544387', '0.3 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544389', '0.35 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544395', '0.45 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544397', '0.5 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544401', '0.6 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544403', '0.15 ML methotrexate 50 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1594757', '0.4 ML methotrexate 18.8 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655956', '40 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655959', '10 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655960', '2 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655967', '4 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655968', '8 ML methotrexate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1660004', 'thiotepa 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1660009', 'thiotepa 15 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1718589', 'trabectedin 1 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719000', 'gemcitabine 200 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719003', 'gemcitabine 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1719005', 'gemcitabine 2000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720735', 'lomustine 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720960', '26.3 ML gemcitabine 38 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720975', '52.6 ML gemcitabine 38 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1720977', '5.26 ML gemcitabine 38 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726097', 'bendamustine hydrochloride 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726271', 'ixabepilone 45 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726276', 'ixabepilone 15 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726319', '2 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726324', '5 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726333', '15 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726492', '25 ML irinotecan hydrochloride 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726673', 'bleomycin 15 UNT Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1726676', 'bleomycin 30 UNT Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1728072', 'pemetrexed 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1728077', 'pemetrexed 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1731338', 'dacarbazine 200 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1731340', 'dacarbazine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1731355', '5 ML cytarabine 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732182', '25 ML epirubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1732186', '100 ML epirubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734340', 'etoposide 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734917', 'cyclophosphamide 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734919', 'cyclophosphamide 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1734921', 'cyclophosphamide 2000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736776', '10 ML oxaliplatin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736781', '20 ML oxaliplatin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736784', 'oxaliplatin 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736786', 'oxaliplatin 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1736854', 'cisplatin 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740864', 'fludarabine phosphate 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740865', '2 ML fludarabine phosphate 25 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740894', 'mitomycin 5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740898', 'mitomycin 40 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1740900', 'mitomycin 20 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1747179', '0.4 ML methotrexate 31.3 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1747185', '0.4 ML methotrexate 43.8 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1747192', '0.4 ML methotrexate 56.3 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790095', 'doxorubicin hydrochloride 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790097', '5 ML doxorubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790099', '10 ML doxorubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790100', '25 ML doxorubicin hydrochloride 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1790103', 'doxorubicin hydrochloride 10 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791493', '20 ML idarubicin hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791498', '10 ML idarubicin hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791500', '5 ML idarubicin hydrochloride 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791588', 'ifosfamide 3000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791593', 'ifosfamide 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791597', '60 ML ifosfamide 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791599', '20 ML ifosfamide 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791701', '10 ML fluorouracil 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1791736', '20 ML fluorouracil 50 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1796419', '1 ML pralatrexate 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1796424', '2 ML pralatrexate 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1797528', '40 ML oxaliplatin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1799416', 'topotecan 4 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1799424', '4 ML topotecan 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1805001', 'bendamustine hydrochloride 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1805007', 'bendamustine hydrochloride 25 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1860480', '1 ML docetaxel 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1860485', '4 ML docetaxel 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1860619', '2 ML docetaxel 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1861411', '8 ML docetaxel 20 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1863343', '1 ML vincristine sulfate 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1863354', '2 ML vincristine sulfate 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1872062', 'doxorubicin hydrochloride 20 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1921592', 'methotrexate 2.5 MG/ML Oral Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1942743', 'cytarabine liposome 100 MG / daunorubicin liposomal 44 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1946772', 'methotrexate 25 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197323', 'altretamine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197422', 'busulfan 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197462', 'chlorambucil 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197687', 'etoposide 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197797', 'hydroxyurea 500 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197894', 'lomustine 10 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197895', 'lomustine 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197896', 'lomustine 40 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197919', 'melphalan 2 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197931', 'mercaptopurine 50 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197988', 'mitotane 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197989', 'mitoxantrone 2 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '198269', 'thioguanine 40 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1992545', '6 ML arsenic trioxide 2 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199315', 'etoposide 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1998783', 'gemcitabine 100 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1999308', 'hydroxyurea 100 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2002002', '10 ML daunorubicin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200327', 'capecitabine 150 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200328', 'capecitabine 500 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200342', 'hydroxyurea 200 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200343', 'hydroxyurea 300 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '200344', 'hydroxyurea 400 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239177', 'fluorouracil 50 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239178', 'vinblastine sulfate 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239179', 'dactinomycin 0.5 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '239180', 'streptozocin 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240416', 'cytarabine 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240573', 'pentostatin 10 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240754', '10 ML cladribine 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '240906', '5 ML pegaspargase 750 UNT/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '249364', '20 ML cytarabine 100 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '253113', '10 ML busulfan 6 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283475', 'hydroxyurea 1000 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283510', 'methotrexate 15 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283511', 'methotrexate 5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '283671', 'methotrexate 7.5 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '308725', 'bexarotene 75 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309012', 'carmustine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309013', 'carmustine 7.7 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309311', 'cisplatin 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '309650', '4 ML daunorubicin 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310194', 'estramustine 140 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310248', 'etoposide 20 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '310351', 'floxuridine 500 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311487', 'melphalan 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '311625', 'methotrexate 1000 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '312199', 'paclitaxel 6 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313209', 'temozolomide 20 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313210', 'temozolomide 250 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313211', 'temozolomide 5 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '313213', '5 ML teniposide 10 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '314167', 'procarbazine 50 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '317160', 'temozolomide 100 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '485246', 'azacitidine 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '486419', '20 ML clofarabine 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '583214', 'paclitaxel 100 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '597195', 'carboplatin 10 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '603566', '50 ML nelarabine 5 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '636631', 'decitabine 50 MG Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '700883', 'temozolomide 140 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '700885', 'temozolomide 180 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '747193', 'topotecan 1 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '747195', 'topotecan 0.25 MG Oral Capsule')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '828706', 'fludarabine phosphate 10 MG Oral Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '829926', '10 ML arsenic trioxide 1 MG/ML Injection')
) AS t (system, code, display) ;