create or replace view irae__lab_hdl as select * from (values

('http://loinc.org','11054-4','LDL cholesterol/HDL Cholesterol, Blood'),
('http://loinc.org','12771-2','HDL cholesterol, Blood'),
('http://loinc.org','12772-0','HDL cholesterol, Blood'),
('http://loinc.org','13460-1','LDL cholesterol/HDL Cholesterol, Blood'),
('http://loinc.org','14646-4','HDL cholesterol, Blood'),
('http://loinc.org','14813-0','Lipoprotein.alpha, Blood'),
('http://loinc.org','15121-7','Lipoprotein.alpha/total Lipoprotein, Blood'),
('http://loinc.org','16616-5','HDL cholesterol/LDL Cholesterol, Blood'),
('http://loinc.org','17082-9','Lipoprotein.alpha, Body fluid'),
('http://loinc.org','17845-9','Lipoprotein.alpha, Blood'),
('http://loinc.org','18263-4','HDL cholesterol, Blood ultracentrifugate'),
('http://loinc.org','19250-0','Lipoprotein.alpha, Pleural fluid'),
('http://loinc.org','2085-9','HDL cholesterol, Blood'),
('http://loinc.org','2086-7','HDL cholesterol, Blood'),
('http://loinc.org','2095-8','HDL cholesterol/Total Cholesterol, Blood'),
('http://loinc.org','2573-4','Lipoprotein.alpha, Blood'),
('http://loinc.org','26015-8','HDL 2 cholesterol, Blood'),
('http://loinc.org','26016-6','HDL 2 cholesterol, Blood ultracentrifugate'),
('http://loinc.org','26017-4','HDL 3 cholesterol, Blood'),
('http://loinc.org','26822-7','Lipoprotein.alpha, Body fluid'),
('http://loinc.org','27340-9','HDL cholesterol, Blood'),
('http://loinc.org','3044-5','Triglyceride+ester in HDL, Blood'),
('http://loinc.org','32309-7','Total cholesterol/HDL Cholesterol, Blood'),
('http://loinc.org','35197-3','HDL cholesterol, Blood'),
('http://loinc.org','35243-5','HDL 3 cholesterol, Blood'),
('http://loinc.org','43396-1','Non-HDL cholesterol, Blood'),
('http://loinc.org','43729-3','Lipoprotein.alpha.subparticle.large, Blood'),
('http://loinc.org','44717-7','Lipoprotein.beta/Lipoprotein.alpha, Blood'),
('http://loinc.org','44733-4','Triglyceride/HDL Cholesterol, Blood'),
('http://loinc.org','44915-7','LDL cholesterol/HDL Cholesterol, Blood'),
('http://loinc.org','47220-9','HDL 4+5 cholesterol, Blood'),
('http://loinc.org','47221-7','HDL 1+2 cholesterol, Blood'),
('http://loinc.org','47228-2','Non-HDL cholesterol/Total Cholesterol, Blood'),
('http://loinc.org','48090-5','HDL cholesterol/Cholesterol in HDL+VLDL, Blood'),
('http://loinc.org','49130-8','HDL cholesterol, Blood'),
('http://loinc.org','49748-7','Lipoprotein.alpha, Blood'),
('http://loinc.org','50409-2','HDL 2+3 cholesterol, Blood'),
('http://loinc.org','50840-8','HDL cholesterol, Body fluid'),
('http://loinc.org','53135-0','HDL cholesterol, Dialysis fluid'),
('http://loinc.org','53527-8','Triglyceride in HDL 2, Blood'),
('http://loinc.org','53528-6','Triglyceride in HDL 3, Blood'),
('http://loinc.org','54372-8','HDL cholesterol, Body fluid'),
('http://loinc.org','54467-6','HDL 2a cholesterol/Cholesterol in Total HDL, Blood'),
('http://loinc.org','54468-4','HDL 2b cholesterol/Cholesterol in Total HDL, Blood'),
('http://loinc.org','54469-2','HDL 3a cholesterol/Cholesterol in Total HDL, Blood'),
('http://loinc.org','54470-0','HDL 3b cholesterol/Cholesterol in Total HDL, Blood'),
('http://loinc.org','54471-8','HDL 3c cholesterol/Cholesterol in Total HDL, Blood'),
('http://loinc.org','55607-6','Triglyceride/HDL Cholesterol, Blood'),
('http://loinc.org','56035-9','Apolipoprotein A-I/HDL Cholesterol, Blood'),
('http://loinc.org','56132-4','HDL 2a cholesterol, Blood'),
('http://loinc.org','56133-2','HDL 2b cholesterol, Blood'),
('http://loinc.org','57936-7','HDL 2a cholesterol, Blood'),
('http://loinc.org','57937-5','HDL 3a cholesterol, Blood'),
('http://loinc.org','62253-0','Lipoprotein.alpha, Blood'),
('http://loinc.org','70200-1','HDL cholesterol/Total Cholesterol, Blood'),
('http://loinc.org','70204-3','Non-HDL cholesterol, Blood'),
('http://loinc.org','86222-7','Lipoprotein.alpha 3, Blood'),
('http://loinc.org','92711-1','HDL small, Blood'),
('http://loinc.org','9322-9','Total cholesterol/HDL Cholesterol, Blood'),
('http://loinc.org','96589-7','Total cholesterol/HDL Cholesterol, Dried blood spot'),
('http://loinc.org','96596-2','HDL cholesterol, Dried blood spot'),
('http://loinc.org','9830-1','Total cholesterol/HDL Cholesterol, Blood'),
('http://loinc.org','9832-7','HDL 2 cholesterol, Blood'),
('http://loinc.org','9833-5','HDL 3 cholesterol, Blood')
) AS t (system,code,display) ;