create or replace view irae__rx_mycophenolate as select * from (values

('http://www.nlm.nih.gov/research/umls/rxnorm','1156390','mycophenolic acid Oral Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1156391','mycophenolic acid Pill'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1157869','mycophenolate mofetil Injectable Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1157870','mycophenolate mofetil Oral Liquid Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1157871','mycophenolate mofetil Oral Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1157872','mycophenolate mofetil Pill'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1166213','Cellcept Injectable Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1166214','Cellcept Oral Liquid Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1166215','Cellcept Oral Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1166216','Cellcept Pill'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1184447','Myfortic Oral Product'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1184448','Myfortic Pill'),
('http://www.nlm.nih.gov/research/umls/rxnorm','152633','Cellcept'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1726176','mycophenolate mofetil Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','1726179','mycophenolate mofetil Injection [Cellcept]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','199058','mycophenolate mofetil 250 MG Oral Capsule'),
('http://www.nlm.nih.gov/research/umls/rxnorm','200060','mycophenolate mofetil 500 MG Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','213394','CellCept 500 MG Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','237112','mycophenolate mofetil hydrochloride'),
('http://www.nlm.nih.gov/research/umls/rxnorm','265323','mycophenolate'),
('http://www.nlm.nih.gov/research/umls/rxnorm','2684847','mycophenolate mofetil 200 MG/ML [Myhibbin]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','2684850','mycophenolate mofetil Oral Suspension [Myhibbin]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','2684851','mycophenolate mofetil 200 MG/ML Oral Suspension [Myhibbin]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','311880','mycophenolate mofetil 200 MG/ML Oral Suspension'),
('http://www.nlm.nih.gov/research/umls/rxnorm','311881','mycophenolate mofetil 500 MG Injection'),
('http://www.nlm.nih.gov/research/umls/rxnorm','316316','mycophenolate mofetil 250 MG'),
('http://www.nlm.nih.gov/research/umls/rxnorm','316317','mycophenolate mofetil 500 MG'),
('http://www.nlm.nih.gov/research/umls/rxnorm','331587','mycophenolate mofetil 200 MG/ML'),
('http://www.nlm.nih.gov/research/umls/rxnorm','374667','mycophenolate mofetil Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','374670','mycophenolate mofetil Oral Suspension'),
('http://www.nlm.nih.gov/research/umls/rxnorm','379060','mycophenolate mofetil Oral Capsule'),
('http://www.nlm.nih.gov/research/umls/rxnorm','408142','mycophenolate sodium'),
('http://www.nlm.nih.gov/research/umls/rxnorm','485018','mycophenolic acid 180 MG'),
('http://www.nlm.nih.gov/research/umls/rxnorm','485019','mycophenolic acid Delayed Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','485020','mycophenolic acid 180 MG Delayed Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','485022','mycophenolic acid 360 MG'),
('http://www.nlm.nih.gov/research/umls/rxnorm','485023','mycophenolic acid 360 MG Delayed Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','541577','mycophenolic acid Extended Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','541578','mycophenolic acid 180 MG Extended Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','541580','mycophenolic acid 180 MG [Myfortic]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','541583','mycophenolic acid 360 MG Extended Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','541585','mycophenolic acid 360 MG [Myfortic]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','579570','Myfortic'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616433','mycophenolate mofetil 500 MG [Cellcept]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616434','mycophenolate mofetil Oral Tablet [Cellcept]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616435','CellCept 500 MG Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616436','mycophenolic acid 500 MG'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616437','mycophenolic acid Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616438','mycophenolic acid 500 MG Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616442','mycophenolate mofetil 200 MG/ML [Cellcept]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616443','mycophenolate mofetil Oral Suspension [Cellcept]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616444','Cellcept 200 MG/ML Oral Suspension'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616445','mycophenolate mofetil 250 MG [Cellcept]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616446','mycophenolate mofetil Oral Capsule [Cellcept]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616447','CellCept 250 MG Oral Capsule'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616448','mycophenolic acid Delayed Release Oral Tablet [Myfortic]'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616449','Myfortic 360 MG Delayed Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','616450','Myfortic 180 MG Delayed Release Oral Tablet'),
('http://www.nlm.nih.gov/research/umls/rxnorm','654611','mycophenolic acid Extended Release Oral Capsule'),
('http://www.nlm.nih.gov/research/umls/rxnorm','654612','mycophenolic acid 180 MG Extended Release Oral Capsule'),
('http://www.nlm.nih.gov/research/umls/rxnorm','654613','mycophenolic acid 360 MG Extended Release Oral Capsule'),
('http://www.nlm.nih.gov/research/umls/rxnorm','68149','mycophenolate mofetil'),
('http://www.nlm.nih.gov/research/umls/rxnorm','7145','mycophenolic acid')
) AS t (system,code,display) ;