create or replace view irae__doc_ontology_kind as select * from (values
('http://loinc.org','101133-7','Organ AndOr tissue donation consent Document','tissue'),
('http://loinc.org','101792-0','Scanned laboratory result',''),
('http://loinc.org','101881-1','Implant card',''),
--('http://loinc.org','101904-1','Release of Information request',''),
('http://loinc.org','102009-8','Clinical pathology Laboratory report','pathology'),
--('http://loinc.org','103813-2','Domestic violence screening report',''),
('http://loinc.org','104605-1','Alert',''),
--('http://loinc.org','105275-2','Mechanical circulatory support Diagnostic study report',''),
('http://loinc.org','18743-5','Autopsy report',''),
--('http://loinc.org','51900-9','Population Summary note',''),
('http://loinc.org','55751-2','Public health Case report',''),
('http://loinc.org','57828-6','Prescription list',''),
('http://loinc.org','57829-4','Prescription for medical equipment or product',''),
('http://loinc.org','57832-8','Prescription for diagnostic or specialist care',''),
('http://loinc.org','57833-6','Prescription for medication',''),
('http://loinc.org','73709-8','Prescription request Pharmacy Document from Pharmacist','pharmacy'),
('http://loinc.org','75218-8','Case report',''),
--('http://loinc.org','76543-8','Weight management summary report',''),
('http://loinc.org','80422-9','Community health care Report',''),
('http://loinc.org','80563-0','Report',''),
('http://loinc.org','82593-5','Immunization summary report',''),
('http://loinc.org','83320-2','Allergy and Immunology Adverse event note',''),
('http://loinc.org','85893-6','Adverse event note',''),
('http://loinc.org','88357-9','Infectious disease Alert','infectious disease'),
('http://loinc.org','88358-7','Mental health Alert',''),
('http://loinc.org','88359-5','Nurse Alert',''),
('http://loinc.org','88360-3','Pharmacology Alert',''),
('http://loinc.org','88361-1','Addiction medicine Alert',''),
('http://loinc.org','89428-7','Blood or blood product transfusion consent Document',''),
('http://loinc.org','89429-5','Surgical operation order','operation|surgical'),
('http://loinc.org','95412-3','COVID-19 case report',''),
('http://loinc.org','96315-7','Gaps in care report',''),
('http://loinc.org','98137-3','Pain assessment report','')
) AS t (system,code,display,keyword) ;