create or replace view irae__lab_cyclosporin as select * from (values

('http://loinc.org','14978-1','cycloSPORINE, Blood'),
('http://loinc.org','15103-5','cycloSPORINE, Blood'),
('http://loinc.org','16703-1','cycloSPORINE, Blood'),
('http://loinc.org','17807-9','cycloSPORINE, Body fluid'),
('http://loinc.org','32997-9','cycloSPORINE 2 hr after dose, Blood'),
('http://loinc.org','33955-6','cycloSPORINE.monoclonal, Blood'),
('http://loinc.org','33956-4','cycloSPORINE.polyclonal, Blood'),
('http://loinc.org','34426-7','cycloSPORINE.monoclonal, Blood'),
('http://loinc.org','3520-4','cycloSPORINE, Blood'),
('http://loinc.org','3521-2','cycloSPORINE, Blood'),
('http://loinc.org','3522-0','cycloSPORINE+Metabolites, Blood'),
('http://loinc.org','3523-8','cycloSPORINE 12 hr after dose, Blood'),
('http://loinc.org','3524-6','cycloSPORINE 12 hr after dose, Blood'),
('http://loinc.org','3525-3','cycloSPORINE 24 hr after dose, Blood'),
('http://loinc.org','3526-1','cycloSPORINE 24 hr after dose, Blood'),
('http://loinc.org','4207-7','cycloSPORINE dose'),
('http://loinc.org','45058-5','cycloSPORINE monoclonal and Polyclonal panel, Blood'),
('http://loinc.org','48597-9','cycloSPORINE trough, Blood'),
('http://loinc.org','53573-2','cycloSPORINE after dose, Blood'),
('http://loinc.org','53828-0','cycloSPORINE trough, Blood'),
('http://loinc.org','53834-8','cycloSPORINE Peak, Blood'),
('http://loinc.org','55805-6','cycloSPORINE, Blood'),
('http://loinc.org','73426-9','cycloSPORINE induced platelet IgM, Blood'),
('http://loinc.org','73427-7','cycloSPORINE induced platelet IgG, Blood'),
('http://loinc.org','77167-5','cycloSPORINE 3 hr after dose, Blood'),
('http://loinc.org','77168-3','cycloSPORINE 4 hr after dose, Blood'),
('http://loinc.org','77169-1','cycloSPORINE 1 hr after dose, Blood'),
('http://loinc.org','78920-6','cycloSPORINE, Blood'),
('http://loinc.org','80561-4','cycloSPORINE, Dried blood spot'),
('http://loinc.org','99413-7','cycloSPORINE, Blood')
) AS t (system,code,display) ;