create or replace view irae__proc_transplant_stem_cell as select * from (values
('http://www.cms.gov/Medicare/Coding/ICD10', '30233AZ', 'Transfusion of Embryonic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233C0', 'Transfusion of Autologous Hematopoietic Stem/Progenitor Cells, Genetically Modified into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233G0', 'Transfusion of Autologous Bone Marrow into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233G2', 'Transfusion of Allogeneic Related Bone Marrow into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233G3', 'Transfusion of Allogeneic Unrelated Bone Marrow into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233G4', 'Transfusion of Allogeneic Unspecified Bone Marrow into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233U2', 'Transfusion of Allogeneic Related T-cell Depleted Hematopoietic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233U3', 'Transfusion of Allogeneic Unrelated T-cell Depleted Hematopoietic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233U4', 'Transfusion of Allogeneic Unspecified T-cell Depleted Hematopoietic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233X0', 'Transfusion of Autologous Cord Blood Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233X2', 'Transfusion of Allogeneic Related Cord Blood Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233X3', 'Transfusion of Allogeneic Unrelated Cord Blood Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233X4', 'Transfusion of Allogeneic Unspecified Cord Blood Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233Y0', 'Transfusion of Autologous Hematopoietic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233Y2', 'Transfusion of Allogeneic Related Hematopoietic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233Y3', 'Transfusion of Allogeneic Unrelated Hematopoietic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30233Y4', 'Transfusion of Allogeneic Unspecified Hematopoietic Stem Cells into Peripheral Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243AZ', 'Transfusion of Embryonic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243C0', 'Transfusion of Autologous Hematopoietic Stem/Progenitor Cells, Genetically Modified into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243G0', 'Transfusion of Autologous Bone Marrow into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243G2', 'Transfusion of Allogeneic Related Bone Marrow into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243G3', 'Transfusion of Allogeneic Unrelated Bone Marrow into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243G4', 'Transfusion of Allogeneic Unspecified Bone Marrow into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243U2', 'Transfusion of Allogeneic Related T-cell Depleted Hematopoietic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243U3', 'Transfusion of Allogeneic Unrelated T-cell Depleted Hematopoietic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243U4', 'Transfusion of Allogeneic Unspecified T-cell Depleted Hematopoietic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243X0', 'Transfusion of Autologous Cord Blood Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243X2', 'Transfusion of Allogeneic Related Cord Blood Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243X3', 'Transfusion of Allogeneic Unrelated Cord Blood Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243X4', 'Transfusion of Allogeneic Unspecified Cord Blood Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243Y0', 'Transfusion of Autologous Hematopoietic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243Y2', 'Transfusion of Allogeneic Related Hematopoietic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243Y3', 'Transfusion of Allogeneic Unrelated Hematopoietic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/ICD10', '30243Y4', 'Transfusion of Allogeneic Unspecified Hematopoietic Stem Cells into Central Vein, Percutaneous Approach')
,('http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets', '38241', 'Transplantation of patient-derived stem cells')
,('http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets', '38243', 'Transplantation of donor stem cells')
,('http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets', 'S2142', 'Cord blood-derived stem-cell transplantation, allogeneic')
) AS t (system, code, display) ;