create or replace view irae__dx_infection_influenza as select * from (values
('http://snomed.info/sct', '10629191000119100', 'Bronchiolitis caused by influenza virus (disorder)')
,('http://snomed.info/sct', '10685111000119102', 'Upper respiratory tract infection caused by Influenza virus (disorder)')
,('http://snomed.info/sct', '1149091008', 'Influenza caused by Influenza A virus valueset H2 (disorder)')
,('http://snomed.info/sct', '142931000119100', 'Pneumonia caused by Influenza A virus valueset H1N1 (disorder)')
,('http://snomed.info/sct', '142941000119109', 'Upper respiratory tract infection caused by H1N1 influenza (disorder)')
,('http://snomed.info/sct', '16311000119108', 'Pneumonia caused by Influenza virus (disorder)')
,('http://snomed.info/sct', '195878008', 'Pneumonia and influenza (disorder)')
,('http://snomed.info/sct', '195923003', 'Influenza with laryngitis (disorder)')
,('http://snomed.info/sct', '195924009', 'Influenza with pharyngitis (disorder)')
,('http://snomed.info/sct', '24662006', 'Influenza caused by Influenza B virus (disorder)')
,('http://snomed.info/sct', '328531000119104', 'Upper respiratory tract infection caused by Influenza A (disorder)')
,('http://snomed.info/sct', '408687004', 'Healthcare associated influenza disease (disorder)')
,('http://snomed.info/sct', '41269000', 'Influenzal bronchopneumonia (disorder)')
,('http://snomed.info/sct', '435051000124104', 'Influenza due to Influenza A virus with upper respiratory signs (disorder)')
,('http://snomed.info/sct', '43692000', 'Influenzal acute upper respiratory infection (disorder)')
,('http://snomed.info/sct', '442438000', 'Influenza caused by Influenza A virus (disorder)')
,('http://snomed.info/sct', '442696006', 'Influenza caused by Influenza A virus valueset H1N1 (disorder)')
,('http://snomed.info/sct', '450715004', 'Influenza caused by Influenza A virus valueset H7 (disorder)')
,('http://snomed.info/sct', '450716003', 'Influenza caused by Influenza A virus subtype H9 (disorder)')
,('http://snomed.info/sct', '541131000124102', 'Infection caused by novel Influenza A virus variant (disorder)')
,('http://snomed.info/sct', '6142004', 'Influenza (disorder)')
,('http://snomed.info/sct', '61700007', 'Influenza with non-respiratory manifestation (disorder)')
,('http://snomed.info/sct', '707448003', 'Influenza caused by Influenza A virus subtype H7N9 (disorder)')
,('http://snomed.info/sct', '713083002', 'Influenza caused by Influenza A virus subtype H5 (disorder)')
,('http://snomed.info/sct', '719590007', 'Influenza caused by seasonal influenza virus (disorder)')
,('http://snomed.info/sct', '719865001', 'Influenza caused by pandemic influenza virus (disorder)')
,('http://snomed.info/sct', '74644004', 'Influenza with encephalopathy (disorder)')
,('http://snomed.info/sct', '772810003', 'Influenza caused by Influenza A virus subtype H3N2 (disorder)')
,('http://snomed.info/sct', '772828001', 'Influenza caused by Influenza A virus subtype H5N1 (disorder)')
,('http://snomed.info/sct', '772839003', 'Pneumonia caused by Influenza A virus (disorder)')
,('http://snomed.info/sct', '81524006', 'Influenza caused by Influenza C virus (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J09.X1', 'Influenza due to identified novel influenza A virus with pneumonia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J09.X2', 'Influenza due to identified novel influenza A virus with other respiratory manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J09.X3', 'Influenza due to identified novel influenza A virus with gastrointestinal manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J09.X9', 'Influenza due to identified novel influenza A virus with other manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.00', 'Influenza due to other identified influenza virus with unspecified type of pneumonia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.01', 'Influenza due to other identified influenza virus with the same other identified influenza virus pneumonia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.08', 'Influenza due to other identified influenza virus with other specified pneumonia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.1', 'Influenza due to other identified influenza virus with other respiratory manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.2', 'Influenza due to other identified influenza virus with gastrointestinal manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.81', 'Influenza due to other identified influenza virus with encephalopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.82', 'Influenza due to other identified influenza virus with myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.83', 'Influenza due to other identified influenza virus with otitis media')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J10.89', 'Influenza due to other identified influenza virus with other manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.00', 'Influenza due to unidentified influenza virus with unspecified type of pneumonia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.08', 'Influenza due to unidentified influenza virus with specified pneumonia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.1', 'Influenza due to unidentified influenza virus with other respiratory manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.2', 'Influenza due to unidentified influenza virus with gastrointestinal manifestations')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.81', 'Influenza due to unidentified influenza virus with encephalopathy')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.82', 'Influenza due to unidentified influenza virus with myocarditis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.83', 'Influenza due to unidentified influenza virus with otitis media')
,('http://hl7.org/fhir/sid/icd-10-cm', 'J11.89', 'Influenza due to unidentified influenza virus with other manifestations')
) AS t (system, code, display) ;