create or replace view $prefix__doc_ontology_domain as select * from (values
('http://loinc.org','100439-9','Allergy and Immunology Outpatient Progress note',''),
('http://loinc.org','100444-9','Blood banking and transfusion medicine Outpatient Progress note',''),
('http://loinc.org','100445-6','Bone Marrow Transplant Outpatient Progress note','transplant'),
('http://loinc.org','100455-5','Clinical pathology Outpatient Progress note','pathology'),
('http://loinc.org','100460-5','Dermatology Outpatient Progress note','dermatology'),
('http://loinc.org','100462-1','Dialysis and Therapeutic apheresis Outpatient Progress note',''),
('http://loinc.org','100472-0','Heart failure+Transplant cardiology Outpatient Progress note','transplant'),
('http://loinc.org','100473-8','Hematology Outpatient Progress note',''),
('http://loinc.org','100474-6','Hematology+Medical oncology Outpatient Progress note','oncology'),
('http://loinc.org','100476-1','Immunology Outpatient Progress note',''),
('http://loinc.org','100477-9','Infectious disease Outpatient Progress note','infectious disease'),
('http://loinc.org','100486-0','Nephrology Outpatient Progress note','nephrology'),
('http://loinc.org','100496-9','Oncology Outpatient Progress note','oncology'),
('http://loinc.org','100506-5','Pediatric dermatology Outpatient Progress note','dermatology'),
('http://loinc.org','100509-9','Pediatric hematology-oncology Outpatient Progress note','oncology'),
('http://loinc.org','100510-7','Pediatric infectious diseases Outpatient Progress note','infectious disease'),
('http://loinc.org','100514-9','Pediatric surgery Outpatient Progress note','surgery'),
('http://loinc.org','100515-6','Pediatric transplant hepatology Outpatient Progress note','transplant'),
('http://loinc.org','100516-4','Pediatric urology Outpatient Progress note','urology'),
('http://loinc.org','100525-5','Radiation oncology Outpatient Progress note','oncology'),
('http://loinc.org','100533-9','Solid Organ Transplant Outpatient Progress note','transplant'),
('http://loinc.org','100540-4','Transplant surgery Outpatient Progress note','surgery|transplant'),
('http://loinc.org','100542-0','Urology Outpatient Progress note','urology'),
('http://loinc.org','100544-6','Vascular surgery Outpatient Progress note','surgery'),
('http://loinc.org','100548-7','Allergy and Immunology Hospital Progress note',''),
('http://loinc.org','100553-7','Blood banking and transfusion medicine Hospital Progress note',''),
('http://loinc.org','100554-5','Bone Marrow Transplant Hospital Progress note','transplant'),
('http://loinc.org','100563-6','Clinical pathology Hospital Progress note','pathology'),
('http://loinc.org','100567-7','Dermatology Hospital Progress note','dermatology'),
('http://loinc.org','100569-3','Dialysis and Therapeutic apheresis Hospital Progress note',''),
('http://loinc.org','100580-0','Heart failure+Transplant cardiology Hospital Progress note','transplant'),
('http://loinc.org','100581-8','Hematology Hospital Progress note',''),
('http://loinc.org','100582-6','Hematology+Medical oncology Hospital Progress note','oncology'),
('http://loinc.org','100584-2','Immunology Hospital Progress note',''),
('http://loinc.org','100585-9','Infectious disease Hospital Progress note','infectious disease'),
('http://loinc.org','100594-1','Nephrology Hospital Progress note','nephrology'),
('http://loinc.org','100604-8','Oncology Hospital Progress note','oncology'),
('http://loinc.org','100612-1','Pastoral care Hospital Progress note',''),
('http://loinc.org','100614-7','Pediatric dermatology Hospital Progress note','dermatology'),
('http://loinc.org','100617-0','Pediatric hematology-oncology Hospital Progress note','oncology'),
('http://loinc.org','100618-8','Pediatric infectious diseases Hospital Progress note','infectious disease'),
('http://loinc.org','100622-0','Pediatric surgery Hospital Progress note','surgery'),
('http://loinc.org','100623-8','Pediatric transplant hepatology Hospital Progress note','transplant'),
('http://loinc.org','100625-3','Pharmacology Hospital Progress note',''),
('http://loinc.org','100631-1','Radiation oncology Hospital Progress note','oncology'),
('http://loinc.org','100640-2','Solid Organ Transplant Hospital Progress note','transplant'),
('http://loinc.org','100646-9','Urology Hospital Progress note','urology'),
('http://loinc.org','100648-5','Vascular surgery Hospital Progress note','surgery'),
('http://loinc.org','100719-4','Surgical oncology Discharge summary','oncology|surgical'),
('http://loinc.org','100730-1','Transplant surgery Discharge summary','surgery|transplant'),
('http://loinc.org','101015-6','Surgical oncology History and physical note','oncology|surgical'),
('http://loinc.org','101029-7','Hematology+Medical oncology History and physical note','oncology'),
('http://loinc.org','101049-5','Anesthesiology Surgical operation note','operation|surgical'),
('http://loinc.org','101136-0','Radiation oncology End of treatment letter','oncology'),
('http://loinc.org','101887-8','Surgery Telephone encounter Consult note','surgery'),
('http://loinc.org','101890-2','Medical toxicology Discharge summary',''),
('http://loinc.org','101896-9','Heart failure+Transplant cardiology procedure note','transplant'),
('http://loinc.org','102009-8','Clinical pathology Laboratory report','pathology'),
('http://loinc.org','103554-2','Surgical oncology Progress note','oncology|surgical'),
('http://loinc.org','103802-5','Medical oncology.team Conference note','oncology'),
('http://loinc.org','103803-3','Surgery Outpatient Progress note','surgery'),
('http://loinc.org','103804-1','Surgical oncology Outpatient Progress note','oncology|surgical'),
('http://loinc.org','103806-6','Oncology Telephone encounter Note','oncology'),
('http://loinc.org','103807-4','Hematology Referral note',''),
('http://loinc.org','103808-2','Allergy and Immunology Medication management note',''),
('http://loinc.org','103816-5','Bone Marrow Transplant Medication management note','transplant'),
('http://loinc.org','103819-9','Dermatology Medication management note','dermatology'),
('http://loinc.org','103820-7','Dialysis Medication management note',''),
('http://loinc.org','103821-5','Emergency medicine Medication management note',''),
('http://loinc.org','103824-9','Hematology Medication management note',''),
('http://loinc.org','103826-4','Infectious disease Medication management note','infectious disease'),
('http://loinc.org','104588-9','Emergency medicine team Conference note',''),
('http://loinc.org','104591-3','Vascular surgery Letter','surgery'),
('http://loinc.org','104593-9','Oncology Letter','oncology'),
('http://loinc.org','107919-3','Surgery Medication management note','surgery'),
('http://loinc.org','107922-7','Oncology Medication management note','oncology'),
('http://loinc.org','107924-3','Nephrology Medication management note','nephrology'),
('http://loinc.org','107949-0','Solid Organ Transplant Medication management note','transplant'),
--('http://loinc.org','18682-5','Ambulance records',''),
('http://loinc.org','34122-2','Pathology procedure note','pathology'),
('http://loinc.org','34123-0','Anesthesiology Hospital Preoperative evaluation and management note','operative'),
('http://loinc.org','34132-1','Pharmacology Outpatient Progress note',''),
('http://loinc.org','34749-2','Anesthesiology Outpatient Consult note',''),
('http://loinc.org','34750-0','Anesthesiology Note',''),
('http://loinc.org','34751-8','Anesthesiology Preoperative evaluation and management note','operative'),
('http://loinc.org','34758-3','Dermatology Consult note','dermatology'),
('http://loinc.org','34759-1','Dermatology Note','dermatology'),
('http://loinc.org','34773-2','Surgery Attending Note','surgery'),
('http://loinc.org','34774-0','Surgery History and physical note','surgery'),
('http://loinc.org','34779-9','Hematology+Medical oncology Consult note','oncology'),
('http://loinc.org','34780-7','Hematology+Medical oncology Note','oncology'),
('http://loinc.org','34781-5','Infectious disease Consult note','infectious disease'),
('http://loinc.org','34782-3','Infectious disease Note','infectious disease'),
('http://loinc.org','34795-5','Nephrology Consult note','nephrology'),
('http://loinc.org','34796-3','Nephrology Note','nephrology'),
('http://loinc.org','34805-2','Oncology Consult note','oncology'),
('http://loinc.org','34806-0','Oncology Note','oncology'),
('http://loinc.org','34819-3','Pathology Note','pathology'),
('http://loinc.org','34820-1','Pharmacology Consult note',''),
('http://loinc.org','34821-9','Pharmacology Note',''),
('http://loinc.org','34831-8','Radiation oncology Consult note','oncology'),
('http://loinc.org','34832-6','Radiation oncology Note','oncology'),
('http://loinc.org','34847-4','Surgery Consult note','surgery'),
('http://loinc.org','34848-2','Surgery Note','surgery'),
('http://loinc.org','34851-6','Urology Consult note','urology'),
('http://loinc.org','34852-4','Urology Note','urology'),
('http://loinc.org','34853-2','Vascular surgery Consult note','surgery'),
('http://loinc.org','34854-0','Vascular surgery Outpatient Note','surgery'),
('http://loinc.org','34869-8','Pharmacology Counseling note',''),
('http://loinc.org','34873-0','Surgery Admission evaluation note','surgery'),
('http://loinc.org','34874-8','Surgery Surgical operation note','operation|surgery|surgical'),
('http://loinc.org','34875-5','Surgery Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','34876-3','Surgery Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','34877-1','Urology Surgical operation note','operation|surgical|urology'),
('http://loinc.org','34878-9','Emergency medicine Note',''),
('http://loinc.org','34880-5','Surgery Nurse Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','34881-3','Surgery Nurse Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','34906-8','Pastoral care Note',''),
('http://loinc.org','57135-6','Dermatology Referral note','dermatology'),
('http://loinc.org','57141-4','Infectious disease Referral note','infectious disease'),
('http://loinc.org','57144-8','Nephrology Referral note','nephrology'),
('http://loinc.org','57149-7','Oncology Referral note','oncology'),
('http://loinc.org','57152-1','Pharmacology Referral note',''),
('http://loinc.org','57159-6','Radiation oncology Referral note','oncology'),
('http://loinc.org','57166-1','Surgery Referral note','surgery'),
('http://loinc.org','57168-7','Urology Referral note','urology'),
('http://loinc.org','57169-5','Vascular surgery Referral note','surgery'),
('http://loinc.org','57172-9','Hematology+Medical oncology Referral note','oncology'),
('http://loinc.org','60570-9','Pathology Consult note','pathology'),
('http://loinc.org','64057-3','Surgery Hospital Progress note','surgery'),
('http://loinc.org','64064-9','Pastoral care Hospital Evaluation note',''),
('http://loinc.org','64066-4','Surgery Medical student Hospital Admission evaluation note','surgery'),
('http://loinc.org','64067-2','Surgery Medical student Hospital Progress note','surgery'),
('http://loinc.org','64068-0','Surgery Medical student Hospital Consult note','surgery'),
('http://loinc.org','68469-6','Pastoral care Hospital Consult note',''),
('http://loinc.org','68480-3','Surgery Attending Hospital Progress note','surgery'),
('http://loinc.org','68550-3','Dermatology Preoperative evaluation and management note','dermatology|operative'),
('http://loinc.org','68551-1','Dermatology Hospital Consult note','dermatology'),
('http://loinc.org','68552-9','Emergency medicine Emergency department Admission evaluation note',''),
('http://loinc.org','68553-7','Hematology+Medical oncology Initial evaluation note','oncology'),
('http://loinc.org','68554-5','Hematology+Medical oncology Progress note','oncology'),
('http://loinc.org','68555-2','Hematology+Medical oncology Hospital Letter','oncology'),
('http://loinc.org','68586-7','Pharmacology Hospital Consult note',''),
('http://loinc.org','68587-5','Pharmacology Hospital Medication management note',''),
('http://loinc.org','68602-2','Radiation oncology Summary note','oncology'),
('http://loinc.org','68603-0','Radiation oncology Hospital Summary note','oncology'),
('http://loinc.org','68606-3','Surgery Hospital Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','68621-2','Heart failure+Transplant cardiology Note','transplant'),
('http://loinc.org','68622-0','Heart failure+Transplant cardiology History and physical note','transplant'),
('http://loinc.org','68623-8','Heart failure+Transplant cardiology Preoperative evaluation and management note','operative|transplant'),
('http://loinc.org','68624-6','Heart failure+Transplant cardiology Hospital Letter','transplant'),
('http://loinc.org','68625-3','Allergy and Immunology Diagnostic study note',''),
('http://loinc.org','68626-1','Allergy and Immunology Discharge summary',''),
('http://loinc.org','68628-7','Allergy and Immunology History and physical note',''),
('http://loinc.org','68629-5','Allergy and Immunology Note',''),
('http://loinc.org','68630-3','Allergy and Immunology procedure note',''),
('http://loinc.org','68631-1','Allergy and Immunology Progress note',''),
('http://loinc.org','68632-9','Allergy and Immunology Transfer summary note',''),
('http://loinc.org','68633-7','Allergy and Immunology Hospital Consult note',''),
('http://loinc.org','68634-5','Allergy and Immunology Hospital Letter',''),
('http://loinc.org','68731-9','Pediatric dermatology History and physical note','dermatology'),
('http://loinc.org','68732-7','Pediatric dermatology Preoperative evaluation and management note','dermatology|operative'),
('http://loinc.org','68748-3','Pediatric hematology-oncology Diagnostic study note','oncology'),
('http://loinc.org','68749-1','Pediatric hematology-oncology Discharge summary','oncology'),
('http://loinc.org','68751-7','Pediatric hematology-oncology History and physical note','oncology'),
('http://loinc.org','68752-5','Pediatric hematology-oncology Note','oncology'),
('http://loinc.org','68753-3','Pediatric hematology-oncology Preoperative evaluation and management note','oncology|operative'),
('http://loinc.org','68754-1','Pediatric hematology-oncology procedure note','oncology'),
('http://loinc.org','68755-8','Pediatric hematology-oncology Progress note','oncology'),
('http://loinc.org','68756-6','Pediatric hematology-oncology Transfer summary note','oncology'),
('http://loinc.org','68757-4','Pediatric hematology-oncology Hospital Consult note','oncology'),
('http://loinc.org','68758-2','Pediatric hematology-oncology Hospital Letter','oncology'),
('http://loinc.org','68760-8','Pediatric infectious diseases History and physical note','infectious disease'),
('http://loinc.org','68761-6','Pediatric infectious diseases Note','infectious disease'),
('http://loinc.org','68762-4','Pediatric infectious diseases Preoperative evaluation and management note','infectious disease|operative'),
('http://loinc.org','68763-2','Pediatric infectious diseases Progress note','infectious disease'),
('http://loinc.org','68764-0','Pediatric infectious diseases Transfer summary note','infectious disease'),
('http://loinc.org','68765-7','Pediatric infectious diseases Hospital Consult note','infectious disease'),
('http://loinc.org','68766-5','Pediatric infectious diseases Hospital Letter','infectious disease'),
('http://loinc.org','68767-3','Pediatric nephrology Diagnostic study note','nephrology'),
('http://loinc.org','68768-1','Pediatric nephrology Discharge summary','nephrology'),
('http://loinc.org','68770-7','Pediatric nephrology History and physical note','nephrology'),
('http://loinc.org','68771-5','Pediatric nephrology Preoperative evaluation and management note','nephrology|operative'),
('http://loinc.org','68772-3','Pediatric nephrology Transfer summary note','nephrology'),
('http://loinc.org','68794-7','Pediatric surgery Diagnostic study note','surgery'),
('http://loinc.org','68795-4','Pediatric surgery Discharge summary','surgery'),
('http://loinc.org','68797-0','Pediatric surgery History and physical note','surgery'),
('http://loinc.org','68798-8','Pediatric surgery Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','68799-6','Pediatric surgery procedure note','surgery'),
('http://loinc.org','68800-2','Pediatric surgery Progress note','surgery'),
('http://loinc.org','68801-0','Pediatric surgery Transfer summary note','surgery'),
('http://loinc.org','68802-8','Pediatric surgery Hospital Consult note','surgery'),
('http://loinc.org','68803-6','Pediatric surgery Hospital Letter','surgery'),
('http://loinc.org','68804-4','Pediatric urology Diagnostic study note','urology'),
('http://loinc.org','68805-1','Pediatric urology Discharge summary','urology'),
('http://loinc.org','68807-7','Pediatric urology History and physical note','urology'),
('http://loinc.org','68808-5','Pediatric urology Preoperative evaluation and management note','operative|urology'),
('http://loinc.org','68809-3','Pediatric urology procedure note','urology'),
('http://loinc.org','68810-1','Pediatric urology Progress note','urology'),
('http://loinc.org','68811-9','Pediatric urology Transfer summary note','urology'),
('http://loinc.org','68812-7','Pediatric urology Hospital Consult note','urology'),
('http://loinc.org','68813-5','Pediatric urology Hospital Letter','urology'),
('http://loinc.org','68848-1','Transplant surgery Note','surgery|transplant'),
('http://loinc.org','68849-9','Transplant surgery History and physical note','surgery|transplant'),
('http://loinc.org','68850-7','Transplant surgery Preoperative evaluation and management note','operative|surgery|transplant'),
('http://loinc.org','68851-5','Transplant surgery procedure note','surgery|transplant'),
('http://loinc.org','68852-3','Transplant surgery Hospital Consult note','surgery|transplant'),
('http://loinc.org','68853-1','Transplant surgery Hospital Letter','surgery|transplant'),
('http://loinc.org','68855-6','Pediatric transplant hepatology Diagnostic study note','transplant'),
('http://loinc.org','68856-4','Pediatric transplant hepatology Discharge summary','transplant'),
('http://loinc.org','68858-0','Pediatric transplant hepatology History and physical note','transplant'),
('http://loinc.org','68859-8','Pediatric transplant hepatology Note','transplant'),
('http://loinc.org','68860-6','Pediatric transplant hepatology Preoperative evaluation and management note','operative|transplant'),
('http://loinc.org','68861-4','Pediatric transplant hepatology procedure note','transplant'),
('http://loinc.org','68862-2','Pediatric transplant hepatology Progress note','transplant'),
('http://loinc.org','68863-0','Pediatric transplant hepatology Transfer summary note','transplant'),
('http://loinc.org','68864-8','Pediatric transplant hepatology Hospital Consult note','transplant'),
('http://loinc.org','68865-5','Pediatric transplant hepatology Hospital Letter','transplant'),
('http://loinc.org','68866-3','Pediatric nephrology Letter','nephrology'),
('http://loinc.org','68867-1','Pediatric nephrology Note','nephrology'),
('http://loinc.org','68868-9','Pediatric nephrology procedure note','nephrology'),
('http://loinc.org','68869-7','Pediatric nephrology Hospital Consult note','nephrology'),
('http://loinc.org','68870-5','Pediatric nephrology Hospital Letter','nephrology'),
('http://loinc.org','68881-2','Pediatric surgery Note','surgery'),
('http://loinc.org','68882-0','Pediatric urology Note','urology'),
('http://loinc.org','68889-5','Pediatric dermatology Note','dermatology'),
('http://loinc.org','68890-3','Pediatric dermatology procedure note','dermatology'),
('http://loinc.org','68891-1','Pediatric dermatology Progress note','dermatology'),
('http://loinc.org','68892-9','Pediatric dermatology Hospital Consult note','dermatology'),
('http://loinc.org','68893-7','Pediatric dermatology Hospital Letter','dermatology'),
('http://loinc.org','70238-1','Transplant surgery Hospital Progress note','surgery|transplant'),
('http://loinc.org','74156-1','Oncology Plan of care and summary note','oncology'),
('http://loinc.org','74264-3','HIV Summary registry report',''),
('http://loinc.org','75220-4','Urology Progress note','urology'),
('http://loinc.org','75467-1','Pharmacology Evaluation and management of anticoagulation note',''),
('http://loinc.org','75468-9','Pharmacology Medication management note',''),
('http://loinc.org','75469-7','Pharmacology Outpatient Note',''),
('http://loinc.org','75470-5','Pharmacology Telephone encounter Note',''),
('http://loinc.org','75493-7','Surgery Outpatient Note','surgery'),
('http://loinc.org','75501-7','Urology Outpatient Note','urology'),
('http://loinc.org','77401-8','Anesthesiology Admission history and physical note',''),
('http://loinc.org','77402-6','Anesthesiology Evaluation note',''),
('http://loinc.org','77403-4','Anesthesiology Consult note',''),
('http://loinc.org','77404-2','Anesthesiology Education note',''),
('http://loinc.org','77405-9','Anesthesiology Referral note',''),
('http://loinc.org','77406-7','Anesthesiology Transfer summary note',''),
('http://loinc.org','77429-9','Allergy and Immunology Consult note',''),
('http://loinc.org','77430-7','Allergy and Immunology Education note',''),
('http://loinc.org','77431-5','Allergy and Immunology Initial evaluation note',''),
('http://loinc.org','77432-3','Allergy and Immunology Referral note',''),
('http://loinc.org','77434-9','Allergy and Immunology Evaluation note',''),
('http://loinc.org','77436-4','Anesthesiology Summary note',''),
('http://loinc.org','77438-0','Allergy and Immunology Flowsheet',''),
('http://loinc.org','77443-0','Allergy and Immunology Plan of care note',''),
('http://loinc.org','78242-5','Hematology+Medical oncology Surgical operation note','oncology|operation|surgical'),
('http://loinc.org','78243-3','Vascular surgery Surgical operation note','operation|surgery|surgical'),
('http://loinc.org','78244-1','Transplant surgery Surgical operation note','operation|surgery|surgical|transplant'),
('http://loinc.org','78247-4','Surgery Admission history and physical note','surgery'),
('http://loinc.org','78251-6','Hematology Consult note',''),
('http://loinc.org','78258-1','Infectious disease Diagnostic study note','infectious disease'),
('http://loinc.org','78260-7','Dermatology Diagnostic study note','dermatology'),
('http://loinc.org','78269-8','Dermatology Education note','dermatology'),
('http://loinc.org','78274-8','Hematology Education note',''),
('http://loinc.org','78280-5','Surgery Education note','surgery'),
('http://loinc.org','78281-3','Infectious disease Education note','infectious disease'),
('http://loinc.org','78291-2','Hematology Flowsheet',''),
('http://loinc.org','78292-0','Surgery Flowsheet','surgery'),
('http://loinc.org','78293-8','Infectious disease Flowsheet','infectious disease'),
('http://loinc.org','78294-6','Dermatology Flowsheet','dermatology'),
('http://loinc.org','78302-7','Emergency medicine Emergency department Flowsheet',''),
('http://loinc.org','78310-0','Hematology Initial evaluation note',''),
('http://loinc.org','78314-2','Dermatology procedure note','dermatology'),
('http://loinc.org','78318-3','Infectious disease procedure note','infectious disease'),
('http://loinc.org','78319-1','Hematology procedure note',''),
('http://loinc.org','78322-5','Surgery procedure note','surgery'),
('http://loinc.org','78325-8','Infectious disease Progress note','infectious disease'),
('http://loinc.org','78326-6','Dermatology Progress note','dermatology'),
('http://loinc.org','78328-2','Hematology Progress note',''),
('http://loinc.org','78333-2','Infectious disease Initial evaluation note','infectious disease'),
('http://loinc.org','78334-0','Dermatology Initial evaluation note','dermatology'),
('http://loinc.org','78387-8','Nephrology Admission history and physical note','nephrology'),
('http://loinc.org','78392-8','Oncology Admission history and physical note','oncology'),
('http://loinc.org','78411-6','Nephrology Discharge instructions','nephrology'),
('http://loinc.org','78417-3','Oncology Discharge instructions','oncology'),
('http://loinc.org','78419-9','Nephrology Discharge summary','nephrology'),
('http://loinc.org','78421-5','Oncology Discharge summary','oncology'),
('http://loinc.org','78423-1','Nephrology Discharge teaching note','nephrology'),
('http://loinc.org','78428-0','Oncology Discharge teaching note','oncology'),
('http://loinc.org','78430-6','Nephrology Education note','nephrology'),
('http://loinc.org','78446-2','Surgical critical care Flowsheet','surgical'),
('http://loinc.org','78453-8','Oncology Education note','oncology'),
('http://loinc.org','78456-1','Nephrology Flowsheet','nephrology'),
('http://loinc.org','78462-9','Oncology Flowsheet','oncology'),
('http://loinc.org','78463-7','Nephrology History and physical note','nephrology'),
('http://loinc.org','78465-2','Oncology History and physical note','oncology'),
('http://loinc.org','78468-6','Nephrology Initial evaluation note','nephrology'),
('http://loinc.org','78471-0','Oncology Initial evaluation note','oncology'),
('http://loinc.org','78474-4','Nephrology procedure note','nephrology'),
('http://loinc.org','78478-5','Oncology procedure note','oncology'),
('http://loinc.org','78480-1','Nephrology Progress note','nephrology'),
('http://loinc.org','78482-7','Oncology Progress note','oncology'),
('http://loinc.org','78490-0','Nephrology Transfer summary note','nephrology'),
('http://loinc.org','78493-4','Oncology Transfer summary note','oncology'),
('http://loinc.org','78495-9','Anesthesiology Checklist',''),
('http://loinc.org','78503-0','Surgery Checklist','surgery'),
('http://loinc.org','78510-5','Vascular surgery Admission history and physical note','surgery'),
('http://loinc.org','78539-4','Transplant surgery Checklist','surgery|transplant'),
('http://loinc.org','78542-8','Vascular surgery Checklist','surgery'),
('http://loinc.org','78544-4','Pediatric surgery Checklist','surgery'),
('http://loinc.org','78572-5','Radiation oncology Diagnostic study note','oncology'),
('http://loinc.org','78576-6','Urology Diagnostic study note','urology'),
('http://loinc.org','78583-2','Pharmacology Discharge instructions',''),
('http://loinc.org','78589-9','Pharmacology Discharge teaching note',''),
('http://loinc.org','78595-6','Radiation oncology Education note','oncology'),
('http://loinc.org','78597-2','Vascular surgery Education note','surgery'),
('http://loinc.org','78598-0','Transplant surgery Education note','surgery|transplant'),
('http://loinc.org','78601-2','Pharmacology Education note',''),
('http://loinc.org','78603-8','Urology Education note','urology'),
('http://loinc.org','78606-1','Pediatric surgery Education note','surgery'),
('http://loinc.org','78620-2','Vascular surgery Flowsheet','surgery'),
('http://loinc.org','78622-8','Urology Flowsheet','urology'),
('http://loinc.org','78627-7','Pediatric surgery Flowsheet','surgery'),
('http://loinc.org','78628-5','Radiation oncology Flowsheet','oncology'),
('http://loinc.org','78629-3','Transplant surgery Flowsheet','surgery|transplant'),
('http://loinc.org','78645-9','Urology Initial evaluation note','urology'),
('http://loinc.org','78653-3','Radiation oncology Initial evaluation note','oncology'),
('http://loinc.org','78656-6','Radiation oncology procedure note','oncology'),
('http://loinc.org','78659-0','Urology procedure note','urology'),
('http://loinc.org','78665-7','Radiation oncology Progress note','oncology'),
('http://loinc.org','78673-1','Pediatric surgery Referral note','surgery'),
('http://loinc.org','78675-6','Pastoral care Referral note',''),
('http://loinc.org','78677-2','Transplant surgery Referral note','surgery|transplant'),
('http://loinc.org','78680-6','Vascular surgery Transfer summary note','surgery'),
('http://loinc.org','78683-0','Transplant surgery Transfer summary note','surgery|transplant'),
('http://loinc.org','78706-9','Oncology Form','oncology'),
('http://loinc.org','78724-2','Pediatric surgery Admission history and physical note','surgery'),
('http://loinc.org','78725-9','Pediatric surgery Surgical operation note','operation|surgery|surgical'),
('http://loinc.org','78729-1','Surgery Transfer summary note','surgery'),
('http://loinc.org','78731-7','Transplant surgery Admission history and physical note','surgery|transplant'),
('http://loinc.org','78733-3','Urology Admission history and physical note','urology'),
('http://loinc.org','78734-1','Urology Checklist','urology'),
('http://loinc.org','78735-8','Urology Preoperative evaluation and management note','operative|urology'),
('http://loinc.org','78736-6','Urology Transfer summary note','urology'),
('http://loinc.org','78737-4','Vascular surgery Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','80569-7','Pharmacology Progress note',''),
('http://loinc.org','80671-1','Pastoral care Progress note',''),
('http://loinc.org','80736-2','Blood banking and transfusion medicine Consult note',''),
('http://loinc.org','80739-6','Infectious disease Plan of care note','infectious disease'),
('http://loinc.org','80740-4','Hematology Plan of care note',''),
('http://loinc.org','80741-2','Emergency medicine Emergency department Plan of care note',''),
('http://loinc.org','80751-1','Dermatology Plan of care note','dermatology'),
('http://loinc.org','80753-7','Surgery Plan of care note','surgery'),
('http://loinc.org','80755-2','Nephrology Plan of care note','nephrology'),
('http://loinc.org','80759-4','Oncology Plan of care note','oncology'),
('http://loinc.org','80763-6','Transplant surgery Plan of care note','surgery|transplant'),
('http://loinc.org','80767-7','Pediatric surgery Plan of care note','surgery'),
('http://loinc.org','80768-5','Vascular surgery Plan of care note','surgery'),
('http://loinc.org','80783-4','Urology Plan of care note','urology'),
('http://loinc.org','80785-9','Radiation oncology Plan of care note','oncology'),
('http://loinc.org','80790-9','Surgical critical care Plan of care note','surgical'),
('http://loinc.org','80797-4','Pharmacology Plan of care note',''),
('http://loinc.org','80799-0','Surgical oncology Admission history and physical note','oncology|surgical'),
('http://loinc.org','80800-6','Surgical oncology Checklist','oncology|surgical'),
('http://loinc.org','80801-4','Surgical oncology Consult note','oncology|surgical'),
('http://loinc.org','80802-2','Surgical oncology Education note','oncology|surgical'),
('http://loinc.org','80803-0','Surgical oncology Flowsheet','oncology|surgical'),
('http://loinc.org','80804-8','Surgical oncology Plan of care note','oncology|surgical'),
('http://loinc.org','80805-5','Surgical oncology Preoperative evaluation and management note','oncology|operative|surgical'),
('http://loinc.org','80806-3','Surgical oncology Referral note','oncology|surgical'),
('http://loinc.org','80807-1','Surgical oncology Surgical operation note','oncology|operation|surgical'),
('http://loinc.org','80808-9','Surgical oncology Transfer summary note','oncology|surgical'),
('http://loinc.org','81191-9','Chemical pathology Consult note','pathology'),
('http://loinc.org','81192-7','Clinical pathology Consult note','pathology'),
('http://loinc.org','81193-5','Medical microbiology - pathology Consult note','pathology'),
('http://loinc.org','81196-8','Clinical pharmacology Consult note',''),
('http://loinc.org','82835-0','Transplant surgery Initial evaluation note','surgery|transplant'),
('http://loinc.org','82836-8','Pediatric surgery Initial evaluation note','surgery'),
('http://loinc.org','82837-6','Pharmacology Initial evaluation note',''),
('http://loinc.org','82838-4','Vascular surgery Initial evaluation note','surgery'),
('http://loinc.org','82839-2','Surgical oncology Initial evaluation note','oncology|surgical'),
('http://loinc.org','83320-2','Allergy and Immunology Adverse event note',''),
('http://loinc.org','83543-9','Dermatology Nurse practitioner Note','dermatology'),
('http://loinc.org','83546-2','Hematology+Medical oncology Nurse practitioner Note','oncology'),
('http://loinc.org','83548-8','Nephrology Nurse practitioner Note','nephrology'),
('http://loinc.org','83562-9','Surgery Nurse practitioner Note','surgery'),
('http://loinc.org','83563-7','Urology Nurse practitioner Note','urology'),
('http://loinc.org','83564-5','Vascular surgery Nurse practitioner Note','surgery'),
('http://loinc.org','83565-2','Allergy and Immunology Nurse Note',''),
('http://loinc.org','83566-0','Allergy and Immunology Nurse Outpatient Note',''),
('http://loinc.org','83567-8','Anesthesiology Nurse Note',''),
('http://loinc.org','83568-6','Dermatology Nurse Note','dermatology'),
('http://loinc.org','83569-4','Dermatology Nurse Outpatient Note','dermatology'),
('http://loinc.org','83578-5','Hematology+Medical oncology Nurse Consult note','oncology'),
('http://loinc.org','83579-3','Hematology+Medical oncology Nurse Note','oncology'),
('http://loinc.org','83580-1','Hematology+Medical oncology Nurse Outpatient Note','oncology'),
('http://loinc.org','83583-5','Nephrology Nurse Note','nephrology'),
('http://loinc.org','83584-3','Nephrology Nurse Outpatient Note','nephrology'),
('http://loinc.org','83592-6','Pathology Nurse Note','pathology'),
('http://loinc.org','83593-4','Radiation oncology Nurse Education note','oncology'),
('http://loinc.org','83594-2','Radiation oncology Nurse Note','oncology'),
('http://loinc.org','83597-5','Urology Nurse Note','urology'),
('http://loinc.org','83598-3','Urology Nurse Outpatient Note','urology'),
('http://loinc.org','83599-1','Urology Nurse procedure note','urology'),
('http://loinc.org','83612-2','Surgery Nurse Hospital Note','surgery'),
('http://loinc.org','83613-0','Surgery Nurse Note','surgery'),
('http://loinc.org','83614-8','Surgery Nurse Surgical operation note','operation|surgery|surgical'),
('http://loinc.org','83615-5','Surgery Nurse Outpatient Note','surgery'),
('http://loinc.org','83616-3','Surgery Nurse Outpatient procedure note','surgery'),
('http://loinc.org','83617-1','Surgery Nurse procedure note','surgery'),
('http://loinc.org','83618-9','Vascular surgery Nurse Note','surgery'),
('http://loinc.org','83619-7','Vascular surgery Nurse Outpatient Note','surgery'),
('http://loinc.org','83620-5','Blood banking and transfusion medicine Nurse Note',''),
('http://loinc.org','83626-2','Infectious disease Nurse Note','infectious disease'),
('http://loinc.org','83627-0','Infectious disease Nurse Outpatient Note','infectious disease'),
('http://loinc.org','83670-0','Surgery Attending Admission evaluation note','surgery'),
('http://loinc.org','83671-8','Surgery Attending Intensive care unit Admission evaluation note','surgery'),
('http://loinc.org','83672-6','Surgery Attending Intensive care unit Note','surgery'),
('http://loinc.org','83673-4','Surgery Attending Surgical operation note','operation|surgery|surgical'),
('http://loinc.org','83674-2','Surgery Attending Outpatient Note','surgery'),
('http://loinc.org','83675-9','Surgery Attending Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','83676-7','Transplant surgery Attending Note','surgery|transplant'),
('http://loinc.org','83677-5','Vascular surgery Attending Admission evaluation note','surgery'),
('http://loinc.org','83678-3','Vascular surgery Attending Note','surgery'),
('http://loinc.org','83679-1','Vascular surgery Attending Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','83680-9','Anesthesiology Attending Note',''),
('http://loinc.org','83681-7','Anesthesiology Attending Preoperative evaluation and management note','operative'),
('http://loinc.org','83682-5','Dermatology Attending Note','dermatology'),
('http://loinc.org','83685-8','Hematology+Medical oncology Attending Consult note','oncology'),
('http://loinc.org','83686-6','Hematology+Medical oncology Attending Note','oncology'),
('http://loinc.org','83687-4','Nephrology Attending Note','nephrology'),
('http://loinc.org','83697-3','Radiation oncology Attending Note','oncology'),
('http://loinc.org','83699-9','Urology Attending Admission evaluation note','urology'),
('http://loinc.org','83700-5','Urology Attending Note','urology'),
('http://loinc.org','83701-3','Urology Attending Preoperative evaluation and management note','operative|urology'),
('http://loinc.org','83739-3','Hematology+Medical oncology Fellow Note','oncology'),
('http://loinc.org','83740-1','Infectious disease Fellow Note','infectious disease'),
('http://loinc.org','83741-9','Nephrology Fellow Note','nephrology'),
('http://loinc.org','83751-8','Urology Physician assistant Note','urology'),
('http://loinc.org','83752-6','Vascular surgery Physician assistant Note','surgery'),
('http://loinc.org','83754-2','Dermatology Resident Note','dermatology'),
('http://loinc.org','83758-3','Hematology+Medical oncology Resident Note','oncology'),
('http://loinc.org','83759-1','Infectious disease Resident Note','infectious disease'),
('http://loinc.org','83762-5','Nephrology Resident Note','nephrology'),
('http://loinc.org','83775-7','Radiation oncology Resident Note','oncology'),
('http://loinc.org','83778-1','Surgery Resident Admission evaluation note','surgery'),
('http://loinc.org','83779-9','Surgery Resident Note','surgery'),
('http://loinc.org','83780-7','Transplant surgery Resident Note','surgery|transplant'),
('http://loinc.org','83781-5','Urology Resident Note','urology'),
('http://loinc.org','83782-3','Vascular surgery Resident Note','surgery'),
('http://loinc.org','83783-1','Infectious disease Attending Note','infectious disease'),
('http://loinc.org','83792-2','Surgery Intern Admission evaluation note','surgery'),
('http://loinc.org','83840-9','Vascular surgery Technician Note','surgery'),
('http://loinc.org','83841-7','Transplant surgery Case manager Note','surgery|transplant'),
('http://loinc.org','83842-5','Surgery Interdisciplinary Note','surgery'),
('http://loinc.org','83843-3','Surgery Case manager Note','surgery'),
('http://loinc.org','83917-5','Radiation oncology Hospital Note','oncology'),
('http://loinc.org','83918-3','Radiation oncology Outpatient Note','oncology'),
('http://loinc.org','83919-1','Radiation oncology Telephone encounter Note','oncology'),
('http://loinc.org','83920-9','Radiation oncology Therapist Note','oncology'),
('http://loinc.org','84012-4','Surgery Intensive care unit Admission evaluation note','surgery'),
('http://loinc.org','84013-2','Surgery Intensive care unit Discharge summary','surgery'),
('http://loinc.org','84014-0','Surgery Intensive care unit Note','surgery'),
('http://loinc.org','84015-7','Surgery Intensive care unit procedure note','surgery'),
('http://loinc.org','84016-5','Surgery Intensive care unit Transfer summary note','surgery'),
('http://loinc.org','84017-3','Surgery Discharge summary','surgery'),
('http://loinc.org','84018-1','Surgery Outpatient Discharge summary','surgery'),
('http://loinc.org','84019-9','Surgery Outpatient History and physical note','surgery'),
('http://loinc.org','84020-7','Surgery Outpatient Surgical operation note','operation|surgery|surgical'),
('http://loinc.org','84021-5','Surgery Outpatient procedure note','surgery'),
('http://loinc.org','84022-3','Surgery Telephone encounter Note','surgery'),
('http://loinc.org','84035-5','Transplant surgery Consult note','surgery|transplant'),
('http://loinc.org','84036-3','Transplant surgery Outpatient Note','surgery|transplant'),
('http://loinc.org','84037-1','Transplant surgery Telephone encounter Note','surgery|transplant'),
('http://loinc.org','84038-9','Urology Administrative note','urology'),
('http://loinc.org','84039-7','Urology Admission evaluation note','urology'),
('http://loinc.org','84040-5','Urology Discharge summary','urology'),
('http://loinc.org','84041-3','Urology History and physical note','urology'),
('http://loinc.org','84042-1','Urology Hospital Note','urology'),
('http://loinc.org','84043-9','Urology Interdisciplinary Note','urology'),
('http://loinc.org','84044-7','Urology Outpatient procedure note','urology'),
('http://loinc.org','84045-4','Urology Postoperative evaluation and management note','operative|urology'),
('http://loinc.org','84046-2','Urology Telephone encounter Note','urology'),
('http://loinc.org','84047-0','Vascular surgery Admission evaluation note','surgery'),
('http://loinc.org','84048-8','Vascular surgery History and physical note','surgery'),
('http://loinc.org','84049-6','Vascular surgery Hospital Note','surgery'),
('http://loinc.org','84050-4','Vascular surgery Note','surgery'),
('http://loinc.org','84051-2','Vascular surgery Outpatient Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','84052-0','Vascular surgery Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','84053-8','Vascular surgery procedure note','surgery'),
('http://loinc.org','84054-6','Vascular surgery Telephone encounter Note','surgery'),
('http://loinc.org','84057-9','Allergy and Immunology Outpatient Note',''),
('http://loinc.org','84058-7','Anesthesiology Flowsheet',''),
('http://loinc.org','84059-5','Anesthesiology Hospital Note',''),
('http://loinc.org','84060-3','Anesthesiology Outpatient Note',''),
('http://loinc.org','84061-1','Anesthesiology Postoperative evaluation and management note','operative'),
('http://loinc.org','84062-9','Anesthesiology procedure note',''),
('http://loinc.org','84063-7','Anesthesiology Telephone encounter Note',''),
('http://loinc.org','84067-8','Blood banking and transfusion medicine Note',''),
('http://loinc.org','84076-9','Dermatology Administrative note','dermatology'),
('http://loinc.org','84077-7','Dermatology History and physical note','dermatology'),
('http://loinc.org','84078-5','Dermatology Hospital Note','dermatology'),
('http://loinc.org','84079-3','Dermatology Surgical operation note','dermatology|operation|surgical'),
('http://loinc.org','84080-1','Dermatology Outpatient Note','dermatology'),
('http://loinc.org','84081-9','Dermatology Outpatient procedure note','dermatology'),
('http://loinc.org','84082-7','Dermatology Telephone encounter Note','dermatology'),
('http://loinc.org','84083-5','Dermatology Transfer summary note','dermatology'),
('http://loinc.org','84096-7','Emergency medicine Telephone encounter Note',''),
('http://loinc.org','84137-9','Hematology+Medical oncology Pharmacist Note','oncology'),
('http://loinc.org','84138-7','Hematology+Medical oncology Conference note','oncology'),
('http://loinc.org','84139-5','Hematology+Medical oncology Discharge summary','oncology'),
('http://loinc.org','84140-3','Hematology+Medical oncology Education note','oncology'),
('http://loinc.org','84141-1','Hematology+Medical oncology Group counseling note','oncology'),
('http://loinc.org','84142-9','Hematology+Medical oncology Hospital Consult note','oncology'),
('http://loinc.org','84143-7','Hematology+Medical oncology Hospital Note','oncology'),
('http://loinc.org','84144-5','Hematology+Medical oncology Medication management note','oncology'),
('http://loinc.org','84145-2','Hematology+Medical oncology Outpatient Consult note','oncology'),
('http://loinc.org','84146-0','Hematology+Medical oncology Outpatient Note','oncology'),
('http://loinc.org','84147-8','Hematology+Medical oncology procedure note','oncology'),
('http://loinc.org','84148-6','Hematology+Medical oncology Risk assessment and screening note','oncology'),
('http://loinc.org','84149-4','Hematology+Medical oncology Team Note','oncology'),
('http://loinc.org','84150-2','Hematology+Medical oncology Telephone encounter Note','oncology'),
('http://loinc.org','84151-0','Hematology+Medical oncology Plan of care note','oncology'),
('http://loinc.org','84166-8','Infectious disease Counseling note','infectious disease'),
('http://loinc.org','84167-6','Infectious disease Group counseling note','infectious disease'),
('http://loinc.org','84168-4','Infectious disease Hospital Note','infectious disease'),
('http://loinc.org','84169-2','Infectious disease Outpatient Note','infectious disease'),
('http://loinc.org','84170-0','Infectious disease Risk assessment and screening note','infectious disease'),
('http://loinc.org','84171-8','Infectious disease Telephone encounter Note','infectious disease'),
('http://loinc.org','84190-8','Medical toxicology Consult note',''),
('http://loinc.org','84191-6','Medical toxicology Note',''),
('http://loinc.org','84219-5','Nephrology Patients home Note','nephrology'),
('http://loinc.org','84220-3','Nephrology Hospital Note','nephrology'),
('http://loinc.org','84221-1','Nephrology Hospital Transfer summary note','nephrology'),
('http://loinc.org','84222-9','Nephrology Outpatient Note','nephrology'),
('http://loinc.org','84223-7','Nephrology Team Note','nephrology'),
('http://loinc.org','84224-5','Nephrology Telephone encounter Note','nephrology'),
('http://loinc.org','84334-2','Pathology Telephone encounter Note','pathology'),
('http://loinc.org','84335-9','Pathology Outpatient Note','pathology'),
('http://loinc.org','84336-7','Pathology Letter','pathology'),
('http://loinc.org','84337-5','Pastoral care Plan of care note',''),
('http://loinc.org','84338-3','Pastoral care Telephone encounter Note',''),
('http://loinc.org','84339-1','Pastoral care Team Note',''),
('http://loinc.org','84340-9','Pastoral care Risk assessment and screening note',''),
('http://loinc.org','84341-7','Pastoral care Outpatient Note',''),
('http://loinc.org','84342-5','Pastoral care Long term care facility Note',''),
('http://loinc.org','84343-3','Pastoral care Hospital Note',''),
('http://loinc.org','84344-1','Pastoral care Initial evaluation note',''),
('http://loinc.org','84345-8','Pastoral care Patients home Note',''),
('http://loinc.org','84346-6','Pastoral care Group counseling note',''),
('http://loinc.org','84347-4','Pastoral care Education note',''),
('http://loinc.org','84348-2','Pastoral care Counseling note',''),
('http://loinc.org','84349-0','Pastoral care Consult note',''),
('http://loinc.org','85153-5','Pharmacology Admission evaluation note',''),
('http://loinc.org','85154-3','Pharmacology Discharge summary',''),
('http://loinc.org','85155-0','Pharmacology Evaluation and management of hyperlipidemia note',''),
('http://loinc.org','85156-8','Pharmacology Evaluation and management of hypertension note',''),
('http://loinc.org','85157-6','Pharmacology Hospital Note',''),
('http://loinc.org','85158-4','Pharmacology Letter',''),
('http://loinc.org','85159-2','Pharmacology Long term care facility Admission evaluation note',''),
('http://loinc.org','85160-0','Pharmacology Long term care facility Medication management note',''),
('http://loinc.org','85161-8','Pharmacology Long term care facility Note',''),
('http://loinc.org','85162-6','Pharmacology Nurse Outpatient Evaluation and management of anticoagulation note',''),
('http://loinc.org','85163-4','Pharmacology Outpatient Counseling note',''),
('http://loinc.org','85164-2','Pharmacology Outpatient Evaluation and management of anticoagulation note',''),
('http://loinc.org','85165-9','Pharmacology Outpatient Evaluation and management of hyperlipidemia note',''),
('http://loinc.org','85166-7','Pharmacology Outpatient Medication management note',''),
('http://loinc.org','85167-5','Pharmacology Patients home Medication management note',''),
('http://loinc.org','85168-3','Pharmacology Patients home Note',''),
('http://loinc.org','85169-1','Pharmacology Team Note',''),
('http://loinc.org','85170-9','Pharmacology Technician Note',''),
('http://loinc.org','85231-9','Tumor board Note',''),
('http://loinc.org','85232-7','Tumor board Consult note',''),
('http://loinc.org','85264-0','Infectious disease Transplant candidate evaluation note','infectious disease|transplant'),
('http://loinc.org','85440-6','Vascular surgery Discharge summary','surgery'),
('http://loinc.org','85441-4','Vascular surgery Progress note','surgery'),
('http://loinc.org','85442-2','Hematology Discharge summary',''),
('http://loinc.org','85443-0','Hematology Note',''),
('http://loinc.org','85588-2','Hematology+Medical oncology Diagnostic study note','oncology'),
('http://loinc.org','85849-8','Anesthesiology Recovery room Discharge summary',''),
('http://loinc.org','85887-8','Dermatology Postoperative evaluation and management note','dermatology|operative'),
('http://loinc.org','85898-5','Surgery Diagnostic study note','surgery'),
('http://loinc.org','85945-4','Surgery Outpatient Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','85946-2','Surgery Outpatient Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','85947-0','Surgery Nurse Outpatient Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','85948-8','Surgery Attending Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','86215-1','Hematology+Medical oncology Disease staging note','oncology'),
('http://loinc.org','86664-0','HIV Referral note',''),
('http://loinc.org','87233-3','Dialysis Consult note',''),
('http://loinc.org','87234-1','Dialysis Education note',''),
('http://loinc.org','87235-8','Dialysis Discharge summary',''),
('http://loinc.org','87236-6','Dialysis Summary note',''),
('http://loinc.org','87237-4','Dialysis Plan of care note',''),
('http://loinc.org','87238-2','Dialysis Note',''),
('http://loinc.org','87265-5','Dialysis Interdisciplinary Plan of care note',''),
('http://loinc.org','87266-3','Dialysis Nurse Note',''),
('http://loinc.org','87267-1','Dialysis Physician Note',''),
('http://loinc.org','88357-9','Infectious disease Alert','infectious disease'),
('http://loinc.org','88360-3','Pharmacology Alert',''),
('http://loinc.org','88648-1','Hematology+Medical oncology Parenteral therapy note','oncology'),
('http://loinc.org','88652-3','Surgery Parenteral therapy note','surgery'),
('http://loinc.org','89031-9','Hematology Telehealth Consult note',''),
('http://loinc.org','89032-7','Nephrology Telehealth Consult note','nephrology'),
('http://loinc.org','89033-5','Urology Telehealth Consult note','urology'),
('http://loinc.org','89794-2','Anesthesiology Team Conference note',''),
('http://loinc.org','89795-9','Blood banking and transfusion medicine Progress note',''),
('http://loinc.org','89796-7','Blood banking and transfusion medicine procedure note',''),
('http://loinc.org','89797-5','Blood banking and transfusion medicine Telephone encounter Note',''),
('http://loinc.org','89804-9','Hematology Telephone encounter Note',''),
('http://loinc.org','89811-4','Anesthesiology Progress note',''),
('http://loinc.org','89825-4','Vascular surgery Team Conference note','surgery'),
('http://loinc.org','89826-2','Clinical pharmacology procedure note',''),
('http://loinc.org','89883-3','Emergency medicine Telehealth Note',''),
('http://loinc.org','89884-1','Hematology+Medical oncology Telehealth Note','oncology'),
('http://loinc.org','89892-4','Infectious disease Telehealth Note','infectious disease'),
('http://loinc.org','89895-7','Allergy and Immunology Telehealth Note',''),
('http://loinc.org','89898-1','Nephrology Telehealth Note','nephrology'),
('http://loinc.org','89903-9','Urology Telehealth Note','urology'),
('http://loinc.org','90009-2','Clinical pathology Team Conference note','pathology'),
('http://loinc.org','90010-0','Clinical pathology procedure note','pathology'),
('http://loinc.org','90011-8','Clinical pathology Progress note','pathology'),
('http://loinc.org','90013-4','Clinical pathology Initial evaluation note','pathology'),
('http://loinc.org','90015-9','Clinical pathology Telephone encounter Note','pathology'),
('http://loinc.org','90371-6','Clinical pathology Note','pathology'),
('http://loinc.org','90717-0','Heart failure+Transplant cardiology Consult note','transplant'),
('http://loinc.org','92913-3','Immunology Telehealth Note',''),
('http://loinc.org','92914-1','Immunology Outpatient Note',''),
('http://loinc.org','92915-8','Immunology Consult note',''),
('http://loinc.org','93894-4','Hematology Team Conference note',''),
('http://loinc.org','93956-1','Heart failure+Transplant cardiology Letter','transplant'),
('http://loinc.org','93959-5','Heart failure+Transplant cardiology Diagnostic study note','transplant'),
('http://loinc.org','93960-3','Immunology Diagnostic study note',''),
('http://loinc.org','93962-9','Nephrology Diagnostic study note','nephrology'),
('http://loinc.org','94461-1','Solid Organ Transplant Consult note','transplant'),
('http://loinc.org','94463-7','Bone Marrow Transplant Consult note','transplant'),
('http://loinc.org','94464-5','Solid Organ Transplant Discharge summary','transplant'),
('http://loinc.org','94465-2','Bone Marrow Transplant Discharge summary','transplant'),
('http://loinc.org','94466-0','Solid Organ Transplant Progress note','transplant'),
('http://loinc.org','94468-6','Bone Marrow Transplant Progress note','transplant'),
('http://loinc.org','94515-4','Anesthesiology Discharge summary',''),
('http://loinc.org','94519-6','Dermatology Discharge summary','dermatology'),
('http://loinc.org','94522-0','Immunology Discharge summary',''),
('http://loinc.org','94525-3','Infectious disease Discharge summary','infectious disease'),
('http://loinc.org','94595-6','Pharmacology Telehealth Medication management note',''),
('http://loinc.org','94771-3','Anesthesiology Telehealth Note',''),
('http://loinc.org','94772-1','Blood banking and transfusion medicine Telehealth Note',''),
('http://loinc.org','94777-0','Dermatology Telehealth Note','dermatology'),
('http://loinc.org','94782-0','Surgery Telehealth Note','surgery'),
('http://loinc.org','94786-1','Hematology Telehealth Note',''),
('http://loinc.org','94788-7','Clinical pathology Telehealth Note','pathology'),
('http://loinc.org','94792-9','Oncology Telehealth Note','oncology'),
('http://loinc.org','94795-2','Pastoral care Telehealth Note',''),
('http://loinc.org','94796-0','Pharmacology Telehealth Note',''),
('http://loinc.org','94799-4','Radiation oncology Telehealth Note','oncology'),
('http://loinc.org','94805-9','Vascular surgery Telehealth Note','surgery'),
('http://loinc.org','95132-7','Dialysis and Therapeutic apheresis Consult note',''),
('http://loinc.org','95133-5','Dialysis and Therapeutic apheresis Discharge summary',''),
('http://loinc.org','95134-3','Dialysis and Therapeutic apheresis Progress note',''),
('http://loinc.org','95746-4','Immunology Progress note',''),
('http://loinc.org','95747-2','Immunology Referral note',''),
('http://loinc.org','95748-0','Immunology Education note',''),
('http://loinc.org','95749-8','Immunology Initial evaluation note',''),
('http://loinc.org','95750-6','Immunology procedure note',''),
('http://loinc.org','95751-4','Immunology Flowsheet',''),
('http://loinc.org','95752-2','Immunology Plan of care note',''),
('http://loinc.org','95753-0','Immunology Evaluation note',''),
('http://loinc.org','96130-0','Surgical oncology Evaluation note','oncology|surgical'),
('http://loinc.org','96133-4','Pharmacology Evaluation note',''),
('http://loinc.org','96137-5','Oncology Evaluation note','oncology'),
('http://loinc.org','96140-9','Nephrology Evaluation note','nephrology'),
('http://loinc.org','96145-8','Emergency medicine Evaluation note',''),
('http://loinc.org','96147-4','Vascular surgery Evaluation note','surgery'),
('http://loinc.org','96148-2','Transplant surgery Evaluation note','surgery|transplant'),
('http://loinc.org','96151-6','Pediatric surgery Evaluation note','surgery'),
('http://loinc.org','96158-1','Urology Evaluation note','urology'),
('http://loinc.org','96161-5','Infectious disease Evaluation note','infectious disease'),
('http://loinc.org','96169-8','Dermatology Evaluation note','dermatology'),
('http://loinc.org','96173-0','Clinical pathology Evaluation note','pathology'),
('http://loinc.org','96183-9','Dermatology Photographic image','dermatology'),
('http://loinc.org','96337-1','Hematology Outpatient Note',''),
('http://loinc.org','96343-9','Oncology Outpatient Note','oncology'),
('http://loinc.org','96344-7','Oncology Summary note','oncology'),
('http://loinc.org','96373-6','Bone Marrow Transplant Admission evaluation note','transplant'),
('http://loinc.org','96374-4','Dialysis and Therapeutic apheresis Admission evaluation note',''),
('http://loinc.org','96377-7','Nephrology Surgical operation note','nephrology|operation|surgical'),
('http://loinc.org','97577-1','Heart failure+Transplant cardiology Progress note','transplant'),
('http://loinc.org','97659-7','Emergency medicine Emergency department Admission history and physical note',''),
('http://loinc.org','97660-5','Emergency medicine Emergency department Evaluation note',''),
('http://loinc.org','97661-3','Emergency medicine Emergency department Checklist',''),
('http://loinc.org','97662-1','Emergency medicine Emergency department Discharge instructions',''),
('http://loinc.org','97663-9','Emergency medicine Emergency department Discharge summary',''),
('http://loinc.org','97664-7','Emergency medicine Emergency department Discharge teaching note',''),
('http://loinc.org','97665-4','Emergency medicine Emergency department Education note',''),
('http://loinc.org','97666-2','Emergency medicine Emergency department History and physical note',''),
('http://loinc.org','97667-0','Emergency medicine Emergency department Initial evaluation note',''),
('http://loinc.org','97668-8','Emergency medicine Emergency department procedure note',''),
('http://loinc.org','97669-6','Emergency medicine Emergency department Progress note',''),
('http://loinc.org','97670-4','Emergency medicine Emergency department Transfer summary note',''),
('http://loinc.org','97671-2','Emergency medicine Emergency department Triage note',''),
('http://loinc.org','97676-1','Anesthesiology History and physical note',''),
('http://loinc.org','97680-3','Infectious disease History and physical note','infectious disease'),
('http://loinc.org','97682-9','Pharmacology History and physical note',''),
('http://loinc.org','97683-7','Radiation oncology History and physical note','oncology'),
('http://loinc.org','97695-1','Solid Organ Transplant Evaluation note','transplant'),
('http://loinc.org','97697-7','Radiation oncology Evaluation note','oncology'),
('http://loinc.org','97699-3','Pastoral care Evaluation note',''),
('http://loinc.org','97704-1','Radiation oncology Discharge summary','oncology'),
('http://loinc.org','97707-4','Solid Organ Transplant procedure note','transplant'),
('http://loinc.org','97722-3','Hematology Evaluation note',''),
('http://loinc.org','97723-1','Hematology History and physical note',''),
('http://loinc.org','99480-6','Solid Organ Transplant History and physical note','transplant')
) AS t (system,code,display,keyword) ;