create or replace view $prefix__fhir_diagnostic_service as select * from (values
('http://loinc.org','LP29684-5','Radiology'),
('http://loinc.org','LP29708-2','Cardiology'),
('http://loinc.org','LP75011-4','Laboratory'),
('http://loinc.org','LP7819-8','Microbiology'),
('http://loinc.org','LP7839-6','Pathology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','AU','Audiology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','BG','Blood Gases'),
('http://terminology.hl7.org/CodeSystem/v2-0074','BLB','Blood Bank'),
('http://terminology.hl7.org/CodeSystem/v2-0074','CG','Cytogenetics'),
('http://terminology.hl7.org/CodeSystem/v2-0074','CUS','Cardiac Ultrasound'),
('http://terminology.hl7.org/CodeSystem/v2-0074','CTH','Cardiac Catheterization'),
('http://terminology.hl7.org/CodeSystem/v2-0074','CT','CAT Scan'),
('http://terminology.hl7.org/CodeSystem/v2-0074','CH','Chemistry'),
('http://terminology.hl7.org/CodeSystem/v2-0074','CP','Cytopathology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','EC','Electrocardiac(EKG, EEC, Holter)'),
('http://terminology.hl7.org/CodeSystem/v2-0074','EN','Electroneuro (EEG, EMG,EP,PSG)'),
('http://terminology.hl7.org/CodeSystem/v2-0074','GE','Genetics'),
('http://terminology.hl7.org/CodeSystem/v2-0074','HM','Hematology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','IMG','Diagnostic Imaging'),
('http://terminology.hl7.org/CodeSystem/v2-0074','ICU','Bedside ICU Monitoring'),
('http://terminology.hl7.org/CodeSystem/v2-0074','IMM','Immunology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','LAB','Laboratory'),
('http://terminology.hl7.org/CodeSystem/v2-0074','MB','Microbiology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','MCB','Mycobacteriology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','MYC','Mycology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','NMS','Nuclear Medicine Scan'),
('http://terminology.hl7.org/CodeSystem/v2-0074','NMR','Nuclear Magnetic Resonance'),
('http://terminology.hl7.org/CodeSystem/v2-0074','NRS','Nursing Service Measures'),
('http://terminology.hl7.org/CodeSystem/v2-0074','OUS','OB Ultrasound'),
('http://terminology.hl7.org/CodeSystem/v2-0074','OT','Occupational Therapy'),
('http://terminology.hl7.org/CodeSystem/v2-0074','OTH','Other'),
('http://terminology.hl7.org/CodeSystem/v2-0074','OSL','Outside Lab'),
('http://terminology.hl7.org/CodeSystem/v2-0074','PAR','Parasitology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','PHR','Pharmacy'),
('http://terminology.hl7.org/CodeSystem/v2-0074','PAT','Pathology (gross & histopath, not surgical)'),
('http://terminology.hl7.org/CodeSystem/v2-0074','PT','Physical Therapy'),
('http://terminology.hl7.org/CodeSystem/v2-0074','PHY','Physician'),
('http://terminology.hl7.org/CodeSystem/v2-0074','PF','Pulmonary Function'),
('http://terminology.hl7.org/CodeSystem/v2-0074','RAD','Radiology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','RX','Radiograph'),
('http://terminology.hl7.org/CodeSystem/v2-0074','RUS','Radiology Ultrasound'),
('http://terminology.hl7.org/CodeSystem/v2-0074','RC','Respiratory Care (therapy)'),
('http://terminology.hl7.org/CodeSystem/v2-0074','RT','Radiation Therapy'),
('http://terminology.hl7.org/CodeSystem/v2-0074','SR','Serology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','SP','Surgical Pathology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','TX','Toxicology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','VUS','Vascular Ultrasound'),
('http://terminology.hl7.org/CodeSystem/v2-0074','VR','Virology'),
('http://terminology.hl7.org/CodeSystem/v2-0074','URN','Urinalysis'),
('http://terminology.hl7.org/CodeSystem/v2-0074','XRC','Cineradiograph')
) AS t (system,code,display) ;