create or replace view irae__doc_ontology_role as select * from (values
('http://loinc.org','100441-5','Attending Outpatient Progress note',''),
('http://loinc.org','100457-1','Consultant Outpatient Progress note',''),
('http://loinc.org','100532-1','Social worker Outpatient Progress note','social work'),
('http://loinc.org','100550-3','Attending Hospital Progress note',''),
('http://loinc.org','100565-1','Consultant Hospital Progress note',''),
('http://loinc.org','100639-4','Social worker Hospital Progress note','social work'),
('http://loinc.org','101898-5','Interdisciplinary Progress note',''),
('http://loinc.org','103964-3','Hospice care social worker Note','social work'),
('http://loinc.org','103965-0','Hospice care Interdisciplinary Note',''),
('http://loinc.org','103966-8','Hospice care case manager Note',''),
('http://loinc.org','108253-6','Community Health Worker Note',''),
('http://loinc.org','11490-0','Physician Discharge summary',''),
('http://loinc.org','11505-5','Physician procedure note',''),
('http://loinc.org','18733-6','Attending Progress note',''),
('http://loinc.org','18736-9','Physician Initial evaluation note',''),
('http://loinc.org','18739-3','Social worker Initial evaluation note','social work'),
('http://loinc.org','18763-3','Consultant Initial evaluation note',''),
('http://loinc.org','28568-4','Physician Emergency department Note',''),
('http://loinc.org','28569-2','Consultant Progress note',''),
('http://loinc.org','28573-4','Physician, Operation note','operation'),
('http://loinc.org','28616-1','Physician Transfer note',''),
('http://loinc.org','28626-0','Physician History and physical note',''),
('http://loinc.org','28653-4','Social worker Note','social work'),
('http://loinc.org','28654-2','Attending Initial evaluation note',''),
('http://loinc.org','28655-9','Attending Discharge summary',''),
('http://loinc.org','28656-7','Social worker Progress note','social work'),
('http://loinc.org','34106-5','Physician Hospital Discharge summary',''),
('http://loinc.org','34116-4','Physician Nursing facility History and physical note',''),
('http://loinc.org','34125-5','Case manager Patients home Progress note',''),
('http://loinc.org','34134-7','Attending Outpatient Supervisory note',''),
--('http://loinc.org','34135-4','Cardiology Attending Outpatient Supervisory note',''),
--('http://loinc.org','34136-2','Gastroenterology Attending Outpatient Supervisory note',''),
('http://loinc.org','34769-0','General medicine Attending Note',''),
('http://loinc.org','34773-2','Surgery Attending Note','surgery'),
('http://loinc.org','34794-8','Interdisciplinary Note',''),
('http://loinc.org','34841-7','Social worker Consult note','social work'),
('http://loinc.org','34842-5','Social worker Evaluation note','social work'),
--('http://loinc.org','34843-3','Social worker Group counseling note','social work'),
('http://loinc.org','34844-1','Social worker Telephone encounter Note','social work'),
('http://loinc.org','34862-3','General medicine Attending Hospital Admission evaluation note',''),
('http://loinc.org','34872-2','Social worker Counseling note','social work'),
('http://loinc.org','46210-1','Case manager Note',''),
('http://loinc.org','57164-6','Social worker Referral note','social work'),
('http://loinc.org','64065-6','Case manager Hospital Initial evaluation note',''),
('http://loinc.org','64069-8','Critical care medicine Attending Hospital Note',''),
--('http://loinc.org','64073-0','Cardiothoracic surgery Attending Hospital Note','surgery'),
--('http://loinc.org','64077-1','Pulmonary Attending Hospital Note',''),
('http://loinc.org','68473-8','Critical care medicine Attending Hospital Progress note',''),
--('http://loinc.org','68474-6','Physician Hospital Restraint note',''),
('http://loinc.org','68475-3','General medicine Attending Hospital Progress note',''),
--('http://loinc.org','68478-7','Pulmonary Attending Hospital Progress note',''),
('http://loinc.org','68480-3','Surgery Attending Hospital Progress note','surgery'),
--('http://loinc.org','68481-1','Cardiothoracic surgery Attending Hospital Progress note','surgery'),
--('http://loinc.org','68484-5','Cardiology Attending Hospital Progress note',''),
('http://loinc.org','73709-8','Prescription request Pharmacy Document from Pharmacist','pharmacy'),
--('http://loinc.org','75427-5','Mental health Case manager Note',''),
--('http://loinc.org','75433-3','Interdisciplinary Education note',''),
('http://loinc.org','75471-3','Attending Note',''),
('http://loinc.org','75472-1','Internal medicine Attending Note',''),
--('http://loinc.org','75473-9','Primary care Attending Note',''),
--('http://loinc.org','75474-7','Psychiatry Attending Note',''),
('http://loinc.org','75475-4','Physician Letter',''),
('http://loinc.org','75476-2','Physician Note',''),
('http://loinc.org','75477-0','Resident Note',''),
('http://loinc.org','75478-8','Internal medicine Resident Note',''),
--('http://loinc.org','75479-6','Primary care Physician Note',''),
--('http://loinc.org','78607-9','Social worker Education note','social work'),
('http://loinc.org','80672-9','Social worker Conference note','social work'),
--('http://loinc.org','80788-3','Social worker Plan of care note','social work'),
--('http://loinc.org','81200-8','Interdisciplinary Plan of care note',''),
--('http://loinc.org','83516-5','Cardiology Attending Intensive care unit Admission evaluation note',''),
--('http://loinc.org','83517-3','Cardiology Attending Intensive care unit Note',''),
--('http://loinc.org','83518-1','Cardiology Attending Note',''),
--('http://loinc.org','83519-9','Cardiology Attending Outpatient Note',''),
--('http://loinc.org','83520-7','Cardiology Case manager Note',''),
--('http://loinc.org','83527-2','Cardiology Fellow Note',''),
--('http://loinc.org','83528-0','Cardiology Fellow Outpatient Note',''),
--('http://loinc.org','83538-9','Cardiology Resident Note',''),
--('http://loinc.org','83656-9','Cardiothoracic surgery Attending Admission evaluation note','surgery'),
--('http://loinc.org','83657-7','Cardiothoracic surgery Attending Note','surgery'),
--('http://loinc.org','83658-5','Colon and rectal surgery Attending Note','surgery'),
--('http://loinc.org','83659-3','Neurological surgery Attending Admission evaluation note','surgery'),
--('http://loinc.org','83660-1','Neurological surgery Attending Note','surgery'),
--('http://loinc.org','83661-9','Neurological surgery Attending Preoperative evaluation and management note','operative|surgery'),
--('http://loinc.org','83662-7','Oral and maxillofacial surgery Attending Note','surgery'),
--('http://loinc.org','83663-5','Orthopaedic surgery Attending Note','surgery'),
--('http://loinc.org','83664-3','Orthopaedic surgery Attending Preoperative evaluation and management note','operative|surgery'),
--('http://loinc.org','83665-0','Plastic surgery Attending Admission evaluation note','surgery'),
--('http://loinc.org','83666-8','Plastic surgery Attending Note','surgery'),
--('http://loinc.org','83667-6','Plastic surgery Attending Preoperative evaluation and management note','operative|surgery'),
--('http://loinc.org','83668-4','Psychiatry Attending Admission evaluation note',''),
--('http://loinc.org','83669-2','Psychiatry Attending Hospital Note',''),
('http://loinc.org','83670-0','Surgery Attending Admission evaluation note','surgery'),
('http://loinc.org','83671-8','Surgery Attending Intensive care unit Admission evaluation note','surgery'),
('http://loinc.org','83672-6','Surgery Attending Intensive care unit Note','surgery'),
('http://loinc.org','83673-4','Surgery Attending Surgical operation note','operation|surgery|surgical'),
('http://loinc.org','83674-2','Surgery Attending Outpatient Note','surgery'),
('http://loinc.org','83675-9','Surgery Attending Postoperative evaluation and management note','operative|surgery'),
('http://loinc.org','83676-7','Transplant surgery Attending Note','surgery|transplant'),
('http://loinc.org','83677-5','Vascular surgery Attending Admission evaluation note','surgery'),
('http://loinc.org','83678-3','Vascular surgery Attending Note','surgery'),
('http://loinc.org','83679-1','Vascular surgery Attending Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','83680-9','Anesthesiology Attending Note',''),
('http://loinc.org','83681-7','Anesthesiology Attending Preoperative evaluation and management note','operative'),
('http://loinc.org','83682-5','Dermatology Attending Note','dermatology'),
--('http://loinc.org','83683-3','Endocrinology Attending Note',''),
--('http://loinc.org','83684-1','Gastroenterology Attending Note',''),
('http://loinc.org','83685-8','Hematology+Medical oncology Attending Consult note','oncology'),
('http://loinc.org','83686-6','Hematology+Medical oncology Attending Note','oncology'),
('http://loinc.org','83687-4','Nephrology Attending Note','nephrology'),
--('http://loinc.org','83688-2','Neurology Attending Admission evaluation note','urology'),
--('http://loinc.org','83689-0','Neurology Attending Note','urology'),
--('http://loinc.org','83690-8','Obstetrics and gynecology Attending Note',''),
--('http://loinc.org','83691-6','Ophthalmology Attending Note',''),
--('http://loinc.org','83692-4','Ophthalmology Attending Surgical operation note','operation|surgical'),
--('http://loinc.org','83693-2','Ophthalmology Attending Preoperative evaluation and management note','operative'),
--('http://loinc.org','83694-0','Otolaryngology Attending Admission evaluation note',''),
--('http://loinc.org','83695-7','Otolaryngology Attending Note',''),
--('http://loinc.org','83696-5','Otolaryngology Attending Preoperative evaluation and management note','operative'),
('http://loinc.org','83697-3','Radiation oncology Attending Note','oncology'),
--('http://loinc.org','83698-1','Rheumatology Attending Note',''),
('http://loinc.org','83699-9','Urology Attending Admission evaluation note','urology'),
('http://loinc.org','83700-5','Urology Attending Note','urology'),
('http://loinc.org','83701-3','Urology Attending Preoperative evaluation and management note','operative|urology'),
--('http://loinc.org','83702-1','Geriatric medicine Attending Note',''),
--('http://loinc.org','83703-9','Primary care Attending Patients home Note',''),
--('http://loinc.org','83704-7','Mental health Attending Note',''),
--('http://loinc.org','83705-4','Palliative care Attending Note',''),
--('http://loinc.org','83706-2','Primary care Attending Initial evaluation note',''),
--('http://loinc.org','83709-6','Physical medicine and rehabilitation Attending Note',''),
--('http://loinc.org','83710-4','Physical medicine and rehabilitation Case manager Note',''),
--('http://loinc.org','83713-8','Physical medicine and rehabilitation Interdisciplinary Note',''),
--('http://loinc.org','83726-0','Physical medicine and rehabilitation Physician Initial evaluation note',''),
--('http://loinc.org','83727-8','Physical medicine and rehabilitation Physician Note',''),
--('http://loinc.org','83729-4','Physical medicine and rehabilitation Resident Note',''),
--('http://loinc.org','83734-4','Physical medicine and rehabilitation Interdisciplinary Plan of care note',''),
--('http://loinc.org','83735-1','Colon and rectal surgery Fellow Note','surgery'),
--('http://loinc.org','83736-9','Endocrinology Fellow Note',''),
--('http://loinc.org','83737-7','Gastroenterology Fellow Note',''),
--('http://loinc.org','83738-5','Geriatric medicine Fellow Note',''),
('http://loinc.org','83739-3','Hematology+Medical oncology Fellow Note','oncology'),
('http://loinc.org','83740-1','Infectious disease Fellow Note','infectious disease'),
('http://loinc.org','83741-9','Nephrology Fellow Note','nephrology'),
--('http://loinc.org','83742-7','Ophthalmology Fellow Note',''),
--('http://loinc.org','83743-5','Plastic surgery Fellow Note','surgery'),
--('http://loinc.org','83744-3','Pulmonary Fellow Note',''),
--('http://loinc.org','83745-0','Rheumatology Fellow Note',''),
--('http://loinc.org','83746-8','Spinal cord injury medicine Fellow Hospital Note',''),
--('http://loinc.org','83753-4','Colon and rectal surgery Resident Note','surgery'),
('http://loinc.org','83754-2','Dermatology Resident Note','dermatology'),
--('http://loinc.org','83755-9','Endocrinology Resident Note',''),
--('http://loinc.org','83756-7','Gastroenterology Resident Note',''),
--('http://loinc.org','83757-5','Geriatric medicine Resident Note',''),
('http://loinc.org','83758-3','Hematology+Medical oncology Resident Note','oncology'),
('http://loinc.org','83759-1','Infectious disease Resident Note','infectious disease'),
('http://loinc.org','83760-9','Interventional radiology Resident Note',''),
--('http://loinc.org','83761-7','Mental health Resident Note',''),
('http://loinc.org','83762-5','Nephrology Resident Note','nephrology'),
--('http://loinc.org','83763-3','Neurology Resident Note','urology'),
--('http://loinc.org','83764-1','Neurological surgery Resident Note','surgery'),
--('http://loinc.org','83765-8','Obstetrics and gynecology Resident Note',''),
--('http://loinc.org','83766-6','Ophthalmology Resident Note',''),
--('http://loinc.org','83767-4','Oral and maxillofacial surgery Resident Note','surgery'),
--('http://loinc.org','83768-2','Orthopaedic surgery Resident Note','surgery'),
--('http://loinc.org','83769-0','Otolaryngology Resident Note',''),
--('http://loinc.org','83770-8','Palliative care Resident Note',''),
--('http://loinc.org','83771-6','Plastic surgery Resident Note','surgery'),
--('http://loinc.org','83772-4','Primary care Resident Note',''),
--('http://loinc.org','83773-2','Psychiatry Resident Note',''),
--('http://loinc.org','83774-0','Pulmonary Resident Note',''),
('http://loinc.org','83775-7','Radiation oncology Resident Note','oncology'),
--('http://loinc.org','83776-5','Rheumatology Resident Note',''),
--('http://loinc.org','83777-3','Spinal cord injury medicine Resident Hospital Note',''),
('http://loinc.org','83778-1','Surgery Resident Admission evaluation note','surgery'),
('http://loinc.org','83779-9','Surgery Resident Note','surgery'),
('http://loinc.org','83780-7','Transplant surgery Resident Note','surgery|transplant'),
('http://loinc.org','83781-5','Urology Resident Note','urology'),
('http://loinc.org','83782-3','Vascular surgery Resident Note','surgery'),
('http://loinc.org','83783-1','Infectious disease Attending Note','infectious disease'),
--('http://loinc.org','83784-9','Mental health Physician Note',''),
--('http://loinc.org','83785-6','Palliative care Physician Note',''),
--('http://loinc.org','83786-4','Primary care Physician History and physical note',''),
--('http://loinc.org','83787-2','Pulmonary Attending Note',''),
--('http://loinc.org','83788-0','Pulmonary Attending Outpatient Note',''),
--('http://loinc.org','83789-8','Pulmonary Attending procedure note',''),
--('http://loinc.org','83790-6','Spinal cord injury medicine Attending Note',''),
--('http://loinc.org','83791-4','Spinal cord injury medicine Physician Note',''),
--('http://loinc.org','83793-0','Physician Long term care facility Note',''),
--('http://loinc.org','83794-8','Physician Urgent care center Note',''),
--('http://loinc.org','83795-5','Physician Telephone encounter Note',''),
('http://loinc.org','83796-3','Physician Summary of death note',''),
('http://loinc.org','83797-1','Physician Referral note',''),
('http://loinc.org','83798-9','Physician Outpatient Note',''),
('http://loinc.org','83799-7','Physician Transplant candidate evaluation note','transplant'),
('http://loinc.org','83800-3','Physician Hospital Note',''),
('http://loinc.org','83801-1','Physician Patients home Note',''),
--('http://loinc.org','83802-9','Physician Discharge instructions',''),
--('http://loinc.org','83803-7','Physician Custodial care facility Note',''),
('http://loinc.org','83804-5','Physician Administrative note',''),
('http://loinc.org','83805-2','Physician Admission evaluation note',''),
('http://loinc.org','83815-1','Attending Surgical operation note','operation|surgical'),
--('http://loinc.org','83816-9','Attending Intensive care unit Admission evaluation note',''),
--('http://loinc.org','83817-7','Attending Intensive care unit Note',''),
('http://loinc.org','83818-5','Attending Emergency department Note',''),
('http://loinc.org','83819-3','Attending History and physical note',''),
('http://loinc.org','83820-1','Attending Preoperative evaluation and management note','operative'),
--('http://loinc.org','83821-9','Attending Outpatient Note',''),
--('http://loinc.org','83822-7','Attending Hospital Note',''),
--('http://loinc.org','83823-5','Attending Long term care facility Note',''),
--('http://loinc.org','83824-3','Attending Admission evaluation note',''),
--('http://loinc.org','83825-0','Fellow Note',''),
--('http://loinc.org','83826-8','Fellow Intensive care unit Admission evaluation note',''),
--('http://loinc.org','83827-6','Fellow Intensive care unit Note',''),
('http://loinc.org','83841-7','Transplant surgery Case manager Note','surgery|transplant'),
('http://loinc.org','83842-5','Surgery Interdisciplinary Note','surgery'),
('http://loinc.org','83843-3','Surgery Case manager Note','surgery'),
--('http://loinc.org','83872-2','Primary care Case manager Note',''),
--('http://loinc.org','83881-3','Psychiatry Case manager Note',''),
--('http://loinc.org','83882-1','Psychiatry Interdisciplinary Note',''),
--('http://loinc.org','83895-3','Psychiatry Interdisciplinary Plan of care note',''),
--('http://loinc.org','83925-8','Recreational therapy Interdisciplinary Note',''),
--('http://loinc.org','83951-4','Interdisciplinary Risk assessment and screening note',''),
('http://loinc.org','83954-8','Social worker Admission evaluation note','social work'),
('http://loinc.org','83955-5','Social worker Annual evaluation note','social work'),
('http://loinc.org','83956-3','Social worker Discharge summary','social work'),
('http://loinc.org','83957-1','Social worker Custodial care facility Note','social work'),
('http://loinc.org','83958-9','Social worker Emergency department Note','social work'),
('http://loinc.org','83959-7','Social worker History and physical note','social work'),
('http://loinc.org','83960-5','Social worker Patients home Consult note','social work'),
('http://loinc.org','83961-3','Social worker Patients home Discharge summary','social work'),
('http://loinc.org','83962-1','Social worker Patients home Initial evaluation note','social work'),
('http://loinc.org','83963-9','Social worker Patients home Note','social work'),
('http://loinc.org','83964-7','Social worker Patients home Referral note','social work'),
('http://loinc.org','83965-4','Social worker Hospital Note','social work'),
--('http://loinc.org','83967-0','Social worker Long term care facility Consult note','social work'),
--('http://loinc.org','83968-8','Social worker Long term care facility Discharge summary','social work'),
--('http://loinc.org','83969-6','Social worker Long term care facility Initial evaluation note','social work'),
--('http://loinc.org','83970-4','Social worker Long term care facility Note','social work'),
--('http://loinc.org','83971-2','Social worker Long term care facility Referral note','social work'),
--('http://loinc.org','83972-0','Social worker Long term care facility Respite note','social work'),
--('http://loinc.org','83973-8','Social worker Long term care facility Risk assessment and screening note','social work'),
('http://loinc.org','83975-3','Social worker Outpatient Group counseling note','social work'),
('http://loinc.org','83976-1','Social worker Outpatient Note','social work'),
('http://loinc.org','83977-9','Social worker Outreach note','social work'),
('http://loinc.org','83978-7','Social worker Respite note','social work'),
('http://loinc.org','83979-5','Social worker Risk assessment and screening note','social work'),
('http://loinc.org','83981-1','Social worker Transfer summary note','social work'),
('http://loinc.org','83982-9','Social worker Transplant candidate evaluation note','social work|transplant'),
--('http://loinc.org','84000-9','Spinal cord injury medicine Interdisciplinary Note',''),
--('http://loinc.org','84011-6','Spinal cord injury medicine Interdisciplinary Plan of care note',''),
('http://loinc.org','84043-9','Urology Interdisciplinary Note','urology'),
--('http://loinc.org','84084-3','Diabetology Case manager Note',''),
--('http://loinc.org','84111-4','Geriatric medicine Case manager Note',''),
--('http://loinc.org','84120-5','Geriatric medicine Pharmacist Note',''),
--('http://loinc.org','84124-7','Geriatric medicine Interdisciplinary Plan of care note',''),
--('http://loinc.org','84135-3','Primary care Interdisciplinary Patients home Plan of care note',''),
('http://loinc.org','84137-9','Hematology+Medical oncology Pharmacist Note','oncology'),
--('http://loinc.org','84163-5','Interdisciplinary Patients home Note',''),
--('http://loinc.org','84164-3','Interdisciplinary Patients home Plan of care note',''),
--('http://loinc.org','84172-6','Interdisciplinary Hospital Plan of care note',''),
--('http://loinc.org','84186-6','Interdisciplinary Long term care facility Note',''),
--('http://loinc.org','84187-4','Interdisciplinary Long term care facility Plan of care note',''),
--('http://loinc.org','84204-7','Mental health Interdisciplinary Note',''),
--('http://loinc.org','84217-9','Mental health Interdisciplinary Plan of care note',''),
--('http://loinc.org','84295-5','Nutrition and dietetics Interdisciplinary Plan of care note',''),
--('http://loinc.org','84314-4','Physical therapy Interdisciplinary Plan of care note',''),
--('http://loinc.org','84325-0','Physical therapy Interdisciplinary Note',''),
--('http://loinc.org','84354-0','Palliative care Pharmacist Note',''),
--('http://loinc.org','84361-5','Interdisciplinary Outpatient Note',''),
--('http://loinc.org','84403-5','Multi-specialty program Case manager Note',''),
--('http://loinc.org','84430-8','Occupational therapy Interdisciplinary Note',''),
--('http://loinc.org','85172-5','Case manager Custodial care facility Note',''),
--('http://loinc.org','85218-6','Internal medicine Attending Hospital Note',''),
('http://loinc.org','85222-8','Case manager Consult note',''),
('http://loinc.org','85223-6','Case manager Discharge summary',''),
--('http://loinc.org','85224-4','Case manager Long term care facility Note',''),
('http://loinc.org','85225-1','Case manager Outpatient Note',''),
('http://loinc.org','85226-9','Case manager Referral note',''),
('http://loinc.org','85227-7','Case manager Telephone encounter Note',''),
--('http://loinc.org','85228-5','Case manager Plan of care note',''),
--('http://loinc.org','85233-5','Internal medicine Attending Admission evaluation note',''),
--('http://loinc.org','85234-3','Internal medicine Attending Intensive care unit Admission evaluation note',''),
--('http://loinc.org','85235-0','Internal medicine Attending Intensive care unit Note',''),
--('http://loinc.org','85251-7','Internal medicine Resident Admission evaluation note',''),
--('http://loinc.org','85254-1','Internal medicine Interdisciplinary Plan of care note',''),
--('http://loinc.org','85256-6','Radiology Attending Note',''),
('http://loinc.org','85265-7','Internal medicine Pharmacist Medication management note',''),
--('http://loinc.org','85266-5','Internal medicine Interdisciplinary Note',''),
--('http://loinc.org','85851-4','Cardiothoracic surgery Interdisciplinary Note','surgery'),
--('http://loinc.org','85873-8','Physician Restraint note',''),
--('http://loinc.org','85891-0','Cardiothoracic surgery Fellow Note','surgery'),
--('http://loinc.org','85900-9','Cardiothoracic surgery Resident Note','surgery'),
('http://loinc.org','85948-8','Surgery Attending Preoperative evaluation and management note','operative|surgery'),
('http://loinc.org','86209-4','Community health care Case manager Note',''),
--('http://loinc.org','86210-2','Physician Medical clearance note',''),
--('http://loinc.org','86211-0','Addiction medicine Physician Note',''),
--('http://loinc.org','86212-8','Addiction medicine Attending Note',''),
--('http://loinc.org','87261-4','Addiction medicine Case manager Note',''),
('http://loinc.org','87265-5','Dialysis Interdisciplinary Plan of care note',''),
('http://loinc.org','87267-1','Dialysis Physician Note',''),
--('http://loinc.org','88350-4','Polytrauma Case manager Note',''),
--('http://loinc.org','89035-0','Sleep medicine Physician Note',''),
--('http://loinc.org','89441-0','Gynecology Resident Note',''),
--('http://loinc.org','89454-3','Obstetrics Attending Note',''),
--('http://loinc.org','89455-0','Gynecology Attending Note',''),
--('http://loinc.org','89456-8','Obstetrics Resident Note',''),
--('http://loinc.org','90342-7','Nuclear medicine Attending Note',''),
--('http://loinc.org','90348-4','Nuclear medicine Resident Note',''),
('http://loinc.org','90751-9','Social worker Adult day care center Note','social work'),
('http://loinc.org','90752-7','Community health care Social worker Note','social work'),
('http://loinc.org','90753-5','Multi-specialty program Social worker Note','social work'),
('http://loinc.org','90754-3','Mental health Social worker Note','social work'),
--('http://loinc.org','90755-0','Palliative care Social worker Long term care facility Note','social work'),
--('http://loinc.org','90756-8','Palliative care Social worker Note','social work'),
--('http://loinc.org','90757-6','Physical medicine and rehabilitation Social worker Hospital Note','social work'),
--('http://loinc.org','90758-4','Physical medicine and rehabilitation Social worker Outpatient hospital Note','social work'),
--('http://loinc.org','90759-2','Primary care Social worker Note','social work'),
--('http://loinc.org','90760-0','Addiction medicine Social worker Note','social work'),
--('http://loinc.org','90786-5','Dentistry Attending Note',''),
--('http://loinc.org','90787-3','Dentistry Resident Note',''),
--('http://loinc.org','90788-1','Optometry Resident Note',''),
--('http://loinc.org','90790-7','Podiatry Resident Note',''),
--('http://loinc.org','90791-5','Physical therapy Resident Note',''),
--('http://loinc.org','90792-3','Podiatry Attending Preoperative evaluation and management note','operative'),
--('http://loinc.org','90793-1','Podiatry Attending Note',''),
('http://loinc.org','91531-4','Social worker Telehealth Note','social work'),
('http://loinc.org','93023-0','Pharmacist Plan of care note',''),
('http://loinc.org','93024-8','Pharmacist Consult note',''),
('http://loinc.org','94807-5','Attending COVID-19 Intubation Consultation note',''),
('http://loinc.org','94808-3','Resident COVID-19 Intubation Consultation note',''),
('http://loinc.org','96332-2','Case manager Telehealth Note','')
) AS t (system,code,display,keyword) ;